window.pageShows = [
  {
    id: 5113,
    tvmazeId: '37139',
    title: 'Boss Cheer',
    network: 'YouTube',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Drama', 'Comedy', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/179/448925.jpg',
    note: '',
  },
  {
    id: 5114,
    tvmazeId: '63012',
    title: 'Breaking News: No Laugh Newsroom',
    network: 'Dropout',
    startYear: 2018,
    years: '2018–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/415/1039168.jpg',
    note: '',
  },
  {
    id: 5115,
    tvmazeId: '34269',
    title: 'Breathe',
    network: 'Prime Video',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/141/353518.jpg',
    note: '',
  },
  {
    id: 5116,
    tvmazeId: '19685',
    title: 'Britannia',
    network: 'Now',
    startYear: 2018,
    years: '2018–2021',
    genres: ['Drama', 'Fantasy', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/163/409168.jpg',
    note: '',
  },
  {
    id: 5117,
    tvmazeId: '36070',
    title: 'BroBot',
    network: 'YouTube',
    startYear: 2018,
    years: '2018',
    genres: ['Comedy', 'Family', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/232/582122.jpg',
    note: '',
  },
  {
    id: 5118,
    tvmazeId: '38563',
    title: 'Bronx SIU',
    network: 'ALLBLK',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Drama', 'Action', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/166/417120.jpg',
    note: '',
  },
  {
    id: 5119,
    tvmazeId: '59913',
    title: 'Buang Ruk Satan',
    network: 'Channel 3',
    startYear: 2018,
    years: '2018',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/389/972550.jpg',
    note: '',
  },
  {
    id: 5120,
    tvmazeId: '31477',
    title: 'Bulletproof',
    network: 'Now',
    startYear: 2018,
    years: '2018–2021',
    genres: ['Drama', 'Comedy', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/247/617968.jpg',
    note: '',
  },
  {
    id: 5121,
    tvmazeId: '28463',
    title: 'Burden of Truth',
    network: 'CBC',
    startYear: 2018,
    years: '2018–2021',
    genres: ['Drama', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/200/501565.jpg',
    note: '',
  },
  {
    id: 5122,
    tvmazeId: '40635',
    title: 'Butterbean\'s Café',
    network: 'Nick Jr.',
    startYear: 2018,
    years: '2018–2020',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/181/453983.jpg',
    note: '',
  },
  {
    id: 5123,
    tvmazeId: '32016',
    title: 'Butterfly',
    network: 'ITV1',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/295/739496.jpg',
    note: '',
  },
  {
    id: 5124,
    tvmazeId: '34817',
    title: 'Camping',
    network: 'HBO',
    startYear: 2018,
    years: '2018',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/484/1211056.jpg',
    note: '',
  },
  {
    id: 5125,
    tvmazeId: '39441',
    title: 'Carl Weber\'s The Family Business',
    network: 'BET+',
    startYear: 2018,
    years: '2018–',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/530/1326901.jpg',
    note: '',
  },
  {
    id: 5126,
    tvmazeId: '36119',
    title: 'Carter',
    network: 'CTV Drama Channel',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/217/543695.jpg',
    note: '',
  },
  {
    id: 5127,
    tvmazeId: '56687',
    title: 'Cartoon Hell',
    network: 'Dropout',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/345/864747.jpg',
    note: '',
  },
  {
    id: 5128,
    tvmazeId: '38161',
    title: 'Casey Tries His Best',
    network: 'Comedy Central',
    startYear: 2018,
    years: '2018',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/326/815512.jpg',
    note: '',
  },
  {
    id: 5129,
    tvmazeId: '57783',
    title: 'Castle & Castle',
    network: 'Netflix',
    startYear: 2018,
    years: '2018–2021',
    genres: ['Drama', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/359/898090.jpg',
    note: '',
  },
  {
    id: 5130,
    tvmazeId: '25414',
    title: 'Castle Rock',
    network: 'Hulu',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Drama', 'Horror', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/214/536992.jpg',
    note: '',
  },
  {
    id: 5131,
    tvmazeId: '17307',
    title: 'Caught',
    network: 'CBC',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/137/344415.jpg',
    note: '',
  },
  {
    id: 5132,
    tvmazeId: '39960',
    title: 'Champaign ILL',
    network: 'YouTube Premium',
    startYear: 2018,
    years: '2018',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/176/441322.jpg',
    note: '',
  },
  {
    id: 5133,
    tvmazeId: '28166',
    title: 'Champions',
    network: 'NBC',
    startYear: 2018,
    years: '2018',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/145/362707.jpg',
    note: '',
  },
  {
    id: 5134,
    tvmazeId: '24267',
    title: 'Charmed',
    network: 'The CW',
    startYear: 2018,
    years: '2018–2022',
    genres: ['Drama', 'Mystery', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/401/1003373.jpg',
    note: '',
  },
  {
    id: 5135,
    tvmazeId: '32649',
    title: 'Chilling Adventures of Sabrina',
    network: 'Netflix',
    startYear: 2018,
    years: '2018–2020',
    genres: ['Horror', 'Romance', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/291/728576.jpg',
    note: '',
  },
  {
    id: 5136,
    tvmazeId: '45251',
    title: 'Chip and Potato',
    network: 'Family Jr.',
    startYear: 2018,
    years: '2018–',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/228/571838.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 214, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
