window.pageShows = [
  {
    id: 14689,
    tvmazeId: '4792',
    title: 'Spitting Image',
    network: 'ITV1',
    startYear: 1984,
    years: '1984–1996',
    genres: ['Comedy', 'Adult'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/53255.jpg',
    note: '',
  },
  {
    id: 14690,
    tvmazeId: '24337',
    title: 'Strangers and Brothers',
    network: 'BBC Two',
    startYear: 1984,
    years: '1984',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/92/231471.jpg',
    note: '',
  },
  {
    id: 14691,
    tvmazeId: '12553',
    title: 'Super Friends: The Legendary Super Powers Show',
    network: 'ABC',
    startYear: 1984,
    years: '1984',
    genres: ['Family', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/252/631029.jpg',
    note: '',
  },
  {
    id: 14692,
    tvmazeId: '44325',
    title: 'Sweet and Sour',
    network: 'ABC',
    startYear: 1984,
    years: '1984',
    genres: ['Drama', 'Comedy', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/214/536861.jpg',
    note: '',
  },
  {
    id: 14693,
    tvmazeId: '3510',
    title: 'Tales from the Darkside',
    network: 'Syndication',
    startYear: 1984,
    years: '1984–1988',
    genres: ['Fantasy', 'Horror', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/46489.jpg',
    note: '',
  },
  {
    id: 14694,
    tvmazeId: '3255',
    title: 'The Adventures of Sherlock Holmes',
    network: 'ITV1',
    startYear: 1984,
    years: '1984–1994',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/501/1254452.jpg',
    note: '',
  },
  {
    id: 14695,
    tvmazeId: '5983',
    title: 'The Bill',
    network: 'ITV1',
    startYear: 1984,
    years: '1984–2010',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/59211.jpg',
    note: '',
  },
  {
    id: 14696,
    tvmazeId: '24152',
    title: 'The Box of Delights',
    network: 'BBC One',
    startYear: 1984,
    years: '1984',
    genres: ['Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/91/228920.jpg',
    note: '',
  },
  {
    id: 14697,
    tvmazeId: '51307',
    title: 'The Brief',
    network: 'ITV1',
    startYear: 1984,
    years: '1984',
    genres: ['Drama', 'Thriller', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/278/696183.jpg',
    note: '',
  },
  {
    id: 14698,
    tvmazeId: '84368',
    title: 'The ChuckleHounds',
    network: 'BBC One',
    startYear: 1984,
    years: '1984–1986',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/606/1515113.jpg',
    note: '',
  },
  {
    id: 14699,
    tvmazeId: '92008',
    title: 'The Clairvoyant',
    network: 'BBC Two',
    startYear: 1984,
    years: '1984–1986',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/625/1564215.jpg',
    note: '',
  },
  {
    id: 14700,
    tvmazeId: '2084',
    title: 'The Cosby Show',
    network: 'NBC',
    startYear: 1984,
    years: '1984–1992',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/313/782979.jpg',
    note: '',
  },
  {
    id: 14701,
    tvmazeId: '51334',
    title: 'The District Nurse',
    network: 'BBC One',
    startYear: 1984,
    years: '1984–1987',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/278/696630.jpg',
    note: '',
  },
  {
    id: 14702,
    tvmazeId: '25633',
    title: 'The Duck Factory',
    network: 'NBC',
    startYear: 1984,
    years: '1984',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/99/249676.jpg',
    note: '',
  },
  {
    id: 14703,
    tvmazeId: '16533',
    title: 'The Edison Twins',
    network: 'CBC',
    startYear: 1984,
    years: '1984–1986',
    genres: ['Drama', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/55/137752.jpg',
    note: '',
  },
  {
    id: 14704,
    tvmazeId: '30546',
    title: 'The Family-Ness',
    network: 'BBC One',
    startYear: 1984,
    years: '1984–1985',
    genres: ['Children', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/120/302190.jpg',
    note: '',
  },
  {
    id: 14705,
    tvmazeId: '28597',
    title: 'The Far Pavilions',
    network: 'HBO',
    startYear: 1984,
    years: '1984',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/113/284599.jpg',
    note: '',
  },
  {
    id: 14706,
    tvmazeId: '87924',
    title: 'The Front Line',
    network: 'BBC One',
    startYear: 1984,
    years: '1984–1985',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/597/1492844.jpg',
    note: '',
  },
  {
    id: 14707,
    tvmazeId: '39673',
    title: 'The Get Along Gang',
    network: 'CBS',
    startYear: 1984,
    years: '1984',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/174/435442.jpg',
    note: '',
  },
  {
    id: 14708,
    tvmazeId: '18404',
    title: 'The Glory Boys',
    network: 'ITV1',
    startYear: 1984,
    years: '1984',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/62/156450.jpg',
    note: '',
  },
  {
    id: 14709,
    tvmazeId: '21842',
    title: 'The Invisible Man',
    network: 'BBC One',
    startYear: 1984,
    years: '1984',
    genres: ['Drama', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/78/196767.jpg',
    note: '',
  },
  {
    id: 14710,
    tvmazeId: '3551',
    title: 'The Jewel in the Crown',
    network: 'ITV1',
    startYear: 1984,
    years: '1984',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/46681.jpg',
    note: '',
  },
  {
    id: 14711,
    tvmazeId: '61073',
    title: 'The Kit Curran Radio Show',
    network: 'ITV1',
    startYear: 1984,
    years: '1984–1986',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/400/1000115.jpg',
    note: '',
  },
  {
    id: 14712,
    tvmazeId: '20553',
    title: 'The Last Days of Pompeii',
    network: 'ABC',
    startYear: 1984,
    years: '1984',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/72/181725.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 613, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
