window.pageShows = [
  {
    id: 6433,
    tvmazeId: '6025',
    title: 'Lab Rats: Elite Force',
    network: 'Disney XD',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy', 'Action', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/43/108249.jpg',
    note: '',
  },
  {
    id: 6434,
    tvmazeId: '13323',
    title: 'Lady Dynamite',
    network: 'Netflix',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/134/336745.jpg',
    note: '',
  },
  {
    id: 6435,
    tvmazeId: '72208',
    title: 'Lamput',
    network: 'Cartoon Network',
    startYear: 2016,
    years: '2016',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/483/1208801.jpg',
    note: '',
  },
  {
    id: 6436,
    tvmazeId: '19014',
    title: 'Legendary Dudas',
    network: 'Nickelodeon',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/66/167298.jpg',
    note: '',
  },
  {
    id: 6437,
    tvmazeId: '19389',
    title: 'Legends of Chamberlain Heights',
    network: 'Comedy Central',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/326/816219.jpg',
    note: '',
  },
  {
    id: 6438,
    tvmazeId: '13748',
    title: 'LEGO Bionicle: The Journey to One',
    network: 'Netflix',
    startYear: 2016,
    years: '2016',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/140/350869.jpg',
    note: '',
  },
  {
    id: 6439,
    tvmazeId: '13749',
    title: 'LEGO Friends: The Power of Friendship',
    network: 'Netflix',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/153/384649.jpg',
    note: '',
  },
  {
    id: 6440,
    tvmazeId: '23559',
    title: 'LEGO Frozen Northern Lights',
    network: 'Disney Channel',
    startYear: 2016,
    years: '2016',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/88/220896.jpg',
    note: '',
  },
  {
    id: 6441,
    tvmazeId: '39928',
    title: 'LEGO Jurassic World: The Indominus Escape',
    network: 'YouTube',
    startYear: 2016,
    years: '2016',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/176/440472.jpg',
    note: '',
  },
  {
    id: 6442,
    tvmazeId: '12929',
    title: 'LEGO Star Wars: The Freemaker Adventures',
    network: 'Disney XD',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Comedy', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/318/795192.jpg',
    note: '',
  },
  {
    id: 6443,
    tvmazeId: '13045',
    title: 'LEGO Star Wars: The Resistance Rises',
    network: 'Disney XD',
    startYear: 2016,
    years: '2016',
    genres: ['Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/86/216301.jpg',
    note: '',
  },
  {
    id: 6444,
    tvmazeId: '18266',
    title: 'Lenny',
    network: 'YouTube',
    startYear: 2016,
    years: '2016',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 6445,
    tvmazeId: '16686',
    title: 'Let\'s Fight Ghost',
    network: 'tvN',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Comedy', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/65/163393.jpg',
    note: '',
  },
  {
    id: 6446,
    tvmazeId: '5495',
    title: 'Lethal Weapon',
    network: 'FOX',
    startYear: 2016,
    years: '2016–2019',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/168/421354.jpg',
    note: '',
  },
  {
    id: 6447,
    tvmazeId: '14055',
    title: 'Letterkenny',
    network: 'Crave',
    startYear: 2016,
    years: '2016–2023',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/436/1092299.jpg',
    note: '',
  },
  {
    id: 6448,
    tvmazeId: '28910',
    title: 'Life, After',
    network: 'Vimeo',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/115/288060.jpg',
    note: '',
  },
  {
    id: 6449,
    tvmazeId: '80828',
    title: 'Lifetime Ripped From the Headlines',
    network: 'Lifetime',
    startYear: 2016,
    years: '2016–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/606/1516181.jpg',
    note: '',
  },
  {
    id: 6450,
    tvmazeId: '22029',
    title: 'Little Big Awesome',
    network: 'Prime Video',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/228/570052.jpg',
    note: '',
  },
  {
    id: 6451,
    tvmazeId: '73367',
    title: 'Little People',
    network: 'Universal Kids',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Comedy', 'Children', 'Music'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/492/1231469.jpg',
    note: '',
  },
  {
    id: 6452,
    tvmazeId: '22396',
    title: 'Little Roy',
    network: 'CBBC',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/256/640865.jpg',
    note: '',
  },
  {
    id: 6453,
    tvmazeId: '39119',
    title: 'Little Things',
    network: 'Netflix',
    startYear: 2016,
    years: '2016–2021',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/171/429038.jpg',
    note: '',
  },
  {
    id: 6454,
    tvmazeId: '17367',
    title: 'Lonely and Horny',
    network: 'Vimeo',
    startYear: 2016,
    years: '2016–2019',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/58/146465.jpg',
    note: '',
  },
  {
    id: 6455,
    tvmazeId: '15943',
    title: 'Looped',
    network: 'Cartoon Network',
    startYear: 2016,
    years: '2016',
    genres: ['Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/121/304608.jpg',
    note: '',
  },
  {
    id: 6456,
    tvmazeId: '19700',
    title: 'Loosely Exactly Nicole',
    network: 'Facebook Watch',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/69/174215.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 269, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
