window.pageShows = [
  {
    id: 1393,
    tvmazeId: '74570',
    title: 'The Believers',
    network: 'Netflix',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/601/1504587.jpg',
    note: '',
  },
  {
    id: 1394,
    tvmazeId: '64736',
    title: 'The Bequeathed',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/495/1239697.jpg',
    note: '',
  },
  {
    id: 1395,
    tvmazeId: '61502',
    title: 'The Big Cigar',
    network: 'Apple TV',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/516/1290672.jpg',
    note: '',
  },
  {
    id: 1396,
    tvmazeId: '79177',
    title: 'The Boy That Never Was',
    network: 'RTÉ ONE',
    startYear: 2024,
    years: '2024',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/532/1332414.jpg',
    note: '',
  },
  {
    id: 1397,
    tvmazeId: '74925',
    title: 'The Boy, the Queen and Everything in Between',
    network: 'TVNZ+',
    startYear: 2024,
    years: '2024',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/586/1466127.jpg',
    note: '',
  },
  {
    id: 1398,
    tvmazeId: '60515',
    title: 'The Brothers Sun',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/485/1214331.jpg',
    note: '',
  },
  {
    id: 1399,
    tvmazeId: '79962',
    title: 'The Charlie Puth Show',
    network: 'The Roku Channel',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy', 'Music'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/538/1345108.jpg',
    note: '',
  },
  {
    id: 1400,
    tvmazeId: '78125',
    title: 'The Chicken Sisters',
    network: 'Hallmark Channel',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy', 'Family', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/582/1455566.jpg',
    note: '',
  },
  {
    id: 1401,
    tvmazeId: '74067',
    title: 'The Completely Made-Up Adventures of Dick Turpin',
    network: 'Apple TV',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/593/1484793.jpg',
    note: '',
  },
  {
    id: 1402,
    tvmazeId: '77574',
    title: 'The Creep Tapes',
    network: 'Shudder',
    startYear: 2024,
    years: '2024–',
    genres: ['Horror'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/598/1495808.jpg',
    note: '',
  },
  {
    id: 1403,
    tvmazeId: '75640',
    title: 'The Cuckoo',
    network: '5',
    startYear: 2024,
    years: '2024',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/512/1281522.jpg',
    note: '',
  },
  {
    id: 1404,
    tvmazeId: '80536',
    title: 'The Darkness',
    network: 'SkyShowtime',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/541/1354590.jpg',
    note: '',
  },
  {
    id: 1405,
    tvmazeId: '64977',
    title: 'The Day of the Jackal',
    network: 'Now',
    startYear: 2024,
    years: '2024–',
    genres: ['Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/541/1352923.jpg',
    note: '',
  },
  {
    id: 1406,
    tvmazeId: '63596',
    title: 'The Decameron',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/528/1321861.jpg',
    note: '',
  },
  {
    id: 1407,
    tvmazeId: '80182',
    title: 'The Edge of Sleep',
    network: 'Prime Video',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/539/1348779.jpg',
    note: '',
  },
  {
    id: 1408,
    tvmazeId: '77516',
    title: 'The Faceless Lady',
    network: 'YouTube',
    startYear: 2024,
    years: '2024–',
    genres: ['Horror', 'Supernatural'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/522/1305016.jpg',
    note: '',
  },
  {
    id: 1409,
    tvmazeId: '74880',
    title: 'The Fairly OddParents! A New Wish',
    network: 'Nickelodeon',
    startYear: 2024,
    years: '2024',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/548/1370855.jpg',
    note: '',
  },
  {
    id: 1410,
    tvmazeId: '63438',
    title: 'The Franchise',
    network: 'HBO',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/538/1345331.jpg',
    note: '',
  },
  {
    id: 1411,
    tvmazeId: '67107',
    title: 'The Frog',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Crime', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/530/1326830.jpg',
    note: '',
  },
  {
    id: 1412,
    tvmazeId: '70235',
    title: 'The Gathering',
    network: 'Channel 4',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/514/1286155.jpg',
    note: '',
  },
  {
    id: 1413,
    tvmazeId: '64992',
    title: 'The Gentlemen',
    network: 'Netflix',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy', 'Action', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/507/1269103.jpg',
    note: '',
  },
  {
    id: 1414,
    tvmazeId: '43568',
    title: 'The Girls on the Bus',
    network: 'HBO Max',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/510/1276534.jpg',
    note: '',
  },
  {
    id: 1415,
    tvmazeId: '76554',
    title: 'The Green Veil',
    network: 'The Network',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/518/1297308.jpg',
    note: '',
  },
  {
    id: 1416,
    tvmazeId: '80410',
    title: 'The Groomsmen',
    network: 'Hallmark+',
    startYear: 2024,
    years: '2024–',
    genres: ['Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/548/1371335.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 59, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
