window.pageShows = [
  {
    id: 1081,
    tvmazeId: '54828',
    title: 'Extraordinary',
    network: 'Disney+',
    startYear: 2023,
    years: '2023–2024',
    genres: ['Comedy', 'Science-Fiction', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/506/1265226.jpg',
    note: '',
  },
  {
    id: 1082,
    tvmazeId: '58431',
    title: 'Extrapolations',
    network: 'Apple TV',
    startYear: 2023,
    years: '2023',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/452/1130038.jpg',
    note: '',
  },
  {
    id: 1083,
    tvmazeId: '66540',
    title: 'Family History Mysteries checkifcancelled',
    network: 'Hallmark Mystery',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/442/1106944.jpg',
    note: '',
  },
  {
    id: 1084,
    tvmazeId: '63511',
    title: 'Far North',
    network: 'ThreeNow',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/472/1181810.jpg',
    note: '',
  },
  {
    id: 1085,
    tvmazeId: '66652',
    title: 'Faraway Downs',
    network: 'Hulu',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/488/1221134.jpg',
    note: '',
  },
  {
    id: 1086,
    tvmazeId: '58938',
    title: 'Fatal Attraction',
    network: 'Paramount+',
    startYear: 2023,
    years: '2023',
    genres: ['Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/459/1148341.jpg',
    note: '',
  },
  {
    id: 1087,
    tvmazeId: '69144',
    title: 'Fatal Seduction checkifcancelled',
    network: 'Netflix',
    startYear: 2023,
    years: '2023–',
    genres: ['Crime', 'Thriller', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/467/1169882.jpg',
    note: '',
  },
  {
    id: 1088,
    tvmazeId: '61735',
    title: 'Fellow Travelers',
    network: 'Paramount+',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Romance', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/485/1213419.jpg',
    note: '',
  },
  {
    id: 1089,
    tvmazeId: '63911',
    title: 'Fifteen-Love',
    network: 'Prime Video',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/488/1222365.jpg',
    note: '',
  },
  {
    id: 1090,
    tvmazeId: '53474',
    title: 'Fired on Mars',
    network: 'HBO Max',
    startYear: 2023,
    years: '2023–',
    genres: ['Comedy', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Max removed and cancelled the series after one season, leaving the Mars colony satire mid-story.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/458/1145720.jpg',
    note: '',
  },
  {
    id: 1091,
    tvmazeId: '54841',
    title: 'Florida Man',
    network: 'Netflix',
    startYear: 2023,
    years: '2023',
    genres: ['Crime', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/457/1142673.jpg',
    note: '',
  },
  {
    id: 1092,
    tvmazeId: '68901',
    title: 'For Her Sins',
    network: '5',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/463/1158760.jpg',
    note: '',
  },
  {
    id: 1093,
    tvmazeId: '59956',
    title: 'Found',
    network: 'NBC',
    startYear: 2023,
    years: '2023–2025',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/537/1343373.jpg',
    note: '',
  },
  {
    id: 1094,
    tvmazeId: '53775',
    title: 'Frasier',
    network: 'Paramount+',
    startYear: 2023,
    years: '2023–2024',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/535/1339506.jpg',
    note: '',
  },
  {
    id: 1095,
    tvmazeId: '60524',
    title: 'Freeridge',
    network: 'Netflix',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Comedy', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/443/1109723.jpg',
    note: '',
  },
  {
    id: 1096,
    tvmazeId: '70352',
    title: 'Fright Krewe',
    network: 'Hulu',
    startYear: 2023,
    years: '2023–2024',
    genres: ['Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/479/1198652.jpg',
    note: '',
  },
  {
    id: 1097,
    tvmazeId: '66660',
    title: 'Frog and Toad checkifcancelled',
    network: 'Apple TV',
    startYear: 2023,
    years: '2023–',
    genres: ['Children'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/458/1145477.jpg',
    note: '',
  },
  {
    id: 1098,
    tvmazeId: '69766',
    title: 'From Shakespeare\'s Globe',
    network: 'BBC Four',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 1099,
    tvmazeId: '65953',
    title: 'FUBAR',
    network: 'Netflix',
    startYear: 2023,
    years: '2023–2025',
    genres: ['Comedy', 'Action', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/565/1414236.jpg',
    note: '',
  },
  {
    id: 1100,
    tvmazeId: '57103',
    title: 'Full Circle',
    network: 'HBO Max',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/488/1220544.jpg',
    note: '',
  },
  {
    id: 1101,
    tvmazeId: '80488',
    title: 'Funday Football',
    network: 'Disney+',
    startYear: 2023,
    years: '2023–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/596/1490557.jpg',
    note: '',
  },
  {
    id: 1102,
    tvmazeId: '81258',
    title: 'Funny Little Monsters',
    network: 'rtéjr',
    startYear: 2023,
    years: '2023–',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/546/1365873.jpg',
    note: '',
  },
  {
    id: 1103,
    tvmazeId: '57325',
    title: 'Funny Woman checkifcancelled',
    network: 'Now',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/535/1337981.jpg',
    note: '',
  },
  {
    id: 1104,
    tvmazeId: '62998',
    title: 'Gen V',
    network: 'Prime Video',
    startYear: 2023,
    years: '2023–2025',
    genres: ['Comedy', 'Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/587/1469203.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 46, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 824, "cliffhanger": 237, "ended": 13574}};
