window.pageShows = [
  {
    id: 6601,
    tvmazeId: '9440',
    title: 'Signal',
    network: 'tvN',
    startYear: 2016,
    years: '2016–',
    genres: ['Crime', 'Thriller', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/139/349655.jpg',
    note: '',
  },
  {
    id: 6602,
    tvmazeId: '17649',
    title: 'Sing It!',
    network: 'YouTube Premium',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/89/223663.jpg',
    note: '',
  },
  {
    id: 6603,
    tvmazeId: '19854',
    title: 'Single by 30',
    network: 'YouTube Premium',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/70/175455.jpg',
    note: '',
  },
  {
    id: 6604,
    tvmazeId: '22013',
    title: 'Skylanders Academy',
    network: 'Netflix',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Comedy', 'Adventure', 'Fantasy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/130/325476.jpg',
    note: '',
  },
  {
    id: 6605,
    tvmazeId: '7019',
    title: 'Slasher',
    network: 'Shudder',
    startYear: 2016,
    years: '2016–2023',
    genres: ['Horror', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/455/1138494.jpg',
    note: '',
  },
  {
    id: 6606,
    tvmazeId: '44368',
    title: 'Sleep Tight',
    network: 'go90',
    startYear: 2016,
    years: '2016',
    genres: ['Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/214/537127.jpg',
    note: '',
  },
  {
    id: 6607,
    tvmazeId: '20781',
    title: 'Smalltown',
    network: 'Virgin Media One',
    startYear: 2016,
    years: '2016',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/183845.jpg',
    note: '',
  },
  {
    id: 6608,
    tvmazeId: '42851',
    title: 'Smart Guys',
    network: 'Prime Video',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/203/509890.jpg',
    note: '',
  },
  {
    id: 6609,
    tvmazeId: '40281',
    title: 'Solo',
    network: 'Prime Video',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Drama', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/179/447973.jpg',
    note: '',
  },
  {
    id: 6610,
    tvmazeId: '21464',
    title: 'Something About 1%',
    network: 'DramaX',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/76/190857.jpg',
    note: '',
  },
  {
    id: 6611,
    tvmazeId: '8097',
    title: 'Son of Zorn',
    network: 'FOX',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/74/185531.jpg',
    note: '',
  },
  {
    id: 6612,
    tvmazeId: '23185',
    title: 'Sonnigsburg',
    network: 'C31',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Mystery', 'Supernatural'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/89/223446.jpg',
    note: '',
  },
  {
    id: 6613,
    tvmazeId: '26646',
    title: 'Sorjonen',
    network: 'Yle TV1',
    startYear: 2016,
    years: '2016–2021',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/104/262061.jpg',
    note: '',
  },
  {
    id: 6614,
    tvmazeId: '20643',
    title: 'Sotus: The Series',
    network: 'One31',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/72/182483.jpg',
    note: '',
  },
  {
    id: 6615,
    tvmazeId: '76272',
    title: 'SpacePOP',
    network: 'YouTube',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Family', 'Fantasy', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/515/1288242.jpg',
    note: '',
  },
  {
    id: 6616,
    tvmazeId: '11553',
    title: 'Speechless',
    network: 'ABC',
    startYear: 2016,
    years: '2016–2019',
    genres: ['Comedy', 'Family'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/138/346144.jpg',
    note: '',
  },
  {
    id: 6617,
    tvmazeId: '23075',
    title: 'Splash and Bubbles',
    network: 'PBS',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Adventure', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/85/214897.jpg',
    note: '',
  },
  {
    id: 6618,
    tvmazeId: '13739',
    title: 'Spot Bots',
    network: 'CBeebies',
    startYear: 2016,
    years: '2016',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/47/118709.jpg',
    note: '',
  },
  {
    id: 6619,
    tvmazeId: '16484',
    title: 'Spot Bots Zoople Time',
    network: 'CBeebies',
    startYear: 2016,
    years: '2016',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 6620,
    tvmazeId: '13103',
    title: 'Stag',
    network: 'BBC Two',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/49/124419.jpg',
    note: '',
  },
  {
    id: 6621,
    tvmazeId: '16020',
    title: 'Stan Against Evil',
    network: 'IFC',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Comedy', 'Action', 'Horror'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/131/327936.jpg',
    note: '',
  },
  {
    id: 6622,
    tvmazeId: '6775',
    title: 'Stan Lee\'s Lucky Man',
    network: 'Sky Showcase',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Drama', 'Crime', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/161/404649.jpg',
    note: '',
  },
  {
    id: 6623,
    tvmazeId: '2746',
    title: 'Star',
    network: 'FOX',
    startYear: 2016,
    years: '2016–2019',
    genres: ['Drama', 'Music'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/88/222182.jpg',
    note: '',
  },
  {
    id: 6624,
    tvmazeId: '33577',
    title: 'Star Wars: Go Rogue',
    network: 'YouTube',
    startYear: 2016,
    years: '2016',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/208/520744.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 276, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
