window.pageShows = [
  {
    id: 11113,
    tvmazeId: '1094',
    title: 'Dinotopia',
    network: 'ABC',
    startYear: 2002,
    years: '2002–2003',
    genres: ['Adventure', 'Family', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/65437.jpg',
    note: '',
  },
  {
    id: 11114,
    tvmazeId: '6949',
    title: 'Dinotopia',
    network: 'ABC',
    startYear: 2002,
    years: '2002',
    genres: ['Adventure', 'Family', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/614/1536891.jpg',
    note: '',
  },
  {
    id: 11115,
    tvmazeId: '4692',
    title: 'Do Over',
    network: 'The WB',
    startYear: 2002,
    years: '2002',
    genres: ['Drama', 'Comedy', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/52870.jpg',
    note: '',
  },
  {
    id: 11116,
    tvmazeId: '46893',
    title: 'Doctor Who: Real Time',
    network: 'BBC Doctor Who Webcast',
    startYear: 2002,
    years: '2002',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/248/620352.jpg',
    note: '',
  },
  {
    id: 11117,
    tvmazeId: '27627',
    title: 'Doctor Zhivago',
    network: 'ITV1',
    startYear: 2002,
    years: '2002',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/108/272236.jpg',
    note: '',
  },
  {
    id: 11118,
    tvmazeId: '21265',
    title: 'Don\'t Blame the Koalas',
    network: '5',
    startYear: 2002,
    years: '2002–2003',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/75/187608.jpg',
    note: '',
  },
  {
    id: 11119,
    tvmazeId: '28123',
    title: 'Doodlez',
    network: 'Nicktoons',
    startYear: 2002,
    years: '2002–2003',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/111/278208.jpg',
    note: '',
  },
  {
    id: 11120,
    tvmazeId: '23208',
    title: 'Dossa and Joe',
    network: 'BBC Two',
    startYear: 2002,
    years: '2002',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11121,
    tvmazeId: '8811',
    title: 'Duel Masters',
    network: 'TV Tokyo',
    startYear: 2002,
    years: '2002–',
    genres: ['Comedy', 'Action', 'Adventure', 'Anime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/253/634523.jpg',
    note: '',
  },
  {
    id: 11122,
    tvmazeId: '9525',
    title: 'E Street',
    network: 'Network 10',
    startYear: 2002,
    years: '2002–2003',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/83364.jpg',
    note: '',
  },
  {
    id: 11123,
    tvmazeId: '48663',
    title: 'Engie Benjy',
    network: 'ITV1',
    startYear: 2002,
    years: '2002–2004',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/262/655314.jpg',
    note: '',
  },
  {
    id: 11124,
    tvmazeId: '440',
    title: 'Everwood',
    network: 'The WB',
    startYear: 2002,
    years: '2002–2006',
    genres: ['Drama', 'Family', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/81/204375.jpg',
    note: '',
  },
  {
    id: 11125,
    tvmazeId: '7130',
    title: 'Family Affair',
    network: 'The WB',
    startYear: 2002,
    years: '2002–2003',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/66641.jpg',
    note: '',
  },
  {
    id: 11126,
    tvmazeId: '1920',
    title: 'Fastlane',
    network: 'FOX',
    startYear: 2002,
    years: '2002–2003',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/258/646821.jpg',
    note: '',
  },
  {
    id: 11127,
    tvmazeId: '17996',
    title: 'Fillmore!',
    network: 'Disney XD',
    startYear: 2002,
    years: '2002–2004',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/61/152581.jpg',
    note: '',
  },
  {
    id: 11128,
    tvmazeId: '180',
    title: 'Firefly',
    network: 'FOX',
    startYear: 2002,
    years: '2002',
    genres: ['Drama', 'Adventure', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Fox cancelled after one season with the crew\'s stories and the Alliance conspiracy unresolved. The film Serenity provided some closure but killed key characters.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/1/2600.jpg',
    note: '',
  },
  {
    id: 11129,
    tvmazeId: '32341',
    title: 'Firestarter: Rekindled',
    network: 'Syfy',
    startYear: 2002,
    years: '2002',
    genres: ['Action', 'Science-Fiction', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/129/323155.jpg',
    note: '',
  },
  {
    id: 11130,
    tvmazeId: '17710',
    title: 'First Monday',
    network: 'CBS',
    startYear: 2002,
    years: '2002',
    genres: ['Drama', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/59/149006.jpg',
    note: '',
  },
  {
    id: 11131,
    tvmazeId: '8083',
    title: 'First Touch',
    network: 'Channel 5',
    startYear: 2002,
    years: '2002–2003',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/73534.jpg',
    note: '',
  },
  {
    id: 11132,
    tvmazeId: '6551',
    title: 'Footballers\' Wives',
    network: 'ITV1',
    startYear: 2002,
    years: '2002–2006',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/432/1081025.jpg',
    note: '',
  },
  {
    id: 11133,
    tvmazeId: '79702',
    title: 'For the People',
    network: 'Lifetime',
    startYear: 2002,
    years: '2002–2003',
    genres: ['Drama', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/536/1341172.jpg',
    note: '',
  },
  {
    id: 11134,
    tvmazeId: '1272',
    title: 'Foyle\'s War',
    network: 'ITV1',
    startYear: 2002,
    years: '2002–2015',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/18354.jpg',
    note: '',
  },
  {
    id: 11135,
    tvmazeId: '19267',
    title: 'Galidor: Defenders of the Outer Dimension',
    network: 'FOX',
    startYear: 2002,
    years: '2002',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/67/169114.jpg',
    note: '',
  },
  {
    id: 11136,
    tvmazeId: '4129',
    title: 'George Lopez',
    network: 'ABC',
    startYear: 2002,
    years: '2002–2007',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/50007.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 464, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
