window.pageShows = [
  {
    id: 2041,
    tvmazeId: '61198',
    title: 'Slip',
    network: 'The Roku Channel',
    startYear: 2023,
    years: '2023',
    genres: ['Comedy', 'Romance', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/458/1145741.jpg',
    note: '',
  },
  {
    id: 2042,
    tvmazeId: '72513',
    title: 'Smothered',
    network: 'Now',
    startYear: 2023,
    years: '2023',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/487/1218339.jpg',
    note: '',
  },
  {
    id: 2043,
    tvmazeId: '54336',
    title: 'Something Undone',
    network: 'CBC Gem',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/516/1291684.jpg',
    note: '',
  },
  {
    id: 2044,
    tvmazeId: '66493',
    title: 'Song of the Bandits',
    network: 'Netflix',
    startYear: 2023,
    years: '2023',
    genres: ['Action', 'Romance', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/474/1185406.jpg',
    note: '',
  },
  {
    id: 2045,
    tvmazeId: '66599',
    title: 'Sono Lillo',
    network: 'Prime Video',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/443/1108396.jpg',
    note: '',
  },
  {
    id: 2046,
    tvmazeId: '70515',
    title: 'Spellbound',
    network: 'Hulu',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Family', 'Fantasy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/538/1347282.jpg',
    note: '',
  },
  {
    id: 2047,
    tvmazeId: '66134',
    title: 'SpongeBob SquarePants Presents The Tidal Zone',
    network: 'Nickelodeon',
    startYear: 2023,
    years: '2023',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/441/1103835.jpg',
    note: '',
  },
  {
    id: 2048,
    tvmazeId: '71916',
    title: 'Spooky Files',
    network: 'ABC iview',
    startYear: 2023,
    years: '2023–',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/482/1206886.jpg',
    note: '',
  },
  {
    id: 2049,
    tvmazeId: '68223',
    title: 'Spy/Master',
    network: 'HBO Max',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Thriller', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/464/1161741.jpg',
    note: '',
  },
  {
    id: 2050,
    tvmazeId: '71090',
    title: 'Star Trek: very Short Treks',
    network: 'YouTube',
    startYear: 2023,
    years: '2023',
    genres: ['Comedy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/477/1192815.jpg',
    note: '',
  },
  {
    id: 2051,
    tvmazeId: '62296',
    title: 'Star Wars: Young Jedi Adventures',
    network: 'Disney+',
    startYear: 2023,
    years: '2023–2025',
    genres: ['Adventure', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/602/1505795.jpg',
    note: '',
  },
  {
    id: 2052,
    tvmazeId: '69462',
    title: 'Stay',
    network: 'YouTube',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/466/1165230.jpg',
    note: '',
  },
  {
    id: 2053,
    tvmazeId: '69432',
    title: 'Stay with Me',
    network: 'GagaOOLala',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Family', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/466/1165002.jpg',
    note: '',
  },
  {
    id: 2054,
    tvmazeId: '66721',
    title: 'Steeltown Murders',
    network: 'BBC iPlayer',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/463/1158155.jpg',
    note: '',
  },
  {
    id: 2055,
    tvmazeId: '66601',
    title: 'Still Up',
    network: 'Apple TV',
    startYear: 2023,
    years: '2023',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/476/1191884.jpg',
    note: '',
  },
  {
    id: 2056,
    tvmazeId: '61295',
    title: 'Stonehouse',
    network: 'ITV1',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/439/1098730.jpg',
    note: '',
  },
  {
    id: 2057,
    tvmazeId: '56075',
    title: 'Strange Planet',
    network: 'Apple TV',
    startYear: 2023,
    years: '2023',
    genres: ['Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/471/1179675.jpg',
    note: '',
  },
  {
    id: 2058,
    tvmazeId: '71364',
    title: 'Strawberry Shortcake Specials',
    network: 'Netflix',
    startYear: 2023,
    years: '2023–2024',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/512/1282046.jpg',
    note: '',
  },
  {
    id: 2059,
    tvmazeId: '72240',
    title: 'Strife',
    network: 'Binge',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/568/1421817.jpg',
    note: '',
  },
  {
    id: 2060,
    tvmazeId: '71383',
    title: 'Suburræterna',
    network: 'Netflix',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/486/1216416.jpg',
    note: '',
  },
  {
    id: 2061,
    tvmazeId: '72410',
    title: 'Such Brave Girls',
    network: 'BBC iPlayer',
    startYear: 2023,
    years: '2023–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/576/1441947.jpg',
    note: '',
  },
  {
    id: 2062,
    tvmazeId: '67268',
    title: 'Sullivan\'s Crossing',
    network: 'CTV',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/617/1543656.jpg',
    note: '',
  },
  {
    id: 2063,
    tvmazeId: '70107',
    title: 'Sunshine Eyes',
    network: 'Netflix',
    startYear: 2023,
    years: '2023',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/470/1175912.jpg',
    note: '',
  },
  {
    id: 2064,
    tvmazeId: '41804',
    title: 'Supa Team 4',
    network: 'Netflix',
    startYear: 2023,
    years: '2023',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/469/1173644.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 86, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
