window.pageShows = [
  {
    id: 4417,
    tvmazeId: '43313',
    title: 'Am I the Only One with Butterflies?',
    network: 'Vimeo',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/415/1038996.jpg',
    note: '',
  },
  {
    id: 4418,
    tvmazeId: '42528',
    title: 'Ambitions',
    network: 'Oprah Winfrey Network',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/201/503873.jpg',
    note: '',
  },
  {
    id: 4419,
    tvmazeId: '31075',
    title: 'American Princess',
    network: 'Lifetime',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/221/554243.jpg',
    note: '',
  },
  {
    id: 4420,
    tvmazeId: '40328',
    title: 'American Soul',
    network: 'BET',
    startYear: 2019,
    years: '2019–2020',
    genres: ['Drama', 'Music', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/259/649254.jpg',
    note: '',
  },
  {
    id: 4421,
    tvmazeId: '35072',
    title: 'Amphibia',
    network: 'Disney Channel',
    startYear: 2019,
    years: '2019–2022',
    genres: ['Comedy', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: 'Disney Channel gave the series a proper finale, concluding Anne and the Plantar family\'s adventure fully.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/344/861126.jpg',
    note: '',
  },
  {
    id: 4422,
    tvmazeId: '46414',
    title: 'Andy\'s Wild Workouts',
    network: 'CBeebies',
    startYear: 2019,
    years: '2019',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/246/617053.jpg',
    note: '',
  },
  {
    id: 4423,
    tvmazeId: '36471',
    title: 'Another Life',
    network: 'Netflix',
    startYear: 2019,
    years: '2019–2021',
    genres: ['Drama', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Netflix cancelled after two seasons with the alien contact storyline and Niko\'s mission left completely open.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/361/903008.jpg',
    note: '',
  },
  {
    id: 4424,
    tvmazeId: '43494',
    title: 'Apache: La vida de Carlos Tevez',
    network: 'Netflix',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/208/521989.jpg',
    note: '',
  },
  {
    id: 4425,
    tvmazeId: '43718',
    title: 'Archibald\'s Next Big Thing',
    network: 'Netflix',
    startYear: 2019,
    years: '2019–2020',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/210/525474.jpg',
    note: '',
  },
  {
    id: 4426,
    tvmazeId: '43830',
    title: 'Are You Afraid of the Dark?',
    network: 'Nickelodeon',
    startYear: 2019,
    years: '2019–2022',
    genres: ['Horror', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/494/1235412.jpg',
    note: '',
  },
  {
    id: 4427,
    tvmazeId: '46972',
    title: 'Astrid et Raphaëlle',
    network: 'France 2',
    startYear: 2019,
    years: '2019–',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/628/1572100.jpg',
    note: '',
  },
  {
    id: 4428,
    tvmazeId: '45144',
    title: 'Atiye',
    network: 'Netflix',
    startYear: 2019,
    years: '2019–2021',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/233/582811.jpg',
    note: '',
  },
  {
    id: 4429,
    tvmazeId: '51428',
    title: 'Aussie Girl',
    network: '9Now',
    startYear: 2019,
    years: '2019',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/279/698215.jpg',
    note: '',
  },
  {
    id: 4430,
    tvmazeId: '44517',
    title: 'Azize',
    network: 'Kanal D',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Crime', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/551/1379344.jpg',
    note: '',
  },
  {
    id: 4431,
    tvmazeId: '41790',
    title: 'Back to Life',
    network: 'BBC Three',
    startYear: 2019,
    years: '2019–2021',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/194/485261.jpg',
    note: '',
  },
  {
    id: 4432,
    tvmazeId: '40300',
    title: 'Bad Mothers',
    network: 'Nine Network',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/181/454101.jpg',
    note: '',
  },
  {
    id: 4433,
    tvmazeId: '48481',
    title: 'Bajillionaires',
    network: 'Family Channel',
    startYear: 2019,
    years: '2019',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/260/651451.jpg',
    note: '',
  },
  {
    id: 4434,
    tvmazeId: '36005',
    title: 'Baptiste',
    network: 'BBC iPlayer',
    startYear: 2019,
    years: '2019–2021',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/187/468518.jpg',
    note: '',
  },
  {
    id: 4435,
    tvmazeId: '43513',
    title: 'Bard of Blood',
    network: 'Netflix',
    startYear: 2019,
    years: '2019',
    genres: ['Action', 'Thriller', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/212/531130.jpg',
    note: '',
  },
  {
    id: 4436,
    tvmazeId: '37776',
    title: 'Batwoman',
    network: 'The CW',
    startYear: 2019,
    years: '2019–2022',
    genres: ['Drama', 'Crime', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'CW cancelled after three seasons; Ryan Wilder\'s Gotham and the Joker\'s device storyline were unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/361/903721.jpg',
    note: '',
  },
  {
    id: 4437,
    tvmazeId: '41295',
    title: 'Be Melodramatic',
    network: 'jTBC',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/206/516065.jpg',
    note: '',
  },
  {
    id: 4438,
    tvmazeId: '35515',
    title: 'Beecham House',
    network: 'ITV1',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/202/506556.jpg',
    note: '',
  },
  {
    id: 4439,
    tvmazeId: '37671',
    title: 'Beforeigners',
    network: 'HBO Max',
    startYear: 2019,
    years: '2019–2022',
    genres: ['Drama', 'Crime', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/446/1117266.jpg',
    note: '',
  },
  {
    id: 4440,
    tvmazeId: '63653',
    title: 'Best Bugs Forever',
    network: 'Disney Channel',
    startYear: 2019,
    years: '2019',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/419/1048806.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 185, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
