window.pageShows = [
  {
    id: 8665,
    tvmazeId: '12297',
    title: 'Let\'s Stay Together',
    network: 'BET',
    startYear: 2011,
    years: '2011–2014',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/41/104424.jpg',
    note: '',
  },
  {
    id: 8666,
    tvmazeId: '9307',
    title: 'Life with Boys',
    network: 'YTV',
    startYear: 2011,
    years: '2011–2013',
    genres: ['Comedy', 'Family'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/32/81884.jpg',
    note: '',
  },
  {
    id: 8667,
    tvmazeId: '423',
    title: 'Life\'s Too Short',
    network: 'BBC Two',
    startYear: 2011,
    years: '2011–2013',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/2/7335.jpg',
    note: '',
  },
  {
    id: 8668,
    tvmazeId: '1025',
    title: 'Lights Out',
    network: 'FX',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Crime', 'Sports'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16691.jpg',
    note: '',
  },
  {
    id: 8669,
    tvmazeId: '27374',
    title: 'Little Charley Bear',
    network: 'CBeebies',
    startYear: 2011,
    years: '2011–2012',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/107/269838.jpg',
    note: '',
  },
  {
    id: 8670,
    tvmazeId: '5714',
    title: 'Love Bites',
    network: 'NBC',
    startYear: 2011,
    years: '2011',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/57107.jpg',
    note: '',
  },
  {
    id: 8671,
    tvmazeId: '1995',
    title: 'Mad Dogs',
    network: 'Sky Showcase',
    startYear: 2011,
    years: '2011–2013',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/28044.jpg',
    note: '',
  },
  {
    id: 8672,
    tvmazeId: '3935',
    title: 'Mad Love',
    network: 'CBS',
    startYear: 2011,
    years: '2011',
    genres: ['Comedy', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/48998.jpg',
    note: '',
  },
  {
    id: 8673,
    tvmazeId: '2001',
    title: 'Man Up!',
    network: 'ABC',
    startYear: 2011,
    years: '2011',
    genres: ['Comedy', 'Family'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/28082.jpg',
    note: '',
  },
  {
    id: 8674,
    tvmazeId: '1756',
    title: 'Marchlands',
    network: 'ITV1',
    startYear: 2011,
    years: '2011',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/9/24585.jpg',
    note: '',
  },
  {
    id: 8675,
    tvmazeId: '40915',
    title: 'Matt Hatter Chronicles',
    network: 'CITV',
    startYear: 2011,
    years: '2011–2015',
    genres: ['Comedy', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/183/458205.jpg',
    note: '',
  },
  {
    id: 8676,
    tvmazeId: '6284',
    title: 'Michael: Every Day',
    network: 'CBC',
    startYear: 2011,
    years: '2011–2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/24/60314.jpg',
    note: '',
  },
  {
    id: 8677,
    tvmazeId: '11376',
    title: 'Mike the Knight',
    network: 'CBeebies',
    startYear: 2011,
    years: '2011–2015',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/38/95995.jpg',
    note: '',
  },
  {
    id: 8678,
    tvmazeId: '1117',
    title: 'Mildred Pierce',
    network: 'HBO',
    startYear: 2011,
    years: '2011',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17250.jpg',
    note: '',
  },
  {
    id: 8679,
    tvmazeId: '12525',
    title: 'Minnie\'s Bow-Toons',
    network: 'Disney Junior',
    startYear: 2011,
    years: '2011–2016',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/463/1159461.jpg',
    note: '',
  },
  {
    id: 8680,
    tvmazeId: '26943',
    title: 'Moby Dick',
    network: 'ABC',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/106/265978.jpg',
    note: '',
  },
  {
    id: 8681,
    tvmazeId: '18608',
    title: 'Mongo Wrestling Alliance',
    network: 'Adult Swim',
    startYear: 2011,
    years: '2011',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/63/159036.jpg',
    note: '',
  },
  {
    id: 8682,
    tvmazeId: '4403',
    title: 'Monroe',
    network: 'ITV1',
    startYear: 2011,
    years: '2011–2012',
    genres: ['Drama', 'Medical'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/51707.jpg',
    note: '',
  },
  {
    id: 8683,
    tvmazeId: '407',
    title: 'Mortal Kombat: Legacy',
    network: 'Machinima',
    startYear: 2011,
    years: '2011–2013',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/399/999495.jpg',
    note: '',
  },
  {
    id: 8684,
    tvmazeId: '266',
    title: 'Mount Pleasant',
    network: 'Sky Showcase',
    startYear: 2011,
    years: '2011–2017',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/1/4706.jpg',
    note: '',
  },
  {
    id: 8685,
    tvmazeId: '509',
    title: 'Mr. Sunshine',
    network: 'ABC',
    startYear: 2011,
    years: '2011–2012',
    genres: ['Comedy', 'Sports'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/4/11135.jpg',
    note: '',
  },
  {
    id: 8686,
    tvmazeId: '15132',
    title: 'Mr. Young',
    network: 'YTV',
    startYear: 2011,
    years: '2011–2013',
    genres: ['Comedy', 'Family', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/51/128556.jpg',
    note: '',
  },
  {
    id: 8687,
    tvmazeId: '1522',
    title: 'Mrs. Brown\'s Boys',
    network: 'RTÉ ONE',
    startYear: 2011,
    years: '2011–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/549/1373249.jpg',
    note: '',
  },
  {
    id: 8688,
    tvmazeId: '70395',
    title: 'Mulher de Fases',
    network: 'HBO',
    startYear: 2011,
    years: '2011',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/471/1179309.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 362, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
