window.pageShows = [
  {
    id: 8449,
    tvmazeId: '20749',
    title: 'Project: Phoenix',
    network: 'projectphoenix.tv',
    startYear: 2012,
    years: '2012–2014',
    genres: ['Drama', 'Action', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/183633.jpg',
    note: '',
  },
  {
    id: 8450,
    tvmazeId: '2163',
    title: 'Puberty Blues',
    network: 'Network 10',
    startYear: 2012,
    years: '2012–2014',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/443/1109535.jpg',
    note: '',
  },
  {
    id: 8451,
    tvmazeId: '4647',
    title: 'Public Enemies',
    network: 'BBC One',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/52597.jpg',
    note: '',
  },
  {
    id: 8452,
    tvmazeId: '23034',
    title: 'Queen In Hyun\'s Man',
    network: 'tvN',
    startYear: 2012,
    years: '2012',
    genres: ['Comedy', 'Fantasy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/85/214200.jpg',
    note: '',
  },
  {
    id: 8453,
    tvmazeId: '8646',
    title: 'Randy Cunningham: 9th Grade Ninja',
    network: 'Disney XD',
    startYear: 2012,
    years: '2012–2015',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/30/77025.jpg',
    note: '',
  },
  {
    id: 8454,
    tvmazeId: '30245',
    title: 'Reality Show',
    network: 'Paramount+ with Showtime',
    startYear: 2012,
    years: '2012',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/119/299428.jpg',
    note: '',
  },
  {
    id: 8455,
    tvmazeId: '7293',
    title: 'Redfern Now',
    network: 'ABC',
    startYear: 2012,
    years: '2012–2013',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/67660.jpg',
    note: '',
  },
  {
    id: 8456,
    tvmazeId: '1535',
    title: 'Restless',
    network: 'BBC One',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/71/179776.jpg',
    note: '',
  },
  {
    id: 8457,
    tvmazeId: '237',
    title: 'Revolution',
    network: 'NBC',
    startYear: 2012,
    years: '2012–2014',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'NBC cancelled after two seasons; the nanite virus, Patriots conspiracy, and Monroe Republic arc were left completely open.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/55/138043.jpg',
    note: '',
  },
  {
    id: 8458,
    tvmazeId: '5746',
    title: 'Ring of Fire',
    network: 'REELZ',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/148/370636.jpg',
    note: '',
  },
  {
    id: 8459,
    tvmazeId: '360',
    title: 'Ripper Street',
    network: 'BBC Two',
    startYear: 2012,
    years: '2012–2016',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/2/5461.jpg',
    note: '',
  },
  {
    id: 8460,
    tvmazeId: '17998',
    title: 'Robot and Monster',
    network: 'Nickelodeon',
    startYear: 2012,
    years: '2012',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/61/152583.jpg',
    note: '',
  },
  {
    id: 8461,
    tvmazeId: '22315',
    title: 'Rocket\'s Island',
    network: 'CBBC',
    startYear: 2012,
    years: '2012–2015',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/81/204202.jpg',
    note: '',
  },
  {
    id: 8462,
    tvmazeId: '23023',
    title: 'Room at the Top',
    network: 'BBC Four',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/85/214017.jpg',
    note: '',
  },
  {
    id: 8463,
    tvmazeId: '271',
    title: 'Saving Hope',
    network: 'CTV',
    startYear: 2012,
    years: '2012–2017',
    genres: ['Drama', 'Fantasy', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/91/229823.jpg',
    note: '',
  },
  {
    id: 8464,
    tvmazeId: '98',
    title: 'Scandal',
    network: 'ABC',
    startYear: 2012,
    years: '2012–2018',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: 'ABC gave the show a proper seven-season finale with Olivia Pope\'s arc resolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/303/758518.jpg',
    note: '',
  },
  {
    id: 8465,
    tvmazeId: '8296',
    title: 'School 2013',
    network: 'KBS1',
    startYear: 2012,
    years: '2012–2013',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/585/1464356.jpg',
    note: '',
  },
  {
    id: 8466,
    tvmazeId: '24412',
    title: 'Scot Squad',
    network: 'BBC iPlayer',
    startYear: 2012,
    years: '2012–2023',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/93/232577.jpg',
    note: '',
  },
  {
    id: 8467,
    tvmazeId: '6178',
    title: 'Secret State',
    network: 'Channel 4',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/59736.jpg',
    note: '',
  },
  {
    id: 8468,
    tvmazeId: '13635',
    title: 'Secrets and Words',
    network: 'BBC One',
    startYear: 2012,
    years: '2012',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 8469,
    tvmazeId: '372',
    title: 'See Dad Run',
    network: 'nick@nite',
    startYear: 2012,
    years: '2012–2014',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/2/5526.jpg',
    note: '',
  },
  {
    id: 8470,
    tvmazeId: '35640',
    title: 'Shaun the Sheep Championsheeps',
    network: 'CBBC',
    startYear: 2012,
    years: '2012',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/150/377182.jpg',
    note: '',
  },
  {
    id: 8471,
    tvmazeId: '9089',
    title: 'SheZow',
    network: 'Network 10',
    startYear: 2012,
    years: '2012–2013',
    genres: ['Action', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/32/80267.jpg',
    note: '',
  },
  {
    id: 8472,
    tvmazeId: '856',
    title: 'Sinbad',
    network: 'Sky Showcase',
    startYear: 2012,
    years: '2012',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/15875.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 353, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
