window.pageShows = [
  {
    id: 11161,
    tvmazeId: '35500',
    title: 'Ted and Alice',
    network: 'BBC One',
    startYear: 2002,
    years: '2002',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11162,
    tvmazeId: '1974',
    title: 'That \'80s Show',
    network: 'FOX',
    startYear: 2002,
    years: '2002',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/27943.jpg',
    note: '',
  },
  {
    id: 11163,
    tvmazeId: '50025',
    title: 'That Was Then',
    network: 'ABC',
    startYear: 2002,
    years: '2002',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/270/676685.jpg',
    note: '',
  },
  {
    id: 11164,
    tvmazeId: '7457',
    title: 'The Adventures of Jimmy Neutron: Boy Genius',
    network: 'Nickelodeon',
    startYear: 2002,
    years: '2002–2006',
    genres: ['Comedy', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/494/1235083.jpg',
    note: '',
  },
  {
    id: 11165,
    tvmazeId: '8844',
    title: 'The American Embassy',
    network: 'FOX',
    startYear: 2002,
    years: '2002',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/418/1045488.jpg',
    note: '',
  },
  {
    id: 11166,
    tvmazeId: '21148',
    title: 'The Basil Brush Show',
    network: 'CBBC',
    startYear: 2002,
    years: '2002–2007',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/74/186569.jpg',
    note: '',
  },
  {
    id: 11167,
    tvmazeId: '43547',
    title: 'The Best Sex Ever',
    network: 'Cinemax',
    startYear: 2002,
    years: '2002–2003',
    genres: ['Drama', 'Fantasy', 'Adult'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/209/522996.jpg',
    note: '',
  },
  {
    id: 11168,
    tvmazeId: '85674',
    title: 'The Big Impression',
    network: 'BBC One',
    startYear: 2002,
    years: '2002–2004',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/576/1441523.jpg',
    note: '',
  },
  {
    id: 11169,
    tvmazeId: '7786',
    title: 'The Book Group',
    network: 'Channel 4',
    startYear: 2002,
    years: '2002–2003',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/71639.jpg',
    note: '',
  },
  {
    id: 11170,
    tvmazeId: '57247',
    title: 'The Book of Pooh',
    network: 'Disney Channel',
    startYear: 2002,
    years: '2002',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/352/882217.jpg',
    note: '',
  },
  {
    id: 11171,
    tvmazeId: '58490',
    title: 'The Court',
    network: 'ABC',
    startYear: 2002,
    years: '2002',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11172,
    tvmazeId: '8911',
    title: 'The Cramp Twins',
    network: 'Cartoon Network',
    startYear: 2002,
    years: '2002–2005',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/79091.jpg',
    note: '',
  },
  {
    id: 11173,
    tvmazeId: '940',
    title: 'The Dead Zone',
    network: 'USA Network',
    startYear: 2002,
    years: '2002–2007',
    genres: ['Drama', 'Fantasy', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16191.jpg',
    note: '',
  },
  {
    id: 11174,
    tvmazeId: '8822',
    title: 'The Eleventh Hour',
    network: 'CTV',
    startYear: 2002,
    years: '2002–2005',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/38/96065.jpg',
    note: '',
  },
  {
    id: 11175,
    tvmazeId: '66034',
    title: 'The Estate Agents',
    network: 'Channel 4',
    startYear: 2002,
    years: '2002',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/437/1093146.jpg',
    note: '',
  },
  {
    id: 11176,
    tvmazeId: '1289',
    title: 'The Forsyte Saga',
    network: 'ITV1',
    startYear: 2002,
    years: '2002–2003',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/18425.jpg',
    note: '',
  },
  {
    id: 11177,
    tvmazeId: '20951',
    title: 'The House That Jack Built',
    network: 'BBC One',
    startYear: 2002,
    years: '2002',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/184916.jpg',
    note: '',
  },
  {
    id: 11178,
    tvmazeId: '18450',
    title: 'The Jury',
    network: 'ITV1',
    startYear: 2002,
    years: '2002',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/62/157206.jpg',
    note: '',
  },
  {
    id: 11179,
    tvmazeId: '41678',
    title: 'The Little Polar Bear',
    network: 'KiKa',
    startYear: 2002,
    years: '2002–1995',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/190/477421.jpg',
    note: '',
  },
  {
    id: 11180,
    tvmazeId: '66380',
    title: 'The Random Years',
    network: 'UPN',
    startYear: 2002,
    years: '2002',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11181,
    tvmazeId: '66379',
    title: 'The Rerun Show',
    network: 'NBC',
    startYear: 2002,
    years: '2002',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/441/1103980.jpg',
    note: '',
  },
  {
    id: 11182,
    tvmazeId: '66413',
    title: 'The Shapies',
    network: 'Nine Network',
    startYear: 2002,
    years: '2002',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/441/1104448.jpg',
    note: '',
  },
  {
    id: 11183,
    tvmazeId: '663',
    title: 'The Shield',
    network: 'FX',
    startYear: 2002,
    years: '2002–2008',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/55/138892.jpg',
    note: '',
  },
  {
    id: 11184,
    tvmazeId: '9541',
    title: 'The Story of Tracy Beaker',
    network: 'BBC One',
    startYear: 2002,
    years: '2002–2005',
    genres: ['Drama', 'Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/398/995494.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 466, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 398, "cliffhanger": 239, "ended": 15092}};
