window.pageShows = [
  {
    id: 13273,
    tvmazeId: '75191',
    title: 'Julie Farr, M.D.',
    network: 'ABC',
    startYear: 1979,
    years: '1979',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 13274,
    tvmazeId: '69533',
    title: 'Just Friends',
    network: 'CBS',
    startYear: 1979,
    years: '1979',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/479/1198285.jpg',
    note: '',
  },
  {
    id: 13275,
    tvmazeId: '56681',
    title: 'Kelly Monteith',
    network: 'BBC One',
    startYear: 1979,
    years: '1979–1984',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/345/864727.jpg',
    note: '',
  },
  {
    id: 13276,
    tvmazeId: '18371',
    title: 'Kidnapped',
    network: 'ITV1',
    startYear: 1979,
    years: '1979',
    genres: ['Drama', 'Adventure', 'History'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: '',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/62/156107.jpg',
    note: '',
  },
  {
    id: 13277,
    tvmazeId: '5319',
    title: 'Knots Landing',
    network: 'CBS',
    startYear: 1979,
    years: '1979–1993',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/55263.jpg',
    note: '',
  },
  {
    id: 13278,
    tvmazeId: '40630',
    title: 'Legends of the Super-Heroes',
    network: 'NBC',
    startYear: 1979,
    years: '1979',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/181/453981.jpg',
    note: '',
  },
  {
    id: 13279,
    tvmazeId: '89780',
    title: 'Love Thy Neighbour',
    network: 'Seven Network',
    startYear: 1979,
    years: '1979',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/608/1520243.jpg',
    note: '',
  },
  {
    id: 13280,
    tvmazeId: '56102',
    title: 'Makin\' It',
    network: 'ABC',
    startYear: 1979,
    years: '1979',
    genres: ['Drama', 'Comedy', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/479/1198290.jpg',
    note: '',
  },
  {
    id: 13281,
    tvmazeId: '40605',
    title: 'Married: The First Year',
    network: 'CBS',
    startYear: 1979,
    years: '1979',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/427/1069865.jpg',
    note: '',
  },
  {
    id: 13282,
    tvmazeId: '43362',
    title: 'Mighty Man and Yukk',
    network: 'ABC',
    startYear: 1979,
    years: '1979–1980',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/208/520140.jpg',
    note: '',
  },
  {
    id: 13283,
    tvmazeId: '6085',
    title: 'Minder',
    network: 'ITV1',
    startYear: 1979,
    years: '1979–1994',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/59226.jpg',
    note: '',
  },
  {
    id: 13284,
    tvmazeId: '20295',
    title: 'Mrs. Columbo',
    network: 'NBC',
    startYear: 1979,
    years: '1979–1980',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/71/179770.jpg',
    note: '',
  },
  {
    id: 13285,
    tvmazeId: '36318',
    title: 'My Son, My Son',
    network: 'BBC One',
    startYear: 1979,
    years: '1979',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 13286,
    tvmazeId: '7823',
    title: 'Only When I Laugh',
    network: 'ITV1',
    startYear: 1979,
    years: '1979–1982',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/71847.jpg',
    note: '',
  },
  {
    id: 13287,
    tvmazeId: '64903',
    title: 'Out of the Blue',
    network: 'ABC',
    startYear: 1979,
    years: '1979',
    genres: ['Comedy', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/428/1071460.jpg',
    note: '',
  },
  {
    id: 13288,
    tvmazeId: '64926',
    title: 'Paris',
    network: 'CBS',
    startYear: 1979,
    years: '1979–1980',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/477/1193088.jpg',
    note: '',
  },
  {
    id: 13289,
    tvmazeId: '1630',
    title: 'Patrol Boat',
    network: 'ABC',
    startYear: 1979,
    years: '1979–1980',
    genres: ['Drama', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/14/37198.jpg',
    note: '',
  },
  {
    id: 13290,
    tvmazeId: '10981',
    title: 'Penmarric',
    network: 'BBC One',
    startYear: 1979,
    years: '1979',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/92/231907.jpg',
    note: '',
  },
  {
    id: 13291,
    tvmazeId: '43364',
    title: 'Plastic Family',
    network: 'ABC',
    startYear: 1979,
    years: '1979',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/208/520146.jpg',
    note: '',
  },
  {
    id: 13292,
    tvmazeId: '47841',
    title: 'Plastic Man',
    network: 'ABC',
    startYear: 1979,
    years: '1979–1980',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/255/638637.jpg',
    note: '',
  },
  {
    id: 13293,
    tvmazeId: '64917',
    title: 'Potter',
    network: 'BBC One',
    startYear: 1979,
    years: '1979–1983',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/428/1071885.jpg',
    note: '',
  },
  {
    id: 13294,
    tvmazeId: '28898',
    title: 'Prince Regent',
    network: 'BBC One',
    startYear: 1979,
    years: '1979',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/115/287923.jpg',
    note: '',
  },
  {
    id: 13295,
    tvmazeId: '5439',
    title: 'Prisoner',
    network: 'Network 10',
    startYear: 1979,
    years: '1979–1986',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/55677.jpg',
    note: '',
  },
  {
    id: 13296,
    tvmazeId: '33240',
    title: 'Quatermass',
    network: 'ITV1',
    startYear: 1979,
    years: '1979',
    genres: ['Drama', 'Fantasy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/221/552882.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 554, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 334, "cliffhanger": 235, "ended": 13701}};
