window.pageShows = [
  {
    id: 12961,
    tvmazeId: '40799',
    title: 'Tattooed Teenage Alien Fighters from Beverly Hills',
    network: 'USA Network',
    startYear: 1994,
    years: '1994–1995',
    genres: ['Action', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/182/455993.jpg',
    note: '',
  },
  {
    id: 12962,
    tvmazeId: '462',
    title: 'TekWar',
    network: 'Syndication',
    startYear: 1994,
    years: '1994–1996',
    genres: ['Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/3/9202.jpg',
    note: '',
  },
  {
    id: 12963,
    tvmazeId: '33004',
    title: 'The 10%ers',
    network: 'ITV1',
    startYear: 1994,
    years: '1994–1996',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12964,
    tvmazeId: '41967',
    title: 'The 5 Mrs. Buchanans',
    network: 'CBS',
    startYear: 1994,
    years: '1994–1995',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/193/483794.jpg',
    note: '',
  },
  {
    id: 12965,
    tvmazeId: '48126',
    title: 'The All New Alexei Sayle Show',
    network: 'BBC Two',
    startYear: 1994,
    years: '1994–1995',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/290/727288.jpg',
    note: '',
  },
  {
    id: 12966,
    tvmazeId: '90724',
    title: 'The Bob Morrison Show',
    network: 'Nine Network',
    startYear: 1994,
    years: '1994',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/616/1542424.jpg',
    note: '',
  },
  {
    id: 12967,
    tvmazeId: '40076',
    title: 'The Boys are Back',
    network: 'CBS',
    startYear: 1994,
    years: '1994–1995',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/177/443607.jpg',
    note: '',
  },
  {
    id: 12968,
    tvmazeId: '72917',
    title: 'The Brothers Grunt',
    network: 'MTV',
    startYear: 1994,
    years: '1994–2019',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/488/1221598.jpg',
    note: '',
  },
  {
    id: 12969,
    tvmazeId: '18008',
    title: 'The Busy World of Richard Scarry',
    network: 'Nickelodeon',
    startYear: 1994,
    years: '1994–1996',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/61/152602.jpg',
    note: '',
  },
  {
    id: 12970,
    tvmazeId: '58245',
    title: 'The Byrds of Paradise',
    network: 'ABC',
    startYear: 1994,
    years: '1994',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/364/911330.jpg',
    note: '',
  },
  {
    id: 12971,
    tvmazeId: '7744',
    title: 'The Cosby Mysteries',
    network: 'NBC',
    startYear: 1994,
    years: '1994–1995',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/71175.jpg',
    note: '',
  },
  {
    id: 12972,
    tvmazeId: '697',
    title: 'The Critic',
    network: 'Atom.com',
    startYear: 1994,
    years: '1994–2001',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/5/14997.jpg',
    note: '',
  },
  {
    id: 12973,
    tvmazeId: '28569',
    title: 'The Damnation of Harvey McHugh',
    network: 'ABC',
    startYear: 1994,
    years: '1994',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/113/284240.jpg',
    note: '',
  },
  {
    id: 12974,
    tvmazeId: '2578',
    title: 'The Day Today',
    network: 'BBC Two',
    startYear: 1994,
    years: '1994',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/13/34446.jpg',
    note: '',
  },
  {
    id: 12975,
    tvmazeId: '2779',
    title: 'The Fast Show',
    network: 'BBC Two',
    startYear: 1994,
    years: '1994–2014',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/59/147884.jpg',
    note: '',
  },
  {
    id: 12976,
    tvmazeId: '6971',
    title: 'The George Carlin Show',
    network: 'FOX',
    startYear: 1994,
    years: '1994–1995',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/65523.jpg',
    note: '',
  },
  {
    id: 12977,
    tvmazeId: '24650',
    title: 'The Good Life',
    network: 'NBC',
    startYear: 1994,
    years: '1994',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/94/235511.jpg',
    note: '',
  },
  {
    id: 12978,
    tvmazeId: '4221',
    title: 'The Head',
    network: 'MTV',
    startYear: 1994,
    years: '1994–1996',
    genres: ['Comedy', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/50676.jpg',
    note: '',
  },
  {
    id: 12979,
    tvmazeId: '2106',
    title: 'The High Life',
    network: 'BBC Two',
    startYear: 1994,
    years: '1994–1995',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/29286.jpg',
    note: '',
  },
  {
    id: 12980,
    tvmazeId: '51135',
    title: 'The Ink Thief',
    network: 'CITV',
    startYear: 1994,
    years: '1994',
    genres: ['Adventure', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/277/693818.jpg',
    note: '',
  },
  {
    id: 12981,
    tvmazeId: '73600',
    title: 'The Itsy Bitsy Spider',
    network: 'USA Network',
    startYear: 1994,
    years: '1994–1995',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/495/1238348.jpg',
    note: '',
  },
  {
    id: 12982,
    tvmazeId: '8460',
    title: 'The Knock',
    network: 'ITV1',
    startYear: 1994,
    years: '1994–2000',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/30/75394.jpg',
    note: '',
  },
  {
    id: 12983,
    tvmazeId: '18504',
    title: 'The Magic School Bus',
    network: 'PBS',
    startYear: 1994,
    years: '1994–1997',
    genres: ['Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/63/157993.jpg',
    note: '',
  },
  {
    id: 12984,
    tvmazeId: '14673',
    title: 'The Man from Snowy River',
    network: 'Nine Network',
    startYear: 1994,
    years: '1994–1998',
    genres: ['Drama', 'Adventure', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/49/124213.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 541, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 398, "cliffhanger": 239, "ended": 15092}};
