window.pageShows = [
  {
    id: 1033,
    tvmazeId: '63255',
    title: 'Champion checkifcancelled',
    network: 'BBC iPlayer',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Music'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/467/1168664.jpg',
    note: '',
  },
  {
    id: 1034,
    tvmazeId: '66768',
    title: 'Changing Ends',
    network: 'ITVX',
    startYear: 2023,
    years: '2023–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/599/1499499.jpg',
    note: '',
  },
  {
    id: 1035,
    tvmazeId: '88031',
    title: 'Cherry Lane Trilogy',
    network: 'Hallmark+',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Family', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/596/1490821.jpg',
    note: '',
  },
  {
    id: 1036,
    tvmazeId: '73840',
    title: 'Chip Chilla',
    network: 'DailyWire+',
    startYear: 2023,
    years: '2023–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/498/1247263.jpg',
    note: '',
  },
  {
    id: 1037,
    tvmazeId: '45834',
    title: 'Citadel',
    network: 'Prime Video',
    startYear: 2023,
    years: '2023–',
    genres: ['Action', 'Thriller', 'Espionage'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: '',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/624/1560435.jpg',
    note: '',
  },
  {
    id: 1038,
    tvmazeId: '56187',
    title: 'City on Fire',
    network: 'Apple TV',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/464/1161713.jpg',
    note: '',
  },
  {
    id: 1039,
    tvmazeId: '67125',
    title: 'Class of \'07 checkifcancelled',
    network: 'Prime Video',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/452/1131776.jpg',
    note: '',
  },
  {
    id: 1040,
    tvmazeId: '56039',
    title: 'Class of \'09',
    network: 'Hulu',
    startYear: 2023,
    years: '2023',
    genres: ['Crime', 'Science-Fiction', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/460/1150604.jpg',
    note: '',
  },
  {
    id: 1041,
    tvmazeId: '63509',
    title: 'Clean Sweep',
    network: 'RTÉ Player',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/443/1108160.jpg',
    note: '',
  },
  {
    id: 1042,
    tvmazeId: '53472',
    title: 'Clone High',
    network: 'HBO Max',
    startYear: 2023,
    years: '2023–2024',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: 'MTV cancelled after one season; a 2023 revival series continued and resolved the story.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/464/1161604.jpg',
    note: '',
  },
  {
    id: 1043,
    tvmazeId: '87842',
    title: 'Cocaine Sisters',
    network: 'UrbanflixTV',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/594/1486162.jpg',
    note: '',
  },
  {
    id: 1044,
    tvmazeId: '71580',
    title: 'CoComelon Lane',
    network: 'Netflix',
    startYear: 2023,
    years: '2023–',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/483/1208620.jpg',
    note: '',
  },
  {
    id: 1045,
    tvmazeId: '69921',
    title: 'Command Z',
    network: 'Extension765',
    startYear: 2023,
    years: '2023',
    genres: ['Comedy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/468/1172333.jpg',
    note: '',
  },
  {
    id: 1046,
    tvmazeId: '66449',
    title: 'Count Abdulla',
    network: 'ITVX',
    startYear: 2023,
    years: '2023',
    genres: ['Comedy', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/465/1163049.jpg',
    note: '',
  },
  {
    id: 1047,
    tvmazeId: '66125',
    title: 'Crazy Fun Park checkifcancelled',
    network: 'ABC iview',
    startYear: 2023,
    years: '2023–',
    genres: ['Adventure', 'Fantasy', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/438/1097017.jpg',
    note: '',
  },
  {
    id: 1048,
    tvmazeId: '75250',
    title: 'Cuddle Season checkifcancelled',
    network: 'Tubi',
    startYear: 2023,
    years: '2023–',
    genres: [],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/507/1269913.jpg',
    note: '',
  },
  {
    id: 1049,
    tvmazeId: '54829',
    title: 'Culprits',
    network: 'Disney+',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/491/1229038.jpg',
    note: '',
  },
  {
    id: 1050,
    tvmazeId: '71231',
    title: 'Curses! checkifcancelled',
    network: 'Apple TV',
    startYear: 2023,
    years: '2023–',
    genres: ['Comedy', 'Adventure', 'Supernatural'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/483/1208612.jpg',
    note: '',
  },
  {
    id: 1051,
    tvmazeId: '72446',
    title: 'Dad\'s Army: The Animations',
    network: 'U&GOLD',
    startYear: 2023,
    years: '2023–',
    genres: ['Comedy', 'War'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/485/1212756.jpg',
    note: '',
  },
  {
    id: 1052,
    tvmazeId: '37884',
    title: 'Daisy Jones & the Six',
    network: 'Prime Video',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/447/1118912.jpg',
    note: '',
  },
  {
    id: 1053,
    tvmazeId: '71316',
    title: 'Darradong Local Council checkifcancelled',
    network: '7mate',
    startYear: 2023,
    years: '2023–',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/483/1208346.jpg',
    note: '',
  },
  {
    id: 1054,
    tvmazeId: '56532',
    title: 'Dead Ringers',
    network: 'Prime Video',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Horror', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/458/1145737.jpg',
    note: '',
  },
  {
    id: 1055,
    tvmazeId: '60614',
    title: 'Deadloch',
    network: 'Prime Video',
    startYear: 2023,
    years: '2023–',
    genres: ['Comedy', 'Crime', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/615/1538438.jpg',
    note: '',
  },
  {
    id: 1056,
    tvmazeId: '60292',
    title: 'Dear Edward',
    network: 'Apple TV',
    startYear: 2023,
    years: '2023',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/445/1112792.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 44, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 824, "cliffhanger": 237, "ended": 13574}};
