window.pageShows = [
  {
    id: 5449,
    tvmazeId: '39929',
    title: 'The Blake Mysteries',
    network: 'Seven Network',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/179/448204.jpg',
    note: '',
  },
  {
    id: 5450,
    tvmazeId: '37008',
    title: 'The Bletchley Circle: San Francisco',
    network: 'BritBox',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/160/401704.jpg',
    note: '',
  },
  {
    id: 5451,
    tvmazeId: '80821',
    title: 'The Blubburbs',
    network: 'go90',
    startYear: 2018,
    years: '2018–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/543/1359343.jpg',
    note: '',
  },
  {
    id: 5452,
    tvmazeId: '27700',
    title: 'The Bobby Brown Story',
    network: 'BET',
    startYear: 2018,
    years: '2018',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/165/414540.jpg',
    note: '',
  },
  {
    id: 5453,
    tvmazeId: '35181',
    title: 'The Boss Baby: Back in Business',
    network: 'Netflix',
    startYear: 2018,
    years: '2018–2020',
    genres: ['Comedy', 'Adventure', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/168/420194.jpg',
    note: '',
  },
  {
    id: 5454,
    tvmazeId: '41782',
    title: 'The Bridge',
    network: 'Viu',
    startYear: 2018,
    years: '2018–2020',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/191/479257.jpg',
    note: '',
  },
  {
    id: 5455,
    tvmazeId: '25949',
    title: 'The Bureau of Magical Things',
    network: 'Nickelodeon',
    startYear: 2018,
    years: '2018–2021',
    genres: ['Drama', 'Children', 'Fantasy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/182/455964.jpg',
    note: '',
  },
  {
    id: 5456,
    tvmazeId: '42097',
    title: 'The Champions',
    network: 'YouTube',
    startYear: 2018,
    years: '2018–',
    genres: ['Comedy', 'Sports'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/465/1164135.jpg',
    note: '',
  },
  {
    id: 5457,
    tvmazeId: '24371',
    title: 'The Chi',
    network: 'Paramount+',
    startYear: 2018,
    years: '2018–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/626/1566210.jpg',
    note: '',
  },
  {
    id: 5458,
    tvmazeId: '50426',
    title: 'The Christmas Chronicles',
    network: 'Netflix',
    startYear: 2018,
    years: '2018–2020',
    genres: ['Comedy', 'Adventure', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/273/683867.jpg',
    note: '',
  },
  {
    id: 5459,
    tvmazeId: '32007',
    title: 'The City and the City',
    network: 'BBC iPlayer',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Science-Fiction', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/150/376040.jpg',
    note: '',
  },
  {
    id: 5460,
    tvmazeId: '37226',
    title: 'The Conners',
    network: 'ABC',
    startYear: 2018,
    years: '2018–2025',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/560/1401889.jpg',
    note: '',
  },
  {
    id: 5461,
    tvmazeId: '31663',
    title: 'The Cool Kids',
    network: 'FOX',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/163/408001.jpg',
    note: '',
  },
  {
    id: 5462,
    tvmazeId: '21866',
    title: 'The Crossing',
    network: 'ABC',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'ABC cancelled after one season; the refugees from the future and Apex\'s plans to alter history were left open.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/142/355299.jpg',
    note: '',
  },
  {
    id: 5463,
    tvmazeId: '34994',
    title: 'The Cry',
    network: 'BBC One',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/171/428583.jpg',
    note: '',
  },
  {
    id: 5464,
    tvmazeId: '38025',
    title: 'The Curious Creations of Christine McConnell',
    network: 'Netflix',
    startYear: 2018,
    years: '2018',
    genres: ['Comedy', 'Food', 'Horror'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/169/424448.jpg',
    note: '',
  },
  {
    id: 5465,
    tvmazeId: '28040',
    title: 'The Dangerous Book for Boys',
    network: 'Prime Video',
    startYear: 2018,
    years: '2018',
    genres: ['Comedy', 'Family', 'Fantasy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/146/366907.jpg',
    note: '',
  },
  {
    id: 5466,
    tvmazeId: '43900',
    title: 'The Dead Girls Detective Agency',
    network: 'Snapchat',
    startYear: 2018,
    years: '2018–2019',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/211/529177.jpg',
    note: '',
  },
  {
    id: 5467,
    tvmazeId: '27769',
    title: 'The Detail',
    network: 'CTV',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/147/368647.jpg',
    note: '',
  },
  {
    id: 5468,
    tvmazeId: '28464',
    title: 'The Detectives',
    network: 'CBC',
    startYear: 2018,
    years: '2018–2020',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/163/409006.jpg',
    note: '',
  },
  {
    id: 5469,
    tvmazeId: '37675',
    title: 'The Dragon Prince',
    network: 'Netflix',
    startYear: 2018,
    years: '2018–2024',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/214/536527.jpg',
    note: '',
  },
  {
    id: 5470,
    tvmazeId: '36449',
    title: 'The Epic Tales of Captain Underpants',
    network: 'Netflix',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Action', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/160/401931.jpg',
    note: '',
  },
  {
    id: 5471,
    tvmazeId: '44895',
    title: 'The Farm',
    network: 'BBC One Scotland',
    startYear: 2018,
    years: '2018–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 5472,
    tvmazeId: '77705',
    title: 'The Fifth Floor',
    network: 'meWATCH',
    startYear: 2018,
    years: '2018',
    genres: ['Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/522/1307124.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 228, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
