window.pageShows = [
  {
    id: 3337,
    tvmazeId: '55699',
    title: 'La muchacha que limpia',
    network: 'HBO',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/331/828415.jpg',
    note: '',
  },
  {
    id: 3338,
    tvmazeId: '70584',
    title: 'La super vie d\'Hakim',
    network: 'Canal+',
    startYear: 2021,
    years: '2021–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        note: '',
  },
  {
    id: 3339,
    tvmazeId: '41068',
    title: 'La Templanza',
    network: 'Prime Video',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/398/995689.jpg',
    note: '',
  },
  {
    id: 3340,
    tvmazeId: '57418',
    title: 'La Venganza de las Juanas',
    network: 'Netflix',
    startYear: 2021,
    years: '2021',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/355/887898.jpg',
    note: '',
  },
  {
    id: 3341,
    tvmazeId: '59423',
    title: 'Lace',
    network: 'ALLBLK',
    startYear: 2021,
    years: '2021–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/382/956613.jpg',
    note: '',
  },
  {
    id: 3342,
    tvmazeId: '61496',
    title: 'Lagging',
    network: 'BBC iPlayer',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Drama', 'Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 3343,
    tvmazeId: '45500',
    title: 'Landscapers',
    network: 'HBO',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/387/967573.jpg',
    note: '',
  },
  {
    id: 3344,
    tvmazeId: '55204',
    title: 'Launchpad',
    network: 'Disney+',
    startYear: 2021,
    years: '2021–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/476/1191794.jpg',
    note: '',
  },
  {
    id: 3345,
    tvmazeId: '48631',
    title: 'Law & Order: Organized Crime',
    network: 'Peacock',
    startYear: 2021,
    years: '2021–2025',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/564/1410371.jpg',
    note: '',
  },
  {
    id: 3346,
    tvmazeId: '53828',
    title: 'Law School',
    network: 'jTBC',
    startYear: 2021,
    years: '2021',
    genres: ['Thriller', 'Mystery', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/298/745468.jpg',
    note: '',
  },
  {
    id: 3347,
    tvmazeId: '59969',
    title: 'Learning with Pibby: Apocalypse',
    network: 'Adult Swim',
    startYear: 2021,
    years: '2021–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/389/973568.jpg',
    note: '',
  },
  {
    id: 3348,
    tvmazeId: '53774',
    title: 'Leonardo',
    network: 'Rai 1',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/297/744697.jpg',
    note: '',
  },
  {
    id: 3349,
    tvmazeId: '54448',
    title: 'Let\'s Be Real',
    network: 'FOX',
    startYear: 2021,
    years: '2021–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/402/1006409.jpg',
    note: '',
  },
  {
    id: 3350,
    tvmazeId: '47451',
    title: 'Leverage: Redemption',
    network: 'Prime Video',
    startYear: 2021,
    years: '2021–2025',
    genres: ['Action', 'Adventure', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/564/1412473.jpg',
    note: '',
  },
  {
    id: 3351,
    tvmazeId: '56189',
    title: 'Lie With Me',
    network: '5',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/339/848902.jpg',
    note: '',
  },
  {
    id: 3352,
    tvmazeId: '57790',
    title: 'Life\'s a Glitch with Julien Bam',
    network: 'Netflix',
    startYear: 2021,
    years: '2021',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/359/899030.jpg',
    note: '',
  },
  {
    id: 3353,
    tvmazeId: '55866',
    title: 'Life\'s Rewards',
    network: 'Prime Video',
    startYear: 2021,
    years: '2021–',
    genres: ['Drama', 'Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/328/821109.jpg',
    note: '',
  },
  {
    id: 3354,
    tvmazeId: '55902',
    title: 'Light On Me',
    network: 'Watcha',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/329/823025.jpg',
    note: '',
  },
  {
    id: 3355,
    tvmazeId: '59171',
    title: 'Light the Night',
    network: 'Netflix',
    startYear: 2021,
    years: '2021–2022',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/379/948003.jpg',
    note: '',
  },
  {
    id: 3356,
    tvmazeId: '54309',
    title: 'Lights Up',
    network: 'BBC Four',
    startYear: 2021,
    years: '2021–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/308/770295.jpg',
    note: '',
  },
  {
    id: 3357,
    tvmazeId: '70321',
    title: 'Lioness',
    network: 'M-Net',
    startYear: 2021,
    years: '2021–',
    genres: ['Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/471/1178760.jpg',
    note: '',
  },
  {
    id: 3358,
    tvmazeId: '41694',
    title: 'Lisey\'s Story',
    network: 'Apple TV',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Fantasy', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/315/789633.jpg',
    note: '',
  },
  {
    id: 3359,
    tvmazeId: '56984',
    title: 'Little Ellen',
    network: 'HBO Max',
    startYear: 2021,
    years: '2021–2022',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/350/876399.jpg',
    note: '',
  },
  {
    id: 3360,
    tvmazeId: '41007',
    title: 'Loki',
    network: 'Disney+',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/478/1195717.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 140, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 398, "cliffhanger": 239, "ended": 15092}};
