window.pageShows = [
  {
    id: 6217,
    tvmazeId: '17181',
    title: 'Baroness von Sketch Show',
    network: 'CBC',
    startYear: 2016,
    years: '2016–2021',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/67/168320.jpg',
    note: '',
  },
  {
    id: 6218,
    tvmazeId: '18961',
    title: 'Barracuda',
    network: 'ABC',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/65/164054.jpg',
    note: '',
  },
  {
    id: 6219,
    tvmazeId: '6741',
    title: 'Baskets',
    network: 'FX',
    startYear: 2016,
    years: '2016–2019',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/196/492355.jpg',
    note: '',
  },
  {
    id: 6220,
    tvmazeId: '13279',
    title: 'Beat Bugs',
    network: '7two',
    startYear: 2016,
    years: '2016–',
    genres: ['Adventure', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/95/239480.jpg',
    note: '',
  },
  {
    id: 6221,
    tvmazeId: '14836',
    title: 'Beautiful Gong Shim',
    network: 'SBS',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/57/143531.jpg',
    note: '',
  },
  {
    id: 6222,
    tvmazeId: '14838',
    title: 'Beautiful Mind',
    network: 'KBS2',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Thriller', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/62/156965.jpg',
    note: '',
  },
  {
    id: 6223,
    tvmazeId: '11087',
    title: 'Bedrag',
    network: 'DR1',
    startYear: 2016,
    years: '2016–2019',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/118/296601.jpg',
    note: '',
  },
  {
    id: 6224,
    tvmazeId: '64066',
    title: 'Before 30',
    network: 'Africa Magic',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/421/1054801.jpg',
    note: '',
  },
  {
    id: 6225,
    tvmazeId: '22084',
    title: 'Ben 10',
    network: 'Cartoon Network',
    startYear: 2016,
    years: '2016–2021',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/80/201155.jpg',
    note: '',
  },
  {
    id: 6226,
    tvmazeId: '3369',
    title: 'Beowulf: Return to the Shieldlands',
    network: 'ITV1',
    startYear: 2016,
    years: '2016',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/351/878431.jpg',
    note: '',
  },
  {
    id: 6227,
    tvmazeId: '2632',
    title: 'Berlin Station',
    network: 'MGM+',
    startYear: 2016,
    years: '2016–2019',
    genres: ['Drama', 'Mystery', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/176/440242.jpg',
    note: '',
  },
  {
    id: 6228,
    tvmazeId: '17247',
    title: 'Bertram Poppingstock: Problem Solver',
    network: 'ABC Entertains',
    startYear: 2016,
    years: '2016',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/58/145450.jpg',
    note: '',
  },
  {
    id: 6229,
    tvmazeId: '20709',
    title: 'Better Life Foundation',
    network: 'YouTube',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/182882.jpg',
    note: '',
  },
  {
    id: 6230,
    tvmazeId: '6514',
    title: 'Better Things',
    network: 'FX',
    startYear: 2016,
    years: '2016–2022',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/405/1013236.jpg',
    note: '',
  },
  {
    id: 6231,
    tvmazeId: '33762',
    title: 'Big Field',
    network: 'BBC Three',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/137/344296.jpg',
    note: '',
  },
  {
    id: 6232,
    tvmazeId: '15263',
    title: 'Big Jay Oakerson\'s What\'s Your F@%ing Deal?!',
    network: 'Seeso',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/201/503888.jpg',
    note: '',
  },
  {
    id: 6233,
    tvmazeId: '3606',
    title: 'Billions',
    network: 'Showtime on Demand',
    startYear: 2016,
    years: '2016–2023',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/471/1179691.jpg',
    note: '',
  },
  {
    id: 6234,
    tvmazeId: '16458',
    title: 'Bizaardvark',
    network: 'Disney Channel',
    startYear: 2016,
    years: '2016–2019',
    genres: ['Comedy', 'Children', 'Music'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/155/388732.jpg',
    note: '',
  },
  {
    id: 6235,
    tvmazeId: '22008',
    title: 'Bookaboo',
    network: 'Prime Video',
    startYear: 2016,
    years: '2016',
    genres: ['Children', 'Family', 'Music'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/79/199783.jpg',
    note: '',
  },
  {
    id: 6236,
    tvmazeId: '19550',
    title: 'Borderline',
    network: '5',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/131/329945.jpg',
    note: '',
  },
  {
    id: 6237,
    tvmazeId: '3946',
    title: 'Bordertown',
    network: 'FOX',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/82/205525.jpg',
    note: '',
  },
  {
    id: 6238,
    tvmazeId: '25085',
    title: 'Born for You',
    network: 'ABS-CBN',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/96/242276.jpg',
    note: '',
  },
  {
    id: 6239,
    tvmazeId: '19184',
    title: 'Bottersnikes & Gumbles',
    network: 'CBBC',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/67/167619.jpg',
    note: '',
  },
  {
    id: 6240,
    tvmazeId: '44310',
    title: 'Brace: The Series',
    network: 'YouTube',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Science-Fiction', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/214/536593.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 260, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
