window.pageShows = [
  {
    id: 3769,
    tvmazeId: '56156',
    title: 'On Order and Away',
    network: 'Prime Video',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/334/835870.jpg',
    note: '',
  },
  {
    id: 3770,
    tvmazeId: '38220',
    title: 'On the Edge',
    network: 'Channel 4',
    startYear: 2018,
    years: '2018–',
    genres: ['Drama', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/165/412521.jpg',
    note: '',
  },
  {
    id: 3771,
    tvmazeId: '39726',
    title: 'On the Ropes',
    network: 'SBS',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/176/441029.jpg',
    note: '',
  },
  {
    id: 3772,
    tvmazeId: '30905',
    title: 'One Dollar',
    network: 'Paramount+',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/174/436538.jpg',
    note: '',
  },
  {
    id: 3773,
    tvmazeId: '30148',
    title: 'Ordeal by Innocence',
    network: 'BBC One',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/150/375379.jpg',
    note: '',
  },
  {
    id: 3774,
    tvmazeId: '32920',
    title: 'Origin',
    network: 'YouTube Premium',
    startYear: 2018,
    years: '2018',
    genres: ['Adventure', 'Science-Fiction', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/172/431489.jpg',
    note: '',
  },
  {
    id: 3775,
    tvmazeId: '40905',
    title: 'Orthus',
    network: 'PlayStation Network',
    startYear: 2018,
    years: '2018',
    genres: ['Science-Fiction', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/183/458113.jpg',
    note: '',
  },
  {
    id: 3776,
    tvmazeId: '34005',
    title: 'Our Cartoon President',
    network: 'Paramount+ with Showtime',
    startYear: 2018,
    years: '2018–2020',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/236/592295.jpg',
    note: '',
  },
  {
    id: 3777,
    tvmazeId: '35134',
    title: 'OverNights',
    network: 'YouTube',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/212/530911.jpg',
    note: '',
  },
  {
    id: 3778,
    tvmazeId: '39948',
    title: 'Overthinking with Kat & June',
    network: 'YouTube Premium',
    startYear: 2018,
    years: '2018',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/176/440983.jpg',
    note: '',
  },
  {
    id: 3779,
    tvmazeId: '35820',
    title: 'Paradise PD',
    network: 'Netflix',
    startYear: 2018,
    years: '2018–2022',
    genres: ['Comedy', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Netflix cancelled after four seasons with character arcs unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/162/406022.jpg',
    note: '',
  },
  {
    id: 3780,
    tvmazeId: '25712',
    title: 'Patrick Melrose',
    network: 'Paramount+ with Showtime',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/152/381141.jpg',
    note: '',
  },
  {
    id: 3781,
    tvmazeId: '25289',
    title: 'Pete the Cat',
    network: 'Prime Video',
    startYear: 2018,
    years: '2018–2022',
    genres: ['Adventure', 'Fantasy', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/169/424288.jpg',
    note: '',
  },
  {
    id: 3782,
    tvmazeId: '30631',
    title: 'Picnic at Hanging Rock',
    network: 'Foxtel Now',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/162/407250.jpg',
    note: '',
  },
  {
    id: 3783,
    tvmazeId: '35919',
    title: 'Pine Gap',
    network: 'ABC',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Thriller', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/171/429274.jpg',
    note: '',
  },
  {
    id: 3784,
    tvmazeId: '72454',
    title: 'Ping and Friends',
    network: 'TVO',
    startYear: 2018,
    years: '2018–2019',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/485/1212807.jpg',
    note: '',
  },
  {
    id: 3785,
    tvmazeId: '83747',
    title: 'Pinkalicious & Peterrific',
    network: 'PBS Kids',
    startYear: 2018,
    years: '2018–',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/561/1404624.jpg',
    note: '',
  },
  {
    id: 3786,
    tvmazeId: '34265',
    title: 'Playing for Keeps',
    network: 'Network 10',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Drama', 'Romance', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/167/418249.jpg',
    note: '',
  },
  {
    id: 3787,
    tvmazeId: '32015',
    title: 'Polly Pocket checkifcancelled',
    network: 'YouTube',
    startYear: 2018,
    years: '2018–',
    genres: ['Children'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/474/1185156.jpg',
    note: '',
  },
  {
    id: 3788,
    tvmazeId: '38223',
    title: 'Ponysitters Club',
    network: 'Netflix',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/165/413866.jpg',
    note: '',
  },
  {
    id: 3789,
    tvmazeId: '60034',
    title: 'Popeye\'s Island Adventures',
    network: 'YouTube',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/390/976888.jpg',
    note: '',
  },
  {
    id: 3790,
    tvmazeId: '26082',
    title: 'Pose',
    network: 'FX',
    startYear: 2018,
    years: '2018–2021',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/304/762252.jpg',
    note: '',
  },
  {
    id: 3791,
    tvmazeId: '39080',
    title: 'Post-Apocalypto',
    network: 'YouTube',
    startYear: 2018,
    years: '2018',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/171/428300.jpg',
    note: '',
  },
  {
    id: 3792,
    tvmazeId: '38315',
    title: 'Press',
    network: 'BBC One',
    startYear: 2018,
    years: '2018',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/165/412526.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 158, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 785, "cliffhanger": 237, "ended": 13610}};
