window.pageShows = [
  {
    id: 8785,
    tvmazeId: '13131',
    title: 'Proxy',
    network: 'Localish',
    startYear: 2011,
    years: '2011',
    genres: ['Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/45/112896.jpg',
    note: '',
  },
  {
    id: 8786,
    tvmazeId: '22282',
    title: 'Raa Raa the Noisy Lion',
    network: 'CBeebies',
    startYear: 2011,
    years: '2011–2018',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/81/203707.jpg',
    note: '',
  },
  {
    id: 8787,
    tvmazeId: '6409',
    title: 'Rastamouse',
    network: 'CBeebies',
    startYear: 2011,
    years: '2011–2015',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/24/61292.jpg',
    note: '',
  },
  {
    id: 8788,
    tvmazeId: '72214',
    title: 'Rated A for Awesome',
    network: 'YTV',
    startYear: 2011,
    years: '2011–2012',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/483/1208811.jpg',
    note: '',
  },
  {
    id: 8789,
    tvmazeId: '7642',
    title: 'Really Me',
    network: 'Family Channel',
    startYear: 2011,
    years: '2011–2013',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/70415.jpg',
    note: '',
  },
  {
    id: 8790,
    tvmazeId: '12227',
    title: 'Redakai: Conquer the Kairu',
    network: 'Cartoon Network',
    startYear: 2011,
    years: '2011–2012',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/41/102931.jpg',
    note: '',
  },
  {
    id: 8791,
    tvmazeId: '5477',
    title: 'Reed Between the Lines',
    network: 'BET Her',
    startYear: 2011,
    years: '2011–2015',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/410/1025684.jpg',
    note: '',
  },
  {
    id: 8792,
    tvmazeId: '37921',
    title: 'Resident Evil: First Hour',
    network: 'YouTube',
    startYear: 2011,
    years: '2011',
    genres: ['Action', 'Horror', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/625/1563850.jpg',
    note: '',
  },
  {
    id: 8793,
    tvmazeId: '4727',
    title: 'Retired at 35',
    network: 'TV Land',
    startYear: 2011,
    years: '2011–2012',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/300/751946.jpg',
    note: '',
  },
  {
    id: 8794,
    tvmazeId: '9',
    title: 'Revenge',
    network: 'ABC',
    startYear: 2011,
    years: '2011–2015',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/82/206879.jpg',
    note: '',
  },
  {
    id: 8795,
    tvmazeId: '917',
    title: 'Ringer',
    network: 'The CW',
    startYear: 2011,
    years: '2011–2012',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'CW cancelled after one season; the twin sisters\' identity swap and the murder conspiracy were left completely unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16078.jpg',
    note: '',
  },
  {
    id: 8796,
    tvmazeId: '6147',
    title: 'Rooster Teeth Animated Adventures',
    network: 'Rooster Teeth',
    startYear: 2011,
    years: '2011–2023',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/59540.jpg',
    note: '',
  },
  {
    id: 8797,
    tvmazeId: '18542',
    title: 'Sadie J',
    network: 'CBBC',
    startYear: 2011,
    years: '2011–2013',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/63/157974.jpg',
    note: '',
  },
  {
    id: 8798,
    tvmazeId: '20564',
    title: 'Scaredy Squirrel',
    network: 'YTV',
    startYear: 2011,
    years: '2011–2012',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/72/181755.jpg',
    note: '',
  },
  {
    id: 8799,
    tvmazeId: '40669',
    title: 'Scary Tales',
    network: '3net',
    startYear: 2011,
    years: '2011',
    genres: ['Horror', 'Mystery', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/378/946549.jpg',
    note: '',
  },
  {
    id: 8800,
    tvmazeId: '1813',
    title: 'Scott and Bailey',
    network: 'ITV1',
    startYear: 2011,
    years: '2011–2016',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/10/26204.jpg',
    note: '',
  },
  {
    id: 8801,
    tvmazeId: '18036',
    title: 'Secret Mountain Fort Awesome',
    network: 'Cartoon Network',
    startYear: 2011,
    years: '2011–2012',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/61/152869.jpg',
    note: '',
  },
  {
    id: 8802,
    tvmazeId: '150',
    title: 'Shameless',
    network: 'Paramount+ with Showtime',
    startYear: 2011,
    years: '2011–2021',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/486/1215661.jpg',
    note: '',
  },
  {
    id: 8803,
    tvmazeId: '3933',
    title: 'Silk',
    network: 'BBC One',
    startYear: 2011,
    years: '2011–2014',
    genres: ['Drama', 'Crime', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/48987.jpg',
    note: '',
  },
  {
    id: 8804,
    tvmazeId: '364',
    title: 'Single Ladies',
    network: 'BET Her',
    startYear: 2011,
    years: '2011–2015',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/2/5478.jpg',
    note: '',
  },
  {
    id: 8805,
    tvmazeId: '7503',
    title: 'Single White Spenny',
    network: 'Showcase',
    startYear: 2011,
    years: '2011',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/69136.jpg',
    note: '',
  },
  {
    id: 8806,
    tvmazeId: '2030',
    title: 'Sirens',
    network: 'Channel 4',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/28365.jpg',
    note: '',
  },
  {
    id: 8807,
    tvmazeId: '2008',
    title: 'Skins',
    network: 'MTV',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/28126.jpg',
    note: '',
  },
  {
    id: 8808,
    tvmazeId: '7640',
    title: 'SLiDE',
    network: 'FOX8',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/70361.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 367, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
