window.pageShows = [
  {
    id: 8833,
    tvmazeId: '7917',
    title: 'Underbelly NZ: Land of the Long Green Cloud',
    network: 'Three',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/72460.jpg',
    note: '',
  },
  {
    id: 8834,
    tvmazeId: '89',
    title: 'Unforgettable',
    network: 'A&E',
    startYear: 2011,
    years: '2011–2016',
    genres: ['Drama', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/0/663.jpg',
    note: '',
  },
  {
    id: 8835,
    tvmazeId: '512',
    title: 'Up All Night',
    network: 'NBC',
    startYear: 2011,
    years: '2011–2012',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/4/11150.jpg',
    note: '',
  },
  {
    id: 8836,
    tvmazeId: '3302',
    title: 'Vera',
    network: 'ITV1',
    startYear: 2011,
    years: '2011–2025',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/550/1376455.jpg',
    note: '',
  },
  {
    id: 8837,
    tvmazeId: '11958',
    title: 'Voltron Force',
    network: 'Nicktoons',
    startYear: 2011,
    years: '2011–2012',
    genres: ['Action', 'Fantasy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/40/100431.jpg',
    note: '',
  },
  {
    id: 8838,
    tvmazeId: '8435',
    title: 'Warehouse 13: Of Monsters and Men',
    network: 'Syfy.com',
    startYear: 2011,
    years: '2011',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/36/90666.jpg',
    note: '',
  },
  {
    id: 8839,
    tvmazeId: '37987',
    title: 'Waterloo Road Reunited',
    network: 'BBC iPlayer',
    startYear: 2011,
    years: '2011',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/162/406809.jpg',
    note: '',
  },
  {
    id: 8840,
    tvmazeId: '148',
    title: 'Web Therapy',
    network: 'Paramount+ with Showtime',
    startYear: 2011,
    years: '2011–2015',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/0/2036.jpg',
    note: '',
  },
  {
    id: 8841,
    tvmazeId: '7912',
    title: 'Wendy',
    network: 'YouTube',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Fantasy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/72447.jpg',
    note: '',
  },
  {
    id: 8842,
    tvmazeId: '4654',
    title: 'White Christmas',
    network: 'KBS1',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/52644.jpg',
    note: '',
  },
  {
    id: 8843,
    tvmazeId: '5794',
    title: 'White Van Man',
    network: 'BBC Three',
    startYear: 2011,
    years: '2011–2012',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/57824.jpg',
    note: '',
  },
  {
    id: 8844,
    tvmazeId: '413',
    title: 'Whitney',
    network: 'NBC',
    startYear: 2011,
    years: '2011–2013',
    genres: ['Comedy', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/2/6377.jpg',
    note: '',
  },
  {
    id: 8845,
    tvmazeId: '7233',
    title: 'Wild Boys',
    network: 'Seven Network',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Adventure', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/67233.jpg',
    note: '',
  },
  {
    id: 8846,
    tvmazeId: '556',
    title: 'Wilfred',
    network: 'FXX',
    startYear: 2011,
    years: '2011–2014',
    genres: ['Drama', 'Comedy', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/4/11623.jpg',
    note: '',
  },
  {
    id: 8847,
    tvmazeId: '8578',
    title: 'Wingin\' It',
    network: 'Nickelodeon',
    startYear: 2011,
    years: '2011–2012',
    genres: ['Comedy', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/30/76352.jpg',
    note: '',
  },
  {
    id: 8848,
    tvmazeId: '3159',
    title: 'Winners & Losers',
    network: 'Seven Network',
    startYear: 2011,
    years: '2011–2016',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/17/43230.jpg',
    note: '',
  },
  {
    id: 8849,
    tvmazeId: '14608',
    title: 'Without You',
    network: 'ITV1',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/49/123809.jpg',
    note: '',
  },
  {
    id: 8850,
    tvmazeId: '32260',
    title: 'Women in Love',
    network: 'BBC Four',
    startYear: 2011,
    years: '2011',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/128/322361.jpg',
    note: '',
  },
  {
    id: 8851,
    tvmazeId: '370',
    title: 'Workaholics',
    network: 'Comedy Central',
    startYear: 2011,
    years: '2011–2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/2/5510.jpg',
    note: '',
  },
  {
    id: 8852,
    tvmazeId: '7785',
    title: 'Working Class',
    network: 'CMT',
    startYear: 2011,
    years: '2011',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/71632.jpg',
    note: '',
  },
  {
    id: 8853,
    tvmazeId: '444',
    title: 'XIII: The Series',
    network: 'Showcase',
    startYear: 2011,
    years: '2011–2012',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/3/9073.jpg',
    note: '',
  },
  {
    id: 8854,
    tvmazeId: '39607',
    title: 'YooHoo & Friends',
    network: 'ABC',
    startYear: 2011,
    years: '2011–2012',
    genres: ['Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/173/434689.jpg',
    note: '',
  },
  {
    id: 8855,
    tvmazeId: '4562',
    title: 'Young James Herriot',
    network: 'BBC One',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/52150.jpg',
    note: '',
  },
  {
    id: 8856,
    tvmazeId: '4528',
    title: 'Zen',
    network: 'BBC One',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/52069.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 369, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 295, "ended": 12349}};
