window.pageShows = [
  {
    id: 7033,
    tvmazeId: '23125',
    title: 'Cell: The Web Series',
    network: 'Koldcast.tv',
    startYear: 2010,
    years: '2010',
    genres: ['Drama', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/86/215956.jpg',
    note: '',
  },
  {
    id: 7034,
    tvmazeId: '977',
    title: 'Chase',
    network: 'NBC',
    startYear: 2010,
    years: '2010–2011',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16501.jpg',
    note: '',
  },
  {
    id: 7035,
    tvmazeId: '59156',
    title: 'Chekhov Comedy Shorts',
    network: 'Sky Arts',
    startYear: 2010,
    years: '2010',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/378/945592.jpg',
    note: '',
  },
  {
    id: 7036,
    tvmazeId: '74999',
    title: 'Cheyenne Cinnamon and the Fantabulous Unicorn of Sugar Town Candy Fudge 2010',
    network: 'Adult Swim',
    startYear: 2010,
    years: '2010',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/506/1265781.jpg',
    note: '',
  },
  {
    id: 7037,
    tvmazeId: '3150',
    title: 'Childrens Hospital',
    network: 'Adult Swim',
    startYear: 2010,
    years: '2010–2016',
    genres: ['Comedy', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/17/43204.jpg',
    note: '',
  },
  {
    id: 7038,
    tvmazeId: '74627',
    title: 'Chuggington: Badge Quest',
    network: 'CBeebies',
    startYear: 2010,
    years: '2010–2012',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/503/1259728.jpg',
    note: '',
  },
  {
    id: 7039,
    tvmazeId: '1214',
    title: 'Come Fly with Me',
    network: 'BBC One',
    startYear: 2010,
    years: '2010–2011',
    genres: ['Comedy', 'Travel'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/17599.jpg',
    note: '',
  },
  {
    id: 7040,
    tvmazeId: '20582',
    title: 'Connor Undercover',
    network: 'Family Channel',
    startYear: 2010,
    years: '2010–2011',
    genres: ['Comedy', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/72/181960.jpg',
    note: '',
  },
  {
    id: 7041,
    tvmazeId: '7155',
    title: 'Cops L.A.C.',
    network: 'Nine Network',
    startYear: 2010,
    years: '2010',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/66944.jpg',
    note: '',
  },
  {
    id: 7042,
    tvmazeId: '46816',
    title: 'Cosmic Quantum Ray',
    network: 'Discovery Family',
    startYear: 2010,
    years: '2010',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/247/618231.jpg',
    note: '',
  },
  {
    id: 7043,
    tvmazeId: '345',
    title: 'Covert Affairs',
    network: 'USA Network',
    startYear: 2010,
    years: '2010–2014',
    genres: ['Drama', 'Action', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/545/1362912.jpg',
    note: '',
  },
  {
    id: 7044,
    tvmazeId: '28381',
    title: 'Cyanide & Happiness Shorts',
    network: 'YouTube',
    startYear: 2010,
    years: '2010–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/112/282062.jpg',
    note: '',
  },
  {
    id: 7045,
    tvmazeId: '4666',
    title: 'Dan for Mayor',
    network: 'CTV',
    startYear: 2010,
    years: '2010–2011',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/52758.jpg',
    note: '',
  },
  {
    id: 7046,
    tvmazeId: '1856',
    title: 'Dance Academy',
    network: 'ABC Entertains',
    startYear: 2010,
    years: '2010–2013',
    genres: ['Drama', 'Music', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/10/27269.jpg',
    note: '',
  },
  {
    id: 7047,
    tvmazeId: '15075',
    title: 'Dappers',
    network: 'BBC Three',
    startYear: 2010,
    years: '2010',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/51/128331.jpg',
    note: '',
  },
  {
    id: 7048,
    tvmazeId: '1758',
    title: 'DCI Banks',
    network: 'ITV1',
    startYear: 2010,
    years: '2010–2016',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/9/24589.jpg',
    note: '',
  },
  {
    id: 7049,
    tvmazeId: '28516',
    title: 'Dead Gorgeous',
    network: 'CBBC',
    startYear: 2010,
    years: '2010',
    genres: ['Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/113/284018.jpg',
    note: '',
  },
  {
    id: 7050,
    tvmazeId: '44725',
    title: 'Death Battle!',
    network: 'YouTube',
    startYear: 2010,
    years: '2010–',
    genres: ['Comedy', 'Action'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/353/884726.jpg',
    note: '',
  },
  {
    id: 7051,
    tvmazeId: '998',
    title: 'Detroit 1-8-7',
    network: 'ABC',
    startYear: 2010,
    years: '2010–2011',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16547.jpg',
    note: '',
  },
  {
    id: 7052,
    tvmazeId: '8390',
    title: 'Dick Figures',
    network: 'YouTube',
    startYear: 2010,
    years: '2010–2014',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/30/75267.jpg',
    note: '',
  },
  {
    id: 7053,
    tvmazeId: '9401',
    title: 'Dino Dan',
    network: 'Nick Jr.',
    startYear: 2010,
    years: '2010–2017',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/82640.jpg',
    note: '',
  },
  {
    id: 7054,
    tvmazeId: '35454',
    title: 'Dive',
    network: 'BBC Two',
    startYear: 2010,
    years: '2010',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/149/374338.jpg',
    note: '',
  },
  {
    id: 7055,
    tvmazeId: '73110',
    title: 'Doodlebops Rockin\' Road Show',
    network: 'CBC',
    startYear: 2010,
    years: '2010',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/489/1224936.jpg',
    note: '',
  },
  {
    id: 7056,
    tvmazeId: '251',
    title: 'Downton Abbey',
    network: 'ITV1',
    startYear: 2010,
    years: '2010–2015',
    genres: ['Drama', 'Family', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/1/4601.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 294, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 856, "cliffhanger": 286, "ended": 13542}};
