window.pageShows = [
  {
    id: 817,
    tvmazeId: '68430',
    title: 'Rescue: HI-Surf',
    network: 'FOX',
    startYear: 2024,
    years: '2024–2025',
    genres: ['Drama', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/536/1340937.jpg',
    note: '',
  },
  {
    id: 818,
    tvmazeId: '72575',
    title: 'Return to Paradise',
    network: 'ABC iview',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/590/1476703.jpg',
    note: '',
  },
  {
    id: 819,
    tvmazeId: '82357',
    title: 'Rhett & Link\'s Wonderhole',
    network: 'YouTube',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/554/1385015.jpg',
    note: '',
  },
  {
    id: 820,
    tvmazeId: '44042',
    title: 'Ripley',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/500/1252264.jpg',
    note: '',
  },
  {
    id: 821,
    tvmazeId: '64087',
    title: 'Rivals',
    network: 'Disney+',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/627/1567849.jpg',
    note: '',
  },
  {
    id: 822,
    tvmazeId: '74478',
    title: 'Roast Night',
    network: 'Seven Network',
    startYear: 2024,
    years: '2024–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 823,
    tvmazeId: '73545',
    title: 'Rock Paper Scissors',
    network: 'Nickelodeon',
    startYear: 2024,
    years: '2024–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/494/1236032.jpg',
    note: '',
  },
  {
    id: 824,
    tvmazeId: '82473',
    title: 'Roses and Ivy',
    network: 'Prime Video',
    startYear: 2024,
    years: '2024–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/555/1387591.jpg',
    note: '',
  },
  {
    id: 825,
    tvmazeId: '80616',
    title: 'Rubble\'s Big Builds',
    network: '5',
    startYear: 2024,
    years: '2024',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 826,
    tvmazeId: '77838',
    title: 'Rumors',
    network: 'Tubi',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/523/1309751.jpg',
    note: '',
  },
  {
    id: 827,
    tvmazeId: '79204',
    title: 'RZR',
    network: 'YouTube',
    startYear: 2024,
    years: '2024–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/565/1412785.jpg',
    note: '',
  },
  {
    id: 828,
    tvmazeId: '63508',
    title: 'Sanctuary: A Witch\'s Tale',
    network: 'AMC+',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Mystery', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/605/1512734.jpg',
    note: '',
  },
  {
    id: 829,
    tvmazeId: '64949',
    title: 'Sausage Party: Foodtopia',
    network: 'Prime Video',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/577/1444694.jpg',
    note: '',
  },
  {
    id: 830,
    tvmazeId: '74425',
    title: 'Say Nothing',
    network: 'Hulu',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/543/1358054.jpg',
    note: '',
  },
  {
    id: 831,
    tvmazeId: '80538',
    title: 'Secrets on Maple Street',
    network: 'Lifetime Movies',
    startYear: 2024,
    years: '2024',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 832,
    tvmazeId: '50165',
    title: 'Senna',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/545/1364921.jpg',
    note: '',
  },
  {
    id: 833,
    tvmazeId: '42984',
    title: 'Sexy Beast',
    network: 'Paramount+',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/501/1253398.jpg',
    note: '',
  },
  {
    id: 834,
    tvmazeId: '66501',
    title: 'Shardlake',
    network: 'Disney+',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Crime', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/513/1283291.jpg',
    note: '',
  },
  {
    id: 835,
    tvmazeId: '80173',
    title: 'Shatter Belt',
    network: 'Prime Video',
    startYear: 2024,
    years: '2024',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/540/1351152.jpg',
    note: '',
  },
  {
    id: 836,
    tvmazeId: '37336',
    title: 'Shōgun',
    network: 'Hulu',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Adventure', 'History'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/506/1265637.jpg',
    note: '',
  },
  {
    id: 837,
    tvmazeId: '71913',
    title: 'Sight Unseen',
    network: 'CTV',
    startYear: 2024,
    years: '2024–2025',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/551/1378351.jpg',
    note: '',
  },
  {
    id: 838,
    tvmazeId: '79638',
    title: 'Smoggie Queens',
    network: 'BBC iPlayer',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/545/1364187.jpg',
    note: '',
  },
  {
    id: 839,
    tvmazeId: '75105',
    title: 'So Long, Marianne',
    network: 'NRK TV',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/536/1342159.jpg',
    note: '',
  },
  {
    id: 840,
    tvmazeId: '68920',
    title: 'Spent',
    network: 'BBC iPlayer',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/526/1316664.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 35, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 334, "cliffhanger": 235, "ended": 13701}};
