window.pageShows = [
  {
    id: 8329,
    tvmazeId: '1140',
    title: 'Gates',
    network: 'Sky Witness',
    startYear: 2012,
    years: '2012',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17324.jpg',
    note: '',
  },
  {
    id: 8330,
    tvmazeId: '236',
    title: 'GCB',
    network: 'ABC',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/84/212122.jpg',
    note: '',
  },
  {
    id: 8331,
    tvmazeId: '89039',
    title: 'Genesis 7',
    network: 'FAWESOME',
    startYear: 2012,
    years: '2012–2013',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 8332,
    tvmazeId: '4742',
    title: 'Ghost',
    network: 'SBS',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/53052.jpg',
    note: '',
  },
  {
    id: 8333,
    tvmazeId: '64187',
    title: 'Ghosts of Time',
    network: 'Seven Network',
    startYear: 2012,
    years: '2012',
    genres: ['Children', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/422/1056865.jpg',
    note: '',
  },
  {
    id: 8334,
    tvmazeId: '9895',
    title: 'Girl vs. Boy',
    network: 'TVNZ 2',
    startYear: 2012,
    years: '2012–2014',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/34/85147.jpg',
    note: '',
  },
  {
    id: 8335,
    tvmazeId: '139',
    title: 'Girls',
    network: 'HBO',
    startYear: 2012,
    years: '2012–2017',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/78286.jpg',
    note: '',
  },
  {
    id: 8336,
    tvmazeId: '230',
    title: 'Go On',
    network: 'NBC',
    startYear: 2012,
    years: '2012–2013',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/1/3773.jpg',
    note: '',
  },
  {
    id: 8337,
    tvmazeId: '9894',
    title: 'Golden',
    network: 'Three',
    startYear: 2012,
    years: '2012',
    genres: ['Comedy', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/34/85146.jpg',
    note: '',
  },
  {
    id: 8338,
    tvmazeId: '4335',
    title: 'Good Cop',
    network: 'BBC One',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/51424.jpg',
    note: '',
  },
  {
    id: 8339,
    tvmazeId: '7504',
    title: 'Good God',
    network: 'HBO',
    startYear: 2012,
    years: '2012',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/69137.jpg',
    note: '',
  },
  {
    id: 8340,
    tvmazeId: '396',
    title: 'Gravity Falls',
    network: 'Disney XD',
    startYear: 2012,
    years: '2012–2016',
    genres: ['Adventure', 'Mystery', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/2/6140.jpg',
    note: '',
  },
  {
    id: 8341,
    tvmazeId: '17758',
    title: 'Guess How Much I Love You',
    network: 'Disney Channel',
    startYear: 2012,
    years: '2012–2016',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/59/149567.jpg',
    note: '',
  },
  {
    id: 8342,
    tvmazeId: '2093',
    title: 'Guys with Kids',
    network: 'NBC',
    startYear: 2012,
    years: '2012–2013',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/29070.jpg',
    note: '',
  },
  {
    id: 8343,
    tvmazeId: '7406',
    title: 'H+',
    network: 'YouTube',
    startYear: 2012,
    years: '2012–2013',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/68213.jpg',
    note: '',
  },
  {
    id: 8344,
    tvmazeId: '1017',
    title: 'Halo 4: Forward Unto Dawn',
    network: 'Machinima',
    startYear: 2012,
    years: '2012',
    genres: ['Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/402/1006821.jpg',
    note: '',
  },
  {
    id: 8345,
    tvmazeId: '37324',
    title: 'Happy Endings: Happy Rides',
    network: 'ABC.com',
    startYear: 2012,
    years: '2012',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/159/398646.jpg',
    note: '',
  },
  {
    id: 8346,
    tvmazeId: '36724',
    title: 'Harder Than It Looks',
    network: 'YouTube',
    startYear: 2012,
    years: '2012',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/155/389021.jpg',
    note: '',
  },
  {
    id: 8347,
    tvmazeId: '1102',
    title: 'Hatfields & McCoys',
    network: 'History',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Romance', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17230.jpg',
    note: '',
  },
  {
    id: 8348,
    tvmazeId: '4714',
    title: 'Hebburn',
    network: 'BBC Two',
    startYear: 2012,
    years: '2012–2013',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/52980.jpg',
    note: '',
  },
  {
    id: 8349,
    tvmazeId: '6976',
    title: 'High Maintenance',
    network: 'Vimeo',
    startYear: 2012,
    years: '2012–2015',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/66/165674.jpg',
    note: '',
  },
  {
    id: 8350,
    tvmazeId: '1242',
    title: 'Hit & Miss',
    network: 'Sky Atlantic',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/41/104210.jpg',
    note: '',
  },
  {
    id: 8351,
    tvmazeId: '6875',
    title: 'Holliston',
    network: 'Syndication',
    startYear: 2012,
    years: '2012–2013',
    genres: ['Comedy', 'Horror', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/25/64854.jpg',
    note: '',
  },
  {
    id: 8352,
    tvmazeId: '983',
    title: 'Hollywood Heights',
    network: 'nick@nite',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Music', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/53/134485.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 348, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
