window.pageShows = [
  {
    id: 7249,
    tvmazeId: '4038',
    title: 'The Adventures of Puss in Boots',
    network: 'Netflix',
    startYear: 2015,
    years: '2015–2018',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/101/254447.jpg',
    note: '',
  },
  {
    id: 7250,
    tvmazeId: '2335',
    title: 'The Art of Foley',
    network: 'Channel 4',
    startYear: 2015,
    years: '2015',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/480/1200256.jpg',
    note: '',
  },
  {
    id: 7251,
    tvmazeId: '2742',
    title: 'The Art of More',
    network: 'Crackle',
    startYear: 2015,
    years: '2015–2016',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/480/1200542.jpg',
    note: '',
  },
  {
    id: 7252,
    tvmazeId: '609',
    title: 'The Astronaut Wives Club',
    network: 'ABC',
    startYear: 2015,
    years: '2015',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/12/30480.jpg',
    note: '',
  },
  {
    id: 7253,
    tvmazeId: '2609',
    title: 'The Aurora Teagarden Mysteries',
    network: 'Hallmark Mystery',
    startYear: 2015,
    years: '2015–2022',
    genres: ['Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/142/355616.jpg',
    note: '',
  },
  {
    id: 7254,
    tvmazeId: '47191',
    title: 'The Ave',
    network: 'Prime Video',
    startYear: 2015,
    years: '2015–2018',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/251/629024.jpg',
    note: '',
  },
  {
    id: 7255,
    tvmazeId: '2753',
    title: 'The Bastard Executioner',
    network: 'FX',
    startYear: 2015,
    years: '2015',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/14/37130.jpg',
    note: '',
  },
  {
    id: 7256,
    tvmazeId: '6126',
    title: 'The Beautiful Lie',
    network: 'ABC',
    startYear: 2015,
    years: '2015',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/24/60221.jpg',
    note: '',
  },
  {
    id: 7257,
    tvmazeId: '3014',
    title: 'The Big Leaf',
    network: 'TV One',
    startYear: 2015,
    years: '2015',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/52/130341.jpg',
    note: '',
  },
  {
    id: 7258,
    tvmazeId: '4010',
    title: 'The Book of Negroes',
    network: 'CBC',
    startYear: 2015,
    years: '2015',
    genres: ['Drama', 'War', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/49320.jpg',
    note: '',
  },
  {
    id: 7259,
    tvmazeId: '1822',
    title: 'The Brink',
    network: 'HBO',
    startYear: 2015,
    years: '2015',
    genres: ['Comedy', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/29606.jpg',
    note: '',
  },
  {
    id: 7260,
    tvmazeId: '2470',
    title: 'The Carmichael Show',
    network: 'NBC',
    startYear: 2015,
    years: '2015–2017',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/330/825918.jpg',
    note: '',
  },
  {
    id: 7261,
    tvmazeId: '2009',
    title: 'The Casual Vacancy',
    network: 'BBC One',
    startYear: 2015,
    years: '2015',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/28135.jpg',
    note: '',
  },
  {
    id: 7262,
    tvmazeId: '26140',
    title: 'The Choo Choo Bob Show',
    network: 'Qubo',
    startYear: 2015,
    years: '2015',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/102/257104.jpg',
    note: '',
  },
  {
    id: 7263,
    tvmazeId: '1594',
    title: 'The Comedians',
    network: 'FX',
    startYear: 2015,
    years: '2015',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/9/23777.jpg',
    note: '',
  },
  {
    id: 7264,
    tvmazeId: '8376',
    title: 'The Coroner',
    network: 'BBC One',
    startYear: 2015,
    years: '2015–2016',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/58/146123.jpg',
    note: '',
  },
  {
    id: 7265,
    tvmazeId: '17792',
    title: 'The Darkside',
    network: 'ABC Family',
    startYear: 2015,
    years: '2015',
    genres: ['Drama', 'Comedy', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 7266,
    tvmazeId: '47326',
    title: 'The Day Henry Met',
    network: 'Nick Jr.',
    startYear: 2015,
    years: '2015',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/252/631830.jpg',
    note: '',
  },
  {
    id: 7267,
    tvmazeId: '14049',
    title: 'The Deep',
    network: 'CBBC',
    startYear: 2015,
    years: '2015–2022',
    genres: ['Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: 'CBBC animated series that ran three seasons and concluded its story.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/48/120277.jpg',
    note: '',
  },
  {
    id: 7268,
    tvmazeId: '2334',
    title: 'The Delivery Man',
    network: 'ITV1',
    startYear: 2015,
    years: '2015',
    genres: ['Comedy', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/137/342992.jpg',
    note: '',
  },
  {
    id: 7269,
    tvmazeId: '9880',
    title: 'The Divorce',
    network: 'ABC',
    startYear: 2015,
    years: '2015',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/34/85019.jpg',
    note: '',
  },
  {
    id: 7270,
    tvmazeId: '1711',
    title: 'The Dovekeepers',
    network: 'CBS',
    startYear: 2015,
    years: '2015',
    genres: ['Drama', 'Romance', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/9/23998.jpg',
    note: '',
  },
  {
    id: 7271,
    tvmazeId: '72594',
    title: 'The Drive',
    network: 'YouTube',
    startYear: 2015,
    years: '2015–2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 7272,
    tvmazeId: '3257',
    title: 'The Enfield Haunting',
    network: 'Sky Witness',
    startYear: 2015,
    years: '2015',
    genres: ['Drama', 'Horror', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/482/1206651.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 303, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
