window.pageShows = [
  {
    id: 10757,
    tvmazeId: '33013',
    title: 'The Stones',
    network: 'CBS',
    startYear: 2004,
    years: '2004',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/133/333194.jpg',
    note: '',
  },
  {
    id: 10758,
    tvmazeId: '43279',
    title: 'The Strangerhood',
    network: 'Rooster Teeth',
    startYear: 2004,
    years: '2004–2015',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/207/518494.jpg',
    note: '',
  },
  {
    id: 10759,
    tvmazeId: '63533',
    title: 'The Sugar Creek Gang',
    network: 'The Roku Channel',
    startYear: 2004,
    years: '2004–2005',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/418/1046796.jpg',
    note: '',
  },
  {
    id: 10760,
    tvmazeId: '70132',
    title: 'The Tofus',
    network: 'Télé Toon',
    startYear: 2004,
    years: '2004–2005',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/470/1176233.jpg',
    note: '',
  },
  {
    id: 10761,
    tvmazeId: '69461',
    title: 'The Way Things Work',
    network: 'CBBC',
    startYear: 2004,
    years: '2004',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/466/1165225.jpg',
    note: '',
  },
  {
    id: 10762,
    tvmazeId: '4497',
    title: 'The Worst Week of My Life',
    network: 'BBC One',
    startYear: 2004,
    years: '2004–2006',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/51996.jpg',
    note: '',
  },
  {
    id: 10763,
    tvmazeId: '4111',
    title: 'The Wrong Coast',
    network: 'Crave',
    startYear: 2004,
    years: '2004',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/49958.jpg',
    note: '',
  },
  {
    id: 10764,
    tvmazeId: '7502',
    title: 'This Is Wonderland',
    network: 'CBC',
    startYear: 2004,
    years: '2004–2006',
    genres: ['Drama', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/69132.jpg',
    note: '',
  },
  {
    id: 10765,
    tvmazeId: '68488',
    title: 'This Just In',
    network: 'Spike',
    startYear: 2004,
    years: '2004',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 10766,
    tvmazeId: '45075',
    title: 'ToddWorld',
    network: 'TLC',
    startYear: 2004,
    years: '2004–2008',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/224/561040.jpg',
    note: '',
  },
  {
    id: 10767,
    tvmazeId: '6243',
    title: 'Tom Goes to the Mayor',
    network: 'Cartoon Network',
    startYear: 2004,
    years: '2004–2006',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/59996.jpg',
    note: '',
  },
  {
    id: 10768,
    tvmazeId: '4087',
    title: 'Top Buzzer',
    network: 'MTV',
    startYear: 2004,
    years: '2004–2005',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/49877.jpg',
    note: '',
  },
  {
    id: 10769,
    tvmazeId: '2024',
    title: 'Touching Evil',
    network: 'USA Network',
    startYear: 2004,
    years: '2004',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/28284.jpg',
    note: '',
  },
  {
    id: 10770,
    tvmazeId: '33671',
    title: 'Traffic',
    network: 'USA Network',
    startYear: 2004,
    years: '2004',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/137/343168.jpg',
    note: '',
  },
  {
    id: 10771,
    tvmazeId: '4108',
    title: 'Tripping the Rift',
    network: 'Syfy',
    startYear: 2004,
    years: '2004–2007',
    genres: ['Comedy', 'Fantasy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/49916.jpg',
    note: '',
  },
  {
    id: 10772,
    tvmazeId: '6289',
    title: 'Unfabulous',
    network: 'Nickelodeon',
    startYear: 2004,
    years: '2004–2007',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/24/60288.jpg',
    note: '',
  },
  {
    id: 10773,
    tvmazeId: '473',
    title: 'Veronica Mars',
    network: 'Hulu',
    startYear: 2004,
    years: '2004–2019',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Originally cancelled after three seasons; a later Kickstarter film and Hulu revival provided partial closure, though the revival series also ended without a fully satisfying conclusion.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/9/24539.jpg',
    note: '',
  },
  {
    id: 10774,
    tvmazeId: '87023',
    title: 'Vitaminix',
    network: 'Qubo',
    startYear: 2004,
    years: '2004–2007',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/587/1467796.jpg',
    note: '',
  },
  {
    id: 10775,
    tvmazeId: '6570',
    title: 'W.I.T.C.H.',
    network: 'ABC',
    startYear: 2004,
    years: '2004–2006',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/24/62386.jpg',
    note: '',
  },
  {
    id: 10776,
    tvmazeId: '15039',
    title: 'Wicked Science',
    network: 'Network 10',
    startYear: 2004,
    years: '2004–2006',
    genres: ['Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/51/128000.jpg',
    note: '',
  },
  {
    id: 10777,
    tvmazeId: '5883',
    title: 'Winx Club',
    network: 'Nickelodeon',
    startYear: 2004,
    years: '2004–2019',
    genres: ['Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/273/684918.jpg',
    note: '',
  },
  {
    id: 10778,
    tvmazeId: '1042',
    title: 'Wonderfalls',
    network: 'VisionTV',
    startYear: 2004,
    years: '2004',
    genres: ['Drama', 'Comedy', 'Fantasy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Fox cancelled after four episodes (all 13 produced); Jaye Tyler\'s inanimate-object conversations were left mid-story.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16927.jpg',
    note: '',
  },
  {
    id: 10779,
    tvmazeId: '18356',
    title: 'Zeroman',
    network: 'Cartoon Network',
    startYear: 2004,
    years: '2004–2005',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/62/156037.jpg',
    note: '',
  },
  {
    id: 10780,
    tvmazeId: '61682',
    title: 'Zixx',
    network: 'YTV',
    startYear: 2004,
    years: '2004–2009',
    genres: ['Family', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/405/1013042.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 449, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
