window.pageShows = [
  {
    id: 1201,
    tvmazeId: '68083',
    title: 'Mystery Lane checkifcancelled',
    network: 'CITV',
    startYear: 2023,
    years: '2023–',
    genres: [],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/457/1143685.jpg',
    note: '',
  },
  {
    id: 1202,
    tvmazeId: '60547',
    title: 'NCIS: Sydney',
    network: 'Paramount+',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/591/1479848.jpg',
    note: '',
  },
  {
    id: 1203,
    tvmazeId: '65097',
    title: 'Neon checkifcancelled',
    network: 'Netflix',
    startYear: 2023,
    years: '2023–',
    genres: ['Comedy', 'Music'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/481/1203655.jpg',
    note: '',
  },
  {
    id: 1204,
    tvmazeId: '73549',
    title: 'Nesting',
    network: 'Crave',
    startYear: 2023,
    years: '2023–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/494/1236339.jpg',
    note: '',
  },
  {
    id: 1205,
    tvmazeId: '71416',
    title: 'Night Bloomers',
    network: 'SBS On Demand',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Horror', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/482/1206387.jpg',
    note: '',
  },
  {
    id: 1206,
    tvmazeId: '52482',
    title: 'Night Court',
    network: 'NBC',
    startYear: 2023,
    years: '2023–2025',
    genres: ['Comedy', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/548/1372474.jpg',
    note: '',
  },
  {
    id: 1207,
    tvmazeId: '68439',
    title: 'Ninjago: Dragons Rising',
    network: 'Netflix',
    startYear: 2023,
    years: '2023–',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/463/1157968.jpg',
    note: '',
  },
  {
    id: 1208,
    tvmazeId: '60889',
    title: 'No Escape checkifcancelled',
    network: 'Paramount+',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/462/1155106.jpg',
    note: '',
  },
  {
    id: 1209,
    tvmazeId: '59117',
    title: 'Nolly',
    network: 'ITVX',
    startYear: 2023,
    years: '2023',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/445/1112525.jpg',
    note: '',
  },
  {
    id: 1210,
    tvmazeId: '63856',
    title: 'North Shore checkifcancelled',
    network: 'Network 10',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/460/1150855.jpg',
    note: '',
  },
  {
    id: 1211,
    tvmazeId: '73369',
    title: 'Northern Lights',
    network: 'TG4',
    startYear: 2023,
    years: '2023',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/492/1231039.jpg',
    note: '',
  },
  {
    id: 1212,
    tvmazeId: '60502',
    title: 'Not Dead Yet',
    network: 'ABC',
    startYear: 2023,
    years: '2023–2024',
    genres: ['Comedy', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/507/1267851.jpg',
    note: '',
  },
  {
    id: 1213,
    tvmazeId: '66916',
    title: 'Not Even checkifcancelled',
    network: 'Sky Go',
    startYear: 2023,
    years: '2023–',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/446/1115908.jpg',
    note: '',
  },
  {
    id: 1214,
    tvmazeId: '68889',
    title: 'Not Quite Narwhal',
    network: 'Netflix',
    startYear: 2023,
    years: '2023–2024',
    genres: ['Children', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/500/1252215.jpg',
    note: '',
  },
  {
    id: 1215,
    tvmazeId: '66285',
    title: 'Obituary',
    network: 'RTÉ Player',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/592/1481353.jpg',
    note: '',
  },
  {
    id: 1216,
    tvmazeId: '61892',
    title: 'Obliterated',
    network: 'Netflix',
    startYear: 2023,
    years: '2023',
    genres: ['Comedy', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/489/1224776.jpg',
    note: '',
  },
  {
    id: 1217,
    tvmazeId: '61093',
    title: 'Obsession',
    network: 'Netflix',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Romance', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/454/1136694.jpg',
    note: '',
  },
  {
    id: 1218,
    tvmazeId: '67096',
    title: 'One Night',
    network: 'Paramount+',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/473/1184490.jpg',
    note: '',
  },
  {
    id: 1219,
    tvmazeId: '46065',
    title: 'One Piece',
    network: 'Netflix',
    startYear: 2023,
    years: '2023–',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/617/1543011.jpg',
    note: '',
  },
  {
    id: 1220,
    tvmazeId: '67665',
    title: 'Only You: An Animated Shorts Collection',
    network: 'HBO Max',
    startYear: 2023,
    years: '2023–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/453/1133950.jpg',
    note: '',
  },
  {
    id: 1221,
    tvmazeId: '78827',
    title: 'Open Season: Call of Nature',
    network: 'ABC iview',
    startYear: 2023,
    years: '2023–2024',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/530/1326291.jpg',
    note: '',
  },
  {
    id: 1222,
    tvmazeId: '46326',
    title: 'Painkiller',
    network: 'Netflix',
    startYear: 2023,
    years: '2023',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/493/1234924.jpg',
    note: '',
  },
  {
    id: 1223,
    tvmazeId: '72992',
    title: 'Paper Dolls checkifcancelled',
    network: 'Paramount+',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Music'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/490/1225589.jpg',
    note: '',
  },
  {
    id: 1224,
    tvmazeId: '55648',
    title: 'Pariah Nexus',
    network: 'Warhammer+',
    startYear: 2023,
    years: '2023',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/407/1018687.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 51, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 856, "cliffhanger": 286, "ended": 13542}};
