window.pageShows = [
  {
    id: 8041,
    tvmazeId: '3804',
    title: 'Pat & Cabbage',
    network: 'ITV1',
    startYear: 2013,
    years: '2013',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/47975.jpg',
    note: '',
  },
  {
    id: 8042,
    tvmazeId: '894',
    title: 'Paw Patrol',
    network: 'TVO',
    startYear: 2013,
    years: '2013–',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/608/1521295.jpg',
    note: '',
  },
  {
    id: 8043,
    tvmazeId: '22655',
    title: 'PAYDAY: The Web Series',
    network: 'YouTube',
    startYear: 2013,
    years: '2013',
    genres: ['Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/83/209474.jpg',
    note: '',
  },
  {
    id: 8044,
    tvmazeId: '269',
    title: 'Peaky Blinders',
    network: 'BBC One',
    startYear: 2013,
    years: '2013–',
    genres: ['Drama', 'Crime', 'History'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/48/122213.jpg',
    note: '',
  },
  {
    id: 8045,
    tvmazeId: '698',
    title: 'Peg + Cat',
    network: 'PBS',
    startYear: 2013,
    years: '2013–2018',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/5/14998.jpg',
    note: '',
  },
  {
    id: 8046,
    tvmazeId: '36275',
    title: 'Planet Cosmo',
    network: 'RTÉ2',
    startYear: 2013,
    years: '2013',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/153/382971.jpg',
    note: '',
  },
  {
    id: 8047,
    tvmazeId: '4681',
    title: 'Played',
    network: 'CTV',
    startYear: 2013,
    years: '2013',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/52816.jpg',
    note: '',
  },
  {
    id: 8048,
    tvmazeId: '3306',
    title: 'Please Like Me',
    network: 'ABC Family',
    startYear: 2013,
    years: '2013–2016',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/17/43990.jpg',
    note: '',
  },
  {
    id: 8049,
    tvmazeId: '313',
    title: 'Plebs',
    network: 'ITV2',
    startYear: 2013,
    years: '2013–2022',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/153/382980.jpg',
    note: '',
  },
  {
    id: 8050,
    tvmazeId: '28532',
    title: 'Power Games: The Packer-Murdoch Story',
    network: 'Nine Network',
    startYear: 2013,
    years: '2013',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/617/1542627.jpg',
    note: '',
  },
  {
    id: 8051,
    tvmazeId: '20242',
    title: 'Privates',
    network: 'BBC One',
    startYear: 2013,
    years: '2013',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/71/179185.jpg',
    note: '',
  },
  {
    id: 8052,
    tvmazeId: '20041',
    title: 'Project: S.E.R.A.',
    network: 'YouTube',
    startYear: 2013,
    years: '2013',
    genres: ['Action', 'Crime', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/70/176950.jpg',
    note: '',
  },
  {
    id: 8053,
    tvmazeId: '31167',
    title: 'Psychobitches',
    network: 'Sky Arts',
    startYear: 2013,
    years: '2013–2014',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/124/310987.jpg',
    note: '',
  },
  {
    id: 8054,
    tvmazeId: '12127',
    title: 'Q Pootle 5',
    network: 'CBeebies',
    startYear: 2013,
    years: '2013–2014',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/40/101781.jpg',
    note: '',
  },
  {
    id: 8055,
    tvmazeId: '29160',
    title: 'Quick Cuts',
    network: 'BBC Four',
    startYear: 2013,
    years: '2013',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/116/291223.jpg',
    note: '',
  },
  {
    id: 8056,
    tvmazeId: '4034',
    title: 'Quick Draw',
    network: 'Hulu',
    startYear: 2013,
    years: '2013–2014',
    genres: ['Comedy', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/49601.jpg',
    note: '',
  },
  {
    id: 8057,
    tvmazeId: '3805',
    title: 'Rabbids Invasion',
    network: 'Nicktoons',
    startYear: 2013,
    years: '2013–2019',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/47976.jpg',
    note: '',
  },
  {
    id: 8058,
    tvmazeId: '225',
    title: 'Ravenswood',
    network: 'Freeform',
    startYear: 2013,
    years: '2013–2014',
    genres: ['Drama', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/1/3700.jpg',
    note: '',
  },
  {
    id: 8059,
    tvmazeId: '152',
    title: 'Ray Donovan',
    network: 'Paramount+ with Showtime',
    startYear: 2013,
    years: '2013–2022',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/212/531511.jpg',
    note: '',
  },
  {
    id: 8060,
    tvmazeId: '221',
    title: 'Rectify',
    network: 'SundanceTV',
    startYear: 2013,
    years: '2013–2016',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: 'SundanceTV gave the series a proper finale after four seasons.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/1/3655.jpg',
    note: '',
  },
  {
    id: 8061,
    tvmazeId: '1225',
    title: 'Red Widow',
    network: 'ABC',
    startYear: 2013,
    years: '2013',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/17647.jpg',
    note: '',
  },
  {
    id: 8062,
    tvmazeId: '9892',
    title: 'Reef Doctors',
    network: '10 Peach Comedy',
    startYear: 2013,
    years: '2013',
    genres: ['Drama', 'Adventure', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/34/85140.jpg',
    note: '',
  },
  {
    id: 8063,
    tvmazeId: '88',
    title: 'Reign',
    network: 'The CW',
    startYear: 2013,
    years: '2013–2017',
    genres: ['Drama', 'Romance', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: 'CW ran for four seasons and ended with Mary Queen of Scots\' execution, a historically grounded conclusion.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/81/204119.jpg',
    note: '',
  },
  {
    id: 8064,
    tvmazeId: '51161',
    title: 'Revolution: Enemies of the State',
    network: 'NBC.com',
    startYear: 2013,
    years: '2013',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  }
];
window.pageMetadata = {"page": 336, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
