window.pageShows = [
  {
    id: 13585,
    tvmazeId: '6276',
    title: 'The Fantastic Journey',
    network: 'NBC',
    startYear: 1977,
    years: '1977',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/530/1325157.jpg',
    note: '',
  },
  {
    id: 13586,
    tvmazeId: '31021',
    title: 'The Fitzpatricks',
    network: 'CBS',
    startYear: 1977,
    years: '1977',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/123/308998.jpg',
    note: '',
  },
  {
    id: 13587,
    tvmazeId: '7902',
    title: 'The Flumps',
    network: 'BBC One',
    startYear: 1977,
    years: '1977',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/72340.jpg',
    note: '',
  },
  {
    id: 13588,
    tvmazeId: '4051',
    title: 'The Hardy Boys/Nancy Drew Mysteries',
    network: 'ABC',
    startYear: 1977,
    years: '1977–1979',
    genres: ['Action', 'Adventure', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/49650.jpg',
    note: '',
  },
  {
    id: 13589,
    tvmazeId: '2151',
    title: 'The Incredible Hulk',
    network: 'CBS',
    startYear: 1977,
    years: '1977–1982',
    genres: ['Action', 'Fantasy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/12/30048.jpg',
    note: '',
  },
  {
    id: 13590,
    tvmazeId: '24309',
    title: 'The Kallikaks',
    network: 'NBC',
    startYear: 1977,
    years: '1977',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/92/231081.jpg',
    note: '',
  },
  {
    id: 13591,
    tvmazeId: '14914',
    title: 'The Life and Times of Grizzly Adams',
    network: 'NBC',
    startYear: 1977,
    years: '1977–1978',
    genres: ['Adventure', 'Children', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/50/127141.jpg',
    note: '',
  },
  {
    id: 13592,
    tvmazeId: '1484',
    title: 'The Love Boat',
    network: 'ABC',
    startYear: 1977,
    years: '1977–1986',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/8/21183.jpg',
    note: '',
  },
  {
    id: 13593,
    tvmazeId: '21036',
    title: 'The Mackinnons',
    network: 'BBC One',
    startYear: 1977,
    years: '1977',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 13594,
    tvmazeId: '19752',
    title: 'The New Adventures of Batman',
    network: 'CBS',
    startYear: 1977,
    years: '1977',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/69/174489.jpg',
    note: '',
  },
  {
    id: 13595,
    tvmazeId: '63281',
    title: 'The New Archie and Sabrina Hour',
    network: 'NBC',
    startYear: 1977,
    years: '1977',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/417/1043142.jpg',
    note: '',
  },
  {
    id: 13596,
    tvmazeId: '71672',
    title: 'The Norman Conquests',
    network: 'PBS',
    startYear: 1977,
    years: '1977',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/479/1198628.jpg',
    note: '',
  },
  {
    id: 13597,
    tvmazeId: '16096',
    title: 'The Oregon Trail',
    network: 'NBC',
    startYear: 1977,
    years: '1977',
    genres: ['Drama', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/53/134692.jpg',
    note: '',
  },
  {
    id: 13598,
    tvmazeId: '30773',
    title: 'The Paper Lads',
    network: 'ITV1',
    startYear: 1977,
    years: '1977–1979',
    genres: ['Drama', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/122/305663.jpg',
    note: '',
  },
  {
    id: 13599,
    tvmazeId: '7737',
    title: 'The Professionals',
    network: 'ITV1',
    startYear: 1977,
    years: '1977–1983',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/469/1172928.jpg',
    note: '',
  },
  {
    id: 13600,
    tvmazeId: '17681',
    title: 'The Red Hand Gang',
    network: 'NBC',
    startYear: 1977,
    years: '1977',
    genres: ['Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/59/148619.jpg',
    note: '',
  },
  {
    id: 13601,
    tvmazeId: '9915',
    title: 'The Robonic Stooges',
    network: 'CBS',
    startYear: 1977,
    years: '1977–1978',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/34/85207.jpg',
    note: '',
  },
  {
    id: 13602,
    tvmazeId: '55411',
    title: 'The San Pedro Beach Bums',
    network: 'ABC',
    startYear: 1977,
    years: '1977',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/477/1193303.jpg',
    note: '',
  },
  {
    id: 13603,
    tvmazeId: '20746',
    title: 'The Space Sentinels',
    network: 'NBC',
    startYear: 1977,
    years: '1977',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/183523.jpg',
    note: '',
  },
  {
    id: 13604,
    tvmazeId: '36510',
    title: 'The Upchat Line',
    network: 'ITV1',
    startYear: 1977,
    years: '1977',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/154/385953.jpg',
    note: '',
  },
  {
    id: 13605,
    tvmazeId: '4132',
    title: 'Three\'s Company',
    network: 'ABC',
    startYear: 1977,
    years: '1977–1984',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/50015.jpg',
    note: '',
  },
  {
    id: 13606,
    tvmazeId: '40692',
    title: 'Thunder',
    network: 'NBC',
    startYear: 1977,
    years: '1977',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/544/1360872.jpg',
    note: '',
  },
  {
    id: 13607,
    tvmazeId: '25394',
    title: 'Treasure Island',
    network: 'BBC One',
    startYear: 1977,
    years: '1977',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/98/246877.jpg',
    note: '',
  },
  {
    id: 13608,
    tvmazeId: '53393',
    title: 'Undercover Elephant',
    network: 'NBC',
    startYear: 1977,
    years: '1977',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/295/739640.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 567, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 824, "cliffhanger": 237, "ended": 13574}};
