window.pageShows = [
  {
    id: 8453,
    tvmazeId: '4896',
    title: 'The Moodys',
    network: 'ABC',
    startYear: 2012,
    years: '2012–2014',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/53549.jpg',
    note: '',
  },
  {
    id: 8454,
    tvmazeId: '33399',
    title: 'The Most Popular Girls in School',
    network: 'YouTube',
    startYear: 2012,
    years: '2012–2017',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/135/338558.jpg',
    note: '',
  },
  {
    id: 8455,
    tvmazeId: '23349',
    title: 'The Mystery of Edwin Drood',
    network: 'BBC Two',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/87/219192.jpg',
    note: '',
  },
  {
    id: 8456,
    tvmazeId: '229',
    title: 'The Neighbors',
    network: 'ABC',
    startYear: 2012,
    years: '2012–2014',
    genres: ['Comedy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/1/3763.jpg',
    note: '',
  },
  {
    id: 8457,
    tvmazeId: '235',
    title: 'The New Normal',
    network: 'NBC',
    startYear: 2012,
    years: '2012–2013',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/1/3817.jpg',
    note: '',
  },
  {
    id: 8458,
    tvmazeId: '151',
    title: 'The Newsroom',
    network: 'HBO',
    startYear: 2012,
    years: '2012–2014',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/0/2066.jpg',
    note: '',
  },
  {
    id: 8459,
    tvmazeId: '22239',
    title: 'The Numtums',
    network: 'CBeebies',
    startYear: 2012,
    years: '2012–2014',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/81/203426.jpg',
    note: '',
  },
  {
    id: 8460,
    tvmazeId: '15713',
    title: 'The Outs',
    network: 'Vimeo',
    startYear: 2012,
    years: '2012–2016',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/53/132635.jpg',
    note: '',
  },
  {
    id: 8461,
    tvmazeId: '1162',
    title: 'The Paradise',
    network: 'BBC One',
    startYear: 2012,
    years: '2012–2013',
    genres: ['Drama', 'Romance', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17441.jpg',
    note: '',
  },
  {
    id: 8462,
    tvmazeId: '5825',
    title: 'The Poison Tree',
    network: 'ITV1',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/58016.jpg',
    note: '',
  },
  {
    id: 8463,
    tvmazeId: '9262',
    title: 'The Revolting World of Stanley Brown',
    network: 'CBBC',
    startYear: 2012,
    years: '2012',
    genres: ['Comedy', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/32/81557.jpg',
    note: '',
  },
  {
    id: 8464,
    tvmazeId: '9599',
    title: 'The Rickey Smiley Show',
    network: 'TV One',
    startYear: 2012,
    years: '2012–2014',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/83735.jpg',
    note: '',
  },
  {
    id: 8465,
    tvmazeId: '232',
    title: 'The River',
    network: 'ABC',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Horror', 'Supernatural'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'ABC cancelled after one season; the search for Dr. Emmet Cole in the Amazon and the supernatural forces there were unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/1/3788.jpg',
    note: '',
  },
  {
    id: 8466,
    tvmazeId: '14544',
    title: 'The Ropes',
    network: 'Crackle',
    startYear: 2012,
    years: '2012',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/49/124115.jpg',
    note: '',
  },
  {
    id: 8467,
    tvmazeId: '2347',
    title: 'The Secret of Crickley Hall',
    network: 'BBC One',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Horror', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/12/32071.jpg',
    note: '',
  },
  {
    id: 8468,
    tvmazeId: '3944',
    title: 'The Soul Man',
    network: 'TV Land',
    startYear: 2012,
    years: '2012–2016',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/302/755436.jpg',
    note: '',
  },
  {
    id: 8469,
    tvmazeId: '11807',
    title: 'The Spiral',
    network: 'SVT1',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/39/99404.jpg',
    note: '',
  },
  {
    id: 8470,
    tvmazeId: '7146',
    title: 'The Straits',
    network: 'ABC',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/66908.jpg',
    note: '',
  },
  {
    id: 8471,
    tvmazeId: '9342',
    title: 'The Strange Calls',
    network: 'ABC',
    startYear: 2012,
    years: '2012',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/179/449244.jpg',
    note: '',
  },
  {
    id: 8472,
    tvmazeId: '2196',
    title: 'The Syndicate',
    network: 'BBC One',
    startYear: 2012,
    years: '2012–2021',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/310/776342.jpg',
    note: '',
  },
  {
    id: 8473,
    tvmazeId: '2333',
    title: 'The Town',
    network: 'ITV1',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/12/32026.jpg',
    note: '',
  },
  {
    id: 8474,
    tvmazeId: '35143',
    title: 'The Unknown',
    network: 'Crackle',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Horror', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/147/368377.jpg',
    note: '',
  },
  {
    id: 8475,
    tvmazeId: '32343',
    title: 'The Walking Dead: Cold Storage',
    network: 'AMC.com',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/129/323201.jpg',
    note: '',
  },
  {
    id: 8476,
    tvmazeId: '40996',
    title: 'The Woodlies',
    network: 'Seven Network',
    startYear: 2012,
    years: '2012',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/184/460210.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 353, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
