window.pageShows = [
  {
    id: 1897,
    tvmazeId: '59754',
    title: 'The PM\'s Daughter',
    network: 'ABC iview',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/387/968736.jpg',
    note: '',
  },
  {
    id: 1898,
    tvmazeId: '56932',
    title: 'The Porter',
    network: 'CBC',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/394/986663.jpg',
    note: '',
  },
  {
    id: 1899,
    tvmazeId: '46457',
    title: 'The Proud Family: Louder and Prouder',
    network: 'Disney+',
    startYear: 2022,
    years: '2022–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/629/1573761.jpg',
    note: '',
  },
  {
    id: 1900,
    tvmazeId: '61347',
    title: 'The Read',
    network: 'BBC Four',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/477/1192814.jpg',
    note: '',
  },
  {
    id: 1901,
    tvmazeId: '60522',
    title: 'The Recruit',
    network: 'Netflix',
    startYear: 2022,
    years: '2022–2025',
    genres: ['Action', 'Thriller', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/550/1376612.jpg',
    note: '',
  },
  {
    id: 1902,
    tvmazeId: '55725',
    title: 'The Resort',
    network: 'Peacock',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/417/1042503.jpg',
    note: '',
  },
  {
    id: 1903,
    tvmazeId: '46417',
    title: 'The Responder',
    network: 'BBC iPlayer',
    startYear: 2022,
    years: '2022–2024',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/388/971494.jpg',
    note: '',
  },
  {
    id: 1904,
    tvmazeId: '54981',
    title: 'The Rising',
    network: 'Now',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Crime', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/437/1092937.jpg',
    note: '',
  },
  {
    id: 1905,
    tvmazeId: '62068',
    title: 'The Rookie: Feds',
    network: 'ABC',
    startYear: 2022,
    years: '2022–2023',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/444/1111664.jpg',
    note: '',
  },
  {
    id: 1906,
    tvmazeId: '42827',
    title: 'The Sandman',
    network: 'Netflix',
    startYear: 2022,
    years: '2022–2025',
    genres: ['Drama', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/423/1059631.jpg',
    note: '',
  },
  {
    id: 1907,
    tvmazeId: '60526',
    title: 'The Santa Clauses',
    network: 'Disney+',
    startYear: 2022,
    years: '2022–',
    genres: ['Comedy', 'Family', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/477/1194725.jpg',
    note: '',
  },
  {
    id: 1908,
    tvmazeId: '65931',
    title: 'The Secret Life of Amy Bensen',
    network: 'PassionFlix',
    startYear: 2022,
    years: '2022–',
    genres: ['Romance', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/436/1090583.jpg',
    note: '',
  },
  {
    id: 1909,
    tvmazeId: '53309',
    title: 'The Serpent Queen',
    network: 'STARZ',
    startYear: 2022,
    years: '2022–2024',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/523/1308389.jpg',
    note: '',
  },
  {
    id: 1910,
    tvmazeId: '54439',
    title: 'The Staircase',
    network: 'HBO Max',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/406/1015974.jpg',
    note: '',
  },
  {
    id: 1911,
    tvmazeId: '53443',
    title: 'The Summer I Turned Pretty',
    network: 'Prime Video',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/576/1440848.jpg',
    note: '',
  },
  {
    id: 1912,
    tvmazeId: '58173',
    title: 'The Suspect',
    network: 'ITV1',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/421/1054863.jpg',
    note: '',
  },
  {
    id: 1913,
    tvmazeId: '52490',
    title: 'The Teacher',
    network: '5',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/618/1546864.jpg',
    note: '',
  },
  {
    id: 1914,
    tvmazeId: '47856',
    title: 'The Terminal List',
    network: 'Prime Video',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Action', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/445/1114091.jpg',
    note: '',
  },
  {
    id: 1915,
    tvmazeId: '61071',
    title: 'The Thief, His Wife and the Canoe',
    network: 'ITVX',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/462/1155378.jpg',
    note: '',
  },
  {
    id: 1916,
    tvmazeId: '53310',
    title: 'The Thing About Pam',
    network: 'NBC',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/397/994397.jpg',
    note: '',
  },
  {
    id: 1917,
    tvmazeId: '38051',
    title: 'The Time Traveler\'s Wife',
    network: 'HBO',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Romance', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/407/1017865.jpg',
    note: '',
  },
  {
    id: 1918,
    tvmazeId: '63455',
    title: 'The Tiny Chef Show',
    network: 'Nickelodeon',
    startYear: 2022,
    years: '2022–2025',
    genres: ['Comedy', 'Children', 'Food'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/418/1046956.jpg',
    note: '',
  },
  {
    id: 1919,
    tvmazeId: '46238',
    title: 'The Tourist',
    network: 'BBC iPlayer',
    startYear: 2022,
    years: '2022–2024',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/499/1248932.jpg',
    note: '',
  },
  {
    id: 1920,
    tvmazeId: '62367',
    title: 'The Transporter',
    network: 'Tubi',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Action'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/411/1029147.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 80, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 334, "cliffhanger": 235, "ended": 13701}};
