window.pageShows = [
  {
    id: 4033,
    tvmazeId: '3080',
    title: 'Big Little Lies',
    network: 'HBO',
    startYear: 2017,
    years: '2017–',
    genres: ['Drama', 'Comedy', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/196/490640.jpg',
    note: '',
  },
  {
    id: 4034,
    tvmazeId: '28757',
    title: 'Big Mouth',
    network: 'Netflix',
    startYear: 2017,
    years: '2017–2025',
    genres: ['Comedy', 'Fantasy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/560/1401497.jpg',
    note: '',
  },
  {
    id: 4035,
    tvmazeId: '33412',
    title: 'Biggleton',
    network: 'CBeebies',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/135/338726.jpg',
    note: '',
  },
  {
    id: 4036,
    tvmazeId: '22606',
    title: 'Billy Dilley\'s Super-Duper Subterranean Summer',
    network: 'Disney XD',
    startYear: 2017,
    years: '2017',
    genres: ['Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/136/340391.jpg',
    note: '',
  },
  {
    id: 4037,
    tvmazeId: '83279',
    title: 'Black Girl in a Big Dress',
    network: 'YouTube',
    startYear: 2017,
    years: '2017–2019',
    genres: ['Comedy', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/559/1399692.jpg',
    note: '',
  },
  {
    id: 4038,
    tvmazeId: '14311',
    title: 'Blood Drive',
    network: 'Syfy',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/116/291702.jpg',
    note: '',
  },
  {
    id: 4039,
    tvmazeId: '11911',
    title: 'Born to Kill',
    network: 'Channel 4',
    startYear: 2017,
    years: '2017',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/405/1014806.jpg',
    note: '',
  },
  {
    id: 4040,
    tvmazeId: '25296',
    title: 'Bounty Hunters',
    network: 'Sky Showcase',
    startYear: 2017,
    years: '2017–2019',
    genres: ['Comedy', 'Action', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/483/1209055.jpg',
    note: '',
  },
  {
    id: 4041,
    tvmazeId: '77485',
    title: 'Brewster the Rooster',
    network: 'rtéjr',
    startYear: 2017,
    years: '2017',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/521/1304406.jpg',
    note: '',
  },
  {
    id: 4042,
    tvmazeId: '16175',
    title: 'Brockmire',
    network: 'IFC',
    startYear: 2017,
    years: '2017–2020',
    genres: ['Drama', 'Comedy', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/190/475038.jpg',
    note: '',
  },
  {
    id: 4043,
    tvmazeId: '86368',
    title: 'Broke & Sexy',
    network: 'Apple TV',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/581/1454461.jpg',
    note: '',
  },
  {
    id: 4044,
    tvmazeId: '11822',
    title: 'Broken',
    network: 'BBC One',
    startYear: 2017,
    years: '2017',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/139/347977.jpg',
    note: '',
  },
  {
    id: 4045,
    tvmazeId: '28993',
    title: 'Brown Girls',
    network: 'Vimeo',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/115/289795.jpg',
    note: '',
  },
  {
    id: 4046,
    tvmazeId: '26339',
    title: 'Bucket',
    network: 'BBC Four',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/107/268471.jpg',
    note: '',
  },
  {
    id: 4047,
    tvmazeId: '21545',
    title: 'Budding Prospects',
    network: 'Prime Video',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/109/273902.jpg',
    note: '',
  },
  {
    id: 4048,
    tvmazeId: '17867',
    title: 'Buddy Thunderstruck',
    network: 'Netflix',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy', 'Action', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/100/251670.jpg',
    note: '',
  },
  {
    id: 4049,
    tvmazeId: '24547',
    title: 'Bunsen is a Beast!',
    network: 'Nickelodeon',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Comedy', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/136/340392.jpg',
    note: '',
  },
  {
    id: 4050,
    tvmazeId: '29038',
    title: 'Canada Crew',
    network: 'TVO',
    startYear: 2017,
    years: '2017',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/115/289351.jpg',
    note: '',
  },
  {
    id: 4051,
    tvmazeId: '26275',
    title: 'Canada: The Story of Us',
    network: 'CBC',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/103/258472.jpg',
    note: '',
  },
  {
    id: 4052,
    tvmazeId: '18613',
    title: 'Cardinal',
    network: 'CTV',
    startYear: 2017,
    years: '2017–2020',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/244/611348.jpg',
    note: '',
  },
  {
    id: 4053,
    tvmazeId: '25864',
    title: 'Carters Get Rich',
    network: 'Sky Showcase',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/105/262837.jpg',
    note: '',
  },
  {
    id: 4054,
    tvmazeId: '23326',
    title: 'Cassandra French\'s Finishing School',
    network: 'Audience Network',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/97/243355.jpg',
    note: '',
  },
  {
    id: 4055,
    tvmazeId: '25242',
    title: 'Castlevania',
    network: 'Netflix',
    startYear: 2017,
    years: '2017–2021',
    genres: ['Fantasy', 'Horror', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/316/790637.jpg',
    note: '',
  },
  {
    id: 4056,
    tvmazeId: '12327',
    title: 'Chicago Justice',
    network: 'NBC',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/93/232510.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 169, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 670, "cliffhanger": 0, "ended": 13760}};
