window.pageShows = [
  {
    id: 4441,
    tvmazeId: '20263',
    title: 'The Orville',
    network: 'Hulu',
    startYear: 2017,
    years: '2017–',
    genres: ['Comedy', 'Adventure', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Hulu cancelled after three seasons; multiple long-running storylines including the Kaylon threat were left unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/445/1113833.jpg',
    note: '',
  },
  {
    id: 4442,
    tvmazeId: '31236',
    title: 'The Other Guy',
    network: 'Stan',
    startYear: 2017,
    years: '2017–2019',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/129/323110.jpg',
    note: '',
  },
  {
    id: 4443,
    tvmazeId: '30757',
    title: 'The Other One',
    network: 'BBC iPlayer',
    startYear: 2017,
    years: '2017–2022',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/402/1005412.jpg',
    note: '',
  },
  {
    id: 4444,
    tvmazeId: '30758',
    title: 'The Pact',
    network: 'BBC Two',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 4445,
    tvmazeId: '33784',
    title: 'The Place We Live',
    network: 'Comedy Crib',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 4446,
    tvmazeId: '24608',
    title: 'The Quad',
    network: 'BET',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/362/906218.jpg',
    note: '',
  },
  {
    id: 4447,
    tvmazeId: '47708',
    title: 'The Real Bros of Simi Valley',
    network: 'Facebook Watch',
    startYear: 2017,
    years: '2017–2020',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/254/636265.jpg',
    note: '',
  },
  {
    id: 4448,
    tvmazeId: '11825',
    title: 'The Replacement',
    network: 'BBC One',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/102/255648.jpg',
    note: '',
  },
  {
    id: 4449,
    tvmazeId: '30585',
    title: 'The Rich and the Ruthless',
    network: 'BET+',
    startYear: 2017,
    years: '2017–2021',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/367/919721.jpg',
    note: '',
  },
  {
    id: 4450,
    tvmazeId: '33470',
    title: 'The Scottish Play',
    network: 'Prime Video',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/136/340135.jpg',
    note: '',
  },
  {
    id: 4451,
    tvmazeId: '20895',
    title: 'The Sinner',
    network: 'USA Network',
    startYear: 2017,
    years: '2017–2021',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/365/914978.jpg',
    note: '',
  },
  {
    id: 4452,
    tvmazeId: '11401',
    title: 'The Son',
    network: 'AMC',
    startYear: 2017,
    years: '2017–2019',
    genres: ['Drama', 'Action', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/187/469215.jpg',
    note: '',
  },
  {
    id: 4453,
    tvmazeId: '30837',
    title: 'The State',
    network: 'Channel 4',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/125/313531.jpg',
    note: '',
  },
  {
    id: 4454,
    tvmazeId: '32884',
    title: 'The Untitled Action Bronson Show',
    network: 'Vice TV',
    startYear: 2017,
    years: '2017–2018',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/403/1007720.jpg',
    note: '',
  },
  {
    id: 4455,
    tvmazeId: '33166',
    title: 'The Walking Dead: Red Machete',
    network: 'AMC.com',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Drama', 'Action', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/149/373722.jpg',
    note: '',
  },
  {
    id: 4456,
    tvmazeId: '22698',
    title: 'The Warriors',
    network: 'ABC',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Comedy', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/107/267619.jpg',
    note: '',
  },
  {
    id: 4457,
    tvmazeId: '12886',
    title: 'The White Princess',
    network: 'STARZ',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/98/245176.jpg',
    note: '',
  },
  {
    id: 4458,
    tvmazeId: '12990',
    title: 'The Worst Witch',
    network: 'CBBC',
    startYear: 2017,
    years: '2017–2020',
    genres: ['Adventure', 'Children', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/98/245721.jpg',
    note: '',
  },
  {
    id: 4459,
    tvmazeId: '29066',
    title: 'The Z Virus',
    network: 'ScreenMagic TV',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Action', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/115/289592.jpg',
    note: '',
  },
  {
    id: 4460,
    tvmazeId: '26638',
    title: 'There\'s... Johnny!',
    network: 'Hulu',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/136/340883.jpg',
    note: '',
  },
  {
    id: 4461,
    tvmazeId: '67879',
    title: 'Thick Skin',
    network: 'Apple TV',
    startYear: 2017,
    years: '2017–2020',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/456/1141471.jpg',
    note: '',
  },
  {
    id: 4462,
    tvmazeId: '24941',
    title: 'This Country',
    network: 'BBC Three',
    startYear: 2017,
    years: '2017–2020',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/277/694009.jpg',
    note: '',
  },
  {
    id: 4463,
    tvmazeId: '43809',
    title: 'This Is Desmondo Ray!',
    network: 'Vimeo',
    startYear: 2017,
    years: '2017',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/210/527465.jpg',
    note: '',
  },
  {
    id: 4464,
    tvmazeId: '48343',
    title: 'Threads',
    network: 'go90',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/258/646180.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 186, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 334, "cliffhanger": 235, "ended": 13701}};
