window.pageShows = [
  {
    id: 4273,
    tvmazeId: '58006',
    title: 'True Story avec',
    network: 'Prime Video',
    startYear: 2020,
    years: '2020–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/362/905683.jpg',
    note: '',
  },
  {
    id: 4274,
    tvmazeId: '48048',
    title: 'True: Terrific Tales',
    network: 'Netflix',
    startYear: 2020,
    years: '2020',
    genres: ['Children', 'Fantasy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/256/641731.jpg',
    note: '',
  },
  {
    id: 4275,
    tvmazeId: '51093',
    title: 'Trump Learns Things',
    network: 'WOW Presents Plus',
    startYear: 2020,
    years: '2020',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/277/693452.jpg',
    note: '',
  },
  {
    id: 4276,
    tvmazeId: '43275',
    title: 'Truth Seekers',
    network: 'Prime Video',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Comedy', 'Supernatural'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/356/890239.jpg',
    note: '',
  },
  {
    id: 4277,
    tvmazeId: '45928',
    title: 'Trying',
    network: 'Apple TV',
    startYear: 2020,
    years: '2020–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/628/1570848.jpg',
    note: '',
  },
  {
    id: 4278,
    tvmazeId: '38796',
    title: 'Twenties',
    network: 'BET',
    startYear: 2020,
    years: '2020–',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'BET cancelled after two seasons leaving Hattie\'s career and relationships unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/364/911628.jpg',
    note: '',
  },
  {
    id: 4279,
    tvmazeId: '42773',
    title: 'Two Weeks to Live',
    network: 'Now',
    startYear: 2020,
    years: '2020',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/268/670510.jpg',
    note: '',
  },
  {
    id: 4280,
    tvmazeId: '50023',
    title: 'Tyler Perry\'s Assisted Living',
    network: 'BET',
    startYear: 2020,
    years: '2020–',
    genres: ['Comedy', 'Family'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/566/1416627.jpg',
    note: '',
  },
  {
    id: 4281,
    tvmazeId: '47633',
    title: 'Tyler Perry\'s Bruh',
    network: 'BET+',
    startYear: 2020,
    years: '2020–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/420/1050641.jpg',
    note: '',
  },
  {
    id: 4282,
    tvmazeId: '46668',
    title: 'Tyler Perry\'s Ruthless',
    network: 'BET+',
    startYear: 2020,
    years: '2020–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/617/1544110.jpg',
    note: '',
  },
  {
    id: 4283,
    tvmazeId: '46300',
    title: 'Tyler Perry\'s Young Dylan',
    network: 'Nickelodeon',
    startYear: 2020,
    years: '2020–2025',
    genres: ['Comedy', 'Family'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/480/1200232.jpg',
    note: '',
  },
  {
    id: 4284,
    tvmazeId: '42165',
    title: 'United We Fall',
    network: 'ABC',
    startYear: 2020,
    years: '2020',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/262/655194.jpg',
    note: '',
  },
  {
    id: 4285,
    tvmazeId: '41072',
    title: 'Unorthodox',
    network: 'Netflix',
    startYear: 2020,
    years: '2020',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/248/620726.jpg',
    note: '',
  },
  {
    id: 4286,
    tvmazeId: '48084',
    title: 'Unprecedented',
    network: 'BBC Four',
    startYear: 2020,
    years: '2020',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/259/647792.jpg',
    note: '',
  },
  {
    id: 4287,
    tvmazeId: '49444',
    title: 'Unsaid Stories',
    network: 'ITV1',
    startYear: 2020,
    years: '2020',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/267/668657.jpg',
    note: '',
  },
  {
    id: 4288,
    tvmazeId: '31732',
    title: 'Upload',
    network: 'Prime Video',
    startYear: 2020,
    years: '2020–2025',
    genres: ['Comedy', 'Science-Fiction', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/586/1466414.jpg',
    note: '',
  },
  {
    id: 4289,
    tvmazeId: '43325',
    title: 'Us',
    network: 'BBC iPlayer',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/402/1005027.jpg',
    note: '',
  },
  {
    id: 4290,
    tvmazeId: '29901',
    title: 'Utopia',
    network: 'Prime Video',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Science-Fiction', 'Thriller'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Amazon Prime cancelled the US remake after one season; the Network\'s population reduction plot and Wilson Wilson\'s fate were left unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/268/672170.jpg',
    note: '',
  },
  {
    id: 4291,
    tvmazeId: '42140',
    title: 'Utopia Falls',
    network: 'Hulu',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Music', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/239/599954.jpg',
    note: '',
  },
  {
    id: 4292,
    tvmazeId: '42267',
    title: 'Vagrant Queen',
    network: 'Syfy',
    startYear: 2020,
    years: '2020',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Cliffhanger ending — Season 1 ends with Elida\'s mother still missing and the Republic\'s forces closing in. The fun space-adventure\'s main quest is unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/241/604625.jpg',
    note: '',
  },
  {
    id: 4293,
    tvmazeId: '42930',
    title: 'Valeria',
    network: 'Netflix',
    startYear: 2020,
    years: '2020–2025',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/251/629179.jpg',
    note: '',
  },
  {
    id: 4294,
    tvmazeId: '47017',
    title: 'Validé',
    network: 'Canal+',
    startYear: 2020,
    years: '2020–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/249/623604.jpg',
    note: '',
  },
  {
    id: 4295,
    tvmazeId: '45894',
    title: 'Vampires',
    network: 'Netflix',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/245/613616.jpg',
    note: '',
  },
  {
    id: 4296,
    tvmazeId: '45978',
    title: 'Van Der Valk',
    network: 'NPO Start',
    startYear: 2020,
    years: '2020–',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/400/1001956.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 179, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 295, "ended": 12349}};
