window.pageShows = [
  {
    id: 433,
    tvmazeId: '76555',
    title: 'The Better Sister',
    network: 'Prime Video',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/571/1427766.jpg',
    note: '',
  },
  {
    id: 434,
    tvmazeId: '84703',
    title: 'The Black Dagger Brotherhood checkifcancelled',
    network: 'PassionFlix',
    startYear: 2025,
    years: '2025–',
    genres: ['Action', 'Fantasy', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/580/1451592.jpg',
    note: '',
  },
  {
    id: 435,
    tvmazeId: '70259',
    title: 'The Bombing of Pan Am 103',
    network: 'BBC One',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/568/1421826.jpg',
    note: '',
  },
  {
    id: 436,
    tvmazeId: '69605',
    title: 'The Bondsman',
    network: 'Prime Video',
    startYear: 2025,
    years: '2025',
    genres: ['Action', 'Horror', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/560/1400212.jpg',
    note: '',
  },
  {
    id: 437,
    tvmazeId: '80324',
    title: 'The Borderline',
    network: 'Crave',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/599/1499020.jpg',
    note: '',
  },
  {
    id: 438,
    tvmazeId: '75852',
    title: 'The Chair Company',
    network: 'HBO',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/591/1479768.jpg',
    note: '',
  },
  {
    id: 439,
    tvmazeId: '82760',
    title: 'The Chief checkifcancelled',
    network: 'BBC iPlayer',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/611/1528314.jpg',
    note: '',
  },
  {
    id: 440,
    tvmazeId: '86859',
    title: 'The Chosen Adventures checkifcancelled',
    network: 'Prime Video',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy', 'Adventure', 'Family'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/593/1482504.jpg',
    note: '',
  },
  {
    id: 441,
    tvmazeId: '82738',
    title: 'The Copenhagen Test',
    network: 'Peacock',
    startYear: 2025,
    years: '2025',
    genres: ['Science-Fiction', 'Thriller', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/605/1513760.jpg',
    note: '',
  },
  {
    id: 442,
    tvmazeId: '72631',
    title: 'The Count of Monte Cristo',
    network: 'Rai 1',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/550/1375445.jpg',
    note: '',
  },
  {
    id: 443,
    tvmazeId: '76694',
    title: 'The Crow Girl',
    network: 'Paramount+',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/551/1377716.jpg',
    note: '',
  },
  {
    id: 444,
    tvmazeId: '73056',
    title: 'The Death of Bunny Munro',
    network: 'Now',
    startYear: 2025,
    years: '2025',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/595/1489737.jpg',
    note: '',
  },
  {
    id: 445,
    tvmazeId: '81120',
    title: 'The Family Next Door',
    network: 'ABC iview',
    startYear: 2025,
    years: '2025',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/578/1445939.jpg',
    note: '',
  },
  {
    id: 446,
    tvmazeId: '76813',
    title: 'The Feud',
    network: '5',
    startYear: 2025,
    years: '2025',
    genres: ['Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/563/1408316.jpg',
    note: '',
  },
  {
    id: 447,
    tvmazeId: '83209',
    title: 'The Forsytes',
    network: '5',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Romance', 'History'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/591/1479673.jpg',
    note: '',
  },
  {
    id: 448,
    tvmazeId: '73889',
    title: 'The Four Seasons',
    network: 'Netflix',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/626/1566331.jpg',
    note: '',
  },
  {
    id: 449,
    tvmazeId: '83042',
    title: 'The Game',
    network: '5',
    startYear: 2025,
    years: '2025–',
    genres: ['Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/567/1419867.jpg',
    note: '',
  },
  {
    id: 450,
    tvmazeId: '84192',
    title: 'The Gaslight District',
    network: 'YouTube',
    startYear: 2025,
    years: '2025–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/564/1411492.jpg',
    note: '',
  },
  {
    id: 451,
    tvmazeId: '76565',
    title: 'The Girlfriend checkifcancelled',
    network: 'Prime Video',
    startYear: 2025,
    years: '2025–',
    genres: ['Thriller'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/583/1459064.jpg',
    note: '',
  },
  {
    id: 452,
    tvmazeId: '79725',
    title: 'The Guest',
    network: 'BBC iPlayer',
    startYear: 2025,
    years: '2025',
    genres: ['Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/585/1464735.jpg',
    note: '',
  },
  {
    id: 453,
    tvmazeId: '82327',
    title: 'The Hack',
    network: 'ITVX',
    startYear: 2025,
    years: '2025',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/587/1467852.jpg',
    note: '',
  },
  {
    id: 454,
    tvmazeId: '75025',
    title: 'The Hunting Party',
    network: 'NBC',
    startYear: 2025,
    years: '2025–2026',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/607/1518293.jpg',
    note: '',
  },
  {
    id: 455,
    tvmazeId: '72427',
    title: 'The Hunting Wives',
    network: 'Netflix',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/579/1448883.jpg',
    note: '',
  },
  {
    id: 456,
    tvmazeId: '86075',
    title: 'The Imposter',
    network: '5',
    startYear: 2025,
    years: '2025',
    genres: ['Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/603/1507930.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 19, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 824, "cliffhanger": 237, "ended": 13574}};
