window.pageShows = [
  {
    id: 6769,
    tvmazeId: '1520',
    title: 'Happily Divorced',
    network: 'TV Land',
    startYear: 2011,
    years: '2011–2013',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/8/21281.jpg',
    note: '',
  },
  {
    id: 6770,
    tvmazeId: '574',
    title: 'Happy Endings',
    network: 'ABC',
    startYear: 2011,
    years: '2011–2013',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/481/1202649.jpg',
    note: '',
  },
  {
    id: 6771,
    tvmazeId: '579',
    title: 'Harry\'s Law',
    network: 'NBC',
    startYear: 2011,
    years: '2011–2012',
    genres: ['Drama', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/4/11862.jpg',
    note: '',
  },
  {
    id: 6772,
    tvmazeId: '301',
    title: 'Hart of Dixie',
    network: 'The CW',
    startYear: 2011,
    years: '2011–2015',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: 'CW ran for four seasons and ended with Zoe and Wade\'s wedding, a satisfying conclusion.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/82/205570.jpg',
    note: '',
  },
  {
    id: 6773,
    tvmazeId: '74',
    title: 'Hell on Wheels',
    network: 'AMC',
    startYear: 2011,
    years: '2011–2016',
    genres: ['Drama', 'Action', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/0/526.jpg',
    note: '',
  },
  {
    id: 6774,
    tvmazeId: '2604',
    title: 'Hidden',
    network: 'BBC One',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/13/34637.jpg',
    note: '',
  },
  {
    id: 6775,
    tvmazeId: '55567',
    title: 'Hindenburg: The Last Flight',
    network: 'RTL',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Action', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/321/803309.jpg',
    note: '',
  },
  {
    id: 6776,
    tvmazeId: '7',
    title: 'Homeland',
    network: 'Paramount+ with Showtime',
    startYear: 2011,
    years: '2011–2020',
    genres: ['Drama', 'Thriller', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/498/1245275.jpg',
    note: '',
  },
  {
    id: 6777,
    tvmazeId: '966',
    title: 'House of Anubis',
    network: 'Nickelodeon',
    startYear: 2011,
    years: '2011–2013',
    genres: ['Drama', 'Fantasy', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16422.jpg',
    note: '',
  },
  {
    id: 6778,
    tvmazeId: '7044',
    title: 'Housos',
    network: '7mate',
    startYear: 2011,
    years: '2011–',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/66014.jpg',
    note: '',
  },
  {
    id: 6779,
    tvmazeId: '1684',
    title: 'How to Be a Gentleman',
    network: 'CBS',
    startYear: 2011,
    years: '2011–2012',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/9/23618.jpg',
    note: '',
  },
  {
    id: 6780,
    tvmazeId: '1984',
    title: 'Husbands',
    network: 'CW Seed',
    startYear: 2011,
    years: '2011–2013',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/27973.jpg',
    note: '',
  },
  {
    id: 6781,
    tvmazeId: '31111',
    title: 'Hustling',
    network: 'YouTube',
    startYear: 2011,
    years: '2011–2013',
    genres: ['Drama', 'Adult'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/124/310095.jpg',
    note: '',
  },
  {
    id: 6782,
    tvmazeId: '3835',
    title: 'I Hate My Teenage Daughter',
    network: 'FOX',
    startYear: 2011,
    years: '2011–2012',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/628/1571134.jpg',
    note: '',
  },
  {
    id: 6783,
    tvmazeId: '1992',
    title: 'I Just Want My Pants Back',
    network: 'MTV',
    startYear: 2011,
    years: '2011–2012',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/28036.jpg',
    note: '',
  },
  {
    id: 6784,
    tvmazeId: '91983',
    title: 'I\'m a Monster',
    network: 'RTÉ2',
    startYear: 2011,
    years: '2011',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/625/1563671.jpg',
    note: '',
  },
  {
    id: 6785,
    tvmazeId: '48267',
    title: 'Ice',
    network: 'Channel 4',
    startYear: 2011,
    years: '2011',
    genres: ['Action', 'Science-Fiction', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/258/645306.jpg',
    note: '',
  },
  {
    id: 6786,
    tvmazeId: '12551',
    title: 'In the Flow with Affion Crockett',
    network: 'FOX',
    startYear: 2011,
    years: '2011',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/42/107222.jpg',
    note: '',
  },
  {
    id: 6787,
    tvmazeId: '4024',
    title: 'In with the Flynns',
    network: 'BBC One',
    startYear: 2011,
    years: '2011–2012',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/49564.jpg',
    note: '',
  },
  {
    id: 6788,
    tvmazeId: '21302',
    title: 'Injustice',
    network: 'ITV1',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/75/188726.jpg',
    note: '',
  },
  {
    id: 6789,
    tvmazeId: '4754',
    title: 'InSecurity',
    network: 'CBC',
    startYear: 2011,
    years: '2011',
    genres: ['Comedy', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/53092.jpg',
    note: '',
  },
  {
    id: 6790,
    tvmazeId: '3916',
    title: 'Jake and the Never Land Pirates',
    network: 'Disney Junior',
    startYear: 2011,
    years: '2011–2016',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/48803.jpg',
    note: '',
  },
  {
    id: 6791,
    tvmazeId: '73527',
    title: 'Jelly Jamm',
    network: 'Cartoonito',
    startYear: 2011,
    years: '2011–2013',
    genres: ['Children', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/494/1235715.jpg',
    note: '',
  },
  {
    id: 6792,
    tvmazeId: '514',
    title: 'Jessie',
    network: 'Disney Channel',
    startYear: 2011,
    years: '2011–2015',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/24/61588.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 283, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 856, "cliffhanger": 286, "ended": 13542}};
