window.pageShows = [
  {
    id: 11545,
    tvmazeId: '1651',
    title: 'God, The Devil and Bob',
    network: 'NBC',
    startYear: 2000,
    years: '2000',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/277/693163.jpg',
    note: '',
  },
  {
    id: 11546,
    tvmazeId: '10996',
    title: 'Gormenghast',
    network: 'BBC One',
    startYear: 2000,
    years: '2000',
    genres: ['Drama', 'Comedy', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/36/92410.jpg',
    note: '',
  },
  {
    id: 11547,
    tvmazeId: '7349',
    title: 'Gotham Girls',
    network: 'GothamGirls.com',
    startYear: 2000,
    years: '2000–2002',
    genres: ['Comedy', 'Crime', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/67814.jpg',
    note: '',
  },
  {
    id: 11548,
    tvmazeId: '66146',
    title: 'Grapevine',
    network: 'CBS',
    startYear: 2000,
    years: '2000',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/439/1097720.jpg',
    note: '',
  },
  {
    id: 11549,
    tvmazeId: '41862',
    title: 'Grass Roots',
    network: 'ABC',
    startYear: 2000,
    years: '2000–2003',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/192/480713.jpg',
    note: '',
  },
  {
    id: 11550,
    tvmazeId: '66138',
    title: 'Grizzly Tales for Gruesome Kids',
    network: 'ITV1',
    startYear: 2000,
    years: '2000–2012',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/439/1097520.jpg',
    note: '',
  },
  {
    id: 11551,
    tvmazeId: '14305',
    title: 'Grosse Pointe',
    network: 'The WB',
    startYear: 2000,
    years: '2000–2001',
    genres: ['Drama', 'Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/48/121537.jpg',
    note: '',
  },
  {
    id: 11552,
    tvmazeId: '1810',
    title: 'Harvey Birdman, Attorney at Law',
    network: 'Adult Swim',
    startYear: 2000,
    years: '2000–2007',
    genres: ['Comedy', 'Science-Fiction', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/10/26196.jpg',
    note: '',
  },
  {
    id: 11553,
    tvmazeId: '44755',
    title: 'Hearts and Bones',
    network: 'BBC One',
    startYear: 2000,
    years: '2000–2001',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/217/544632.jpg',
    note: '',
  },
  {
    id: 11554,
    tvmazeId: '39180',
    title: 'Hero to Zero',
    network: 'BBC One',
    startYear: 2000,
    years: '2000',
    genres: ['Drama', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11555,
    tvmazeId: '16135',
    title: 'Higher Ground',
    network: 'Freeform',
    startYear: 2000,
    years: '2000',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/54/135016.jpg',
    note: '',
  },
  {
    id: 11556,
    tvmazeId: '66139',
    title: 'Hollywood Off-Ramp',
    network: 'E!',
    startYear: 2000,
    years: '2000',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11557,
    tvmazeId: '72121',
    title: 'Homestar Runner',
    network: 'YouTube',
    startYear: 2000,
    years: '2000–2023',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/482/1207063.jpg',
    note: '',
  },
  {
    id: 11558,
    tvmazeId: '23512',
    title: 'Human Remains',
    network: 'BBC Two',
    startYear: 2000,
    years: '2000',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/88/220569.jpg',
    note: '',
  },
  {
    id: 11559,
    tvmazeId: '18816',
    title: 'In a Heartbeat',
    network: 'Disney Channel',
    startYear: 2000,
    years: '2000–2001',
    genres: ['Drama', 'Family', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/114/287469.jpg',
    note: '',
  },
  {
    id: 11560,
    tvmazeId: '78424',
    title: 'In Defence',
    network: 'ITV1',
    startYear: 2000,
    years: '2000',
    genres: ['Drama', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/527/1319160.jpg',
    note: '',
  },
  {
    id: 11561,
    tvmazeId: '45099',
    title: 'In the Beginning',
    network: 'NBC',
    startYear: 2000,
    years: '2000',
    genres: ['Drama', 'Adventure', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/224/562050.jpg',
    note: '',
  },
  {
    id: 11562,
    tvmazeId: '66147',
    title: 'Internet Slutts',
    network: 'CTV Comedy Channel',
    startYear: 2000,
    years: '2000',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/439/1097721.jpg',
    note: '',
  },
  {
    id: 11563,
    tvmazeId: '982',
    title: 'Jack of All Trades',
    network: 'Syndication',
    startYear: 2000,
    years: '2000',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16514.jpg',
    note: '',
  },
  {
    id: 11564,
    tvmazeId: '5709',
    title: 'Jackie Chan Adventures',
    network: 'The WB',
    startYear: 2000,
    years: '2000–2005',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/57089.jpg',
    note: '',
  },
  {
    id: 11565,
    tvmazeId: '11004',
    title: 'Jam',
    network: 'Channel 4',
    startYear: 2000,
    years: '2000',
    genres: ['Comedy', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/36/92421.jpg',
    note: '',
  },
  {
    id: 11566,
    tvmazeId: '18414',
    title: 'Jason and the Argonauts',
    network: 'NBC',
    startYear: 2000,
    years: '2000',
    genres: ['Drama', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/62/156870.jpg',
    note: '',
  },
  {
    id: 11567,
    tvmazeId: '72222',
    title: 'JBVO: Your All Request Cartoon Show',
    network: 'Cartoon Network',
    startYear: 2000,
    years: '2000–2001',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/483/1208829.jpg',
    note: '',
  },
  {
    id: 11568,
    tvmazeId: '66148',
    title: 'Just Deal',
    network: 'NBC',
    startYear: 2000,
    years: '2000–2002',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/439/1097723.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 482, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
