window.pageShows = [
  {
    id: 14593,
    tvmazeId: '24155',
    title: 'One by One',
    network: 'BBC One',
    startYear: 1984,
    years: '1984–1987',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/91/228952.jpg',
    note: '',
  },
  {
    id: 14594,
    tvmazeId: '48235',
    title: 'Oxbridge Blues',
    network: 'BBC Two',
    startYear: 1984,
    years: '1984',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14595,
    tvmazeId: '21742',
    title: 'Paper Dolls',
    network: 'ABC',
    startYear: 1984,
    years: '1984',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/78/195662.jpg',
    note: '',
  },
  {
    id: 14596,
    tvmazeId: '37899',
    title: 'Partners in Crime',
    network: 'NBC',
    startYear: 1984,
    years: '1984',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/162/406048.jpg',
    note: '',
  },
  {
    id: 14597,
    tvmazeId: '33893',
    title: 'Pink Panther and Sons',
    network: 'ABC',
    startYear: 1984,
    years: '1984–1985',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/138/345958.jpg',
    note: '',
  },
  {
    id: 14598,
    tvmazeId: '19249',
    title: 'Pole Position',
    network: 'CBS',
    startYear: 1984,
    years: '1984',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/67/168654.jpg',
    note: '',
  },
  {
    id: 14599,
    tvmazeId: '7301',
    title: 'Pryor\'s Place',
    network: 'CBS',
    startYear: 1984,
    years: '1984',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/67744.jpg',
    note: '',
  },
  {
    id: 14600,
    tvmazeId: '1253',
    title: 'Punky Brewster',
    network: 'Syndication',
    startYear: 1984,
    years: '1984–1988',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/292/731593.jpg',
    note: '',
  },
  {
    id: 14601,
    tvmazeId: '19294',
    title: 'Rainbow Brite',
    network: 'Syndication',
    startYear: 1984,
    years: '1984–1985',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/67/169661.jpg',
    note: '',
  },
  {
    id: 14602,
    tvmazeId: '1497',
    title: 'Riptide',
    network: 'NBC',
    startYear: 1984,
    years: '1984–1986',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/8/21217.jpg',
    note: '',
  },
  {
    id: 14603,
    tvmazeId: '1663',
    title: 'Robin of Sherwood',
    network: 'ITV1',
    startYear: 1984,
    years: '1984–1986',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/9/22953.jpg',
    note: '',
  },
  {
    id: 14604,
    tvmazeId: '84390',
    title: 'Round and Round',
    network: 'BBC Two',
    startYear: 1984,
    years: '1984',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14605,
    tvmazeId: '37190',
    title: 'Runaway Island',
    network: 'Seven Network',
    startYear: 1984,
    years: '1984',
    genres: ['Drama', 'Comedy', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/158/397007.jpg',
    note: '',
  },
  {
    id: 14606,
    tvmazeId: '5909',
    title: 'Santa Barbara',
    network: 'NBC',
    startYear: 1984,
    years: '1984–1993',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/466/1166917.jpg',
    note: '',
  },
  {
    id: 14607,
    tvmazeId: '51003',
    title: 'Scully',
    network: 'Channel 4',
    startYear: 1984,
    years: '1984',
    genres: ['Comedy', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/276/692285.jpg',
    note: '',
  },
  {
    id: 14608,
    tvmazeId: '9147',
    title: 'Secret Valley',
    network: 'ABC',
    startYear: 1984,
    years: '1984',
    genres: ['Drama', 'Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/32/80674.jpg',
    note: '',
  },
  {
    id: 14609,
    tvmazeId: '45366',
    title: 'Shaping Up',
    network: 'ABC',
    startYear: 1984,
    years: '1984',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/230/575775.jpg',
    note: '',
  },
  {
    id: 14610,
    tvmazeId: '22613',
    title: 'Sherlock Hound',
    network: 'TV Asahi',
    startYear: 1984,
    years: '1984–1985',
    genres: ['Action', 'Adventure', 'Anime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/83/208833.jpg',
    note: '',
  },
  {
    id: 14611,
    tvmazeId: '23366',
    title: 'Shroud for a Nightingale',
    network: 'ITV1',
    startYear: 1984,
    years: '1984',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/87/219414.jpg',
    note: '',
  },
  {
    id: 14612,
    tvmazeId: '80047',
    title: 'Singles',
    network: 'ITV1',
    startYear: 1984,
    years: '1984–1991',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14613,
    tvmazeId: '12422',
    title: 'Snorks',
    network: 'Syndication',
    startYear: 1984,
    years: '1984–1989',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/42/106167.jpg',
    note: '',
  },
  {
    id: 14614,
    tvmazeId: '51017',
    title: 'Sorrell and Son',
    network: 'ITV1',
    startYear: 1984,
    years: '1984',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/276/692337.jpg',
    note: '',
  },
  {
    id: 14615,
    tvmazeId: '70848',
    title: 'Special Squad',
    network: 'Network 10',
    startYear: 1984,
    years: '1984–1993',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/600/1501569.jpg',
    note: '',
  },
  {
    id: 14616,
    tvmazeId: '23961',
    title: 'Spencer',
    network: 'NBC',
    startYear: 1984,
    years: '1984–1985',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/90/226701.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 609, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 295, "ended": 12349}};
