window.pageShows = [
  {
    id: 8233,
    tvmazeId: '41334',
    title: 'DC Nation Shorts',
    network: 'Cartoon Network',
    startYear: 2012,
    years: '2012–2014',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/255/639386.jpg',
    note: '',
  },
  {
    id: 8234,
    tvmazeId: '7427',
    title: 'Dead Boss',
    network: 'BBC Three',
    startYear: 2012,
    years: '2012',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/68338.jpg',
    note: '',
  },
  {
    id: 8235,
    tvmazeId: '9015',
    title: 'Deadtime Stories',
    network: 'Nickelodeon',
    startYear: 2012,
    years: '2012–2014',
    genres: ['Children', 'Fantasy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/79911.jpg',
    note: '',
  },
  {
    id: 8236,
    tvmazeId: '12174',
    title: 'Deep Space 69',
    network: 'YouTube',
    startYear: 2012,
    years: '2012–2018',
    genres: ['Comedy', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/40/102377.jpg',
    note: '',
  },
  {
    id: 8237,
    tvmazeId: '405',
    title: 'Derek',
    network: 'Channel 4',
    startYear: 2012,
    years: '2012–2014',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/2/6206.jpg',
    note: '',
  },
  {
    id: 8238,
    tvmazeId: '31563',
    title: 'Devil\'s Dust',
    network: 'ABC',
    startYear: 2012,
    years: '2012',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/126/315516.jpg',
    note: '',
  },
  {
    id: 8239,
    tvmazeId: '3570',
    title: 'Dirk Gently',
    network: 'BBC Four',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/597/1494008.jpg',
    note: '',
  },
  {
    id: 8240,
    tvmazeId: '44178',
    title: 'Dirty Work',
    network: 'Rides.tv',
    startYear: 2012,
    years: '2012',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/213/534198.jpg',
    note: '',
  },
  {
    id: 8241,
    tvmazeId: '5347',
    title: 'Doc McStuffins',
    network: 'DisneyNOW',
    startYear: 2012,
    years: '2012–2020',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/55379.jpg',
    note: '',
  },
  {
    id: 8242,
    tvmazeId: '3823',
    title: 'Dog with a Blog',
    network: 'Disney Channel',
    startYear: 2012,
    years: '2012–2015',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/48043.jpg',
    note: '',
  },
  {
    id: 8243,
    tvmazeId: '397',
    title: 'Don\'t Trust the B---- in Apartment 23',
    network: 'ABC',
    startYear: 2012,
    years: '2012–2014',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/2/6145.jpg',
    note: '',
  },
  {
    id: 8244,
    tvmazeId: '7412',
    title: 'Doraleous and Associates',
    network: 'YouTube',
    startYear: 2012,
    years: '2012–2014',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/68240.jpg',
    note: '',
  },
  {
    id: 8245,
    tvmazeId: '1266',
    title: 'DreamWorks Dragons',
    network: 'Cartoon Network',
    startYear: 2012,
    years: '2012–2014',
    genres: ['Adventure', 'Family', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/18291.jpg',
    note: '',
  },
  {
    id: 8246,
    tvmazeId: '52980',
    title: 'Drone',
    network: 'YouTube',
    startYear: 2012,
    years: '2012',
    genres: ['Science-Fiction', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/293/732762.jpg',
    note: '',
  },
  {
    id: 8247,
    tvmazeId: '1519',
    title: 'DTLA',
    network: 'Logo TV',
    startYear: 2012,
    years: '2012',
    genres: [],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/8/21278.jpg',
    note: '',
  },
  {
    id: 8248,
    tvmazeId: '39532',
    title: 'Electric City',
    network: 'Yahoo! View',
    startYear: 2012,
    years: '2012',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/173/434215.jpg',
    note: '',
  },
  {
    id: 8249,
    tvmazeId: '133',
    title: 'Elementary',
    network: 'CBS',
    startYear: 2012,
    years: '2012–2019',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/195/488201.jpg',
    note: '',
  },
  {
    id: 8250,
    tvmazeId: '1317',
    title: 'Emily Owens, M.D.',
    network: 'The CW',
    startYear: 2012,
    years: '2012–2013',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/18557.jpg',
    note: '',
  },
  {
    id: 8251,
    tvmazeId: '1268',
    title: 'Endeavour',
    network: 'ITV1',
    startYear: 2012,
    years: '2012–2023',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/449/1123748.jpg',
    note: '',
  },
  {
    id: 8252,
    tvmazeId: '13121',
    title: 'Eternal Law',
    network: 'ITV1',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Crime', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/45/112808.jpg',
    note: '',
  },
  {
    id: 8253,
    tvmazeId: '21984',
    title: 'Faith',
    network: 'SBS',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Fantasy', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/79/199257.jpg',
    note: '',
  },
  {
    id: 8254,
    tvmazeId: '3657',
    title: 'Falcón',
    network: 'Sky Atlantic',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/47306.jpg',
    note: '',
  },
  {
    id: 8255,
    tvmazeId: '5560',
    title: 'Family Time',
    network: 'Bounce',
    startYear: 2012,
    years: '2012–2020',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/56405.jpg',
    note: '',
  },
  {
    id: 8256,
    tvmazeId: '13164',
    title: 'Fred: The Show',
    network: 'Nickelodeon',
    startYear: 2012,
    years: '2012',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/124/310178.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 344, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
