window.pageShows = [
  {
    id: 3913,
    tvmazeId: '37453',
    title: 'Dracula',
    network: 'BBC One',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/234/587308.jpg',
    note: '',
  },
  {
    id: 3914,
    tvmazeId: '49821',
    title: 'Dream Raider',
    network: 'HBO',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/269/672573.jpg',
    note: '',
  },
  {
    id: 3915,
    tvmazeId: '56155',
    title: 'Drowning in Sunshine',
    network: 'Prime Video',
    startYear: 2020,
    years: '2020',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/334/835869.jpg',
    note: '',
  },
  {
    id: 3916,
    tvmazeId: '30826',
    title: 'Dummy',
    network: 'Quibi',
    startYear: 2020,
    years: '2020',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/248/621496.jpg',
    note: '',
  },
  {
    id: 3917,
    tvmazeId: '39351',
    title: 'Duncanville',
    network: 'FOX',
    startYear: 2020,
    years: '2020–2022',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Fox cancelled after three seasons; Duncan\'s coming-of-age adventures were mid-arc.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/423/1058271.jpg',
    note: '',
  },
  {
    id: 3918,
    tvmazeId: '49260',
    title: 'El Candidato',
    network: 'Prime Video',
    startYear: 2020,
    years: '2020',
    genres: ['Action', 'Thriller', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/265/663349.jpg',
    note: '',
  },
  {
    id: 3919,
    tvmazeId: '41067',
    title: 'El Cid',
    network: 'Prime Video',
    startYear: 2020,
    years: '2020–2021',
    genres: ['Drama', 'Adventure', 'History'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/282/707025.jpg',
    note: '',
  },
  {
    id: 3920,
    tvmazeId: '51653',
    title: 'El desorden que dejas',
    network: 'Netflix',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/282/706310.jpg',
    note: '',
  },
  {
    id: 3921,
    tvmazeId: '46585',
    title: 'El Presidente',
    network: 'Prime Video',
    startYear: 2020,
    years: '2020–2022',
    genres: ['Drama', 'Comedy', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/258/646121.jpg',
    note: '',
  },
  {
    id: 3922,
    tvmazeId: '49603',
    title: 'El robo del siglo',
    network: 'Netflix',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/271/678687.jpg',
    note: '',
  },
  {
    id: 3923,
    tvmazeId: '59384',
    title: 'Elinor Wonders Why',
    network: 'PBS Kids',
    startYear: 2020,
    years: '2020–',
    genres: ['Adventure', 'Children', 'Fantasy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/381/954601.jpg',
    note: '',
  },
  {
    id: 3924,
    tvmazeId: '41632',
    title: 'Emily in Paris',
    network: 'Netflix',
    startYear: 2020,
    years: '2020–',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/604/1510920.jpg',
    note: '',
  },
  {
    id: 3925,
    tvmazeId: '36952',
    title: 'Endlings',
    network: 'Hulu',
    startYear: 2020,
    years: '2020–2021',
    genres: ['Adventure', 'Family', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/616/1541004.jpg',
    note: '',
  },
  {
    id: 3926,
    tvmazeId: '55261',
    title: 'Enola Holmes',
    network: 'Netflix',
    startYear: 2020,
    years: '2020–',
    genres: ['Adventure', 'Family', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/629/1573440.jpg',
    note: '',
  },
  {
    id: 3927,
    tvmazeId: '46572',
    title: 'Entre Hombres',
    network: 'HBO',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/244/612277.jpg',
    note: '',
  },
  {
    id: 3928,
    tvmazeId: '43890',
    title: 'Equinox',
    network: 'Netflix',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Thriller', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/284/712082.jpg',
    note: '',
  },
  {
    id: 3929,
    tvmazeId: '45971',
    title: 'Eternal Love of Dream',
    network: 'Tencent QQ',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Fantasy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/241/604794.jpg',
    note: '',
  },
  {
    id: 3930,
    tvmazeId: '49831',
    title: 'Etheria',
    network: 'Prime Video',
    startYear: 2020,
    years: '2020–',
    genres: ['Horror', 'Science-Fiction'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/614/1537404.jpg',
    note: '',
  },
  {
    id: 3931,
    tvmazeId: '36693',
    title: 'Everything\'s Gonna Be Okay',
    network: 'Freeform',
    startYear: 2020,
    years: '2020–2021',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/594/1485542.jpg',
    note: '',
  },
  {
    id: 3932,
    tvmazeId: '66539',
    title: 'Extraction',
    network: 'Netflix',
    startYear: 2020,
    years: '2020–',
    genres: ['Drama', 'Action', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/442/1106936.jpg',
    note: '',
  },
  {
    id: 3933,
    tvmazeId: '42861',
    title: 'Extracurricular',
    network: 'Netflix',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/466/1166257.jpg',
    note: '',
  },
  {
    id: 3934,
    tvmazeId: '50102',
    title: 'Fair Trade',
    network: 'Prime Video',
    startYear: 2020,
    years: '2020–2022',
    genres: ['Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/273/683572.jpg',
    note: '',
  },
  {
    id: 3935,
    tvmazeId: '51654',
    title: 'Fantasy Ireland',
    network: 'RTÉ2',
    startYear: 2020,
    years: '2020',
    genres: ['Comedy', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/280/701743.jpg',
    note: '',
  },
  {
    id: 3936,
    tvmazeId: '40695',
    title: 'FBI: Most Wanted',
    network: 'CBS',
    startYear: 2020,
    years: '2020–2025',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/538/1345375.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 164, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
