window.pageShows = [
  {
    id: 9481,
    tvmazeId: '1301',
    title: 'Ben 10: Alien Force',
    network: 'Cartoon Network',
    startYear: 2008,
    years: '2008–2010',
    genres: ['Action', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/18463.jpg',
    note: '',
  },
  {
    id: 9482,
    tvmazeId: '70502',
    title: 'Best Ed',
    network: 'Télé Toon',
    startYear: 2008,
    years: '2008',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/472/1180563.jpg',
    note: '',
  },
  {
    id: 9483,
    tvmazeId: '77169',
    title: 'Betsy\'s Kindergarten Adventures',
    network: 'PBS Kids',
    startYear: 2008,
    years: '2008',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/519/1299853.jpg',
    note: '',
  },
  {
    id: 9484,
    tvmazeId: '74721',
    title: 'Big and Small',
    network: 'CBeebies',
    startYear: 2008,
    years: '2008–2011',
    genres: ['Comedy', 'Children', 'Music'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/504/1261425.jpg',
    note: '',
  },
  {
    id: 9485,
    tvmazeId: '34159',
    title: 'Big Barn Farm',
    network: 'CBeebies',
    startYear: 2008,
    years: '2008–2010',
    genres: ['Comedy', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/140/351523.jpg',
    note: '',
  },
  {
    id: 9486,
    tvmazeId: '42594',
    title: 'Body Language',
    network: 'Paramount+ with Showtime',
    startYear: 2008,
    years: '2008–2010',
    genres: ['Drama', 'Romance', 'Adult'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/201/504805.jpg',
    note: '',
  },
  {
    id: 9487,
    tvmazeId: '15484',
    title: 'Bogan Pride',
    network: 'SBS',
    startYear: 2008,
    years: '2008',
    genres: ['Comedy', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/52/131293.jpg',
    note: '',
  },
  {
    id: 9488,
    tvmazeId: '1074',
    title: 'Bonekickers',
    network: 'BBC One',
    startYear: 2008,
    years: '2008',
    genres: ['Drama', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/82/205389.jpg',
    note: '',
  },
  {
    id: 9489,
    tvmazeId: '169',
    title: 'Breaking Bad',
    network: 'AMC',
    startYear: 2008,
    years: '2008–2019',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/501/1253519.jpg',
    note: '',
  },
  {
    id: 9490,
    tvmazeId: '18419',
    title: 'Britannia High',
    network: 'ITV1',
    startYear: 2008,
    years: '2008',
    genres: ['Drama', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/62/156912.jpg',
    note: '',
  },
  {
    id: 9491,
    tvmazeId: '31383',
    title: 'Burn Up',
    network: 'BBC Two',
    startYear: 2008,
    years: '2008',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/125/313273.jpg',
    note: '',
  },
  {
    id: 9492,
    tvmazeId: '9937',
    title: 'Burying Brian',
    network: 'TVNZ 1',
    startYear: 2008,
    years: '2008',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/99/249671.jpg',
    note: '',
  },
  {
    id: 9493,
    tvmazeId: '72206',
    title: 'Calling Cat-22!',
    network: 'Cartoon Network',
    startYear: 2008,
    years: '2008',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/483/1208796.jpg',
    note: '',
  },
  {
    id: 9494,
    tvmazeId: '86588',
    title: 'Camp Rock',
    network: 'Disney Channel',
    startYear: 2008,
    years: '2008–',
    genres: ['Drama', 'Children', 'Music'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/583/1458912.jpg',
    note: '',
  },
  {
    id: 9495,
    tvmazeId: '76300',
    title: 'Can You Teach My Alligator Manners?',
    network: 'Disney Channel',
    startYear: 2008,
    years: '2008',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/515/1288676.jpg',
    note: '',
  },
  {
    id: 9496,
    tvmazeId: '7097',
    title: 'Canal Road',
    network: 'Nine Network',
    startYear: 2008,
    years: '2008',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/66431.jpg',
    note: '',
  },
  {
    id: 9497,
    tvmazeId: '13058',
    title: 'Canterbury\'s Law',
    network: 'FOX',
    startYear: 2008,
    years: '2008',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/44/112109.jpg',
    note: '',
  },
  {
    id: 9498,
    tvmazeId: '9671',
    title: 'Capadocia',
    network: 'HBO',
    startYear: 2008,
    years: '2008–2012',
    genres: ['Drama'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/84011.jpg',
    note: '',
  },
  {
    id: 9499,
    tvmazeId: '1312',
    title: 'Cashmere Mafia',
    network: 'ABC',
    startYear: 2008,
    years: '2008',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/18529.jpg',
    note: '',
  },
  {
    id: 9500,
    tvmazeId: '28860',
    title: 'Casualty 1907',
    network: 'BBC One',
    startYear: 2008,
    years: '2008',
    genres: ['Drama', 'Medical', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/115/287580.jpg',
    note: '',
  },
  {
    id: 9501,
    tvmazeId: '34450',
    title: 'Childrens\' Hospital',
    network: 'TheWB.com',
    startYear: 2008,
    years: '2008',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/407/1018538.jpg',
    note: '',
  },
  {
    id: 9502,
    tvmazeId: '27290',
    title: 'Chop Socky Chooks',
    network: 'Cartoon Network',
    startYear: 2008,
    years: '2008',
    genres: ['Comedy', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/107/269395.jpg',
    note: '',
  },
  {
    id: 9503,
    tvmazeId: '32616',
    title: 'Chuck Versus the Webisodes',
    network: 'NBC.com',
    startYear: 2008,
    years: '2008',
    genres: ['Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 9504,
    tvmazeId: '12097',
    title: 'Chuggington',
    network: 'CBeebies',
    startYear: 2008,
    years: '2008–2015',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/40/101524.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 396, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
