window.pageShows = [
  {
    id: 12121,
    tvmazeId: '12461',
    title: 'The Adventures of Swiss Family Robinson',
    network: 'ION',
    startYear: 1998,
    years: '1998',
    genres: ['Drama', 'Adventure', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/42/106371.jpg',
    note: '',
  },
  {
    id: 12122,
    tvmazeId: '1599',
    title: 'The Ambassador',
    network: 'BBC One',
    startYear: 1998,
    years: '1998–1999',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/8/22049.jpg',
    note: '',
  },
  {
    id: 12123,
    tvmazeId: '17717',
    title: 'The Army Show',
    network: 'The WB',
    startYear: 1998,
    years: '1998',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/281/704887.jpg',
    note: '',
  },
  {
    id: 12124,
    tvmazeId: '42682',
    title: 'The Charlie Horse Music Pizza',
    network: 'PBS',
    startYear: 1998,
    years: '1998–1999',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12125,
    tvmazeId: '11533',
    title: 'The Closer',
    network: 'CBS',
    startYear: 1998,
    years: '1998',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/38/97435.jpg',
    note: '',
  },
  {
    id: 12126,
    tvmazeId: '57975',
    title: 'The Cops',
    network: 'BBC Two',
    startYear: 1998,
    years: '1998–2001',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12127,
    tvmazeId: '35921',
    title: 'The Country Mouse and the City Mouse Adventures',
    network: 'HBO',
    startYear: 1998,
    years: '1998–1999',
    genres: ['Comedy', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/152/380525.jpg',
    note: '',
  },
  {
    id: 12128,
    tvmazeId: '58523',
    title: 'The Creatives',
    network: 'BBC Two',
    startYear: 1998,
    years: '1998–2000',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12129,
    tvmazeId: '1900',
    title: 'The Crow: Stairway to Heaven',
    network: 'Syndication',
    startYear: 1998,
    years: '1998–1999',
    genres: ['Action', 'Fantasy', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/27653.jpg',
    note: '',
  },
  {
    id: 12130,
    tvmazeId: '8365',
    title: 'The Famous Jett Jackson',
    network: 'Disney Channel',
    startYear: 1998,
    years: '1998–2001',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/30/75011.jpg',
    note: '',
  },
  {
    id: 12131,
    tvmazeId: '73347',
    title: 'The Fantastic Voyages of Sinbad the Sailor',
    network: 'Cartoon Network',
    startYear: 1998,
    years: '1998',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/492/1230384.jpg',
    note: '',
  },
  {
    id: 12132,
    tvmazeId: '37979',
    title: 'The Games',
    network: 'ABC',
    startYear: 1998,
    years: '1998–2000',
    genres: ['Comedy', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/162/406788.jpg',
    note: '',
  },
  {
    id: 12133,
    tvmazeId: '8149',
    title: 'The Hughleys',
    network: 'UPN',
    startYear: 1998,
    years: '1998–2002',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/73982.jpg',
    note: '',
  },
  {
    id: 12134,
    tvmazeId: '51139',
    title: 'The Jump',
    network: 'ITV1',
    startYear: 1998,
    years: '1998',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/277/694041.jpg',
    note: '',
  },
  {
    id: 12135,
    tvmazeId: '552',
    title: 'The King of Queens',
    network: 'CBS',
    startYear: 1998,
    years: '1998–2007',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/94/235537.jpg',
    note: '',
  },
  {
    id: 12136,
    tvmazeId: '44914',
    title: 'The Last Don II',
    network: 'CBS',
    startYear: 1998,
    years: '1998',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/220/550230.jpg',
    note: '',
  },
  {
    id: 12137,
    tvmazeId: '65933',
    title: 'The Last Salute',
    network: 'BBC One',
    startYear: 1998,
    years: '1998–1999',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12138,
    tvmazeId: '27149',
    title: 'The Legend of William Tell',
    network: '5',
    startYear: 1998,
    years: '1998',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/107/267901.jpg',
    note: '',
  },
  {
    id: 12139,
    tvmazeId: '60331',
    title: 'The Lionhearts',
    network: 'UPN',
    startYear: 1998,
    years: '1998',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/394/986690.jpg',
    note: '',
  },
  {
    id: 12140,
    tvmazeId: '7128',
    title: 'The Love Boat: The Next Wave',
    network: 'UPN',
    startYear: 1998,
    years: '1998–1999',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/66801.jpg',
    note: '',
  },
  {
    id: 12141,
    tvmazeId: '9979',
    title: 'The Magnificent Seven',
    network: 'CBS',
    startYear: 1998,
    years: '1998–1999',
    genres: ['Drama', 'Action', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/34/85503.jpg',
    note: '',
  },
  {
    id: 12142,
    tvmazeId: '1152',
    title: 'The Net',
    network: 'USA Network',
    startYear: 1998,
    years: '1998–1999',
    genres: ['Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17369.jpg',
    note: '',
  },
  {
    id: 12143,
    tvmazeId: '18035',
    title: 'The New Addams Family',
    network: 'Freeform',
    startYear: 1998,
    years: '1998–1999',
    genres: ['Comedy', 'Family', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/112/281937.jpg',
    note: '',
  },
  {
    id: 12144,
    tvmazeId: '1955',
    title: 'The Powerpuff Girls',
    network: 'Cartoon Network',
    startYear: 1998,
    years: '1998–2005',
    genres: ['Action', 'Children', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/27896.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 506, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 398, "cliffhanger": 239, "ended": 15092}};
