window.pageShows = [
  {
    id: 11905,
    tvmazeId: '66100',
    title: 'The Pleasure Zone',
    network: 'Cinemax',
    startYear: 1999,
    years: '1999',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/438/1095591.jpg',
    note: '',
  },
  {
    id: 11906,
    tvmazeId: '27305',
    title: 'The Scarlet Pimpernel',
    network: 'BBC One',
    startYear: 1999,
    years: '1999–2000',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/107/269565.jpg',
    note: '',
  },
  {
    id: 11907,
    tvmazeId: '527',
    title: 'The Sopranos',
    network: 'HBO',
    startYear: 1999,
    years: '1999–2007',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/4/11341.jpg',
    note: '',
  },
  {
    id: 11908,
    tvmazeId: '45411',
    title: 'The Strip',
    network: 'UPN',
    startYear: 1999,
    years: '1999–2000',
    genres: ['Drama', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/230/577311.jpg',
    note: '',
  },
  {
    id: 11909,
    tvmazeId: '19242',
    title: 'The Tribe',
    network: '5',
    startYear: 1999,
    years: '1999–2003',
    genres: ['Drama', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/67/168579.jpg',
    note: '',
  },
  {
    id: 11910,
    tvmazeId: '19743',
    title: 'The Vice',
    network: 'ITV1',
    startYear: 1999,
    years: '1999–2003',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/281/704493.jpg',
    note: '',
  },
  {
    id: 11911,
    tvmazeId: '523',
    title: 'The West Wing',
    network: 'NBC',
    startYear: 1999,
    years: '1999–2006',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/4/11284.jpg',
    note: '',
  },
  {
    id: 11912,
    tvmazeId: '1333',
    title: 'Third Watch',
    network: 'NBC',
    startYear: 1999,
    years: '1999–2005',
    genres: ['Drama', 'Crime', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/126/316896.jpg',
    note: '',
  },
  {
    id: 11913,
    tvmazeId: '19369',
    title: 'Thunderstone',
    network: 'Network 10',
    startYear: 1999,
    years: '1999–2000',
    genres: ['Drama', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/68/170467.jpg',
    note: '',
  },
  {
    id: 11914,
    tvmazeId: '18334',
    title: 'Time of Your Life',
    network: 'FOX',
    startYear: 1999,
    years: '1999–2000',
    genres: ['Drama'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/214/537280.jpg',
    note: '',
  },
  {
    id: 11915,
    tvmazeId: '23826',
    title: 'Toad Patrol',
    network: 'Cartoon Network',
    startYear: 1999,
    years: '1999–2002',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/89/224928.jpg',
    note: '',
  },
  {
    id: 11916,
    tvmazeId: '45114',
    title: 'Too Rich: The Secret Life of Doris Duke',
    network: 'CBS',
    startYear: 1999,
    years: '1999',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/225/563098.jpg',
    note: '',
  },
  {
    id: 11917,
    tvmazeId: '11208',
    title: 'Total Recall 2070',
    network: 'CBC',
    startYear: 1999,
    years: '1999',
    genres: ['Drama', 'Science-Fiction', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/37/94200.jpg',
    note: '',
  },
  {
    id: 11918,
    tvmazeId: '51250',
    title: 'Trust',
    network: 'ITV1',
    startYear: 1999,
    years: '1999',
    genres: ['Drama', 'Crime', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/278/695591.jpg',
    note: '',
  },
  {
    id: 11919,
    tvmazeId: '8846',
    title: 'Turks',
    network: 'CBS',
    startYear: 1999,
    years: '1999',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/78607.jpg',
    note: '',
  },
  {
    id: 11920,
    tvmazeId: '7318',
    title: 'Tweenies',
    network: 'CBeebies',
    startYear: 1999,
    years: '1999–2002',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/67737.jpg',
    note: '',
  },
  {
    id: 11921,
    tvmazeId: '18780',
    title: 'Twice in a Lifetime',
    network: 'CTV',
    startYear: 1999,
    years: '1999–2001',
    genres: ['Drama', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/64/162309.jpg',
    note: '',
  },
  {
    id: 11922,
    tvmazeId: '15107',
    title: 'Undressed',
    network: 'MTV',
    startYear: 1999,
    years: '1999–2002',
    genres: ['Drama', 'Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/51/128426.jpg',
    note: '',
  },
  {
    id: 11923,
    tvmazeId: '51264',
    title: 'Warriors',
    network: 'BBC One',
    startYear: 1999,
    years: '1999',
    genres: ['Drama', 'Action', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/278/695831.jpg',
    note: '',
  },
  {
    id: 11924,
    tvmazeId: '21414',
    title: 'Wasteland',
    network: 'ABC',
    startYear: 1999,
    years: '1999',
    genres: ['Drama'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/76/190195.jpg',
    note: '',
  },
  {
    id: 11925,
    tvmazeId: '12706',
    title: 'Watership Down',
    network: 'YTV',
    startYear: 1999,
    years: '1999–2001',
    genres: ['Drama', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/43/108695.jpg',
    note: '',
  },
  {
    id: 11926,
    tvmazeId: '66123',
    title: 'Weird-Ohs',
    network: 'YTV',
    startYear: 1999,
    years: '1999–2000',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11927,
    tvmazeId: '80114',
    title: 'Wilmot',
    network: 'ITV1',
    startYear: 1999,
    years: '1999–2000',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11928,
    tvmazeId: '1296',
    title: 'Wives and Daughters',
    network: 'BBC One',
    startYear: 1999,
    years: '1999',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/18456.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 497, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
