window.pageShows = [
  {
    id: 9505,
    tvmazeId: '4064',
    title: 'The Zeta Project',
    network: 'The WB',
    startYear: 2001,
    years: '2001–2002',
    genres: ['Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/300/751947.jpg',
    note: '',
  },
  {
    id: 9506,
    tvmazeId: '20235',
    title: 'Thieves',
    network: 'ABC',
    startYear: 2001,
    years: '2001',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/71/179160.jpg',
    note: '',
  },
  {
    id: 9507,
    tvmazeId: '66291',
    title: 'This Sitcom Is... Not to Be Repeated',
    network: 'CTV Comedy Channel',
    startYear: 2001,
    years: '2001',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 9508,
    tvmazeId: '23930',
    title: 'Three Sisters',
    network: 'NBC',
    startYear: 2001,
    years: '2001–2002',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/361/902797.jpg',
    note: '',
  },
  {
    id: 9509,
    tvmazeId: '79866',
    title: 'Timber Wolf',
    network: 'Warner Bros. Online',
    startYear: 2001,
    years: '2001–2002',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/537/1343560.jpg',
    note: '',
  },
  {
    id: 9510,
    tvmazeId: '24100',
    title: 'Time Squad',
    network: 'Cartoon Network',
    startYear: 2001,
    years: '2001–2003',
    genres: ['Comedy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/91/228276.jpg',
    note: '',
  },
  {
    id: 9511,
    tvmazeId: '6459',
    title: 'Totally Spies!',
    network: 'TF1',
    startYear: 2001,
    years: '2001–',
    genres: ['Action', 'Adventure', 'Espionage'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/24/61754.jpg',
    note: '',
  },
  {
    id: 9512,
    tvmazeId: '2023',
    title: 'Tracker',
    network: 'Syndication',
    startYear: 2001,
    years: '2001–2002',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/28283.jpg',
    note: '',
  },
  {
    id: 9513,
    tvmazeId: '302',
    title: 'Trailer Park Boys',
    network: 'SwearNet',
    startYear: 2001,
    years: '2001–',
    genres: ['Comedy', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/2/5013.jpg',
    note: '',
  },
  {
    id: 9514,
    tvmazeId: '27239',
    title: 'Truth or Scare',
    network: 'Discovery Family',
    startYear: 2001,
    years: '2001–2003',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/107/269095.jpg',
    note: '',
  },
  {
    id: 9515,
    tvmazeId: '34142',
    title: 'TV Go Home',
    network: 'E4',
    startYear: 2001,
    years: '2001',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/140/351030.jpg',
    note: '',
  },
  {
    id: 9516,
    tvmazeId: '4031',
    title: 'Two Pints of Lager and a Packet of Crisps',
    network: 'BBC Three',
    startYear: 2001,
    years: '2001–2011',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/49587.jpg',
    note: '',
  },
  {
    id: 9517,
    tvmazeId: '8269',
    title: 'Two Thousand Acres of Sky',
    network: 'BBC One',
    startYear: 2001,
    years: '2001–2003',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/74641.jpg',
    note: '',
  },
  {
    id: 9518,
    tvmazeId: '66301',
    title: 'U.B.O.S.',
    network: 'YTV',
    startYear: 2001,
    years: '2001–2002',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/440/1102471.jpg',
    note: '',
  },
  {
    id: 9519,
    tvmazeId: '11767',
    title: 'UC: Undercover',
    network: 'NBC',
    startYear: 2001,
    years: '2001–2002',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/401/1004257.jpg',
    note: '',
  },
  {
    id: 9520,
    tvmazeId: '2220',
    title: 'Undeclared',
    network: 'FOX',
    startYear: 2001,
    years: '2001–2003',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/12/30697.jpg',
    note: '',
  },
  {
    id: 9521,
    tvmazeId: '12848',
    title: 'Undergrads',
    network: 'MTV',
    startYear: 2001,
    years: '2001',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/43/109860.jpg',
    note: '',
  },
  {
    id: 9522,
    tvmazeId: '14812',
    title: 'Untalkative Bunny',
    network: 'Cartoon Network',
    startYear: 2001,
    years: '2001–2003',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/525/1312689.jpg',
    note: '',
  },
  {
    id: 9523,
    tvmazeId: '9155',
    title: 'Vampire High',
    network: 'YTV',
    startYear: 2001,
    years: '2001–2002',
    genres: ['Drama', 'Romance', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/624/1560434.jpg',
    note: '',
  },
  {
    id: 9524,
    tvmazeId: '37986',
    title: 'Victoria & Albert',
    network: 'BBC One',
    startYear: 2001,
    years: '2001',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/162/406807.jpg',
    note: '',
  },
  {
    id: 9525,
    tvmazeId: '44836',
    title: 'Voyage of the Unicorn',
    network: 'Odyssey',
    startYear: 2001,
    years: '2001',
    genres: ['Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/218/546012.jpg',
    note: '',
  },
  {
    id: 9526,
    tvmazeId: '39474',
    title: 'What About Joan',
    network: 'ABC',
    startYear: 2001,
    years: '2001',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/173/433776.jpg',
    note: '',
  },
  {
    id: 9527,
    tvmazeId: '2568',
    title: 'What\'s with Andy?',
    network: 'Cartoon Network',
    startYear: 2001,
    years: '2001–2007',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/13/34331.jpg',
    note: '',
  },
  {
    id: 9528,
    tvmazeId: '76274',
    title: 'Wicked!',
    network: 'ABC',
    startYear: 2001,
    years: '2001',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/515/1288332.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 397, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 670, "cliffhanger": 0, "ended": 13760}};
