window.pageShows = [
  {
    id: 10589,
    tvmazeId: '13269',
    title: 'Clubhouse',
    network: 'CBS',
    startYear: 2004,
    years: '2004–2005',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/45/114875.jpg',
    note: '',
  },
  {
    id: 10590,
    tvmazeId: '33009',
    title: 'Come to Papa',
    network: 'NBC',
    startYear: 2004,
    years: '2004',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/133/333742.jpg',
    note: '',
  },
  {
    id: 10591,
    tvmazeId: '1996',
    title: 'Complete Savages',
    network: 'ABC',
    startYear: 2004,
    years: '2004–2005',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/28050.jpg',
    note: '',
  },
  {
    id: 10592,
    tvmazeId: '19742',
    title: 'Conviction',
    network: 'BBC Three',
    startYear: 2004,
    years: '2004',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/69/174423.jpg',
    note: '',
  },
  {
    id: 10593,
    tvmazeId: '4641',
    title: 'Corner Gas',
    network: 'CTV',
    startYear: 2004,
    years: '2004–2014',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/206/515201.jpg',
    note: '',
  },
  {
    id: 10594,
    tvmazeId: '31299',
    title: 'Cracking Up',
    network: 'FOX',
    startYear: 2004,
    years: '2004',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/130/326220.jpg',
    note: '',
  },
  {
    id: 10595,
    tvmazeId: '42650',
    title: 'Creepschool',
    network: 'Cartoon Network',
    startYear: 2004,
    years: '2004',
    genres: ['Fantasy', 'Horror', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/202/505725.jpg',
    note: '',
  },
  {
    id: 10596,
    tvmazeId: '749',
    title: 'CSI: NY',
    network: 'CBS',
    startYear: 2004,
    years: '2004–2013',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/501/1253796.jpg',
    note: '',
  },
  {
    id: 10597,
    tvmazeId: '48589',
    title: 'Da Boom Crew',
    network: 'The WB',
    startYear: 2004,
    years: '2004',
    genres: ['Adventure', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/384/960368.jpg',
    note: '',
  },
  {
    id: 10598,
    tvmazeId: '6301',
    title: 'Danny Phantom',
    network: 'Nickelodeon',
    startYear: 2004,
    years: '2004–2007',
    genres: ['Comedy', 'Fantasy', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/478/1195260.jpg',
    note: '',
  },
  {
    id: 10599,
    tvmazeId: '39668',
    title: 'Darcy\'s Wild Life',
    network: 'Discovery Family',
    startYear: 2004,
    years: '2004–2006',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/174/435432.jpg',
    note: '',
  },
  {
    id: 10600,
    tvmazeId: '18584',
    title: 'Dark Oracle',
    network: 'YTV',
    startYear: 2004,
    years: '2004–2006',
    genres: ['Drama', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/63/158240.jpg',
    note: '',
  },
  {
    id: 10601,
    tvmazeId: '14340',
    title: 'Dave the Barbarian',
    network: 'Disney Channel',
    startYear: 2004,
    years: '2004–2005',
    genres: ['Comedy', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/48/121894.jpg',
    note: '',
  },
  {
    id: 10602,
    tvmazeId: '565',
    title: 'Deadwood',
    network: 'HBO',
    startYear: 2004,
    years: '2004–2019',
    genres: ['Drama', 'Crime', 'Western'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'HBO cancelled after three seasons without the planned fourth season conclusion; a 2019 TV film provided partial but not complete closure.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/4/11724.jpg',
    note: '',
  },
  {
    id: 10603,
    tvmazeId: '28674',
    title: 'Delta State',
    network: 'Canal+',
    startYear: 2004,
    years: '2004–2005',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/114/285637.jpg',
    note: '',
  },
  {
    id: 10604,
    tvmazeId: '550',
    title: 'Desperate Housewives',
    network: 'ABC',
    startYear: 2004,
    years: '2004–2012',
    genres: ['Drama', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/4/11549.jpg',
    note: '',
  },
  {
    id: 10605,
    tvmazeId: '990',
    title: 'Doc Martin',
    network: 'ITV1',
    startYear: 2004,
    years: '2004–2022',
    genres: ['Drama', 'Comedy', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/423/1058629.jpg',
    note: '',
  },
  {
    id: 10606,
    tvmazeId: '49251',
    title: 'Doctors and Nurses',
    network: 'BBC One',
    startYear: 2004,
    years: '2004',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 10607,
    tvmazeId: '79024',
    title: 'Donovan',
    network: 'ITV1',
    startYear: 2004,
    years: '2004–2006',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/618/1547117.jpg',
    note: '',
  },
  {
    id: 10608,
    tvmazeId: '28565',
    title: 'Dr. Vegas',
    network: 'CBS',
    startYear: 2004,
    years: '2004',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/113/284228.jpg',
    note: '',
  },
  {
    id: 10609,
    tvmazeId: '12212',
    title: 'Dragon Booster',
    network: 'CBC',
    startYear: 2004,
    years: '2004–2006',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/41/102613.jpg',
    note: '',
  },
  {
    id: 10610,
    tvmazeId: '988',
    title: 'Drake & Josh',
    network: 'Nickelodeon',
    startYear: 2004,
    years: '2004–2007',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/258/647005.jpg',
    note: '',
  },
  {
    id: 10611,
    tvmazeId: '1518',
    title: 'Drawn Together',
    network: 'Comedy Central',
    startYear: 2004,
    years: '2004–2010',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/8/21274.jpg',
    note: '',
  },
  {
    id: 10612,
    tvmazeId: '19843',
    title: 'Eagle & Evans',
    network: 'ABC',
    startYear: 2004,
    years: '2004–2005',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/70/175211.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 442, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
