window.pageShows = [
  {
    id: 625,
    tvmazeId: '67316',
    title: 'Dexter: Original Sin',
    network: 'Paramount+',
    startYear: 2024,
    years: '2024–2025',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/548/1372007.jpg',
    note: '',
  },
  {
    id: 626,
    tvmazeId: '69170',
    title: 'Diarra from Detroit',
    network: 'Paramount+',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Comedy', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/507/1269977.jpg',
    note: '',
  },
  {
    id: 627,
    tvmazeId: '64116',
    title: 'Dinner with the Parents',
    network: 'Amazon Freevee',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/507/1269091.jpg',
    note: '',
  },
  {
    id: 628,
    tvmazeId: '79920',
    title: 'Dino Dex',
    network: 'Prime Video',
    startYear: 2024,
    years: '2024–',
    genres: ['Adventure', 'Children', 'Fantasy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/537/1344249.jpg',
    note: '',
  },
  {
    id: 629,
    tvmazeId: '59248',
    title: 'Disclaimer',
    network: 'Apple TV',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/538/1347291.jpg',
    note: '',
  },
  {
    id: 630,
    tvmazeId: '75508',
    title: 'Doctor Odyssey',
    network: 'ABC',
    startYear: 2024,
    years: '2024–2025',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/533/1334692.jpg',
    note: '',
  },
  {
    id: 631,
    tvmazeId: '79040',
    title: 'Dodge\'s Pup School checkifcancelled',
    network: 'BBC iPlayer',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy', 'Children'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/537/1344330.jpg',
    note: '',
  },
  {
    id: 632,
    tvmazeId: '54407',
    title: 'Domino Day',
    network: 'BBC iPlayer',
    startYear: 2024,
    years: '2024–',
    genres: ['Thriller', 'Supernatural'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/502/1255964.jpg',
    note: '',
  },
  {
    id: 633,
    tvmazeId: '79130',
    title: 'Don\'t Even',
    network: 'Crave',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/532/1331565.jpg',
    note: '',
  },
  {
    id: 634,
    tvmazeId: '61798',
    title: 'Dora',
    network: 'Paramount+',
    startYear: 2024,
    years: '2024–2025',
    genres: ['Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/513/1284071.jpg',
    note: '',
  },
  {
    id: 635,
    tvmazeId: '72766',
    title: 'Douglas is Cancelled',
    network: 'ITVX',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/525/1313017.jpg',
    note: '',
  },
  {
    id: 636,
    tvmazeId: '76497',
    title: 'Drag Me to the Movies checkifcancelled',
    network: 'WOW Presents Plus',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/519/1298540.jpg',
    note: '',
  },
  {
    id: 637,
    tvmazeId: '77488',
    title: 'Dream Productions',
    network: 'Disney+',
    startYear: 2024,
    years: '2024',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/621/1553834.jpg',
    note: '',
  },
  {
    id: 638,
    tvmazeId: '81471',
    title: 'Drill',
    network: 'VET Tv',
    startYear: 2024,
    years: '2024–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 639,
    tvmazeId: '42846',
    title: 'Dune: Prophecy',
    network: 'HBO',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Science-Fiction'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/543/1358056.jpg',
    note: '',
  },
  {
    id: 640,
    tvmazeId: '86156',
    title: 'Dutch',
    network: 'BET+',
    startYear: 2024,
    years: '2024–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/580/1451101.jpg',
    note: '',
  },
  {
    id: 641,
    tvmazeId: '74492',
    title: 'Dylan\'s Playtime Adventures checkifcancelled',
    network: 'BBC iPlayer',
    startYear: 2024,
    years: '2024–',
    genres: [],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/527/1318422.jpg',
    note: '',
  },
  {
    id: 642,
    tvmazeId: '66318',
    title: 'Earth Abides',
    network: 'MGM+',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/545/1364371.jpg',
    note: '',
  },
  {
    id: 643,
    tvmazeId: '58950',
    title: 'Echo',
    network: 'Disney+',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/499/1247624.jpg',
    note: '',
  },
  {
    id: 644,
    tvmazeId: '72422',
    title: 'Eddie\'s Lil\' Homies checkifcancelled',
    network: 'SBS On Demand',
    startYear: 2024,
    years: '2024–',
    genres: [],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/504/1261022.jpg',
    note: '',
  },
  {
    id: 645,
    tvmazeId: '82703',
    title: 'El Conde: Amor y honor',
    network: 'Telemundo',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/556/1391218.jpg',
    note: '',
  },
  {
    id: 646,
    tvmazeId: '76155',
    title: 'Elkhorn',
    network: 'insp',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Western', 'History'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/514/1285652.jpg',
    note: '',
  },
  {
    id: 647,
    tvmazeId: '74522',
    title: 'Ellis',
    network: '5',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/615/1538104.jpg',
    note: '',
  },
  {
    id: 648,
    tvmazeId: '66869',
    title: 'Elsbeth',
    network: 'CBS',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/591/1479795.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 27, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 785, "cliffhanger": 237, "ended": 13610}};
