window.pageShows = [
  {
    id: 14137,
    tvmazeId: '23372',
    title: 'Justice',
    network: 'ITV1',
    startYear: 1971,
    years: '1971–1974',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/87/219420.jpg',
    note: '',
  },
  {
    id: 14138,
    tvmazeId: '79974',
    title: 'Kindly Leave the Kerb',
    network: 'ITV1',
    startYear: 1971,
    years: '1971',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14139,
    tvmazeId: '7102',
    title: 'Lidsville',
    network: 'ABC',
    startYear: 1971,
    years: '1971',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/66451.jpg',
    note: '',
  },
  {
    id: 14140,
    tvmazeId: '79979',
    title: 'Lollipop Loves Mr Mole',
    network: 'ITV1',
    startYear: 1971,
    years: '1971–1972',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14141,
    tvmazeId: '26087',
    title: 'Longstreet',
    network: 'ABC',
    startYear: 1971,
    years: '1971–1972',
    genres: ['Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/388/971715.jpg',
    note: '',
  },
  {
    id: 14142,
    tvmazeId: '7512',
    title: 'McMillan & Wife',
    network: 'NBC',
    startYear: 1971,
    years: '1971–1977',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/69157.jpg',
    note: '',
  },
  {
    id: 14143,
    tvmazeId: '56819',
    title: 'Monty Nash',
    network: 'Syndication',
    startYear: 1971,
    years: '1971',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14144,
    tvmazeId: '8273',
    title: 'Mr. Benn',
    network: 'BBC One',
    startYear: 1971,
    years: '1971–2005',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/74645.jpg',
    note: '',
  },
  {
    id: 14145,
    tvmazeId: '14554',
    title: 'Nichols',
    network: 'NBC',
    startYear: 1971,
    years: '1971–1972',
    genres: ['Action', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/49/123198.jpg',
    note: '',
  },
  {
    id: 14146,
    tvmazeId: '33348',
    title: 'Now Look Here',
    network: 'BBC One',
    startYear: 1971,
    years: '1971–1973',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/134/337348.jpg',
    note: '',
  },
  {
    id: 14147,
    tvmazeId: '64755',
    title: 'O\'Hara, U.S. Treasury',
    network: 'CBS',
    startYear: 1971,
    years: '1971–1972',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/427/1068771.jpg',
    note: '',
  },
  {
    id: 14148,
    tvmazeId: '16295',
    title: 'Owen Marshall, Counselor at Law',
    network: 'ABC',
    startYear: 1971,
    years: '1971–1974',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/54/135932.jpg',
    note: '',
  },
  {
    id: 14149,
    tvmazeId: '18882',
    title: 'Persuasion',
    network: 'BBC One',
    startYear: 1971,
    years: '1971',
    genres: ['Drama', 'Romance', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/65/163028.jpg',
    note: '',
  },
  {
    id: 14150,
    tvmazeId: '9271',
    title: 'Play Away',
    network: 'BBC Two',
    startYear: 1971,
    years: '1971–1984',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/32/81693.jpg',
    note: '',
  },
  {
    id: 14151,
    tvmazeId: '81319',
    title: 'Police Surgeon',
    network: 'CTV',
    startYear: 1971,
    years: '1971–1975',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/546/1366851.jpg',
    note: '',
  },
  {
    id: 14152,
    tvmazeId: '16536',
    title: 'Polka Dot Door',
    network: 'TVO',
    startYear: 1971,
    years: '1971',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/55/137754.jpg',
    note: '',
  },
  {
    id: 14153,
    tvmazeId: '18970',
    title: 'Primus',
    network: 'Syndication',
    startYear: 1971,
    years: '1971–1972',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/587/1468416.jpg',
    note: '',
  },
  {
    id: 14154,
    tvmazeId: '28628',
    title: 'Sarge',
    network: 'NBC',
    startYear: 1971,
    years: '1971–1972',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/114/285011.jpg',
    note: '',
  },
  {
    id: 14155,
    tvmazeId: '18888',
    title: 'Sense and Sensibility',
    network: 'BBC One',
    startYear: 1971,
    years: '1971',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/65/163047.jpg',
    note: '',
  },
  {
    id: 14156,
    tvmazeId: '28495',
    title: 'Shirley\'s World',
    network: 'ABC',
    startYear: 1971,
    years: '1971–1972',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/136/340472.jpg',
    note: '',
  },
  {
    id: 14157,
    tvmazeId: '80049',
    title: 'Six Dates with Barker',
    network: 'ITV1',
    startYear: 1971,
    years: '1971',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/538/1346489.jpg',
    note: '',
  },
  {
    id: 14158,
    tvmazeId: '56881',
    title: 'Spyforce',
    network: 'Nine Network',
    startYear: 1971,
    years: '1971–1973',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/349/873065.jpg',
    note: '',
  },
  {
    id: 14159,
    tvmazeId: '66969',
    title: 'Stage 2',
    network: 'BBC Two',
    startYear: 1971,
    years: '1971–1973',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14160,
    tvmazeId: '79883',
    title: 'That\'s Your Funeral',
    network: 'BBC One',
    startYear: 1971,
    years: '1971',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  }
];
window.pageMetadata = {"page": 590, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 824, "cliffhanger": 237, "ended": 13574}};
