window.pageShows = [
  {
    id: 13921,
    tvmazeId: '81028',
    title: 'Teen Angel Returns',
    network: 'Disney Channel',
    startYear: 1989,
    years: '1989',
    genres: ['Drama', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 13922,
    tvmazeId: '28557',
    title: 'The Adventures of McGee and Me',
    network: 'ABC',
    startYear: 1989,
    years: '1989–1992',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/113/284186.jpg',
    note: '',
  },
  {
    id: 13923,
    tvmazeId: '65225',
    title: 'The All New Mickey Mouse Club',
    network: 'Disney Channel',
    startYear: 1989,
    years: '1989–1993',
    genres: ['Comedy', 'Children', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/556/1391215.jpg',
    note: '',
  },
  {
    id: 13924,
    tvmazeId: '40523',
    title: 'The California Raisin Show',
    network: 'CBS',
    startYear: 1989,
    years: '1989',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/181/453146.jpg',
    note: '',
  },
  {
    id: 13925,
    tvmazeId: '22200',
    title: 'The Dark Angel',
    network: 'BBC Two',
    startYear: 1989,
    years: '1989',
    genres: ['Drama', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/81/203178.jpg',
    note: '',
  },
  {
    id: 13926,
    tvmazeId: '86064',
    title: 'The Edge',
    network: 'HBO',
    startYear: 1989,
    years: '1989',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 13927,
    tvmazeId: '50960',
    title: 'The Endless Game',
    network: 'ITV1',
    startYear: 1989,
    years: '1989',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/397/994013.jpg',
    note: '',
  },
  {
    id: 13928,
    tvmazeId: '42473',
    title: 'The Famous Teddy Z',
    network: 'CBS',
    startYear: 1989,
    years: '1989–1990',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 13929,
    tvmazeId: '41316',
    title: 'The Ginger Tree',
    network: 'BBC One',
    startYear: 1989,
    years: '1989',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/187/468401.jpg',
    note: '',
  },
  {
    id: 13930,
    tvmazeId: '65235',
    title: 'The Groovy Fellers',
    network: 'Channel 4',
    startYear: 1989,
    years: '1989',
    genres: ['Comedy', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 13931,
    tvmazeId: '9711',
    title: 'The Karate Kid',
    network: 'NBC',
    startYear: 1989,
    years: '1989',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/84294.jpg',
    note: '',
  },
  {
    id: 13932,
    tvmazeId: '78856',
    title: 'The Labours of Erica',
    network: 'ITV1',
    startYear: 1989,
    years: '1989–1990',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/530/1326693.jpg',
    note: '',
  },
  {
    id: 13933,
    tvmazeId: '26813',
    title: 'The Legend of Zelda',
    network: 'NBC',
    startYear: 1989,
    years: '1989',
    genres: ['Adventure', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/105/263896.jpg',
    note: '',
  },
  {
    id: 13934,
    tvmazeId: '51530',
    title: 'The Manageress',
    network: 'Channel 4',
    startYear: 1989,
    years: '1989–1990',
    genres: ['Drama', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/279/699986.jpg',
    note: '',
  },
  {
    id: 13935,
    tvmazeId: '6320',
    title: 'The New Lassie',
    network: 'Syndication',
    startYear: 1989,
    years: '1989–1992',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/24/60634.jpg',
    note: '',
  },
  {
    id: 13936,
    tvmazeId: '64140',
    title: 'The Nightmare Years',
    network: 'TNT',
    startYear: 1989,
    years: '1989',
    genres: ['Drama', 'War', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/422/1055797.jpg',
    note: '',
  },
  {
    id: 13937,
    tvmazeId: '33736',
    title: 'The Nineteenth Hole',
    network: 'ITV1',
    startYear: 1989,
    years: '1989',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 13938,
    tvmazeId: '24046',
    title: 'The Nutt House',
    network: 'NBC',
    startYear: 1989,
    years: '1989',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/502/1256260.jpg',
    note: '',
  },
  {
    id: 13939,
    tvmazeId: '51592',
    title: 'The Paradise Club',
    network: 'BBC One',
    startYear: 1989,
    years: '1989–1990',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/280/700932.jpg',
    note: '',
  },
  {
    id: 13940,
    tvmazeId: '16677',
    title: 'The People Next Door',
    network: 'CBS',
    startYear: 1989,
    years: '1989',
    genres: ['Comedy', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/354/885950.jpg',
    note: '',
  },
  {
    id: 13941,
    tvmazeId: '9561',
    title: 'The Poddington Peas',
    network: 'BBC One',
    startYear: 1989,
    years: '1989',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/83576.jpg',
    note: '',
  },
  {
    id: 13942,
    tvmazeId: '84442',
    title: 'The Real Eddy English',
    network: 'Channel 4',
    startYear: 1989,
    years: '1989',
    genres: ['Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 13943,
    tvmazeId: '31864',
    title: 'The Riddlers',
    network: 'ITV1',
    startYear: 1989,
    years: '1989–1998',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/127/319033.jpg',
    note: '',
  },
  {
    id: 13944,
    tvmazeId: '38001',
    title: 'The Robert Guillaume Show',
    network: 'ABC',
    startYear: 1989,
    years: '1989',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/162/406912.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 581, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
