window.pageShows = [
  {
    id: 9913,
    tvmazeId: '22620',
    title: 'Hot Pink Shorts',
    network: 'OUTtv',
    startYear: 2007,
    years: '2007–2009',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/83/208870.jpg',
    note: '',
  },
  {
    id: 9914,
    tvmazeId: '17964',
    title: 'How It Should Have Ended',
    network: 'YouTube',
    startYear: 2007,
    years: '2007–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/60/151883.jpg',
    note: '',
  },
  {
    id: 9915,
    tvmazeId: '37961',
    title: 'I Hate My 30\'s',
    network: 'VH1',
    startYear: 2007,
    years: '2007',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 9916,
    tvmazeId: '808',
    title: 'iCarly',
    network: 'Nickelodeon',
    startYear: 2007,
    years: '2007–2012',
    genres: ['Comedy', 'Children', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/404/1011740.jpg',
    note: '',
  },
  {
    id: 9917,
    tvmazeId: '43353',
    title: 'Iggy Arbuckle',
    network: 'Cartoon Network',
    startYear: 2007,
    years: '2007',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/208/520011.jpg',
    note: '',
  },
  {
    id: 9918,
    tvmazeId: '5249',
    title: 'Ijon Tichy: Raumpilot',
    network: 'ZDF',
    startYear: 2007,
    years: '2007–2011',
    genres: ['Comedy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/54953.jpg',
    note: '',
  },
  {
    id: 9919,
    tvmazeId: '3836',
    title: 'In Case of Emergency',
    network: 'ABC',
    startYear: 2007,
    years: '2007',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/337/842798.jpg',
    note: '',
  },
  {
    id: 9920,
    tvmazeId: '8961',
    title: 'In the Night Garden...',
    network: 'CBeebies',
    startYear: 2007,
    years: '2007–2009',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/79651.jpg',
    note: '',
  },
  {
    id: 9921,
    tvmazeId: '91094',
    title: 'It\'s Adam and Shelley',
    network: 'BBC Three',
    startYear: 2007,
    years: '2007',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/619/1549268.jpg',
    note: '',
  },
  {
    id: 9922,
    tvmazeId: '28629',
    title: 'Jacob\'s Cross',
    network: 'M-Net',
    startYear: 2007,
    years: '2007–2012',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/114/285015.jpg',
    note: '',
  },
  {
    id: 9923,
    tvmazeId: '37980',
    title: 'Jake and Amir',
    network: 'YouTube',
    startYear: 2007,
    years: '2007–2016',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/162/406800.jpg',
    note: '',
  },
  {
    id: 9924,
    tvmazeId: '1108',
    title: 'Jekyll',
    network: 'BBC One',
    startYear: 2007,
    years: '2007',
    genres: ['Drama', 'Horror', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17233.jpg',
    note: '',
  },
  {
    id: 9925,
    tvmazeId: '1276',
    title: 'John from Cincinnati',
    network: 'HBO',
    startYear: 2007,
    years: '2007',
    genres: ['Drama'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'HBO cancelled after one season; the mysterious John\'s divine mission in the surfing community was never explained.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/184/461278.jpg',
    note: '',
  },
  {
    id: 9926,
    tvmazeId: '66197',
    title: 'Johnny and the Sprites',
    network: 'Disney Junior',
    startYear: 2007,
    years: '2007–2008',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/439/1098684.jpg',
    note: '',
  },
  {
    id: 9927,
    tvmazeId: '1130',
    title: 'Journeyman',
    network: 'NBC',
    startYear: 2007,
    years: '2007',
    genres: ['Drama', 'Science-Fiction', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'NBC cancelled after one season; Dan Vasser\'s involuntary time travel and its effects on his family were unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17277.jpg',
    note: '',
  },
  {
    id: 9928,
    tvmazeId: '33251',
    title: 'Just Jordan',
    network: 'Nickelodeon',
    startYear: 2007,
    years: '2007–2008',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/134/337459.jpg',
    note: '',
  },
  {
    id: 9929,
    tvmazeId: '1113',
    title: 'K-Ville',
    network: 'FOX',
    startYear: 2007,
    years: '2007',
    genres: ['Drama'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Fox cancelled after one season mid-arc in the post-Katrina New Orleans setting.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17245.jpg',
    note: '',
  },
  {
    id: 9930,
    tvmazeId: '80709',
    title: 'Kaboum',
    network: 'Télé-Québec',
    startYear: 2007,
    years: '2007–2009',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 9931,
    tvmazeId: '23687',
    title: 'Katy Brand\'s Big Ass Show',
    network: 'ITV2',
    startYear: 2007,
    years: '2007–2009',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/88/222421.jpg',
    note: '',
  },
  {
    id: 9932,
    tvmazeId: '30810',
    title: 'Kaya',
    network: 'MTV',
    startYear: 2007,
    years: '2007',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/139/347520.jpg',
    note: '',
  },
  {
    id: 9933,
    tvmazeId: '4651',
    title: 'Kick',
    network: 'SBS',
    startYear: 2007,
    years: '2007',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/52634.jpg',
    note: '',
  },
  {
    id: 9934,
    tvmazeId: '38098',
    title: 'Killer Wave',
    network: 'ION',
    startYear: 2007,
    years: '2007',
    genres: ['Action', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/163/408238.jpg',
    note: '',
  },
  {
    id: 9935,
    tvmazeId: '7653',
    title: 'Kingdom',
    network: 'ITV1',
    startYear: 2007,
    years: '2007–2009',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/70437.jpg',
    note: '',
  },
  {
    id: 9936,
    tvmazeId: '22299',
    title: 'Kombat Opera Presents',
    network: 'BBC Two',
    startYear: 2007,
    years: '2007',
    genres: ['Comedy', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/235/587817.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 414, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
