window.pageShows = [
  {
    id: 222,
    title: "The Peripheral",
    network: "Amazon Prime",
    startYear: 2022,
    years: "2022",
    genres: ["Sci-Fi", "Thriller", "Drama"],
    status: "cancelled",
    cancelledAfterSeason: 1,
    cliffhanger: true,
    cliffhangerNote: "Flynne's role in the future timeline and the faction war over the stub's past are left completely unresolved",
    note: "Based on William Gibson's novel, produced by Westworld's creators. Amazon cancelled after one excellent season of dense sci-fi."
  },
  {
    id: 223,
    title: "The Man in the High Castle",
    network: "Amazon Prime",
    startYear: 2015,
    years: "2015–2019",
    genres: ["Sci-Fi", "Alternate History", "Drama"],
    status: "ended",
    cancelledAfterSeason: null,
    totalSeasons: 4,
    cliffhanger: false,
    cliffhangerNote: "Season 4 concluded with the Nazi Reich's downfall and the portal's purpose revealed, though the finale divided fans",
    note: "Based on Philip K. Dick's novel. Four seasons with an actual ending — one of Amazon's first major prestige shows saw the story through."
  },
  {
    id: 224,
    title: "Outer Range",
    network: "Amazon Prime",
    startYear: 2022,
    years: "2022–2024",
    genres: ["Sci-Fi", "Western", "Mystery"],
    status: "cancelled",
    cancelledAfterSeason: 2,
    cliffhanger: true,
    cliffhangerNote: "The void's connection to time and the Abbott family's destiny are left open after Season 2's stunning revelations",
    note: "Josh Brolin discovering a mysterious void on his ranch. Amazon cancelled after Season 2, leaving the time-travel western mythology permanently open."
  },
  {
    id: 225,
    title: "The Rings of Power",
    network: "Amazon Prime",
    startYear: 2022,
    years: "2022–",
    genres: ["Fantasy", "Adventure", "Drama"],
    status: "running",
    cancelledAfterSeason: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: "Tolkien's Second Age on Amazon's $1 billion bet. Still running — included because the 'Is it good?' debate has never been more heated for a fantasy show."
  },

  // ── Batch 6: Hulu, Paramount+, FX, Showtime, Comedy Central ──
  {
    id: 226,
    title: "The Great",
    network: "Hulu",
    startYear: 2020,
    years: "2020–2023",
    genres: ["Historical", "Dark Comedy", "Drama"],
    status: "cancelled",
    cancelledAfterSeason: 3,
    cliffhanger: true,
    cliffhangerNote: "Catherine's rule over Russia and her complicated marriage with Peter are left permanently unresolved with a season-ending assassination attempt",
    note: "Elle Fanning and Nicholas Hoult in Tony McNamara's anarchic Catherine the Great comedy. Hulu cancelled after Season 3 with the story unfinished."
  },
  {
    id: 227,
    title: "High Fidelity",
    network: "Hulu",
    startYear: 2020,
    years: "2020",
    genres: ["Comedy", "Drama", "Romance"],
    status: "cancelled",
    cancelledAfterSeason: 1,
    cliffhanger: true,
    cliffhangerNote: "Rob's choice between her past and her new relationship is left open at the end of the season",
    note: "Zoë Kravitz's gender-swapped Nick Hornby adaptation. Hulu cancelled after one acclaimed season. One of the better streaming cancellations of 2020."
  },
  {
    id: 228,
    title: "Dollface",
    network: "Hulu",
    startYear: 2019,
    years: "2019–2022",
    genres: ["Comedy", "Fantasy", "Drama"],
    status: "cancelled",
    cancelledAfterSeason: 2,
    cliffhanger: true,
    cliffhangerNote: "Jules and her friends' careers and relationships are left open mid-growth at the end of Season 2",
    note: "Kat Dennings in a surreal comedy about female friendship. Hulu cancelled after Season 2 with the women's lives just hitting their stride."
  },
  {
    id: 229,
    title: "Ramy",
    network: "Hulu",
    startYear: 2019,
    years: "2019–2022",
    genres: ["Comedy", "Drama"],
    status: "cancelled",
    cancelledAfterSeason: 3,
    cliffhanger: true,
    cliffhangerNote: "Ramy's spiritual journey and his fractured relationship with Sheikh Ali are abandoned mid-resolution",
    note: "Ramy Youssef's semi-autobiographical Muslim-American comedy-drama. Hulu cancelled after Season 3. One of the most critically beloved and undervalued shows of its era."
  },
  {
    id: 230,
    title: "The Path",
    network: "Hulu",
    startYear: 2016,
    years: "2016–2018",
    genres: ["Drama", "Thriller"],
    status: "cancelled",
    cancelledAfterSeason: 3,
    cliffhanger: true,
    cliffhangerNote: "The Meyerist Movement's dissolution and Eddie's future as its de facto leader are left completely open",
    note: "Aaron Paul and Hugh Dancy in a cult drama. Hulu cancelled after Season 3. One of Hulu's early prestige shows ended without a real conclusion."
  },
  {
    id: 231,
    title: "Casual",
    network: "Hulu",
    startYear: 2015,
    years: "2015–2018",
    genres: ["Comedy", "Drama"],
    status: "ended",
    cancelledAfterSeason: null,
    totalSeasons: 4,
    cliffhanger: false,
    cliffhangerNote: null,
    note: "Michaela Watkins and Tommy Dewey as siblings navigating dating and family. Four complete seasons with a graceful ending — a Hulu original that actually got to finish."
  },
  {
    id: 232,
    title: "Future Man",
    network: "Hulu",
    startYear: 2017,
    years: "2017–2020",
    genres: ["Sci-Fi", "Comedy", "Action"],
    status: "ended",
    cancelledAfterSeason: null,
    totalSeasons: 3,
    cliffhanger: false,
    cliffhangerNote: null,
    note: "Josh Hutcherson recruited by time-travelers because he beat an impossible video game. Three seasons, a complete arc — Seth Rogen's Hulu comedy that stuck the landing."
  },
  {
    id: 233,
    title: "Halo",
    network: "Paramount+",
    startYear: 2022,
    years: "2022–2024",
    genres: ["Sci-Fi", "Action", "Adventure"],
    status: "cancelled",
    cancelledAfterSeason: 2,
    cliffhanger: true,
    cliffhangerNote: "Master Chief's war with the Covenant and the Halo ring's purpose are unresolved; the show invented non-canon story that now just ends",
    note: "Paramount+ cancelled after Season 2 despite massive investment. Controversial for deviating from the games; its cancellation leaves the non-canon story permanently orphaned."
  },
  {
    id: 234,
    title: "The Man Who Fell to Earth",
    network: "Paramount+",
    startYear: 2022,
    years: "2022",
    genres: ["Sci-Fi", "Drama"],
    status: "cancelled",
    cancelledAfterSeason: 1,
    cliffhanger: true,
    cliffhangerNote: "Faraday's mission to save his dying planet and the future of humanity's energy crisis are left completely open",
    note: "Chiwetel Ejiofor and Naomie Harris in a Bowie-inspired sequel series to the 1976 film. Paramount+ cancelled after one cerebral season."
  },
  {
    id: 235,
    title: "Star Trek: Discovery",
    network: "Paramount+",
    startYear: 2017,
    years: "2017–2024",
    genres: ["Sci-Fi", "Adventure", "Drama"],
    status: "ended",
    cancelledAfterSeason: null,
    totalSeasons: 5,
    cliffhanger: false,
    cliffhangerNote: "Season 5 was rushed into a series finale after cancellation was announced mid-production, leaving some threads slightly compressed",
    note: "Paramount+ cancelled Discovery after Season 5 was already filmed. A hasty finale was assembled — not ideal, but it provided some closure."
  },
  {
    id: 236,
    title: "Star Trek: Picard",
    network: "Paramount+",
    startYear: 2020,
    years: "2020–2023",
    genres: ["Sci-Fi", "Adventure", "Drama"],
    status: "ended",
    cancelledAfterSeason: null,
    totalSeasons: 3,
    cliffhanger: false,
    cliffhangerNote: null,
    note: "Patrick Stewart returning as Jean-Luc Picard. Season 3 reunited The Next Generation cast for a beloved farewell. One of streaming's most celebrated final seasons."
  },
  {
    id: 237,
    title: "1883",
    network: "Paramount+",
    startYear: 2021,
    years: "2021–2022",
    genres: ["Western", "Drama"],
    status: "ended",
    cancelledAfterSeason: null,
    totalSeasons: 1,
    cliffhanger: false,
    cliffhangerNote: null,
    note: "Taylor Sheridan's Yellowstone prequel starring Tim McGraw and Faith Hill. A complete, devastating limited series that didn't outstay its welcome."
  },
  {
    id: 238,
    title: "Rutherford Falls",
    network: "Peacock",
    startYear: 2021,
    years: "2021–2022",
    genres: ["Comedy", "Drama"],
    status: "cancelled",
    cancelledAfterSeason: 2,
    cliffhanger: true,
    cliffhangerNote: "Nathan and Reagan's friendship and the Minishonka nation's sovereignty battles are left open at the end of Season 2",
    note: "Ed Helms and Sierra Teller Ornelas in a small-town comedy that centered Indigenous characters. Peacock cancelled after Season 2 to widespread dismay."
  },
  {
    id: 239,
    title: "Girls5eva",
    network: "Peacock / Netflix",
    startYear: 2021,
    years: "2021–2024",
    genres: ["Comedy", "Musical"],
    status: "cancelled",
    cancelledAfterSeason: 3,
    cliffhanger: false,
    cliffhangerNote: "Season 3 moved to Netflix and wrapped the girls' reunion arc, though not every character got a full ending",
    note: "Tina Fey's 90s girl group reunion comedy. Moved from Peacock to Netflix for Season 3 then cancelled — a two-platform ending."
  },
  {
    id: 240,
    title: "Poker Face",
    network: "Peacock",
    startYear: 2023,
    years: "2023–2024",
    genres: ["Mystery", "Comedy", "Drama"],
    status: "ended",
    cancelledAfterSeason: null,
    totalSeasons: 2,
    cliffhanger: false,
    cliffhangerNote: null,
    note: "Natasha Lyonne as a human lie detector solving murders in a Columbo-style procedural. Two complete seasons — Rian Johnson's best work in television form."
  },
  {
    id: 241,
    title: "Resident Alien",
    network: "Syfy / Peacock",
    startYear: 2021,
    years: "2021–2024",
    genres: ["Sci-Fi", "Comedy", "Mystery"],
    status: "cancelled",
    cancelledAfterSeason: 3,
    cliffhanger: true,
    cliffhangerNote: "Harry's mission to destroy humanity and his growing attachment to the humans of Patience, Colorado are left unresolved",
    note: "Alan Tudyk as an alien living as a small-town doctor. Syfy/Peacock cancelled after Season 3 with the alien threat mythology wide open."
  },
  {
    id: 243,
    title: "Reservation Dogs",
    network: "FX on Hulu",
    startYear: 2021,
    years: "2021–2023",
    genres: ["Comedy", "Drama"],
    status: "ended",
    cancelledAfterSeason: null,
    totalSeasons: 3,
    cliffhanger: false,
    cliffhangerNote: null,
    note: "Sterlin Harjo and Taika Waititi's Indigenous teen comedy-drama. Three seasons, a complete and heartfelt ending. One of the best shows of the 2020s, full stop."
  },
  {
    id: 244,
    title: "Kindred",
    network: "FX on Hulu",
    startYear: 2022,
    years: "2022",
    genres: ["Sci-Fi", "Drama", "Horror"],
    status: "cancelled",
    cancelledAfterSeason: 1,
    cliffhanger: true,
    cliffhangerNote: "Dana's involuntary time-travel to antebellum Maryland and the mystery of her ancestor Rufus are left completely unresolved",
    note: "Based on Octavia Butler's masterwork. FX cancelled after one season of the long-awaited adaptation. A literary landmark remains unfinished on screen."
  },
  {
    id: 245,
    title: "Fleishman Is in Trouble",
    network: "FX on Hulu",
    startYear: 2022,
    years: "2022",
    genres: ["Drama", "Comedy"],
    status: "ended",
    cancelledAfterSeason: null,
    totalSeasons: 1,
    cliffhanger: false,
    cliffhangerNote: null,
    note: "Jesse Eisenberg, Claire Danes, and Lizzy Caplan in Taffy Brodesser-Akner's limited series. A complete adaptation — one of the best limited series of 2022."
  },
  {
    id: 246,
    title: "Snowfall",
    network: "FX",
    startYear: 2017,
    years: "2017–2023",
    genres: ["Crime", "Drama"],
    status: "ended",
    cancelledAfterSeason: null,
    totalSeasons: 6,
    cliffhanger: false,
    cliffhangerNote: null,
    note: "John Singleton's crack cocaine epidemic drama set in 1980s Los Angeles. Six seasons, a complete story. Damson Idris anchored one of FX's most consistent dramas."
  }
];
window.pageMetadata = {"page": 10, "totalPages": 19, "perPage": 24, "stats": {"total": 454, "cancelled": 297, "cliffhanger": 250, "ended": 132}};
