window.pageShows = [
  {
    id: 13129,
    tvmazeId: '51072',
    title: 'Diana: Her True Story',
    network: 'Sky Showcase',
    startYear: 1993,
    years: '1993',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/277/693064.jpg',
    note: '',
  },
  {
    id: 13130,
    tvmazeId: '11342',
    title: 'Doctor Finlay',
    network: 'ITV1',
    startYear: 1993,
    years: '1993–1996',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/38/95799.jpg',
    note: '',
  },
  {
    id: 13131,
    tvmazeId: '50384',
    title: 'Double Dragon',
    network: 'Syndication',
    startYear: 1993,
    years: '1993–1994',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/371/927767.jpg',
    note: '',
  },
  {
    id: 13132,
    tvmazeId: '1097',
    title: 'Dr. Quinn, Medicine Woman',
    network: 'CBS',
    startYear: 1993,
    years: '1993–1998',
    genres: ['Drama', 'Family', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17225.jpg',
    note: '',
  },
  {
    id: 13133,
    tvmazeId: '12177',
    title: 'Droopy: Master Detective',
    network: 'FOX',
    startYear: 1993,
    years: '1993',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/40/102380.jpg',
    note: '',
  },
  {
    id: 13134,
    tvmazeId: '58684',
    title: 'Dudley',
    network: 'CBS',
    startYear: 1993,
    years: '1993',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/371/927501.jpg',
    note: '',
  },
  {
    id: 13135,
    tvmazeId: '54986',
    title: 'Eden',
    network: 'USA Network',
    startYear: 1993,
    years: '1993',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/310/777157.jpg',
    note: '',
  },
  {
    id: 13136,
    tvmazeId: '53700',
    title: 'Every Silver Lining',
    network: 'BBC One',
    startYear: 1993,
    years: '1993',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 13137,
    tvmazeId: '19134',
    title: 'Exosquad',
    network: 'Syndication',
    startYear: 1993,
    years: '1993–1994',
    genres: ['Drama', 'Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/66/167066.jpg',
    note: '',
  },
  {
    id: 13138,
    tvmazeId: '34618',
    title: 'Fallen Angels',
    network: 'Paramount+ with Showtime',
    startYear: 1993,
    years: '1993–1995',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/144/360233.jpg',
    note: '',
  },
  {
    id: 13139,
    tvmazeId: '40596',
    title: 'Family Album',
    network: 'CBS',
    startYear: 1993,
    years: '1993',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 13140,
    tvmazeId: '27656',
    title: 'Family Dog',
    network: 'CBS',
    startYear: 1993,
    years: '1993',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/109/272540.jpg',
    note: '',
  },
  {
    id: 13141,
    tvmazeId: '56644',
    title: 'Frank Stubbs Promotes',
    network: 'ITV1',
    startYear: 1993,
    years: '1993–1994',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 13142,
    tvmazeId: '540',
    title: 'Frasier',
    network: 'NBC',
    startYear: 1993,
    years: '1993–2004',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/611/1528088.jpg',
    note: '',
  },
  {
    id: 13143,
    tvmazeId: '17264',
    title: 'Full Stretch',
    network: 'ITV1',
    startYear: 1993,
    years: '1993',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/58/145679.jpg',
    note: '',
  },
  {
    id: 13144,
    tvmazeId: '37309',
    title: 'Gallowglass',
    network: 'BBC One',
    startYear: 1993,
    years: '1993',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/159/398550.jpg',
    note: '',
  },
  {
    id: 13145,
    tvmazeId: '65496',
    title: 'George',
    network: 'ABC',
    startYear: 1993,
    years: '1993–1994',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/576/1440285.jpg',
    note: '',
  },
  {
    id: 13146,
    tvmazeId: '8151',
    title: 'Getting By',
    network: 'NBC',
    startYear: 1993,
    years: '1993–1994',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 13147,
    tvmazeId: '65522',
    title: 'Good Advice',
    network: 'CBS',
    startYear: 1993,
    years: '1993–1994',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/432/1082276.jpg',
    note: '',
  },
  {
    id: 13148,
    tvmazeId: '7537',
    title: 'Goodnight Sweetheart',
    network: 'BBC One',
    startYear: 1993,
    years: '1993–2016',
    genres: ['Comedy', 'Romance', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/69540.jpg',
    note: '',
  },
  {
    id: 13149,
    tvmazeId: '7691',
    title: 'Grace Under Fire',
    network: 'ABC',
    startYear: 1993,
    years: '1993–1998',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/603/1507826.jpg',
    note: '',
  },
  {
    id: 13150,
    tvmazeId: '8211',
    title: 'Halfway Across the Galaxy and Turn Left',
    network: 'ITV1',
    startYear: 1993,
    years: '1993–1994',
    genres: ['Comedy', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/74297.jpg',
    note: '',
  },
  {
    id: 13151,
    tvmazeId: '51690',
    title: 'Harry',
    network: 'BBC One',
    startYear: 1993,
    years: '1993–1995',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/280/702112.jpg',
    note: '',
  },
  {
    id: 13152,
    tvmazeId: '18043',
    title: 'Harts of the West',
    network: 'CBS',
    startYear: 1993,
    years: '1993–1994',
    genres: ['Drama', 'Comedy', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/61/153004.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 548, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
