window.pageShows = [
  {
    id: 6361,
    tvmazeId: '19444',
    title: 'Good Morning Call',
    network: 'FOD',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/68/171178.jpg',
    note: '',
  },
  {
    id: 6362,
    tvmazeId: '18517',
    title: 'Gotham Stories',
    network: 'FOX',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Crime', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/63/158007.jpg',
    note: '',
  },
  {
    id: 6363,
    tvmazeId: '2636',
    title: 'Graves',
    network: 'MGM+',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/171/429916.jpg',
    note: '',
  },
  {
    id: 6364,
    tvmazeId: '6935',
    title: 'Greenleaf',
    network: 'Oprah Winfrey Network',
    startYear: 2016,
    years: '2016–2020',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/263/659185.jpg',
    note: '',
  },
  {
    id: 6365,
    tvmazeId: '17914',
    title: 'Grey Rainbow',
    network: 'PPTV',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/60/151257.jpg',
    note: '',
  },
  {
    id: 6366,
    tvmazeId: '16150',
    title: 'Guardian: The Lonely and Great God',
    network: 'tvN',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Drama', 'Fantasy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/532/1330901.jpg',
    note: '',
  },
  {
    id: 6367,
    tvmazeId: '7673',
    title: 'Guilt',
    network: 'Freeform',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/58/147009.jpg',
    note: '',
  },
  {
    id: 6368,
    tvmazeId: '76768',
    title: 'Gummibär and Friends: The Gummy Bear Show',
    network: 'YouTube',
    startYear: 2016,
    years: '2016–2020',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/518/1295543.jpg',
    note: '',
  },
  {
    id: 6369,
    tvmazeId: '26703',
    title: 'Hailey Dean Mysteries',
    network: 'Hallmark Mystery',
    startYear: 2016,
    years: '2016–2019',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/507/1269442.jpg',
    note: '',
  },
  {
    id: 6370,
    tvmazeId: '19593',
    title: 'Halcyon',
    network: 'halcyonvr.com',
    startYear: 2016,
    years: '2016',
    genres: ['Crime', 'Science-Fiction', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/74/186755.jpg',
    note: '',
  },
  {
    id: 6371,
    tvmazeId: '6764',
    title: 'Hap and Leonard',
    network: 'SundanceTV',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/149/373896.jpg',
    note: '',
  },
  {
    id: 6372,
    tvmazeId: '21884',
    title: 'Happy Marriage!?',
    network: 'Prime Video',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/78/197267.jpg',
    note: '',
  },
  {
    id: 6373,
    tvmazeId: '6753',
    title: 'Harlan Coben\'s The Five',
    network: 'Sky Showcase',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/58/146726.jpg',
    note: '',
  },
  {
    id: 6374,
    tvmazeId: '19714',
    title: 'Harley and the Davidsons',
    network: 'Discovery',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/72/181350.jpg',
    note: '',
  },
  {
    id: 6375,
    tvmazeId: '19244',
    title: 'HarmonQuest',
    network: 'VRV Select',
    startYear: 2016,
    years: '2016–2019',
    genres: ['Comedy', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/128/322008.jpg',
    note: '',
  },
  {
    id: 6376,
    tvmazeId: '11821',
    title: 'Haters Back Off!',
    network: 'Netflix',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/80/200711.jpg',
    note: '',
  },
  {
    id: 6377,
    tvmazeId: '18672',
    title: 'Haunted or Hoax',
    network: 'YouTube',
    startYear: 2016,
    years: '2016',
    genres: ['Horror', 'Romance', 'Supernatural'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/75/187720.jpg',
    note: '',
  },
  {
    id: 6378,
    tvmazeId: '27010',
    title: 'Hawaiian Sovereignty',
    network: 'Syndication',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/106/266746.jpg',
    note: '',
  },
  {
    id: 6379,
    tvmazeId: '3078',
    title: 'Heartbeat',
    network: 'NBC',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Medical'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/47/119892.jpg',
    note: '',
  },
  {
    id: 6380,
    tvmazeId: '17509',
    title: 'Heidi',
    network: '9Go!',
    startYear: 2016,
    years: '2016',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/59/147628.jpg',
    note: '',
  },
  {
    id: 6381,
    tvmazeId: '12007',
    title: 'Her Story',
    network: 'YouTube',
    startYear: 2016,
    years: '2016',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/40/100703.jpg',
    note: '',
  },
  {
    id: 6382,
    tvmazeId: '12615',
    title: 'Here Come the Habibs!',
    network: 'Nine Network',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Comedy', 'Family'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/45/112509.jpg',
    note: '',
  },
  {
    id: 6383,
    tvmazeId: '9798',
    title: 'Here We Go Again',
    network: 'TV One',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/347/869631.jpg',
    note: '',
  },
  {
    id: 6384,
    tvmazeId: '17723',
    title: 'Hibana: Spark',
    network: 'Netflix',
    startYear: 2016,
    years: '2016',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/59/149070.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 266, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
