window.pageShows = [
  {
    id: 14833,
    tvmazeId: '16033',
    title: 'Whiplash',
    network: 'Seven Network',
    startYear: 1961,
    years: '1961',
    genres: ['Drama', 'Adventure', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/53/134369.jpg',
    note: '',
  },
  {
    id: 14834,
    tvmazeId: '16099',
    title: 'Whispering Smith',
    network: 'NBC',
    startYear: 1961,
    years: '1961',
    genres: ['Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/53/134715.jpg',
    note: '',
  },
  {
    id: 14835,
    tvmazeId: '44752',
    title: 'Window on Main Street',
    network: 'CBS',
    startYear: 1961,
    years: '1961–1962',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14836,
    tvmazeId: '47635',
    title: 'Winning Widows',
    network: 'ITV1',
    startYear: 1961,
    years: '1961–1962',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14837,
    tvmazeId: '21530',
    title: 'Yakky Doodle',
    network: 'Boomerang',
    startYear: 1961,
    years: '1961',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/76/191947.jpg',
    note: '',
  },
  {
    id: 14838,
    tvmazeId: '49165',
    title: 'An Age of Kings',
    network: 'BBC Two',
    startYear: 1960,
    years: '1960',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/264/661916.jpg',
    note: '',
  },
  {
    id: 14839,
    tvmazeId: '47342',
    title: 'Angel',
    network: 'CBS',
    startYear: 1960,
    years: '1960–1961',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: '',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/252/632026.jpg',
    note: '',
  },
  {
    id: 14840,
    tvmazeId: '79772',
    title: 'Arthur\'s Treasured Volumes',
    network: 'ITV1',
    startYear: 1960,
    years: '1960',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14841,
    tvmazeId: '23357',
    title: 'Barnaby Rudge',
    network: 'BBC One',
    startYear: 1960,
    years: '1960',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/87/219215.jpg',
    note: '',
  },
  {
    id: 14842,
    tvmazeId: '58226',
    title: 'Bringing Up Buddy',
    network: 'CBS',
    startYear: 1960,
    years: '1960–1961',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/555/1388685.jpg',
    note: '',
  },
  {
    id: 14843,
    tvmazeId: '17743',
    title: 'Checkmate',
    network: 'CBS',
    startYear: 1960,
    years: '1960–1962',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/59/149378.jpg',
    note: '',
  },
  {
    id: 14844,
    tvmazeId: '11261',
    title: 'Citizen James',
    network: 'BBC One',
    startYear: 1960,
    years: '1960–1962',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/38/95036.jpg',
    note: '',
  },
  {
    id: 14845,
    tvmazeId: '56781',
    title: 'Coronado 9',
    network: 'Syndication',
    startYear: 1960,
    years: '1960–1961',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/347/869451.jpg',
    note: '',
  },
  {
    id: 14846,
    tvmazeId: '4139',
    title: 'Coronation Street',
    network: 'ITVX',
    startYear: 1960,
    years: '1960–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/598/1495734.jpg',
    note: '',
  },
  {
    id: 14847,
    tvmazeId: '65400',
    title: 'Dan Raven',
    network: 'NBC',
    startYear: 1960,
    years: '1960–1961',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/480/1201707.jpg',
    note: '',
  },
  {
    id: 14848,
    tvmazeId: '16146',
    title: 'Danger Man',
    network: 'ITV1',
    startYear: 1960,
    years: '1960–1968',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/54/135036.jpg',
    note: '',
  },
  {
    id: 14849,
    tvmazeId: '17456',
    title: 'Dante',
    network: 'NBC',
    startYear: 1960,
    years: '1960–1961',
    genres: ['Drama', 'Adventure', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/58/147267.jpg',
    note: '',
  },
  {
    id: 14850,
    tvmazeId: '21976',
    title: 'Davey and Goliath',
    network: 'Syndication',
    startYear: 1960,
    years: '1960–1973',
    genres: ['Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/79/199015.jpg',
    note: '',
  },
  {
    id: 14851,
    tvmazeId: '56779',
    title: 'Diagnosis: Unknown',
    network: 'CBS',
    startYear: 1960,
    years: '1960',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/347/869450.jpg',
    note: '',
  },
  {
    id: 14852,
    tvmazeId: '77139',
    title: 'Dow Hour of Great Mysteries',
    network: 'NBC',
    startYear: 1960,
    years: '1960',
    genres: ['Horror', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14853,
    tvmazeId: '13075',
    title: 'Four Feather Falls',
    network: 'ITV1',
    startYear: 1960,
    years: '1960',
    genres: ['Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/44/112370.jpg',
    note: '',
  },
  {
    id: 14854,
    tvmazeId: '42837',
    title: 'Guestward Ho!',
    network: 'ABC',
    startYear: 1960,
    years: '1960–1961',
    genres: ['Comedy', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/203/509779.jpg',
    note: '',
  },
  {
    id: 14855,
    tvmazeId: '37702',
    title: 'Happy',
    network: 'NBC',
    startYear: 1960,
    years: '1960–1961',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/160/402272.jpg',
    note: '',
  },
  {
    id: 14856,
    tvmazeId: '70036',
    title: 'Harrigan and Son',
    network: 'ABC',
    startYear: 1960,
    years: '1960–1961',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/482/1205204.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 619, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 824, "cliffhanger": 237, "ended": 13574}};
