window.pageShows = [
  {
    id: 769,
    tvmazeId: '69580',
    title: 'The Stolen Girl',
    network: 'Disney+',
    startYear: 2025,
    years: '2025',
    genres: ['Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/564/1410383.jpg',
    note: '',
  },
  {
    id: 770,
    tvmazeId: '75605',
    title: 'The Studio',
    network: 'Apple TV',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/569/1424520.jpg',
    note: '',
  },
  {
    id: 771,
    tvmazeId: '86717',
    title: 'The Sunshine Murders',
    network: '5',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/584/1460892.jpg',
    note: '',
  },
  {
    id: 772,
    tvmazeId: '84598',
    title: 'The Survivors',
    network: 'Netflix',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/568/1420828.jpg',
    note: '',
  },
  {
    id: 773,
    tvmazeId: '74127',
    title: 'The Terminal List: Dark Wolf',
    network: 'Prime Video',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Thriller', 'Espionage'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/590/1475632.jpg',
    note: '',
  },
  {
    id: 774,
    tvmazeId: '90227',
    title: 'The Thirsty Thirty',
    network: 'Disney+',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/612/1531415.jpg',
    note: '',
  },
  {
    id: 775,
    tvmazeId: '81568',
    title: 'The Thundermans: Undercover',
    network: 'Nickelodeon',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy', 'Family', 'Science-Fiction'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/604/1510956.jpg',
    note: '',
  },
  {
    id: 776,
    tvmazeId: '73789',
    title: 'The Trauma Code: Heroes on Call',
    network: 'Netflix',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/552/1382428.jpg',
    note: '',
  },
  {
    id: 777,
    tvmazeId: '86017',
    title: 'The Trouble with Tessa',
    network: 'Screambox',
    startYear: 2025,
    years: '2025',
    genres: ['Horror'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/578/1447218.jpg',
    note: '',
  },
  {
    id: 778,
    tvmazeId: '82250',
    title: 'The Twisted Tale of Amanda Knox',
    network: 'Hulu',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/592/1480194.jpg',
    note: '',
  },
  {
    id: 779,
    tvmazeId: '86695',
    title: 'The Unstoppable Jenny Garcia',
    network: 'CBC Gem',
    startYear: 2025,
    years: '2025–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/586/1465690.jpg',
    note: '',
  },
  {
    id: 780,
    tvmazeId: '81245',
    title: 'The Walsh Sisters',
    network: 'RTÉ ONE',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/589/1473563.jpg',
    note: '',
  },
  {
    id: 781,
    tvmazeId: '78640',
    title: 'The War Between the Land and the Sea',
    network: 'BBC iPlayer',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/602/1506196.jpg',
    note: '',
  },
  {
    id: 782,
    tvmazeId: '85135',
    title: 'The Warehouse Phase',
    network: 'Peacock',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Comedy', 'Music'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/571/1428903.jpg',
    note: '',
  },
  {
    id: 783,
    tvmazeId: '77065',
    title: 'The Waterfront',
    network: 'Netflix',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/570/1425195.jpg',
    note: '',
  },
  {
    id: 784,
    tvmazeId: '84485',
    title: 'The Wayfinders',
    network: 'Angel Studios',
    startYear: 2025,
    years: '2025–',
    genres: ['Adventure', 'Fantasy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/567/1418277.jpg',
    note: '',
  },
  {
    id: 785,
    tvmazeId: '86249',
    title: 'The Wonderfully Weird World of Gumball',
    network: 'Hulu',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/604/1510610.jpg',
    note: '',
  },
  {
    id: 786,
    tvmazeId: '82188',
    title: 'The Z-Suite',
    network: 'Tubi',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/553/1382894.jpg',
    note: '',
  },
  {
    id: 787,
    tvmazeId: '74826',
    title: 'This City Is Ours',
    network: 'BBC iPlayer',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/568/1420509.jpg',
    note: '',
  },
  {
    id: 788,
    tvmazeId: '83701',
    title: 'This Is Not a Murder Mystery',
    network: 'VRT MAX',
    startYear: 2025,
    years: '2025',
    genres: ['Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/595/1487899.jpg',
    note: '',
  },
  {
    id: 789,
    tvmazeId: '83850',
    title: 'Tim Rex in Space',
    network: '5',
    startYear: 2025,
    years: '2025–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/562/1406631.jpg',
    note: '',
  },
  {
    id: 790,
    tvmazeId: '82342',
    title: 'Tiệm ăn của quỷ',
    network: 'Netflix',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Horror', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/553/1384809.jpg',
    note: '',
  },
  {
    id: 791,
    tvmazeId: '86018',
    title: 'To Kill A Monkey',
    network: 'Netflix',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/578/1447229.jpg',
    note: '',
  },
  {
    id: 792,
    tvmazeId: '49424',
    title: 'Tom Clancy\'s Splinter Cell: Deathwatch',
    network: 'Netflix',
    startYear: 2025,
    years: '2025–',
    genres: ['Action', 'Thriller', 'Espionage'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/592/1481328.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 33, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
