window.pageShows = [
  {
    id: 3409,
    tvmazeId: '42868',
    title: 'The Unsettling',
    network: 'Hulu',
    startYear: 2019,
    years: '2019',
    genres: ['Crime', 'Fantasy', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/255/638856.jpg',
    note: '',
  },
  {
    id: 3410,
    tvmazeId: '34995',
    title: 'The Victim',
    network: 'BBC One',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Thriller', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/402/1005026.jpg',
    note: '',
  },
  {
    id: 3411,
    tvmazeId: '34317',
    title: 'The Village',
    network: 'NBC',
    startYear: 2019,
    years: '2019',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/178/446928.jpg',
    note: '',
  },
  {
    id: 3412,
    tvmazeId: '30415',
    title: 'The Virtues',
    network: 'Channel 4',
    startYear: 2019,
    years: '2019',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/195/487708.jpg',
    note: '',
  },
  {
    id: 3413,
    tvmazeId: '35920',
    title: 'The War of the Worlds',
    network: 'BBC One',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/213/532849.jpg',
    note: '',
  },
  {
    id: 3414,
    tvmazeId: '41294',
    title: 'The Weird Place',
    network: 'Rooster Teeth',
    startYear: 2019,
    years: '2019',
    genres: ['Comedy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/187/468537.jpg',
    note: '',
  },
  {
    id: 3415,
    tvmazeId: '26806',
    title: 'The Widow',
    network: 'Prime Video',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Action', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/498/1245278.jpg',
    note: '',
  },
  {
    id: 3416,
    tvmazeId: '28276',
    title: 'The Witcher',
    network: 'Netflix',
    startYear: 2019,
    years: '2019–',
    genres: ['Drama', 'Action', 'Fantasy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/594/1486674.jpg',
    note: '',
  },
  {
    id: 3417,
    tvmazeId: '82928',
    title: 'Theme Song Takeover',
    network: 'Disney Channel',
    startYear: 2019,
    years: '2019–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/557/1394932.jpg',
    note: '',
  },
  {
    id: 3418,
    tvmazeId: '42067',
    title: 'This Way Up',
    network: 'Channel 4',
    startYear: 2019,
    years: '2019–2021',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/207/519141.jpg',
    note: '',
  },
  {
    id: 3419,
    tvmazeId: '36752',
    title: 'Tigtone',
    network: 'Adult Swim',
    startYear: 2019,
    years: '2019–2020',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/179/448396.jpg',
    note: '',
  },
  {
    id: 3420,
    tvmazeId: '25720',
    title: 'Too Old to Die Young',
    network: 'Prime Video',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/480/1200134.jpg',
    note: '',
  },
  {
    id: 3421,
    tvmazeId: '43819',
    title: 'Top Boy',
    network: 'Netflix',
    startYear: 2019,
    years: '2019–2023',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/211/528058.jpg',
    note: '',
  },
  {
    id: 3422,
    tvmazeId: '56572',
    title: 'Tot Cop',
    network: 'Nickelodeon',
    startYear: 2019,
    years: '2019',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/344/861157.jpg',
    note: '',
  },
  {
    id: 3423,
    tvmazeId: '39869',
    title: 'Total Control',
    network: 'ABC',
    startYear: 2019,
    years: '2019–2024',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/211/528759.jpg',
    note: '',
  },
  {
    id: 3424,
    tvmazeId: '41272',
    title: 'Total Forgiveness',
    network: 'Dropout',
    startYear: 2019,
    years: '2019',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/607/1519915.jpg',
    note: '',
  },
  {
    id: 3425,
    tvmazeId: '70221',
    title: 'Toto\'s Kindergarten',
    network: 'BabyTV',
    startYear: 2019,
    years: '2019',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/470/1177182.jpg',
    note: '',
  },
  {
    id: 3426,
    tvmazeId: '41001',
    title: 'Traces',
    network: 'U&alibi',
    startYear: 2019,
    years: '2019–2022',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/232/582449.jpg',
    note: '',
  },
  {
    id: 3427,
    tvmazeId: '42601',
    title: 'Trackers',
    network: 'M-Net',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/225/563745.jpg',
    note: '',
  },
  {
    id: 3428,
    tvmazeId: '41410',
    title: 'Trailer Park Boys: The Animated Series',
    network: 'Netflix',
    startYear: 2019,
    years: '2019–2020',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/188/472147.jpg',
    note: '',
  },
  {
    id: 3429,
    tvmazeId: '35172',
    title: 'Traitors',
    network: 'Channel 4',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Thriller', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/184/460235.jpg',
    note: '',
  },
  {
    id: 3430,
    tvmazeId: '35987',
    title: 'Treadstone',
    network: 'USA Network',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Action', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/217/544715.jpg',
    note: '',
  },
  {
    id: 3431,
    tvmazeId: '39141',
    title: 'Trinkets',
    network: 'Netflix',
    startYear: 2019,
    years: '2019–2020',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/201/504182.jpg',
    note: '',
  },
  {
    id: 3432,
    tvmazeId: '54005',
    title: 'Troopers',
    network: 'Dropout',
    startYear: 2019,
    years: '2019',
    genres: ['Comedy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/299/748341.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 143, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 670, "cliffhanger": 0, "ended": 13760}};
