window.pageShows = [
  {
    id: 937,
    tvmazeId: '72981',
    title: 'Boarders',
    network: 'BBC iPlayer',
    startYear: 2024,
    years: '2024–2026',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/553/1383820.jpg',
    note: '',
  },
  {
    id: 938,
    tvmazeId: '62602',
    title: 'Bodkin',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Comedy', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/518/1296268.jpg',
    note: '',
  },
  {
    id: 939,
    tvmazeId: '74707',
    title: 'Boku no Itoshii Youkai Girlfriend',
    network: 'Prime Video',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/509/1274618.jpg',
    note: '',
  },
  {
    id: 940,
    tvmazeId: '79445',
    title: 'Borderline',
    network: 'The Roku Channel',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/534/1336471.jpg',
    note: '',
  },
  {
    id: 941,
    tvmazeId: '79357',
    title: 'Born for the Spotlight',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/542/1356638.jpg',
    note: '',
  },
  {
    id: 942,
    tvmazeId: '80622',
    title: 'Boy Culture: Generation X',
    network: 'OUTtv',
    startYear: 2024,
    years: '2024–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/542/1355873.jpg',
    note: '',
  },
  {
    id: 943,
    tvmazeId: '63872',
    title: 'Boy Swallows Universe',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Crime', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/499/1248587.jpg',
    note: '',
  },
  {
    id: 944,
    tvmazeId: '83836',
    title: 'Brat Pack',
    network: 'YouTube',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy', 'Children', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/562/1406213.jpg',
    note: '',
  },
  {
    id: 945,
    tvmazeId: '70136',
    title: 'Breathtaking',
    network: 'ITVX',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/504/1262312.jpg',
    note: '',
  },
  {
    id: 946,
    tvmazeId: '71421',
    title: 'Briganti',
    network: 'Netflix',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Action', 'History'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/514/1286762.jpg',
    note: '',
  },
  {
    id: 947,
    tvmazeId: '66625',
    title: 'Brilliant Minds',
    network: 'NBC',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Medical'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/590/1475103.jpg',
    note: '',
  },
  {
    id: 948,
    tvmazeId: '72202',
    title: 'Bros',
    network: 'Netflix',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/514/1286778.jpg',
    note: '',
  },
  {
    id: 949,
    tvmazeId: '78249',
    title: 'Broute 24.',
    network: 'Canal+',
    startYear: 2024,
    years: '2024–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/526/1316481.jpg',
    note: '',
  },
  {
    id: 950,
    tvmazeId: '73481',
    title: 'Cada Minuto Cuenta',
    network: 'Prime Video',
    startYear: 2024,
    years: '2024–2025',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/539/1348076.jpg',
    note: '',
  },
  {
    id: 951,
    tvmazeId: '74879',
    title: 'Caillou',
    network: 'Peacock',
    startYear: 2024,
    years: '2024–',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/505/1263741.jpg',
    note: '',
  },
  {
    id: 952,
    tvmazeId: '75469',
    title: 'Call Me Bae',
    network: 'Prime Video',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/521/1304230.jpg',
    note: '',
  },
  {
    id: 953,
    tvmazeId: '80130',
    title: 'Camp Be Better',
    network: 'TVNZ+',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/617/1544800.jpg',
    note: '',
  },
  {
    id: 954,
    tvmazeId: '68804',
    title: 'Camp Snoopy',
    network: 'Apple TV',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/521/1303548.jpg',
    note: '',
  },
  {
    id: 955,
    tvmazeId: '81050',
    title: 'Carl the Collector',
    network: 'PBS Kids',
    startYear: 2024,
    years: '2024–',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/545/1363388.jpg',
    note: '',
  },
  {
    id: 956,
    tvmazeId: '74588',
    title: 'Catch Me a Killer',
    network: 'Showmax',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/503/1258586.jpg',
    note: '',
  },
  {
    id: 957,
    tvmazeId: '76538',
    title: 'Century of Love',
    network: 'One31',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Action', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/522/1307305.jpg',
    note: '',
  },
  {
    id: 958,
    tvmazeId: '81511',
    title: 'Chancers checkifcancelled',
    network: 'BBC iPlayer',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/548/1370042.jpg',
    note: '',
  },
  {
    id: 959,
    tvmazeId: '78111',
    title: 'Chastity High',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/533/1333411.jpg',
    note: '',
  },
  {
    id: 960,
    tvmazeId: '64454',
    title: 'Chicken Nugget',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/506/1267108.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 40, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
