window.pageShows = [
  {
    id: 14573,
    tvmazeId: '47203',
    title: 'Little Memole',
    network: 'TV Asahi',
    startYear: 1984,
    years: '1984–1985',
    genres: ['Anime', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/251/629202.jpg',
    note: '',
  },
  {
    id: 14574,
    tvmazeId: '73985',
    title: 'Maggie Briggs',
    network: 'CBS',
    startYear: 1984,
    years: '1984',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14575,
    tvmazeId: '73984',
    title: 'Mama Malone',
    network: 'CBS',
    startYear: 1984,
    years: '1984',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/499/1249841.jpg',
    note: '',
  },
  {
    id: 14576,
    tvmazeId: '18885',
    title: 'Master of the Game',
    network: 'CBS',
    startYear: 1984,
    years: '1984',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/65/163033.jpg',
    note: '',
  },
  {
    id: 14577,
    tvmazeId: '48954',
    title: 'Maximum Security',
    network: 'HBO',
    startYear: 1984,
    years: '1984–1985',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14578,
    tvmazeId: '7549',
    title: 'Me and My Girl',
    network: 'ITV1',
    startYear: 1984,
    years: '1984–1988',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/69645.jpg',
    note: '',
  },
  {
    id: 14579,
    tvmazeId: '760',
    title: 'Miami Vice',
    network: 'NBC',
    startYear: 1984,
    years: '1984–1990',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/357/894989.jpg',
    note: '',
  },
  {
    id: 14580,
    tvmazeId: '19264',
    title: 'Mighty Orbots',
    network: 'ABC',
    startYear: 1984,
    years: '1984',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/297/744033.jpg',
    note: '',
  },
  {
    id: 14581,
    tvmazeId: '51531',
    title: 'Miracles Take Longer',
    network: 'ITV1',
    startYear: 1984,
    years: '1984',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14582,
    tvmazeId: '24151',
    title: 'Miss Marple',
    network: 'BBC Two',
    startYear: 1984,
    years: '1984–1992',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/91/228926.jpg',
    note: '',
  },
  {
    id: 14583,
    tvmazeId: '91054',
    title: 'Missing from Home',
    network: 'BBC One',
    startYear: 1984,
    years: '1984',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14584,
    tvmazeId: '18405',
    title: 'Mistral\'s Daughter',
    network: 'CBS',
    startYear: 1984,
    years: '1984',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/62/156453.jpg',
    note: '',
  },
  {
    id: 14585,
    tvmazeId: '36383',
    title: 'Mitch',
    network: 'ITV1',
    startYear: 1984,
    years: '1984',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/153/384992.jpg',
    note: '',
  },
  {
    id: 14586,
    tvmazeId: '27611',
    title: 'Mother & Son',
    network: 'ABC',
    startYear: 1984,
    years: '1984–1994',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/108/272172.jpg',
    note: '',
  },
  {
    id: 14587,
    tvmazeId: '37564',
    title: 'Mr. Palfrey of Westminster',
    network: 'ITV1',
    startYear: 1984,
    years: '1984–1985',
    genres: ['Drama', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/160/400067.jpg',
    note: '',
  },
  {
    id: 14588,
    tvmazeId: '5490',
    title: 'Muppet Babies',
    network: 'CBS',
    startYear: 1984,
    years: '1984–1991',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/55925.jpg',
    note: '',
  },
  {
    id: 14589,
    tvmazeId: '2083',
    title: 'Murder, She Wrote',
    network: 'CBS',
    startYear: 1984,
    years: '1984–2003',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/28859.jpg',
    note: '',
  },
  {
    id: 14590,
    tvmazeId: '1489',
    title: 'Night Court',
    network: 'NBC',
    startYear: 1984,
    years: '1984–1992',
    genres: ['Comedy', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/8/21196.jpg',
    note: '',
  },
  {
    id: 14591,
    tvmazeId: '35202',
    title: 'Noozles',
    network: 'Nickelodeon',
    startYear: 1984,
    years: '1984',
    genres: ['Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/147/369786.jpg',
    note: '',
  },
  {
    id: 14592,
    tvmazeId: '65112',
    title: 'Off the Rack',
    network: 'ABC',
    startYear: 1984,
    years: '1984–1985',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14593,
    tvmazeId: '24155',
    title: 'One by One',
    network: 'BBC One',
    startYear: 1984,
    years: '1984–1987',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/91/228952.jpg',
    note: '',
  },
  {
    id: 14594,
    tvmazeId: '48235',
    title: 'Oxbridge Blues',
    network: 'BBC Two',
    startYear: 1984,
    years: '1984',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14595,
    tvmazeId: '21742',
    title: 'Paper Dolls',
    network: 'ABC',
    startYear: 1984,
    years: '1984',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/78/195662.jpg',
    note: '',
  },
  {
    id: 14596,
    tvmazeId: '37899',
    title: 'Partners in Crime',
    network: 'NBC',
    startYear: 1984,
    years: '1984',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/162/406048.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 608, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
