window.pageShows = [
  {
    id: 9217,
    tvmazeId: '31372',
    title: 'Rockface',
    network: 'BBC One',
    startYear: 2002,
    years: '2002–2003',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/125/313151.jpg',
    note: '',
  },
  {
    id: 9218,
    tvmazeId: '14545',
    title: 'Rose and Maloney',
    network: 'ITV1',
    startYear: 2002,
    years: '2002–2005',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/49/123086.jpg',
    note: '',
  },
  {
    id: 9219,
    tvmazeId: '2306',
    title: 'Rose Red',
    network: 'ABC',
    startYear: 2002,
    years: '2002',
    genres: ['Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/50/125578.jpg',
    note: '',
  },
  {
    id: 9220,
    tvmazeId: '66410',
    title: 'Scout\'s Safari',
    network: 'NBC',
    startYear: 2002,
    years: '2002–2004',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/441/1104574.jpg',
    note: '',
  },
  {
    id: 9221,
    tvmazeId: '46527',
    title: 'Seriously Weird',
    network: 'YTV',
    startYear: 2002,
    years: '2002',
    genres: ['Family', 'Fantasy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/244/610621.jpg',
    note: '',
  },
  {
    id: 9222,
    tvmazeId: '32711',
    title: 'Shackleton',
    network: 'Channel 4',
    startYear: 2002,
    years: '2002',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/131/328758.jpg',
    note: '',
  },
  {
    id: 9223,
    tvmazeId: '3711',
    title: 'She Spies',
    network: 'Syndication',
    startYear: 2002,
    years: '2002–2004',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/47520.jpg',
    note: '',
  },
  {
    id: 9224,
    tvmazeId: '23225',
    title: 'Short Cuts',
    network: 'Seven Network',
    startYear: 2002,
    years: '2002',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 9225,
    tvmazeId: '40184',
    title: 'Skinwalkers: The Navajo Mysteries',
    network: 'PBS',
    startYear: 2002,
    years: '2002–2004',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/178/446063.jpg',
    note: '',
  },
  {
    id: 9226,
    tvmazeId: '36806',
    title: 'Snow Queen',
    network: 'Hallmark Channel',
    startYear: 2002,
    years: '2002',
    genres: ['Adventure', 'Family', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/222/556017.jpg',
    note: '',
  },
  {
    id: 9227,
    tvmazeId: '37977',
    title: 'Sparkhouse',
    network: 'BBC One',
    startYear: 2002,
    years: '2002',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/162/406773.jpg',
    note: '',
  },
  {
    id: 9228,
    tvmazeId: '657',
    title: 'Spooks',
    network: 'BBC One',
    startYear: 2002,
    years: '2002–2011',
    genres: ['Drama', 'Thriller', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/5/13652.jpg',
    note: '',
  },
  {
    id: 9229,
    tvmazeId: '29371',
    title: 'Stan the Man',
    network: 'ITV1',
    startYear: 2002,
    years: '2002',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 9230,
    tvmazeId: '3721',
    title: 'Stargate: Infinity',
    network: 'FOX',
    startYear: 2002,
    years: '2002–2003',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/47541.jpg',
    note: '',
  },
  {
    id: 9231,
    tvmazeId: '36272',
    title: 'Stig of the Dump',
    network: 'BBC One',
    startYear: 2002,
    years: '2002',
    genres: ['Drama', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/153/382911.jpg',
    note: '',
  },
  {
    id: 9232,
    tvmazeId: '11025',
    title: 'Still Game',
    network: 'BBC Scotland',
    startYear: 2002,
    years: '2002–2019',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/37/92691.jpg',
    note: '',
  },
  {
    id: 9233,
    tvmazeId: '1502',
    title: 'Still Standing',
    network: 'CBS',
    startYear: 2002,
    years: '2002–2006',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/8/21228.jpg',
    note: '',
  },
  {
    id: 9234,
    tvmazeId: '16254',
    title: 'Strange Days at Blake Holsey High',
    network: 'Discovery Family',
    startYear: 2002,
    years: '2002–2006',
    genres: ['Adventure', 'Family', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/54/135620.jpg',
    note: '',
  },
  {
    id: 9235,
    tvmazeId: '39494',
    title: 'Street Time',
    network: 'ABC',
    startYear: 2002,
    years: '2002–2003',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/173/433911.jpg',
    note: '',
  },
  {
    id: 9236,
    tvmazeId: '11223',
    title: 'Sue Thomas F.B.Eye',
    network: 'ION',
    startYear: 2002,
    years: '2002–2005',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/37/94360.jpg',
    note: '',
  },
  {
    id: 9237,
    tvmazeId: '1889',
    title: 'Taken',
    network: 'Syfy',
    startYear: 2002,
    years: '2002',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/27603.jpg',
    note: '',
  },
  {
    id: 9238,
    tvmazeId: '52755',
    title: 'Teamo Supremo',
    network: 'Disney XD',
    startYear: 2002,
    years: '2002–2004',
    genres: ['Comedy', 'Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/291/729403.jpg',
    note: '',
  },
  {
    id: 9239,
    tvmazeId: '35500',
    title: 'Ted and Alice',
    network: 'BBC One',
    startYear: 2002,
    years: '2002',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 9240,
    tvmazeId: '1974',
    title: 'That \'80s Show',
    network: 'FOX',
    startYear: 2002,
    years: '2002',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/27943.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 385, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 824, "cliffhanger": 237, "ended": 13574}};
