window.pageShows = [
  {
    id: 17185,
    tvmazeId: '18443',
    title: 'Medic',
    network: 'NBC',
    startYear: 1954,
    years: '1954–1956',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/62/157075.jpg',
    note: '',
  },
  {
    id: 17186,
    tvmazeId: '79081',
    title: 'Producers\' Showcase',
    network: 'NBC',
    startYear: 1954,
    years: '1954–1957',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17187,
    tvmazeId: '26747',
    title: 'Rocky Jones, Space Ranger',
    network: 'Syndication',
    startYear: 1954,
    years: '1954',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/105/263370.jpg',
    note: '',
  },
  {
    id: 17188,
    tvmazeId: '22618',
    title: 'Sherlock Holmes',
    network: 'Syndication',
    startYear: 1954,
    years: '1954–1955',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/544/1362262.jpg',
    note: '',
  },
  {
    id: 17189,
    tvmazeId: '16191',
    title: 'Stories of the Century',
    network: 'Syndication',
    startYear: 1954,
    years: '1954–1955',
    genres: ['Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/54/135238.jpg',
    note: '',
  },
  {
    id: 17190,
    tvmazeId: '21859',
    title: 'Studio 57',
    network: 'Syndication',
    startYear: 1954,
    years: '1954–1957',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/78/196844.jpg',
    note: '',
  },
  {
    id: 17191,
    tvmazeId: '10604',
    title: 'The Adventures of Rin Tin Tin',
    network: 'ABC',
    startYear: 1954,
    years: '1954–1959',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/35/89272.jpg',
    note: '',
  },
  {
    id: 17192,
    tvmazeId: '59921',
    title: 'The Best of Broadway',
    network: 'CBS',
    startYear: 1954,
    years: '1954–1955',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17193,
    tvmazeId: '75056',
    title: 'The Elgin Hour',
    network: 'ABC',
    startYear: 1954,
    years: '1954–1955',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/506/1266783.jpg',
    note: '',
  },
  {
    id: 17194,
    tvmazeId: '62905',
    title: 'The Grove Family',
    network: 'BBC One',
    startYear: 1954,
    years: '1954–1957',
    genres: ['Drama', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17195,
    tvmazeId: '48889',
    title: 'The Lineup',
    network: 'CBS',
    startYear: 1954,
    years: '1954–1960',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/478/1195390.jpg',
    note: '',
  },
  {
    id: 17196,
    tvmazeId: '62788',
    title: 'The Marriage',
    network: 'NBC',
    startYear: 1954,
    years: '1954',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17197,
    tvmazeId: '29760',
    title: 'The Mickey Rooney Show',
    network: 'NBC',
    startYear: 1954,
    years: '1954–1955',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/118/295862.jpg',
    note: '',
  },
  {
    id: 17198,
    tvmazeId: '42980',
    title: 'The Public Defender',
    network: 'CBS',
    startYear: 1954,
    years: '1954–1955',
    genres: ['Drama', 'Crime', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/204/512212.jpg',
    note: '',
  },
  {
    id: 17199,
    tvmazeId: '75647',
    title: 'The Vise',
    network: 'ABC',
    startYear: 1954,
    years: '1954–1960',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17200,
    tvmazeId: '71094',
    title: 'The Whistler',
    network: 'CBS',
    startYear: 1954,
    years: '1954–1955',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17201,
    tvmazeId: '22156',
    title: 'Action in the Afternoon',
    network: 'CBS',
    startYear: 1953,
    years: '1953',
    genres: ['Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17202,
    tvmazeId: '58443',
    title: 'Colonel Humphrey Flack',
    network: 'DuMont Television Network',
    startYear: 1953,
    years: '1953–1959',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17203,
    tvmazeId: '25234',
    title: 'Ethel and Albert',
    network: 'ABC',
    startYear: 1953,
    years: '1953–1956',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/97/244462.jpg',
    note: '',
  },
  {
    id: 17204,
    tvmazeId: '18432',
    title: 'General Electric Theater',
    network: 'CBS',
    startYear: 1953,
    years: '1953–1961',
    genres: ['Drama', 'Comedy', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/355/889201.jpg',
    note: '',
  },
  {
    id: 17205,
    tvmazeId: '59997',
    title: 'I\'m the Law',
    network: 'Syndication',
    startYear: 1953,
    years: '1953',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17206,
    tvmazeId: '12740',
    title: 'Make Room for Daddy',
    network: 'CBS',
    startYear: 1953,
    years: '1953–1964',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/43/109171.jpg',
    note: '',
  },
  {
    id: 17207,
    tvmazeId: '65961',
    title: 'Ponds Theater',
    network: 'ABC',
    startYear: 1953,
    years: '1953–1955',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17208,
    tvmazeId: '22601',
    title: 'Private Secretary',
    network: 'CBS',
    startYear: 1953,
    years: '1953–1957',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/83/208611.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 717, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
