window.pageShows = [
  {
    id: 15673,
    tvmazeId: '37182',
    title: 'The XYY Man',
    network: 'ITV1',
    startYear: 1976,
    years: '1976–1977',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/158/396868.jpg',
    note: '',
  },
  {
    id: 15674,
    tvmazeId: '9498',
    title: 'The Young Doctors',
    network: 'Nine Network',
    startYear: 1976,
    years: '1976',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/83122.jpg',
    note: '',
  },
  {
    id: 15675,
    tvmazeId: '45151',
    title: 'Van Dyke and Company',
    network: 'NBC',
    startYear: 1976,
    years: '1976',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/226/565462.jpg',
    note: '',
  },
  {
    id: 15676,
    tvmazeId: '79636',
    title: 'Well Anyway',
    network: 'BBC Two',
    startYear: 1976,
    years: '1976',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 15677,
    tvmazeId: '16455',
    title: 'What\'s Happening!!',
    network: 'ABC',
    startYear: 1976,
    years: '1976–1979',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/54/137094.jpg',
    note: '',
  },
  {
    id: 15678,
    tvmazeId: '10422',
    title: 'When the Boat Comes In',
    network: 'BBC One',
    startYear: 1976,
    years: '1976–1981',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/35/88076.jpg',
    note: '',
  },
  {
    id: 15679,
    tvmazeId: '10758',
    title: 'Yanks Go Home',
    network: 'ITV1',
    startYear: 1976,
    years: '1976–1977',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/36/90692.jpg',
    note: '',
  },
  {
    id: 15680,
    tvmazeId: '48701',
    title: 'Yes, Honestly',
    network: 'ITV1',
    startYear: 1976,
    years: '1976–1977',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/261/654397.jpg',
    note: '',
  },
  {
    id: 15681,
    tvmazeId: '20966',
    title: 'Yus, My Dear',
    network: 'ITV1',
    startYear: 1976,
    years: '1976',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/184996.jpg',
    note: '',
  },
  {
    id: 15682,
    tvmazeId: '37689',
    title: 'Приключения Буратино',
    network: 'ЦТ СССР',
    startYear: 1976,
    years: '1976',
    genres: ['Adventure', 'Children', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/160/401759.jpg',
    note: '',
  },
  {
    id: 15683,
    tvmazeId: '74936',
    title: 'Adams of Eagle Lake',
    network: 'ABC',
    startYear: 1975,
    years: '1975',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 15684,
    tvmazeId: '9524',
    title: 'Angels',
    network: 'BBC One',
    startYear: 1975,
    years: '1975–1983',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/83363.jpg',
    note: '',
  },
  {
    id: 15685,
    tvmazeId: '23341',
    title: 'Anne of Avonlea',
    network: 'BBC One',
    startYear: 1975,
    years: '1975',
    genres: ['Drama', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/87/219370.jpg',
    note: '',
  },
  {
    id: 15686,
    tvmazeId: '57529',
    title: 'Archer',
    network: 'NBC',
    startYear: 1975,
    years: '1975',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/626/1566414.jpg',
    note: '',
  },
  {
    id: 15687,
    tvmazeId: '13088',
    title: 'Barbary Coast',
    network: 'ABC',
    startYear: 1975,
    years: '1975–1976',
    genres: ['Action', 'Adventure', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/45/112545.jpg',
    note: '',
  },
  {
    id: 15688,
    tvmazeId: '8092',
    title: 'Baretta',
    network: 'ABC',
    startYear: 1975,
    years: '1975–1978',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/73504.jpg',
    note: '',
  },
  {
    id: 15689,
    tvmazeId: '5782',
    title: 'Barney Miller',
    network: 'ABC',
    startYear: 1975,
    years: '1975–1982',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/206/515173.jpg',
    note: '',
  },
  {
    id: 15690,
    tvmazeId: '39276',
    title: 'Beacon Hill',
    network: 'CBS',
    startYear: 1975,
    years: '1975',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/172/431277.jpg',
    note: '',
  },
  {
    id: 15691,
    tvmazeId: '49079',
    title: 'Black Bart',
    network: 'CBS',
    startYear: 1975,
    years: '1975',
    genres: ['Comedy', 'Crime', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/264/660468.jpg',
    note: '',
  },
  {
    id: 15692,
    tvmazeId: '7764',
    title: 'Bod',
    network: 'BBC One',
    startYear: 1975,
    years: '1975',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/71467.jpg',
    note: '',
  },
  {
    id: 15693,
    tvmazeId: '56884',
    title: 'Bronk',
    network: 'CBS',
    startYear: 1975,
    years: '1975–1976',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/349/873067.jpg',
    note: '',
  },
  {
    id: 15694,
    tvmazeId: '30204',
    title: 'Caribe',
    network: 'ABC',
    startYear: 1975,
    years: '1975',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/367/918470.jpg',
    note: '',
  },
  {
    id: 15695,
    tvmazeId: '11281',
    title: 'Carry On Laughing',
    network: 'ITV1',
    startYear: 1975,
    years: '1975',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/38/95258.jpg',
    note: '',
  },
  {
    id: 15696,
    tvmazeId: '47793',
    title: 'Cash and Company',
    network: 'London Weekend Television',
    startYear: 1975,
    years: '1975',
    genres: ['Drama', 'Action', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/255/637905.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 654, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 398, "cliffhanger": 239, "ended": 15092}};
