window.pageShows = [
  {
    id: 13109,
    tvmazeId: '28538',
    title: 'Mission Top Secret',
    network: 'Network 10',
    startYear: 1993,
    years: '1993–1996',
    genres: ['Adventure', 'Children', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/113/284109.jpg',
    note: '',
  },
  {
    id: 13110,
    tvmazeId: '42637',
    title: 'Moon Over Miami',
    network: 'ABC',
    startYear: 1993,
    years: '1993',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/297/743133.jpg',
    note: '',
  },
  {
    id: 13111,
    tvmazeId: '48323',
    title: 'Mr Don & Mr George',
    network: 'Channel 4',
    startYear: 1993,
    years: '1993',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/258/645958.jpg',
    note: '',
  },
  {
    id: 13112,
    tvmazeId: '29898',
    title: 'Mr. Wroe\'s Virgins',
    network: 'BBC Two',
    startYear: 1993,
    years: '1993',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/118/296694.jpg',
    note: '',
  },
  {
    id: 13113,
    tvmazeId: '28755',
    title: 'Murder in the Heartland',
    network: 'ABC',
    startYear: 1993,
    years: '1993',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/114/286723.jpg',
    note: '',
  },
  {
    id: 13114,
    tvmazeId: '50842',
    title: 'Ned Blessing: The Story of My Life and Times',
    network: 'CBS',
    startYear: 1993,
    years: '1993',
    genres: ['Drama', 'Adventure', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/275/689889.jpg',
    note: '',
  },
  {
    id: 13115,
    tvmazeId: '28589',
    title: 'Newlyweds',
    network: 'Seven Network',
    startYear: 1993,
    years: '1993–1994',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/113/284394.jpg',
    note: '',
  },
  {
    id: 13116,
    tvmazeId: '570',
    title: 'NYPD Blue',
    network: 'ABC',
    startYear: 1993,
    years: '1993–2005',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/4/11779.jpg',
    note: '',
  },
  {
    id: 13117,
    tvmazeId: '73671',
    title: 'Papa Beaver\'s Story Time',
    network: 'Family Channel',
    startYear: 1993,
    years: '1993',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/496/1241338.jpg',
    note: '',
  },
  {
    id: 13118,
    tvmazeId: '7767',
    title: 'Peak Practice',
    network: 'ITV1',
    startYear: 1993,
    years: '1993–2002',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/71628.jpg',
    note: '',
  },
  {
    id: 13119,
    tvmazeId: '34143',
    title: 'Phenom',
    network: 'ABC',
    startYear: 1993,
    years: '1993–1994',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/140/351150.jpg',
    note: '',
  },
  {
    id: 13120,
    tvmazeId: '794',
    title: 'Power Rangers',
    network: 'Netflix',
    startYear: 1993,
    years: '1993–2023',
    genres: ['Action', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/15520.jpg',
    note: '',
  },
  {
    id: 13121,
    tvmazeId: '26417',
    title: 'Problem Child',
    network: 'USA Network',
    startYear: 1993,
    years: '1993–1994',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/104/260072.jpg',
    note: '',
  },
  {
    id: 13122,
    tvmazeId: '26450',
    title: 'Ready or Not',
    network: 'Global',
    startYear: 1993,
    years: '1993–1997',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/104/260309.jpg',
    note: '',
  },
  {
    id: 13123,
    tvmazeId: '8426',
    title: 'Return to Lonesome Dove',
    network: 'CBS',
    startYear: 1993,
    years: '1993',
    genres: ['Drama', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/30/75316.jpg',
    note: '',
  },
  {
    id: 13124,
    tvmazeId: '36170',
    title: 'Rik Mayall Presents',
    network: 'ITV1',
    startYear: 1993,
    years: '1993–1995',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/152/382475.jpg',
    note: '',
  },
  {
    id: 13125,
    tvmazeId: '6322',
    title: 'Rocko\'s Modern Life',
    network: 'Nickelodeon',
    startYear: 1993,
    years: '1993–1996',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/24/60503.jpg',
    note: '',
  },
  {
    id: 13126,
    tvmazeId: '65543',
    title: 'Route 66',
    network: 'NBC',
    startYear: 1993,
    years: '1993',
    genres: ['Drama', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 13127,
    tvmazeId: '8369',
    title: 'Royal Canadian Air Farce',
    network: 'CBC',
    startYear: 1993,
    years: '1993–2008',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/30/75035.jpg',
    note: '',
  },
  {
    id: 13128,
    tvmazeId: '47125',
    title: 'Running the Halls',
    network: 'NBC',
    startYear: 1993,
    years: '1993',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/250/626642.jpg',
    note: '',
  },
  {
    id: 13129,
    tvmazeId: '4452',
    title: 'Saved by the Bell: The College Years',
    network: 'NBC',
    startYear: 1993,
    years: '1993–1994',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/51845.jpg',
    note: '',
  },
  {
    id: 13130,
    tvmazeId: '4453',
    title: 'Saved by the Bell: The New Class',
    network: 'NBC',
    startYear: 1993,
    years: '1993–2000',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/51846.jpg',
    note: '',
  },
  {
    id: 13131,
    tvmazeId: '10935',
    title: 'Scarlet & Black',
    network: 'BBC Two',
    startYear: 1993,
    years: '1993',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/36/92008.jpg',
    note: '',
  },
  {
    id: 13132,
    tvmazeId: '3292',
    title: 'seaQuest DSV',
    network: 'NBC',
    startYear: 1993,
    years: '1993–1996',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/17/43923.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 547, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
