window.pageShows = [
  {
    id: 1849,
    tvmazeId: '54403',
    title: 'The Control Room checkifcancelled',
    network: 'BBC iPlayer',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Thriller'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/416/1040022.jpg',
    note: '',
  },
  {
    id: 1850,
    tvmazeId: '61684',
    title: 'The Creature Cases',
    network: 'Netflix',
    startYear: 2022,
    years: '2022–',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/405/1013044.jpg',
    note: '',
  },
  {
    id: 1851,
    tvmazeId: '42927',
    title: 'The Cuphead Show!',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/593/1484367.jpg',
    note: '',
  },
  {
    id: 1852,
    tvmazeId: '59299',
    title: 'The Curse',
    network: 'Channel 4',
    startYear: 2022,
    years: '2022–2023',
    genres: ['Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/391/978778.jpg',
    note: '',
  },
  {
    id: 1853,
    tvmazeId: '53882',
    title: 'The Devil\'s Hour',
    network: 'Prime Video',
    startYear: 2022,
    years: '2022–',
    genres: ['Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/539/1348192.jpg',
    note: '',
  },
  {
    id: 1854,
    tvmazeId: '73696',
    title: 'The Dirty D',
    network: 'Peacock',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/497/1243987.jpg',
    note: '',
  },
  {
    id: 1855,
    tvmazeId: '82450',
    title: 'The Dreamcatchers',
    network: 'APTN',
    startYear: 2022,
    years: '2022–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/554/1387222.jpg',
    note: '',
  },
  {
    id: 1856,
    tvmazeId: '41736',
    title: 'The Dropout',
    network: 'Hulu',
    startYear: 2022,
    years: '2022',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/395/987963.jpg',
    note: '',
  },
  {
    id: 1857,
    tvmazeId: '56826',
    title: 'The Dry',
    network: 'ITVX',
    startYear: 2022,
    years: '2022–2026',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/624/1561689.jpg',
    note: '',
  },
  {
    id: 1858,
    tvmazeId: '57798',
    title: 'The Endgame',
    network: 'NBC',
    startYear: 2022,
    years: '2022',
    genres: ['Crime', 'Thriller'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'NBC cancelled after one season; Elena\'s master plan and Agent Turner\'s investigation were left completely open.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/394/986259.jpg',
    note: '',
  },
  {
    id: 1859,
    tvmazeId: '55215',
    title: 'The English',
    network: 'BBC iPlayer',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/444/1112100.jpg',
    note: '',
  },
  {
    id: 1860,
    tvmazeId: '49890',
    title: 'The Essex Serpent',
    network: 'Apple TV',
    startYear: 2022,
    years: '2022',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/406/1016494.jpg',
    note: '',
  },
  {
    id: 1861,
    tvmazeId: '61451',
    title: 'The Ex-Wife',
    network: 'Paramount+',
    startYear: 2022,
    years: '2022–2025',
    genres: ['Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/425/1063840.jpg',
    note: '',
  },
  {
    id: 1862,
    tvmazeId: '55642',
    title: 'The Exodite',
    network: 'Warhammer+',
    startYear: 2022,
    years: '2022',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/407/1018680.jpg',
    note: '',
  },
  {
    id: 1863,
    tvmazeId: '53840',
    title: 'The Fairly OddParents: Fairly Odder',
    network: 'Paramount+',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/401/1002520.jpg',
    note: '',
  },
  {
    id: 1864,
    tvmazeId: '54964',
    title: 'The Fear Index',
    network: 'Sky Atlantic',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Science-Fiction', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/385/963087.jpg',
    note: '',
  },
  {
    id: 1865,
    tvmazeId: '46143',
    title: 'The First Lady',
    network: 'Paramount+ with Showtime',
    startYear: 2022,
    years: '2022',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/405/1014009.jpg',
    note: '',
  },
  {
    id: 1866,
    tvmazeId: '60736',
    title: 'The Flatshare',
    network: 'Paramount+',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/444/1110324.jpg',
    note: '',
  },
  {
    id: 1867,
    tvmazeId: '63391',
    title: 'The Four of Them',
    network: 'YouTube',
    startYear: 2022,
    years: '2022',
    genres: ['Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/419/1048285.jpg',
    note: '',
  },
  {
    id: 1868,
    tvmazeId: '55024',
    title: 'The Garcias',
    network: 'HBO Max',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/406/1016612.jpg',
    note: '',
  },
  {
    id: 1869,
    tvmazeId: '34685',
    title: 'The Gilded Age',
    network: 'HBO',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'History'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/572/1431317.jpg',
    note: '',
  },
  {
    id: 1870,
    tvmazeId: '49574',
    title: 'The Girl from Plainville',
    network: 'Hulu',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/404/1010799.jpg',
    note: '',
  },
  {
    id: 1871,
    tvmazeId: '60405',
    title: 'The Guardians of Justice',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy', 'Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/398/995028.jpg',
    note: '',
  },
  {
    id: 1872,
    tvmazeId: '52486',
    title: 'The Holiday',
    network: '5',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/397/994883.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 78, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 856, "cliffhanger": 286, "ended": 13542}};
