window.pageShows = [
  {
    id: 11521,
    tvmazeId: '91225',
    title: 'Deceit',
    network: 'BBC One',
    startYear: 2000,
    years: '2000',
    genres: ['Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11522,
    tvmazeId: '80088',
    title: 'Dirty Work',
    network: 'BBC One',
    startYear: 2000,
    years: '2000',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11523,
    tvmazeId: '3399',
    title: 'Doctors',
    network: 'BBC One',
    startYear: 2000,
    years: '2000–2024',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/105/264564.jpg',
    note: '',
  },
  {
    id: 11524,
    tvmazeId: '6489',
    title: 'Dora the Explorer',
    network: 'Nickelodeon',
    startYear: 2000,
    years: '2000–2019',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/448/1121183.jpg',
    note: '',
  },
  {
    id: 11525,
    tvmazeId: '41848',
    title: 'Down to Earth',
    network: 'BBC One',
    startYear: 2000,
    years: '2000–2005',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/192/480413.jpg',
    note: '',
  },
  {
    id: 11526,
    tvmazeId: '70381',
    title: 'Eckhart',
    network: 'Télé Toon',
    startYear: 2000,
    years: '2000–2002',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/471/1179170.jpg',
    note: '',
  },
  {
    id: 11527,
    tvmazeId: '3643',
    title: 'Ed',
    network: 'NBC',
    startYear: 2000,
    years: '2000–2004',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/47250.jpg',
    note: '',
  },
  {
    id: 11528,
    tvmazeId: '78662',
    title: 'Ethelbert the Tiger',
    network: 'BBC Two',
    startYear: 2000,
    years: '2000–2004',
    genres: ['Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11529,
    tvmazeId: '28573',
    title: 'Eugénie Sandler P.I.',
    network: 'ABC',
    startYear: 2000,
    years: '2000',
    genres: ['Children', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/113/284268.jpg',
    note: '',
  },
  {
    id: 11530,
    tvmazeId: '2207',
    title: 'Even Stevens',
    network: 'Disney Channel',
    startYear: 2000,
    years: '2000–2003',
    genres: ['Comedy', 'Children', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/12/30563.jpg',
    note: '',
  },
  {
    id: 11531,
    tvmazeId: '32959',
    title: 'Falcone',
    network: 'CBS',
    startYear: 2000,
    years: '2000',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/132/332410.jpg',
    note: '',
  },
  {
    id: 11532,
    tvmazeId: '31848',
    title: 'Fat Friends',
    network: 'ITV1',
    startYear: 2000,
    years: '2000–2005',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/522/1306698.jpg',
    note: '',
  },
  {
    id: 11533,
    tvmazeId: '75324',
    title: 'Fetch the Vet',
    network: 'ITV1',
    startYear: 2000,
    years: '2000–2001',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/508/1271763.jpg',
    note: '',
  },
  {
    id: 11534,
    tvmazeId: '70854',
    title: 'For Better or for Worse',
    network: 'Cartoon Network',
    startYear: 2000,
    years: '2000–2001',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/474/1186000.jpg',
    note: '',
  },
  {
    id: 11535,
    tvmazeId: '1101',
    title: 'Frank Herbert\'s Dune',
    network: 'Syfy',
    startYear: 2000,
    years: '2000',
    genres: ['Drama', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17229.jpg',
    note: '',
  },
  {
    id: 11536,
    tvmazeId: '26930',
    title: 'FreakyLinks',
    network: 'FOX',
    startYear: 2000,
    years: '2000–2001',
    genres: ['Horror', 'Science-Fiction', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/106/265912.jpg',
    note: '',
  },
  {
    id: 11537,
    tvmazeId: '36820',
    title: 'Freedom',
    network: 'UPN',
    startYear: 2000,
    years: '2000',
    genres: ['Action', 'Adventure'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/156/390896.jpg',
    note: '',
  },
  {
    id: 11538,
    tvmazeId: '91710',
    title: 'Generation O!',
    network: 'The WB',
    startYear: 2000,
    years: '2000–2001',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/623/1559812.jpg',
    note: '',
  },
  {
    id: 11539,
    tvmazeId: '31024',
    title: 'George Shrinks',
    network: 'PBS Kids',
    startYear: 2000,
    years: '2000–2003',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/123/309005.jpg',
    note: '',
  },
  {
    id: 11540,
    tvmazeId: '15081',
    title: 'Gideon\'s Crossing',
    network: 'ABC',
    startYear: 2000,
    years: '2000–2001',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/353/882673.jpg',
    note: '',
  },
  {
    id: 11541,
    tvmazeId: '525',
    title: 'Gilmore Girls',
    network: 'The CW',
    startYear: 2000,
    years: '2000–2007',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/4/11308.jpg',
    note: '',
  },
  {
    id: 11542,
    tvmazeId: '906',
    title: 'Girlfriends',
    network: 'The CW',
    startYear: 2000,
    years: '2000–2008',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/42/106159.jpg',
    note: '',
  },
  {
    id: 11543,
    tvmazeId: '42495',
    title: 'Glasgow Kiss',
    network: 'BBC One',
    startYear: 2000,
    years: '2000',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/201/502800.jpg',
    note: '',
  },
  {
    id: 11544,
    tvmazeId: '78028',
    title: 'Gloria\'s House',
    network: 'Seven Network',
    startYear: 2000,
    years: '2000',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  }
];
window.pageMetadata = {"page": 481, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
