window.pageShows = [
  {
    id: 5305,
    tvmazeId: '39476',
    title: 'Ladies of the Law',
    network: 'ALLBLK',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Comedy', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/245/614368.jpg',
    note: '',
  },
  {
    id: 5306,
    tvmazeId: '39191',
    title: 'Larva Island',
    network: 'Netflix',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/172/430472.jpg',
    note: '',
  },
  {
    id: 5307,
    tvmazeId: '36072',
    title: 'Le Chalet',
    network: 'France 2',
    startYear: 2018,
    years: '2018',
    genres: ['Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/201/504665.jpg',
    note: '',
  },
  {
    id: 5308,
    tvmazeId: '35478',
    title: 'Lee and Dean',
    network: 'Channel 4',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/189/474683.jpg',
    note: '',
  },
  {
    id: 5309,
    tvmazeId: '36708',
    title: 'Legacies',
    network: 'The CW',
    startYear: 2018,
    years: '2018–2022',
    genres: ['Drama', 'Romance', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/364/911065.jpg',
    note: '',
  },
  {
    id: 5310,
    tvmazeId: '44396',
    title: 'LEGO Friends: Girls on a Mission',
    network: 'Family Channel',
    startYear: 2018,
    years: '2018–2021',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/215/537550.jpg',
    note: '',
  },
  {
    id: 5311,
    tvmazeId: '39694',
    title: 'LEGO Jurassic World: The Secret Exhibit',
    network: 'NBC',
    startYear: 2018,
    years: '2018',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/174/435746.jpg',
    note: '',
  },
  {
    id: 5312,
    tvmazeId: '39408',
    title: 'LEGO Star Wars: All-Stars',
    network: 'Disney XD',
    startYear: 2018,
    years: '2018',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/318/795191.jpg',
    note: '',
  },
  {
    id: 5313,
    tvmazeId: '19535',
    title: 'Les Misérables',
    network: 'BBC One',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Drama', 'Romance', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/178/445322.jpg',
    note: '',
  },
  {
    id: 5314,
    tvmazeId: '27086',
    title: 'Let\'s Get Physical',
    network: 'Pop',
    startYear: 2018,
    years: '2018',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/146/366896.jpg',
    note: '',
  },
  {
    id: 5315,
    tvmazeId: '83416',
    title: 'Let\'s Go Luna!',
    network: 'PBS Kids',
    startYear: 2018,
    years: '2018–2022',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/560/1401246.jpg',
    note: '',
  },
  {
    id: 5316,
    tvmazeId: '26596',
    title: 'Liberty Crossing',
    network: 'go90',
    startYear: 2018,
    years: '2018',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/142/355151.jpg',
    note: '',
  },
  {
    id: 5317,
    tvmazeId: '24915',
    title: 'Life Sentence',
    network: 'The CW',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/145/363287.jpg',
    note: '',
  },
  {
    id: 5318,
    tvmazeId: '36655',
    title: 'Light as a Feather',
    network: 'Hulu',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Drama', 'Horror', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/213/534600.jpg',
    note: '',
  },
  {
    id: 5319,
    tvmazeId: '50899',
    title: 'Like and Subscribe',
    network: 'Prime Video',
    startYear: 2018,
    years: '2018',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/276/690501.jpg',
    note: '',
  },
  {
    id: 5320,
    tvmazeId: '28465',
    title: 'Little Dog',
    network: 'CBC',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/146/366761.jpg',
    note: '',
  },
  {
    id: 5321,
    tvmazeId: '51430',
    title: 'Littlest Pet Shop: A World of Our Own',
    network: 'Discovery Family',
    startYear: 2018,
    years: '2018',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/279/698231.jpg',
    note: '',
  },
  {
    id: 5322,
    tvmazeId: '48176',
    title: 'Liverspots and Astronots',
    network: 'Facebook Watch',
    startYear: 2018,
    years: '2018',
    genres: ['Comedy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/257/643711.jpg',
    note: '',
  },
  {
    id: 5323,
    tvmazeId: '25132',
    title: 'Living Biblically',
    network: 'CBS',
    startYear: 2018,
    years: '2018',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/143/359278.jpg',
    note: '',
  },
  {
    id: 5324,
    tvmazeId: '37945',
    title: 'Liza on Demand',
    network: 'YouTube Premium',
    startYear: 2018,
    years: '2018–2021',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/369/923586.jpg',
    note: '',
  },
  {
    id: 5325,
    tvmazeId: '25909',
    title: 'Llama Llama',
    network: 'Netflix',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/143/359341.jpg',
    note: '',
  },
  {
    id: 5326,
    tvmazeId: '21765',
    title: 'Lodge 49',
    network: 'AMC',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/202/505714.jpg',
    note: '',
  },
  {
    id: 5327,
    tvmazeId: '37583',
    title: 'Logan High',
    network: 'BBC iPlayer',
    startYear: 2018,
    years: '2018',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/236/590079.jpg',
    note: '',
  },
  {
    id: 5328,
    tvmazeId: '8898',
    title: 'Lost in Space',
    network: 'Netflix',
    startYear: 2018,
    years: '2018–2021',
    genres: ['Drama', 'Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: 'Netflix gave the show a three-season planned conclusion.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/372/930999.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 222, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
