window.pageShows = [
  {
    id: 16945,
    tvmazeId: '13467',
    title: 'Quatermass and the Pit',
    network: 'BBC One',
    startYear: 1958,
    years: '1958–1959',
    genres: ['Drama', 'Science-Fiction', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/465/1163270.jpg',
    note: '',
  },
  {
    id: 16946,
    tvmazeId: '62295',
    title: 'Rescue 8',
    network: 'Syndication',
    startYear: 1958,
    years: '1958',
    genres: ['Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/410/1026327.jpg',
    note: '',
  },
  {
    id: 16947,
    tvmazeId: '3710',
    title: 'Sea Hunt',
    network: 'Syndication',
    startYear: 1958,
    years: '1958–1961',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/47519.jpg',
    note: '',
  },
  {
    id: 16948,
    tvmazeId: '31778',
    title: 'Shirley Temple\'s Storybook',
    network: 'NBC',
    startYear: 1958,
    years: '1958–1960',
    genres: ['Drama', 'Family', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/127/318428.jpg',
    note: '',
  },
  {
    id: 16949,
    tvmazeId: '84668',
    title: 'Solo for Canary',
    network: 'BBC One',
    startYear: 1958,
    years: '1958',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 16950,
    tvmazeId: '55165',
    title: 'Steve Canyon',
    network: 'NBC',
    startYear: 1958,
    years: '1958–1959',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/314/786407.jpg',
    note: '',
  },
  {
    id: 16951,
    tvmazeId: '41208',
    title: 'Sword of Freedom',
    network: 'ITV1',
    startYear: 1958,
    years: '1958–1961',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/186/465958.jpg',
    note: '',
  },
  {
    id: 16952,
    tvmazeId: '56611',
    title: 'Texas John Slaughter',
    network: 'ABC',
    startYear: 1958,
    years: '1958–1961',
    genres: ['Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/344/861760.jpg',
    note: '',
  },
  {
    id: 16953,
    tvmazeId: '57531',
    title: 'The Ann Sothern Show',
    network: 'CBS',
    startYear: 1958,
    years: '1958–1961',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/388/971962.jpg',
    note: '',
  },
  {
    id: 16954,
    tvmazeId: '24644',
    title: 'The Donna Reed Show',
    network: 'ABC',
    startYear: 1958,
    years: '1958–1966',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/616/1540995.jpg',
    note: '',
  },
  {
    id: 16955,
    tvmazeId: '40536',
    title: 'The Ed Wynn Show',
    network: 'NBC',
    startYear: 1958,
    years: '1958–1959',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/477/1194069.jpg',
    note: '',
  },
  {
    id: 16956,
    tvmazeId: '16535',
    title: 'The Friendly Giant',
    network: 'CBC',
    startYear: 1958,
    years: '1958–1960',
    genres: ['Children', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/55/138301.jpg',
    note: '',
  },
  {
    id: 16957,
    tvmazeId: '83891',
    title: 'The Further Adventures of Ellery Queen',
    network: 'NBC',
    startYear: 1958,
    years: '1958–1959',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 16958,
    tvmazeId: '5754',
    title: 'The Huckleberry Hound Show',
    network: 'CBS',
    startYear: 1958,
    years: '1958–1961',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/522/1307491.jpg',
    note: '',
  },
  {
    id: 16959,
    tvmazeId: '43220',
    title: 'The Larkins',
    network: 'ITV1',
    startYear: 1958,
    years: '1958–1964',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/206/517263.jpg',
    note: '',
  },
  {
    id: 16960,
    tvmazeId: '3877',
    title: 'The Rifleman',
    network: 'ABC',
    startYear: 1958,
    years: '1958–1963',
    genres: ['Action', 'Adventure', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/48671.jpg',
    note: '',
  },
  {
    id: 16961,
    tvmazeId: '37056',
    title: 'The Rough Riders',
    network: 'ABC',
    startYear: 1958,
    years: '1958–1959',
    genres: ['Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 16962,
    tvmazeId: '56283',
    title: 'The Texan',
    network: 'CBS',
    startYear: 1958,
    years: '1958–1960',
    genres: ['Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/337/844404.jpg',
    note: '',
  },
  {
    id: 16963,
    tvmazeId: '18037',
    title: 'The Veil',
    network: 'Syndication',
    startYear: 1958,
    years: '1958',
    genres: ['Fantasy', 'Horror', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/61/152871.jpg',
    note: '',
  },
  {
    id: 16964,
    tvmazeId: '5755',
    title: 'The Yogi Bear Show',
    network: 'Syndication',
    startYear: 1958,
    years: '1958–1962',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/57393.jpg',
    note: '',
  },
  {
    id: 16965,
    tvmazeId: '41330',
    title: 'Union Pacific',
    network: 'Syndication',
    startYear: 1958,
    years: '1958–1959',
    genres: ['Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/187/468807.jpg',
    note: '',
  },
  {
    id: 16966,
    tvmazeId: '4380',
    title: 'Wanted: Dead or Alive',
    network: 'CBS',
    startYear: 1958,
    years: '1958–1961',
    genres: ['Drama', 'Action', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/51669.jpg',
    note: '',
  },
  {
    id: 16967,
    tvmazeId: '27613',
    title: 'Westinghouse Desilu Playhouse',
    network: 'CBS',
    startYear: 1958,
    years: '1958–1960',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/365/913145.jpg',
    note: '',
  },
  {
    id: 16968,
    tvmazeId: '21082',
    title: 'William Tell',
    network: 'ITV1',
    startYear: 1958,
    years: '1958–1959',
    genres: ['Action', 'Adventure', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/74/186088.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 707, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
