window.pageShows = [
  {
    id: 4849,
    tvmazeId: '92509',
    title: 'Real Life Lore',
    network: 'Nebula',
    startYear: 2016,
    years: '2016–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/628/1571859.jpg',
    note: '',
  },
  {
    id: 4850,
    tvmazeId: '3726',
    title: 'Rebellion',
    network: 'RTÉ ONE',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'War', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/295/738321.jpg',
    note: '',
  },
  {
    id: 4851,
    tvmazeId: '2186',
    title: 'Recovery Road',
    network: 'Freeform',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/149/374391.jpg',
    note: '',
  },
  {
    id: 4852,
    tvmazeId: '19978',
    title: 'Regal Academy',
    network: 'Nickelodeon',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/357/893250.jpg',
    note: '',
  },
  {
    id: 4853,
    tvmazeId: '16382',
    title: 'Relationship Status',
    network: 'go90',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/54/136563.jpg',
    note: '',
  },
  {
    id: 4854,
    tvmazeId: '44084',
    title: 'Ren: The Girl with the Mark',
    network: 'YouTube',
    startYear: 2016,
    years: '2016–',
    genres: ['Drama', 'Adventure', 'Fantasy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/213/532525.jpg',
    note: '',
  },
  {
    id: 4855,
    tvmazeId: '18084',
    title: 'RePlay',
    network: 'go90',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy', 'Fantasy', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/61/153353.jpg',
    note: '',
  },
  {
    id: 4856,
    tvmazeId: '23280',
    title: 'Revolting Rhymes',
    network: 'BBC One',
    startYear: 2016,
    years: '2016',
    genres: ['Family', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/95/239378.jpg',
    note: '',
  },
  {
    id: 4857,
    tvmazeId: '22562',
    title: 'Rhett & Link\'s Buddy System',
    network: 'YouTube Premium',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/83/208474.jpg',
    note: '',
  },
  {
    id: 4858,
    tvmazeId: '56775',
    title: 'Rick and Morty Specials',
    network: 'Adult Swim',
    startYear: 2016,
    years: '2016–2022',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 4859,
    tvmazeId: '55936',
    title: 'Rick and Morty: The Non-Canonical Adventures',
    network: 'AdultSwim.com',
    startYear: 2016,
    years: '2016–2021',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/348/871668.jpg',
    note: '',
  },
  {
    id: 4860,
    tvmazeId: '20902',
    title: 'Ride',
    network: 'YTV',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/397/994363.jpg',
    note: '',
  },
  {
    id: 4861,
    tvmazeId: '20927',
    title: 'Right Now Kapow',
    network: 'Disney XD',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/184789.jpg',
    note: '',
  },
  {
    id: 4862,
    tvmazeId: '21316',
    title: 'Rillington Place',
    network: 'BBC One',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/87/219262.jpg',
    note: '',
  },
  {
    id: 4863,
    tvmazeId: '2740',
    title: 'Roadies',
    network: 'Paramount+ with Showtime',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/206/516515.jpg',
    note: '',
  },
  {
    id: 4864,
    tvmazeId: '19827',
    title: 'Robin Hood: Mischief in Sherwood',
    network: 'Discovery Family',
    startYear: 2016,
    years: '2016',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/70/175052.jpg',
    note: '',
  },
  {
    id: 4865,
    tvmazeId: '22666',
    title: 'Roman Empire',
    network: 'Netflix',
    startYear: 2016,
    years: '2016–2019',
    genres: ['Drama', 'Action', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/190/476560.jpg',
    note: '',
  },
  {
    id: 4866,
    tvmazeId: '5513',
    title: 'Roots',
    network: 'History',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/59/149729.jpg',
    note: '',
  },
  {
    id: 4867,
    tvmazeId: '20058',
    title: 'Rosehaven',
    network: 'ABC',
    startYear: 2016,
    years: '2016–2021',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/266/665864.jpg',
    note: '',
  },
  {
    id: 4868,
    tvmazeId: '26915',
    title: 'Rostered On',
    network: 'YouTube',
    startYear: 2016,
    years: '2016–2022',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/106/265656.jpg',
    note: '',
  },
  {
    id: 4869,
    tvmazeId: '36530',
    title: 'Round Planet',
    network: 'BBC Earth',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy', 'Nature'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/154/386164.jpg',
    note: '',
  },
  {
    id: 4870,
    tvmazeId: '6761',
    title: 'Rovers',
    network: 'Sky Showcase',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/59/149230.jpg',
    note: '',
  },
  {
    id: 4871,
    tvmazeId: '24344',
    title: 'Rufus',
    network: 'Nickelodeon',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/92/231542.jpg',
    note: '',
  },
  {
    id: 4872,
    tvmazeId: '3076',
    title: 'Rush Hour',
    network: 'CBS',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/50/125780.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 203, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 334, "cliffhanger": 235, "ended": 13701}};
