window.pageShows = [
  {
    id: 3145,
    tvmazeId: '36872',
    title: 'Good Trouble',
    network: 'Freeform',
    startYear: 2019,
    years: '2019–2024',
    genres: ['Drama', 'Family', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/501/1252566.jpg',
    note: '',
  },
  {
    id: 3146,
    tvmazeId: '36757',
    title: 'Grand Hotel',
    network: 'ABC',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/195/488154.jpg',
    note: '',
  },
  {
    id: 3147,
    tvmazeId: '41144',
    title: 'Green Eggs and Ham',
    network: 'Netflix',
    startYear: 2019,
    years: '2019–2022',
    genres: ['Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/218/545918.jpg',
    note: '',
  },
  {
    id: 3148,
    tvmazeId: '44273',
    title: 'Guilt',
    network: 'BBC iPlayer',
    startYear: 2019,
    years: '2019–2023',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/217/542542.jpg',
    note: '',
  },
  {
    id: 3149,
    tvmazeId: '28449',
    title: 'Hanna',
    network: 'Prime Video',
    startYear: 2019,
    years: '2019–2021',
    genres: ['Drama', 'Action', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/375/939904.jpg',
    note: '',
  },
  {
    id: 3150,
    tvmazeId: '47588',
    title: 'Hardball',
    network: 'ABC Entertains',
    startYear: 2019,
    years: '2019–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/254/635065.jpg',
    note: '',
  },
  {
    id: 3151,
    tvmazeId: '33452',
    title: 'Harley Quinn',
    network: 'HBO Max',
    startYear: 2019,
    years: '2019–',
    genres: ['Comedy', 'Action', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: 'Max — ongoing; renewed through multiple seasons.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/547/1368613.jpg',
    note: '',
  },
  {
    id: 3152,
    tvmazeId: '29777',
    title: 'Hatton Garden',
    network: 'ITV1',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/447/1118926.jpg',
    note: '',
  },
  {
    id: 3153,
    tvmazeId: '43094',
    title: 'Hazbin Hotel',
    network: 'Prime Video',
    startYear: 2019,
    years: '2019–',
    genres: ['Comedy', 'Fantasy', 'Horror'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/594/1487307.jpg',
    note: '',
  },
  {
    id: 3154,
    tvmazeId: '43800',
    title: 'Headcases',
    network: 'RTÉ ONE',
    startYear: 2019,
    years: '2019',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/210/527226.jpg',
    note: '',
  },
  {
    id: 3155,
    tvmazeId: '45066',
    title: 'Hell Den',
    network: 'Syfy',
    startYear: 2019,
    years: '2019–2020',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/224/560927.jpg',
    note: '',
  },
  {
    id: 3156,
    tvmazeId: '44863',
    title: 'Hello Ninja',
    network: 'Netflix',
    startYear: 2019,
    years: '2019–2021',
    genres: ['Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/253/633696.jpg',
    note: '',
  },
  {
    id: 3157,
    tvmazeId: '45397',
    title: 'Helluva Boss',
    network: 'Prime Video',
    startYear: 2019,
    years: '2019–',
    genres: ['Comedy', 'Fantasy', 'Horror'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/515/1288260.jpg',
    note: '',
  },
  {
    id: 3158,
    tvmazeId: '39678',
    title: 'High School Musical: The Musical: The Series',
    network: 'Disney+',
    startYear: 2019,
    years: '2019–2023',
    genres: ['Drama', 'Comedy', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/465/1164995.jpg',
    note: '',
  },
  {
    id: 3159,
    tvmazeId: '45282',
    title: 'High Wizard',
    network: 'Syfy',
    startYear: 2019,
    years: '2019',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 3160,
    tvmazeId: '42364',
    title: 'Himmelsdalen',
    network: 'C More',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/200/500017.jpg',
    note: '',
  },
  {
    id: 3161,
    tvmazeId: '7626',
    title: 'His Dark Materials',
    network: 'BBC iPlayer',
    startYear: 2019,
    years: '2019–2022',
    genres: ['Drama', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/445/1113926.jpg',
    note: '',
  },
  {
    id: 3162,
    tvmazeId: '41233',
    title: 'Home',
    network: 'Channel 4',
    startYear: 2019,
    years: '2019–2020',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/191/477743.jpg',
    note: '',
  },
  {
    id: 3163,
    tvmazeId: '60565',
    title: 'Horrible Histories Top 5',
    network: 'BBC iPlayer',
    startYear: 2019,
    years: '2019',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 3164,
    tvmazeId: '44047',
    title: 'Hospital Show',
    network: 'YouTube',
    startYear: 2019,
    years: '2019–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/212/531916.jpg',
    note: '',
  },
  {
    id: 3165,
    tvmazeId: '39049',
    title: 'Hudson & Rex',
    network: 'Citytv',
    startYear: 2019,
    years: '2019–',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/594/1485046.jpg',
    note: '',
  },
  {
    id: 3166,
    tvmazeId: '33332',
    title: 'Huge in France',
    network: 'Netflix',
    startYear: 2019,
    years: '2019',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/189/473898.jpg',
    note: '',
  },
  {
    id: 3167,
    tvmazeId: '41131',
    title: 'Human Discoveries',
    network: 'Facebook Watch',
    startYear: 2019,
    years: '2019',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/203/508392.jpg',
    note: '',
  },
  {
    id: 3168,
    tvmazeId: '43081',
    title: 'I Am',
    network: 'Channel 4',
    startYear: 2019,
    years: '2019–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/207/518786.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 132, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 785, "cliffhanger": 237, "ended": 13610}};
