window.pageShows = [
  {
    id: 10517,
    tvmazeId: '20006',
    title: 'The Ghost Squad',
    network: 'Channel 4',
    startYear: 2005,
    years: '2005',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/70/176479.jpg',
    note: '',
  },
  {
    id: 10518,
    tvmazeId: '36117',
    title: 'The Golden Hour',
    network: 'ITV1',
    startYear: 2005,
    years: '2005',
    genres: ['Drama', 'Medical'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 10519,
    tvmazeId: '3991',
    title: 'The Green Green Grass',
    network: 'BBC One',
    startYear: 2005,
    years: '2005–2009',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/49243.jpg',
    note: '',
  },
  {
    id: 10520,
    tvmazeId: '10505',
    title: 'The Incredible Journey of Mary Bryant',
    network: 'Network 10',
    startYear: 2005,
    years: '2005',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/35/88715.jpg',
    note: '',
  },
  {
    id: 10521,
    tvmazeId: '1019',
    title: 'The Inside',
    network: 'FOX',
    startYear: 2005,
    years: '2005',
    genres: ['Drama', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Fox cancelled after one season mid-story.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16663.jpg',
    note: '',
  },
  {
    id: 10522,
    tvmazeId: '17659',
    title: 'The Insiders Guide to Love',
    network: 'TVNZ 2',
    startYear: 2005,
    years: '2005',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/186/466358.jpg',
    note: '',
  },
  {
    id: 10523,
    tvmazeId: '16204',
    title: 'The Life and Times of Juniper Lee',
    network: 'Cartoon Network',
    startYear: 2005,
    years: '2005–2007',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/54/135330.jpg',
    note: '',
  },
  {
    id: 10524,
    tvmazeId: '23368',
    title: 'The Murder Room',
    network: 'BBC One',
    startYear: 2005,
    years: '2005',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/87/219416.jpg',
    note: '',
  },
  {
    id: 10525,
    tvmazeId: '9754',
    title: 'The New Tomorrow',
    network: 'Seven Network',
    startYear: 2005,
    years: '2005',
    genres: ['Drama', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/84560.jpg',
    note: '',
  },
  {
    id: 10526,
    tvmazeId: '26619',
    title: 'The New Worst Witch',
    network: 'ITV1',
    startYear: 2005,
    years: '2005–2007',
    genres: ['Drama', 'Comedy', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/104/261787.jpg',
    note: '',
  },
  {
    id: 10527,
    tvmazeId: '526',
    title: 'The Office',
    network: 'NBC',
    startYear: 2005,
    years: '2005–2013',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/481/1204342.jpg',
    note: '',
  },
  {
    id: 10528,
    tvmazeId: '31776',
    title: 'The Poseidon Adventure',
    network: 'Hallmark Channel',
    startYear: 2005,
    years: '2005',
    genres: ['Drama', 'Adventure', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/127/318334.jpg',
    note: '',
  },
  {
    id: 10529,
    tvmazeId: '41106',
    title: 'The Prince Who Turns Into a Frog',
    network: 'TTV',
    startYear: 2005,
    years: '2005',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/185/463028.jpg',
    note: '',
  },
  {
    id: 10530,
    tvmazeId: '33011',
    title: 'The Robinsons',
    network: 'BBC Two',
    startYear: 2005,
    years: '2005',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/133/333191.jpg',
    note: '',
  },
  {
    id: 10531,
    tvmazeId: '915',
    title: 'The Suite Life of Zack and Cody',
    network: 'Disney Channel',
    startYear: 2005,
    years: '2005–2008',
    genres: ['Comedy', 'Children', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/453/1132771.jpg',
    note: '',
  },
  {
    id: 10532,
    tvmazeId: '17662',
    title: 'The Surgeon',
    network: 'Network 10',
    startYear: 2005,
    years: '2005',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/287/718643.jpg',
    note: '',
  },
  {
    id: 10533,
    tvmazeId: '1667',
    title: 'The Thick of It',
    network: 'BBC Four',
    startYear: 2005,
    years: '2005–2012',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/9/22970.jpg',
    note: '',
  },
  {
    id: 10534,
    tvmazeId: '2022',
    title: 'The Triangle',
    network: 'Syfy',
    startYear: 2005,
    years: '2005',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/28268.jpg',
    note: '',
  },
  {
    id: 10535,
    tvmazeId: '2866',
    title: 'The War at Home',
    network: 'FOX',
    startYear: 2005,
    years: '2005–2007',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/15/39064.jpg',
    note: '',
  },
  {
    id: 10536,
    tvmazeId: '73892',
    title: 'The X\'s',
    network: 'Nickelodeon',
    startYear: 2005,
    years: '2005–2006',
    genres: ['Action', 'Children', 'Espionage'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/499/1248066.jpg',
    note: '',
  },
  {
    id: 10537,
    tvmazeId: '12442',
    title: 'The Zula Patrol',
    network: 'PBS Kids',
    startYear: 2005,
    years: '2005–2008',
    genres: ['Comedy', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/42/106273.jpg',
    note: '',
  },
  {
    id: 10538,
    tvmazeId: '1963',
    title: 'Threshold',
    network: 'CBS',
    startYear: 2005,
    years: '2005',
    genres: ['Drama', 'Science-Fiction', 'Thriller'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'CBS cancelled after nine episodes; the alien signal\'s spread and Molly Caffrey\'s response team were mid-arc.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/27910.jpg',
    note: '',
  },
  {
    id: 10539,
    tvmazeId: '4502',
    title: 'Tilt',
    network: 'ESPN',
    startYear: 2005,
    years: '2005',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/52008.jpg',
    note: '',
  },
  {
    id: 10540,
    tvmazeId: '68791',
    title: 'Time Warp Trio',
    network: 'Discovery Family',
    startYear: 2005,
    years: '2005–2006',
    genres: ['Adventure', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/461/1154323.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 439, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
