window.pageShows = [
  {
    id: 4897,
    tvmazeId: '23185',
    title: 'Sonnigsburg',
    network: 'C31',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Mystery', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/89/223446.jpg',
    note: '',
  },
  {
    id: 4898,
    tvmazeId: '76272',
    title: 'SpacePOP',
    network: 'YouTube',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Family', 'Fantasy', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/515/1288242.jpg',
    note: '',
  },
  {
    id: 4899,
    tvmazeId: '11553',
    title: 'Speechless',
    network: 'ABC',
    startYear: 2016,
    years: '2016–2019',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/138/346144.jpg',
    note: '',
  },
  {
    id: 4900,
    tvmazeId: '23075',
    title: 'Splash and Bubbles',
    network: 'PBS',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/85/214897.jpg',
    note: '',
  },
  {
    id: 4901,
    tvmazeId: '13739',
    title: 'Spot Bots',
    network: 'CBeebies',
    startYear: 2016,
    years: '2016',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/47/118709.jpg',
    note: '',
  },
  {
    id: 4902,
    tvmazeId: '16484',
    title: 'Spot Bots Zoople Time',
    network: 'CBeebies',
    startYear: 2016,
    years: '2016',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 4903,
    tvmazeId: '13103',
    title: 'Stag',
    network: 'BBC Two',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/49/124419.jpg',
    note: '',
  },
  {
    id: 4904,
    tvmazeId: '16020',
    title: 'Stan Against Evil',
    network: 'IFC',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Comedy', 'Action', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/131/327936.jpg',
    note: '',
  },
  {
    id: 4905,
    tvmazeId: '6775',
    title: 'Stan Lee\'s Lucky Man',
    network: 'Sky Showcase',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Drama', 'Crime', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/161/404649.jpg',
    note: '',
  },
  {
    id: 4906,
    tvmazeId: '2746',
    title: 'Star',
    network: 'FOX',
    startYear: 2016,
    years: '2016–2019',
    genres: ['Drama', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/88/222182.jpg',
    note: '',
  },
  {
    id: 4907,
    tvmazeId: '33577',
    title: 'Star Wars: Go Rogue',
    network: 'YouTube',
    startYear: 2016,
    years: '2016',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/208/520744.jpg',
    note: '',
  },
  {
    id: 4908,
    tvmazeId: '12323',
    title: 'StartUp',
    network: 'Crackle',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/173/433460.jpg',
    note: '',
  },
  {
    id: 4909,
    tvmazeId: '2161',
    title: 'Still The King',
    network: 'CMT',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Comedy', 'Family', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/51/129737.jpg',
    note: '',
  },
  {
    id: 4910,
    tvmazeId: '59639',
    title: 'StoryBots Super Songs',
    network: 'Netflix',
    startYear: 2016,
    years: '2016',
    genres: ['Children', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/395/987967.jpg',
    note: '',
  },
  {
    id: 4911,
    tvmazeId: '2993',
    title: 'Stranger Things',
    network: 'Netflix',
    startYear: 2016,
    years: '2016–2025',
    genres: ['Drama', 'Horror', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/595/1489169.jpg',
    note: '',
  },
  {
    id: 4912,
    tvmazeId: '32861',
    title: 'Street Fighter: Resurrection',
    network: 'Machinima',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Action', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/132/330952.jpg',
    note: '',
  },
  {
    id: 4913,
    tvmazeId: '5264',
    title: 'Stuck in the Middle',
    network: 'DisneyNOW',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/50/126283.jpg',
    note: '',
  },
  {
    id: 4914,
    tvmazeId: '22654',
    title: 'Subject to Change',
    network: 'YouTube',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/93/232593.jpg',
    note: '',
  },
  {
    id: 4915,
    tvmazeId: '16671',
    title: 'Submission',
    network: 'Paramount+ with Showtime',
    startYear: 2016,
    years: '2016',
    genres: ['Romance', 'Mystery', 'Adult'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/58/146575.jpg',
    note: '',
  },
  {
    id: 4916,
    tvmazeId: '71123',
    title: 'Successful People',
    network: 'Prime Video',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/476/1190805.jpg',
    note: '',
  },
  {
    id: 4917,
    tvmazeId: '16746',
    title: 'Sudden Master',
    network: 'YouTube',
    startYear: 2016,
    years: '2016',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 4918,
    tvmazeId: '47988',
    title: 'Sunny Bunnies',
    network: 'YouTube',
    startYear: 2016,
    years: '2016–',
    genres: ['Adventure', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/256/640618.jpg',
    note: '',
  },
  {
    id: 4919,
    tvmazeId: '22461',
    title: 'Sunny D',
    network: 'BBC Three',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/85/213487.jpg',
    note: '',
  },
  {
    id: 4920,
    tvmazeId: '11551',
    title: 'Sunset PPL',
    network: 'NBC',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/72/181404.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 205, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 824, "cliffhanger": 237, "ended": 13574}};
