window.pageShows = [
  {
    id: 14833,
    tvmazeId: '5676',
    title: 'SuperTed',
    network: 'BBC One',
    startYear: 1983,
    years: '1983–1986',
    genres: ['Family', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/56892.jpg',
    note: '',
  },
  {
    id: 14834,
    tvmazeId: '35851',
    title: 'Sweet Sixteen',
    network: 'BBC One',
    startYear: 1983,
    years: '1983',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/421/1054512.jpg',
    note: '',
  },
  {
    id: 14835,
    tvmazeId: '6792',
    title: 'Taggart',
    network: 'ITV1',
    startYear: 1983,
    years: '1983–2010',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/607/1519309.jpg',
    note: '',
  },
  {
    id: 14836,
    tvmazeId: '36402',
    title: 'Tears Before Bedtime',
    network: 'BBC One',
    startYear: 1983,
    years: '1983',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14837,
    tvmazeId: '9535',
    title: 'Terrahawks',
    network: 'Syndication',
    startYear: 1983,
    years: '1983–1986',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/83378.jpg',
    note: '',
  },
  {
    id: 14838,
    tvmazeId: '1058',
    title: 'The A-Team',
    network: 'NBC',
    startYear: 1983,
    years: '1983–1987',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17013.jpg',
    note: '',
  },
  {
    id: 14839,
    tvmazeId: '49362',
    title: 'The Adventures of Portland Bill',
    network: 'ITV1',
    startYear: 1983,
    years: '1983–1984',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/266/665489.jpg',
    note: '',
  },
  {
    id: 14840,
    tvmazeId: '22616',
    title: 'The Baker Street Boys',
    network: 'BBC One',
    startYear: 1983,
    years: '1983',
    genres: ['Adventure', 'Children', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/83/208851.jpg',
    note: '',
  },
  {
    id: 14841,
    tvmazeId: '20365',
    title: 'The Biskitts',
    network: 'CBS',
    startYear: 1983,
    years: '1983',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/72/180228.jpg',
    note: '',
  },
  {
    id: 14842,
    tvmazeId: '67641',
    title: 'The Boy Who Won The Pools',
    network: 'ITV1',
    startYear: 1983,
    years: '1983',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14843,
    tvmazeId: '56680',
    title: 'The Cabbage Patch',
    network: 'ITV1',
    startYear: 1983,
    years: '1983',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14844,
    tvmazeId: '8206',
    title: 'The Charlie Brown and Snoopy Show',
    network: 'CBS',
    startYear: 1983,
    years: '1983–1985',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/74273.jpg',
    note: '',
  },
  {
    id: 14845,
    tvmazeId: '36311',
    title: 'The Citadel',
    network: 'BBC One',
    startYear: 1983,
    years: '1983',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/153/383590.jpg',
    note: '',
  },
  {
    id: 14846,
    tvmazeId: '86705',
    title: 'The Climber',
    network: 'BBC One',
    startYear: 1983,
    years: '1983',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/597/1493395.jpg',
    note: '',
  },
  {
    id: 14847,
    tvmazeId: '35178',
    title: 'The Crystal Cube',
    network: 'BBC Two',
    startYear: 1983,
    years: '1983',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14848,
    tvmazeId: '18982',
    title: 'The Dark Side of the Sun',
    network: 'BBC One',
    startYear: 1983,
    years: '1983',
    genres: ['Fantasy', 'Horror', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/65/164284.jpg',
    note: '',
  },
  {
    id: 14849,
    tvmazeId: '29705',
    title: 'The Dukes',
    network: 'CBS',
    startYear: 1983,
    years: '1983',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/118/295037.jpg',
    note: '',
  },
  {
    id: 14850,
    tvmazeId: '38053',
    title: 'The Family Tree',
    network: 'NBC',
    startYear: 1983,
    years: '1983',
    genres: ['Drama', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/163/407743.jpg',
    note: '',
  },
  {
    id: 14851,
    tvmazeId: '51407',
    title: 'The Forgotten Story',
    network: 'ITV1',
    startYear: 1983,
    years: '1983',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/279/698019.jpg',
    note: '',
  },
  {
    id: 14852,
    tvmazeId: '51410',
    title: 'The Fourth Arm',
    network: 'BBC One',
    startYear: 1983,
    years: '1983',
    genres: ['Drama', 'Action', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/279/698030.jpg',
    note: '',
  },
  {
    id: 14853,
    tvmazeId: '43145',
    title: 'The Happy Apple',
    network: 'ITV1',
    startYear: 1983,
    years: '1983',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14854,
    tvmazeId: '3843',
    title: 'The Hitchhiker',
    network: 'USA Network',
    startYear: 1983,
    years: '1983–1991',
    genres: ['Drama', 'Horror', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/48297.jpg',
    note: '',
  },
  {
    id: 14855,
    tvmazeId: '87438',
    title: 'The Home Front',
    network: 'ITV1',
    startYear: 1983,
    years: '1983',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14856,
    tvmazeId: '36240',
    title: 'The Irish R. M.',
    network: 'Channel 4',
    startYear: 1983,
    years: '1983–1985',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/153/382883.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 619, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
