window.pageShows = [
  {
    id: 2425,
    tvmazeId: '50998',
    title: 'The Tailings checkifcancelled',
    network: 'SBS On Demand',
    startYear: 2021,
    years: '2021–',
    genres: ['Drama'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/412/1031698.jpg',
    note: '',
  },
  {
    id: 2426,
    tvmazeId: '54055',
    title: 'The Tower',
    network: 'ITVX',
    startYear: 2021,
    years: '2021–',
    genres: ['Crime', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/533/1332740.jpg',
    note: '',
  },
  {
    id: 2427,
    tvmazeId: '26481',
    title: 'The Underground Railroad',
    network: 'Prime Video',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/309/774476.jpg',
    note: '',
  },
  {
    id: 2428,
    tvmazeId: '47586',
    title: 'The Unusual Suspects',
    network: 'SBS',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/322/807175.jpg',
    note: '',
  },
  {
    id: 2429,
    tvmazeId: '43458',
    title: 'The Upshaws',
    network: 'Netflix',
    startYear: 2021,
    years: '2021–2026',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/608/1521710.jpg',
    note: '',
  },
  {
    id: 2430,
    tvmazeId: '71299',
    title: 'The Very Small Creatures checkifcancelled',
    network: 'Now',
    startYear: 2021,
    years: '2021–',
    genres: [],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/518/1297046.jpg',
    note: '',
  },
  {
    id: 2431,
    tvmazeId: '39428',
    title: 'The Watch',
    network: 'BBC America',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Comedy', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/294/737490.jpg',
    note: '',
  },
  {
    id: 2432,
    tvmazeId: '35083',
    title: 'The Wheel of Time',
    network: 'Prime Video',
    startYear: 2021,
    years: '2021–2025',
    genres: ['Drama', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/564/1411765.jpg',
    note: '',
  },
  {
    id: 2433,
    tvmazeId: '51394',
    title: 'The White Lotus',
    network: 'HBO',
    startYear: 2021,
    years: '2021–',
    genres: ['Drama', 'Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/557/1393876.jpg',
    note: '',
  },
  {
    id: 2434,
    tvmazeId: '56567',
    title: 'The Window',
    network: 'Streamz',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Thriller', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/343/859363.jpg',
    note: '',
  },
  {
    id: 2435,
    tvmazeId: '57907',
    title: 'The Witcher Anime Specials checkifcancelled',
    network: 'Netflix',
    startYear: 2021,
    years: '2021–',
    genres: ['Action', 'Adventure', 'Anime', 'Fantasy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/557/1394589.jpg',
    note: '',
  },
  {
    id: 2436,
    tvmazeId: '57021',
    title: 'The Wonder Gang checkifcancelled',
    network: 'ABC Kids',
    startYear: 2021,
    years: '2021–',
    genres: [],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 2437,
    tvmazeId: '55351',
    title: 'The Wonder Years',
    network: 'ABC',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/464/1161206.jpg',
    note: '',
  },
  {
    id: 2438,
    tvmazeId: '37988',
    title: 'Them',
    network: 'Prime Video',
    startYear: 2021,
    years: '2021–2024',
    genres: ['Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/510/1277188.jpg',
    note: '',
  },
  {
    id: 2439,
    tvmazeId: '54041',
    title: 'Thomas & Friends: All Engines Go',
    network: 'Netflix',
    startYear: 2021,
    years: '2021–2025',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/372/931938.jpg',
    note: '',
  },
  {
    id: 2440,
    tvmazeId: '55031',
    title: 'Three Families',
    network: 'BBC One',
    startYear: 2021,
    years: '2021',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/315/788893.jpg',
    note: '',
  },
  {
    id: 2441,
    tvmazeId: '50374',
    title: 'Time',
    network: 'BBC iPlayer',
    startYear: 2021,
    years: '2021–',
    genres: ['Drama', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/483/1209865.jpg',
    note: '',
  },
  {
    id: 2442,
    tvmazeId: '55833',
    title: 'Tom and Jerry in New York',
    network: 'HBO Max',
    startYear: 2021,
    years: '2021–',
    genres: ['Comedy', 'Adventure'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: '',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/334/837419.jpg',
    note: '',
  },
  {
    id: 2443,
    tvmazeId: '53694',
    title: 'Tom and Jerry Special Shorts',
    network: 'HBO Max',
    startYear: 2021,
    years: '2021',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/297/743761.jpg',
    note: '',
  },
  {
    id: 2444,
    tvmazeId: '43771',
    title: 'Too Close',
    network: 'ITV1',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/402/1005025.jpg',
    note: '',
  },
  {
    id: 2445,
    tvmazeId: '80304',
    title: 'Toon In with Me',
    network: 'Me-TV',
    startYear: 2021,
    years: '2021–',
    genres: ['Comedy', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/540/1350886.jpg',
    note: '',
  },
  {
    id: 2446,
    tvmazeId: '71026',
    title: 'Trace',
    network: 'OUTtv',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/475/1189421.jpg',
    note: '',
  },
  {
    id: 2447,
    tvmazeId: '54241',
    title: 'Trailer Park Boys: JAIL',
    network: 'SwearNet',
    startYear: 2021,
    years: '2021–2024',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/300/751599.jpg',
    note: '',
  },
  {
    id: 2448,
    tvmazeId: '52319',
    title: 'True Story',
    network: 'Netflix',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/371/928800.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 102, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 824, "cliffhanger": 237, "ended": 13574}};
