window.pageShows = [
  {
    id: 4397,
    tvmazeId: '43538',
    title: 'Blue\'s Clues & You!',
    network: 'Nickelodeon',
    startYear: 2019,
    years: '2019–2024',
    genres: ['Adventure', 'Children'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/402/1007443.jpg',
    note: '',
  },
  {
    id: 4398,
    tvmazeId: '42157',
    title: 'Bluff City Law',
    network: 'NBC',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Legal'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/234/586536.jpg',
    note: '',
  },
  {
    id: 4399,
    tvmazeId: '42167',
    title: 'Bob ♥ Abishola',
    network: 'CBS',
    startYear: 2019,
    years: '2019–2024',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/502/1256967.jpg',
    note: '',
  },
  {
    id: 4400,
    tvmazeId: '42728',
    title: 'Bolívar',
    network: 'Netflix',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Romance', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/202/507241.jpg',
    note: '',
  },
  {
    id: 4401,
    tvmazeId: '34493',
    title: 'Bonding',
    network: 'Netflix',
    startYear: 2019,
    years: '2019–2021',
    genres: ['Drama', 'Comedy', 'Adult'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/161/403020.jpg',
    note: '',
  },
  {
    id: 4402,
    tvmazeId: '40327',
    title: 'Boomerang',
    network: 'BET',
    startYear: 2019,
    years: '2019–2020',
    genres: ['Comedy', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/378/945057.jpg',
    note: '',
  },
  {
    id: 4403,
    tvmazeId: '45377',
    title: 'Boy Girl Dog Cat Mouse Cheese',
    network: 'BBC iPlayer',
    startYear: 2019,
    years: '2019–2024',
    genres: ['Comedy', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/230/576498.jpg',
    note: '',
  },
  {
    id: 4404,
    tvmazeId: '49503',
    title: 'Brain in Gear',
    network: 'BBC Two',
    startYear: 2019,
    years: '2019–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 4405,
    tvmazeId: '38307',
    title: 'Brassic',
    network: 'Now',
    startYear: 2019,
    years: '2019–2025',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/587/1467940.jpg',
    note: '',
  },
  {
    id: 4406,
    tvmazeId: '60870',
    title: 'Breakers',
    network: 'Network 10',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/398/996911.jpg',
    note: '',
  },
  {
    id: 4407,
    tvmazeId: '45281',
    title: 'Brogan: Master of Castles',
    network: 'Sky Sci-Fi',
    startYear: 2019,
    years: '2019',
    genres: ['Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/376/941712.jpg',
    note: '',
  },
  {
    id: 4408,
    tvmazeId: '46667',
    title: 'Bug Diaries',
    network: 'Prime Video',
    startYear: 2019,
    years: '2019–2020',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/245/614001.jpg',
    note: '',
  },
  {
    id: 4409,
    tvmazeId: '43962',
    title: 'Cake',
    network: 'FXX',
    startYear: 2019,
    years: '2019–2021',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/361/903730.jpg',
    note: '',
  },
  {
    id: 4410,
    tvmazeId: '30918',
    title: 'Cannon Busters',
    network: 'Netflix',
    startYear: 2019,
    years: '2019',
    genres: ['Action', 'Adventure', 'Anime', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/122/307387.jpg',
    note: '',
  },
  {
    id: 4411,
    tvmazeId: '27346',
    title: 'Carmen Sandiego',
    network: 'Netflix',
    startYear: 2019,
    years: '2019–2021',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/213/533548.jpg',
    note: '',
  },
  {
    id: 4412,
    tvmazeId: '28120',
    title: 'Carnival Row',
    network: 'Prime Video',
    startYear: 2019,
    years: '2019–2023',
    genres: ['Drama', 'Fantasy', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/445/1114054.jpg',
    note: '',
  },
  {
    id: 4413,
    tvmazeId: '41263',
    title: 'Carol\'s Second Act',
    network: 'CBS',
    startYear: 2019,
    years: '2019–2020',
    genres: ['Comedy', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/209/523144.jpg',
    note: '',
  },
  {
    id: 4414,
    tvmazeId: '34363',
    title: 'Catch-22',
    network: 'Hulu',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Comedy', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/198/496169.jpg',
    note: '',
  },
  {
    id: 4415,
    tvmazeId: '34566',
    title: 'Catherine the Great',
    network: 'Sky Go',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/213/534021.jpg',
    note: '',
  },
  {
    id: 4416,
    tvmazeId: '36857',
    title: 'Cavendish',
    network: 'CBC',
    startYear: 2019,
    years: '2019',
    genres: ['Comedy', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/179/448920.jpg',
    note: '',
  },
  {
    id: 4417,
    tvmazeId: '34346',
    title: 'Chambers',
    network: 'Netflix',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Horror', 'Supernatural'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Netflix cancelled after one season; Sasha\'s possession storyline and the Annex Foundation conspiracy were unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/189/474342.jpg',
    note: '',
  },
  {
    id: 4418,
    tvmazeId: '41571',
    title: 'Channel wa Sonomama! (Stay Tuned!)',
    network: 'Netflix',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/285/712535.jpg',
    note: '',
  },
  {
    id: 4419,
    tvmazeId: '80339',
    title: 'Charlie the Interviewer of Things',
    network: 'Discovery Kids',
    startYear: 2019,
    years: '2019',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/540/1351258.jpg',
    note: '',
  },
  {
    id: 4420,
    tvmazeId: '41622',
    title: 'Charlie\'s Colorforms City',
    network: 'Netflix',
    startYear: 2019,
    years: '2019–2022',
    genres: ['Children'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/190/476181.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 184, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
