window.pageShows = [
  {
    id: 6025,
    tvmazeId: '7829',
    title: 'Emma Approved',
    network: 'YouTube',
    startYear: 2013,
    years: '2013–2014',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/71865.jpg',
    note: '',
  },
  {
    id: 6026,
    tvmazeId: '43108',
    title: 'Emo Dad',
    network: 'YouTube',
    startYear: 2013,
    years: '2013–2016',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/232/582317.jpg',
    note: '',
  },
  {
    id: 6027,
    tvmazeId: '5743',
    title: 'Eve of Destruction',
    network: 'REELZ',
    startYear: 2013,
    years: '2013',
    genres: ['Drama', 'Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/57306.jpg',
    note: '',
  },
  {
    id: 6028,
    tvmazeId: '11693',
    title: 'Ever After High',
    network: 'Netflix',
    startYear: 2013,
    years: '2013–2016',
    genres: ['Comedy', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/248/622394.jpg',
    note: '',
  },
  {
    id: 6029,
    tvmazeId: '12241',
    title: 'Exploding Sun',
    network: 'REELZ',
    startYear: 2013,
    years: '2013',
    genres: ['Action', 'Science-Fiction', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/41/103170.jpg',
    note: '',
  },
  {
    id: 6030,
    tvmazeId: '4542',
    title: 'Family Tools',
    network: 'ABC',
    startYear: 2013,
    years: '2013',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/52109.jpg',
    note: '',
  },
  {
    id: 6031,
    tvmazeId: '1218',
    title: 'Family Tree',
    network: 'HBO',
    startYear: 2013,
    years: '2013',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/17607.jpg',
    note: '',
  },
  {
    id: 6032,
    tvmazeId: '28716',
    title: 'Fast Food Heights',
    network: 'MTV',
    startYear: 2013,
    years: '2013–2014',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/114/286376.jpg',
    note: '',
  },
  {
    id: 6033,
    tvmazeId: '3156',
    title: 'Father Brown',
    network: 'BBC iPlayer',
    startYear: 2013,
    years: '2013–',
    genres: ['Drama', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/17/43213.jpg',
    note: '',
  },
  {
    id: 6034,
    tvmazeId: '3782',
    title: 'Father Figure',
    network: 'BBC One',
    startYear: 2013,
    years: '2013',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/47933.jpg',
    note: '',
  },
  {
    id: 6035,
    tvmazeId: '80911',
    title: 'Fluffle Puff Tales',
    network: 'YouTube',
    startYear: 2013,
    years: '2013–2016',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/544/1360489.jpg',
    note: '',
  },
  {
    id: 6036,
    tvmazeId: '5355',
    title: 'Forgive Me',
    network: 'Super Channel Fuse',
    startYear: 2013,
    years: '2013–2018',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/55401.jpg',
    note: '',
  },
  {
    id: 6037,
    tvmazeId: '4837',
    title: 'Frankie',
    network: 'BBC One',
    startYear: 2013,
    years: '2013',
    genres: ['Drama', 'Family', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/53312.jpg',
    note: '',
  },
  {
    id: 6038,
    tvmazeId: '3354',
    title: 'Full Circle',
    network: 'Audience Network',
    startYear: 2013,
    years: '2013–2016',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/17/44271.jpg',
    note: '',
  },
  {
    id: 6039,
    tvmazeId: '16404',
    title: 'Future Firepower',
    network: 'Discovery',
    startYear: 2013,
    years: '2013',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/354/885752.jpg',
    note: '',
  },
  {
    id: 6040,
    tvmazeId: '64664',
    title: 'Gangsta Granny',
    network: 'CBBC',
    startYear: 2013,
    years: '2013–2022',
    genres: ['Drama', 'Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/426/1066451.jpg',
    note: '',
  },
  {
    id: 6041,
    tvmazeId: '3527',
    title: 'Garage Sale Mystery',
    network: 'Hallmark Mystery',
    startYear: 2013,
    years: '2013–2020',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/171/428059.jpg',
    note: '',
  },
  {
    id: 6042,
    tvmazeId: '75620',
    title: 'Get Squiggling! Letters',
    network: 'CBeebies',
    startYear: 2013,
    years: '2013',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/510/1275857.jpg',
    note: '',
  },
  {
    id: 6043,
    tvmazeId: '141',
    title: 'Getting On',
    network: 'HBO',
    startYear: 2013,
    years: '2013–2015',
    genres: ['Comedy', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/0/1970.jpg',
    note: '',
  },
  {
    id: 6044,
    tvmazeId: '28734',
    title: 'Ghost Ghirls',
    network: 'Yahoo! View',
    startYear: 2013,
    years: '2013',
    genres: ['Comedy', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/114/286475.jpg',
    note: '',
  },
  {
    id: 6045,
    tvmazeId: '1843',
    title: 'Golan the Insatiable',
    network: 'FOX',
    startYear: 2013,
    years: '2013–2015',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/10/26949.jpg',
    note: '',
  },
  {
    id: 6046,
    tvmazeId: '1241',
    title: 'Golden Boy',
    network: 'CBS',
    startYear: 2013,
    years: '2013',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/17824.jpg',
    note: '',
  },
  {
    id: 6047,
    tvmazeId: '205',
    title: 'Graceland',
    network: 'USA Network',
    startYear: 2013,
    years: '2013–2015',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/54/137054.jpg',
    note: '',
  },
  {
    id: 6048,
    tvmazeId: '6930',
    title: 'Granite Flats',
    network: 'BYUtv',
    startYear: 2013,
    years: '2013–2015',
    genres: ['Drama', 'Thriller', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/65181.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 252, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 334, "cliffhanger": 235, "ended": 13701}};
