window.pageShows = [
  {
    id: 7585,
    tvmazeId: '4164',
    title: 'Mind Games',
    network: 'ABC',
    startYear: 2014,
    years: '2014',
    genres: ['Drama', 'Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'ABC cancelled after one season; the behavioural science consulting firm\'s cases were mid-arc.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/50270.jpg',
    note: '',
  },
  {
    id: 7586,
    tvmazeId: '20435',
    title: 'Mixels',
    network: 'Cartoon Network',
    startYear: 2014,
    years: '2014–2016',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/72/180724.jpg',
    note: '',
  },
  {
    id: 7587,
    tvmazeId: '1211',
    title: 'Mixology',
    network: 'ABC',
    startYear: 2014,
    years: '2014',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/17559.jpg',
    note: '',
  },
  {
    id: 7588,
    tvmazeId: '7108',
    title: 'Mohawk Girls',
    network: 'OMNI',
    startYear: 2014,
    years: '2014–2017',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/66494.jpg',
    note: '',
  },
  {
    id: 7589,
    tvmazeId: '29155',
    title: 'Money & Violence',
    network: 'YouTube',
    startYear: 2014,
    years: '2014–2016',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/613/1534009.jpg',
    note: '',
  },
  {
    id: 7590,
    tvmazeId: '18652',
    title: 'MorganVille: The Series',
    network: 'YouTube',
    startYear: 2014,
    years: '2014',
    genres: ['Fantasy', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/288/721449.jpg',
    note: '',
  },
  {
    id: 7591,
    tvmazeId: '1620',
    title: 'Mozart in the Jungle',
    network: 'Prime Video',
    startYear: 2014,
    years: '2014–2018',
    genres: ['Drama', 'Comedy', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/138/345853.jpg',
    note: '',
  },
  {
    id: 7592,
    tvmazeId: '4358',
    title: 'Mr. Pickles',
    network: 'Adult Swim',
    startYear: 2014,
    years: '2014–2019',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/51628.jpg',
    note: '',
  },
  {
    id: 7593,
    tvmazeId: '2328',
    title: 'Mr. Sloane',
    network: 'Sky Atlantic',
    startYear: 2014,
    years: '2014',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/12/32001.jpg',
    note: '',
  },
  {
    id: 7594,
    tvmazeId: '108',
    title: 'Mulaney',
    network: 'FOX',
    startYear: 2014,
    years: '2014–2015',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/0/846.jpg',
    note: '',
  },
  {
    id: 7595,
    tvmazeId: '300',
    title: 'Murder in the First',
    network: 'TNT',
    startYear: 2014,
    years: '2014–2016',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/192/481470.jpg',
    note: '',
  },
  {
    id: 7596,
    tvmazeId: '10549',
    title: 'My Jihad',
    network: 'BBC iPlayer',
    startYear: 2014,
    years: '2014–2015',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/35/89291.jpg',
    note: '',
  },
  {
    id: 7597,
    tvmazeId: '3950',
    title: 'Mystery Girls',
    network: 'Freeform',
    startYear: 2014,
    years: '2014',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/49049.jpg',
    note: '',
  },
  {
    id: 7598,
    tvmazeId: '45',
    title: 'NCIS: New Orleans',
    network: 'CBS',
    startYear: 2014,
    years: '2014–2021',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/280/701985.jpg',
    note: '',
  },
  {
    id: 7599,
    tvmazeId: '13743',
    title: 'Nerds and Monsters',
    network: 'YTV',
    startYear: 2014,
    years: '2014–2016',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/75/188073.jpg',
    note: '',
  },
  {
    id: 7600,
    tvmazeId: '13025',
    title: 'Neste Sommer',
    network: 'HBO Max',
    startYear: 2014,
    years: '2014–2024',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/532/1330806.jpg',
    note: '',
  },
  {
    id: 7601,
    tvmazeId: '79644',
    title: 'New Puss in Boots',
    network: 'YouTube',
    startYear: 2014,
    years: '2014–2016',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/536/1340305.jpg',
    note: '',
  },
  {
    id: 7602,
    tvmazeId: '79645',
    title: 'New Shrek',
    network: 'YouTube',
    startYear: 2014,
    years: '2014–2015',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/536/1340306.jpg',
    note: '',
  },
  {
    id: 7603,
    tvmazeId: '7707',
    title: 'New Worlds',
    network: 'Channel 4',
    startYear: 2014,
    years: '2014',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/70850.jpg',
    note: '',
  },
  {
    id: 7604,
    tvmazeId: '3862',
    title: 'Nicky, Ricky, Dicky & Dawn',
    network: 'Nickelodeon',
    startYear: 2014,
    years: '2014–2018',
    genres: ['Comedy', 'Children', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/483/1207920.jpg',
    note: '',
  },
  {
    id: 7605,
    tvmazeId: '7116',
    title: 'Nightwing: The Series',
    network: 'YouTube',
    startYear: 2014,
    years: '2014',
    genres: ['Action', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/66518.jpg',
    note: '',
  },
  {
    id: 7606,
    tvmazeId: '13713',
    title: 'Nixon\'s the One',
    network: 'Sky Arts',
    startYear: 2014,
    years: '2014',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/48/121676.jpg',
    note: '',
  },
  {
    id: 7607,
    tvmazeId: '6861',
    title: 'Northpole',
    network: 'Hallmark Channel',
    startYear: 2014,
    years: '2014–2015',
    genres: ['Comedy', 'Family', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/25/64704.jpg',
    note: '',
  },
  {
    id: 7608,
    tvmazeId: '37604',
    title: 'Nothing Much to Do',
    network: 'YouTube',
    startYear: 2014,
    years: '2014–2015',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/160/400338.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 317, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
