window.pageShows = [
  {
    id: 1585,
    tvmazeId: '72033',
    title: 'Beijo Adolescente: O Futuro Está Morto',
    network: 'HBO Max',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Fantasy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/482/1205708.jpg',
    note: '',
  },
  {
    id: 1586,
    tvmazeId: '59241',
    title: 'Berlín',
    network: 'Netflix',
    startYear: 2023,
    years: '2023',
    genres: ['Action', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/497/1243972.jpg',
    note: '',
  },
  {
    id: 1587,
    tvmazeId: '43164',
    title: 'Best Interests',
    network: 'BBC One',
    startYear: 2023,
    years: '2023',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/464/1161171.jpg',
    note: '',
  },
  {
    id: 1588,
    tvmazeId: '54402',
    title: 'Better',
    network: 'BBC iPlayer',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/446/1116193.jpg',
    note: '',
  },
  {
    id: 1589,
    tvmazeId: '62816',
    title: 'Beyond Paradise',
    network: 'BBC One',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/619/1549488.jpg',
    note: '',
  },
  {
    id: 1590,
    tvmazeId: '67165',
    title: 'Biz Kimden Kaçıyorduk Anne?',
    network: 'Netflix',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/449/1122544.jpg',
    note: '',
  },
  {
    id: 1591,
    tvmazeId: '60525',
    title: 'Black Cake',
    network: 'Hulu',
    startYear: 2023,
    years: '2023',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/483/1209532.jpg',
    note: '',
  },
  {
    id: 1592,
    tvmazeId: '87426',
    title: 'Black Girl Missing',
    network: 'Lifetime',
    startYear: 2023,
    years: '2023–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/594/1485948.jpg',
    note: '',
  },
  {
    id: 1593,
    tvmazeId: '61006',
    title: 'Black Knight',
    network: 'Netflix',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Fantasy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/457/1144613.jpg',
    note: '',
  },
  {
    id: 1594,
    tvmazeId: '57129',
    title: 'Black Ops',
    network: 'BBC iPlayer',
    startYear: 2023,
    years: '2023–',
    genres: ['Comedy', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/608/1520429.jpg',
    note: '',
  },
  {
    id: 1595,
    tvmazeId: '72359',
    title: 'Black Santiago Club',
    network: 'Canal+',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/484/1210624.jpg',
    note: '',
  },
  {
    id: 1596,
    tvmazeId: '63510',
    title: 'Black Snow',
    network: 'Stan',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/438/1096696.jpg',
    note: '',
  },
  {
    id: 1597,
    tvmazeId: '72231',
    title: 'BlackBerry',
    network: 'CBC Gem',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/484/1212202.jpg',
    note: '',
  },
  {
    id: 1598,
    tvmazeId: '55645',
    title: 'Blacktalon',
    network: 'Warhammer+',
    startYear: 2023,
    years: '2023–',
    genres: ['Action', 'Fantasy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/456/1141523.jpg',
    note: '',
  },
  {
    id: 1599,
    tvmazeId: '69414',
    title: 'Blindspot',
    network: '5',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/467/1168155.jpg',
    note: '',
  },
  {
    id: 1600,
    tvmazeId: '63870',
    title: 'Bloodhounds',
    network: 'Netflix',
    startYear: 2023,
    years: '2023–2026',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/620/1550874.jpg',
    note: '',
  },
  {
    id: 1601,
    tvmazeId: '51112',
    title: 'Blue Eye Samurai',
    network: 'Netflix',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Action'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/488/1220768.jpg',
    note: '',
  },
  {
    id: 1602,
    tvmazeId: '54401',
    title: 'Blue Lights',
    network: 'BBC iPlayer',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/589/1474873.jpg',
    note: '',
  },
  {
    id: 1603,
    tvmazeId: '65702',
    title: 'Boat Story',
    network: 'BBC iPlayer',
    startYear: 2023,
    years: '2023',
    genres: ['Action', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/508/1270802.jpg',
    note: '',
  },
  {
    id: 1604,
    tvmazeId: '60737',
    title: 'Bodies',
    network: 'Netflix',
    startYear: 2023,
    years: '2023',
    genres: ['Crime', 'Science-Fiction', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/482/1205619.jpg',
    note: '',
  },
  {
    id: 1605,
    tvmazeId: '68156',
    title: 'Boiling Point',
    network: 'BBC iPlayer',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/479/1198412.jpg',
    note: '',
  },
  {
    id: 1606,
    tvmazeId: '64692',
    title: 'Bones of Crows',
    network: 'CBC',
    startYear: 2023,
    years: '2023',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/477/1193485.jpg',
    note: '',
  },
  {
    id: 1607,
    tvmazeId: '64493',
    title: 'Bookie',
    network: 'HBO Max',
    startYear: 2023,
    years: '2023–2025',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/543/1359778.jpg',
    note: '',
  },
  {
    id: 1608,
    tvmazeId: '71290',
    title: 'BooSnoo!',
    network: 'Sky Kids',
    startYear: 2023,
    years: '2023–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/477/1193211.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 67, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
