window.pageShows = [
  {
    id: 15841,
    tvmazeId: '24079',
    title: 'The Montefuscos',
    network: 'NBC',
    startYear: 1975,
    years: '1975',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/91/228072.jpg',
    note: '',
  },
  {
    id: 15842,
    tvmazeId: '18963',
    title: 'The New Tom & Jerry Show',
    network: 'ABC',
    startYear: 1975,
    years: '1975',
    genres: ['Comedy', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/136/342238.jpg',
    note: '',
  },
  {
    id: 15843,
    tvmazeId: '39512',
    title: 'The Oddball Couple',
    network: 'ABC',
    startYear: 1975,
    years: '1975',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/173/433942.jpg',
    note: '',
  },
  {
    id: 15844,
    tvmazeId: '25377',
    title: 'The Secret Garden',
    network: 'BBC One',
    startYear: 1975,
    years: '1975',
    genres: ['Drama', 'Children', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/98/246738.jpg',
    note: '',
  },
  {
    id: 15845,
    tvmazeId: '40757',
    title: 'The Secret Lives of Waldo Kitty',
    network: 'NBC',
    startYear: 1975,
    years: '1975',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/182/455694.jpg',
    note: '',
  },
  {
    id: 15846,
    tvmazeId: '14680',
    title: 'The Secrets of ISIS',
    network: 'CBS',
    startYear: 1975,
    years: '1975–1976',
    genres: ['Drama', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/49/124323.jpg',
    note: '',
  },
  {
    id: 15847,
    tvmazeId: '25862',
    title: 'The Siege of Golden Hill',
    network: 'ITV1',
    startYear: 1975,
    years: '1975',
    genres: ['Drama', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/101/252904.jpg',
    note: '',
  },
  {
    id: 15848,
    tvmazeId: '3675',
    title: 'The Sweeney',
    network: 'ITV1',
    startYear: 1975,
    years: '1975–1978',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/47377.jpg',
    note: '',
  },
  {
    id: 15849,
    tvmazeId: '23569',
    title: 'The Wackers',
    network: 'ITV1',
    startYear: 1975,
    years: '1975',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/88/221015.jpg',
    note: '',
  },
  {
    id: 15850,
    tvmazeId: '36890',
    title: 'Three for the Road',
    network: 'CBS',
    startYear: 1975,
    years: '1975',
    genres: ['Drama', 'Adventure', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/156/391700.jpg',
    note: '',
  },
  {
    id: 15851,
    tvmazeId: '39784',
    title: 'Two\'s Company',
    network: 'ITV1',
    startYear: 1975,
    years: '1975–1979',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/175/437953.jpg',
    note: '',
  },
  {
    id: 15852,
    tvmazeId: '39689',
    title: 'Uncle Croc\'s Block',
    network: 'ABC',
    startYear: 1975,
    years: '1975',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 15853,
    tvmazeId: '72726',
    title: 'We\'ll Get By',
    network: 'CBS',
    startYear: 1975,
    years: '1975',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/486/1217465.jpg',
    note: '',
  },
  {
    id: 15854,
    tvmazeId: '3743',
    title: 'Welcome Back, Kotter',
    network: 'ABC',
    startYear: 1975,
    years: '1975–1979',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/47757.jpg',
    note: '',
  },
  {
    id: 15855,
    tvmazeId: '24198',
    title: 'Westwind',
    network: 'NBC',
    startYear: 1975,
    years: '1975',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/91/229994.jpg',
    note: '',
  },
  {
    id: 15856,
    tvmazeId: '59355',
    title: 'When Things Were Rotten',
    network: 'ABC',
    startYear: 1975,
    years: '1975',
    genres: ['Comedy', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/381/953073.jpg',
    note: '',
  },
  {
    id: 15857,
    tvmazeId: '36236',
    title: 'Wodehouse Playhouse',
    network: 'BBC Two',
    startYear: 1975,
    years: '1975–1978',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/153/382863.jpg',
    note: '',
  },
  {
    id: 15858,
    tvmazeId: '1341',
    title: 'Wonder Woman',
    network: 'CBS',
    startYear: 1975,
    years: '1975–1979',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/506/1265303.jpg',
    note: '',
  },
  {
    id: 15859,
    tvmazeId: '40079',
    title: 'Капитан Немо',
    network: 'ЦТ СССР',
    startYear: 1975,
    years: '1975',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/177/443744.jpg',
    note: '',
  },
  {
    id: 15860,
    tvmazeId: '40132',
    title: 'Соломенная шляпка',
    network: 'ЦТ СССР',
    startYear: 1975,
    years: '1975',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/178/445507.jpg',
    note: '',
  },
  {
    id: 15861,
    tvmazeId: '61459',
    title: 'Affairs of the Heart',
    network: 'ITV1',
    startYear: 1974,
    years: '1974–1975',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/564/1411368.jpg',
    note: '',
  },
  {
    id: 15862,
    tvmazeId: '44281',
    title: 'Amy Prentiss',
    network: 'NBC',
    startYear: 1974,
    years: '1974–1975',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/382/955659.jpg',
    note: '',
  },
  {
    id: 15863,
    tvmazeId: '50056',
    title: 'And Mother Makes Five',
    network: 'ITV1',
    startYear: 1974,
    years: '1974–1976',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/270/677477.jpg',
    note: '',
  },
  {
    id: 15864,
    tvmazeId: '27258',
    title: 'Apple\'s Way',
    network: 'CBS',
    startYear: 1974,
    years: '1974–1975',
    genres: ['Drama', 'Adventure', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/107/269288.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 661, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
