window.pageShows = [
  {
    id: 12961,
    tvmazeId: '1653',
    title: 'Highlander: The Animated Series',
    network: 'USA Network',
    startYear: 1994,
    years: '1994–1995',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/389/973855.jpg',
    note: '',
  },
  {
    id: 12962,
    tvmazeId: '44189',
    title: 'Honey for Tea',
    network: 'BBC One',
    startYear: 1994,
    years: '1994',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12963,
    tvmazeId: '65557',
    title: 'Hotel Malibu',
    network: 'CBS',
    startYear: 1994,
    years: '1994',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12964,
    tvmazeId: '44829',
    title: 'Insektors',
    network: 'YTV',
    startYear: 1994,
    years: '1994',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/218/545753.jpg',
    note: '',
  },
  {
    id: 12965,
    tvmazeId: '4243',
    title: 'Iron Man',
    network: 'Syndication',
    startYear: 1994,
    years: '1994–1996',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/50854.jpg',
    note: '',
  },
  {
    id: 12966,
    tvmazeId: '52292',
    title: 'Janus',
    network: 'ABC',
    startYear: 1994,
    years: '1994–1995',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/287/718178.jpg',
    note: '',
  },
  {
    id: 12967,
    tvmazeId: '55985',
    title: 'Jim Henson\'s Animal Show',
    network: 'Animal Planet',
    startYear: 1994,
    years: '1994–1997',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/331/828445.jpg',
    note: '',
  },
  {
    id: 12968,
    tvmazeId: '9684',
    title: 'Jim Lee\'s Wild C.A.T.S: Covert Action Teams',
    network: 'CBS',
    startYear: 1994,
    years: '1994–1995',
    genres: ['Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/84100.jpg',
    note: '',
  },
  {
    id: 12969,
    tvmazeId: '62640',
    title: 'Katie and Orbie',
    network: 'Family Channel',
    startYear: 1994,
    years: '1994–2002',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/413/1033719.jpg',
    note: '',
  },
  {
    id: 12970,
    tvmazeId: '6561',
    title: 'Kommissar Rex',
    network: 'ORF 1',
    startYear: 1994,
    years: '1994–2015',
    genres: ['Action', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/24/62355.jpg',
    note: '',
  },
  {
    id: 12971,
    tvmazeId: '8737',
    title: 'Law and Disorder',
    network: 'ITV1',
    startYear: 1994,
    years: '1994',
    genres: ['Comedy', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/77768.jpg',
    note: '',
  },
  {
    id: 12972,
    tvmazeId: '37116',
    title: 'Law of the Land',
    network: 'Nine Network',
    startYear: 1994,
    years: '1994–1999',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12973,
    tvmazeId: '43001',
    title: 'Liberty Street',
    network: 'CBC',
    startYear: 1994,
    years: '1994',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12974,
    tvmazeId: '7442',
    title: 'Life with Louie',
    network: 'FOX',
    startYear: 1994,
    years: '1994–1998',
    genres: ['Comedy', 'Adventure', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/68558.jpg',
    note: '',
  },
  {
    id: 12975,
    tvmazeId: '51146',
    title: 'Little Napoleons',
    network: 'Channel 4',
    startYear: 1994,
    years: '1994',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12976,
    tvmazeId: '8853',
    title: 'Lonesome Dove: The Series',
    network: 'Syndication',
    startYear: 1994,
    years: '1994–1995',
    genres: ['Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/78695.jpg',
    note: '',
  },
  {
    id: 12977,
    tvmazeId: '51148',
    title: 'Love on a Branch Line',
    network: 'BBC One',
    startYear: 1994,
    years: '1994',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/277/694115.jpg',
    note: '',
  },
  {
    id: 12978,
    tvmazeId: '15088',
    title: 'M.A.N.T.I.S.',
    network: 'FOX',
    startYear: 1994,
    years: '1994–1997',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/51/128364.jpg',
    note: '',
  },
  {
    id: 12979,
    tvmazeId: '22533',
    title: 'Madman of the People',
    network: 'NBC',
    startYear: 1994,
    years: '1994–1995',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/83/207947.jpg',
    note: '',
  },
  {
    id: 12980,
    tvmazeId: '13077',
    title: 'Martin Chuzzlewit',
    network: 'BBC One',
    startYear: 1994,
    years: '1994',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/44/112394.jpg',
    note: '',
  },
  {
    id: 12981,
    tvmazeId: '33245',
    title: 'McKenna',
    network: 'ABC',
    startYear: 1994,
    years: '1994–1995',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/220/551786.jpg',
    note: '',
  },
  {
    id: 12982,
    tvmazeId: '65558',
    title: 'Me and the Boys',
    network: 'ABC',
    startYear: 1994,
    years: '1994–1995',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12983,
    tvmazeId: '19048',
    title: 'Mega Man',
    network: 'Syndication',
    startYear: 1994,
    years: '1994–1995',
    genres: ['Action', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/66/165126.jpg',
    note: '',
  },
  {
    id: 12984,
    tvmazeId: '72886',
    title: 'Mega Man: Upon a Star',
    network: 'Syndication',
    startYear: 1994,
    years: '1994–1995',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/488/1221111.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 541, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
