window.pageShows = [
  {
    id: 12673,
    tvmazeId: '70848',
    title: 'Special Squad',
    network: 'Network 10',
    startYear: 1984,
    years: '1984–1993',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/600/1501569.jpg',
    note: '',
  },
  {
    id: 12674,
    tvmazeId: '23961',
    title: 'Spencer',
    network: 'NBC',
    startYear: 1984,
    years: '1984–1985',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/90/226701.jpg',
    note: '',
  },
  {
    id: 12675,
    tvmazeId: '4792',
    title: 'Spitting Image',
    network: 'ITV1',
    startYear: 1984,
    years: '1984–1996',
    genres: ['Comedy', 'Adult'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/53255.jpg',
    note: '',
  },
  {
    id: 12676,
    tvmazeId: '24337',
    title: 'Strangers and Brothers',
    network: 'BBC Two',
    startYear: 1984,
    years: '1984',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/92/231471.jpg',
    note: '',
  },
  {
    id: 12677,
    tvmazeId: '12553',
    title: 'Super Friends: The Legendary Super Powers Show',
    network: 'ABC',
    startYear: 1984,
    years: '1984',
    genres: ['Family', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/252/631029.jpg',
    note: '',
  },
  {
    id: 12678,
    tvmazeId: '44325',
    title: 'Sweet and Sour',
    network: 'ABC',
    startYear: 1984,
    years: '1984',
    genres: ['Drama', 'Comedy', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/214/536861.jpg',
    note: '',
  },
  {
    id: 12679,
    tvmazeId: '3510',
    title: 'Tales from the Darkside',
    network: 'Syndication',
    startYear: 1984,
    years: '1984–1988',
    genres: ['Fantasy', 'Horror', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/46489.jpg',
    note: '',
  },
  {
    id: 12680,
    tvmazeId: '3255',
    title: 'The Adventures of Sherlock Holmes',
    network: 'ITV1',
    startYear: 1984,
    years: '1984–1994',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/501/1254452.jpg',
    note: '',
  },
  {
    id: 12681,
    tvmazeId: '5983',
    title: 'The Bill',
    network: 'ITV1',
    startYear: 1984,
    years: '1984–2010',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/59211.jpg',
    note: '',
  },
  {
    id: 12682,
    tvmazeId: '24152',
    title: 'The Box of Delights',
    network: 'BBC One',
    startYear: 1984,
    years: '1984',
    genres: ['Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/91/228920.jpg',
    note: '',
  },
  {
    id: 12683,
    tvmazeId: '51307',
    title: 'The Brief',
    network: 'ITV1',
    startYear: 1984,
    years: '1984',
    genres: ['Drama', 'Thriller', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/278/696183.jpg',
    note: '',
  },
  {
    id: 12684,
    tvmazeId: '84368',
    title: 'The ChuckleHounds',
    network: 'BBC One',
    startYear: 1984,
    years: '1984–1986',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/606/1515113.jpg',
    note: '',
  },
  {
    id: 12685,
    tvmazeId: '92008',
    title: 'The Clairvoyant',
    network: 'BBC Two',
    startYear: 1984,
    years: '1984–1986',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/625/1564215.jpg',
    note: '',
  },
  {
    id: 12686,
    tvmazeId: '2084',
    title: 'The Cosby Show',
    network: 'NBC',
    startYear: 1984,
    years: '1984–1992',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/313/782979.jpg',
    note: '',
  },
  {
    id: 12687,
    tvmazeId: '51334',
    title: 'The District Nurse',
    network: 'BBC One',
    startYear: 1984,
    years: '1984–1987',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/278/696630.jpg',
    note: '',
  },
  {
    id: 12688,
    tvmazeId: '25633',
    title: 'The Duck Factory',
    network: 'NBC',
    startYear: 1984,
    years: '1984',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/99/249676.jpg',
    note: '',
  },
  {
    id: 12689,
    tvmazeId: '16533',
    title: 'The Edison Twins',
    network: 'CBC',
    startYear: 1984,
    years: '1984–1986',
    genres: ['Drama', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/55/137752.jpg',
    note: '',
  },
  {
    id: 12690,
    tvmazeId: '30546',
    title: 'The Family-Ness',
    network: 'BBC One',
    startYear: 1984,
    years: '1984–1985',
    genres: ['Children', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/120/302190.jpg',
    note: '',
  },
  {
    id: 12691,
    tvmazeId: '28597',
    title: 'The Far Pavilions',
    network: 'HBO',
    startYear: 1984,
    years: '1984',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/113/284599.jpg',
    note: '',
  },
  {
    id: 12692,
    tvmazeId: '87924',
    title: 'The Front Line',
    network: 'BBC One',
    startYear: 1984,
    years: '1984–1985',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/597/1492844.jpg',
    note: '',
  },
  {
    id: 12693,
    tvmazeId: '39673',
    title: 'The Get Along Gang',
    network: 'CBS',
    startYear: 1984,
    years: '1984',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/174/435442.jpg',
    note: '',
  },
  {
    id: 12694,
    tvmazeId: '18404',
    title: 'The Glory Boys',
    network: 'ITV1',
    startYear: 1984,
    years: '1984',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/62/156450.jpg',
    note: '',
  },
  {
    id: 12695,
    tvmazeId: '21842',
    title: 'The Invisible Man',
    network: 'BBC One',
    startYear: 1984,
    years: '1984',
    genres: ['Drama', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/78/196767.jpg',
    note: '',
  },
  {
    id: 12696,
    tvmazeId: '3551',
    title: 'The Jewel in the Crown',
    network: 'ITV1',
    startYear: 1984,
    years: '1984',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/46681.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 529, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 334, "cliffhanger": 235, "ended": 13701}};
