window.pageShows = [
  {
    id: 9889,
    tvmazeId: '13186',
    title: 'Five Days',
    network: 'BBC One',
    startYear: 2007,
    years: '2007–2010',
    genres: ['Crime', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/45/113555.jpg',
    note: '',
  },
  {
    id: 9890,
    tvmazeId: '999',
    title: 'Flash Gordon',
    network: 'Syfy',
    startYear: 2007,
    years: '2007–2008',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16548.jpg',
    note: '',
  },
  {
    id: 9891,
    tvmazeId: '994',
    title: 'Flight of the Conchords',
    network: 'HBO',
    startYear: 2007,
    years: '2007–2009',
    genres: ['Comedy', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/41/103111.jpg',
    note: '',
  },
  {
    id: 9892,
    tvmazeId: '4090',
    title: 'Fonejacker',
    network: 'E4',
    startYear: 2007,
    years: '2007–2008',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/40/101753.jpg',
    note: '',
  },
  {
    id: 9893,
    tvmazeId: '1271',
    title: 'Forbrydelsen',
    network: 'DR1',
    startYear: 2007,
    years: '2007–2012',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/18353.jpg',
    note: '',
  },
  {
    id: 9894,
    tvmazeId: '42262',
    title: 'Friday: The Animated Series',
    network: 'MTV2',
    startYear: 2007,
    years: '2007',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/198/495713.jpg',
    note: '',
  },
  {
    id: 9895,
    tvmazeId: '73283',
    title: 'Funky Town',
    network: '5',
    startYear: 2007,
    years: '2007',
    genres: ['Comedy', 'Action', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/494/1235009.jpg',
    note: '',
  },
  {
    id: 9896,
    tvmazeId: '71647',
    title: 'Futz!',
    network: 'Télé Toon',
    startYear: 2007,
    years: '2007–2008',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 9897,
    tvmazeId: '2775',
    title: 'Galileo',
    network: 'Fuji TV',
    startYear: 2007,
    years: '2007–2022',
    genres: ['Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/581/1453671.jpg',
    note: '',
  },
  {
    id: 9898,
    tvmazeId: '2331',
    title: 'Gavin & Stacey',
    network: 'BBC One',
    startYear: 2007,
    years: '2007–2024',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/12/32015.jpg',
    note: '',
  },
  {
    id: 9899,
    tvmazeId: '26874',
    title: 'General Hospital: Night Shift',
    network: 'Soapnet',
    startYear: 2007,
    years: '2007–2008',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/105/264683.jpg',
    note: '',
  },
  {
    id: 9900,
    tvmazeId: '56274',
    title: 'George of the Jungle',
    network: 'Cartoon Network',
    startYear: 2007,
    years: '2007–2015',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/337/842886.jpg',
    note: '',
  },
  {
    id: 9901,
    tvmazeId: '90403',
    title: 'Girltrash!',
    network: 'OurChart.com',
    startYear: 2007,
    years: '2007',
    genres: ['Comedy', 'Crime', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/614/1535631.jpg',
    note: '',
  },
  {
    id: 9902,
    tvmazeId: '56314',
    title: 'Gofrette',
    network: 'CBC',
    startYear: 2007,
    years: '2007–2008',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/338/847087.jpg',
    note: '',
  },
  {
    id: 9903,
    tvmazeId: '567',
    title: 'Gossip Girl',
    network: 'The CW',
    startYear: 2007,
    years: '2007–2012',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/499/1247570.jpg',
    note: '',
  },
  {
    id: 9904,
    tvmazeId: '7144',
    title: 'Grand Star',
    network: 'CTV Sci-Fi Channel',
    startYear: 2007,
    years: '2007–2008',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/66901.jpg',
    note: '',
  },
  {
    id: 9905,
    tvmazeId: '788',
    title: 'GREEK',
    network: 'Freeform',
    startYear: 2007,
    years: '2007–2011',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/15483.jpg',
    note: '',
  },
  {
    id: 9906,
    tvmazeId: '22099',
    title: 'Halfway Home',
    network: 'Comedy Central',
    startYear: 2007,
    years: '2007',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/80/201379.jpg',
    note: '',
  },
  {
    id: 9907,
    tvmazeId: '17757',
    title: 'Happy Monster Band',
    network: 'Disney XD',
    startYear: 2007,
    years: '2007–2008',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/59/149566.jpg',
    note: '',
  },
  {
    id: 9908,
    tvmazeId: '8353',
    title: 'Head Case',
    network: 'STARZ',
    startYear: 2007,
    years: '2007–2009',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/74984.jpg',
    note: '',
  },
  {
    id: 9909,
    tvmazeId: '2201',
    title: 'Heartland',
    network: 'TNT',
    startYear: 2007,
    years: '2007',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/12/30419.jpg',
    note: '',
  },
  {
    id: 9910,
    tvmazeId: '3164',
    title: 'Heartland',
    network: 'CBC Gem',
    startYear: 2007,
    years: '2007–',
    genres: ['Drama', 'Family'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/593/1483994.jpg',
    note: '',
  },
  {
    id: 9911,
    tvmazeId: '3833',
    title: 'Hidden Palms',
    network: 'The CW',
    startYear: 2007,
    years: '2007',
    genres: ['Drama', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/48222.jpg',
    note: '',
  },
  {
    id: 9912,
    tvmazeId: '16871',
    title: 'Holby/Blue',
    network: 'BBC One',
    startYear: 2007,
    years: '2007–2008',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/56/141465.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 413, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
