window.pageShows = [
  {
    id: 2233,
    tvmazeId: '61368',
    title: '42 días en la oscuridad',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Crime', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/408/1021593.jpg',
    note: '',
  },
  {
    id: 2234,
    tvmazeId: '63782',
    title: '50/50 Heroes',
    network: 'France 4',
    startYear: 2022,
    years: '2022',
    genres: ['Children', 'Science-Fiction'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/420/1050322.jpg',
    note: '',
  },
  {
    id: 2235,
    tvmazeId: '40916',
    title: '61st Street',
    network: 'Stan',
    startYear: 2022,
    years: '2022–2023',
    genres: ['Drama', 'Crime', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/402/1005349.jpg',
    note: '',
  },
  {
    id: 2236,
    tvmazeId: '63966',
    title: 'A Beginner\'s Guide to Grief',
    network: 'SBS On Demand',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/443/1108312.jpg',
    note: '',
  },
  {
    id: 2237,
    tvmazeId: '60974',
    title: 'A Besúgó',
    network: 'HBO Max',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Espionage'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/399/998368.jpg',
    note: '',
  },
  {
    id: 2238,
    tvmazeId: '60551',
    title: 'A Friend of the Family',
    network: 'Peacock',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/424/1061087.jpg',
    note: '',
  },
  {
    id: 2239,
    tvmazeId: '65160',
    title: 'A Grito Herido',
    network: 'Prime Video',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Comedy', 'Music'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/430/1076100.jpg',
    note: '',
  },
  {
    id: 2240,
    tvmazeId: '46094',
    title: 'A League of Their Own',
    network: 'Prime Video',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Comedy', 'Sports'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/429/1073470.jpg',
    note: '',
  },
  {
    id: 2241,
    tvmazeId: '63084',
    title: 'A Model Family',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/562/1406777.jpg',
    note: '',
  },
  {
    id: 2242,
    tvmazeId: '61172',
    title: 'A Sogra Que Te Pariu',
    network: 'Netflix',
    startYear: 2022,
    years: '2022–2023',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/456/1141368.jpg',
    note: '',
  },
  {
    id: 2243,
    tvmazeId: '49118',
    title: 'A Spy Among Friends',
    network: 'ITVX',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Thriller', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/469/1172929.jpg',
    note: '',
  },
  {
    id: 2244,
    tvmazeId: '63987',
    title: 'Abominable and the Invisible City',
    network: 'Peacock',
    startYear: 2022,
    years: '2022–2023',
    genres: ['Comedy', 'Adventure', 'Fantasy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/454/1135675.jpg',
    note: '',
  },
  {
    id: 2245,
    tvmazeId: '63203',
    title: 'About Youth',
    network: 'Bilibili',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/416/1041604.jpg',
    note: '',
  },
  {
    id: 2246,
    tvmazeId: '87132',
    title: 'Above Average Presents',
    network: 'Peacock',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/587/1469431.jpg',
    note: '',
  },
  {
    id: 2247,
    tvmazeId: '71703',
    title: 'Acting Good',
    network: 'CTV Comedy Channel',
    startYear: 2022,
    years: '2022–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/486/1215165.jpg',
    note: '',
  },
  {
    id: 2248,
    tvmazeId: '59807',
    title: 'Action Pack',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/388/970173.jpg',
    note: '',
  },
  {
    id: 2249,
    tvmazeId: '60127',
    title: 'After the Verdict',
    network: 'Nine Network',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Crime', 'Legal'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/421/1052625.jpg',
    note: '',
  },
  {
    id: 2250,
    tvmazeId: '62057',
    title: 'Alaska Daily',
    network: 'ABC',
    startYear: 2022,
    years: '2022–2023',
    genres: ['Drama'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/424/1061090.jpg',
    note: '',
  },
  {
    id: 2251,
    tvmazeId: '62248',
    title: 'Alchemy of Souls',
    network: 'tvN',
    startYear: 2022,
    years: '2022–2023',
    genres: ['Action', 'Fantasy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/609/1523773.jpg',
    note: '',
  },
  {
    id: 2252,
    tvmazeId: '57068',
    title: 'Alice\'s Wonderland Bakery',
    network: 'DisneyNOW',
    startYear: 2022,
    years: '2022–2024',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/469/1174135.jpg',
    note: '',
  },
  {
    id: 2253,
    tvmazeId: '53247',
    title: 'All American: Homecoming',
    network: 'The CW',
    startYear: 2022,
    years: '2022–2024',
    genres: ['Drama', 'Sports'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/425/1064743.jpg',
    note: '',
  },
  {
    id: 2254,
    tvmazeId: '47199',
    title: 'All of Us Are Dead',
    network: 'Netflix',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Horror'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/394/985544.jpg',
    note: '',
  },
  {
    id: 2255,
    tvmazeId: '39648',
    title: 'Alma',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Thriller', 'Supernatural'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/421/1054409.jpg',
    note: '',
  },
  {
    id: 2256,
    tvmazeId: '87267',
    title: 'Alphablocks and Numberblocks',
    network: 'CBeebies',
    startYear: 2022,
    years: '2022',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/588/1471802.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 94, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
