window.pageShows = [
  {
    id: 3265,
    tvmazeId: '33318',
    title: 'Pure',
    network: 'Channel 4',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/181/453953.jpg',
    note: '',
  },
  {
    id: 3266,
    tvmazeId: '38070',
    title: 'Queens of Mystery',
    network: 'Acorn TV',
    startYear: 2019,
    years: '2019–2021',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/365/914118.jpg',
    note: '',
  },
  {
    id: 3267,
    tvmazeId: '60629',
    title: 'Queer·ious',
    network: 'YouTube',
    startYear: 2019,
    years: '2019–',
    genres: ['Drama', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/397/992667.jpg',
    note: '',
  },
  {
    id: 3268,
    tvmazeId: '40732',
    title: 'Rainbow Butterfly Unicorn Kitty',
    network: 'Nickelodeon',
    startYear: 2019,
    years: '2019',
    genres: ['Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/182/455351.jpg',
    note: '',
  },
  {
    id: 3269,
    tvmazeId: '32518',
    title: 'Raising Dion',
    network: 'Netflix',
    startYear: 2019,
    years: '2019–2022',
    genres: ['Drama', 'Family', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Netflix cancelled after two seasons on a cliffhanger; Dion\'s powers and the Crooked Energy threat were unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/390/977143.jpg',
    note: '',
  },
  {
    id: 3270,
    tvmazeId: '36563',
    title: 'Ramy',
    network: 'Hulu',
    startYear: 2019,
    years: '2019–2022',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/445/1113772.jpg',
    note: '',
  },
  {
    id: 3271,
    tvmazeId: '85722',
    title: 'Random Rings',
    network: 'Disney+',
    startYear: 2019,
    years: '2019–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/576/1442209.jpg',
    note: '',
  },
  {
    id: 3272,
    tvmazeId: '63334',
    title: 'Rational Creatures',
    network: 'YouTube',
    startYear: 2019,
    years: '2019–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 3273,
    tvmazeId: '45433',
    title: 'Reckoning',
    network: 'TVNZ+',
    startYear: 2019,
    years: '2019',
    genres: ['Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/231/577868.jpg',
    note: '',
  },
  {
    id: 3274,
    tvmazeId: '41920',
    title: 'Red Ruby',
    network: 'YouTube',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Mystery', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/222/555939.jpg',
    note: '',
  },
  {
    id: 3275,
    tvmazeId: '63002',
    title: 'Redbad - The Legend',
    network: 'NPO 1',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Action', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/415/1038905.jpg',
    note: '',
  },
  {
    id: 3276,
    tvmazeId: '38378',
    title: 'Reef Break',
    network: 'ABC',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/202/505267.jpg',
    note: '',
  },
  {
    id: 3277,
    tvmazeId: '36855',
    title: 'Reprisal',
    network: 'Hulu',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/218/547113.jpg',
    note: '',
  },
  {
    id: 3278,
    tvmazeId: '40356',
    title: 'Resistance',
    network: 'RTÉ ONE',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/182/456797.jpg',
    note: '',
  },
  {
    id: 3279,
    tvmazeId: '73289',
    title: 'Rev & Roll',
    network: 'YouTube',
    startYear: 2019,
    years: '2019',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/491/1228505.jpg',
    note: '',
  },
  {
    id: 3280,
    tvmazeId: '43906',
    title: 'Ricky Zoom',
    network: 'Nick Jr.',
    startYear: 2019,
    years: '2019–2022',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/274/686480.jpg',
    note: '',
  },
  {
    id: 3281,
    tvmazeId: '32669',
    title: 'Roswell, New Mexico',
    network: 'The CW',
    startYear: 2019,
    years: '2019–2022',
    genres: ['Drama', 'Romance', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/413/1034850.jpg',
    note: '',
  },
  {
    id: 3282,
    tvmazeId: '43270',
    title: 'Ruby Herring Mysteries',
    network: 'Hallmark Mystery',
    startYear: 2019,
    years: '2019–2020',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/213/533293.jpg',
    note: '',
  },
  {
    id: 3283,
    tvmazeId: '39987',
    title: 'Russian Doll',
    network: 'Netflix',
    startYear: 2019,
    years: '2019–2022',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/403/1009012.jpg',
    note: '',
  },
  {
    id: 3284,
    tvmazeId: '37585',
    title: 'Sadie Sparks',
    network: 'Disney Channel',
    startYear: 2019,
    years: '2019',
    genres: ['Comedy', 'Children', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/376/940197.jpg',
    note: '',
  },
  {
    id: 3285,
    tvmazeId: '52722',
    title: 'Sakho & Mangane',
    network: 'Canal+',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/291/728382.jpg',
    note: '',
  },
  {
    id: 3286,
    tvmazeId: '41029',
    title: 'Sanditon',
    network: 'PBS Passport',
    startYear: 2019,
    years: '2019–2023',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/452/1131331.jpg',
    note: '',
  },
  {
    id: 3287,
    tvmazeId: '44853',
    title: 'Sarah\'s Channel',
    network: 'ABC Family',
    startYear: 2019,
    years: '2019–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/218/546475.jpg',
    note: '',
  },
  {
    id: 3288,
    tvmazeId: '41794',
    title: 'Scarborough',
    network: 'BBC One',
    startYear: 2019,
    years: '2019',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/211/527719.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 137, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 856, "cliffhanger": 286, "ended": 13542}};
