window.pageShows = [
  {
    id: 15269,
    tvmazeId: '9008',
    title: 'The Boy Merlin',
    network: 'ITV1',
    startYear: 1979,
    years: '1979',
    genres: ['Drama', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/79895.jpg',
    note: '',
  },
  {
    id: 15270,
    tvmazeId: '18581',
    title: 'The Chisholms',
    network: 'CBS',
    startYear: 1979,
    years: '1979–1980',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/63/158237.jpg',
    note: '',
  },
  {
    id: 15271,
    tvmazeId: '50908',
    title: 'The Danedyke Mystery',
    network: 'ITV1',
    startYear: 1979,
    years: '1979',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/276/690634.jpg',
    note: '',
  },
  {
    id: 15272,
    tvmazeId: '75537',
    title: 'The Dawson Watch',
    network: 'BBC One',
    startYear: 1979,
    years: '1979–1980',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/509/1274630.jpg',
    note: '',
  },
  {
    id: 15273,
    tvmazeId: '36057',
    title: 'The Dick Francis Thriller: The Racing Game',
    network: 'ITV1',
    startYear: 1979,
    years: '1979',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/152/381655.jpg',
    note: '',
  },
  {
    id: 15274,
    tvmazeId: '20769',
    title: 'The Duke',
    network: 'NBC',
    startYear: 1979,
    years: '1979',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/183704.jpg',
    note: '',
  },
  {
    id: 15275,
    tvmazeId: '4284',
    title: 'The Dukes of Hazzard',
    network: 'CBS',
    startYear: 1979,
    years: '1979–1985',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/51133.jpg',
    note: '',
  },
  {
    id: 15276,
    tvmazeId: '37202',
    title: 'The Enchanted Castle',
    network: 'BBC One',
    startYear: 1979,
    years: '1979',
    genres: ['Adventure', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/158/397290.jpg',
    note: '',
  },
  {
    id: 15277,
    tvmazeId: '4607',
    title: 'The Facts of Life',
    network: 'NBC',
    startYear: 1979,
    years: '1979–1988',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/52417.jpg',
    note: '',
  },
  {
    id: 15278,
    tvmazeId: '23456',
    title: 'The Flying Kiwi',
    network: 'TVNZ 1',
    startYear: 1979,
    years: '1979',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/480/1201119.jpg',
    note: '',
  },
  {
    id: 15279,
    tvmazeId: '53258',
    title: 'The Glums',
    network: 'ITV1',
    startYear: 1979,
    years: '1979',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/295/738425.jpg',
    note: '',
  },
  {
    id: 15280,
    tvmazeId: '10457',
    title: 'The Great Detective',
    network: 'CBC',
    startYear: 1979,
    years: '1979–1982',
    genres: ['Drama', 'Mystery', 'History'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/103/257878.jpg',
    note: '',
  },
  {
    id: 15281,
    tvmazeId: '3618',
    title: 'The Kids of Degrassi Street',
    network: 'CBC',
    startYear: 1979,
    years: '1979–1986',
    genres: ['Drama', 'Children', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/59/149799.jpg',
    note: '',
  },
  {
    id: 15282,
    tvmazeId: '69832',
    title: 'The Last Resort',
    network: 'CBS',
    startYear: 1979,
    years: '1979–1980',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/468/1170723.jpg',
    note: '',
  },
  {
    id: 15283,
    tvmazeId: '36585',
    title: 'The Lazarus Syndrome',
    network: 'ABC',
    startYear: 1979,
    years: '1979',
    genres: ['Drama'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/235/589253.jpg',
    note: '',
  },
  {
    id: 15284,
    tvmazeId: '25440',
    title: 'The Legend of King Arthur',
    network: 'BBC One',
    startYear: 1979,
    years: '1979',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/99/247604.jpg',
    note: '',
  },
  {
    id: 15285,
    tvmazeId: '5482',
    title: 'The Littlest Hobo',
    network: 'CTV',
    startYear: 1979,
    years: '1979–1985',
    genres: ['Drama', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/55903.jpg',
    note: '',
  },
  {
    id: 15286,
    tvmazeId: '75281',
    title: 'The MacKenzies of Paradise Cove',
    network: 'ABC',
    startYear: 1979,
    years: '1979',
    genres: ['Drama', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 15287,
    tvmazeId: '26040',
    title: 'The Mallens',
    network: 'ITV1',
    startYear: 1979,
    years: '1979–1980',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/102/255615.jpg',
    note: '',
  },
  {
    id: 15288,
    tvmazeId: '3914',
    title: 'The Misadventures of Sheriff Lobo',
    network: 'NBC',
    startYear: 1979,
    years: '1979–1981',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/48791.jpg',
    note: '',
  },
  {
    id: 15289,
    tvmazeId: '63287',
    title: 'The New Adventures of Mighty Mouse and Heckle and Jeckle',
    network: 'CBS',
    startYear: 1979,
    years: '1979–1980',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/417/1043144.jpg',
    note: '',
  },
  {
    id: 15290,
    tvmazeId: '15732',
    title: 'The New Animated Adventures of Flash Gordon',
    network: 'NBC',
    startYear: 1979,
    years: '1979–1982',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/53/132700.jpg',
    note: '',
  },
  {
    id: 15291,
    tvmazeId: '18937',
    title: 'The New Fred and Barney Show',
    network: 'NBC',
    startYear: 1979,
    years: '1979',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/65/163482.jpg',
    note: '',
  },
  {
    id: 15292,
    tvmazeId: '22039',
    title: 'The New Shmoo',
    network: 'NBC',
    startYear: 1979,
    years: '1979–1980',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/80/200322.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 637, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
