window.pageShows = [
  {
    id: 2305,
    tvmazeId: '53147',
    title: 'Black Bird',
    network: 'Apple TV',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/501/1254750.jpg',
    note: '',
  },
  {
    id: 2306,
    tvmazeId: '62835',
    title: 'Blind',
    network: 'tvN',
    startYear: 2022,
    years: '2022',
    genres: ['Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/419/1047981.jpg',
    note: '',
  },
  {
    id: 2307,
    tvmazeId: '61860',
    title: 'Blocco 181',
    network: 'Sky Atlantic',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/410/1027137.jpg',
    note: '',
  },
  {
    id: 2308,
    tvmazeId: '58935',
    title: 'Blockbuster',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/425/1063064.jpg',
    note: '',
  },
  {
    id: 2309,
    tvmazeId: '61822',
    title: 'Blood Sisters',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/408/1020879.jpg',
    note: '',
  },
  {
    id: 2310,
    tvmazeId: '53342',
    title: 'Boo, Bitch',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy', 'Adventure', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/412/1032240.jpg',
    note: '',
  },
  {
    id: 2311,
    tvmazeId: '60501',
    title: 'Borgen - Riget, Magten og Æren',
    network: 'DR TV',
    startYear: 2022,
    years: '2022',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/396/990410.jpg',
    note: '',
  },
  {
    id: 2312,
    tvmazeId: '60175',
    title: 'Bosch: Legacy',
    network: 'Prime Video',
    startYear: 2022,
    years: '2022–2025',
    genres: ['Drama', 'Crime', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/564/1411768.jpg',
    note: '',
  },
  {
    id: 2313,
    tvmazeId: '64994',
    title: 'Bosé',
    network: 'Paramount+',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Music', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/429/1073196.jpg',
    note: '',
  },
  {
    id: 2314,
    tvmazeId: '78626',
    title: 'Bridesman',
    network: 'Grindr',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/528/1322166.jpg',
    note: '',
  },
  {
    id: 2315,
    tvmazeId: '65730',
    title: 'Brokat',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/434/1087467.jpg',
    note: '',
  },
  {
    id: 2316,
    tvmazeId: '65696',
    title: 'Brown and Friends',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/438/1096615.jpg',
    note: '',
  },
  {
    id: 2317,
    tvmazeId: '62776',
    title: 'Bugs Bunny Builders',
    network: 'HBO Max',
    startYear: 2022,
    years: '2022–',
    genres: ['Comedy', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/414/1035684.jpg',
    note: '',
  },
  {
    id: 2318,
    tvmazeId: '60447',
    title: 'Bust Down',
    network: 'Peacock',
    startYear: 2022,
    years: '2022–2022',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/395/989408.jpg',
    note: '',
  },
  {
    id: 2319,
    tvmazeId: '52202',
    title: 'Candy',
    network: 'Hulu',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/404/1010796.jpg',
    note: '',
  },
  {
    id: 2320,
    tvmazeId: '60942',
    title: 'Carl Weber\'s The Black Hamptons',
    network: 'BET+',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Family'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/502/1256071.jpg',
    note: '',
  },
  {
    id: 2321,
    tvmazeId: '52361',
    title: 'Cars on the Road',
    network: 'Disney+',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy', 'Adventure', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/438/1095301.jpg',
    note: '',
  },
  {
    id: 2322,
    tvmazeId: '64110',
    title: 'Casino',
    network: 'Disney+',
    startYear: 2022,
    years: '2022–2023',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/431/1078948.jpg',
    note: '',
  },
  {
    id: 2323,
    tvmazeId: '65657',
    title: 'CAT',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/433/1084925.jpg',
    note: '',
  },
  {
    id: 2324,
    tvmazeId: '85247',
    title: 'CBeebies House: Time to Play',
    network: 'BBC iPlayer',
    startYear: 2022,
    years: '2022–',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 2325,
    tvmazeId: '60210',
    title: 'Cheaters',
    network: 'BBC iPlayer',
    startYear: 2022,
    years: '2022–2024',
    genres: ['Drama', 'Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/395/988194.jpg',
    note: '',
  },
  {
    id: 2326,
    tvmazeId: '59960',
    title: 'Cherry Blossoms After Winter',
    network: 'Heavenly',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/389/973374.jpg',
    note: '',
  },
  {
    id: 2327,
    tvmazeId: '63389',
    title: 'Chibiverse',
    network: 'Disney Channel',
    startYear: 2022,
    years: '2022–',
    genres: ['Adventure', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/418/1045062.jpg',
    note: '',
  },
  {
    id: 2328,
    tvmazeId: '63019',
    title: 'Chicken Girls: College Years',
    network: 'YouTube',
    startYear: 2022,
    years: '2022–2023',
    genres: ['Drama', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/417/1043236.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 97, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
