window.pageShows = [
  {
    id: 11425,
    tvmazeId: '18550',
    title: 'Sagwa, the Chinese Siamese Cat',
    network: 'PBS Kids',
    startYear: 2001,
    years: '2001–2002',
    genres: ['Children', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/63/158027.jpg',
    note: '',
  },
  {
    id: 11426,
    tvmazeId: '55746',
    title: 'Sam\'s Game',
    network: 'ITV1',
    startYear: 2001,
    years: '2001',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/325/813920.jpg',
    note: '',
  },
  {
    id: 11427,
    tvmazeId: '1603',
    title: 'Samurai Jack',
    network: 'Adult Swim',
    startYear: 2001,
    years: '2001–2017',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: 'After a long hiatus, Adult Swim revived it for a fifth season that concluded Jack\'s battle with Aku.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/82695.jpg',
    note: '',
  },
  {
    id: 11428,
    tvmazeId: '72317',
    title: 'Sanrio Anime Sekai Meisaku Gekijō',
    network: 'YouTube',
    startYear: 2001,
    years: '2001',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11429,
    tvmazeId: '66279',
    title: 'Screech Owls',
    network: 'YTV',
    startYear: 2001,
    years: '2001–2002',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11430,
    tvmazeId: '532',
    title: 'Scrubs',
    network: 'ABC',
    startYear: 2001,
    years: '2001–2010',
    genres: ['Drama', 'Comedy', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/4/11371.jpg',
    note: '',
  },
  {
    id: 11431,
    tvmazeId: '22289',
    title: 'Sexy Urban Legends',
    network: 'Playboy TV',
    startYear: 2001,
    years: '2001–2013',
    genres: ['Comedy', 'Romance', 'Adult'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/81/203834.jpg',
    note: '',
  },
  {
    id: 11432,
    tvmazeId: '11588',
    title: 'Sit Down, Shut Up',
    network: 'Network 10',
    startYear: 2001,
    years: '2001',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/273/684245.jpg',
    note: '',
  },
  {
    id: 11433,
    tvmazeId: '39672',
    title: 'Sitting Ducks',
    network: 'Cartoon Network',
    startYear: 2001,
    years: '2001–2003',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/174/435441.jpg',
    note: '',
  },
  {
    id: 11434,
    tvmazeId: '367',
    title: 'Six Feet Under',
    network: 'HBO',
    startYear: 2001,
    years: '2001–2005',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/2/5480.jpg',
    note: '',
  },
  {
    id: 11435,
    tvmazeId: '66271',
    title: 'Sk8',
    network: 'NBC',
    startYear: 2001,
    years: '2001–2002',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11436,
    tvmazeId: '435',
    title: 'Smallville',
    network: 'The CW',
    startYear: 2001,
    years: '2001–2011',
    genres: ['Drama', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/79/199609.jpg',
    note: '',
  },
  {
    id: 11437,
    tvmazeId: '12803',
    title: 'So Little Time',
    network: 'Freeform',
    startYear: 2001,
    years: '2001–2002',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/43/109652.jpg',
    note: '',
  },
  {
    id: 11438,
    tvmazeId: '16266',
    title: 'Some of My Best Friends',
    network: 'CBS',
    startYear: 2001,
    years: '2001',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/54/135685.jpg',
    note: '',
  },
  {
    id: 11439,
    tvmazeId: '1921',
    title: 'Special Unit 2',
    network: 'UPN',
    startYear: 2001,
    years: '2001–2002',
    genres: ['Comedy', 'Action', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/27783.jpg',
    note: '',
  },
  {
    id: 11440,
    tvmazeId: '18815',
    title: 'Spyder Games',
    network: 'MTV',
    startYear: 2001,
    years: '2001',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/65/162569.jpg',
    note: '',
  },
  {
    id: 11441,
    tvmazeId: '52754',
    title: 'Stanley',
    network: 'Disney Junior',
    startYear: 2001,
    years: '2001–2004',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/291/729319.jpg',
    note: '',
  },
  {
    id: 11442,
    tvmazeId: '714',
    title: 'Star Trek: Enterprise',
    network: 'UPN',
    startYear: 2001,
    years: '2001–2005',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/458/1145937.jpg',
    note: '',
  },
  {
    id: 11443,
    tvmazeId: '40798',
    title: 'State of Grace',
    network: 'Freeform',
    startYear: 2001,
    years: '2001–2002',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/182/455992.jpg',
    note: '',
  },
  {
    id: 11444,
    tvmazeId: '23511',
    title: 'Strange Frequency',
    network: 'VH1',
    startYear: 2001,
    years: '2001',
    genres: ['Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/88/220567.jpg',
    note: '',
  },
  {
    id: 11445,
    tvmazeId: '72778',
    title: 'strongbad_email.exe',
    network: 'Homestarrunner',
    startYear: 2001,
    years: '2001–2006',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/487/1219349.jpg',
    note: '',
  },
  {
    id: 11446,
    tvmazeId: '66433',
    title: 'Super Duper Sumos',
    network: 'Tooniverse',
    startYear: 2001,
    years: '2001–2002',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/442/1105274.jpg',
    note: '',
  },
  {
    id: 11447,
    tvmazeId: '42061',
    title: 'Supergirly',
    network: 'BBC Choice',
    startYear: 2001,
    years: '2001',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11448,
    tvmazeId: '4180',
    title: 'Sword of Honour',
    network: 'Channel 4',
    startYear: 2001,
    years: '2001',
    genres: ['Drama', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/50401.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 477, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
