window.pageShows = [
  {
    id: 6145,
    tvmazeId: '170',
    title: 'Orange Is the New Black',
    network: 'Netflix',
    startYear: 2013,
    years: '2013–2019',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/203/508250.jpg',
    note: '',
  },
  {
    id: 6146,
    tvmazeId: '61',
    title: 'Orphan Black',
    network: 'CTV Sci-Fi Channel',
    startYear: 2013,
    years: '2013–2017',
    genres: ['Drama', 'Science-Fiction', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/484/1210257.jpg',
    note: '',
  },
  {
    id: 6147,
    tvmazeId: '7013',
    title: 'Out There',
    network: 'IFC',
    startYear: 2013,
    years: '2013',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/65734.jpg',
    note: '',
  },
  {
    id: 6148,
    tvmazeId: '15770',
    title: 'Pac-Man and the Ghostly Adventures',
    network: 'Disney XD',
    startYear: 2013,
    years: '2013–2015',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/53/132939.jpg',
    note: '',
  },
  {
    id: 6149,
    tvmazeId: '268',
    title: 'Package Deal',
    network: 'Citytv',
    startYear: 2013,
    years: '2013–2014',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/1/4708.jpg',
    note: '',
  },
  {
    id: 6150,
    tvmazeId: '18650',
    title: 'Packages from Planet X',
    network: 'Cartoon Network',
    startYear: 2013,
    years: '2013–2014',
    genres: ['Comedy', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/63/159525.jpg',
    note: '',
  },
  {
    id: 6151,
    tvmazeId: '10446',
    title: 'Paper Giants: Magazine Wars',
    network: 'ABC',
    startYear: 2013,
    years: '2013',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/35/88395.jpg',
    note: '',
  },
  {
    id: 6152,
    tvmazeId: '3804',
    title: 'Pat & Cabbage',
    network: 'ITV1',
    startYear: 2013,
    years: '2013',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/47975.jpg',
    note: '',
  },
  {
    id: 6153,
    tvmazeId: '894',
    title: 'Paw Patrol',
    network: 'TVO',
    startYear: 2013,
    years: '2013–',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/608/1521295.jpg',
    note: '',
  },
  {
    id: 6154,
    tvmazeId: '22655',
    title: 'PAYDAY: The Web Series',
    network: 'YouTube',
    startYear: 2013,
    years: '2013',
    genres: ['Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/83/209474.jpg',
    note: '',
  },
  {
    id: 6155,
    tvmazeId: '269',
    title: 'Peaky Blinders',
    network: 'BBC One',
    startYear: 2013,
    years: '2013–',
    genres: ['Drama', 'Crime', 'History'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/48/122213.jpg',
    note: '',
  },
  {
    id: 6156,
    tvmazeId: '698',
    title: 'Peg + Cat',
    network: 'PBS',
    startYear: 2013,
    years: '2013–2018',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/5/14998.jpg',
    note: '',
  },
  {
    id: 6157,
    tvmazeId: '36275',
    title: 'Planet Cosmo',
    network: 'RTÉ2',
    startYear: 2013,
    years: '2013',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/153/382971.jpg',
    note: '',
  },
  {
    id: 6158,
    tvmazeId: '4681',
    title: 'Played',
    network: 'CTV',
    startYear: 2013,
    years: '2013',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/52816.jpg',
    note: '',
  },
  {
    id: 6159,
    tvmazeId: '3306',
    title: 'Please Like Me',
    network: 'ABC Family',
    startYear: 2013,
    years: '2013–2016',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/17/43990.jpg',
    note: '',
  },
  {
    id: 6160,
    tvmazeId: '313',
    title: 'Plebs',
    network: 'ITV2',
    startYear: 2013,
    years: '2013–2022',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/153/382980.jpg',
    note: '',
  },
  {
    id: 6161,
    tvmazeId: '28532',
    title: 'Power Games: The Packer-Murdoch Story',
    network: 'Nine Network',
    startYear: 2013,
    years: '2013',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/617/1542627.jpg',
    note: '',
  },
  {
    id: 6162,
    tvmazeId: '20242',
    title: 'Privates',
    network: 'BBC One',
    startYear: 2013,
    years: '2013',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/71/179185.jpg',
    note: '',
  },
  {
    id: 6163,
    tvmazeId: '20041',
    title: 'Project: S.E.R.A.',
    network: 'YouTube',
    startYear: 2013,
    years: '2013',
    genres: ['Action', 'Crime', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/70/176950.jpg',
    note: '',
  },
  {
    id: 6164,
    tvmazeId: '31167',
    title: 'Psychobitches',
    network: 'Sky Arts',
    startYear: 2013,
    years: '2013–2014',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/124/310987.jpg',
    note: '',
  },
  {
    id: 6165,
    tvmazeId: '12127',
    title: 'Q Pootle 5',
    network: 'CBeebies',
    startYear: 2013,
    years: '2013–2014',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/40/101781.jpg',
    note: '',
  },
  {
    id: 6166,
    tvmazeId: '29160',
    title: 'Quick Cuts',
    network: 'BBC Four',
    startYear: 2013,
    years: '2013',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/116/291223.jpg',
    note: '',
  },
  {
    id: 6167,
    tvmazeId: '4034',
    title: 'Quick Draw',
    network: 'Hulu',
    startYear: 2013,
    years: '2013–2014',
    genres: ['Comedy', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/49601.jpg',
    note: '',
  },
  {
    id: 6168,
    tvmazeId: '3805',
    title: 'Rabbids Invasion',
    network: 'Nicktoons',
    startYear: 2013,
    years: '2013–2019',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/47976.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 257, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 785, "cliffhanger": 237, "ended": 13610}};
