window.pageShows = [
  {
    id: 385,
    tvmazeId: '85051',
    title: 'El refugio atómico',
    network: 'Netflix',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/587/1469212.jpg',
    note: '',
  },
  {
    id: 386,
    tvmazeId: '80542',
    title: 'Electric Bloom',
    network: 'DisneyNOW',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy', 'Children', 'Music'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/599/1498698.jpg',
    note: '',
  },
  {
    id: 387,
    tvmazeId: '82650',
    title: 'Empathie',
    network: 'Crave',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/556/1392080.jpg',
    note: '',
  },
  {
    id: 388,
    tvmazeId: '85817',
    title: 'En el barro',
    network: 'Netflix',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/613/1533863.jpg',
    note: '',
  },
  {
    id: 389,
    tvmazeId: '87051',
    title: 'Enfes Bir Akşam',
    network: 'Netflix',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/589/1473454.jpg',
    note: '',
  },
  {
    id: 390,
    tvmazeId: '82550',
    title: 'Entre Paredes',
    network: 'Disney+',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/555/1388898.jpg',
    note: '',
  },
  {
    id: 391,
    tvmazeId: '86886',
    title: 'Entrepreneurs',
    network: 'Disney+',
    startYear: 2025,
    years: '2025',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/585/1464821.jpg',
    note: '',
  },
  {
    id: 392,
    tvmazeId: '82800',
    title: 'Espartanos. Una historia real',
    network: 'Disney+',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Sports'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/557/1392838.jpg',
    note: '',
  },
  {
    id: 393,
    tvmazeId: '88692',
    title: 'Estado de fuga 1986',
    network: 'Netflix',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/601/1503168.jpg',
    note: '',
  },
  {
    id: 394,
    tvmazeId: '88138',
    title: 'Eyes In The Woods',
    network: 'OUTtv',
    startYear: 2025,
    years: '2025–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/597/1492522.jpg',
    note: '',
  },
  {
    id: 395,
    tvmazeId: '73415',
    title: 'Eyes of Wakanda',
    network: 'Disney+',
    startYear: 2025,
    years: '2025',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/580/1451968.jpg',
    note: '',
  },
  {
    id: 396,
    tvmazeId: '84686',
    title: 'Favàritx',
    network: 'HBO Max',
    startYear: 2025,
    years: '2025–',
    genres: ['Crime', 'Thriller', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/568/1422149.jpg',
    note: '',
  },
  {
    id: 397,
    tvmazeId: '82548',
    title: 'Fear',
    network: 'Prime Video',
    startYear: 2025,
    years: '2025',
    genres: ['Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/555/1388892.jpg',
    note: '',
  },
  {
    id: 398,
    tvmazeId: '61922',
    title: 'Festning Norge',
    network: 'Prime Video',
    startYear: 2025,
    years: '2025–2024',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/523/1308928.jpg',
    note: '',
  },
  {
    id: 399,
    tvmazeId: '74834',
    title: 'Film Club',
    network: 'BBC iPlayer',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/591/1477788.jpg',
    note: '',
  },
  {
    id: 400,
    tvmazeId: '79722',
    title: 'Football Fantastics',
    network: 'BBC iPlayer',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy', 'Children', 'Sports'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/626/1566685.jpg',
    note: '',
  },
  {
    id: 401,
    tvmazeId: '65120',
    title: 'Forever',
    network: 'Netflix',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: '',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/564/1411466.jpg',
    note: '',
  },
  {
    id: 402,
    tvmazeId: '83389',
    title: 'Forget You Not',
    network: 'Netflix',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/569/1424752.jpg',
    note: '',
  },
  {
    id: 403,
    tvmazeId: '87996',
    title: 'Fortnite x The Simpsons',
    network: 'Disney+',
    startYear: 2025,
    years: '2025–',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/596/1490326.jpg',
    note: '',
  },
  {
    id: 404,
    tvmazeId: '84366',
    title: 'Franklin',
    network: 'Netflix',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/568/1421816.jpg',
    note: '',
  },
  {
    id: 405,
    tvmazeId: '82358',
    title: 'Frauds',
    network: 'ITVX',
    startYear: 2025,
    years: '2025–',
    genres: ['Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/590/1477157.jpg',
    note: '',
  },
  {
    id: 406,
    tvmazeId: '82168',
    title: 'Friendly Rivalry',
    network: 'U+ Mobile TV',
    startYear: 2025,
    years: '2025',
    genres: ['Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/552/1382447.jpg',
    note: '',
  },
  {
    id: 407,
    tvmazeId: '82532',
    title: 'Funboys',
    network: 'BBC iPlayer',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/629/1572517.jpg',
    note: '',
  },
  {
    id: 408,
    tvmazeId: '85376',
    title: 'Furia',
    network: 'HBO Max',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/583/1459460.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 17, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 398, "cliffhanger": 239, "ended": 15092}};
