window.pageShows = [
  {
    id: 1033,
    tvmazeId: '72758',
    title: 'English Teacher',
    network: 'FX',
    startYear: 2024,
    years: '2024–2025',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/586/1467301.jpg',
    note: '',
  },
  {
    id: 1034,
    tvmazeId: '74241',
    title: 'Enterrement de Vie de Garçon',
    network: 'Canal+',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/501/1253465.jpg',
    note: '',
  },
  {
    id: 1035,
    tvmazeId: '78971',
    title: 'Envidiosa',
    network: 'Netflix',
    startYear: 2024,
    years: '2024–2026',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/599/1498114.jpg',
    note: '',
  },
  {
    id: 1036,
    tvmazeId: '59244',
    title: 'Eric',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/531/1327939.jpg',
    note: '',
  },
  {
    id: 1037,
    tvmazeId: '91780',
    title: 'Escorting the Heiress',
    network: 'Reelshort',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/624/1561133.jpg',
    note: '',
  },
  {
    id: 1038,
    tvmazeId: '77924',
    title: 'Everybody Still Hates Chris',
    network: 'Comedy Central',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/533/1334841.jpg',
    note: '',
  },
  {
    id: 1039,
    tvmazeId: '37965',
    title: 'Expats',
    network: 'Prime Video',
    startYear: 2024,
    years: '2024',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/500/1251454.jpg',
    note: '',
  },
  {
    id: 1040,
    tvmazeId: '66350',
    title: 'Exploding Kittens',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy', 'Adult'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/527/1318636.jpg',
    note: '',
  },
  {
    id: 1041,
    tvmazeId: '75316',
    title: 'Exposure',
    network: 'Stan',
    startYear: 2024,
    years: '2024',
    genres: ['Thriller', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/524/1310822.jpg',
    note: '',
  },
  {
    id: 1042,
    tvmazeId: '76102',
    title: 'Faithless',
    network: 'Virgin Media Player',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/514/1285017.jpg',
    note: '',
  },
  {
    id: 1043,
    tvmazeId: '71232',
    title: 'Fake',
    network: 'Paramount+',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Romance', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/522/1306878.jpg',
    note: '',
  },
  {
    id: 1044,
    tvmazeId: '73556',
    title: 'Fallen',
    network: 'Globoplay',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Romance', 'Supernatural'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/531/1328102.jpg',
    note: '',
  },
  {
    id: 1045,
    tvmazeId: '49041',
    title: 'Fallout',
    network: 'Prime Video',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Action', 'Science-Fiction'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/599/1499142.jpg',
    note: '',
  },
  {
    id: 1046,
    tvmazeId: '45185',
    title: 'Fam Time',
    network: '7plus',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/527/1318415.jpg',
    note: '',
  },
  {
    id: 1047,
    tvmazeId: '79364',
    title: 'Family By Choice',
    network: 'jTBC',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/533/1334809.jpg',
    note: '',
  },
  {
    id: 1048,
    tvmazeId: '80348',
    title: 'Family Guy Hulu Exclusives',
    network: 'Hulu',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/599/1497907.jpg',
    note: '',
  },
  {
    id: 1049,
    tvmazeId: '76553',
    title: 'Fantasmas',
    network: 'HBO',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/522/1306906.jpg',
    note: '',
  },
  {
    id: 1050,
    tvmazeId: '76563',
    title: 'Felices Los 6',
    network: 'HBO Max',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/522/1306818.jpg',
    note: '',
  },
  {
    id: 1051,
    tvmazeId: '69674',
    title: 'Fiasco',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/513/1283157.jpg',
    note: '',
  },
  {
    id: 1052,
    tvmazeId: '74506',
    title: 'Fight Night: The Million Dollar Heist',
    network: 'Peacock',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/528/1322334.jpg',
    note: '',
  },
  {
    id: 1053,
    tvmazeId: '68641',
    title: 'Finders Keepers',
    network: '5',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/500/1250125.jpg',
    note: '',
  },
  {
    id: 1054,
    tvmazeId: '75942',
    title: 'Fizzy and Suds',
    network: 'ABC iview',
    startYear: 2024,
    years: '2024–',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/512/1281850.jpg',
    note: '',
  },
  {
    id: 1055,
    tvmazeId: '75339',
    title: 'Fleur Bleue',
    network: 'Canal+',
    startYear: 2024,
    years: '2024–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/546/1367288.jpg',
    note: '',
  },
  {
    id: 1056,
    tvmazeId: '73181',
    title: 'Flex x Cop',
    network: 'SBS',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Romance', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/500/1252007.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 44, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
