window.pageShows = [
  {
    id: 10729,
    tvmazeId: '41849',
    title: 'Down to Earth',
    network: 'BBC One',
    startYear: 1995,
    years: '1995',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 10730,
    tvmazeId: '7218',
    title: 'Dr. Katz, Professional Therapist',
    network: 'Comedy Central',
    startYear: 1995,
    years: '1995–2002',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/67168.jpg',
    note: '',
  },
  {
    id: 10731,
    tvmazeId: '80150',
    title: 'Dressing for Breakfast',
    network: 'Channel 4',
    startYear: 1995,
    years: '1995–1998',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/539/1348296.jpg',
    note: '',
  },
  {
    id: 10732,
    tvmazeId: '9704',
    title: 'Dumb and Dumber',
    network: 'Cartoon Network',
    startYear: 1995,
    years: '1995–1996',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/84274.jpg',
    note: '',
  },
  {
    id: 10733,
    tvmazeId: '28856',
    title: 'Dweebs',
    network: 'CBS',
    startYear: 1995,
    years: '1995',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/114/287391.jpg',
    note: '',
  },
  {
    id: 10734,
    tvmazeId: '6833',
    title: 'Earthworm Jim',
    network: 'The WB',
    startYear: 1995,
    years: '1995–1996',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/25/64589.jpg',
    note: '',
  },
  {
    id: 10735,
    tvmazeId: '39584',
    title: 'Extreme',
    network: 'ABC',
    startYear: 1995,
    years: '1995',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/173/434471.jpg',
    note: '',
  },
  {
    id: 10736,
    tvmazeId: '11531',
    title: 'Faith in the Future',
    network: 'ITV1',
    startYear: 1995,
    years: '1995–1998',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/38/97380.jpg',
    note: '',
  },
  {
    id: 10737,
    tvmazeId: '5953',
    title: 'Fantomcat',
    network: 'ITV1',
    startYear: 1995,
    years: '1995',
    genres: ['Children', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/58642.jpg',
    note: '',
  },
  {
    id: 10738,
    tvmazeId: '3254',
    title: 'Father Ted',
    network: 'Channel 4',
    startYear: 1995,
    years: '1995–1998',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/17/43679.jpg',
    note: '',
  },
  {
    id: 10739,
    tvmazeId: '28529',
    title: 'Fire',
    network: 'Seven Network',
    startYear: 1995,
    years: '1995–1996',
    genres: ['Drama', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/113/284105.jpg',
    note: '',
  },
  {
    id: 10740,
    tvmazeId: '39517',
    title: 'First Time Out',
    network: 'The WB',
    startYear: 1995,
    years: '1995',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/173/434186.jpg',
    note: '',
  },
  {
    id: 10741,
    tvmazeId: '31308',
    title: 'Fist of Fun',
    network: 'BBC Two',
    startYear: 1995,
    years: '1995–1996',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/124/312484.jpg',
    note: '',
  },
  {
    id: 10742,
    tvmazeId: '17403',
    title: 'Flipper',
    network: 'Syndication',
    startYear: 1995,
    years: '1995–2000',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/58/147048.jpg',
    note: '',
  },
  {
    id: 10743,
    tvmazeId: '6838',
    title: 'Freakazoid!',
    network: 'The WB',
    startYear: 1995,
    years: '1995–1997',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/25/64591.jpg',
    note: '',
  },
  {
    id: 10744,
    tvmazeId: '27141',
    title: 'Fudge',
    network: 'CBS',
    startYear: 1995,
    years: '1995',
    genres: ['Comedy', 'Children', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/107/267892.jpg',
    note: '',
  },
  {
    id: 10745,
    tvmazeId: '28581',
    title: 'Funky Squad',
    network: 'ABC',
    startYear: 1995,
    years: '1995',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/113/284314.jpg',
    note: '',
  },
  {
    id: 10746,
    tvmazeId: '23661',
    title: 'G.I. Joe Extreme',
    network: 'Syndication',
    startYear: 1995,
    years: '1995–1997',
    genres: ['Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/88/222228.jpg',
    note: '',
  },
  {
    id: 10747,
    tvmazeId: '37806',
    title: 'Gadget Boy and Heather',
    network: 'Syndication',
    startYear: 1995,
    years: '1995–1998',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/161/404261.jpg',
    note: '',
  },
  {
    id: 10748,
    tvmazeId: '4292',
    title: 'Game On!',
    network: 'BBC Two',
    startYear: 1995,
    years: '1995–1998',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/51175.jpg',
    note: '',
  },
  {
    id: 10749,
    tvmazeId: '5443',
    title: 'Get Smart',
    network: 'FOX',
    startYear: 1995,
    years: '1995',
    genres: ['Comedy', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/55692.jpg',
    note: '',
  },
  {
    id: 10750,
    tvmazeId: '51109',
    title: 'Ghosts',
    network: 'BBC One',
    startYear: 1995,
    years: '1995',
    genres: ['Drama', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/299/747835.jpg',
    note: '',
  },
  {
    id: 10751,
    tvmazeId: '42078',
    title: 'Glad Rags',
    network: 'Nine Network',
    startYear: 1995,
    years: '1995',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 10752,
    tvmazeId: '9546',
    title: 'Goosebumps',
    network: 'YTV',
    startYear: 1995,
    years: '1995–1998',
    genres: ['Children', 'Fantasy', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/400/1001463.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 448, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 670, "cliffhanger": 0, "ended": 13760}};
