window.pageShows = [
  {
    id: 5665,
    tvmazeId: '23326',
    title: 'Cassandra French\'s Finishing School',
    network: 'Audience Network',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/97/243355.jpg',
    note: '',
  },
  {
    id: 5666,
    tvmazeId: '25242',
    title: 'Castlevania',
    network: 'Netflix',
    startYear: 2017,
    years: '2017–2021',
    genres: ['Fantasy', 'Horror', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/316/790637.jpg',
    note: '',
  },
  {
    id: 5667,
    tvmazeId: '74085',
    title: 'Chase',
    network: 'Prime Video',
    startYear: 2017,
    years: '2017–2018',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/500/1250930.jpg',
    note: '',
  },
  {
    id: 5668,
    tvmazeId: '12327',
    title: 'Chicago Justice',
    network: 'NBC',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/93/232510.jpg',
    note: '',
  },
  {
    id: 5669,
    tvmazeId: '25715',
    title: 'Chicago Typewriter',
    network: 'tvN',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy', 'Fantasy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/559/1399212.jpg',
    note: '',
  },
  {
    id: 5670,
    tvmazeId: '32087',
    title: 'Chicken Girls',
    network: 'YouTube',
    startYear: 2017,
    years: '2017–2023',
    genres: ['Drama', 'Music', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/137/344365.jpg',
    note: '',
  },
  {
    id: 5671,
    tvmazeId: '22986',
    title: 'Chief Kim',
    network: 'KBS2',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/95/238056.jpg',
    note: '',
  },
  {
    id: 5672,
    tvmazeId: '30759',
    title: 'Chinese Burn',
    network: 'BBC Three',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 5673,
    tvmazeId: '74567',
    title: 'Chip \'N Dale\'s Nutty Tales',
    network: 'Disney Junior',
    startYear: 2017,
    years: '2017–2019',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/503/1258223.jpg',
    note: '',
  },
  {
    id: 5674,
    tvmazeId: '27011',
    title: 'Chloe Does It',
    network: 'mylifetime.com',
    startYear: 2017,
    years: '2017',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/364/912463.jpg',
    note: '',
  },
  {
    id: 5675,
    tvmazeId: '44113',
    title: 'Christmas in Evergreen',
    network: 'Hallmark Channel',
    startYear: 2017,
    years: '2017–2020',
    genres: ['Drama', 'Family', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/213/533355.jpg',
    note: '',
  },
  {
    id: 5676,
    tvmazeId: '27846',
    title: 'Chuck\'s Choice',
    network: 'YTV',
    startYear: 2017,
    years: '2017',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/110/275633.jpg',
    note: '',
  },
  {
    id: 5677,
    tvmazeId: '26156',
    title: 'Circle: Two Worlds Connected',
    network: 'tvN',
    startYear: 2017,
    years: '2017',
    genres: ['Science-Fiction', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/111/279506.jpg',
    note: '',
  },
  {
    id: 5678,
    tvmazeId: '15774',
    title: 'Claws',
    network: 'TNT',
    startYear: 2017,
    years: '2017–2022',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/360/902167.jpg',
    note: '',
  },
  {
    id: 5679,
    tvmazeId: '12328',
    title: 'Clique',
    network: 'BBC Three',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Crime', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/115/287894.jpg',
    note: '',
  },
  {
    id: 5680,
    tvmazeId: '25277',
    title: 'Cloudy with a Chance of Meatballs',
    network: 'Cartoon Network',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/98/245431.jpg',
    note: '',
  },
  {
    id: 5681,
    tvmazeId: '32318',
    title: 'Cody & Lexy',
    network: 'YouTube',
    startYear: 2017,
    years: '2017',
    genres: ['Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/448/1122324.jpg',
    note: '',
  },
  {
    id: 5682,
    tvmazeId: '26827',
    title: 'Commander Inappropriate',
    network: 'Prime Video',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/121/303346.jpg',
    note: '',
  },
  {
    id: 5683,
    tvmazeId: '30529',
    title: 'Comrade Detective',
    network: 'Prime Video',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/122/306139.jpg',
    note: '',
  },
  {
    id: 5684,
    tvmazeId: '25924',
    title: 'Confess',
    network: 'go90',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/104/261284.jpg',
    note: '',
  },
  {
    id: 5685,
    tvmazeId: '45080',
    title: 'Cooking with Bill',
    network: 'Steam',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy', 'Food'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 5686,
    tvmazeId: '6456',
    title: 'Counterpart',
    network: 'STARZ',
    startYear: 2017,
    years: '2017–2019',
    genres: ['Drama', 'Science-Fiction', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/175/438213.jpg',
    note: '',
  },
  {
    id: 5687,
    tvmazeId: '31082',
    title: 'Crash Course Film',
    network: 'YouTube',
    startYear: 2017,
    years: '2017–2018',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/123/309728.jpg',
    note: '',
  },
  {
    id: 5688,
    tvmazeId: '31076',
    title: 'Crash Course Mythology',
    network: 'YouTube',
    startYear: 2017,
    years: '2017–2018',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/123/309707.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 237, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 398, "cliffhanger": 239, "ended": 15092}};
