window.pageShows = [
  {
    id: 14329,
    tvmazeId: '65129',
    title: 'Jack and Mike',
    network: 'ABC',
    startYear: 1986,
    years: '1986–1987',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/523/1309763.jpg',
    note: '',
  },
  {
    id: 14330,
    tvmazeId: '69636',
    title: 'Jimbo and the Jet Set',
    network: 'BBC One',
    startYear: 1986,
    years: '1986–1987',
    genres: ['Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/467/1167902.jpg',
    note: '',
  },
  {
    id: 14331,
    tvmazeId: '75189',
    title: 'Joe Bash',
    network: 'ABC',
    startYear: 1986,
    years: '1986',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/566/1417033.jpg',
    note: '',
  },
  {
    id: 14332,
    tvmazeId: '33861',
    title: 'Jonny Quest',
    network: 'Syndication',
    startYear: 1986,
    years: '1986–1987',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/138/345647.jpg',
    note: '',
  },
  {
    id: 14333,
    tvmazeId: '32326',
    title: 'Jossy\'s Giants',
    network: 'BBC One',
    startYear: 1986,
    years: '1986–1987',
    genres: ['Drama', 'Comedy', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/145/362746.jpg',
    note: '',
  },
  {
    id: 14334,
    tvmazeId: '25786',
    title: 'Kay O\'Brien',
    network: 'CBS',
    startYear: 1986,
    years: '1986',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/478/1197331.jpg',
    note: '',
  },
  {
    id: 14335,
    tvmazeId: '51513',
    title: 'King and Castle',
    network: 'ITV1',
    startYear: 1986,
    years: '1986–1988',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/279/699881.jpg',
    note: '',
  },
  {
    id: 14336,
    tvmazeId: '50995',
    title: 'King of the Ghetto',
    network: 'BBC Two',
    startYear: 1986,
    years: '1986',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14337,
    tvmazeId: '23147',
    title: 'Kissyfur',
    network: 'NBC',
    startYear: 1986,
    years: '1986–1987',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/86/216258.jpg',
    note: '',
  },
  {
    id: 14338,
    tvmazeId: '1481',
    title: 'L.A. Law',
    network: 'NBC',
    startYear: 1986,
    years: '1986–2002',
    genres: ['Drama', 'Crime', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/8/21145.jpg',
    note: '',
  },
  {
    id: 14339,
    tvmazeId: '24473',
    title: 'Ladies in Charge',
    network: 'ITV1',
    startYear: 1986,
    years: '1986',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/93/233374.jpg',
    note: '',
  },
  {
    id: 14340,
    tvmazeId: '19544',
    title: 'Lazer Tag Academy',
    network: 'NBC',
    startYear: 1986,
    years: '1986',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/68/172186.jpg',
    note: '',
  },
  {
    id: 14341,
    tvmazeId: '65152',
    title: 'Lenny Henry Tonite',
    network: 'BBC Two',
    startYear: 1986,
    years: '1986',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14342,
    tvmazeId: '24594',
    title: 'Life with Lucy',
    network: 'ABC',
    startYear: 1986,
    years: '1986',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/598/1495157.jpg',
    note: '',
  },
  {
    id: 14343,
    tvmazeId: '51519',
    title: 'Lord Mountbatten: The Last Viceroy',
    network: 'ITV1',
    startYear: 1986,
    years: '1986',
    genres: ['Drama', 'War', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/279/699899.jpg',
    note: '',
  },
  {
    id: 14344,
    tvmazeId: '36261',
    title: 'Lost Empires',
    network: 'ITV1',
    startYear: 1986,
    years: '1986',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/153/382903.jpg',
    note: '',
  },
  {
    id: 14345,
    tvmazeId: '7548',
    title: 'Lovejoy',
    network: 'BBC One',
    startYear: 1986,
    years: '1986–1994',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/69643.jpg',
    note: '',
  },
  {
    id: 14346,
    tvmazeId: '1748',
    title: 'Matlock',
    network: 'ABC',
    startYear: 1986,
    years: '1986–1995',
    genres: ['Drama', 'Crime', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/9/24437.jpg',
    note: '',
  },
  {
    id: 14347,
    tvmazeId: '73991',
    title: 'Melba',
    network: 'CBS',
    startYear: 1986,
    years: '1986',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/566/1416996.jpg',
    note: '',
  },
  {
    id: 14348,
    tvmazeId: '50662',
    title: 'Monte Carlo',
    network: 'CBS',
    startYear: 1986,
    years: '1986',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/275/687646.jpg',
    note: '',
  },
  {
    id: 14349,
    tvmazeId: '50999',
    title: 'Mr Pye',
    network: 'Channel 4',
    startYear: 1986,
    years: '1986',
    genres: ['Drama', 'Comedy', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/276/692102.jpg',
    note: '',
  },
  {
    id: 14350,
    tvmazeId: '33611',
    title: 'Mr. Sunshine',
    network: 'ABC',
    startYear: 1986,
    years: '1986',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/139/349457.jpg',
    note: '',
  },
  {
    id: 14351,
    tvmazeId: '55405',
    title: 'Muzzy in Gondoland',
    network: 'BBC One',
    startYear: 1986,
    years: '1986',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/318/796444.jpg',
    note: '',
  },
  {
    id: 14352,
    tvmazeId: '27017',
    title: 'My Little Pony \'n Friends',
    network: 'Syndication',
    startYear: 1986,
    years: '1986–1987',
    genres: ['Adventure', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/106/266888.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 598, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
