window.pageShows = [
  {
    id: 3005,
    tvmazeId: '56607',
    title: 'Warped!',
    network: 'Nickelodeon',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy', 'Children'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/389/973793.jpg',
    note: '',
  },
  {
    id: 3006,
    tvmazeId: '51025',
    title: 'We Baby Bears',
    network: 'Cartoon Network',
    startYear: 2022,
    years: '2022–',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/416/1041406.jpg',
    note: '',
  },
  {
    id: 3007,
    tvmazeId: '53984',
    title: 'We Own This City',
    network: 'HBO',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/407/1017587.jpg',
    note: '',
  },
  {
    id: 3008,
    tvmazeId: '64033',
    title: 'Weak Hero: Class 1',
    network: 'Netflix',
    startYear: 2022,
    years: '2022–2025',
    genres: ['Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/568/1420042.jpg',
    note: '',
  },
  {
    id: 3009,
    tvmazeId: '53182',
    title: 'WeCrashed',
    network: 'Apple TV',
    startYear: 2022,
    years: '2022',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/397/994399.jpg',
    note: '',
  },
  {
    id: 3010,
    tvmazeId: '56586',
    title: 'Wedding Season',
    network: 'Disney+',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy', 'Action', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/418/1046286.jpg',
    note: '',
  },
  {
    id: 3011,
    tvmazeId: '53647',
    title: 'Wednesday',
    network: 'Netflix',
    startYear: 2022,
    years: '2022–',
    genres: ['Comedy', 'Mystery', 'Supernatural'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/586/1466410.jpg',
    note: '',
  },
  {
    id: 3012,
    tvmazeId: '58974',
    title: 'Week-end Family',
    network: 'Disney+',
    startYear: 2022,
    years: '2022–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/398/996578.jpg',
    note: '',
  },
  {
    id: 3013,
    tvmazeId: '60196',
    title: 'Welcome to Chippendales',
    network: 'Hulu',
    startYear: 2022,
    years: '2022–2023',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/440/1100146.jpg',
    note: '',
  },
  {
    id: 3014,
    tvmazeId: '46416',
    title: 'Welcome to Flatch',
    network: 'FOX',
    startYear: 2022,
    years: '2022–2023',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/418/1046811.jpg',
    note: '',
  },
  {
    id: 3015,
    tvmazeId: '54722',
    title: 'Why Didn\'t They Ask Evans?',
    network: 'BritBox',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/404/1010786.jpg',
    note: '',
  },
  {
    id: 3016,
    tvmazeId: '64628',
    title: 'Why You… Y Me?',
    network: 'YouTube',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy', 'Music', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/426/1065776.jpg',
    note: '',
  },
  {
    id: 3017,
    tvmazeId: '63487',
    title: 'Wicked City',
    network: 'ALLBLK',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Supernatural'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'ABC cancelled after three episodes; the 1980s Sunset Strip serial killer anthology was barely introduced.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/482/1205712.jpg',
    note: '',
  },
  {
    id: 3018,
    tvmazeId: '63037',
    title: 'Wielka woda',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/469/1172959.jpg',
    note: '',
  },
  {
    id: 3019,
    tvmazeId: '51419',
    title: 'Willow',
    network: 'Disney+',
    startYear: 2022,
    years: '2022–2023',
    genres: ['Adventure', 'Fantasy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/426/1067123.jpg',
    note: '',
  },
  {
    id: 3020,
    tvmazeId: '59390',
    title: 'Winning Time: The Rise of the Lakers Dynasty',
    network: 'HBO',
    startYear: 2022,
    years: '2022–2023',
    genres: ['Drama', 'Comedy', 'Sports'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/473/1183737.jpg',
    note: '',
  },
  {
    id: 3021,
    tvmazeId: '58215',
    title: 'Without Sin',
    network: 'ITVX',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/437/1093847.jpg',
    note: '',
  },
  {
    id: 3022,
    tvmazeId: '58856',
    title: 'Witness Number 3',
    network: '5',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/416/1040023.jpg',
    note: '',
  },
  {
    id: 3023,
    tvmazeId: '55006',
    title: 'Wolf Like Me',
    network: 'Stan',
    startYear: 2022,
    years: '2022–2023',
    genres: ['Drama', 'Romance', 'Supernatural'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/482/1205713.jpg',
    note: '',
  },
  {
    id: 3024,
    tvmazeId: '67621',
    title: 'Women in Taipei',
    network: 'Disney+',
    startYear: 2022,
    years: '2022',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/453/1133038.jpg',
    note: '',
  },
  {
    id: 3025,
    tvmazeId: '50002',
    title: 'Women of the Movement',
    network: 'ABC',
    startYear: 2022,
    years: '2022',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/388/971109.jpg',
    note: '',
  },
  {
    id: 3026,
    tvmazeId: '54395',
    title: 'Wreck',
    network: 'BBC iPlayer',
    startYear: 2022,
    years: '2022–2024',
    genres: ['Comedy', 'Thriller', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/524/1312078.jpg',
    note: '',
  },
  {
    id: 3027,
    tvmazeId: '54360',
    title: 'Yakamoz S-245',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Science-Fiction', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/403/1009885.jpg',
    note: '',
  },
  {
    id: 3028,
    tvmazeId: '59833',
    title: 'Yeh Kaali Kaali Ankhein',
    network: 'Netflix',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/389/973433.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 126, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
