window.pageShows = [
  {
    id: 14429,
    tvmazeId: '51528',
    title: 'Lytton\'s Diary',
    network: 'ITV1',
    startYear: 1985,
    years: '1985–1986',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/279/699971.jpg',
    note: '',
  },
  {
    id: 14430,
    tvmazeId: '4400',
    title: 'M.A.S.K.',
    network: 'Syndication',
    startYear: 1985,
    years: '1985–1986',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/140/350953.jpg',
    note: '',
  },
  {
    id: 14431,
    tvmazeId: '56584',
    title: 'MacGruder and Loud',
    network: 'ABC',
    startYear: 1985,
    years: '1985',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/586/1466821.jpg',
    note: '',
  },
  {
    id: 14432,
    tvmazeId: '821',
    title: 'MacGyver',
    network: 'ABC',
    startYear: 1985,
    years: '1985–1994',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/237/592622.jpg',
    note: '',
  },
  {
    id: 14433,
    tvmazeId: '17818',
    title: 'Maelstrom',
    network: 'BBC One',
    startYear: 1985,
    years: '1985',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/60/150315.jpg',
    note: '',
  },
  {
    id: 14434,
    tvmazeId: '8819',
    title: 'Mann\'s Best Friends',
    network: 'Channel 4',
    startYear: 1985,
    years: '1985',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/78227.jpg',
    note: '',
  },
  {
    id: 14435,
    tvmazeId: '24166',
    title: 'Mapp & Lucia',
    network: 'ITV1',
    startYear: 1985,
    years: '1985–1986',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/613/1534008.jpg',
    note: '',
  },
  {
    id: 14436,
    tvmazeId: '38000',
    title: 'Mary',
    network: 'CBS',
    startYear: 1985,
    years: '1985–1986',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/162/406909.jpg',
    note: '',
  },
  {
    id: 14437,
    tvmazeId: '47805',
    title: 'Me & Mom',
    network: 'ABC',
    startYear: 1985,
    years: '1985',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/477/1193127.jpg',
    note: '',
  },
  {
    id: 14438,
    tvmazeId: '3619',
    title: 'Misfits of Science',
    network: 'NBC',
    startYear: 1985,
    years: '1985–1986',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/46944.jpg',
    note: '',
  },
  {
    id: 14439,
    tvmazeId: '1487',
    title: 'Moonlighting',
    network: 'ABC',
    startYear: 1985,
    years: '1985–1989',
    genres: ['Drama', 'Comedy', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/8/21190.jpg',
    note: '',
  },
  {
    id: 14440,
    tvmazeId: '80002',
    title: 'Moving',
    network: 'ITV1',
    startYear: 1985,
    years: '1985',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14441,
    tvmazeId: '7603',
    title: 'Mr. Belvedere',
    network: 'ABC',
    startYear: 1985,
    years: '1985–1990',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/70108.jpg',
    note: '',
  },
  {
    id: 14442,
    tvmazeId: '81304',
    title: 'Murder of a Moderate Man',
    network: 'BBC One',
    startYear: 1985,
    years: '1985',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14443,
    tvmazeId: '28619',
    title: 'Mussolini and I',
    network: 'HBO',
    startYear: 1985,
    years: '1985',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/113/284805.jpg',
    note: '',
  },
  {
    id: 14444,
    tvmazeId: '28949',
    title: 'Mussolini: The Untold Story',
    network: 'NBC',
    startYear: 1985,
    years: '1985',
    genres: ['Drama', 'War', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/115/288411.jpg',
    note: '',
  },
  {
    id: 14445,
    tvmazeId: '27519',
    title: 'My Brother Jonathan',
    network: 'BBC Two',
    startYear: 1985,
    years: '1985',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/108/271556.jpg',
    note: '',
  },
  {
    id: 14446,
    tvmazeId: '5420',
    title: 'Neighbours',
    network: 'Prime Video',
    startYear: 1985,
    years: '1985–2025',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/471/1178200.jpg',
    note: '',
  },
  {
    id: 14447,
    tvmazeId: '20658',
    title: 'Night Heat',
    network: 'CTV',
    startYear: 1985,
    years: '1985–1989',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/182533.jpg',
    note: '',
  },
  {
    id: 14448,
    tvmazeId: '1157',
    title: 'North and South',
    network: 'ABC',
    startYear: 1985,
    years: '1985–1994',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17403.jpg',
    note: '',
  },
  {
    id: 14449,
    tvmazeId: '45246',
    title: 'Oliver Twist',
    network: 'BBC One',
    startYear: 1985,
    years: '1985',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/228/571691.jpg',
    note: '',
  },
  {
    id: 14450,
    tvmazeId: '51586',
    title: 'Oscar',
    network: 'BBC Two',
    startYear: 1985,
    years: '1985',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14451,
    tvmazeId: '19368',
    title: 'Otherworld',
    network: 'CBS',
    startYear: 1985,
    years: '1985',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/68/170466.jpg',
    note: '',
  },
  {
    id: 14452,
    tvmazeId: '65111',
    title: 'Our Family Honor',
    network: 'ABC',
    startYear: 1985,
    years: '1985–1986',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/566/1417003.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 602, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
