window.pageShows = [
  {
    id: 11137,
    tvmazeId: '540',
    title: 'Frasier',
    network: 'NBC',
    startYear: 1993,
    years: '1993–2004',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/611/1528088.jpg',
    note: '',
  },
  {
    id: 11138,
    tvmazeId: '17264',
    title: 'Full Stretch',
    network: 'ITV1',
    startYear: 1993,
    years: '1993',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/58/145679.jpg',
    note: '',
  },
  {
    id: 11139,
    tvmazeId: '37309',
    title: 'Gallowglass',
    network: 'BBC One',
    startYear: 1993,
    years: '1993',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/159/398550.jpg',
    note: '',
  },
  {
    id: 11140,
    tvmazeId: '65496',
    title: 'George',
    network: 'ABC',
    startYear: 1993,
    years: '1993–1994',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/576/1440285.jpg',
    note: '',
  },
  {
    id: 11141,
    tvmazeId: '8151',
    title: 'Getting By',
    network: 'NBC',
    startYear: 1993,
    years: '1993–1994',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11142,
    tvmazeId: '65522',
    title: 'Good Advice',
    network: 'CBS',
    startYear: 1993,
    years: '1993–1994',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/432/1082276.jpg',
    note: '',
  },
  {
    id: 11143,
    tvmazeId: '7537',
    title: 'Goodnight Sweetheart',
    network: 'BBC One',
    startYear: 1993,
    years: '1993–2016',
    genres: ['Comedy', 'Romance', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/69540.jpg',
    note: '',
  },
  {
    id: 11144,
    tvmazeId: '7691',
    title: 'Grace Under Fire',
    network: 'ABC',
    startYear: 1993,
    years: '1993–1998',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/603/1507826.jpg',
    note: '',
  },
  {
    id: 11145,
    tvmazeId: '8211',
    title: 'Halfway Across the Galaxy and Turn Left',
    network: 'ITV1',
    startYear: 1993,
    years: '1993–1994',
    genres: ['Comedy', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/74297.jpg',
    note: '',
  },
  {
    id: 11146,
    tvmazeId: '51690',
    title: 'Harry',
    network: 'BBC One',
    startYear: 1993,
    years: '1993–1995',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/280/702112.jpg',
    note: '',
  },
  {
    id: 11147,
    tvmazeId: '18043',
    title: 'Harts of the West',
    network: 'CBS',
    startYear: 1993,
    years: '1993–1994',
    genres: ['Drama', 'Comedy', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/61/153004.jpg',
    note: '',
  },
  {
    id: 11148,
    tvmazeId: '51116',
    title: 'Head Over Heels',
    network: 'ITV1',
    startYear: 1993,
    years: '1993',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/277/693607.jpg',
    note: '',
  },
  {
    id: 11149,
    tvmazeId: '37765',
    title: 'Health and Efficiency',
    network: 'BBC One',
    startYear: 1993,
    years: '1993–1995',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/161/403177.jpg',
    note: '',
  },
  {
    id: 11150,
    tvmazeId: '45043',
    title: 'Heidi',
    network: 'Disney Channel',
    startYear: 1993,
    years: '1993',
    genres: ['Drama', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/224/560169.jpg',
    note: '',
  },
  {
    id: 11151,
    tvmazeId: '6224',
    title: 'Home Free',
    network: 'ABC',
    startYear: 1993,
    years: '1993',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/343/858887.jpg',
    note: '',
  },
  {
    id: 11152,
    tvmazeId: '830',
    title: 'Homicide: Life on the Street',
    network: 'NBC',
    startYear: 1993,
    years: '1993–2000',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/15762.jpg',
    note: '',
  },
  {
    id: 11153,
    tvmazeId: '40773',
    title: 'Hotel Room',
    network: 'HBO',
    startYear: 1993,
    years: '1993',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/378/946630.jpg',
    note: '',
  },
  {
    id: 11154,
    tvmazeId: '65236',
    title: 'I, Lovett',
    network: 'BBC Two',
    startYear: 1993,
    years: '1993',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/611/1528168.jpg',
    note: '',
  },
  {
    id: 11155,
    tvmazeId: '65521',
    title: 'If You See God, Tell Him',
    network: 'BBC One',
    startYear: 1993,
    years: '1993',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/432/1082275.jpg',
    note: '',
  },
  {
    id: 11156,
    tvmazeId: '65523',
    title: 'It Had to Be You',
    network: 'CBS',
    startYear: 1993,
    years: '1993',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/432/1082277.jpg',
    note: '',
  },
  {
    id: 11157,
    tvmazeId: '44930',
    title: 'J.F.K.: Reckless Youth',
    network: 'ABC',
    startYear: 1993,
    years: '1993',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/220/550985.jpg',
    note: '',
  },
  {
    id: 11158,
    tvmazeId: '41076',
    title: 'Joe\'s Life',
    network: 'ABC',
    startYear: 1993,
    years: '1993',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/379/948200.jpg',
    note: '',
  },
  {
    id: 11159,
    tvmazeId: '55728',
    title: 'Johnny Bago',
    network: 'CBS',
    startYear: 1993,
    years: '1993',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/324/812307.jpg',
    note: '',
  },
  {
    id: 11160,
    tvmazeId: '35883',
    title: 'Joking Apart',
    network: 'BBC Two',
    startYear: 1993,
    years: '1993–1995',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/151/379945.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 465, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 334, "cliffhanger": 235, "ended": 13701}};
