window.pageShows = [
  {
    id: 12577,
    tvmazeId: '22007',
    title: 'The Faculty',
    network: 'ABC',
    startYear: 1996,
    years: '1996',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/79/199744.jpg',
    note: '',
  },
  {
    id: 12578,
    tvmazeId: '36698',
    title: 'The Fortunes and Misfortunes of Moll Flanders',
    network: 'PBS',
    startYear: 1996,
    years: '1996',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/277/693496.jpg',
    note: '',
  },
  {
    id: 12579,
    tvmazeId: '51105',
    title: 'The Fragile Heart',
    network: 'Channel 4',
    startYear: 1996,
    years: '1996',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/277/693500.jpg',
    note: '',
  },
  {
    id: 12580,
    tvmazeId: '90745',
    title: 'The Genie From Down Under',
    network: 'ABC',
    startYear: 1996,
    years: '1996–1998',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/617/1543015.jpg',
    note: '',
  },
  {
    id: 12581,
    tvmazeId: '48951',
    title: 'The Hello Girls',
    network: 'BBC One',
    startYear: 1996,
    years: '1996–1998',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12582,
    tvmazeId: '35909',
    title: 'The High Life',
    network: 'HBO',
    startYear: 1996,
    years: '1996',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12583,
    tvmazeId: '4241',
    title: 'The Incredible Hulk',
    network: 'UPN',
    startYear: 1996,
    years: '1996–1997',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/50843.jpg',
    note: '',
  },
  {
    id: 12584,
    tvmazeId: '12298',
    title: 'The Jamie Foxx Show',
    network: 'The WB',
    startYear: 1996,
    years: '1996–2001',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/41/104425.jpg',
    note: '',
  },
  {
    id: 12585,
    tvmazeId: '87517',
    title: 'The Last Frontier',
    network: 'FOX',
    startYear: 1996,
    years: '1996',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12586,
    tvmazeId: '40787',
    title: 'The Lazarus Man',
    network: 'TNT',
    startYear: 1996,
    years: '1996',
    genres: ['Action', 'Adventure', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/182/455979.jpg',
    note: '',
  },
  {
    id: 12587,
    tvmazeId: '36262',
    title: 'The Legacy of Reginald Perrin',
    network: 'BBC One',
    startYear: 1996,
    years: '1996',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/153/382904.jpg',
    note: '',
  },
  {
    id: 12588,
    tvmazeId: '65709',
    title: 'The Louie Show',
    network: 'CBS',
    startYear: 1996,
    years: '1996',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12589,
    tvmazeId: '51163',
    title: 'The Moonstone',
    network: 'BBC Two',
    startYear: 1996,
    years: '1996',
    genres: ['Drama', 'Crime', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/277/694222.jpg',
    note: '',
  },
  {
    id: 12590,
    tvmazeId: '32241',
    title: 'The Mystery Files of Shelby Woo',
    network: 'Nickelodeon',
    startYear: 1996,
    years: '1996–1998',
    genres: ['Children', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/128/321920.jpg',
    note: '',
  },
  {
    id: 12591,
    tvmazeId: '12995',
    title: 'The Newsroom',
    network: 'CBC',
    startYear: 1996,
    years: '1996–2005',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/44/111515.jpg',
    note: '',
  },
  {
    id: 12592,
    tvmazeId: '681',
    title: 'The Pretender',
    network: 'NBC',
    startYear: 1996,
    years: '1996–2001',
    genres: ['Drama', 'Adventure', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/5/14846.jpg',
    note: '',
  },
  {
    id: 12593,
    tvmazeId: '75689',
    title: 'The Prince and the Pauper',
    network: 'BBC One',
    startYear: 1996,
    years: '1996',
    genres: ['Drama', 'Adventure', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/510/1276565.jpg',
    note: '',
  },
  {
    id: 12594,
    tvmazeId: '58613',
    title: 'The Rez',
    network: 'CBC',
    startYear: 1996,
    years: '1996–1997',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/369/924975.jpg',
    note: '',
  },
  {
    id: 12595,
    tvmazeId: '18976',
    title: 'The Sculptress',
    network: 'BBC One',
    startYear: 1996,
    years: '1996',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/65/164257.jpg',
    note: '',
  },
  {
    id: 12596,
    tvmazeId: '12218',
    title: 'The Sentinel',
    network: 'UPN',
    startYear: 1996,
    years: '1996–1999',
    genres: ['Drama', 'Crime', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/41/102923.jpg',
    note: '',
  },
  {
    id: 12597,
    tvmazeId: '40760',
    title: 'The Show',
    network: 'FOX',
    startYear: 1996,
    years: '1996',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12598,
    tvmazeId: '12299',
    title: 'The Steve Harvey Show',
    network: 'The WB',
    startYear: 1996,
    years: '1996–2002',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/41/104427.jpg',
    note: '',
  },
  {
    id: 12599,
    tvmazeId: '11357',
    title: 'The Tenant of Wildfell Hall',
    network: 'BBC One',
    startYear: 1996,
    years: '1996',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/38/95912.jpg',
    note: '',
  },
  {
    id: 12600,
    tvmazeId: '74165',
    title: 'The Tex Avery Show',
    network: 'Cartoon Network',
    startYear: 1996,
    years: '1996',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/500/1251978.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 525, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 398, "cliffhanger": 239, "ended": 15092}};
