window.pageShows = [
  {
    id: 13153,
    tvmazeId: '44428',
    title: 'The Adventures of Dudley the Dragon',
    network: 'TVO',
    startYear: 1993,
    years: '1993–1997',
    genres: ['Family', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/215/538626.jpg',
    note: '',
  },
  {
    id: 13154,
    tvmazeId: '5940',
    title: 'The Adventures of Pete & Pete',
    network: 'Nickelodeon',
    startYear: 1993,
    years: '1993–1996',
    genres: ['Drama', 'Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/58566.jpg',
    note: '',
  },
  {
    id: 13155,
    tvmazeId: '12648',
    title: 'The Animals of Farthing Wood',
    network: 'BBC One',
    startYear: 1993,
    years: '1993–1995',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/43/108295.jpg',
    note: '',
  },
  {
    id: 13156,
    tvmazeId: '18669',
    title: 'The Bots Master',
    network: 'Syndication',
    startYear: 1993,
    years: '1993–1994',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/63/159762.jpg',
    note: '',
  },
  {
    id: 13157,
    tvmazeId: '10980',
    title: 'The Buddha of Suburbia',
    network: 'BBC Two',
    startYear: 1993,
    years: '1993',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/608/1522361.jpg',
    note: '',
  },
  {
    id: 13158,
    tvmazeId: '16759',
    title: 'The Building',
    network: 'CBS',
    startYear: 1993,
    years: '1993',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 13159,
    tvmazeId: '10005',
    title: 'The Detectives',
    network: 'BBC One',
    startYear: 1993,
    years: '1993–1997',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/291/729608.jpg',
    note: '',
  },
  {
    id: 13160,
    tvmazeId: '50804',
    title: 'The Fire Next Time',
    network: 'CBS',
    startYear: 1993,
    years: '1993',
    genres: ['Drama', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/276/690078.jpg',
    note: '',
  },
  {
    id: 13161,
    tvmazeId: '14757',
    title: 'The Inspector Alleyn Mysteries',
    network: 'BBC One',
    startYear: 1993,
    years: '1993–1994',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/49/124838.jpg',
    note: '',
  },
  {
    id: 13162,
    tvmazeId: '1479',
    title: 'The John Larroquette Show',
    network: 'NBC',
    startYear: 1993,
    years: '1993–1996',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/14/37195.jpg',
    note: '',
  },
  {
    id: 13163,
    tvmazeId: '5952',
    title: 'The Legends of Treasure Island',
    network: 'ITV1',
    startYear: 1993,
    years: '1993–1995',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/58625.jpg',
    note: '',
  },
  {
    id: 13164,
    tvmazeId: '64326',
    title: 'The Lodge',
    network: 'ITV1',
    startYear: 1993,
    years: '1993',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 13165,
    tvmazeId: '16937',
    title: 'The Mommies',
    network: 'NBC',
    startYear: 1993,
    years: '1993–1995',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/56/142440.jpg',
    note: '',
  },
  {
    id: 13166,
    tvmazeId: '1119',
    title: 'The Nanny',
    network: 'CBS',
    startYear: 1993,
    years: '1993–1999',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17252.jpg',
    note: '',
  },
  {
    id: 13167,
    tvmazeId: '72142',
    title: 'The New Adventures of Speed Racer',
    network: 'Syndication',
    startYear: 1993,
    years: '1993',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/483/1207519.jpg',
    note: '',
  },
  {
    id: 13168,
    tvmazeId: '29583',
    title: 'The Pink Panther',
    network: 'Syndication',
    startYear: 1993,
    years: '1993–1995',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/117/294031.jpg',
    note: '',
  },
  {
    id: 13169,
    tvmazeId: '25391',
    title: 'The Return of the Psammead',
    network: 'BBC One',
    startYear: 1993,
    years: '1993',
    genres: ['Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/98/246870.jpg',
    note: '',
  },
  {
    id: 13170,
    tvmazeId: '23977',
    title: 'The Second Half',
    network: 'NBC',
    startYear: 1993,
    years: '1993–1994',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/90/226818.jpg',
    note: '',
  },
  {
    id: 13171,
    tvmazeId: '41839',
    title: 'The Secrets of Lake Success',
    network: 'NBC',
    startYear: 1993,
    years: '1993',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/192/480161.jpg',
    note: '',
  },
  {
    id: 13172,
    tvmazeId: '40704',
    title: 'The Sinbad Show',
    network: 'FOX',
    startYear: 1993,
    years: '1993–1994',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/181/454935.jpg',
    note: '',
  },
  {
    id: 13173,
    tvmazeId: '42480',
    title: 'The Spooks of Bottle Bay',
    network: 'ITV1',
    startYear: 1993,
    years: '1993',
    genres: ['Drama', 'Adventure', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/201/502505.jpg',
    note: '',
  },
  {
    id: 13174,
    tvmazeId: '24009',
    title: 'The Tommyknockers',
    network: 'ABC',
    startYear: 1993,
    years: '1993',
    genres: ['Horror', 'Science-Fiction', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/90/227181.jpg',
    note: '',
  },
  {
    id: 13175,
    tvmazeId: '22535',
    title: 'The Trouble with Larry',
    network: 'CBS',
    startYear: 1993,
    years: '1993',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/359/899425.jpg',
    note: '',
  },
  {
    id: 13176,
    tvmazeId: '11679',
    title: 'The Untouchables',
    network: 'Syndication',
    startYear: 1993,
    years: '1993–1994',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/39/98522.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 549, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
