window.pageShows = [
  {
    id: 9193,
    tvmazeId: '27602',
    title: 'Casualty 1909',
    network: 'BBC One',
    startYear: 2009,
    years: '2009',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/108/272107.jpg',
    note: '',
  },
  {
    id: 9194,
    tvmazeId: '45391',
    title: 'CJ the DJ',
    network: 'ABC',
    startYear: 2009,
    years: '2009–2010',
    genres: ['Comedy', 'Family', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/230/577226.jpg',
    note: '',
  },
  {
    id: 9195,
    tvmazeId: '4211',
    title: 'Collision',
    network: 'ITV1',
    startYear: 2009,
    years: '2009',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/286/715183.jpg',
    note: '',
  },
  {
    id: 9196,
    tvmazeId: '318',
    title: 'Community',
    network: 'Yahoo! View',
    startYear: 2009,
    years: '2009–2015',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: 'NBC/Yahoo gave the show sufficient closure (and a movie was later announced); the study group\'s stories were concluded.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/2/5134.jpg',
    note: '',
  },
  {
    id: 9197,
    tvmazeId: '319',
    title: 'Cougar Town',
    network: 'TBS',
    startYear: 2009,
    years: '2009–2015',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/2/5195.jpg',
    note: '',
  },
  {
    id: 9198,
    tvmazeId: '26010',
    title: 'Cowards',
    network: 'BBC Four',
    startYear: 2009,
    years: '2009',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/125/312682.jpg',
    note: '',
  },
  {
    id: 9199,
    tvmazeId: '16378',
    title: 'Cra$h & Burn',
    network: 'Showcase',
    startYear: 2009,
    years: '2009–2010',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/54/136545.jpg',
    note: '',
  },
  {
    id: 9200,
    tvmazeId: '35527',
    title: 'Crash',
    network: 'BBC One Wales',
    startYear: 2009,
    years: '2009–2010',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/150/375053.jpg',
    note: '',
  },
  {
    id: 9201,
    tvmazeId: '37930',
    title: 'Ctrl',
    network: 'NBC.com',
    startYear: 2009,
    years: '2009',
    genres: ['Comedy', 'Fantasy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/162/406390.jpg',
    note: '',
  },
  {
    id: 9202,
    tvmazeId: '1091',
    title: 'Cupid',
    network: 'ABC',
    startYear: 2009,
    years: '2009',
    genres: ['Drama', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17212.jpg',
    note: '',
  },
  {
    id: 9203,
    tvmazeId: '937',
    title: 'Dark Blue',
    network: 'TNT',
    startYear: 2009,
    years: '2009–2010',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16180.jpg',
    note: '',
  },
  {
    id: 9204,
    tvmazeId: '11288',
    title: 'Dave in the Life',
    network: 'SBS',
    startYear: 2009,
    years: '2009',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/38/95333.jpg',
    note: '',
  },
  {
    id: 9205,
    tvmazeId: '88763',
    title: 'Debbie Macomber\'s Mrs. Miracle',
    network: 'Hallmark Channel',
    startYear: 2009,
    years: '2009–',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/601/1504546.jpg',
    note: '',
  },
  {
    id: 9206,
    tvmazeId: '446',
    title: 'Defying Gravity',
    network: 'CTV',
    startYear: 2009,
    years: '2009',
    genres: ['Drama', 'Science-Fiction', 'Thriller'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/3/9089.jpg',
    note: '',
  },
  {
    id: 9207,
    tvmazeId: '6223',
    title: 'Delocated',
    network: 'Adult Swim',
    startYear: 2009,
    years: '2009–2013',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/59961.jpg',
    note: '',
  },
  {
    id: 9208,
    tvmazeId: '4572',
    title: 'Demons',
    network: 'ITV1',
    startYear: 2009,
    years: '2009',
    genres: ['Drama', 'Action', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/52221.jpg',
    note: '',
  },
  {
    id: 9209,
    tvmazeId: '12217',
    title: 'Dennis the Menace and Gnasher',
    network: 'CBBC',
    startYear: 2009,
    years: '2009–2014',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/535/1338542.jpg',
    note: '',
  },
  {
    id: 9210,
    tvmazeId: '4691',
    title: 'Desperate Romantics',
    network: 'BBC Two',
    startYear: 2009,
    years: '2009',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/52867.jpg',
    note: '',
  },
  {
    id: 9211,
    tvmazeId: '7001',
    title: 'Dexter: Early Cuts',
    network: 'Paramount+ with Showtime',
    startYear: 2009,
    years: '2009–2012',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/65766.jpg',
    note: '',
  },
  {
    id: 9212,
    tvmazeId: '33863',
    title: 'Diamonds',
    network: 'ABC',
    startYear: 2009,
    years: '2009',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/138/345655.jpg',
    note: '',
  },
  {
    id: 9213,
    tvmazeId: '6457',
    title: 'Dinosaur Train',
    network: 'PBS',
    startYear: 2009,
    years: '2009–2020',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/24/61752.jpg',
    note: '',
  },
  {
    id: 9214,
    tvmazeId: '6191',
    title: 'Diplomatic Immunity',
    network: 'TVNZ 1',
    startYear: 2009,
    years: '2009',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/59789.jpg',
    note: '',
  },
  {
    id: 9215,
    tvmazeId: '7287',
    title: 'Dirt Game',
    network: 'ABC',
    startYear: 2009,
    years: '2009',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/151/378537.jpg',
    note: '',
  },
  {
    id: 9216,
    tvmazeId: '30645',
    title: 'DJ & the Fro',
    network: 'MTV',
    startYear: 2009,
    years: '2009',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/121/304011.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 384, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
