window.pageShows = [
  {
    id: 8833,
    tvmazeId: '3134',
    title: 'The Amazing World of Gumball',
    network: 'Cartoon Network',
    startYear: 2011,
    years: '2011–2019',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/17/43096.jpg',
    note: '',
  },
  {
    id: 8834,
    tvmazeId: '1812',
    title: 'The Body Farm',
    network: 'BBC One',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/10/26198.jpg',
    note: '',
  },
  {
    id: 8835,
    tvmazeId: '515',
    title: 'The Borgias',
    network: 'Paramount+ with Showtime',
    startYear: 2011,
    years: '2011–2013',
    genres: ['Drama', 'Romance', 'History'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Showtime cancelled before the planned season four finale; Rodrigo Borgia\'s papal legacy and family schemes were left unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/306/765764.jpg',
    note: '',
  },
  {
    id: 8836,
    tvmazeId: '9041',
    title: 'The Café',
    network: 'Sky Showcase',
    startYear: 2011,
    years: '2011–2013',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/82929.jpg',
    note: '',
  },
  {
    id: 8837,
    tvmazeId: '411',
    title: 'The Cape',
    network: 'NBC',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Crime', 'Supernatural'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'NBC cancelled after one season; Vince Faraday\'s vigilante war against Peter Fleming/Chess was just beginning.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/2/6361.jpg',
    note: '',
  },
  {
    id: 8838,
    tvmazeId: '29257',
    title: 'The Case',
    network: 'BBC One',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 8839,
    tvmazeId: '511',
    title: 'The Chicago Code',
    network: 'FOX',
    startYear: 2011,
    years: '2011',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/4/11142.jpg',
    note: '',
  },
  {
    id: 8840,
    tvmazeId: '4169',
    title: 'The Confession',
    network: 'Hulu',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/50298.jpg',
    note: '',
  },
  {
    id: 8841,
    tvmazeId: '1088',
    title: 'The Crimson Petal and the White',
    network: 'BBC Two',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17200.jpg',
    note: '',
  },
  {
    id: 8842,
    tvmazeId: '43605',
    title: 'The Daly Show',
    network: 'YouTube',
    startYear: 2011,
    years: '2011–2015',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 8843,
    tvmazeId: '25628',
    title: 'The Division',
    network: 'YouTube',
    startYear: 2011,
    years: '2011–2014',
    genres: ['Drama', 'Action', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/99/249615.jpg',
    note: '',
  },
  {
    id: 8844,
    tvmazeId: '352',
    title: 'The Exes',
    network: 'TV Land',
    startYear: 2011,
    years: '2011–2015',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/2/5392.jpg',
    note: '',
  },
  {
    id: 8845,
    tvmazeId: '1100',
    title: 'The Fades',
    network: 'BBC Three',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Thriller', 'Supernatural'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'BBC Three cancelled after one series; Paul\'s angel powers and the Fades\' resurrection plan were mid-arc.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17228.jpg',
    note: '',
  },
  {
    id: 8846,
    tvmazeId: '1439',
    title: 'The Field of Blood',
    network: 'BBC One',
    startYear: 2011,
    years: '2011–2013',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/8/20807.jpg',
    note: '',
  },
  {
    id: 8847,
    tvmazeId: '16856',
    title: 'The Filthy Frank Show',
    network: 'YouTube',
    startYear: 2011,
    years: '2011–2016',
    genres: ['Comedy', 'Adult'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/109/274311.jpg',
    note: '',
  },
  {
    id: 8848,
    tvmazeId: '1023',
    title: 'The Glee Project',
    network: 'Oxygen True Crime',
    startYear: 2011,
    years: '2011–2012',
    genres: ['Drama', 'Family', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16685.jpg',
    note: '',
  },
  {
    id: 8849,
    tvmazeId: '36468',
    title: 'The Gradual Demise of Phillipa Finch',
    network: 'ABC',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/154/385292.jpg',
    note: '',
  },
  {
    id: 8850,
    tvmazeId: '11593',
    title: 'The Hamster Wheel',
    network: 'ABC',
    startYear: 2011,
    years: '2011–2012',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/39/97928.jpg',
    note: '',
  },
  {
    id: 8851,
    tvmazeId: '6235',
    title: 'The Heart, She Holler',
    network: 'Adult Swim',
    startYear: 2011,
    years: '2011–2014',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/59985.jpg',
    note: '',
  },
  {
    id: 8852,
    tvmazeId: '3531',
    title: 'The Heritage of Lancaster County',
    network: 'Hallmark Mystery',
    startYear: 2011,
    years: '2011–2015',
    genres: ['Drama', 'Family', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/56947.jpg',
    note: '',
  },
  {
    id: 8853,
    tvmazeId: '1103',
    title: 'The Hour',
    network: 'BBC Two',
    startYear: 2011,
    years: '2011–2012',
    genres: ['Drama', 'Thriller', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17231.jpg',
    note: '',
  },
  {
    id: 8854,
    tvmazeId: '18453',
    title: 'The Jury',
    network: 'ITV1',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/62/157232.jpg',
    note: '',
  },
  {
    id: 8855,
    tvmazeId: '1238',
    title: 'The Kennedys',
    network: 'REELZ',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/17745.jpg',
    note: '',
  },
  {
    id: 8856,
    tvmazeId: '35',
    title: 'The Killing',
    network: 'AMC',
    startYear: 2011,
    years: '2011–2014',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: 'Netflix/AMC gave the show a proper conclusion after four seasons, solving the Rosie Larsen case.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/216/540157.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 369, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
