window.pageShows = [
  {
    id: 7249,
    tvmazeId: '5033',
    title: 'The Trip',
    network: 'Now',
    startYear: 2010,
    years: '2010–',
    genres: ['Comedy', 'Food', 'Travel'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/54269.jpg',
    note: '',
  },
  {
    id: 7250,
    tvmazeId: '42765',
    title: 'The Twisted Whiskers Show',
    network: 'Discovery Family',
    startYear: 2010,
    years: '2010',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/203/508067.jpg',
    note: '',
  },
  {
    id: 7251,
    tvmazeId: '73',
    title: 'The Walking Dead',
    network: 'AMC+',
    startYear: 2010,
    years: '2010–2022',
    genres: ['Drama', 'Action', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/424/1061900.jpg',
    note: '',
  },
  {
    id: 7252,
    tvmazeId: '1338',
    title: 'The Whole Truth',
    network: 'ABC',
    startYear: 2010,
    years: '2010',
    genres: ['Drama', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/18622.jpg',
    note: '',
  },
  {
    id: 7253,
    tvmazeId: '1887',
    title: 'This is England',
    network: 'Channel 4',
    startYear: 2010,
    years: '2010–2015',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/27594.jpg',
    note: '',
  },
  {
    id: 7254,
    tvmazeId: '3088',
    title: 'This is Not My Life',
    network: 'TVNZ 1',
    startYear: 2010,
    years: '2010',
    genres: ['Drama', 'Science-Fiction', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/251/628523.jpg',
    note: '',
  },
  {
    id: 7255,
    tvmazeId: '8085',
    title: 'Thorne',
    network: 'Sky Showcase',
    startYear: 2010,
    years: '2010',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/73486.jpg',
    note: '',
  },
  {
    id: 7256,
    tvmazeId: '14400',
    title: 'Tinga Tinga Tales',
    network: 'CBeebies',
    startYear: 2010,
    years: '2010–2011',
    genres: ['Children', 'Nature'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/532/1330472.jpg',
    note: '',
  },
  {
    id: 7257,
    tvmazeId: '3463',
    title: 'Todd & The Book of Pure Evil',
    network: 'CTV Sci-Fi Channel',
    startYear: 2010,
    years: '2010–2012',
    genres: ['Comedy', 'Fantasy', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/45520.jpg',
    note: '',
  },
  {
    id: 7258,
    tvmazeId: '4103',
    title: 'Tower Prep',
    network: 'Cartoon Network',
    startYear: 2010,
    years: '2010',
    genres: ['Drama', 'Fantasy', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/302/755440.jpg',
    note: '',
  },
  {
    id: 7259,
    tvmazeId: '28892',
    title: 'Tracy Beaker Returns',
    network: 'CBBC',
    startYear: 2010,
    years: '2010–2012',
    genres: ['Drama', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/115/287773.jpg',
    note: '',
  },
  {
    id: 7260,
    tvmazeId: '5823',
    title: 'Transformers: Prime',
    network: 'Discovery Family',
    startYear: 2010,
    years: '2010–2013',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/397/994964.jpg',
    note: '',
  },
  {
    id: 7261,
    tvmazeId: '840',
    title: 'Treme',
    network: 'HBO',
    startYear: 2010,
    years: '2010–2013',
    genres: ['Drama', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/173/433306.jpg',
    note: '',
  },
  {
    id: 7262,
    tvmazeId: '34628',
    title: 'Tyranny',
    network: 'YouTube',
    startYear: 2010,
    years: '2010–2011',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/144/360549.jpg',
    note: '',
  },
  {
    id: 7263,
    tvmazeId: '4323',
    title: 'Ugly Americans',
    network: 'Comedy Central',
    startYear: 2010,
    years: '2010–2012',
    genres: ['Comedy', 'Fantasy', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/328/820604.jpg',
    note: '',
  },
  {
    id: 7264,
    tvmazeId: '1012',
    title: 'Undercovers',
    network: 'NBC',
    startYear: 2010,
    years: '2010',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16624.jpg',
    note: '',
  },
  {
    id: 7265,
    tvmazeId: '4527',
    title: 'Unnatural History',
    network: 'Cartoon Network',
    startYear: 2010,
    years: '2010',
    genres: ['Action', 'Adventure', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/52065.jpg',
    note: '',
  },
  {
    id: 7266,
    tvmazeId: '1047',
    title: 'Upstairs Downstairs',
    network: 'BBC One',
    startYear: 2010,
    years: '2010–2012',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16943.jpg',
    note: '',
  },
  {
    id: 7267,
    tvmazeId: '7258',
    title: 'Vexed',
    network: 'BBC Two',
    startYear: 2010,
    years: '2010–2012',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/67557.jpg',
    note: '',
  },
  {
    id: 7268,
    tvmazeId: '2189',
    title: 'Victorious',
    network: 'Nickelodeon',
    startYear: 2010,
    years: '2010–2013',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/441/1102783.jpg',
    note: '',
  },
  {
    id: 7269,
    tvmazeId: '54801',
    title: 'Wakkaville',
    network: 'Nine Network',
    startYear: 2010,
    years: '2010–2012',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/539/1348089.jpg',
    note: '',
  },
  {
    id: 7270,
    tvmazeId: '9875',
    title: 'Wallace & Gromit\'s World of Invention',
    network: 'BBC One',
    startYear: 2010,
    years: '2010',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/84957.jpg',
    note: '',
  },
  {
    id: 7271,
    tvmazeId: '27400',
    title: 'WANNA-BEn',
    network: 'Three',
    startYear: 2010,
    years: '2010–2012',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/107/269900.jpg',
    note: '',
  },
  {
    id: 7272,
    tvmazeId: '4153',
    title: 'Warren the Ape',
    network: 'MTV',
    startYear: 2010,
    years: '2010',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/50223.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 303, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 824, "cliffhanger": 237, "ended": 13574}};
