window.pageShows = [
  {
    id: 16753,
    tvmazeId: '35642',
    title: 'Benny Hill',
    network: 'BBC One',
    startYear: 1962,
    years: '1962–1963',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 16754,
    tvmazeId: '3653',
    title: 'City Beneath the Sea',
    network: 'ITV1',
    startYear: 1962,
    years: '1962',
    genres: ['Drama', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/47302.jpg',
    note: '',
  },
  {
    id: 16755,
    tvmazeId: '1462',
    title: 'Combat!',
    network: 'ABC',
    startYear: 1962,
    years: '1962–1967',
    genres: ['Drama', 'Action', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/80/202316.jpg',
    note: '',
  },
  {
    id: 16756,
    tvmazeId: '56285',
    title: 'Don\'t Call Me Charlie!',
    network: 'NBC',
    startYear: 1962,
    years: '1962–1963',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/442/1106813.jpg',
    note: '',
  },
  {
    id: 16757,
    tvmazeId: '11343',
    title: 'Dr. Finlay\'s Casebook',
    network: 'BBC One',
    startYear: 1962,
    years: '1962–1971',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/38/95801.jpg',
    note: '',
  },
  {
    id: 16758,
    tvmazeId: '3529',
    title: 'Empire',
    network: 'NBC',
    startYear: 1962,
    years: '1962–1963',
    genres: ['Drama', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/302/755423.jpg',
    note: '',
  },
  {
    id: 16759,
    tvmazeId: '25235',
    title: 'Ensign O\'Toole',
    network: 'NBC',
    startYear: 1962,
    years: '1962–1963',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/97/244501.jpg',
    note: '',
  },
  {
    id: 16760,
    tvmazeId: '73855',
    title: 'Fair Exchange',
    network: 'CBS',
    startYear: 1962,
    years: '1962',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 16761,
    tvmazeId: '5916',
    title: 'Fireball XL5',
    network: 'ITV1',
    startYear: 1962,
    years: '1962–1963',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/250/627094.jpg',
    note: '',
  },
  {
    id: 16762,
    tvmazeId: '46566',
    title: 'Going My Way',
    network: 'ABC',
    startYear: 1962,
    years: '1962–1963',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 16763,
    tvmazeId: '11422',
    title: 'Hugh and I',
    network: 'BBC One',
    startYear: 1962,
    years: '1962–1967',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/38/96324.jpg',
    note: '',
  },
  {
    id: 16764,
    tvmazeId: '6271',
    title: 'I\'m Dickens... He\'s Fenster',
    network: 'ABC',
    startYear: 1962,
    years: '1962–1963',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/24/60243.jpg',
    note: '',
  },
  {
    id: 16765,
    tvmazeId: '44194',
    title: 'It\'s a Man\'s World',
    network: 'NBC',
    startYear: 1962,
    years: '1962–1963',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/382/955077.jpg',
    note: '',
  },
  {
    id: 16766,
    tvmazeId: '38313',
    title: 'Lippy the Lion and Hardy Har Har',
    network: 'Syndication',
    startYear: 1962,
    years: '1962–1963',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/164/412469.jpg',
    note: '',
  },
  {
    id: 16767,
    tvmazeId: '40981',
    title: 'Man of the World',
    network: 'ITV1',
    startYear: 1962,
    years: '1962–1963',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/183/459570.jpg',
    note: '',
  },
  {
    id: 16768,
    tvmazeId: '6269',
    title: 'McHale\'s Navy',
    network: 'ABC',
    startYear: 1962,
    years: '1962–1966',
    genres: ['Comedy', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/24/60229.jpg',
    note: '',
  },
  {
    id: 16769,
    tvmazeId: '74279',
    title: 'McKeever and the Colonel',
    network: 'NBC',
    startYear: 1962,
    years: '1962–1963',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/501/1254112.jpg',
    note: '',
  },
  {
    id: 16770,
    tvmazeId: '74691',
    title: 'Mr. Smith Goes to Washington',
    network: 'ABC',
    startYear: 1962,
    years: '1962–1963',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 16771,
    tvmazeId: '45245',
    title: 'Oliver Twist',
    network: 'BBC One',
    startYear: 1962,
    years: '1962',
    genres: ['Drama', 'Adventure', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 16772,
    tvmazeId: '16829',
    title: 'Out of This World',
    network: 'ITV1',
    startYear: 1962,
    years: '1962',
    genres: ['Drama', 'Science-Fiction', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/56/140598.jpg',
    note: '',
  },
  {
    id: 16773,
    tvmazeId: '72022',
    title: 'Richard the Lionheart',
    network: 'ITV1',
    startYear: 1962,
    years: '1962–1963',
    genres: ['Action', 'Adventure', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/481/1204395.jpg',
    note: '',
  },
  {
    id: 16774,
    tvmazeId: '74734',
    title: 'Room for One More',
    network: 'ABC',
    startYear: 1962,
    years: '1962',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 16775,
    tvmazeId: '79664',
    title: 'Saints and Sinners',
    network: 'NBC',
    startYear: 1962,
    years: '1962–1963',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/536/1340595.jpg',
    note: '',
  },
  {
    id: 16776,
    tvmazeId: '28664',
    title: 'Sam Benedict',
    network: 'NBC',
    startYear: 1962,
    years: '1962–1963',
    genres: ['Drama', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/114/285558.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 699, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
