window.pageShows = [
  {
    id: 14069,
    tvmazeId: '13344',
    title: 'Filthy Rich & Catflap',
    network: 'BBC Two',
    startYear: 1987,
    years: '1987',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/121/304354.jpg',
    note: '',
  },
  {
    id: 14070,
    tvmazeId: '8207',
    title: 'Fireman Sam',
    network: 'Cartoonito',
    startYear: 1987,
    years: '1987–',
    genres: ['Comedy', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/542/1356056.jpg',
    note: '',
  },
  {
    id: 14071,
    tvmazeId: '51392',
    title: 'Floodtide',
    network: 'ITV1',
    startYear: 1987,
    years: '1987–1988',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/279/697748.jpg',
    note: '',
  },
  {
    id: 14072,
    tvmazeId: '59104',
    title: 'Foreign Bodies',
    network: 'BBC Two',
    startYear: 1987,
    years: '1987–1989',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14073,
    tvmazeId: '18803',
    title: 'Fortunes of War',
    network: 'BBC One',
    startYear: 1987,
    years: '1987',
    genres: ['Drama', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/64/162471.jpg',
    note: '',
  },
  {
    id: 14074,
    tvmazeId: '52033',
    title: 'Fraggle Rock: The Animated Series',
    network: 'NBC',
    startYear: 1987,
    years: '1987',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/289/722620.jpg',
    note: '',
  },
  {
    id: 14075,
    tvmazeId: '13427',
    title: 'Frank\'s Place',
    network: 'CBS',
    startYear: 1987,
    years: '1987–1988',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/46/116153.jpg',
    note: '',
  },
  {
    id: 14076,
    tvmazeId: '8692',
    title: 'French and Saunders',
    network: 'BBC Two',
    startYear: 1987,
    years: '1987–2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/30/77259.jpg',
    note: '',
  },
  {
    id: 14077,
    tvmazeId: '3573',
    title: 'Friday the 13th: The Series',
    network: 'Syndication',
    startYear: 1987,
    years: '1987–1990',
    genres: ['Drama', 'Fantasy', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/46790.jpg',
    note: '',
  },
  {
    id: 14078,
    tvmazeId: '1251',
    title: 'Full House',
    network: 'ABC',
    startYear: 1987,
    years: '1987–1995',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/17933.jpg',
    note: '',
  },
  {
    id: 14079,
    tvmazeId: '4520',
    title: 'Good Morning Miss Bliss',
    network: 'Disney Channel',
    startYear: 1987,
    years: '1987–1989',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/52054.jpg',
    note: '',
  },
  {
    id: 14080,
    tvmazeId: '41778',
    title: 'Hard Knocks',
    network: 'Paramount+ with Showtime',
    startYear: 1987,
    years: '1987',
    genres: ['Drama', 'Comedy', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/379/949212.jpg',
    note: '',
  },
  {
    id: 14081,
    tvmazeId: '38499',
    title: 'Hardwicke House',
    network: 'ITV1',
    startYear: 1987,
    years: '1987',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/430/1076701.jpg',
    note: '',
  },
  {
    id: 14082,
    tvmazeId: '65174',
    title: 'Harry',
    network: 'ABC',
    startYear: 1987,
    years: '1987',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14083,
    tvmazeId: '70979',
    title: 'HBO Storybook Musicals',
    network: 'HBO',
    startYear: 1987,
    years: '1987–1993',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/475/1188000.jpg',
    note: '',
  },
  {
    id: 14084,
    tvmazeId: '27775',
    title: 'Hello Kitty\'s Furry Tale Theater',
    network: 'CBS',
    startYear: 1987,
    years: '1987',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/109/274918.jpg',
    note: '',
  },
  {
    id: 14085,
    tvmazeId: '72622',
    title: 'Hey Dad',
    network: '7plus',
    startYear: 1987,
    years: '1987–1994',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/486/1215472.jpg',
    note: '',
  },
  {
    id: 14086,
    tvmazeId: '79909',
    title: 'High & Dry',
    network: 'ITV1',
    startYear: 1987,
    years: '1987',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14087,
    tvmazeId: '36074',
    title: 'High Mountain Rangers',
    network: 'CBS',
    startYear: 1987,
    years: '1987–1988',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/152/381948.jpg',
    note: '',
  },
  {
    id: 14088,
    tvmazeId: '8718',
    title: 'Home James!',
    network: 'ITV1',
    startYear: 1987,
    years: '1987–1990',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/77705.jpg',
    note: '',
  },
  {
    id: 14089,
    tvmazeId: '4668',
    title: 'Hooperman',
    network: 'ABC',
    startYear: 1987,
    years: '1987–1989',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/52768.jpg',
    note: '',
  },
  {
    id: 14090,
    tvmazeId: '24649',
    title: 'Houston Knights',
    network: 'CBS',
    startYear: 1987,
    years: '1987–1988',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/94/235545.jpg',
    note: '',
  },
  {
    id: 14091,
    tvmazeId: '65175',
    title: 'I Married Dora',
    network: 'ABC',
    startYear: 1987,
    years: '1987',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/569/1422974.jpg',
    note: '',
  },
  {
    id: 14092,
    tvmazeId: '28610',
    title: 'I\'ll Take Manhattan',
    network: 'CBS',
    startYear: 1987,
    years: '1987',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/113/284673.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 587, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
