window.pageShows = [
  {
    id: 3965,
    tvmazeId: '46710',
    title: 'JoJo & Gran Gran',
    network: 'BBC iPlayer',
    startYear: 2020,
    years: '2020–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/381/952865.jpg',
    note: '',
  },
  {
    id: 3966,
    tvmazeId: '48016',
    title: 'JU-ON: Origins',
    network: 'Netflix',
    startYear: 2020,
    years: '2020',
    genres: ['Horror', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/263/659927.jpg',
    note: '',
  },
  {
    id: 3967,
    tvmazeId: '49308',
    title: 'Julie and the Phantoms',
    network: 'Netflix',
    startYear: 2020,
    years: '2020',
    genres: ['Comedy', 'Music', 'Supernatural'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/269/674832.jpg',
    note: '',
  },
  {
    id: 3968,
    tvmazeId: '42435',
    title: 'Jurassic World: Camp Cretaceous',
    network: 'Netflix',
    startYear: 2020,
    years: '2020–2022',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/374/936975.jpg',
    note: '',
  },
  {
    id: 3969,
    tvmazeId: '45897',
    title: 'Just Add Magic: Mystery City',
    network: 'Prime Video',
    startYear: 2020,
    years: '2020–2020',
    genres: ['Adventure', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/236/591129.jpg',
    note: '',
  },
  {
    id: 3970,
    tvmazeId: '45875',
    title: 'Kalifat',
    network: 'SVT Play',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/236/591128.jpg',
    note: '',
  },
  {
    id: 3971,
    tvmazeId: '62541',
    title: 'Kangaroo Beach',
    network: 'ABC Kids',
    startYear: 2020,
    years: '2020–',
    genres: ['Comedy', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/413/1032971.jpg',
    note: '',
  },
  {
    id: 3972,
    tvmazeId: '56505',
    title: 'Kappa Kappa Die',
    network: 'CW Seed',
    startYear: 2020,
    years: '2020',
    genres: ['Comedy', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/402/1005268.jpg',
    note: '',
  },
  {
    id: 3973,
    tvmazeId: '46601',
    title: 'Kate & Koji',
    network: 'ITV1',
    startYear: 2020,
    years: '2020–2022',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/599/1498112.jpg',
    note: '',
  },
  {
    id: 3974,
    tvmazeId: '40541',
    title: 'Katy Keene',
    network: 'The CW',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Comedy', 'Music'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/235/587788.jpg',
    note: '',
  },
  {
    id: 3975,
    tvmazeId: '69858',
    title: 'Khloe',
    network: 'meWATCH',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Comedy', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/468/1171166.jpg',
    note: '',
  },
  {
    id: 3976,
    tvmazeId: '51463',
    title: 'Kinderfänger',
    network: 'Facebook Watch',
    startYear: 2020,
    years: '2020–2021',
    genres: ['Horror', 'Supernatural'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/280/701241.jpg',
    note: '',
  },
  {
    id: 3977,
    tvmazeId: '45487',
    title: 'King Gary',
    network: 'BBC iPlayer',
    startYear: 2020,
    years: '2020–2021',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/235/588171.jpg',
    note: '',
  },
  {
    id: 3978,
    tvmazeId: '51914',
    title: 'Kings of Jo\'Burg',
    network: 'Netflix',
    startYear: 2020,
    years: '2020–',
    genres: ['Drama', 'Crime', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/286/716265.jpg',
    note: '',
  },
  {
    id: 3979,
    tvmazeId: '42593',
    title: 'Kipo and the Age of Wonderbeasts',
    network: 'Netflix',
    startYear: 2020,
    years: '2020',
    genres: ['Adventure', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: 'Netflix gave the show a three-season planned conclusion.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/272/682154.jpg',
    note: '',
  },
  {
    id: 3980,
    tvmazeId: '43590',
    title: 'Kärlek & Anarki',
    network: 'Netflix',
    startYear: 2020,
    years: '2020–2022',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/282/705004.jpg',
    note: '',
  },
  {
    id: 3981,
    tvmazeId: '51285',
    title: 'La Flamme',
    network: 'Canal+',
    startYear: 2020,
    years: '2020',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/278/696199.jpg',
    note: '',
  },
  {
    id: 3982,
    tvmazeId: '46588',
    title: 'La Jauría',
    network: 'Prime Video',
    startYear: 2020,
    years: '2020–2022',
    genres: ['Drama', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/264/661847.jpg',
    note: '',
  },
  {
    id: 3983,
    tvmazeId: '51475',
    title: 'La reina de Indias y el conquistador',
    network: 'Netflix',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Romance', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/281/702605.jpg',
    note: '',
  },
  {
    id: 3984,
    tvmazeId: '45895',
    title: 'La Révolution',
    network: 'Netflix',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/274/687135.jpg',
    note: '',
  },
  {
    id: 3985,
    tvmazeId: '51816',
    title: 'LEGO Marvel Avengers: Climate Conundrum',
    network: 'Disney Channel',
    startYear: 2020,
    years: '2020',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/282/705195.jpg',
    note: '',
  },
  {
    id: 3986,
    tvmazeId: '58890',
    title: 'LEGO Monkie Kid',
    network: 'TV3',
    startYear: 2020,
    years: '2020–2024',
    genres: ['Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/408/1020941.jpg',
    note: '',
  },
  {
    id: 3987,
    tvmazeId: '49749',
    title: 'Life',
    network: 'BBC iPlayer',
    startYear: 2020,
    years: '2020',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: 'BBC One 6-episode mini-series by Mike Bartlett; told a complete story about four housemates in Manchester.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/268/670996.jpg',
    note: '',
  },
  {
    id: 3988,
    tvmazeId: '58905',
    title: 'Life & Rhymes',
    network: 'Sky Arts',
    startYear: 2020,
    years: '2020–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/483/1208470.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 166, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
