window.pageShows = [
  {
    id: 15049,
    tvmazeId: '24108',
    title: 'Love, Sidney',
    network: 'NBC',
    startYear: 1981,
    years: '1981–1983',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/91/228349.jpg',
    note: '',
  },
  {
    id: 15050,
    tvmazeId: '65011',
    title: 'Maggie',
    network: 'ABC',
    startYear: 1981,
    years: '1981–1982',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/429/1074092.jpg',
    note: '',
  },
  {
    id: 15051,
    tvmazeId: '8263',
    title: 'Masada',
    network: 'ABC',
    startYear: 1981,
    years: '1981',
    genres: ['Drama', 'Action', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/74629.jpg',
    note: '',
  },
  {
    id: 15052,
    tvmazeId: '62705',
    title: 'McClain\'s Law',
    network: 'NBC',
    startYear: 1981,
    years: '1981–1982',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/413/1034445.jpg',
    note: '',
  },
  {
    id: 15053,
    tvmazeId: '22675',
    title: 'Mr. Merlin',
    network: 'CBS',
    startYear: 1981,
    years: '1981–1982',
    genres: ['Comedy', 'Family', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/83/209845.jpg',
    note: '',
  },
  {
    id: 15054,
    tvmazeId: '32391',
    title: 'Nanny',
    network: 'BBC One',
    startYear: 1981,
    years: '1981–1983',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/129/323544.jpg',
    note: '',
  },
  {
    id: 15055,
    tvmazeId: '7735',
    title: 'Never the Twain',
    network: 'ITV1',
    startYear: 1981,
    years: '1981–1991',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/71145.jpg',
    note: '',
  },
  {
    id: 15056,
    tvmazeId: '83198',
    title: 'Now for Nookie',
    network: 'ITV1',
    startYear: 1981,
    years: '1981',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 15057,
    tvmazeId: '65012',
    title: 'Nurse',
    network: 'CBS',
    startYear: 1981,
    years: '1981–1982',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/588/1470028.jpg',
    note: '',
  },
  {
    id: 15058,
    tvmazeId: '2094',
    title: 'Only Fools and Horses',
    network: 'BBC One',
    startYear: 1981,
    years: '1981–2003',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/29077.jpg',
    note: '',
  },
  {
    id: 15059,
    tvmazeId: '65033',
    title: 'Open All Night',
    network: 'ABC',
    startYear: 1981,
    years: '1981–1982',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 15060,
    tvmazeId: '56544',
    title: 'Peter and Paul',
    network: 'CBS',
    startYear: 1981,
    years: '1981',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/343/857656.jpg',
    note: '',
  },
  {
    id: 15061,
    tvmazeId: '9550',
    title: 'Pigeon Street',
    network: 'BBC One',
    startYear: 1981,
    years: '1981',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/83500.jpg',
    note: '',
  },
  {
    id: 15062,
    tvmazeId: '9551',
    title: 'Postman Pat',
    network: 'CBeebies',
    startYear: 1981,
    years: '1981–2017',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/83501.jpg',
    note: '',
  },
  {
    id: 15063,
    tvmazeId: '10052',
    title: 'Private Benjamin',
    network: 'CBS',
    startYear: 1981,
    years: '1981–1983',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/34/85876.jpg',
    note: '',
  },
  {
    id: 15064,
    tvmazeId: '22970',
    title: 'Private Schulz',
    network: 'BBC Two',
    startYear: 1981,
    years: '1981',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/85/212948.jpg',
    note: '',
  },
  {
    id: 15065,
    tvmazeId: '10176',
    title: 'Rex Stout\'s Nero Wolfe',
    network: 'NBC',
    startYear: 1981,
    years: '1981',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/475/1188035.jpg',
    note: '',
  },
  {
    id: 15066,
    tvmazeId: '52157',
    title: 'Riker',
    network: 'CBS',
    startYear: 1981,
    years: '1981',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/285/714818.jpg',
    note: '',
  },
  {
    id: 15067,
    tvmazeId: '79708',
    title: 'Roger Doesn\'t Live Here Anymore',
    network: 'BBC Two',
    startYear: 1981,
    years: '1981',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 15068,
    tvmazeId: '15349',
    title: 'SCTV Network 90',
    network: 'NBC',
    startYear: 1981,
    years: '1981–1983',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/52/130369.jpg',
    note: '',
  },
  {
    id: 15069,
    tvmazeId: '57449',
    title: 'Seconds Out',
    network: 'BBC One',
    startYear: 1981,
    years: '1981–1982',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/355/888848.jpg',
    note: '',
  },
  {
    id: 15070,
    tvmazeId: '10859',
    title: 'Seeing Things',
    network: 'CBC',
    startYear: 1981,
    years: '1981–1987',
    genres: ['Comedy', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/36/91464.jpg',
    note: '',
  },
  {
    id: 15071,
    tvmazeId: '51625',
    title: 'Sense and Sensibility',
    network: 'BBC One',
    startYear: 1981,
    years: '1981',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/280/701302.jpg',
    note: '',
  },
  {
    id: 15072,
    tvmazeId: '18969',
    title: 'Shannon',
    network: 'CBS',
    startYear: 1981,
    years: '1981–1982',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/417/1044784.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 628, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
