window.pageShows = [
  {
    id: 9337,
    tvmazeId: '27987',
    title: 'Jimmy Two-Shoes',
    network: 'Cartoon Network',
    startYear: 2009,
    years: '2009–2012',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/110/276918.jpg',
    note: '',
  },
  {
    id: 9338,
    tvmazeId: '87255',
    title: 'Jinx',
    network: 'CBBC',
    startYear: 2009,
    years: '2009',
    genres: ['Comedy', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/588/1471544.jpg',
    note: '',
  },
  {
    id: 9339,
    tvmazeId: '2096',
    title: 'JONAS',
    network: 'Disney Channel',
    startYear: 2009,
    years: '2009–2010',
    genres: ['Comedy', 'Family', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/44/111130.jpg',
    note: '',
  },
  {
    id: 9340,
    tvmazeId: '11379',
    title: 'Jungle Junction',
    network: 'Disney Channel',
    startYear: 2009,
    years: '2009–2012',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/115/289226.jpg',
    note: '',
  },
  {
    id: 9341,
    tvmazeId: '8394',
    title: 'K9',
    network: 'Network 10',
    startYear: 2009,
    years: '2009–2010',
    genres: ['Adventure', 'Family', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/30/75271.jpg',
    note: '',
  },
  {
    id: 9342,
    tvmazeId: '26711',
    title: 'Kamen Rider: Dragon Knight',
    network: 'The CW',
    startYear: 2009,
    years: '2009–2010',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/105/262950.jpg',
    note: '',
  },
  {
    id: 9343,
    tvmazeId: '1110',
    title: 'Kings',
    network: 'NBC',
    startYear: 2009,
    years: '2009',
    genres: ['Drama', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'NBC cancelled after one season; David\'s rise to challenge King Silas in the allegorical kingdom of Gilboa was unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17235.jpg',
    note: '',
  },
  {
    id: 9344,
    tvmazeId: '23242',
    title: 'Knights of Bloodsteel',
    network: 'Syfy',
    startYear: 2009,
    years: '2009',
    genres: ['Drama', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/87/217777.jpg',
    note: '',
  },
  {
    id: 9345,
    tvmazeId: '1147',
    title: 'Kröd Mändoon and the Flaming Sword of Fire',
    network: 'Comedy Central',
    startYear: 2009,
    years: '2009',
    genres: ['Comedy', 'Action', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/326/816187.jpg',
    note: '',
  },
  {
    id: 9346,
    tvmazeId: '30100',
    title: 'Kung Fu Dino Posse',
    network: 'CITV',
    startYear: 2009,
    years: '2009',
    genres: ['Comedy', 'Action', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/119/298062.jpg',
    note: '',
  },
  {
    id: 9347,
    tvmazeId: '62529',
    title: 'L\'École du pouvoir',
    network: 'Canal+',
    startYear: 2009,
    years: '2009',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/413/1032544.jpg',
    note: '',
  },
  {
    id: 9348,
    tvmazeId: '11166',
    title: 'Ladies of Letters',
    network: 'ITV3',
    startYear: 2009,
    years: '2009–2010',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/37/93678.jpg',
    note: '',
  },
  {
    id: 9349,
    tvmazeId: '7827',
    title: 'Land Girls',
    network: 'BBC One',
    startYear: 2009,
    years: '2009–2011',
    genres: ['Drama', 'Romance', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/71862.jpg',
    note: '',
  },
  {
    id: 9350,
    tvmazeId: '1262',
    title: 'Law & Order: UK',
    network: 'ITV1',
    startYear: 2009,
    years: '2009–2014',
    genres: ['Drama', 'Crime', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/334/836812.jpg',
    note: '',
  },
  {
    id: 9351,
    tvmazeId: '12470',
    title: 'League of Super Evil',
    network: 'YTV',
    startYear: 2009,
    years: '2009–2012',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/42/106405.jpg',
    note: '',
  },
  {
    id: 9352,
    tvmazeId: '79395',
    title: 'Let\'s Go Pocoyo',
    network: 'Disney Channel',
    startYear: 2009,
    years: '2009–2010',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/534/1335366.jpg',
    note: '',
  },
  {
    id: 9353,
    tvmazeId: '520',
    title: 'Lie to Me*',
    network: 'FOX',
    startYear: 2009,
    years: '2009–2011',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/4/11275.jpg',
    note: '',
  },
  {
    id: 9354,
    tvmazeId: '10967',
    title: 'Life of Riley',
    network: 'BBC One',
    startYear: 2009,
    years: '2009–2011',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/36/92323.jpg',
    note: '',
  },
  {
    id: 9355,
    tvmazeId: '4630',
    title: 'Life on Top',
    network: 'Cinemax',
    startYear: 2009,
    years: '2009–2011',
    genres: ['Drama', 'Romance', 'Adult'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/52516.jpg',
    note: '',
  },
  {
    id: 9356,
    tvmazeId: '13842',
    title: 'Limmy\'s Show',
    network: 'BBC Two Scotland',
    startYear: 2009,
    years: '2009–2013',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/47/118861.jpg',
    note: '',
  },
  {
    id: 9357,
    tvmazeId: '4407',
    title: 'Lingerie',
    network: 'Cinemax',
    startYear: 2009,
    years: '2009–2011',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/51715.jpg',
    note: '',
  },
  {
    id: 9358,
    tvmazeId: '69215',
    title: 'Little Monk',
    network: 'USA Network',
    startYear: 2009,
    years: '2009',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/464/1161502.jpg',
    note: '',
  },
  {
    id: 9359,
    tvmazeId: '28310',
    title: 'Llamas with Hats',
    network: 'YouTube',
    startYear: 2009,
    years: '2009–2015',
    genres: ['Drama', 'Comedy', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/112/281095.jpg',
    note: '',
  },
  {
    id: 9360,
    tvmazeId: '53409',
    title: 'Lost: Untangled',
    network: 'ABC.com',
    startYear: 2009,
    years: '2009–2010',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/295/739835.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 390, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
