window.pageShows = [
  {
    id: 16369,
    tvmazeId: '15060',
    title: 'Gazette',
    network: 'ITV1',
    startYear: 1968,
    years: '1968',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/51/128123.jpg',
    note: '',
  },
  {
    id: 16370,
    tvmazeId: '962',
    title: 'Hawaii Five-O',
    network: 'CBS',
    startYear: 1968,
    years: '1968–1980',
    genres: ['Action', 'Adventure', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16397.jpg',
    note: '',
  },
  {
    id: 16371,
    tvmazeId: '3359',
    title: 'Here Come the Brides',
    network: 'ABC',
    startYear: 1968,
    years: '1968–1970',
    genres: ['Comedy', 'Adventure', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/17/44289.jpg',
    note: '',
  },
  {
    id: 16372,
    tvmazeId: '14149',
    title: 'Here\'s Lucy',
    network: 'CBS',
    startYear: 1968,
    years: '1968–1974',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/48/120797.jpg',
    note: '',
  },
  {
    id: 16373,
    tvmazeId: '5518',
    title: 'It Takes a Thief',
    network: 'ABC',
    startYear: 1968,
    years: '1968–1970',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/56143.jpg',
    note: '',
  },
  {
    id: 16374,
    tvmazeId: '5918',
    title: 'Joe 90',
    network: 'ITV1',
    startYear: 1968,
    years: '1968–1969',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/58450.jpg',
    note: '',
  },
  {
    id: 16375,
    tvmazeId: '15059',
    title: 'Journey to the Unknown',
    network: 'ABC',
    startYear: 1968,
    years: '1968–1969',
    genres: ['Fantasy', 'Science-Fiction', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/51/128122.jpg',
    note: '',
  },
  {
    id: 16376,
    tvmazeId: '24314',
    title: 'Julia',
    network: 'NBC',
    startYear: 1968,
    years: '1968–1971',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/92/231210.jpg',
    note: '',
  },
  {
    id: 16377,
    tvmazeId: '17400',
    title: 'Lancer',
    network: 'CBS',
    startYear: 1968,
    years: '1968–1970',
    genres: ['Drama', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/58/147035.jpg',
    note: '',
  },
  {
    id: 16378,
    tvmazeId: '3498',
    title: 'Land of the Giants',
    network: 'ABC',
    startYear: 1968,
    years: '1968–1970',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/46321.jpg',
    note: '',
  },
  {
    id: 16379,
    tvmazeId: '48313',
    title: 'Marty',
    network: 'BBC Two',
    startYear: 1968,
    years: '1968–1969',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/258/645929.jpg',
    note: '',
  },
  {
    id: 16380,
    tvmazeId: '16573',
    title: 'Mayberry R.F.D.',
    network: 'CBS',
    startYear: 1968,
    years: '1968–1971',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/55/138069.jpg',
    note: '',
  },
  {
    id: 16381,
    tvmazeId: '53372',
    title: 'Micro Ventures',
    network: 'NBC',
    startYear: 1968,
    years: '1968',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/295/739462.jpg',
    note: '',
  },
  {
    id: 16382,
    tvmazeId: '7223',
    title: 'Mister Rogers\' Neighborhood',
    network: 'PBS',
    startYear: 1968,
    years: '1968–2001',
    genres: ['Family', 'Fantasy', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/67175.jpg',
    note: '',
  },
  {
    id: 16383,
    tvmazeId: '42510',
    title: 'Mum\'s Boys',
    network: 'BBC One',
    startYear: 1968,
    years: '1968',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 16384,
    tvmazeId: '10948',
    title: 'Nearest and Dearest',
    network: 'ITV1',
    startYear: 1968,
    years: '1968–1973',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/282/706181.jpg',
    note: '',
  },
  {
    id: 16385,
    tvmazeId: '21046',
    title: 'Never a Cross Word',
    network: 'London Weekend Television',
    startYear: 1968,
    years: '1968–1970',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/437/1092596.jpg',
    note: '',
  },
  {
    id: 16386,
    tvmazeId: '40929',
    title: 'Oh Brother!',
    network: 'BBC One',
    startYear: 1968,
    years: '1968–1970',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/183/458490.jpg',
    note: '',
  },
  {
    id: 16387,
    tvmazeId: '5910',
    title: 'One Life to Live',
    network: 'ABC',
    startYear: 1968,
    years: '1968–2012',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/58433.jpg',
    note: '',
  },
  {
    id: 16388,
    tvmazeId: '5976',
    title: 'Please Sir!',
    network: 'London Weekend Television',
    startYear: 1968,
    years: '1968–1972',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/58736.jpg',
    note: '',
  },
  {
    id: 16389,
    tvmazeId: '35706',
    title: 'Resurrection',
    network: 'BBC Two',
    startYear: 1968,
    years: '1968',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: '',
    note: '',
  },
  {
    id: 16390,
    tvmazeId: '9552',
    title: 'Skippy the Bush Kangaroo',
    network: 'Nine Network',
    startYear: 1968,
    years: '1968–1970',
    genres: ['Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/83508.jpg',
    note: '',
  },
  {
    id: 16391,
    tvmazeId: '8858',
    title: 'That\'s Life',
    network: 'ABC',
    startYear: 1968,
    years: '1968–1969',
    genres: ['Comedy', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/78682.jpg',
    note: '',
  },
  {
    id: 16392,
    tvmazeId: '33618',
    title: 'The Adventures of Batman',
    network: 'CBS',
    startYear: 1968,
    years: '1968–1969',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/136/342479.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 683, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
