window.pageShows = [
  {
    id: 7633,
    tvmazeId: '2710',
    title: 'Playing House',
    network: 'USA Network',
    startYear: 2014,
    years: '2014–2017',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/117/294873.jpg',
    note: '',
  },
  {
    id: 7634,
    tvmazeId: '9888',
    title: 'Plonk',
    network: 'Stan',
    startYear: 2014,
    years: '2014–2015',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/292/730080.jpg',
    note: '',
  },
  {
    id: 7635,
    tvmazeId: '299',
    title: 'Power',
    network: 'STARZ',
    startYear: 2014,
    years: '2014–2020',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/48/122426.jpg',
    note: '',
  },
  {
    id: 7636,
    tvmazeId: '1790',
    title: 'Prey',
    network: 'ITV1',
    startYear: 2014,
    years: '2014–2015',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/10/25704.jpg',
    note: '',
  },
  {
    id: 7637,
    tvmazeId: '71115',
    title: 'Pride: The Series',
    network: 'Prime Video',
    startYear: 2014,
    years: '2014–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/476/1190795.jpg',
    note: '',
  },
  {
    id: 7638,
    tvmazeId: '9983',
    title: 'Professor Branestawm',
    network: 'BBC One',
    startYear: 2014,
    years: '2014–2015',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/34/85560.jpg',
    note: '',
  },
  {
    id: 7639,
    tvmazeId: '42416',
    title: 'Psi',
    network: 'HBO',
    startYear: 2014,
    years: '2014–2019',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/200/501746.jpg',
    note: '',
  },
  {
    id: 7640,
    tvmazeId: '14007',
    title: 'Puppy Love',
    network: 'BBC Four',
    startYear: 2014,
    years: '2014',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/47/119984.jpg',
    note: '',
  },
  {
    id: 7641,
    tvmazeId: '2360',
    title: 'Quirke',
    network: 'RTÉ ONE',
    startYear: 2014,
    years: '2014',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/12/32141.jpg',
    note: '',
  },
  {
    id: 7642,
    tvmazeId: '895',
    title: 'Rake',
    network: 'FOX',
    startYear: 2014,
    years: '2014',
    genres: ['Drama', 'Comedy', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/15989.jpg',
    note: '',
  },
  {
    id: 7643,
    tvmazeId: '13443',
    title: 'Really',
    network: 'Prime Video',
    startYear: 2014,
    years: '2014',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/46/116263.jpg',
    note: '',
  },
  {
    id: 7644,
    tvmazeId: '897',
    title: 'Reckless',
    network: 'CBS',
    startYear: 2014,
    years: '2014',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/50/125774.jpg',
    note: '',
  },
  {
    id: 7645,
    tvmazeId: '55',
    title: 'Red Band Society',
    network: 'FOX',
    startYear: 2014,
    years: '2014–2015',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/0/441.jpg',
    note: '',
  },
  {
    id: 7646,
    tvmazeId: '3099',
    title: 'Red Oaks',
    network: 'Prime Video',
    startYear: 2014,
    years: '2014–2017',
    genres: ['Drama', 'Comedy', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/131/329842.jpg',
    note: '',
  },
  {
    id: 7647,
    tvmazeId: '1779',
    title: 'Remedy',
    network: 'Global',
    startYear: 2014,
    years: '2014–2015',
    genres: ['Drama', 'Family', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/10/25284.jpg',
    note: '',
  },
  {
    id: 7648,
    tvmazeId: '3397',
    title: 'Remember Me',
    network: 'BBC One',
    startYear: 2014,
    years: '2014',
    genres: ['Drama', 'Horror', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/17/44645.jpg',
    note: '',
  },
  {
    id: 7649,
    tvmazeId: '45527',
    title: 'Rent Controlled',
    network: 'Tello',
    startYear: 2014,
    years: '2014',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/232/581578.jpg',
    note: '',
  },
  {
    id: 7650,
    tvmazeId: '39',
    title: 'Resurrection',
    network: 'ABC',
    startYear: 2014,
    years: '2014–2015',
    genres: ['Drama', 'Science-Fiction', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'ABC cancelled after two seasons; the mysterious return of the dead in Arcadia was left completely unexplained.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/0/350.jpg',
    note: '',
  },
  {
    id: 7651,
    tvmazeId: '26629',
    title: 'Revelation: The End of Days',
    network: 'Sky History',
    startYear: 2014,
    years: '2014',
    genres: ['Drama', 'Thriller', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/482/1206571.jpg',
    note: '',
  },
  {
    id: 7652,
    tvmazeId: '1443',
    title: 'Review',
    network: 'Comedy Central',
    startYear: 2014,
    years: '2014–2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/326/816663.jpg',
    note: '',
  },
  {
    id: 7653,
    tvmazeId: '41212',
    title: 'Romeo and Juliet',
    network: 'Canale 5',
    startYear: 2014,
    years: '2014',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/186/466361.jpg',
    note: '',
  },
  {
    id: 7654,
    tvmazeId: '14639',
    title: 'Room Alone 401-410 checkifcancelled',
    network: 'One31',
    startYear: 2014,
    years: '2014–2016',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/49/123935.jpg',
    note: '',
  },
  {
    id: 7655,
    tvmazeId: '1403',
    title: 'Rosemary\'s Baby',
    network: 'NBC',
    startYear: 2014,
    years: '2014',
    genres: ['Drama', 'Horror', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/19805.jpg',
    note: '',
  },
  {
    id: 7656,
    tvmazeId: '1706',
    title: 'Rush',
    network: 'USA Network',
    startYear: 2014,
    years: '2014',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/9/23904.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 319, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
