window.pageShows = [
  {
    id: 15625,
    tvmazeId: '4132',
    title: 'Three\'s Company',
    network: 'ABC',
    startYear: 1977,
    years: '1977–1984',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/50015.jpg',
    note: '',
  },
  {
    id: 15626,
    tvmazeId: '40692',
    title: 'Thunder',
    network: 'NBC',
    startYear: 1977,
    years: '1977',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/544/1360872.jpg',
    note: '',
  },
  {
    id: 15627,
    tvmazeId: '25394',
    title: 'Treasure Island',
    network: 'BBC One',
    startYear: 1977,
    years: '1977',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/98/246877.jpg',
    note: '',
  },
  {
    id: 15628,
    tvmazeId: '53393',
    title: 'Undercover Elephant',
    network: 'NBC',
    startYear: 1977,
    years: '1977',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/295/739640.jpg',
    note: '',
  },
  {
    id: 15629,
    tvmazeId: '61241',
    title: 'Washington: Behind Closed Doors',
    network: 'ABC',
    startYear: 1977,
    years: '1977',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/401/1003551.jpg',
    note: '',
  },
  {
    id: 15630,
    tvmazeId: '34264',
    title: 'We\'ve Got Each Other',
    network: 'CBS',
    startYear: 1977,
    years: '1977–1978',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/585/1463134.jpg',
    note: '',
  },
  {
    id: 15631,
    tvmazeId: '75744',
    title: 'Westside Medical',
    network: 'ABC',
    startYear: 1977,
    years: '1977',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/587/1468814.jpg',
    note: '',
  },
  {
    id: 15632,
    tvmazeId: '28163',
    title: 'What Really Happened to the Class of \'65?',
    network: 'NBC',
    startYear: 1977,
    years: '1977–1978',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/111/279018.jpg',
    note: '',
  },
  {
    id: 15633,
    tvmazeId: '12108',
    title: 'What\'s New, Mr. Magoo?',
    network: 'CBS',
    startYear: 1977,
    years: '1977',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/40/101704.jpg',
    note: '',
  },
  {
    id: 15634,
    tvmazeId: '28054',
    title: 'Who Pays the Ferryman?',
    network: 'BBC Two',
    startYear: 1977,
    years: '1977',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/111/277653.jpg',
    note: '',
  },
  {
    id: 15635,
    tvmazeId: '36084',
    title: 'Wings',
    network: 'BBC One',
    startYear: 1977,
    years: '1977–1978',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/152/382003.jpg',
    note: '',
  },
  {
    id: 15636,
    tvmazeId: '53396',
    title: 'Wonder Wheels',
    network: 'CBS',
    startYear: 1977,
    years: '1977',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/295/739645.jpg',
    note: '',
  },
  {
    id: 15637,
    tvmazeId: '27714',
    title: 'You\'re Only Young Twice',
    network: 'ITV1',
    startYear: 1977,
    years: '1977–1981',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/109/273573.jpg',
    note: '',
  },
  {
    id: 15638,
    tvmazeId: '30181',
    title: 'Young Dan\'l Boone',
    network: 'CBS',
    startYear: 1977,
    years: '1977',
    genres: ['Action', 'Adventure', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/119/298677.jpg',
    note: '',
  },
  {
    id: 15639,
    tvmazeId: '43262',
    title: '¿Qué pasa, U.S.A.?',
    network: 'PBS',
    startYear: 1977,
    years: '1977',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/207/518166.jpg',
    note: '',
  },
  {
    id: 15640,
    tvmazeId: '45939',
    title: '4 Idle Hands',
    network: 'ITV1',
    startYear: 1976,
    years: '1976',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/236/592434.jpg',
    note: '',
  },
  {
    id: 15641,
    tvmazeId: '7553',
    title: 'Alice',
    network: 'CBS',
    startYear: 1976,
    years: '1976–1985',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/69654.jpg',
    note: '',
  },
  {
    id: 15642,
    tvmazeId: '57496',
    title: 'All\'s Fair',
    network: 'CBS',
    startYear: 1976,
    years: '1976–1977',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/356/890613.jpg',
    note: '',
  },
  {
    id: 15643,
    tvmazeId: '19540',
    title: 'Ark II',
    network: 'CBS',
    startYear: 1976,
    years: '1976',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/68/172165.jpg',
    note: '',
  },
  {
    id: 15644,
    tvmazeId: '18416',
    title: 'Arthur Hailey\'s The Moneychangers',
    network: 'NBC',
    startYear: 1976,
    years: '1976',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/487/1219305.jpg',
    note: '',
  },
  {
    id: 15645,
    tvmazeId: '57566',
    title: 'Ball Four',
    network: 'CBS',
    startYear: 1976,
    years: '1976',
    genres: ['Comedy', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 15646,
    tvmazeId: '13464',
    title: 'Beasts',
    network: 'ITV1',
    startYear: 1976,
    years: '1976',
    genres: ['Drama', 'Fantasy', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/602/1507071.jpg',
    note: '',
  },
  {
    id: 15647,
    tvmazeId: '35814',
    title: 'Bert D\'Angelo Superstar',
    network: 'ABC',
    startYear: 1976,
    years: '1976',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/151/379158.jpg',
    note: '',
  },
  {
    id: 15648,
    tvmazeId: '15549',
    title: 'Big John, Little John',
    network: 'NBC',
    startYear: 1976,
    years: '1976',
    genres: ['Comedy', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/52/131889.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 652, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
