window.pageShows = [
  {
    id: 9769,
    tvmazeId: '66745',
    title: 'The Roaring Twenties',
    network: 'RTÉ2',
    startYear: 2008,
    years: '2008',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/444/1111880.jpg',
    note: '',
  },
  {
    id: 9770,
    tvmazeId: '35668',
    title: 'The Royal Today',
    network: 'ITV1',
    startYear: 2008,
    years: '2008',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/151/377613.jpg',
    note: '',
  },
  {
    id: 9771,
    tvmazeId: '758',
    title: 'The Secret Life of the American Teenager',
    network: 'Freeform',
    startYear: 2008,
    years: '2008–2013',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/15243.jpg',
    note: '',
  },
  {
    id: 9772,
    tvmazeId: '26989',
    title: 'The Secret Saturdays',
    network: 'Cartoon Network',
    startYear: 2008,
    years: '2008–2010',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/106/266623.jpg',
    note: '',
  },
  {
    id: 9773,
    tvmazeId: '4490',
    title: 'The Spectacular Spider-Man',
    network: 'The CW',
    startYear: 2008,
    years: '2008–2009',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Disney cancelled after two seasons mid-story; Peter Parker\'s high school years and the Green Goblin arc were unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/51967.jpg',
    note: '',
  },
  {
    id: 9774,
    tvmazeId: '9447',
    title: 'The Strip',
    network: 'Nine Network',
    startYear: 2008,
    years: '2008',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/82952.jpg',
    note: '',
  },
  {
    id: 9775,
    tvmazeId: '2195',
    title: 'The Suite Life on Deck',
    network: 'Disney Channel',
    startYear: 2008,
    years: '2008–2011',
    genres: ['Comedy', 'Children', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/453/1132773.jpg',
    note: '',
  },
  {
    id: 9776,
    tvmazeId: '55790',
    title: 'The Summit',
    network: 'CBC',
    startYear: 2008,
    years: '2008',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/326/816668.jpg',
    note: '',
  },
  {
    id: 9777,
    tvmazeId: '26510',
    title: 'The Trojan Horse',
    network: 'CBC',
    startYear: 2008,
    years: '2008',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/104/260881.jpg',
    note: '',
  },
  {
    id: 9778,
    tvmazeId: '12562',
    title: 'The Xtacles',
    network: 'Adult Swim',
    startYear: 2008,
    years: '2008',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/42/107235.jpg',
    note: '',
  },
  {
    id: 9779,
    tvmazeId: '30096',
    title: 'Three Delivery',
    network: 'Nicktoons',
    startYear: 2008,
    years: '2008–2009',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/119/298060.jpg',
    note: '',
  },
  {
    id: 9780,
    tvmazeId: '9613',
    title: 'Time Trackers',
    network: 'Seven Network',
    startYear: 2008,
    years: '2008',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 9781,
    tvmazeId: '16958',
    title: 'To Love & Die',
    network: 'USA Network',
    startYear: 2008,
    years: '2008',
    genres: ['Drama', 'Comedy', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/57/144270.jpg',
    note: '',
  },
  {
    id: 9782,
    tvmazeId: '72924',
    title: 'Toot & Puddle',
    network: 'Nick Jr.',
    startYear: 2008,
    years: '2008–2009',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/488/1221639.jpg',
    note: '',
  },
  {
    id: 9783,
    tvmazeId: '18301',
    title: 'Tracey Ullman\'s State of the Union',
    network: 'Paramount+ with Showtime',
    startYear: 2008,
    years: '2008–2010',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/62/155231.jpg',
    note: '',
  },
  {
    id: 9784,
    tvmazeId: '9940',
    title: 'Trapped',
    network: 'Seven Network',
    startYear: 2008,
    years: '2008–2009',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/34/85369.jpg',
    note: '',
  },
  {
    id: 9785,
    tvmazeId: '28438',
    title: 'Trexx and Flipside',
    network: 'BBC Three',
    startYear: 2008,
    years: '2008',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/113/283029.jpg',
    note: '',
  },
  {
    id: 9786,
    tvmazeId: '22',
    title: 'True Blood',
    network: 'HBO',
    startYear: 2008,
    years: '2008–2014',
    genres: ['Drama', 'Romance', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/410/1026956.jpg',
    note: '',
  },
  {
    id: 9787,
    tvmazeId: '23046',
    title: 'True Jackson, VP',
    network: 'Nickelodeon',
    startYear: 2008,
    years: '2008–2011',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/85/214236.jpg',
    note: '',
  },
  {
    id: 9788,
    tvmazeId: '74618',
    title: 'TurboDogs',
    network: 'Qubo',
    startYear: 2008,
    years: '2008–2010',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/503/1259339.jpg',
    note: '',
  },
  {
    id: 9789,
    tvmazeId: '39200',
    title: 'Under One Roof',
    network: 'MyNetworkTV',
    startYear: 2008,
    years: '2008–2009',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/172/430883.jpg',
    note: '',
  },
  {
    id: 9790,
    tvmazeId: '1808',
    title: 'Underbelly',
    network: 'Nine Network',
    startYear: 2008,
    years: '2008–2013',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/10/26170.jpg',
    note: '',
  },
  {
    id: 9791,
    tvmazeId: '2020',
    title: 'Unhitched',
    network: 'FOX',
    startYear: 2008,
    years: '2008',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/398/995274.jpg',
    note: '',
  },
  {
    id: 9792,
    tvmazeId: '1358',
    title: 'Valentine',
    network: 'The CW',
    startYear: 2008,
    years: '2008–2009',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/18857.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 408, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
