window.pageShows = [
  {
    id: 122,
    title: "Stumptown",
    network: "ABC",
    startYear: 2019,
    years: "2019–2020",
    genres: ["Crime", "Drama", "Comedy"],
    status: "cancelled",
    cancelledAfterSeason: 1,
    cliffhanger: false,
    cliffhangerNote: "Season 1 resolved its main case arc; ABC renewed then un-renewed during the COVID-19 production halt",
    note: "Cobie Smulders as a veteran PI. ABC renewed for Season 2 then reversed that decision due to COVID — a particularly frustrating administrative cancellation."
  },
  {
    id: 123,
    title: "Emergence",
    network: "ABC",
    startYear: 2019,
    years: "2019–2020",
    genres: ["Sci-Fi", "Mystery", "Drama"],
    status: "cancelled",
    cancelledAfterSeason: 1,
    cliffhanger: true,
    cliffhangerNote: "Piper's true nature as an AI and the Augur corporation's plans for her kind are left permanently unresolved",
    note: "Allison Tolman as a sheriff who takes in a mysterious girl from a plane crash. ABC cancelled before the AI conspiracy was explained."
  },
  {
    id: 125,
    title: "The River",
    network: "ABC",
    startYear: 2012,
    years: "2012",
    genres: ["Horror", "Mystery", "Sci-Fi"],
    status: "cancelled",
    cancelledAfterSeason: 1,
    cliffhanger: true,
    cliffhangerNote: "Emmet Cole's true fate and the nature of the Amazon's 'Boiúna' magic are only beginning to be understood when the show ends",
    note: "Found-footage supernatural series about a crew searching for a missing wildlife documentarian in the Amazon. ABC cancelled after 8 episodes."
  },

  // ── Batch 4: UK cult, streaming era, more genre ───────────
  {
    id: 126,
    title: "Utopia",
    tvmazeQuery: "Utopia UK",
    network: "Channel 4",
    startYear: 2013,
    years: "2013–2014",
    genres: ["Conspiracy", "Thriller", "Sci-Fi"],
    status: "cancelled",
    cancelledAfterSeason: 2,
    cliffhanger: true,
    cliffhangerNote: "The Network's true endgame and Jessica Hyde's fate are left open; the planned Season 3 was never made",
    note: "Dennis Kelly's luridly violent conspiracy thriller. Channel 4 cancelled after Season 2. The US remake (Amazon, 2020) was also cancelled after one season."
  },
  {
    id: 127,
    title: "The Fades",
    network: "BBC Three",
    startYear: 2011,
    years: "2011",
    genres: ["Supernatural", "Horror", "YA"],
    status: "cancelled",
    cancelledAfterSeason: 1,
    cliffhanger: true,
    cliffhangerNote: "Paul's angelic powers are only emerging and the Fade invasion of the living world has barely begun",
    note: "Jack Thorne's BAFTA-winning British supernatural drama. BBC Three cancelled after one season despite immediate critical acclaim."
  },
  {
    id: 128,
    title: "In the Flesh",
    network: "BBC Three",
    startYear: 2013,
    years: "2013–2014",
    genres: ["Horror", "Drama", "Sci-Fi"],
    status: "cancelled",
    cancelledAfterSeason: 2,
    cliffhanger: true,
    cliffhangerNote: "Kieren's role in the Second Rising prophecy and the Undead Liberation Army's goals are left unresolved",
    note: "BAFTA-winning British zombie drama about the social reintegration of 'Partially Deceased Syndrome' sufferers. BBC Three cancelled mid-story."
  },
  {
    id: 129,
    title: "Humans",
    network: "Channel 4 / AMC",
    startYear: 2015,
    years: "2015–2018",
    genres: ["Sci-Fi", "Drama"],
    status: "cancelled",
    cancelledAfterSeason: 3,
    cliffhanger: true,
    cliffhangerNote: "The synth consciousness signal has been broadcast globally — the full consequences for human-synth coexistence left permanently open",
    note: "UK-US co-production about humanoid robots gaining consciousness. Cancelled after Season 3 just as the show's world was at its most interesting."
  },
  {
    id: 130,
    title: "Class",
    tvmazeQuery: "Class BBC",
    network: "BBC Three",
    startYear: 2016,
    years: "2016",
    genres: ["Sci-Fi", "YA", "Drama"],
    status: "cancelled",
    cancelledAfterSeason: 1,
    cliffhanger: true,
    cliffhangerNote: "Ram's father is dead, April is trapped in Shadow Kin space, and an alien invasion of Coal Hill is underway",
    note: "Doctor Who spin-off set at Coal Hill Academy. BBC Three cancelled after one season despite critical praise; BBC America aired it to a cult US following."
  },
  {
    id: 131,
    title: "Garth Marenghi's Darkplace",
    network: "Channel 4",
    startYear: 2004,
    years: "2004",
    genres: ["Comedy", "Horror", "Parody"],
    status: "cancelled",
    cancelledAfterSeason: 1,
    cliffhanger: false,
    cliffhangerNote: "Only 6 episodes were made; the parody format meant each episode was self-contained",
    note: "Matthew Holness and Richard Ayoade's genius parody of 80s horror TV. Channel 4 cancelled after 6 episodes — now a cult classic."
  },
  {
    id: 132,
    title: "Crazyhead",
    network: "E4",
    startYear: 2016,
    years: "2016",
    genres: ["Comedy", "Horror", "Fantasy"],
    status: "cancelled",
    cancelledAfterSeason: 1,
    cliffhanger: true,
    cliffhangerNote: "The demon hierarchy's larger plan beyond Callum and the girls' demon-hunting future are left open",
    note: "Howard Overman's demon-hunting comedy. E4 cancelled after 6 episodes — the spiritual successor to Misfits that never got to grow."
  },
  {
    id: 133,
    title: "Hex",
    network: "Sky One",
    startYear: 2004,
    years: "2004–2005",
    genres: ["Horror", "Supernatural", "Drama"],
    status: "cancelled",
    cancelledAfterSeason: 2,
    cliffhanger: true,
    cliffhangerNote: "Ella's angelic mission and the Nephilim prophecy are abandoned at a critical juncture",
    note: "British supernatural drama about a student discovering witchcraft. Sky One cancelled after Season 2 mid-prophecy."
  },
  {
    id: 134,
    title: "The Guild",
    network: "Web / Xbox Live",
    startYear: 2007,
    years: "2007–2013",
    genres: ["Comedy", "Web Series"],
    status: "ended",
    cancelledAfterSeason: null,
    totalSeasons: 6,
    cliffhanger: false,
    cliffhangerNote: null,
    note: "Felicia Day's pioneering web series about an online gaming guild. Ran 6 seasons independently — a landmark in creator-owned web content."
  },
  {
    id: 135,
    title: "Dr. Horrible's Sing-Along Blog",
    network: "Web",
    startYear: 2008,
    years: "2008",
    genres: ["Musical", "Comedy", "Web Series"],
    status: "ended",
    cancelledAfterSeason: null,
    totalSeasons: 1,
    cliffhanger: false,
    cliffhangerNote: "A sequel has been discussed for over a decade but remains unmade",
    note: "Joss Whedon's 43-minute supervillain musical made during the writers' strike. A complete story, though fans have waited 16 years for Act II."
  },
  {
    id: 136,
    title: "Video Game High School",
    network: "RocketJump / YouTube",
    startYear: 2012,
    years: "2012–2014",
    genres: ["Action", "Comedy", "Web Series"],
    status: "ended",
    cancelledAfterSeason: null,
    totalSeasons: 3,
    cliffhanger: false,
    cliffhangerNote: null,
    note: "Freddie Wong's YouTube web series about a school where gaming is the ultimate sport. Ran 3 seasons and concluded properly — a web series success story."
  },
  {
    id: 137,
    title: "Pioneer One",
    network: "VODO",
    startYear: 2010,
    years: "2010–2012",
    genres: ["Sci-Fi", "Drama", "Web Series"],
    status: "cancelled",
    cancelledAfterSeason: 1,
    cliffhanger: true,
    cliffhangerNote: "The cosmonaut's identity and the Soviet Mars mission he claims to be from are left unexplored beyond episode 6",
    note: "Crowdfunded sci-fi distributed free via BitTorrent — a landmark in independent distribution. The story was only beginning when funding ran out."
  },
  {
    id: 138,
    title: "Mortal Kombat: Legacy",
    network: "YouTube / Machinima",
    startYear: 2011,
    years: "2011–2013",
    genres: ["Action", "Sci-Fi", "Web Series"],
    status: "cancelled",
    cancelledAfterSeason: 2,
    cliffhanger: true,
    cliffhangerNote: "The tournament has barely begun and the Outworld characters' arrival is unresolved",
    note: "Kevin Tancharoen's gritty live-action Mortal Kombat web series. Machinima cancelled after Season 2 just as the actual tournament plot began."
  },
  {
    id: 139,
    title: "Tuca & Bertie",
    network: "Netflix / Adult Swim",
    startYear: 2019,
    years: "2019–2022",
    genres: ["Animated", "Comedy", "Drama"],
    status: "cancelled",
    cancelledAfterSeason: 3,
    cliffhanger: false,
    cliffhangerNote: "Netflix cancelled after Season 1; Adult Swim saved it for Seasons 2–3 then also cancelled — Season 3 finale provided decent closure",
    note: "Lisa Hanawalt's animated bird-woman comedy. Netflix cancelled, Adult Swim rescued it, then Adult Swim also cancelled. Two cancellations, one show."
  },
  {
    id: 140,
    title: "Final Space",
    network: "TBS / Adult Swim",
    startYear: 2018,
    years: "2018–2021",
    genres: ["Animated", "Sci-Fi", "Comedy"],
    status: "cancelled",
    cancelledAfterSeason: 3,
    cliffhanger: true,
    cliffhangerNote: "Gary is trapped in Final Space, Mooncake's true power is unrealised, and the dimensional threat is left entirely unresolved",
    note: "Olan Rogers' space adventure cancelled by Adult Swim after Season 3. The show was removed from streaming entirely — fans can't even rewatch it."
  },
  {
    id: 141,
    title: "Infinity Train",
    network: "Cartoon Network / HBO Max",
    startYear: 2019,
    years: "2019–2021",
    genres: ["Animated", "Sci-Fi", "YA"],
    status: "cancelled",
    cancelledAfterSeason: 4,
    cliffhanger: true,
    cliffhangerNote: "The One-One conductor's origin and the Train's true purpose were planned for future seasons that will never exist",
    note: "Owen Dennis's anthology sci-fi cancelled after four books. Like Final Space, removed from HBO Max entirely — a streaming-era tragedy."
  },
  {
    id: 142,
    title: "Young Justice",
    network: "Cartoon Network / DC Universe",
    startYear: 2010,
    years: "2010–2022",
    genres: ["Animated", "Superhero", "Action"],
    status: "cancelled",
    cancelledAfterSeason: 4,
    cliffhanger: true,
    cliffhangerNote: "Phantoms ended with a massive setup for Season 5 — the Reach's plans and the Team's future left open",
    note: "Cancelled by Cartoon Network after S2 despite huge popularity; fan pressure brought it back on DC Universe for S3–4, then cancelled again."
  },
  {
    id: 143,
    title: "The Spectacular Spider-Man",
    network: "Kids WB / Disney XD",
    startYear: 2008,
    years: "2008–2009",
    genres: ["Animated", "Superhero", "Action"],
    status: "cancelled",
    cancelledAfterSeason: 2,
    cliffhanger: true,
    cliffhangerNote: "The Master Planner's identity was just revealed in the Season 2 finale — Season 3 was already in development when Marvel's acquisition by Disney ended it",
    note: "Greg Weisman's acclaimed Spider-Man series cancelled when Disney acquired Marvel and discontinued all non-Disney animated productions."
  },
  {
    id: 144,
    title: "Sym-Bionic Titan",
    network: "Cartoon Network",
    startYear: 2010,
    years: "2010–2011",
    genres: ["Animated", "Sci-Fi", "Action"],
    status: "cancelled",
    cancelledAfterSeason: 1,
    cliffhanger: true,
    cliffhangerNote: "Ilana's royal identity has been discovered by the General and the royal forces approaching Earth are never addressed",
    note: "Genndy Tartakovsky's mecha sci-fi cancelled reportedly because it had no toy line. A legendary example of corporate interference killing creativity."
  },
  {
    id: 145,
    title: "Avengers: Earth's Mightiest Heroes",
    network: "Disney XD",
    startYear: 2010,
    years: "2010–2012",
    genres: ["Animated", "Superhero", "Action"],
    status: "cancelled",
    cancelledAfterSeason: 2,
    cliffhanger: false,
    cliffhangerNote: "Season 2 wrapped up its Skrull invasion arc, but the replacement with Avengers Assemble robbed the show of planned future stories",
    note: "Disney cancelled to make way for Avengers Assemble, which tied into the MCU branding. Fans have never forgiven the swap."
  },
  {
    id: 146,
    title: "Stargirl",
    network: "DC Universe / The CW",
    startYear: 2020,
    years: "2020–2022",
    genres: ["Superhero", "Drama", "YA"],
    status: "cancelled",
    cancelledAfterSeason: 3,
    cliffhanger: true,
    cliffhangerNote: "Starman's return and the Shade's true allegiance are left as setups for a Season 4 that The CW cancelled",
    note: "Geoff Johns' passion project about his late sister. The CW cancelled as part of its Arrowverse shutdown, leaving the JSA's story incomplete."
  }
];
window.pageMetadata = {"page": 6, "totalPages": 19, "perPage": 24, "stats": {"total": 454, "cancelled": 297, "cliffhanger": 250, "ended": 132}};
