window.pageShows = [
  {
    id: 9457,
    tvmazeId: '4029',
    title: 'Teachers',
    network: 'Channel 4',
    startYear: 2001,
    years: '2001–2004',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/49584.jpg',
    note: '',
  },
  {
    id: 9458,
    tvmazeId: '1666',
    title: 'That\'s My Bush!',
    network: 'Comedy Central',
    startYear: 2001,
    years: '2001',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/9/22969.jpg',
    note: '',
  },
  {
    id: 9459,
    tvmazeId: '1975',
    title: 'The Agency',
    network: 'CBS',
    startYear: 2001,
    years: '2001–2003',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/27951.jpg',
    note: '',
  },
  {
    id: 9460,
    tvmazeId: '2574',
    title: 'The Armando Iannucci Shows',
    network: 'Channel 4',
    startYear: 2001,
    years: '2001',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/58/145465.jpg',
    note: '',
  },
  {
    id: 9461,
    tvmazeId: '57541',
    title: 'The Associates',
    network: 'CTV',
    startYear: 2001,
    years: '2001–2002',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/356/891323.jpg',
    note: '',
  },
  {
    id: 9462,
    tvmazeId: '23844',
    title: 'The Beast',
    network: 'ABC',
    startYear: 2001,
    years: '2001',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/90/225144.jpg',
    note: '',
  },
  {
    id: 9463,
    tvmazeId: '6836',
    title: 'The Bernie Mac Show',
    network: 'FOX',
    startYear: 2001,
    years: '2001–2006',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/25/64590.jpg',
    note: '',
  },
  {
    id: 9464,
    tvmazeId: '58229',
    title: 'The Broad Side',
    network: 'CBC',
    startYear: 2001,
    years: '2001',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 9465,
    tvmazeId: '9149',
    title: 'The Cazalets',
    network: 'BBC One',
    startYear: 2001,
    years: '2001',
    genres: ['Drama', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/116/291278.jpg',
    note: '',
  },
  {
    id: 9466,
    tvmazeId: '12877',
    title: 'The Chris Isaak Show',
    network: 'Paramount+ with Showtime',
    startYear: 2001,
    years: '2001–2004',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/44/111433.jpg',
    note: '',
  },
  {
    id: 9467,
    tvmazeId: '3775',
    title: 'The Chronicle',
    network: 'Syfy',
    startYear: 2001,
    years: '2001–2002',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/47912.jpg',
    note: '',
  },
  {
    id: 9468,
    tvmazeId: '34272',
    title: 'The Diamond Hunters',
    network: 'Cinemax',
    startYear: 2001,
    years: '2001',
    genres: ['Drama', 'Romance', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/141/353621.jpg',
    note: '',
  },
  {
    id: 9469,
    tvmazeId: '18771',
    title: 'The Division',
    network: 'Lifetime',
    startYear: 2001,
    years: '2001–2004',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/64/162144.jpg',
    note: '',
  },
  {
    id: 9470,
    tvmazeId: '48208',
    title: 'The Downer Channel',
    network: 'NBC',
    startYear: 2001,
    years: '2001',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/257/644054.jpg',
    note: '',
  },
  {
    id: 9471,
    tvmazeId: '18357',
    title: 'The Education of Max Bickford',
    network: 'CBS',
    startYear: 2001,
    years: '2001–2002',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/62/156041.jpg',
    note: '',
  },
  {
    id: 9472,
    tvmazeId: '8176',
    title: 'The Ellen Show',
    network: 'CBS',
    startYear: 2001,
    years: '2001–2002',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/74133.jpg',
    note: '',
  },
  {
    id: 9473,
    tvmazeId: '2565',
    title: 'The Fairly OddParents',
    network: 'Nicktoons',
    startYear: 2001,
    years: '2001–2017',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/402/1006095.jpg',
    note: '',
  },
  {
    id: 9474,
    tvmazeId: '24967',
    title: 'The Fighting Fitzgeralds',
    network: 'NBC',
    startYear: 2001,
    years: '2001',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/96/240525.jpg',
    note: '',
  },
  {
    id: 9475,
    tvmazeId: '57589',
    title: 'The Glass',
    network: 'ITV1',
    startYear: 2001,
    years: '2001',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/356/892355.jpg',
    note: '',
  },
  {
    id: 9476,
    tvmazeId: '7345',
    title: 'The Grim Adventures of Billy & Mandy',
    network: 'Cartoon Network',
    startYear: 2001,
    years: '2001–2007',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/67810.jpg',
    note: '',
  },
  {
    id: 9477,
    tvmazeId: '2219',
    title: 'The Guardian',
    network: 'CBS',
    startYear: 2001,
    years: '2001–2004',
    genres: ['Drama', 'Crime', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/495/1239348.jpg',
    note: '',
  },
  {
    id: 9478,
    tvmazeId: '30614',
    title: 'The Hire',
    network: 'BMW Films',
    startYear: 2001,
    years: '2001–2016',
    genres: ['Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/121/303162.jpg',
    note: '',
  },
  {
    id: 9479,
    tvmazeId: '3660',
    title: 'The Infinite Worlds of H.G. Wells',
    network: 'Hallmark Channel',
    startYear: 2001,
    years: '2001',
    genres: ['Drama', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/47316.jpg',
    note: '',
  },
  {
    id: 9480,
    tvmazeId: '8517',
    title: 'The Inspector Lynley Mysteries',
    network: 'BBC One',
    startYear: 2001,
    years: '2001–2007',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/30/75780.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 395, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 856, "cliffhanger": 286, "ended": 13542}};
