window.pageShows = [
  {
    id: 12937,
    tvmazeId: '547',
    title: 'ER',
    network: 'NBC',
    startYear: 1994,
    years: '1994–2009',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/4/11490.jpg',
    note: '',
  },
  {
    id: 12938,
    tvmazeId: '28566',
    title: 'Escape from Jupiter',
    network: 'ABC',
    startYear: 1994,
    years: '1994',
    genres: ['Adventure', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12939,
    tvmazeId: '51078',
    title: 'Faith',
    network: 'ITV1',
    startYear: 1994,
    years: '1994',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/277/693104.jpg',
    note: '',
  },
  {
    id: 12940,
    tvmazeId: '51084',
    title: 'Family',
    network: 'RTÉ ONE',
    startYear: 1994,
    years: '1994',
    genres: ['Drama', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/277/693174.jpg',
    note: '',
  },
  {
    id: 12941,
    tvmazeId: '50671',
    title: 'Family Album',
    network: 'NBC',
    startYear: 1994,
    years: '1994',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/275/687786.jpg',
    note: '',
  },
  {
    id: 12942,
    tvmazeId: '4240',
    title: 'Fantastic Four',
    network: 'Syndication',
    startYear: 1994,
    years: '1994–1996',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/50840.jpg',
    note: '',
  },
  {
    id: 12943,
    tvmazeId: '12214',
    title: 'Fantasy Football League',
    network: 'BBC Two',
    startYear: 1994,
    years: '1994–2004',
    genres: ['Comedy', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/41/102641.jpg',
    note: '',
  },
  {
    id: 12944,
    tvmazeId: '51086',
    title: 'Finney',
    network: 'ITV1',
    startYear: 1994,
    years: '1994',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/277/693193.jpg',
    note: '',
  },
  {
    id: 12945,
    tvmazeId: '62729',
    title: 'Fortune Hunter',
    network: 'FOX',
    startYear: 1994,
    years: '1994',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/413/1034608.jpg',
    note: '',
  },
  {
    id: 12946,
    tvmazeId: '90342',
    title: 'Free Willy',
    network: 'ABC',
    startYear: 1994,
    years: '1994–1995',
    genres: ['Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/613/1534256.jpg',
    note: '',
  },
  {
    id: 12947,
    tvmazeId: '431',
    title: 'Friends',
    network: 'NBC',
    startYear: 1994,
    years: '1994–2004',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/41/104565.jpg',
    note: '',
  },
  {
    id: 12948,
    tvmazeId: '12964',
    title: 'Frontline',
    network: 'ABC',
    startYear: 1994,
    years: '1994–1997',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/44/111412.jpg',
    note: '',
  },
  {
    id: 12949,
    tvmazeId: '1898',
    title: 'Gargoyles',
    network: 'ABC',
    startYear: 1994,
    years: '1994–1997',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/27638.jpg',
    note: '',
  },
  {
    id: 12950,
    tvmazeId: '51113',
    title: 'Grushko',
    network: 'BBC One',
    startYear: 1994,
    years: '1994',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12951,
    tvmazeId: '6332',
    title: 'Gullah Gullah Island',
    network: 'Nick Jr.',
    startYear: 1994,
    years: '1994–1999',
    genres: ['Comedy', 'Children', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/24/60614.jpg',
    note: '',
  },
  {
    id: 12952,
    tvmazeId: '28547',
    title: 'Halifax f.p',
    network: 'Nine Network',
    startYear: 1994,
    years: '1994–2002',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/113/284106.jpg',
    note: '',
  },
  {
    id: 12953,
    tvmazeId: '17396',
    title: 'Hard Times',
    network: 'BBC One',
    startYear: 1994,
    years: '1994',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/134/336715.jpg',
    note: '',
  },
  {
    id: 12954,
    tvmazeId: '38014',
    title: 'Hardball',
    network: 'FOX',
    startYear: 1994,
    years: '1994',
    genres: ['Comedy', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/497/1243860.jpg',
    note: '',
  },
  {
    id: 12955,
    tvmazeId: '6088',
    title: 'Harry Enfield & Chums',
    network: 'BBC One',
    startYear: 1994,
    years: '1994–1998',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/59237.jpg',
    note: '',
  },
  {
    id: 12956,
    tvmazeId: '27081',
    title: 'Hawkeye',
    network: 'Syndication',
    startYear: 1994,
    years: '1994–1995',
    genres: ['Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/107/267520.jpg',
    note: '',
  },
  {
    id: 12957,
    tvmazeId: '60206',
    title: 'Heartland',
    network: 'ABC',
    startYear: 1994,
    years: '1994',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12958,
    tvmazeId: '65545',
    title: 'Heaven Help Us',
    network: 'Syndication',
    startYear: 1994,
    years: '1994',
    genres: ['Drama', 'Comedy', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12959,
    tvmazeId: '905',
    title: 'Hercules: The Legendary Journeys',
    network: 'Syndication',
    startYear: 1994,
    years: '1994–1999',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16007.jpg',
    note: '',
  },
  {
    id: 12960,
    tvmazeId: '8563',
    title: 'High Tide',
    network: 'CBS',
    startYear: 1994,
    years: '1994–1997',
    genres: ['Comedy', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/286/716697.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 540, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
