window.pageShows = [
  {
    id: 14281,
    tvmazeId: '73839',
    title: 'ITV Sunday Night Theatre',
    network: 'ITV1',
    startYear: 1969,
    years: '1969–1974',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14282,
    tvmazeId: '33494',
    title: 'Judge Dee',
    network: 'ITV1',
    startYear: 1969,
    years: '1969',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/136/340393.jpg',
    note: '',
  },
  {
    id: 14283,
    tvmazeId: '7747',
    title: 'Love, American Style',
    network: 'ABC',
    startYear: 1969,
    years: '1969–1974',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/60/152483.jpg',
    note: '',
  },
  {
    id: 14284,
    tvmazeId: '11516',
    title: 'Marcus Welby, M.D.',
    network: 'ABC',
    startYear: 1969,
    years: '1969–1976',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/38/97258.jpg',
    note: '',
  },
  {
    id: 14285,
    tvmazeId: '30643',
    title: 'Marine Boy',
    network: 'Fuji TV',
    startYear: 1969,
    years: '1969',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/121/303937.jpg',
    note: '',
  },
  {
    id: 14286,
    tvmazeId: '8180',
    title: 'Mary, Mungo and Midge',
    network: 'BBC One',
    startYear: 1969,
    years: '1969',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/74208.jpg',
    note: '',
  },
  {
    id: 14287,
    tvmazeId: '6321',
    title: 'Medical Center',
    network: 'CBS',
    startYear: 1969,
    years: '1969–1976',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/24/60631.jpg',
    note: '',
  },
  {
    id: 14288,
    tvmazeId: '27242',
    title: 'Motormouse and Autocat',
    network: 'ABC',
    startYear: 1969,
    years: '1969–1971',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/107/269059.jpg',
    note: '',
  },
  {
    id: 14289,
    tvmazeId: '78988',
    title: 'My Friend Tony',
    network: 'NBC',
    startYear: 1969,
    years: '1969',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14290,
    tvmazeId: '17416',
    title: 'My World and Welcome to It',
    network: 'NBC',
    startYear: 1969,
    years: '1969–1970',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/58/147147.jpg',
    note: '',
  },
  {
    id: 14291,
    tvmazeId: '3699',
    title: 'Night Gallery',
    network: 'NBC',
    startYear: 1969,
    years: '1969–1973',
    genres: ['Drama', 'Horror', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/47465.jpg',
    note: '',
  },
  {
    id: 14292,
    tvmazeId: '5972',
    title: 'On the Buses',
    network: 'ITV1',
    startYear: 1969,
    years: '1969–1973',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/58720.jpg',
    note: '',
  },
  {
    id: 14293,
    tvmazeId: '44753',
    title: 'Parkin\'s Patch',
    network: 'ITV1',
    startYear: 1969,
    years: '1969–1970',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/217/544625.jpg',
    note: '',
  },
  {
    id: 14294,
    tvmazeId: '21045',
    title: 'Paul Temple',
    network: 'BBC One',
    startYear: 1969,
    years: '1969–1971',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/74/185700.jpg',
    note: '',
  },
  {
    id: 14295,
    tvmazeId: '2585',
    title: 'Randall & Hopkirk (Deceased)',
    network: 'ITV1',
    startYear: 1969,
    years: '1969–1970',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/13/34457.jpg',
    note: '',
  },
  {
    id: 14296,
    tvmazeId: '7510',
    title: 'Room 222',
    network: 'ABC',
    startYear: 1969,
    years: '1969–1974',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/69152.jpg',
    note: '',
  },
  {
    id: 14297,
    tvmazeId: '17272',
    title: 'Sabrina',
    network: 'CBS',
    startYear: 1969,
    years: '1969–1972',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/280/701812.jpg',
    note: '',
  },
  {
    id: 14298,
    tvmazeId: '3358',
    title: 'Scooby Doo, Where Are You!',
    network: 'CBS',
    startYear: 1969,
    years: '1969–1970',
    genres: ['Comedy', 'Adventure', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/17/44284.jpg',
    note: '',
  },
  {
    id: 14299,
    tvmazeId: '6544',
    title: 'Sesame Street',
    network: 'Netflix',
    startYear: 1969,
    years: '1969–',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/597/1494633.jpg',
    note: '',
  },
  {
    id: 14300,
    tvmazeId: '75550',
    title: 'Skyhawks',
    network: 'ABC',
    startYear: 1969,
    years: '1969',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/509/1274758.jpg',
    note: '',
  },
  {
    id: 14301,
    tvmazeId: '55459',
    title: 'Softly Softly: Task Force',
    network: 'BBC One',
    startYear: 1969,
    years: '1969–1976',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/319/799019.jpg',
    note: '',
  },
  {
    id: 14302,
    tvmazeId: '8760',
    title: 'Special Branch',
    network: 'ITV1',
    startYear: 1969,
    years: '1969–1974',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/77882.jpg',
    note: '',
  },
  {
    id: 14303,
    tvmazeId: '21038',
    title: 'Spike Milligan\'s Q',
    network: 'BBC Two',
    startYear: 1969,
    years: '1969–1980',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/159/398515.jpg',
    note: '',
  },
  {
    id: 14304,
    tvmazeId: '24672',
    title: 'Strange Paradise',
    network: 'Syndication',
    startYear: 1969,
    years: '1969–1970',
    genres: ['Drama', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/94/236131.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 596, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 670, "cliffhanger": 0, "ended": 13760}};
