window.pageShows = [
  {
    id: 3077,
    tvmazeId: '48000',
    title: 'American Horror Stories',
    network: 'Hulu',
    startYear: 2021,
    years: '2021–2024',
    genres: ['Horror'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/592/1480231.jpg',
    note: '',
  },
  {
    id: 3078,
    tvmazeId: '43217',
    title: 'American Rust',
    network: 'Prime Video',
    startYear: 2021,
    years: '2021–2024',
    genres: ['Drama', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/512/1281767.jpg',
    note: '',
  },
  {
    id: 3079,
    tvmazeId: '52904',
    title: 'And Just Like That...',
    network: 'HBO Max',
    startYear: 2021,
    years: '2021–2025',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/581/1453808.jpg',
    note: '',
  },
  {
    id: 3080,
    tvmazeId: '51063',
    title: 'Angela Black',
    network: 'ITV1',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/364/910347.jpg',
    note: '',
  },
  {
    id: 3081,
    tvmazeId: '55641',
    title: 'Angels of Death',
    network: 'Warhammer+',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/353/883760.jpg',
    note: '',
  },
  {
    id: 3082,
    tvmazeId: '54628',
    title: 'Anna',
    network: 'Sky Atlantic',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/310/775401.jpg',
    note: '',
  },
  {
    id: 3083,
    tvmazeId: '53485',
    title: 'Anne Boleyn',
    network: '5',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Thriller', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/324/811513.jpg',
    note: '',
  },
  {
    id: 3084,
    tvmazeId: '52732',
    title: 'Annika',
    network: 'U&alibi',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/419/1049050.jpg',
    note: '',
  },
  {
    id: 3085,
    tvmazeId: '45844',
    title: 'Aquaman: King of Atlantis',
    network: 'HBO Max',
    startYear: 2021,
    years: '2021',
    genres: ['Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/360/901244.jpg',
    note: '',
  },
  {
    id: 3086,
    tvmazeId: '58894',
    title: 'Aranyak',
    network: 'Netflix',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/383/957613.jpg',
    note: '',
  },
  {
    id: 3087,
    tvmazeId: '55138',
    title: 'Arcane: League of Legends',
    network: 'Netflix',
    startYear: 2021,
    years: '2021–2024',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/536/1340287.jpg',
    note: '',
  },
  {
    id: 3088,
    tvmazeId: '53156',
    title: 'Archibald\'s Next Big Thing Is Here!',
    network: 'Peacock',
    startYear: 2021,
    years: '2021',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/383/959615.jpg',
    note: '',
  },
  {
    id: 3089,
    tvmazeId: '45325',
    title: 'Around the World in 80 Days',
    network: 'ZDFmediathek',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Comedy', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/379/948816.jpg',
    note: '',
  },
  {
    id: 3090,
    tvmazeId: '57687',
    title: 'Asesino del Olvido',
    network: 'HBO Max',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/357/894876.jpg',
    note: '',
  },
  {
    id: 3091,
    tvmazeId: '55489',
    title: 'Aspirants',
    network: 'Prime Video',
    startYear: 2021,
    years: '2021–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/320/800421.jpg',
    note: '',
  },
  {
    id: 3092,
    tvmazeId: '57458',
    title: 'Australia\'s Sexiest Tradie',
    network: '7mate',
    startYear: 2021,
    years: '2021',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/364/910023.jpg',
    note: '',
  },
  {
    id: 3093,
    tvmazeId: '57613',
    title: 'Australian Gangster',
    network: 'Seven Network',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/357/892889.jpg',
    note: '',
  },
  {
    id: 3094,
    tvmazeId: '74207',
    title: 'B.O.T. and the Beasties',
    network: 'CBeebies',
    startYear: 2021,
    years: '2021',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/501/1252732.jpg',
    note: '',
  },
  {
    id: 3095,
    tvmazeId: '58171',
    title: 'Babble Bop!',
    network: 'Peacock',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Comedy', 'Children', 'Music'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/392/982465.jpg',
    note: '',
  },
  {
    id: 3096,
    tvmazeId: '50128',
    title: 'Back to the Rafters',
    network: 'Prime Video',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/606/1516550.jpg',
    note: '',
  },
  {
    id: 3097,
    tvmazeId: '59346',
    title: 'Backwashed',
    network: 'BBC iPlayer',
    startYear: 2021,
    years: '2021',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 3098,
    tvmazeId: '58876',
    title: 'Bad and Crazy',
    network: 'tvN',
    startYear: 2021,
    years: '2021–2022',
    genres: ['Action', 'Thriller', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/612/1531644.jpg',
    note: '',
  },
  {
    id: 3099,
    tvmazeId: '52237',
    title: 'Bad Buddy',
    network: 'GMM25',
    startYear: 2021,
    years: '2021–2022',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/612/1531857.jpg',
    note: '',
  },
  {
    id: 3100,
    tvmazeId: '57880',
    title: 'Bangkok Breaking',
    network: 'Netflix',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/360/901524.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 129, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
