window.pageShows = [
  {
    id: 7345,
    tvmazeId: '8792',
    title: 'V Morgan is Dead',
    network: 'YouTube',
    startYear: 2015,
    years: '2015–2016',
    genres: ['Drama', 'Comedy', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/49/124263.jpg',
    note: '',
  },
  {
    id: 7346,
    tvmazeId: '48431',
    title: 'Venus vs. Mars',
    network: 'Sky Witness',
    startYear: 2015,
    years: '2015',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/259/649239.jpg',
    note: '',
  },
  {
    id: 7347,
    tvmazeId: '3386',
    title: 'Versailles',
    network: 'Canal+',
    startYear: 2015,
    years: '2015–2018',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/34/86312.jpg',
    note: '',
  },
  {
    id: 7348,
    tvmazeId: '16214',
    title: 'Vikings: Athelstan\'s Journal',
    network: 'History Channel',
    startYear: 2015,
    years: '2015',
    genres: ['Drama', 'Action', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/54/135411.jpg',
    note: '',
  },
  {
    id: 7349,
    tvmazeId: '2752',
    title: 'Vixen',
    network: 'CW Seed',
    startYear: 2015,
    years: '2015–2016',
    genres: ['Action', 'Fantasy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/14/37129.jpg',
    note: '',
  },
  {
    id: 7350,
    tvmazeId: '5535',
    title: 'W/ Bob & David',
    network: 'Netflix',
    startYear: 2015,
    years: '2015',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/117/293999.jpg',
    note: '',
  },
  {
    id: 7351,
    tvmazeId: '1179',
    title: 'Wayward Pines',
    network: 'FOX',
    startYear: 2015,
    years: '2015–2016',
    genres: ['Drama', 'Science-Fiction', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/54/135773.jpg',
    note: '',
  },
  {
    id: 7352,
    tvmazeId: '2612',
    title: 'We Bare Bears',
    network: 'Cartoon Network',
    startYear: 2015,
    years: '2015–2019',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/223/557683.jpg',
    note: '',
  },
  {
    id: 7353,
    tvmazeId: '1712',
    title: 'Weird Loners',
    network: 'FOX',
    startYear: 2015,
    years: '2015',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/9/23999.jpg',
    note: '',
  },
  {
    id: 7354,
    tvmazeId: '3087',
    title: 'Westside',
    network: 'Three',
    startYear: 2015,
    years: '2015–2020',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/120/302473.jpg',
    note: '',
  },
  {
    id: 7355,
    tvmazeId: '1847',
    title: 'Wet Hot American Summer: First Day of Camp',
    network: 'Netflix',
    startYear: 2015,
    years: '2015',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/14/35306.jpg',
    note: '',
  },
  {
    id: 7356,
    tvmazeId: '8366',
    title: 'What Lives Inside',
    network: 'Hulu',
    startYear: 2015,
    years: '2015',
    genres: ['Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/30/75012.jpg',
    note: '',
  },
  {
    id: 7357,
    tvmazeId: '4878',
    title: 'When We Go to War',
    network: 'TVNZ 1',
    startYear: 2015,
    years: '2015',
    genres: ['Drama', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/53422.jpg',
    note: '',
  },
  {
    id: 7358,
    tvmazeId: '14254',
    title: 'WHIH News Front',
    network: 'YouTube',
    startYear: 2015,
    years: '2015–2016',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/48/121146.jpg',
    note: '',
  },
  {
    id: 7359,
    tvmazeId: '15609',
    title: 'Whisker Haven Tales with the Palace Pets',
    network: 'Disney Junior',
    startYear: 2015,
    years: '2015–2017',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/74/187161.jpg',
    note: '',
  },
  {
    id: 7360,
    tvmazeId: '1863',
    title: 'Wicked City',
    network: 'Hulu',
    startYear: 2015,
    years: '2015',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'ABC cancelled after three episodes; the 1980s Sunset Strip serial killer anthology was barely introduced.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/66540.jpg',
    note: '',
  },
  {
    id: 7361,
    tvmazeId: '2600',
    title: 'Winter',
    network: 'Seven Network',
    startYear: 2015,
    years: '2015',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/13/34566.jpg',
    note: '',
  },
  {
    id: 7362,
    tvmazeId: '15150',
    title: 'Wissper',
    network: '5',
    startYear: 2015,
    years: '2015–2016',
    genres: ['Comedy', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/97/244433.jpg',
    note: '',
  },
  {
    id: 7363,
    tvmazeId: '5463',
    title: 'WITS Academy',
    network: 'Nickelodeon',
    startYear: 2015,
    years: '2015',
    genres: ['Comedy', 'Family', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/55840.jpg',
    note: '',
  },
  {
    id: 7364,
    tvmazeId: '1432',
    title: 'Wolf Hall',
    network: 'BBC One',
    startYear: 2015,
    years: '2015–2024',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/542/1356077.jpg',
    note: '',
  },
  {
    id: 7365,
    tvmazeId: '58321',
    title: 'Wolverine Versus Sabretooth: Reborn',
    network: 'Unknown',
    startYear: 2015,
    years: '2015',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 7366,
    tvmazeId: '10546',
    title: 'Women Who Spit',
    network: 'BBC iPlayer',
    startYear: 2015,
    years: '2015',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/35/89098.jpg',
    note: '',
  },
  {
    id: 7367,
    tvmazeId: '11471',
    title: 'World\'s End',
    network: 'CBBC',
    startYear: 2015,
    years: '2015',
    genres: ['Drama', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/38/96564.jpg',
    note: '',
  },
  {
    id: 7368,
    tvmazeId: '18157',
    title: 'Wussywat the Clumsy Cat',
    network: 'CBeebies',
    startYear: 2015,
    years: '2015–2016',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/69/174870.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 307, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
