window.pageShows = [
  {
    id: 1489,
    tvmazeId: '53147',
    title: 'Black Bird',
    network: 'Apple TV',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/501/1254750.jpg',
    note: '',
  },
  {
    id: 1490,
    tvmazeId: '58935',
    title: 'Blockbuster',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/425/1063064.jpg',
    note: '',
  },
  {
    id: 1491,
    tvmazeId: '61822',
    title: 'Blood Sisters',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/408/1020879.jpg',
    note: '',
  },
  {
    id: 1492,
    tvmazeId: '53342',
    title: 'Boo, Bitch',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy', 'Adventure', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/412/1032240.jpg',
    note: '',
  },
  {
    id: 1493,
    tvmazeId: '60175',
    title: 'Bosch: Legacy',
    network: 'Prime Video',
    startYear: 2022,
    years: '2022–2025',
    genres: ['Drama', 'Crime', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/564/1411768.jpg',
    note: '',
  },
  {
    id: 1494,
    tvmazeId: '78626',
    title: 'Bridesman',
    network: 'Grindr',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/528/1322166.jpg',
    note: '',
  },
  {
    id: 1495,
    tvmazeId: '65696',
    title: 'Brown and Friends',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/438/1096615.jpg',
    note: '',
  },
  {
    id: 1496,
    tvmazeId: '62776',
    title: 'Bugs Bunny Builders',
    network: 'HBO Max',
    startYear: 2022,
    years: '2022–',
    genres: ['Comedy', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/414/1035684.jpg',
    note: '',
  },
  {
    id: 1497,
    tvmazeId: '60447',
    title: 'Bust Down',
    network: 'Peacock',
    startYear: 2022,
    years: '2022–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/395/989408.jpg',
    note: '',
  },
  {
    id: 1498,
    tvmazeId: '52202',
    title: 'Candy',
    network: 'Hulu',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/404/1010796.jpg',
    note: '',
  },
  {
    id: 1499,
    tvmazeId: '60942',
    title: 'Carl Weber\'s The Black Hamptons',
    network: 'BET+',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Family'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/502/1256071.jpg',
    note: '',
  },
  {
    id: 1500,
    tvmazeId: '52361',
    title: 'Cars on the Road',
    network: 'Disney+',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy', 'Adventure', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/438/1095301.jpg',
    note: '',
  },
  {
    id: 1501,
    tvmazeId: '85247',
    title: 'CBeebies House: Time to Play',
    network: 'BBC iPlayer',
    startYear: 2022,
    years: '2022–',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 1502,
    tvmazeId: '60210',
    title: 'Cheaters',
    network: 'BBC iPlayer',
    startYear: 2022,
    years: '2022–2024',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/395/988194.jpg',
    note: '',
  },
  {
    id: 1503,
    tvmazeId: '63389',
    title: 'Chibiverse',
    network: 'Disney Channel',
    startYear: 2022,
    years: '2022–',
    genres: ['Adventure', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/418/1045062.jpg',
    note: '',
  },
  {
    id: 1504,
    tvmazeId: '63019',
    title: 'Chicken Girls: College Years',
    network: 'YouTube',
    startYear: 2022,
    years: '2022–2023',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/417/1043236.jpg',
    note: '',
  },
  {
    id: 1505,
    tvmazeId: '64856',
    title: 'Chicken Girls: Forever Team',
    network: 'YouTube',
    startYear: 2022,
    years: '2022',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/429/1074610.jpg',
    note: '',
  },
  {
    id: 1506,
    tvmazeId: '46068',
    title: 'Children Ruin Everything',
    network: 'CTV',
    startYear: 2022,
    years: '2022–2025',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/389/973349.jpg',
    note: '',
  },
  {
    id: 1507,
    tvmazeId: '45825',
    title: 'Chivalry',
    network: 'Channel 4',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/405/1014374.jpg',
    note: '',
  },
  {
    id: 1508,
    tvmazeId: '46422',
    title: 'Chloe',
    network: 'BBC iPlayer',
    startYear: 2022,
    years: '2022',
    genres: ['Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/392/981821.jpg',
    note: '',
  },
  {
    id: 1509,
    tvmazeId: '64858',
    title: 'Circuit Breakers',
    network: 'Apple TV',
    startYear: 2022,
    years: '2022–',
    genres: ['Family', 'Science-Fiction', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/428/1070818.jpg',
    note: '',
  },
  {
    id: 1510,
    tvmazeId: '63315',
    title: 'Class of 1970',
    network: 'YouTube',
    startYear: 2022,
    years: '2022–',
    genres: ['Children', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/426/1065791.jpg',
    note: '',
  },
  {
    id: 1511,
    tvmazeId: '64860',
    title: 'Colin From Accounts',
    network: 'Binge',
    startYear: 2022,
    years: '2022–',
    genres: ['Comedy', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/485/1214687.jpg',
    note: '',
  },
  {
    id: 1512,
    tvmazeId: '64127',
    title: 'Colourblocks',
    network: 'BBC iPlayer',
    startYear: 2022,
    years: '2022–',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/422/1055360.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 63, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 334, "cliffhanger": 235, "ended": 13701}};
