window.pageShows = [
  {
    id: 14353,
    tvmazeId: '85098',
    title: 'Wilderness Road',
    network: 'BBC One',
    startYear: 1986,
    years: '1986',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/571/1428461.jpg',
    note: '',
  },
  {
    id: 14354,
    tvmazeId: '24948',
    title: 'Wildfire',
    network: 'CBS',
    startYear: 1986,
    years: '1986',
    genres: ['Children', 'Fantasy', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/96/240286.jpg',
    note: '',
  },
  {
    id: 14355,
    tvmazeId: '10174',
    title: 'Worlds Beyond',
    network: 'ITV1',
    startYear: 1986,
    years: '1986–1988',
    genres: ['Drama', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/297/744188.jpg',
    note: '',
  },
  {
    id: 14356,
    tvmazeId: '6647',
    title: 'Yes, Prime Minister',
    network: 'BBC Two',
    startYear: 1986,
    years: '1986–1988',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/25/62845.jpg',
    note: '',
  },
  {
    id: 14357,
    tvmazeId: '11641',
    title: 'You Again?',
    network: 'NBC',
    startYear: 1986,
    years: '1986–1987',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/39/98367.jpg',
    note: '',
  },
  {
    id: 14358,
    tvmazeId: '6860',
    title: 'Zoobilee Zoo',
    network: 'Syndication',
    startYear: 1986,
    years: '1986–1987',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/99/249020.jpg',
    note: '',
  },
  {
    id: 14359,
    tvmazeId: '7602',
    title: '227',
    network: 'NBC',
    startYear: 1985,
    years: '1985–1990',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/63/158609.jpg',
    note: '',
  },
  {
    id: 14360,
    tvmazeId: '48774',
    title: 'A Thousand Skies',
    network: 'Seven Network',
    startYear: 1985,
    years: '1985',
    genres: ['Drama', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/262/655422.jpg',
    note: '',
  },
  {
    id: 14361,
    tvmazeId: '18887',
    title: 'A Woman of Substance',
    network: 'Channel 4',
    startYear: 1985,
    years: '1985',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/65/163044.jpg',
    note: '',
  },
  {
    id: 14362,
    tvmazeId: '26841',
    title: 'A.D.',
    network: 'NBC',
    startYear: 1985,
    years: '1985',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/105/264259.jpg',
    note: '',
  },
  {
    id: 14363,
    tvmazeId: '31065',
    title: 'Alias the Jester',
    network: 'ITV1',
    startYear: 1985,
    years: '1985–1986',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/123/309598.jpg',
    note: '',
  },
  {
    id: 14364,
    tvmazeId: '37959',
    title: 'Alice in Wonderland',
    network: 'CBS',
    startYear: 1985,
    years: '1985',
    genres: ['Adventure', 'Family', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/162/406640.jpg',
    note: '',
  },
  {
    id: 14365,
    tvmazeId: '39224',
    title: 'All in Good Faith',
    network: 'ITV1',
    startYear: 1985,
    years: '1985–1988',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/406/1017457.jpg',
    note: '',
  },
  {
    id: 14366,
    tvmazeId: '1122',
    title: 'Amazing Stories',
    network: 'NBC',
    startYear: 1985,
    years: '1985–1987',
    genres: ['Fantasy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17262.jpg',
    note: '',
  },
  {
    id: 14367,
    tvmazeId: '51290',
    title: 'Anna of the Five Towns',
    network: 'BBC Two',
    startYear: 1985,
    years: '1985',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/460/1150391.jpg',
    note: '',
  },
  {
    id: 14368,
    tvmazeId: '1760',
    title: 'Anne of Green Gables',
    network: 'CBC',
    startYear: 1985,
    years: '1985–2008',
    genres: ['Drama', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/9/24599.jpg',
    note: '',
  },
  {
    id: 14369,
    tvmazeId: '8239',
    title: 'Anzacs',
    network: 'Nine Network',
    startYear: 1985,
    years: '1985',
    genres: ['Drama', 'War', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/74579.jpg',
    note: '',
  },
  {
    id: 14370,
    tvmazeId: '57625',
    title: 'Berrenger\'s',
    network: 'NBC',
    startYear: 1985,
    years: '1985',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/357/893176.jpg',
    note: '',
  },
  {
    id: 14371,
    tvmazeId: '20715',
    title: 'Bertha',
    network: 'BBC One',
    startYear: 1985,
    years: '1985–1986',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/182971.jpg',
    note: '',
  },
  {
    id: 14372,
    tvmazeId: '23362',
    title: 'Bleak House',
    network: 'BBC Two',
    startYear: 1985,
    years: '1985',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/87/219223.jpg',
    note: '',
  },
  {
    id: 14373,
    tvmazeId: '11937',
    title: 'Blott on the Landscape',
    network: 'BBC Two',
    startYear: 1985,
    years: '1985',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/40/100327.jpg',
    note: '',
  },
  {
    id: 14374,
    tvmazeId: '16830',
    title: 'Bulman',
    network: 'ITV1',
    startYear: 1985,
    years: '1985–1987',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/56/140601.jpg',
    note: '',
  },
  {
    id: 14375,
    tvmazeId: '5982',
    title: 'C.A.T.S. Eyes',
    network: 'ITV1',
    startYear: 1985,
    years: '1985–1987',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/58739.jpg',
    note: '',
  },
  {
    id: 14376,
    tvmazeId: '9218',
    title: 'Care Bears',
    network: 'ABC',
    startYear: 1985,
    years: '1985–1988',
    genres: ['Comedy', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/32/81206.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 599, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 398, "cliffhanger": 239, "ended": 15092}};
