window.pageShows = [
  {
    id: 247,
    title: "The Terror",
    tvmazeQuery: "The Terror",
    network: "AMC",
    startYear: 2018,
    years: "2018–2019",
    genres: ["Horror", "Historical", "Anthology"],
    status: "cancelled",
    cancelledAfterSeason: 2,
    cliffhanger: false,
    cliffhangerNote: "Each season was a self-contained anthology; Season 2 (Infamy) told a complete Japanese-American internment ghost story",
    note: "AMC's anthology horror — Season 1 was a gripping Arctic survival story, Season 2 a ghost story during WWII internment. Cancelled but both seasons complete."
  },
  {
    id: 249,
    title: "Snowpiercer",
    network: "TNT / Netflix",
    startYear: 2020,
    years: "2020–2023",
    genres: ["Sci-Fi", "Drama", "Thriller"],
    status: "cancelled",
    cancelledAfterSeason: 4,
    cliffhanger: true,
    cliffhangerNote: "Layton's leadership of Snowpiercer and the possibility of leaving the train for a warming Earth are left open",
    note: "Based on the Bong Joon-ho film and original French graphic novel. Cancelled after Season 4 with the post-ice-age future unresolved."
  },
  {
    id: 250,
    title: "Claws",
    network: "TNT",
    startYear: 2017,
    years: "2017–2022",
    genres: ["Crime", "Drama", "Comedy"],
    status: "ended",
    cancelledAfterSeason: null,
    totalSeasons: 4,
    cliffhanger: false,
    cliffhangerNote: null,
    note: "Niecy Nash leading a nail salon money-laundering ensemble. Four seasons, a proper finale — TNT's gloriously trashy prestige drama that earned its ending."
  },
  {
    id: 251,
    title: "The Alienist",
    network: "TNT",
    startYear: 2018,
    years: "2018–2020",
    genres: ["Crime", "Historical", "Thriller"],
    status: "cancelled",
    cancelledAfterSeason: 2,
    cliffhanger: false,
    cliffhangerNote: "Season 2 (Angel of Darkness) adapted the second novel and told a complete story, though more books in the series remain unadapted",
    note: "Daniel Brühl and Luke Evans as Victorian-era criminal profilers. Two seasons adapted two novels — complete in itself, though Caleb Carr wrote more books."
  },
  {
    id: 252,
    title: "Animal Kingdom",
    network: "TNT",
    startYear: 2016,
    years: "2016–2022",
    genres: ["Crime", "Drama"],
    status: "ended",
    cancelledAfterSeason: null,
    totalSeasons: 6,
    cliffhanger: false,
    cliffhangerNote: null,
    note: "Based on the Australian film. Six seasons of the Cody family's criminal empire. Ellen Barkin's Smurf is one of TV's great matriarchs. Properly ended."
  },
  {
    id: 253,
    title: "Detroiters",
    network: "Comedy Central",
    startYear: 2017,
    years: "2017–2018",
    genres: ["Comedy"],
    status: "cancelled",
    cancelledAfterSeason: 2,
    cliffhanger: false,
    cliffhangerNote: null,
    note: "Sam Richardson and Tim Robinson's beloved local ad agency comedy. Comedy Central cancelled after two short seasons. A cult gem criminally under-watched."
  },
  {
    id: 254,
    title: "Corporate",
    network: "Comedy Central",
    startYear: 2018,
    years: "2018–2020",
    genres: ["Dark Comedy", "Satire"],
    status: "ended",
    cancelledAfterSeason: null,
    totalSeasons: 3,
    cliffhanger: false,
    cliffhangerNote: null,
    note: "Bleak satire of corporate America with a nihilistic edge. Three seasons, complete arc — an underrated Comedy Central gem that knew when to stop."
  },
  {
    id: 255,
    title: "Ugly Americans",
    network: "Comedy Central",
    startYear: 2010,
    years: "2010–2012",
    genres: ["Animated", "Comedy", "Fantasy"],
    status: "cancelled",
    cancelledAfterSeason: 2,
    cliffhanger: true,
    cliffhangerNote: "Mark's relationship with his demon girlfriend Callie and his work managing supernatural beings in New York are abandoned mid-arc",
    note: "Animated comedy set in a New York overrun by monsters, zombies, and demons. Comedy Central cancelled after two seasons mid-story."
  },
  {
    id: 256,
    title: "Dexter: New Blood",
    network: "Showtime",
    startYear: 2021,
    years: "2021",
    genres: ["Crime", "Thriller", "Drama"],
    status: "ended",
    cancelledAfterSeason: null,
    totalSeasons: 1,
    cliffhanger: false,
    cliffhangerNote: "The limited series ended definitively — though a planned second revival was later announced, making this 'ending' complicated",
    note: "Michael C. Hall returning as Dexter Morgan. The limited revival finally gave the character a proper death after the original series' infamous finale."
  },
  {
    id: 257,
    title: "The Affair",
    network: "Showtime",
    startYear: 2014,
    years: "2014–2019",
    genres: ["Drama", "Mystery"],
    status: "ended",
    cancelledAfterSeason: null,
    totalSeasons: 5,
    cliffhanger: false,
    cliffhangerNote: null,
    note: "Five seasons exploring the aftermath of an extramarital affair and a murder mystery. Showtime let the show run its course with a proper finale."
  },
  {
    id: 258,
    title: "American Rust",
    network: "Showtime",
    startYear: 2021,
    years: "2021–2023",
    genres: ["Crime", "Drama"],
    status: "cancelled",
    cancelledAfterSeason: 2,
    cliffhanger: true,
    cliffhangerNote: "The murder investigation and the Poe family's unresolved tensions in a dying Pennsylvania steel town are abandoned",
    note: "Jeff Daniels as a Pennsylvania sheriff covering up a murder. Showtime cancelled after Season 2 — the Rust Belt noir story left unfinished."
  },
  {
    id: 259,
    title: "City on a Hill",
    network: "Showtime",
    startYear: 2019,
    years: "2019–2022",
    genres: ["Crime", "Drama"],
    status: "cancelled",
    cancelledAfterSeason: 3,
    cliffhanger: true,
    cliffhangerNote: "Jackie Rohr's corruption arc and Decourcy Ward's crusade for justice are cut off mid-story in their Boston crime saga",
    note: "Kevin Bacon and Aldis Hodge in Ben Affleck and Matt Damon's Boston crime drama. Showtime cancelled after Season 3 with the story incomplete."
  },
  {
    id: 260,
    title: "Minx",
    network: "HBO Max / Starz",
    startYear: 2022,
    years: "2022–2023",
    genres: ["Comedy", "Drama"],
    status: "cancelled",
    cancelledAfterSeason: 2,
    cliffhanger: false,
    cliffhangerNote: "Season 2, made for Starz after HBO Max dropped the show, wrapped Joyce and Doug's story with a reasonable conclusion",
    note: "1970s feminist magazine comedy cancelled by HBO Max, rescued by Starz for Season 2, then cancelled again. A show with two lives and two deaths."
  },
  {
    id: 261,
    title: "Generation",
    tvmazeQuery: "Generation HBO",
    network: "HBO Max",
    startYear: 2021,
    years: "2021",
    genres: ["Drama", "Comedy", "YA"],
    status: "cancelled",
    cancelledAfterSeason: 1,
    cliffhanger: true,
    cliffhangerNote: "The teen ensemble's coming-of-age crises are abandoned mid-arc — a show about Gen Z queer teens cut off before its story began",
    note: "Lena Dunham-produced teen drama. HBO Max cancelled mid-season, pulling episodes that had already aired from the platform."
  },
  {
    id: 262,
    title: "Rap Sh!t",
    network: "HBO Max",
    startYear: 2022,
    years: "2022–2023",
    genres: ["Comedy", "Music", "Drama"],
    status: "cancelled",
    cancelledAfterSeason: 2,
    cliffhanger: true,
    cliffhangerNote: "Shawna and Mia's rap career breakthrough and fractured friendship are left open after their biggest moment",
    note: "Issa Rae's Miami rap duo comedy. HBO Max cancelled after Season 2 — the friendship-and-music story deserved at least one more season."
  },
  {
    id: 263,
    title: "His Dark Materials",
    network: "BBC / HBO",
    startYear: 2019,
    years: "2019–2022",
    genres: ["Fantasy", "Adventure", "Drama"],
    status: "ended",
    cancelledAfterSeason: null,
    totalSeasons: 3,
    cliffhanger: false,
    cliffhangerNote: null,
    note: "Dafne Keen as Lyra in Philip Pullman's epic. Three seasons adapted all three novels — a complete, faithful adaptation with a proper ending."
  },
  {
    id: 264,
    title: "The Watch",
    network: "BBC America",
    startYear: 2021,
    years: "2021",
    genres: ["Fantasy", "Comedy", "Action"],
    status: "cancelled",
    cancelledAfterSeason: 1,
    cliffhanger: true,
    cliffhangerNote: "The Ankh-Morpork City Watch's fight against the criminal guilds is abandoned in its first season",
    note: "Based loosely on Terry Pratchett's Discworld novels. Cancelled after one divisive season — purists rejected the loose adaptation, casuals found it confusing."
  },
  {
    id: 265,
    title: "Gentleman Jack",
    network: "BBC / HBO",
    startYear: 2019,
    years: "2019–2022",
    genres: ["Historical", "Drama", "Romance"],
    status: "cancelled",
    cancelledAfterSeason: 2,
    cliffhanger: true,
    cliffhangerNote: "Anne Lister and Ann Walker's lives after their church marriage and the coal mine battle are permanently unresolved",
    note: "Suranne Jones as Anne Lister, the 19th century's most extraordinary diarist. BBC/HBO cancelled after Season 2 with years of Lister's real diary left unexplored."
  },
  {
    id: 266,
    title: "Ghosts",
    tvmazeQuery: "Ghosts UK",
    network: "BBC",
    startYear: 2019,
    years: "2019–2023",
    genres: ["Comedy", "Fantasy"],
    status: "ended",
    cancelledAfterSeason: null,
    totalSeasons: 5,
    cliffhanger: false,
    cliffhangerNote: null,
    note: "The original UK Ghosts — a house full of ghosts from different eras of British history. Five complete seasons with a proper farewell. The US remake is still running."
  },
  {
    id: 267,
    title: "La Casa de Papel",
    tvmazeQuery: "La Casa de Papel",
    network: "Antena 3 / Netflix",
    startYear: 2017,
    years: "2017–2021",
    genres: ["Crime", "Action", "Thriller"],
    status: "ended",
    cancelledAfterSeason: null,
    totalSeasons: 5,
    cliffhanger: false,
    cliffhangerNote: null,
    note: "Spanish heist thriller that became Netflix's global phenomenon. Five seasons with a complete ending — one of the most-watched non-English shows ever."
  },
  {
    id: 269,
    title: "Barbarians",
    tvmazeQuery: "Barbarians 2020",
    network: "Netflix",
    startYear: 2020,
    years: "2020–2022",
    genres: ["Historical", "Action", "Drama"],
    status: "cancelled",
    cancelledAfterSeason: 2,
    cliffhanger: true,
    cliffhangerNote: "The Germanic tribes' conflict with Rome and Arminius's divided loyalties are left open after the Battle of Teutoburg Forest's aftermath",
    note: "German historical drama about the Battle of Teutoburg Forest. Netflix cancelled after Season 2 with the tribal war against Rome unresolved."
  },
  {
    id: 270,
    title: "Lupin",
    network: "Netflix",
    startYear: 2021,
    years: "2021–",
    genres: ["Crime", "Mystery", "Drama"],
    status: "running",
    cancelledAfterSeason: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: "Omar Sy as Assane Diop, inspired by Arsène Lupin. Still running — one of Netflix's biggest international hits, proving non-English shows can be global sensations."
  },
  {
    id: 271,
    title: "Squid Game",
    network: "Netflix",
    startYear: 2021,
    years: "2021–2025",
    genres: ["Thriller", "Sci-Fi", "Drama"],
    status: "ended",
    cancelledAfterSeason: null,
    totalSeasons: 3,
    cliffhanger: false,
    cliffhangerNote: null,
    note: "Hwang Dong-hyuk's death-game thriller — Netflix's most-watched series ever. Three seasons, a complete story. Season 3 concluded the show in 2025."
  },
  {
    id: 272,
    title: "Kingdom",
    tvmazeQuery: "Kingdom Netflix",
    network: "Netflix",
    startYear: 2019,
    years: "2019–2020",
    genres: ["Historical", "Horror", "Action"],
    status: "ended",
    cancelledAfterSeason: null,
    totalSeasons: 2,
    cliffhanger: false,
    cliffhangerNote: "A special episode 'Ashin of the North' served as a complete coda to the zombie story",
    note: "Korean historical zombie thriller set in the Joseon Dynasty. Two seasons plus a special episode — complete and stunning. One of Netflix's best original series."
  }
];
window.pageMetadata = {"page": 11, "totalPages": 19, "perPage": 24, "stats": {"total": 454, "cancelled": 297, "cliffhanger": 250, "ended": 132}};
