window.pageShows = [
  {
    id: 3241,
    tvmazeId: '35951',
    title: 'Foundation',
    network: 'Apple TV',
    startYear: 2021,
    years: '2021–',
    genres: ['Drama', 'Science-Fiction', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/573/1433544.jpg',
    note: '',
  },
  {
    id: 3242,
    tvmazeId: '46468',
    title: 'Frank of Ireland',
    network: 'Channel 4',
    startYear: 2021,
    years: '2021',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/301/752515.jpg',
    note: '',
  },
  {
    id: 3243,
    tvmazeId: '50214',
    title: 'Furia',
    network: 'Prime Video',
    startYear: 2021,
    years: '2021–2024',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/383/958182.jpg',
    note: '',
  },
  {
    id: 3244,
    tvmazeId: '61395',
    title: 'G.O.A.T.',
    network: 'Disney XD',
    startYear: 2021,
    years: '2021–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/402/1006769.jpg',
    note: '',
  },
  {
    id: 3245,
    tvmazeId: '51222',
    title: 'Gabby\'s Dollhouse',
    network: 'Netflix',
    startYear: 2021,
    years: '2021–',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/468/1172282.jpg',
    note: '',
  },
  {
    id: 3246,
    tvmazeId: '85130',
    title: 'Gary\'s Magic Fort',
    network: 'CBC Gem',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/571/1428833.jpg',
    note: '',
  },
  {
    id: 3247,
    tvmazeId: '45617',
    title: 'Genera+ion',
    network: 'HBO Max',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/322/805263.jpg',
    note: '',
  },
  {
    id: 3248,
    tvmazeId: '55787',
    title: 'Generazione 56k',
    network: 'Netflix',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/326/816621.jpg',
    note: '',
  },
  {
    id: 3249,
    tvmazeId: '57462',
    title: 'Get Rolling with Otis',
    network: 'Apple TV',
    startYear: 2021,
    years: '2021–',
    genres: ['Children'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/355/889422.jpg',
    note: '',
  },
  {
    id: 3250,
    tvmazeId: '58277',
    title: 'GhostForce',
    network: 'Disney XD',
    startYear: 2021,
    years: '2021–',
    genres: ['Comedy', 'Action', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/368/920535.jpg',
    note: '',
  },
  {
    id: 3251,
    tvmazeId: '46573',
    title: 'Ghosts',
    network: 'CBS',
    startYear: 2021,
    years: '2021–',
    genres: ['Comedy', 'Supernatural'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/590/1475093.jpg',
    note: '',
  },
  {
    id: 3252,
    tvmazeId: '83154',
    title: 'Gilly and Keeves',
    network: 'YouTube',
    startYear: 2021,
    years: '2021–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 3253,
    tvmazeId: '47549',
    title: 'Ginny & Georgia',
    network: 'Netflix',
    startYear: 2021,
    years: '2021–',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/570/1427139.jpg',
    note: '',
  },
  {
    id: 3254,
    tvmazeId: '49145',
    title: 'Girls5eva',
    network: 'Netflix',
    startYear: 2021,
    years: '2021–2024',
    genres: ['Comedy', 'Music'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/509/1273209.jpg',
    note: '',
  },
  {
    id: 3255,
    tvmazeId: '56362',
    title: 'Given',
    network: 'FOD',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Music', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/341/852644.jpg',
    note: '',
  },
  {
    id: 3256,
    tvmazeId: '50322',
    title: 'Glória',
    network: 'Netflix',
    startYear: 2021,
    years: '2021',
    genres: ['Thriller', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/368/921986.jpg',
    note: '',
  },
  {
    id: 3257,
    tvmazeId: '52969',
    title: 'Go, Dog. Go!',
    network: 'Netflix',
    startYear: 2021,
    years: '2021–',
    genres: ['Adventure', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/383/957587.jpg',
    note: '',
  },
  {
    id: 3258,
    tvmazeId: '74031',
    title: 'Goldie\'s Oldies',
    network: 'Nickelodeon',
    startYear: 2021,
    years: '2021',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/500/1250173.jpg',
    note: '',
  },
  {
    id: 3259,
    tvmazeId: '55708',
    title: 'Good Grief',
    network: 'TVNZ 1',
    startYear: 2021,
    years: '2021–',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/324/811340.jpg',
    note: '',
  },
  {
    id: 3260,
    tvmazeId: '55694',
    title: 'Good Luck Have Fun',
    network: 'YouTube',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/330/825709.jpg',
    note: '',
  },
  {
    id: 3261,
    tvmazeId: '43051',
    title: 'Gossip Girl',
    network: 'HBO Max',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Drama', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/447/1118408.jpg',
    note: '',
  },
  {
    id: 3262,
    tvmazeId: '45489',
    title: 'Grace',
    network: 'ITVX',
    startYear: 2021,
    years: '2021–',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/533/1332741.jpg',
    note: '',
  },
  {
    id: 3263,
    tvmazeId: '49439',
    title: 'Grand Crew',
    network: 'NBC',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/449/1123540.jpg',
    note: '',
  },
  {
    id: 3264,
    tvmazeId: '56280',
    title: 'Guerra de vecinos',
    network: 'Netflix',
    startYear: 2021,
    years: '2021–2022',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/337/843719.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 136, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 295, "ended": 12349}};
