window.pageShows = [
  {
    id: 1129,
    tvmazeId: '78887',
    title: 'Kindergarten: The Musical',
    network: 'Disney Junior',
    startYear: 2024,
    years: '2024–',
    genres: ['Children', 'Music'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/533/1334490.jpg',
    note: '',
  },
  {
    id: 1130,
    tvmazeId: '61066',
    title: 'Kite Man: Hell Yeah!',
    network: 'HBO Max',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy', 'Action', 'Adult'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: 'Max cancelled after one season; Kite Man and Golden Glider\'s Noonan\'s Bar storyline was unfinished.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/526/1315189.jpg',
    note: '',
  },
  {
    id: 1131,
    tvmazeId: '73184',
    title: 'Knight Flower',
    network: 'MBC',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/498/1246934.jpg',
    note: '',
  },
  {
    id: 1132,
    tvmazeId: '60808',
    title: 'Knuckles',
    network: 'Paramount+',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/510/1277082.jpg',
    note: '',
  },
  {
    id: 1133,
    tvmazeId: '73902',
    title: 'Komedi Kacau',
    network: 'Netflix',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/504/1261201.jpg',
    note: '',
  },
  {
    id: 1134,
    tvmazeId: '81370',
    title: 'Konflikti',
    network: 'MTV3',
    startYear: 2024,
    years: '2024–2025',
    genres: ['Drama', 'Action', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/547/1367820.jpg',
    note: '',
  },
  {
    id: 1135,
    tvmazeId: '74702',
    title: 'Kuvvetli Bir Alkış',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/506/1266389.jpg',
    note: '',
  },
  {
    id: 1136,
    tvmazeId: '73599',
    title: 'Kübra',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/500/1250782.jpg',
    note: '',
  },
  {
    id: 1137,
    tvmazeId: '80905',
    title: 'L\'amour sans',
    network: 'Canal+',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        note: '',
  },
  {
    id: 1138,
    tvmazeId: '72959',
    title: 'La cage',
    network: 'Netflix',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Action', 'Sports'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/488/1222483.jpg',
    note: '',
  },
  {
    id: 1139,
    tvmazeId: '72695',
    title: 'La Fièvre',
    network: 'Canal+',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/506/1266048.jpg',
    note: '',
  },
  {
    id: 1140,
    tvmazeId: '63924',
    title: 'La Máquina',
    network: 'Disney+',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/538/1345353.jpg',
    note: '',
  },
  {
    id: 1141,
    tvmazeId: '81135',
    title: 'La Palma',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/545/1364327.jpg',
    note: '',
  },
  {
    id: 1142,
    tvmazeId: '76239',
    title: 'La Partitura Secreta',
    network: 'Disney+',
    startYear: 2024,
    years: '2024–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/514/1287380.jpg',
    note: '',
  },
  {
    id: 1143,
    tvmazeId: '71424',
    title: 'La vita che volevi',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/521/1303493.jpg',
    note: '',
  },
  {
    id: 1144,
    tvmazeId: '78758',
    title: 'La Voz Ausente',
    network: 'Disney+',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/530/1325222.jpg',
    note: '',
  },
  {
    id: 1145,
    tvmazeId: '79486',
    title: 'La última noche en Tremor',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/540/1351540.jpg',
    note: '',
  },
  {
    id: 1146,
    tvmazeId: '77423',
    title: 'Ladies in Black',
    network: 'ABC iview',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/522/1305741.jpg',
    note: '',
  },
  {
    id: 1147,
    tvmazeId: '54016',
    title: 'Lady in the Lake',
    network: 'Apple TV',
    startYear: 2024,
    years: '2024',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/524/1310314.jpg',
    note: '',
  },
  {
    id: 1148,
    tvmazeId: '81338',
    title: 'Lady Love',
    network: 'HBO Max',
    startYear: 2024,
    years: '2024–2025',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/546/1367280.jpg',
    note: '',
  },
  {
    id: 1149,
    tvmazeId: '80346',
    title: 'Laid',
    network: 'Peacock',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/548/1370954.jpg',
    note: '',
  },
  {
    id: 1150,
    tvmazeId: '77134',
    title: 'Land of Tanabata',
    network: 'Disney+',
    startYear: 2024,
    years: '2024',
    genres: ['Science-Fiction', 'Mystery', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/526/1316597.jpg',
    note: '',
  },
  {
    id: 1151,
    tvmazeId: '53777',
    title: 'Landman',
    network: 'Paramount+',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/598/1495770.jpg',
    note: '',
  },
  {
    id: 1152,
    tvmazeId: '80507',
    title: 'Las hermanas Guerra',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/543/1358051.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 48, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
