window.pageShows = [
  {
    id: 5065,
    tvmazeId: '26775',
    title: 'AFK',
    network: 'YouTube',
    startYear: 2015,
    years: '2015–2019',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/105/263523.jpg',
    note: '',
  },
  {
    id: 5066,
    tvmazeId: '6780',
    title: 'After Hours',
    network: 'Sky Showcase',
    startYear: 2015,
    years: '2015',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/103/259512.jpg',
    note: '',
  },
  {
    id: 5067,
    tvmazeId: '3030',
    title: 'Agent X',
    network: 'TNT',
    startYear: 2015,
    years: '2015',
    genres: ['Drama', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/380/951829.jpg',
    note: '',
  },
  {
    id: 5068,
    tvmazeId: '38947',
    title: 'All of My Heart',
    network: 'Hallmark Channel',
    startYear: 2015,
    years: '2015–2018',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/169/424189.jpg',
    note: '',
  },
  {
    id: 5069,
    tvmazeId: '617',
    title: 'Allegiance',
    network: 'NBC',
    startYear: 2015,
    years: '2015',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/8/20832.jpg',
    note: '',
  },
  {
    id: 5070,
    tvmazeId: '2659',
    title: 'Alvinnn!!! and the Chipmunks',
    network: 'Nickelodeon',
    startYear: 2015,
    years: '2015–2023',
    genres: ['Children', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/210/526033.jpg',
    note: '',
  },
  {
    id: 5071,
    tvmazeId: '33435',
    title: 'Ambient',
    network: 'YouTube',
    startYear: 2015,
    years: '2015',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 5072,
    tvmazeId: '339',
    title: 'American Crime',
    network: 'ABC',
    startYear: 2015,
    years: '2015–2017',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/100/252315.jpg',
    note: '',
  },
  {
    id: 5073,
    tvmazeId: '1178',
    title: 'American Odyssey',
    network: 'NBC',
    startYear: 2015,
    years: '2015',
    genres: ['Action', 'Adventure', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/76/191429.jpg',
    note: '',
  },
  {
    id: 5074,
    tvmazeId: '23486',
    title: 'An American Girl Story',
    network: 'Prime Video',
    startYear: 2015,
    years: '2015–2023',
    genres: ['Drama', 'Children', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/103/258834.jpg',
    note: '',
  },
  {
    id: 5075,
    tvmazeId: '18109',
    title: 'Anamnesis',
    network: 'YouTube',
    startYear: 2015,
    years: '2015',
    genres: ['Drama', 'Science-Fiction', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/61/153440.jpg',
    note: '',
  },
  {
    id: 5076,
    tvmazeId: '4795',
    title: 'And Then There Were None',
    network: 'BBC One',
    startYear: 2015,
    years: '2015',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/77/192526.jpg',
    note: '',
  },
  {
    id: 5077,
    tvmazeId: '2240',
    title: 'Another Period',
    network: 'Comedy Central',
    startYear: 2015,
    years: '2015–2018',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/494/1235402.jpg',
    note: '',
  },
  {
    id: 5078,
    tvmazeId: '341',
    title: 'Aquarius',
    network: 'NBC',
    startYear: 2015,
    years: '2015–2016',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/38/95845.jpg',
    note: '',
  },
  {
    id: 5079,
    tvmazeId: '3062',
    title: 'Arthur & George',
    network: 'ITV1',
    startYear: 2015,
    years: '2015',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/487/1219271.jpg',
    note: '',
  },
  {
    id: 5080,
    tvmazeId: '2427',
    title: 'Ash vs Evil Dead',
    network: 'STARZ',
    startYear: 2015,
    years: '2015–2018',
    genres: ['Comedy', 'Action', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/145/363490.jpg',
    note: '',
  },
  {
    id: 5081,
    tvmazeId: '15456',
    title: 'Asylum',
    network: 'BBC Four',
    startYear: 2015,
    years: '2015',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/79/198013.jpg',
    note: '',
  },
  {
    id: 5082,
    tvmazeId: '37931',
    title: 'Auckward Love',
    network: 'TVNZ+',
    startYear: 2015,
    years: '2015–2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/528/1320617.jpg',
    note: '',
  },
  {
    id: 5083,
    tvmazeId: '621',
    title: 'Backstrom',
    network: 'FOX',
    startYear: 2015,
    years: '2015',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/19620.jpg',
    note: '',
  },
  {
    id: 5084,
    tvmazeId: '1821',
    title: 'Ballers',
    network: 'HBO',
    startYear: 2015,
    years: '2015–2019',
    genres: ['Drama', 'Comedy', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/498/1245483.jpg',
    note: '',
  },
  {
    id: 5085,
    tvmazeId: '9898',
    title: 'Ballot Monkeys',
    network: 'Channel 4',
    startYear: 2015,
    years: '2015',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/34/85151.jpg',
    note: '',
  },
  {
    id: 5086,
    tvmazeId: '3737',
    title: 'Banana',
    network: 'E4',
    startYear: 2015,
    years: '2015',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/80/201654.jpg',
    note: '',
  },
  {
    id: 5087,
    tvmazeId: '1833',
    title: 'Banished',
    network: 'BBC Two',
    startYear: 2015,
    years: '2015',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/80/201739.jpg',
    note: '',
  },
  {
    id: 5088,
    tvmazeId: '25270',
    title: 'Barbie Vlogs',
    network: 'YouTube',
    startYear: 2015,
    years: '2015–',
    genres: ['Comedy', 'Adventure', 'Music'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/431/1079912.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 212, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 856, "cliffhanger": 286, "ended": 13542}};
