window.pageShows = [
  {
    id: 11857,
    tvmazeId: '79875',
    title: 'Laura and Disorder',
    network: 'BBC One',
    startYear: 1989,
    years: '1989',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/609/1522714.jpg',
    note: '',
  },
  {
    id: 11858,
    tvmazeId: '4915',
    title: 'Life Goes On',
    network: 'ABC',
    startYear: 1989,
    years: '1989–1993',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/53621.jpg',
    note: '',
  },
  {
    id: 11859,
    tvmazeId: '38006',
    title: 'Live-In',
    network: 'CBS',
    startYear: 1989,
    years: '1989',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/162/406966.jpg',
    note: '',
  },
  {
    id: 11860,
    tvmazeId: '42898',
    title: 'Living Dolls',
    network: 'ABC',
    startYear: 1989,
    years: '1989',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/204/510909.jpg',
    note: '',
  },
  {
    id: 11861,
    tvmazeId: '7845',
    title: 'Lonesome Dove',
    network: 'CBS',
    startYear: 1989,
    years: '1989',
    genres: ['Drama', 'Adventure', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/72029.jpg',
    note: '',
  },
  {
    id: 11862,
    tvmazeId: '60865',
    title: 'Long Ago and Far Away',
    network: 'PBS',
    startYear: 1989,
    years: '1989–1992',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11863,
    tvmazeId: '10950',
    title: 'Maid Marian and Her Merry Men',
    network: 'BBC One',
    startYear: 1989,
    years: '1989–1994',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/36/92026.jpg',
    note: '',
  },
  {
    id: 11864,
    tvmazeId: '2131',
    title: 'Major Dad',
    network: 'CBS',
    startYear: 1989,
    years: '1989–1993',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/610/1526170.jpg',
    note: '',
  },
  {
    id: 11865,
    tvmazeId: '79729',
    title: 'Making News',
    network: 'ITV1',
    startYear: 1989,
    years: '1989–1990',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11866,
    tvmazeId: '42459',
    title: 'Making Out',
    network: 'BBC One',
    startYear: 1989,
    years: '1989–1991',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11867,
    tvmazeId: '22563',
    title: 'Mancuso, FBI',
    network: 'NBC',
    startYear: 1989,
    years: '1989–1990',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/294/735003.jpg',
    note: '',
  },
  {
    id: 11868,
    tvmazeId: '27028',
    title: 'May to December',
    network: 'BBC One',
    startYear: 1989,
    years: '1989–1994',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/106/267015.jpg',
    note: '',
  },
  {
    id: 11869,
    tvmazeId: '58325',
    title: 'Men',
    network: 'ABC',
    startYear: 1989,
    years: '1989',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11870,
    tvmazeId: '35740',
    title: 'Mike & Angelo',
    network: 'ITV1',
    startYear: 1989,
    years: '1989–2000',
    genres: ['Comedy', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/151/378035.jpg',
    note: '',
  },
  {
    id: 11871,
    tvmazeId: '78990',
    title: 'Morris Minor\'s Marvellous Motors',
    network: 'BBC One',
    startYear: 1989,
    years: '1989',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11872,
    tvmazeId: '18362',
    title: 'Mother Love',
    network: 'BBC One',
    startYear: 1989,
    years: '1989',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/62/156072.jpg',
    note: '',
  },
  {
    id: 11873,
    tvmazeId: '70408',
    title: 'Muzzy Comes Back',
    network: 'BBC One',
    startYear: 1989,
    years: '1989',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/471/1179450.jpg',
    note: '',
  },
  {
    id: 11874,
    tvmazeId: '52034',
    title: 'Nasty Boys',
    network: 'NBC',
    startYear: 1989,
    years: '1989–1990',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/284/711362.jpg',
    note: '',
  },
  {
    id: 11875,
    tvmazeId: '51858',
    title: 'Nearly Departed',
    network: 'NBC',
    startYear: 1989,
    years: '1989',
    genres: ['Comedy', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/282/706186.jpg',
    note: '',
  },
  {
    id: 11876,
    tvmazeId: '71253',
    title: 'Neon Rider',
    network: 'CTV',
    startYear: 1989,
    years: '1989–1991',
    genres: ['Drama', 'Action', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/477/1192622.jpg',
    note: '',
  },
  {
    id: 11877,
    tvmazeId: '24340',
    title: 'Nice Work',
    network: 'BBC Two',
    startYear: 1989,
    years: '1989',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/92/231474.jpg',
    note: '',
  },
  {
    id: 11878,
    tvmazeId: '28612',
    title: 'Nightmare Classics',
    network: 'Paramount+ with Showtime',
    startYear: 1989,
    years: '1989',
    genres: ['Horror', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/113/284715.jpg',
    note: '',
  },
  {
    id: 11879,
    tvmazeId: '80006',
    title: 'No Strings',
    network: 'ITV1',
    startYear: 1989,
    years: '1989',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11880,
    tvmazeId: '36756',
    title: 'Oceano',
    network: 'Rai 1',
    startYear: 1989,
    years: '1989',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/155/389402.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 495, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 856, "cliffhanger": 286, "ended": 13542}};
