window.pageShows = [
  {
    id: 13729,
    tvmazeId: '16455',
    title: 'What\'s Happening!!',
    network: 'ABC',
    startYear: 1976,
    years: '1976–1979',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/54/137094.jpg',
    note: '',
  },
  {
    id: 13730,
    tvmazeId: '10422',
    title: 'When the Boat Comes In',
    network: 'BBC One',
    startYear: 1976,
    years: '1976–1981',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/35/88076.jpg',
    note: '',
  },
  {
    id: 13731,
    tvmazeId: '10758',
    title: 'Yanks Go Home',
    network: 'ITV1',
    startYear: 1976,
    years: '1976–1977',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/36/90692.jpg',
    note: '',
  },
  {
    id: 13732,
    tvmazeId: '48701',
    title: 'Yes, Honestly',
    network: 'ITV1',
    startYear: 1976,
    years: '1976–1977',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/261/654397.jpg',
    note: '',
  },
  {
    id: 13733,
    tvmazeId: '20966',
    title: 'Yus, My Dear',
    network: 'ITV1',
    startYear: 1976,
    years: '1976',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/184996.jpg',
    note: '',
  },
  {
    id: 13734,
    tvmazeId: '74936',
    title: 'Adams of Eagle Lake',
    network: 'ABC',
    startYear: 1975,
    years: '1975',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 13735,
    tvmazeId: '9524',
    title: 'Angels',
    network: 'BBC One',
    startYear: 1975,
    years: '1975–1983',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/83363.jpg',
    note: '',
  },
  {
    id: 13736,
    tvmazeId: '23341',
    title: 'Anne of Avonlea',
    network: 'BBC One',
    startYear: 1975,
    years: '1975',
    genres: ['Drama', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/87/219370.jpg',
    note: '',
  },
  {
    id: 13737,
    tvmazeId: '57529',
    title: 'Archer',
    network: 'NBC',
    startYear: 1975,
    years: '1975',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/626/1566414.jpg',
    note: '',
  },
  {
    id: 13738,
    tvmazeId: '13088',
    title: 'Barbary Coast',
    network: 'ABC',
    startYear: 1975,
    years: '1975–1976',
    genres: ['Action', 'Adventure', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/45/112545.jpg',
    note: '',
  },
  {
    id: 13739,
    tvmazeId: '8092',
    title: 'Baretta',
    network: 'ABC',
    startYear: 1975,
    years: '1975–1978',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/73504.jpg',
    note: '',
  },
  {
    id: 13740,
    tvmazeId: '5782',
    title: 'Barney Miller',
    network: 'ABC',
    startYear: 1975,
    years: '1975–1982',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/206/515173.jpg',
    note: '',
  },
  {
    id: 13741,
    tvmazeId: '39276',
    title: 'Beacon Hill',
    network: 'CBS',
    startYear: 1975,
    years: '1975',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/172/431277.jpg',
    note: '',
  },
  {
    id: 13742,
    tvmazeId: '49079',
    title: 'Black Bart',
    network: 'CBS',
    startYear: 1975,
    years: '1975',
    genres: ['Comedy', 'Crime', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/264/660468.jpg',
    note: '',
  },
  {
    id: 13743,
    tvmazeId: '7764',
    title: 'Bod',
    network: 'BBC One',
    startYear: 1975,
    years: '1975',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/71467.jpg',
    note: '',
  },
  {
    id: 13744,
    tvmazeId: '56884',
    title: 'Bronk',
    network: 'CBS',
    startYear: 1975,
    years: '1975–1976',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/349/873067.jpg',
    note: '',
  },
  {
    id: 13745,
    tvmazeId: '30204',
    title: 'Caribe',
    network: 'ABC',
    startYear: 1975,
    years: '1975',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/367/918470.jpg',
    note: '',
  },
  {
    id: 13746,
    tvmazeId: '11281',
    title: 'Carry On Laughing',
    network: 'ITV1',
    startYear: 1975,
    years: '1975',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/38/95258.jpg',
    note: '',
  },
  {
    id: 13747,
    tvmazeId: '47793',
    title: 'Cash and Company',
    network: 'London Weekend Television',
    startYear: 1975,
    years: '1975',
    genres: ['Drama', 'Action', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/255/637905.jpg',
    note: '',
  },
  {
    id: 13748,
    tvmazeId: '22604',
    title: 'Cilla\'s Comedy Six',
    network: 'ITV1',
    startYear: 1975,
    years: '1975',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/83/208624.jpg',
    note: '',
  },
  {
    id: 13749,
    tvmazeId: '75538',
    title: 'Dawson\'s Weekly',
    network: 'ITV1',
    startYear: 1975,
    years: '1975',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/509/1274632.jpg',
    note: '',
  },
  {
    id: 13750,
    tvmazeId: '50909',
    title: 'Days of Hope',
    network: 'BBC One',
    startYear: 1975,
    years: '1975',
    genres: ['Drama', 'Family', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/276/690639.jpg',
    note: '',
  },
  {
    id: 13751,
    tvmazeId: '56807',
    title: 'Doctor on the Go',
    network: 'ITV1',
    startYear: 1975,
    years: '1975–1977',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/348/870455.jpg',
    note: '',
  },
  {
    id: 13752,
    tvmazeId: '64762',
    title: 'Doctors\' Hospital',
    network: 'NBC',
    startYear: 1975,
    years: '1975–1976',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/478/1195383.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 573, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 334, "cliffhanger": 235, "ended": 13701}};
