window.pageShows = [
  {
    id: 13681,
    tvmazeId: '59839',
    title: 'Power Without Glory',
    network: 'ABC',
    startYear: 1976,
    years: '1976',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/388/971260.jpg',
    note: '',
  },
  {
    id: 13682,
    tvmazeId: '841',
    title: 'Quincy, M.E.',
    network: 'NBC',
    startYear: 1976,
    years: '1976–1983',
    genres: ['Drama', 'Crime', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/15814.jpg',
    note: '',
  },
  {
    id: 13683,
    tvmazeId: '41183',
    title: 'Red Letter Day',
    network: 'ITV1',
    startYear: 1976,
    years: '1976',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/186/465480.jpg',
    note: '',
  },
  {
    id: 13684,
    tvmazeId: '8642',
    title: 'Rentaghost',
    network: 'BBC One',
    startYear: 1976,
    years: '1976–1984',
    genres: ['Comedy', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/30/76982.jpg',
    note: '',
  },
  {
    id: 13685,
    tvmazeId: '13349',
    title: 'Rich Man, Poor Man',
    network: 'ABC',
    startYear: 1976,
    years: '1976–1977',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/46/115542.jpg',
    note: '',
  },
  {
    id: 13686,
    tvmazeId: '16572',
    title: 'Ripping Yarns',
    network: 'BBC Two',
    startYear: 1976,
    years: '1976–1979',
    genres: ['Comedy', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/55/138059.jpg',
    note: '',
  },
  {
    id: 13687,
    tvmazeId: '13352',
    title: 'Rock Follies',
    network: 'ITV1',
    startYear: 1976,
    years: '1976–1977',
    genres: ['Drama', 'Comedy', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/46/115556.jpg',
    note: '',
  },
  {
    id: 13688,
    tvmazeId: '28926',
    title: 'Sara',
    network: 'CBS',
    startYear: 1976,
    years: '1976',
    genres: ['Drama', 'Family', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/115/288285.jpg',
    note: '',
  },
  {
    id: 13689,
    tvmazeId: '5762',
    title: 'SCTV',
    network: 'Crave',
    startYear: 1976,
    years: '1976–1981',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/57455.jpg',
    note: '',
  },
  {
    id: 13690,
    tvmazeId: '33080',
    title: 'Second Verdict',
    network: 'BBC One',
    startYear: 1976,
    years: '1976',
    genres: ['Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 13691,
    tvmazeId: '24582',
    title: 'Serpico',
    network: 'NBC',
    startYear: 1976,
    years: '1976',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/93/234857.jpg',
    note: '',
  },
  {
    id: 13692,
    tvmazeId: '23970',
    title: 'Sirota\'s Court',
    network: 'NBC',
    startYear: 1976,
    years: '1976–1977',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/90/226751.jpg',
    note: '',
  },
  {
    id: 13693,
    tvmazeId: '5769',
    title: 'Spencer\'s Pilots',
    network: 'CBS',
    startYear: 1976,
    years: '1976',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/57526.jpg',
    note: '',
  },
  {
    id: 13694,
    tvmazeId: '3672',
    title: 'Star Maidens',
    network: 'ITV1',
    startYear: 1976,
    years: '1976',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/47355.jpg',
    note: '',
  },
  {
    id: 13695,
    tvmazeId: '25062',
    title: 'Sybil',
    network: 'NBC',
    startYear: 1976,
    years: '1976',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/96/241925.jpg',
    note: '',
  },
  {
    id: 13696,
    tvmazeId: '23041',
    title: 'Tabitha',
    network: 'ABC',
    startYear: 1976,
    years: '1976–1978',
    genres: ['Comedy', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/85/214210.jpg',
    note: '',
  },
  {
    id: 13697,
    tvmazeId: '47795',
    title: 'Tandarra',
    network: 'London Weekend Television',
    startYear: 1976,
    years: '1976',
    genres: ['Drama', 'Action', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/255/637921.jpg',
    note: '',
  },
  {
    id: 13698,
    tvmazeId: '18921',
    title: 'Tarzan, Lord of the Jungle',
    network: 'CBS',
    startYear: 1976,
    years: '1976–1979',
    genres: ['Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/65/163366.jpg',
    note: '',
  },
  {
    id: 13699,
    tvmazeId: '18574',
    title: 'The Adams Chronicles',
    network: 'PBS',
    startYear: 1976,
    years: '1976',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/63/158232.jpg',
    note: '',
  },
  {
    id: 13700,
    tvmazeId: '2140',
    title: 'The Bionic Woman',
    network: 'NBC',
    startYear: 1976,
    years: '1976–1978',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/29899.jpg',
    note: '',
  },
  {
    id: 13701,
    tvmazeId: '57552',
    title: 'The Cedar Tree',
    network: 'ITV1',
    startYear: 1976,
    years: '1976–1978',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/356/891610.jpg',
    note: '',
  },
  {
    id: 13702,
    tvmazeId: '13354',
    title: 'The Duchess of Duke Street',
    network: 'BBC One',
    startYear: 1976,
    years: '1976–1977',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/46/115561.jpg',
    note: '',
  },
  {
    id: 13703,
    tvmazeId: '2077',
    title: 'The Fall and Rise of Reginald Perrin',
    network: 'BBC One',
    startYear: 1976,
    years: '1976–1979',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/28838.jpg',
    note: '',
  },
  {
    id: 13704,
    tvmazeId: '44311',
    title: 'The Feather and Father Gang',
    network: 'ABC',
    startYear: 1976,
    years: '1976–1977',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/214/536602.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 571, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 824, "cliffhanger": 237, "ended": 13574}};
