window.pageShows = [
  {
    id: 1753,
    tvmazeId: '55712',
    title: 'Ridley',
    network: 'PBS',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/423/1058628.jpg',
    note: '',
  },
  {
    id: 1754,
    tvmazeId: '63055',
    title: 'Riptide',
    network: '5',
    startYear: 2022,
    years: '2022',
    genres: ['Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/435/1089351.jpg',
    note: '',
  },
  {
    id: 1755,
    tvmazeId: '60330',
    title: 'Rise Up, Sing Out checkifcancelled',
    network: 'Disney Junior',
    startYear: 2022,
    years: '2022–',
    genres: ['Children', 'Family', 'Music'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/394/987047.jpg',
    note: '',
  },
  {
    id: 1756,
    tvmazeId: '53884',
    title: 'Roar',
    network: 'Apple TV',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/401/1003804.jpg',
    note: '',
  },
  {
    id: 1757,
    tvmazeId: '61813',
    title: 'Rock Island Mysteries',
    network: 'Nickelodeon',
    startYear: 2022,
    years: '2022–',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/548/1372193.jpg',
    note: '',
  },
  {
    id: 1758,
    tvmazeId: '62124',
    title: 'Romantic Getaway checkifcancelled',
    network: 'Now',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/437/1094959.jpg',
    note: '',
  },
  {
    id: 1759,
    tvmazeId: '64678',
    title: 'Roots & Fruits',
    network: 'BBC iPlayer',
    startYear: 2022,
    years: '2022–2024',
    genres: ['Comedy', 'Food', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/427/1069329.jpg',
    note: '',
  },
  {
    id: 1760,
    tvmazeId: '62175',
    title: 'Rosie Molloy Gives Up Everything',
    network: 'Now',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/431/1079680.jpg',
    note: '',
  },
  {
    id: 1761,
    tvmazeId: '75184',
    title: 'Rosie\'s Rules',
    network: 'PBS Kids',
    startYear: 2022,
    years: '2022–',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/507/1268651.jpg',
    note: '',
  },
  {
    id: 1762,
    tvmazeId: '60591',
    title: 'Ruby and the Well',
    network: 'BYUtv.org',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Family', 'Fantasy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/440/1100079.jpg',
    note: '',
  },
  {
    id: 1763,
    tvmazeId: '54405',
    title: 'Rules of the Game',
    network: 'BBC iPlayer',
    startYear: 2022,
    years: '2022',
    genres: ['Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/387/968478.jpg',
    note: '',
  },
  {
    id: 1764,
    tvmazeId: '54337',
    title: 'Run the Burbs',
    network: 'CBC',
    startYear: 2022,
    years: '2022–2024',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/388/970654.jpg',
    note: '',
  },
  {
    id: 1765,
    tvmazeId: '63843',
    title: 'Sago Mini Friends checkifcancelled',
    network: 'Apple TV',
    startYear: 2022,
    years: '2022–',
    genres: ['Children', 'Music'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/420/1051559.jpg',
    note: '',
  },
  {
    id: 1766,
    tvmazeId: '62419',
    title: 'Salvage Marines',
    network: 'Popcornflix',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/416/1040608.jpg',
    note: '',
  },
  {
    id: 1767,
    tvmazeId: '43539',
    title: 'SAS: Rogue Heroes',
    network: 'BBC iPlayer',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'War', 'History'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/547/1368034.jpg',
    note: '',
  },
  {
    id: 1768,
    tvmazeId: '61661',
    title: 'Savage Beauty checkifcancelled',
    network: 'Netflix',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/405/1014218.jpg',
    note: '',
  },
  {
    id: 1769,
    tvmazeId: '59190',
    title: 'Savage River',
    network: 'ABC',
    startYear: 2022,
    years: '2022',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/419/1049999.jpg',
    note: '',
  },
  {
    id: 1770,
    tvmazeId: '66071',
    title: 'Saving Me checkifcancelled',
    network: 'BYUtv.org',
    startYear: 2022,
    years: '2022–',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/437/1094496.jpg',
    note: '',
  },
  {
    id: 1771,
    tvmazeId: '50069',
    title: 'Screw',
    network: 'Channel 4',
    startYear: 2022,
    years: '2022–2023',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/392/980120.jpg',
    note: '',
  },
  {
    id: 1772,
    tvmazeId: '62229',
    title: 'Sea of Love',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/410/1025003.jpg',
    note: '',
  },
  {
    id: 1773,
    tvmazeId: '61186',
    title: 'Send Help checkifcancelled',
    network: 'ALLBLK',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/417/1042502.jpg',
    note: '',
  },
  {
    id: 1774,
    tvmazeId: '61911',
    title: 'Sesame Street Mecha Builders',
    network: 'Cartoon Network',
    startYear: 2022,
    years: '2022–2023',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/407/1019173.jpg',
    note: '',
  },
  {
    id: 1775,
    tvmazeId: '44933',
    title: 'Severance',
    network: 'Apple TV',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Science-Fiction', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/548/1371406.jpg',
    note: '',
  },
  {
    id: 1776,
    tvmazeId: '72380',
    title: 'Shadow of the Rougarou checkifcancelled',
    network: 'APTN Lumi',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Horror', 'Western'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/484/1210684.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 74, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 824, "cliffhanger": 237, "ended": 13574}};
