window.pageShows = [
  {
    id: 5069,
    tvmazeId: '38161',
    title: 'Casey Tries His Best',
    network: 'Comedy Central',
    startYear: 2018,
    years: '2018',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/326/815512.jpg',
    note: '',
  },
  {
    id: 5070,
    tvmazeId: '57783',
    title: 'Castle & Castle',
    network: 'Netflix',
    startYear: 2018,
    years: '2018–2021',
    genres: ['Drama', 'Legal'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/359/898090.jpg',
    note: '',
  },
  {
    id: 5071,
    tvmazeId: '25414',
    title: 'Castle Rock',
    network: 'Hulu',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Drama', 'Horror', 'Thriller'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/214/536992.jpg',
    note: '',
  },
  {
    id: 5072,
    tvmazeId: '17307',
    title: 'Caught',
    network: 'CBC',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/137/344415.jpg',
    note: '',
  },
  {
    id: 5073,
    tvmazeId: '39960',
    title: 'Champaign ILL',
    network: 'YouTube Premium',
    startYear: 2018,
    years: '2018',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/176/441322.jpg',
    note: '',
  },
  {
    id: 5074,
    tvmazeId: '28166',
    title: 'Champions',
    network: 'NBC',
    startYear: 2018,
    years: '2018',
    genres: ['Comedy', 'Family'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/145/362707.jpg',
    note: '',
  },
  {
    id: 5075,
    tvmazeId: '24267',
    title: 'Charmed',
    network: 'The CW',
    startYear: 2018,
    years: '2018–2022',
    genres: ['Drama', 'Mystery', 'Supernatural'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/401/1003373.jpg',
    note: '',
  },
  {
    id: 5076,
    tvmazeId: '32649',
    title: 'Chilling Adventures of Sabrina',
    network: 'Netflix',
    startYear: 2018,
    years: '2018–2020',
    genres: ['Horror', 'Romance', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/291/728576.jpg',
    note: '',
  },
  {
    id: 5077,
    tvmazeId: '45251',
    title: 'Chip and Potato',
    network: 'Family Jr.',
    startYear: 2018,
    years: '2018–2022',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/228/571838.jpg',
    note: '',
  },
  {
    id: 5078,
    tvmazeId: '38497',
    title: 'Chop Chop Ninja',
    network: 'Cartoon Network',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/166/415699.jpg',
    note: '',
  },
  {
    id: 5079,
    tvmazeId: '38435',
    title: 'Chris P. Duck',
    network: 'Cartoon Hangover',
    startYear: 2018,
    years: '2018',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/165/414384.jpg',
    note: '',
  },
  {
    id: 5080,
    tvmazeId: '36662',
    title: 'CLAIREvoyant',
    network: 'YouTube',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Comedy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/155/388069.jpg',
    note: '',
  },
  {
    id: 5081,
    tvmazeId: '39405',
    title: 'Class of Lies',
    network: 'Snapchat',
    startYear: 2018,
    years: '2018',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/219/549858.jpg',
    note: '',
  },
  {
    id: 5082,
    tvmazeId: '74106',
    title: 'Claude',
    network: 'Disney Junior',
    startYear: 2018,
    years: '2018',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/500/1251244.jpg',
    note: '',
  },
  {
    id: 5083,
    tvmazeId: '41513',
    title: 'CliffSide',
    network: 'YouTube',
    startYear: 2018,
    years: '2018',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/189/474247.jpg',
    note: '',
  },
  {
    id: 5084,
    tvmazeId: '37252',
    title: 'Club de Cuervos presenta: La balada de Hugo Sánchez',
    network: 'Netflix',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Comedy', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/159/398009.jpg',
    note: '',
  },
  {
    id: 5085,
    tvmazeId: '55396',
    title: 'Co-Ed',
    network: 'Snapchat',
    startYear: 2018,
    years: '2018',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/318/796248.jpg',
    note: '',
  },
  {
    id: 5086,
    tvmazeId: '30960',
    title: 'Cobra Kai',
    network: 'Netflix',
    startYear: 2018,
    years: '2018–2025',
    genres: ['Drama', 'Comedy', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/536/1340290.jpg',
    note: '',
  },
  {
    id: 5087,
    tvmazeId: '26868',
    title: 'Collateral',
    network: 'BBC Two',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/146/366909.jpg',
    note: '',
  },
  {
    id: 5088,
    tvmazeId: '31576',
    title: 'Come Home',
    network: 'BBC One',
    startYear: 2018,
    years: '2018',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/152/382352.jpg',
    note: '',
  },
  {
    id: 5089,
    tvmazeId: '91115',
    title: 'Comedy InvAsian',
    network: 'Hulu',
    startYear: 2018,
    years: '2018–2021',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/619/1549460.jpg',
    note: '',
  },
  {
    id: 5090,
    tvmazeId: '25110',
    title: 'Condor',
    network: 'Pickbox NOW',
    startYear: 2018,
    years: '2018–2020',
    genres: ['Drama', 'Action', 'Espionage'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/445/1113850.jpg',
    note: '',
  },
  {
    id: 5091,
    tvmazeId: '71455',
    title: 'Conframa',
    network: 'OUTtv',
    startYear: 2018,
    years: '2018–2022',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/478/1195747.jpg',
    note: '',
  },
  {
    id: 5092,
    tvmazeId: '24351',
    title: 'Constantine: City of Demons',
    network: 'CW Seed',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Drama', 'Horror', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/150/376009.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 212, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
