window.pageShows = [
  {
    id: 505,
    tvmazeId: '78727',
    title: 'Trespasses',
    network: 'Channel 4',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Romance', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/596/1491402.jpg',
    note: '',
  },
  {
    id: 506,
    tvmazeId: '88407',
    title: 'Truth & Treason',
    network: 'Angel Studios',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Thriller', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/598/1496599.jpg',
    note: '',
  },
  {
    id: 507,
    tvmazeId: '83406',
    title: 'Twelve Dates \'Til Christmas',
    network: 'Hallmark Channel',
    startYear: 2025,
    years: '2025',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/601/1504735.jpg',
    note: '',
  },
  {
    id: 508,
    tvmazeId: '84490',
    title: 'Tyler Perry\'s Divorced Sistas',
    network: 'Paramount+',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/573/1433267.jpg',
    note: '',
  },
  {
    id: 509,
    tvmazeId: '82484',
    title: 'Unconventional',
    network: 'Revry',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/555/1387784.jpg',
    note: '',
  },
  {
    id: 510,
    tvmazeId: '75342',
    title: 'Untamed',
    network: 'Netflix',
    startYear: 2025,
    years: '2025–',
    genres: ['Crime', 'Thriller', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/579/1447918.jpg',
    note: '',
  },
  {
    id: 511,
    tvmazeId: '83194',
    title: 'Urvi Went To An All Girls School',
    network: 'ABC iview',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/594/1486451.jpg',
    note: '',
  },
  {
    id: 512,
    tvmazeId: '80543',
    title: 'Vampirina: Teenage Vampire',
    network: 'DisneyNOW',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy', 'Music', 'Supernatural'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/587/1468841.jpg',
    note: '',
  },
  {
    id: 513,
    tvmazeId: '77782',
    title: 'Video Nasty',
    network: 'BBC iPlayer',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/551/1377698.jpg',
    note: '',
  },
  {
    id: 514,
    tvmazeId: '82754',
    title: 'Vince',
    network: 'Three',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/556/1391908.jpg',
    note: '',
  },
  {
    id: 515,
    tvmazeId: '70857',
    title: 'Virdee',
    network: 'BBC iPlayer',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/554/1386046.jpg',
    note: '',
  },
  {
    id: 516,
    tvmazeId: '86711',
    title: 'Waffle\'s After School Club',
    network: 'BBC iPlayer',
    startYear: 2025,
    years: '2025–',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/585/1463056.jpg',
    note: '',
  },
  {
    id: 517,
    tvmazeId: '85671',
    title: 'Warm Props',
    network: 'SBS On Demand',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/576/1441611.jpg',
    note: '',
  },
  {
    id: 518,
    tvmazeId: '85798',
    title: 'Warren\'s Vortex',
    network: 'TVNZ 2',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy', 'Fantasy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/577/1443237.jpg',
    note: '',
  },
  {
    id: 519,
    tvmazeId: '58213',
    title: 'Washington Black',
    network: 'Hulu',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/579/1448943.jpg',
    note: '',
  },
  {
    id: 520,
    tvmazeId: '82696',
    title: 'Watching You',
    network: 'Stan',
    startYear: 2025,
    years: '2025',
    genres: ['Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/590/1476418.jpg',
    note: '',
  },
  {
    id: 521,
    tvmazeId: '64507',
    title: 'Watson',
    network: 'CBS',
    startYear: 2025,
    years: '2025–2026',
    genres: ['Drama', 'Mystery', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/590/1476556.jpg',
    note: '',
  },
  {
    id: 522,
    tvmazeId: '67919',
    title: 'Wayward',
    network: 'Netflix',
    startYear: 2025,
    years: '2025',
    genres: ['Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/589/1472932.jpg',
    note: '',
  },
  {
    id: 523,
    tvmazeId: '67627',
    title: 'We Were Liars',
    network: 'Prime Video',
    startYear: 2025,
    years: '2025–',
    genres: ['Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/572/1431040.jpg',
    note: '',
  },
  {
    id: 524,
    tvmazeId: '87254',
    title: 'Weather Hunters',
    network: 'PBS Kids',
    startYear: 2025,
    years: '2025–',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/588/1471541.jpg',
    note: '',
  },
  {
    id: 525,
    tvmazeId: '83195',
    title: 'Westerners',
    network: 'ABC iview',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/594/1486450.jpg',
    note: '',
  },
  {
    id: 526,
    tvmazeId: '82749',
    title: 'What It Feels Like for a Girl',
    network: 'BBC iPlayer',
    startYear: 2025,
    years: '2025',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/571/1428516.jpg',
    note: '',
  },
  {
    id: 527,
    tvmazeId: '89497',
    title: 'Wicked Game',
    network: 'My Drama',
    startYear: 2025,
    years: '2025',
    genres: ['Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/606/1515884.jpg',
    note: '',
  },
  {
    id: 528,
    tvmazeId: '80587',
    title: 'Wild Cherry',
    network: 'BBC iPlayer',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/598/1496018.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 22, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 334, "cliffhanger": 235, "ended": 13701}};
