window.pageShows = [
  {
    id: 16057,
    tvmazeId: '3879',
    title: 'The Sixth Sense',
    network: 'ABC',
    startYear: 1972,
    years: '1972',
    genres: ['Drama', 'Mystery', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/48677.jpg',
    note: '',
  },
  {
    id: 16058,
    tvmazeId: '10595',
    title: 'The Snoop Sisters',
    network: 'NBC',
    startYear: 1972,
    years: '1972–1974',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/35/89268.jpg',
    note: '',
  },
  {
    id: 16059,
    tvmazeId: '7577',
    title: 'The Streets of San Francisco',
    network: 'ABC',
    startYear: 1972,
    years: '1972–1992',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/69773.jpg',
    note: '',
  },
  {
    id: 16060,
    tvmazeId: '39534',
    title: 'The Super',
    network: 'ABC',
    startYear: 1972,
    years: '1972',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/377/942594.jpg',
    note: '',
  },
  {
    id: 16061,
    tvmazeId: '3309',
    title: 'The Waltons',
    network: 'CBS',
    startYear: 1972,
    years: '1972–1981',
    genres: ['Drama', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/17/44012.jpg',
    note: '',
  },
  {
    id: 16062,
    tvmazeId: '10693',
    title: 'Van der Valk',
    network: 'ITV1',
    startYear: 1972,
    years: '1972–1992',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/36/90238.jpg',
    note: '',
  },
  {
    id: 16063,
    tvmazeId: '32832',
    title: 'Villains',
    network: 'ITV1',
    startYear: 1972,
    years: '1972',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/132/330330.jpg',
    note: '',
  },
  {
    id: 16064,
    tvmazeId: '9405',
    title: 'Wait Till Your Father Gets Home',
    network: 'Syndication',
    startYear: 1972,
    years: '1972–1974',
    genres: ['Comedy', 'Adult'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/82677.jpg',
    note: '',
  },
  {
    id: 16065,
    tvmazeId: '13505',
    title: 'War & Peace',
    network: 'BBC One',
    startYear: 1972,
    years: '1972–1973',
    genres: ['Drama', 'Romance', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/46/116628.jpg',
    note: '',
  },
  {
    id: 16066,
    tvmazeId: '86411',
    title: 'Who Do You Do',
    network: 'London Weekend Television',
    startYear: 1972,
    years: '1972–1976',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 16067,
    tvmazeId: '3184',
    title: 'Alias Smith and Jones',
    network: 'ABC',
    startYear: 1971,
    years: '1971–1973',
    genres: ['Action', 'Adventure', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/17/43394.jpg',
    note: '',
  },
  {
    id: 16068,
    tvmazeId: '1784',
    title: 'All in the Family',
    network: 'CBS',
    startYear: 1971,
    years: '1971–1979',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/605/1513713.jpg',
    note: '',
  },
  {
    id: 16069,
    tvmazeId: '50055',
    title: 'And Mother Makes Three',
    network: 'ITV1',
    startYear: 1971,
    years: '1971–1973',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/270/677475.jpg',
    note: '',
  },
  {
    id: 16070,
    tvmazeId: '72177',
    title: 'Archie\'s TV Funnies',
    network: 'CBS',
    startYear: 1971,
    years: '1971',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/483/1208339.jpg',
    note: '',
  },
  {
    id: 16071,
    tvmazeId: '57573',
    title: 'Barlow at Large',
    network: 'BBC One',
    startYear: 1971,
    years: '1971–1975',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 16072,
    tvmazeId: '62073',
    title: 'Barrier Reef',
    network: 'BBC One',
    startYear: 1971,
    years: '1971',
    genres: ['Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/408/1021881.jpg',
    note: '',
  },
  {
    id: 16073,
    tvmazeId: '57609',
    title: 'Bearcats!',
    network: 'CBS',
    startYear: 1971,
    years: '1971',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/357/892868.jpg',
    note: '',
  },
  {
    id: 16074,
    tvmazeId: '7763',
    title: 'Bless This House',
    network: 'ITV1',
    startYear: 1971,
    years: '1971–1976',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/71465.jpg',
    note: '',
  },
  {
    id: 16075,
    tvmazeId: '62168',
    title: 'Brett',
    network: 'BBC One',
    startYear: 1971,
    years: '1971',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 16076,
    tvmazeId: '11019',
    title: 'Budgie',
    network: 'ITV1',
    startYear: 1971,
    years: '1971–1972',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/37/92666.jpg',
    note: '',
  },
  {
    id: 16077,
    tvmazeId: '38019',
    title: 'Cade\'s County',
    network: 'CBS',
    startYear: 1971,
    years: '1971–1972',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/337/844539.jpg',
    note: '',
  },
  {
    id: 16078,
    tvmazeId: '3561',
    title: 'Cannon',
    network: 'CBS',
    startYear: 1971,
    years: '1971–1976',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/46709.jpg',
    note: '',
  },
  {
    id: 16079,
    tvmazeId: '42373',
    title: 'Casanova',
    network: 'BBC One',
    startYear: 1971,
    years: '1971',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/200/500062.jpg',
    note: '',
  },
  {
    id: 16080,
    tvmazeId: '49271',
    title: 'Eerie Street',
    network: 'ABC',
    startYear: 1971,
    years: '1971–1973',
    genres: ['Comedy', 'Horror', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  }
];
window.pageMetadata = {"page": 670, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
