window.pageShows = [
  {
    id: 529,
    tvmazeId: '52363',
    title: 'Win or Lose',
    network: 'Disney+',
    startYear: 2025,
    years: '2025',
    genres: ['Comedy', 'Family', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/557/1393426.jpg',
    note: '',
  },
  {
    id: 530,
    tvmazeId: '87081',
    title: 'Winx Club: The Magic is Back',
    network: 'BBC iPlayer',
    startYear: 2025,
    years: '2025–',
    genres: ['Adventure', 'Children', 'Fantasy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/614/1535087.jpg',
    note: '',
  },
  {
    id: 531,
    tvmazeId: '72015',
    title: 'Wonderblocks',
    network: 'BBC iPlayer',
    startYear: 2025,
    years: '2025–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/553/1383970.jpg',
    note: '',
  },
  {
    id: 532,
    tvmazeId: '86097',
    title: 'Wrong Number',
    network: 'YouTube',
    startYear: 2025,
    years: '2025',
    genres: ['Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/579/1448584.jpg',
    note: '',
  },
  {
    id: 533,
    tvmazeId: '83144',
    title: 'Wylde Pak',
    network: 'Nickelodeon',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy', 'Family'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/571/1427598.jpg',
    note: '',
  },
  {
    id: 534,
    tvmazeId: '58952',
    title: 'Your Friendly Neighborhood Spider-Man',
    network: 'Disney+',
    startYear: 2025,
    years: '2025–',
    genres: ['Action', 'Science-Fiction'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/556/1391478.jpg',
    note: '',
  },
  {
    id: 535,
    tvmazeId: '73484',
    title: 'Your Friends & Neighbors',
    network: 'Apple TV',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/620/1550778.jpg',
    note: '',
  },
  {
    id: 536,
    tvmazeId: '65491',
    title: 'Zero Day',
    network: 'Netflix',
    startYear: 2025,
    years: '2025',
    genres: ['Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/557/1394491.jpg',
    note: '',
  },
  {
    id: 537,
    tvmazeId: '68394',
    title: 'Étoile',
    network: 'Prime Video',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/565/1413224.jpg',
    note: '',
  },
  {
    id: 538,
    tvmazeId: '53277',
    title: '3 Body Problem',
    network: 'Netflix',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Science-Fiction', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/507/1268925.jpg',
    note: '',
  },
  {
    id: 539,
    tvmazeId: '60549',
    title: 'A Gentleman in Moscow',
    network: 'Paramount+',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/602/1505996.jpg',
    note: '',
  },
  {
    id: 540,
    tvmazeId: '63949',
    title: 'A Good Girl\'s Guide to Murder',
    network: 'BBC iPlayer',
    startYear: 2024,
    years: '2024–',
    genres: ['Crime', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/626/1566763.jpg',
    note: '',
  },
  {
    id: 541,
    tvmazeId: '60513',
    title: 'A Man in Full',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/513/1283156.jpg',
    note: '',
  },
  {
    id: 542,
    tvmazeId: '74443',
    title: 'A Man on the Inside',
    network: 'Netflix',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy', 'Espionage'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/599/1499138.jpg',
    note: '',
  },
  {
    id: 543,
    tvmazeId: '80518',
    title: 'A Remarkable Place to Die',
    network: 'TVNZ 1',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/563/1407678.jpg',
    note: '',
  },
  {
    id: 544,
    tvmazeId: '76879',
    title: 'A Thousand Suns',
    network: 'YouTube',
    startYear: 2024,
    years: '2024',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/572/1431975.jpg',
    note: '',
  },
  {
    id: 545,
    tvmazeId: '72976',
    title: 'A Very Royal Scandal',
    network: 'Prime Video',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/535/1339905.jpg',
    note: '',
  },
  {
    id: 546,
    tvmazeId: '67032',
    title: 'After the Flood',
    network: 'ITVX',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/609/1523380.jpg',
    note: '',
  },
  {
    id: 547,
    tvmazeId: '58948',
    title: 'Agatha All Along',
    network: 'Disney+',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy', 'Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/536/1340567.jpg',
    note: '',
  },
  {
    id: 548,
    tvmazeId: '75058',
    title: 'Ainsley MacGregor Mysteries',
    network: 'Great American Pure Flix',
    startYear: 2024,
    years: '2024–',
    genres: ['Crime', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/573/1432539.jpg',
    note: '',
  },
  {
    id: 549,
    tvmazeId: '70499',
    title: 'Alice & Jack',
    network: 'Channel 4',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/580/1450569.jpg',
    note: '',
  },
  {
    id: 550,
    tvmazeId: '72511',
    title: 'Allegiance',
    network: 'CBC',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/605/1514891.jpg',
    note: '',
  },
  {
    id: 551,
    tvmazeId: '56861',
    title: 'American Sports Story',
    network: 'FX',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Sports'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/536/1342292.jpg',
    note: '',
  },
  {
    id: 552,
    tvmazeId: '69164',
    title: 'Angry Birds Mystery Island A Hatchlings Adventure',
    network: 'Prime Video',
    startYear: 2024,
    years: '2024',
    genres: ['Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/521/1303888.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 23, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 334, "cliffhanger": 235, "ended": 13701}};
