window.pageShows = [
  {
    id: 4825,
    tvmazeId: '16821',
    title: 'Peanuts',
    network: 'Cartoon Network',
    startYear: 2016,
    years: '2016',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/56/140528.jpg',
    note: '',
  },
  {
    id: 4826,
    tvmazeId: '50789',
    title: 'People Like Us',
    network: 'YouTube',
    startYear: 2016,
    years: '2016–2019',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/275/689193.jpg',
    note: '',
  },
  {
    id: 4827,
    tvmazeId: '8870',
    title: 'People of Earth',
    network: 'TBS',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Comedy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/74/186663.jpg',
    note: '',
  },
  {
    id: 4828,
    tvmazeId: '11901',
    title: 'Pitch',
    network: 'FOX',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/66/166858.jpg',
    note: '',
  },
  {
    id: 4829,
    tvmazeId: '21083',
    title: 'Pokémon Generations',
    network: 'YouTube',
    startYear: 2016,
    years: '2016',
    genres: ['Action', 'Adventure', 'Anime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/74/186102.jpg',
    note: '',
  },
  {
    id: 4830,
    tvmazeId: '20929',
    title: 'Polly and the ZhuZhu Pets',
    network: 'Disney Channel',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/184784.jpg',
    note: '',
  },
  {
    id: 4831,
    tvmazeId: '31766',
    title: 'Porridge',
    network: 'BBC One',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/138/347438.jpg',
    note: '',
  },
  {
    id: 4832,
    tvmazeId: '18078',
    title: 'Power Monkeys',
    network: 'Channel 4',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/61/153236.jpg',
    note: '',
  },
  {
    id: 4833,
    tvmazeId: '3144',
    title: 'Preacher',
    network: 'AMC',
    startYear: 2016,
    years: '2016–2019',
    genres: ['Drama', 'Western', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/205/514552.jpg',
    note: '',
  },
  {
    id: 4834,
    tvmazeId: '15735',
    title: 'Premonition',
    network: 'Channel 5',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Crime', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/54/137012.jpg',
    note: '',
  },
  {
    id: 4835,
    tvmazeId: '21122',
    title: 'Prisoner Zero',
    network: 'ABC Entertains',
    startYear: 2016,
    years: '2016',
    genres: ['Adventure', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/74/186354.jpg',
    note: '',
  },
  {
    id: 4836,
    tvmazeId: '17153',
    title: 'Private Eyes',
    network: 'Global',
    startYear: 2016,
    years: '2016–2021',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/199/499691.jpg',
    note: '',
  },
  {
    id: 4837,
    tvmazeId: '24349',
    title: 'Private Sales',
    network: 'Prime Video',
    startYear: 2016,
    years: '2016',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/92/231527.jpg',
    note: '',
  },
  {
    id: 4838,
    tvmazeId: '12112',
    title: 'Pure Genius',
    network: 'CBS',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/88/220699.jpg',
    note: '',
  },
  {
    id: 4839,
    tvmazeId: '15619',
    title: 'Quantum Break',
    network: 'XBOX Live',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/261/652693.jpg',
    note: '',
  },
  {
    id: 4840,
    tvmazeId: '4158',
    title: 'Quarry',
    network: 'Cinemax',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/184949.jpg',
    note: '',
  },
  {
    id: 4841,
    tvmazeId: '7015',
    title: 'Queen of the South',
    network: 'USA Network',
    startYear: 2016,
    years: '2016–2021',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/116/292024.jpg',
    note: '',
  },
  {
    id: 4842,
    tvmazeId: '11649',
    title: 'Queen Sugar',
    network: 'Oprah Winfrey Network',
    startYear: 2016,
    years: '2016–2022',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/424/1060596.jpg',
    note: '',
  },
  {
    id: 4843,
    tvmazeId: '17597',
    title: 'Rainbow Ruby',
    network: 'Family Jr.',
    startYear: 2016,
    years: '2016–2020',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/59/148062.jpg',
    note: '',
  },
  {
    id: 4844,
    tvmazeId: '17594',
    title: 'Raising Expectations',
    network: 'Family Channel',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/59/148058.jpg',
    note: '',
  },
  {
    id: 4845,
    tvmazeId: '16712',
    title: 'Random Acts',
    network: 'Channel 4',
    startYear: 2016,
    years: '2016–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/61/153224.jpg',
    note: '',
  },
  {
    id: 4846,
    tvmazeId: '20900',
    title: 'Ranger Rob',
    network: 'Treehouse',
    startYear: 2016,
    years: '2016–2018',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/184595.jpg',
    note: '',
  },
  {
    id: 4847,
    tvmazeId: '33510',
    title: 'Ravenwolf Towers',
    network: 'Prime Video',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Drama', 'Horror', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/227/569646.jpg',
    note: '',
  },
  {
    id: 4848,
    tvmazeId: '12265',
    title: 'Ready Jet Go!',
    network: 'PBS',
    startYear: 2016,
    years: '2016–2019',
    genres: ['Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/350/876638.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 202, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 670, "cliffhanger": 0, "ended": 13760}};
