window.pageShows = [
  {
    id: 2713,
    tvmazeId: '73709',
    title: 'Ming\'s Dynasty',
    network: 'CBC Gem',
    startYear: 2020,
    years: '2020',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/497/1243815.jpg',
    note: '',
  },
  {
    id: 2714,
    tvmazeId: '46591',
    title: 'Mira, Royal Detective',
    network: 'DisneyNOW',
    startYear: 2020,
    years: '2020–2022',
    genres: ['Adventure', 'Fantasy', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/244/612244.jpg',
    note: '',
  },
  {
    id: 2715,
    tvmazeId: '46361',
    title: 'Mirage',
    network: 'France 2',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/242/606623.jpg',
    note: '',
  },
  {
    id: 2716,
    tvmazeId: '41532',
    title: 'Miss Scarlet',
    network: 'PBS Passport',
    startYear: 2020,
    years: '2020–',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/594/1485577.jpg',
    note: '',
  },
  {
    id: 2717,
    tvmazeId: '68814',
    title: 'Mister Parker\'s Cul De Sac',
    network: 'YouTube',
    startYear: 2020,
    years: '2020',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 2718,
    tvmazeId: '30753',
    title: 'Mister Winner',
    network: 'BBC iPlayer',
    startYear: 2020,
    years: '2020',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/247/617922.jpg',
    note: '',
  },
  {
    id: 2719,
    tvmazeId: '49747',
    title: 'Monster Beach',
    network: 'Cartoon Network',
    startYear: 2020,
    years: '2020–',
    genres: ['Comedy', 'Adventure'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/268/670899.jpg',
    note: '',
  },
  {
    id: 2720,
    tvmazeId: '46111',
    title: 'Monsterland',
    network: 'Hulu',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Fantasy', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/272/681786.jpg',
    note: '',
  },
  {
    id: 2721,
    tvmazeId: '49827',
    title: 'Moonbase 8',
    network: 'Paramount+ with Showtime',
    startYear: 2020,
    years: '2020',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/277/693276.jpg',
    note: '',
  },
  {
    id: 2722,
    tvmazeId: '71302',
    title: 'Morph\'s Epic Adventures',
    network: 'Now',
    startYear: 2020,
    years: '2020',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/477/1193204.jpg',
    note: '',
  },
  {
    id: 2723,
    tvmazeId: '45970',
    title: 'Most Dangerous Game',
    network: 'The Roku Channel',
    startYear: 2020,
    years: '2020–2023',
    genres: ['Action', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/599/1497762.jpg',
    note: '',
  },
  {
    id: 2724,
    tvmazeId: '37031',
    title: 'Motherland: Fort Salem',
    network: 'Freeform',
    startYear: 2020,
    years: '2020–2022',
    genres: ['Drama', 'Action', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/325/814082.jpg',
    note: '',
  },
  {
    id: 2725,
    tvmazeId: '86131',
    title: 'Mount Hideaway Mysteries checkifcancelled',
    network: 'Great American Pure Flix',
    startYear: 2020,
    years: '2020–',
    genres: ['Thriller', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/579/1449162.jpg',
    note: '',
  },
  {
    id: 2726,
    tvmazeId: '42441',
    title: 'Mrs. America',
    network: 'Hulu',
    startYear: 2020,
    years: '2020',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/253/632587.jpg',
    note: '',
  },
  {
    id: 2727,
    tvmazeId: '46164',
    title: 'My Left Nut',
    network: 'BBC Three',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/241/603243.jpg',
    note: '',
  },
  {
    id: 2728,
    tvmazeId: '45026',
    title: 'My Little Pony: Pony Life',
    network: 'Discovery Family',
    startYear: 2020,
    years: '2020–2021',
    genres: ['Comedy', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/259/649707.jpg',
    note: '',
  },
  {
    id: 2729,
    tvmazeId: '46917',
    title: 'My Perfect Landing checkifcancelled',
    network: 'Family Channel',
    startYear: 2020,
    years: '2020–',
    genres: ['Drama', 'Family', 'Sports'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/254/637026.jpg',
    note: '',
  },
  {
    id: 2730,
    tvmazeId: '47583',
    title: 'Mystic',
    network: 'BBC iPlayer',
    startYear: 2020,
    years: '2020–2022',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/403/1009235.jpg',
    note: '',
  },
  {
    id: 2731,
    tvmazeId: '41530',
    title: 'Mythic Quest',
    network: 'Apple TV',
    startYear: 2020,
    years: '2020–2025',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/564/1412475.jpg',
    note: '',
  },
  {
    id: 2732,
    tvmazeId: '60086',
    title: 'Nebula-75',
    network: 'Prime Video',
    startYear: 2020,
    years: '2020–2021',
    genres: ['Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/391/978890.jpg',
    note: '',
  },
  {
    id: 2733,
    tvmazeId: '44592',
    title: 'Never Have I Ever',
    network: 'Netflix',
    startYear: 2020,
    years: '2020–2023',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/461/1152604.jpg',
    note: '',
  },
  {
    id: 2734,
    tvmazeId: '45639',
    title: 'New Eden checkifcancelled',
    network: 'Crave',
    startYear: 2020,
    years: '2020–',
    genres: ['Comedy', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/233/584699.jpg',
    note: '',
  },
  {
    id: 2735,
    tvmazeId: '40873',
    title: 'neXt',
    network: 'FOX',
    startYear: 2020,
    years: '2020',
    genres: ['Science-Fiction', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/266/665211.jpg',
    note: '',
  },
  {
    id: 2736,
    tvmazeId: '56398',
    title: 'Nick News checkifcancelled',
    network: 'Nickelodeon',
    startYear: 2020,
    years: '2020–',
    genres: ['Children', 'Travel'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/474/1186573.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 114, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 856, "cliffhanger": 286, "ended": 13542}};
