window.pageShows = [
  {
    id: 4969,
    tvmazeId: '41001',
    title: 'Traces',
    network: 'U&alibi',
    startYear: 2019,
    years: '2019–2022',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/232/582449.jpg',
    note: '',
  },
  {
    id: 4970,
    tvmazeId: '42601',
    title: 'Trackers',
    network: 'M-Net',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/225/563745.jpg',
    note: '',
  },
  {
    id: 4971,
    tvmazeId: '41410',
    title: 'Trailer Park Boys: The Animated Series',
    network: 'Netflix',
    startYear: 2019,
    years: '2019–2020',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/188/472147.jpg',
    note: '',
  },
  {
    id: 4972,
    tvmazeId: '35172',
    title: 'Traitors',
    network: 'Channel 4',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Thriller', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/184/460235.jpg',
    note: '',
  },
  {
    id: 4973,
    tvmazeId: '35987',
    title: 'Treadstone',
    network: 'USA Network',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Action', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/217/544715.jpg',
    note: '',
  },
  {
    id: 4974,
    tvmazeId: '40550',
    title: 'Triad Princess',
    network: 'Netflix',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Crime', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/230/576408.jpg',
    note: '',
  },
  {
    id: 4975,
    tvmazeId: '39141',
    title: 'Trinkets',
    network: 'Netflix',
    startYear: 2019,
    years: '2019–2020',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/201/504182.jpg',
    note: '',
  },
  {
    id: 4976,
    tvmazeId: '54005',
    title: 'Troopers',
    network: 'Dropout',
    startYear: 2019,
    years: '2019',
    genres: ['Comedy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/299/748341.jpg',
    note: '',
  },
  {
    id: 4977,
    tvmazeId: '60450',
    title: 'Troopers: Rise of the Budget',
    network: 'Dropout',
    startYear: 2019,
    years: '2019',
    genres: ['Comedy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/395/989412.jpg',
    note: '',
  },
  {
    id: 4978,
    tvmazeId: '40354',
    title: 'Tropical Cop Tales',
    network: 'Adult Swim',
    startYear: 2019,
    years: '2019',
    genres: ['Comedy', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/183/459422.jpg',
    note: '',
  },
  {
    id: 4979,
    tvmazeId: '44746',
    title: 'True Tunes',
    network: 'Netflix',
    startYear: 2019,
    years: '2019',
    genres: ['Children', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/217/544587.jpg',
    note: '',
  },
  {
    id: 4980,
    tvmazeId: '34221',
    title: 'Truth Be Told',
    network: 'Apple TV',
    startYear: 2019,
    years: '2019–2023',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/443/1107671.jpg',
    note: '',
  },
  {
    id: 4981,
    tvmazeId: '35086',
    title: 'Tuca & Bertie',
    network: 'Adult Swim',
    startYear: 2019,
    years: '2019–2022',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Netflix cancelled after one season (Adult Swim later revived it for two more seasons before cancelling again); Tuca and Bertie\'s friendship and trauma journeys were left mid-arc when Netflix cancelled.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/146/367400.jpg',
    note: '',
  },
  {
    id: 4982,
    tvmazeId: '36227',
    title: 'Turn Up Charlie',
    network: 'Netflix',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/186/465154.jpg',
    note: '',
  },
  {
    id: 4983,
    tvmazeId: '43050',
    title: 'Twelve Forever',
    network: 'Netflix',
    startYear: 2019,
    years: '2019',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/205/513555.jpg',
    note: '',
  },
  {
    id: 4984,
    tvmazeId: '66671',
    title: 'Two Sides',
    network: 'Snapchat',
    startYear: 2019,
    years: '2019–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/444/1110022.jpg',
    note: '',
  },
  {
    id: 4985,
    tvmazeId: '44634',
    title: 'Tyler Perry\'s Sistas',
    network: 'BET',
    startYear: 2019,
    years: '2019–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/539/1348197.jpg',
    note: '',
  },
  {
    id: 4986,
    tvmazeId: '43276',
    title: 'Tyler Perry\'s The Oval',
    network: 'BET',
    startYear: 2019,
    years: '2019–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/502/1256068.jpg',
    note: '',
  },
  {
    id: 4987,
    tvmazeId: '42770',
    title: 'Typewriter',
    network: 'Netflix',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Horror', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/204/511397.jpg',
    note: '',
  },
  {
    id: 4988,
    tvmazeId: '45124',
    title: 'TZGZ Shorts',
    network: 'Syfy',
    startYear: 2019,
    years: '2019–2020',
    genres: ['Comedy', 'Adult'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/225/563823.jpg',
    note: '',
  },
  {
    id: 4989,
    tvmazeId: '80794',
    title: 'Têtard',
    network: 'Canal+',
    startYear: 2019,
    years: '2019–2020',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/543/1359285.jpg',
    note: '',
  },
  {
    id: 4990,
    tvmazeId: '76887',
    title: 'Ultramechatron Team Go!',
    network: 'Dropout',
    startYear: 2019,
    years: '2019',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/518/1296719.jpg',
    note: '',
  },
  {
    id: 4991,
    tvmazeId: '34526',
    title: 'Unbelievable',
    network: 'Netflix',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/205/513793.jpg',
    note: '',
  },
  {
    id: 4992,
    tvmazeId: '22400',
    title: 'Undercover',
    network: 'VRT 1',
    startYear: 2019,
    years: '2019–2024',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/388/972090.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 208, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
