window.pageShows = [
  {
    id: 16897,
    tvmazeId: '22150',
    title: 'The Alaskans',
    network: 'ABC',
    startYear: 1959,
    years: '1959–1960',
    genres: ['Adventure', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/80/202384.jpg',
    note: '',
  },
  {
    id: 16898,
    tvmazeId: '57640',
    title: 'The Betty Hutton Show',
    network: 'CBS',
    startYear: 1959,
    years: '1959–1960',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/391/978500.jpg',
    note: '',
  },
  {
    id: 16899,
    tvmazeId: '62775',
    title: 'The D.A.\'s Man',
    network: 'NBC',
    startYear: 1959,
    years: '1959',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 16900,
    tvmazeId: '89404',
    title: 'The David Niven Show',
    network: 'NBC',
    startYear: 1959,
    years: '1959',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/605/1514568.jpg',
    note: '',
  },
  {
    id: 16901,
    tvmazeId: '58611',
    title: 'The Dennis O\'Keefe Show',
    network: 'CBS',
    startYear: 1959,
    years: '1959–1960',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/390/976764.jpg',
    note: '',
  },
  {
    id: 16902,
    tvmazeId: '58609',
    title: 'The Deputy',
    network: 'NBC',
    startYear: 1959,
    years: '1959–1961',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/392/980840.jpg',
    note: '',
  },
  {
    id: 16903,
    tvmazeId: '28692',
    title: 'The Detectives',
    network: 'NBC',
    startYear: 1959,
    years: '1959–1962',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/283/707512.jpg',
    note: '',
  },
  {
    id: 16904,
    tvmazeId: '79641',
    title: 'The Flying Doctor',
    network: 'ITV1',
    startYear: 1959,
    years: '1959–1960',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 16905,
    tvmazeId: '79715',
    title: 'The Four Just Men',
    network: 'ITV1',
    startYear: 1959,
    years: '1959–1960',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/536/1341477.jpg',
    note: '',
  },
  {
    id: 16906,
    tvmazeId: '17480',
    title: 'The Man from Blackhawk',
    network: 'ABC',
    startYear: 1959,
    years: '1959–1960',
    genres: ['Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/593/1482855.jpg',
    note: '',
  },
  {
    id: 16907,
    tvmazeId: '4965',
    title: 'The Many Loves of Dobie Gillis',
    network: 'CBS',
    startYear: 1959,
    years: '1959–1963',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/53894.jpg',
    note: '',
  },
  {
    id: 16908,
    tvmazeId: '4951',
    title: 'The Rebel',
    network: 'NBC',
    startYear: 1959,
    years: '1959–1961',
    genres: ['Action', 'Adventure', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/53787.jpg',
    note: '',
  },
  {
    id: 16909,
    tvmazeId: '5658',
    title: 'The Rocky and Bullwinkle Show',
    network: 'ABC',
    startYear: 1959,
    years: '1959–1963',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/56872.jpg',
    note: '',
  },
  {
    id: 16910,
    tvmazeId: '59327',
    title: 'The Third Man',
    network: 'BBC One',
    startYear: 1959,
    years: '1959–1965',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/380/951874.jpg',
    note: '',
  },
  {
    id: 16911,
    tvmazeId: '79519',
    title: 'The Troubleshooters',
    network: 'NBC',
    startYear: 1959,
    years: '1959–1960',
    genres: ['Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/535/1338040.jpg',
    note: '',
  },
  {
    id: 16912,
    tvmazeId: '787',
    title: 'The Twilight Zone',
    network: 'CBS',
    startYear: 1959,
    years: '1959–1964',
    genres: ['Science-Fiction', 'Mystery', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/398/996733.jpg',
    note: '',
  },
  {
    id: 16913,
    tvmazeId: '2130',
    title: 'The Untouchables',
    network: 'ABC',
    startYear: 1959,
    years: '1959–1963',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/29813.jpg',
    note: '',
  },
  {
    id: 16914,
    tvmazeId: '34742',
    title: 'This Man Dawson',
    network: 'Syndication',
    startYear: 1959,
    years: '1959–1960',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/144/362116.jpg',
    note: '',
  },
  {
    id: 16915,
    tvmazeId: '24749',
    title: 'Tightrope!',
    network: 'CBS',
    startYear: 1959,
    years: '1959–1960',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/468/1171191.jpg',
    note: '',
  },
  {
    id: 16916,
    tvmazeId: '40205',
    title: 'U.S. Border Patrol',
    network: 'CBS',
    startYear: 1959,
    years: '1959',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/486/1215567.jpg',
    note: '',
  },
  {
    id: 16917,
    tvmazeId: '79581',
    title: 'Wichita Town',
    network: 'NBC',
    startYear: 1959,
    years: '1959–1960',
    genres: ['Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/591/1478924.jpg',
    note: '',
  },
  {
    id: 16918,
    tvmazeId: '63299',
    title: 'World of Giants',
    network: 'Syndication',
    startYear: 1959,
    years: '1959',
    genres: ['Science-Fiction', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/417/1043651.jpg',
    note: '',
  },
  {
    id: 16919,
    tvmazeId: '6272',
    title: '77 Sunset Strip',
    network: 'ABC',
    startYear: 1958,
    years: '1958–1964',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/200/500752.jpg',
    note: '',
  },
  {
    id: 16920,
    tvmazeId: '43033',
    title: 'African Patrol',
    network: 'Syndication',
    startYear: 1958,
    years: '1958–1959',
    genres: ['Drama', 'Adventure', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/205/513290.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 705, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 295, "ended": 12349}};
