window.pageShows = [
  {
    id: 14377,
    tvmazeId: '19354',
    title: 'CBS Storybreak',
    network: 'CBS',
    startYear: 1985,
    years: '1985',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/68/170309.jpg',
    note: '',
  },
  {
    id: 14378,
    tvmazeId: '24318',
    title: 'Charters & Caldicott',
    network: 'BBC One',
    startYear: 1985,
    years: '1985',
    genres: ['Drama', 'Comedy', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/92/231302.jpg',
    note: '',
  },
  {
    id: 14379,
    tvmazeId: '30395',
    title: 'Check It Out!',
    network: 'CTV',
    startYear: 1985,
    years: '1985–1987',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/531/1329042.jpg',
    note: '',
  },
  {
    id: 14380,
    tvmazeId: '54169',
    title: 'Children\'s Island',
    network: 'BBC One',
    startYear: 1985,
    years: '1985',
    genres: ['Drama', 'Adventure', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/300/750585.jpg',
    note: '',
  },
  {
    id: 14381,
    tvmazeId: '36719',
    title: 'Code Name: Foxfire',
    network: 'NBC',
    startYear: 1985,
    years: '1985',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/155/388848.jpg',
    note: '',
  },
  {
    id: 14382,
    tvmazeId: '44604',
    title: 'Colour in the Creek',
    network: 'Nine Network',
    startYear: 1985,
    years: '1985',
    genres: ['Drama', 'Family', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/216/541202.jpg',
    note: '',
  },
  {
    id: 14383,
    tvmazeId: '51333',
    title: 'Connie',
    network: 'ITV1',
    startYear: 1985,
    years: '1985',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/278/696621.jpg',
    note: '',
  },
  {
    id: 14384,
    tvmazeId: '41775',
    title: 'Cool It',
    network: 'BBC Two',
    startYear: 1985,
    years: '1985–1988',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/191/479118.jpg',
    note: '',
  },
  {
    id: 14385,
    tvmazeId: '23365',
    title: 'Cover Her Face',
    network: 'ITV1',
    startYear: 1985,
    years: '1985',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/87/219369.jpg',
    note: '',
  },
  {
    id: 14386,
    tvmazeId: '58574',
    title: 'Dalton\'s Code of Vengeance',
    network: 'NBC',
    startYear: 1985,
    years: '1985–1986',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14387,
    tvmazeId: '16540',
    title: 'Danger Bay',
    network: 'CBC',
    startYear: 1985,
    years: '1985–1990',
    genres: ['Adventure', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/55/137769.jpg',
    note: '',
  },
  {
    id: 14388,
    tvmazeId: '8304',
    title: 'Das Boot',
    network: 'Das Erste',
    startYear: 1985,
    years: '1985',
    genres: ['Action', 'Thriller', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/74757.jpg',
    note: '',
  },
  {
    id: 14389,
    tvmazeId: '19777',
    title: 'David, el Gnomo',
    network: 'TVE',
    startYear: 1985,
    years: '1985–1986',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/289/724151.jpg',
    note: '',
  },
  {
    id: 14390,
    tvmazeId: '50259',
    title: 'Deceptions',
    network: 'NBC',
    startYear: 1985,
    years: '1985',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14391,
    tvmazeId: '4674',
    title: 'Dempsey and Makepeace',
    network: 'ITV1',
    startYear: 1985,
    years: '1985–1986',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/52787.jpg',
    note: '',
  },
  {
    id: 14392,
    tvmazeId: '53037',
    title: 'Detective in the House',
    network: 'CBS',
    startYear: 1985,
    years: '1985',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/293/733775.jpg',
    note: '',
  },
  {
    id: 14393,
    tvmazeId: '5314',
    title: 'Disney\'s Adventures of the Gummi Bears',
    network: 'Disney Channel',
    startYear: 1985,
    years: '1985–1991',
    genres: ['Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/55239.jpg',
    note: '',
  },
  {
    id: 14394,
    tvmazeId: '22455',
    title: 'Double Dare',
    network: 'CBS',
    startYear: 1985,
    years: '1985',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/82/206566.jpg',
    note: '',
  },
  {
    id: 14395,
    tvmazeId: '75422',
    title: 'Doubletake',
    network: 'CBS News',
    startYear: 1985,
    years: '1985',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14396,
    tvmazeId: '51390',
    title: 'Drummonds',
    network: 'ITV1',
    startYear: 1985,
    years: '1985–1987',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14397,
    tvmazeId: '9705',
    title: 'Dumbo\'s Circus',
    network: 'Disney Channel',
    startYear: 1985,
    years: '1985–1986',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/84278.jpg',
    note: '',
  },
  {
    id: 14398,
    tvmazeId: '793',
    title: 'EastEnders',
    network: 'BBC iPlayer',
    startYear: 1985,
    years: '1985–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/15519.jpg',
    note: '',
  },
  {
    id: 14399,
    tvmazeId: '18671',
    title: 'Edge of Darkness',
    network: 'BBC Two',
    startYear: 1985,
    years: '1985',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/63/159937.jpg',
    note: '',
  },
  {
    id: 14400,
    tvmazeId: '21139',
    title: 'Evergreen',
    network: 'NBC',
    startYear: 1985,
    years: '1985',
    genres: ['Drama', 'Family', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/275/687902.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 600, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 398, "cliffhanger": 239, "ended": 15092}};
