window.pageShows = [
  {
    id: 14693,
    tvmazeId: '9402',
    title: 'Dramarama',
    network: 'ITV1',
    startYear: 1983,
    years: '1983–1989',
    genres: ['Drama', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/82641.jpg',
    note: '',
  },
  {
    id: 14694,
    tvmazeId: '1129',
    title: 'Dungeons & Dragons',
    network: 'CBS',
    startYear: 1983,
    years: '1983–1985',
    genres: ['Adventure', 'Fantasy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/152/380755.jpg',
    note: '',
  },
  {
    id: 14695,
    tvmazeId: '14338',
    title: 'Emerald Point N.A.S.',
    network: 'CBS',
    startYear: 1983,
    years: '1983–1984',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/48/121874.jpg',
    note: '',
  },
  {
    id: 14696,
    tvmazeId: '65295',
    title: 'Empire, Inc.',
    network: 'CBC',
    startYear: 1983,
    years: '1983',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/431/1078550.jpg',
    note: '',
  },
  {
    id: 14697,
    tvmazeId: '27866',
    title: 'Five Mile Creek',
    network: 'Seven Network',
    startYear: 1983,
    years: '1983–1985',
    genres: ['Action', 'Adventure', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/110/275752.jpg',
    note: '',
  },
  {
    id: 14698,
    tvmazeId: '44896',
    title: 'Foot in the Door',
    network: 'CBS',
    startYear: 1983,
    years: '1983',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14699,
    tvmazeId: '12307',
    title: 'For Love and Honor',
    network: 'NBC',
    startYear: 1983,
    years: '1983–1984',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/350/876647.jpg',
    note: '',
  },
  {
    id: 14700,
    tvmazeId: '63265',
    title: 'For the Term of His Natural Life',
    network: 'Nine Network',
    startYear: 1983,
    years: '1983',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/448/1120654.jpg',
    note: '',
  },
  {
    id: 14701,
    tvmazeId: '6880',
    title: 'G.I. Joe: A Real American Hero',
    network: 'Syndication',
    startYear: 1983,
    years: '1983–1992',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/25/64877.jpg',
    note: '',
  },
  {
    id: 14702,
    tvmazeId: '3459',
    title: 'Give Us a Break',
    network: 'BBC One',
    startYear: 1983,
    years: '1983–1984',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/45439.jpg',
    note: '',
  },
  {
    id: 14703,
    tvmazeId: '87441',
    title: 'Goodnight and God Bless',
    network: 'ITV1',
    startYear: 1983,
    years: '1983',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14704,
    tvmazeId: '65040',
    title: 'Goodnight, Beantown',
    network: 'CBS',
    startYear: 1983,
    years: '1983–1984',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/429/1074433.jpg',
    note: '',
  },
  {
    id: 14705,
    tvmazeId: '30997',
    title: 'Gran',
    network: 'BBC One',
    startYear: 1983,
    years: '1983',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/123/308730.jpg',
    note: '',
  },
  {
    id: 14706,
    tvmazeId: '56539',
    title: 'Gun Shy',
    network: 'CBS',
    startYear: 1983,
    years: '1983',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/524/1310667.jpg',
    note: '',
  },
  {
    id: 14707,
    tvmazeId: '32275',
    title: 'Hallelujah!',
    network: 'ITV1',
    startYear: 1983,
    years: '1983–1984',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/128/322485.jpg',
    note: '',
  },
  {
    id: 14708,
    tvmazeId: '13102',
    title: 'Hardcastle and McCormick',
    network: 'ABC',
    startYear: 1983,
    years: '1983–1986',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/45/112642.jpg',
    note: '',
  },
  {
    id: 14709,
    tvmazeId: '4230',
    title: 'He-Man and the Masters of the Universe',
    network: 'Syndication',
    startYear: 1983,
    years: '1983–1984',
    genres: ['Action', 'Fantasy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/50749.jpg',
    note: '',
  },
  {
    id: 14710,
    tvmazeId: '32284',
    title: 'Henry\'s Cat',
    network: 'BBC One',
    startYear: 1983,
    years: '1983',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/129/322611.jpg',
    note: '',
  },
  {
    id: 14711,
    tvmazeId: '1435',
    title: 'Herman Wouk\'s The Winds of War',
    network: 'ABC',
    startYear: 1983,
    years: '1983',
    genres: ['Drama', 'Romance', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/12/31600.jpg',
    note: '',
  },
  {
    id: 14712,
    tvmazeId: '63659',
    title: 'High Performance',
    network: 'ABC',
    startYear: 1983,
    years: '1983',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/419/1048977.jpg',
    note: '',
  },
  {
    id: 14713,
    tvmazeId: '4579',
    title: 'Inspector Gadget',
    network: 'Syndication',
    startYear: 1983,
    years: '1983–1986',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/495/1239435.jpg',
    note: '',
  },
  {
    id: 14714,
    tvmazeId: '42671',
    title: 'It\'s Not Easy',
    network: 'ABC',
    startYear: 1983,
    years: '1983',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/480/1200371.jpg',
    note: '',
  },
  {
    id: 14715,
    tvmazeId: '50976',
    title: 'Jamaica Inn',
    network: 'ITV1',
    startYear: 1983,
    years: '1983',
    genres: ['Drama', 'Thriller', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/276/691933.jpg',
    note: '',
  },
  {
    id: 14716,
    tvmazeId: '23667',
    title: 'Jane Eyre',
    network: 'BBC One',
    startYear: 1983,
    years: '1983',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/88/222275.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 613, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
