window.pageShows = [
  {
    id: 9005,
    tvmazeId: '6937',
    title: 'Monster High',
    network: 'Nickelodeon',
    startYear: 2010,
    years: '2010–2016',
    genres: ['Comedy', 'Adventure', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/65260.jpg',
    note: '',
  },
  {
    id: 9006,
    tvmazeId: '20583',
    title: 'Mr Moon',
    network: 'Disney Junior',
    startYear: 2010,
    years: '2010',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/72/181962.jpg',
    note: '',
  },
  {
    id: 9007,
    tvmazeId: '2517',
    title: 'My Babysitter\'s a Vampire',
    network: 'Disney Channel',
    startYear: 2010,
    years: '2010–2012',
    genres: ['Comedy', 'Action', 'Supernatural'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/13/33604.jpg',
    note: '',
  },
  {
    id: 9008,
    tvmazeId: '2003',
    title: 'My Generation',
    network: 'ABC',
    startYear: 2010,
    years: '2010',
    genres: ['Drama', 'Family', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/28096.jpg',
    note: '',
  },
  {
    id: 9009,
    tvmazeId: '8325',
    title: 'My Girlfriend is a Gumiho',
    network: 'SBS',
    startYear: 2010,
    years: '2010',
    genres: ['Comedy', 'Fantasy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/582/1455746.jpg',
    note: '',
  },
  {
    id: 9010,
    tvmazeId: '2818',
    title: 'My Little Pony: Friendship is Magic',
    network: 'Discovery Family',
    startYear: 2010,
    years: '2010–2019',
    genres: ['Adventure', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/15/38187.jpg',
    note: '',
  },
  {
    id: 9011,
    tvmazeId: '8395',
    title: 'Neighbors from Hell',
    network: 'TBS',
    startYear: 2010,
    years: '2010',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/48/121184.jpg',
    note: '',
  },
  {
    id: 9012,
    tvmazeId: '3148',
    title: 'NFL Rush Zone',
    network: 'Nicktoons',
    startYear: 2010,
    years: '2010–2016',
    genres: ['Action', 'Children'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/17/43192.jpg',
    note: '',
  },
  {
    id: 9013,
    tvmazeId: '122',
    title: 'Nikita',
    network: 'The CW',
    startYear: 2010,
    years: '2010–2013',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: 'CW ran for four seasons and gave Nikita a proper series finale with closure for the characters.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/545/1362913.jpg',
    note: '',
  },
  {
    id: 9014,
    tvmazeId: '814',
    title: 'No Ordinary Family',
    network: 'ABC',
    startYear: 2010,
    years: '2010–2011',
    genres: ['Drama', 'Action', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Season 1 ends with the central conflict reaching a crisis point and the family\'s superhero future completely unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/15673.jpg',
    note: '',
  },
  {
    id: 9015,
    tvmazeId: '21529',
    title: 'Noodle and Doodle',
    network: 'Universal Kids',
    startYear: 2010,
    years: '2010–2013',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/76/191945.jpg',
    note: '',
  },
  {
    id: 9016,
    tvmazeId: '17756',
    title: 'Octonauts',
    network: 'CBeebies',
    startYear: 2010,
    years: '2010–2023',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/81/203713.jpg',
    note: '',
  },
  {
    id: 9017,
    tvmazeId: '4343',
    title: 'Offspring',
    network: 'Network 10',
    startYear: 2010,
    years: '2010–2017',
    genres: ['Drama', 'Family', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/51453.jpg',
    note: '',
  },
  {
    id: 9018,
    tvmazeId: '35227',
    title: 'Oscar\'s Oasis',
    network: 'Canal+',
    startYear: 2010,
    years: '2010–2011',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/148/370218.jpg',
    note: '',
  },
  {
    id: 9019,
    tvmazeId: '11056',
    title: 'Out with Dad',
    network: 'YouTube',
    startYear: 2010,
    years: '2010–2017',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/37/92910.jpg',
    note: '',
  },
  {
    id: 9020,
    tvmazeId: '1380',
    title: 'Outlaw',
    network: 'NBC',
    startYear: 2010,
    years: '2010',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/19248.jpg',
    note: '',
  },
  {
    id: 9021,
    tvmazeId: '1230',
    title: 'Outsourced',
    network: 'NBC',
    startYear: 2010,
    years: '2010–2011',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/17688.jpg',
    note: '',
  },
  {
    id: 9022,
    tvmazeId: '18508',
    title: 'Pair of Kings',
    network: 'Disney XD',
    startYear: 2010,
    years: '2010–2013',
    genres: ['Comedy', 'Family', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/597/1494009.jpg',
    note: '',
  },
  {
    id: 9023,
    tvmazeId: '93',
    title: 'Parenthood',
    network: 'NBC',
    startYear: 2010,
    years: '2010–2015',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/0/685.jpg',
    note: '',
  },
  {
    id: 9024,
    tvmazeId: '4020',
    title: 'Past Life',
    network: 'FOX',
    startYear: 2010,
    years: '2010',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/49531.jpg',
    note: '',
  },
  {
    id: 9025,
    tvmazeId: '26946',
    title: 'Patricia Cornwell\'s Win Garano',
    network: 'Lifetime',
    startYear: 2010,
    years: '2010',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/106/266124.jpg',
    note: '',
  },
  {
    id: 9026,
    tvmazeId: '1228',
    title: 'Penoza',
    network: 'NPO 3',
    startYear: 2010,
    years: '2010–2017',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/186/465916.jpg',
    note: '',
  },
  {
    id: 9027,
    tvmazeId: '4303',
    title: 'Perfect Couples',
    network: 'NBC',
    startYear: 2010,
    years: '2010–2011',
    genres: ['Comedy', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/51210.jpg',
    note: '',
  },
  {
    id: 9028,
    tvmazeId: '558',
    title: 'Persons Unknown',
    network: 'NBC',
    startYear: 2010,
    years: '2010',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'NBC cancelled after one season; the shadowy Programme holding people captive was never explained.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/4/11645.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 376, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
