window.pageShows = [
  {
    id: 17017,
    tvmazeId: '8420',
    title: 'Wagon Train',
    network: 'ABC',
    startYear: 1957,
    years: '1957–1965',
    genres: ['Drama', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/30/75307.jpg',
    note: '',
  },
  {
    id: 17018,
    tvmazeId: '61181',
    title: 'Whirlybirds',
    network: 'CBS',
    startYear: 1957,
    years: '1957–1960',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/401/1002586.jpg',
    note: '',
  },
  {
    id: 17019,
    tvmazeId: '65544',
    title: 'White Hunter',
    network: 'Syndication',
    startYear: 1957,
    years: '1957–1958',
    genres: ['Drama', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17020,
    tvmazeId: '4262',
    title: 'Zorro',
    network: 'ABC',
    startYear: 1957,
    years: '1957–1961',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/50956.jpg',
    note: '',
  },
  {
    id: 17021,
    tvmazeId: '82783',
    title: 'A Show Called Fred',
    network: 'ITV1',
    startYear: 1956,
    years: '1956',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17022,
    tvmazeId: '9756',
    title: 'Armchair Theatre',
    network: 'ITV1',
    startYear: 1956,
    years: '1956–1974',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/471/1179541.jpg',
    note: '',
  },
  {
    id: 17023,
    tvmazeId: '17907',
    title: 'As the World Turns',
    network: 'CBS',
    startYear: 1956,
    years: '1956–2010',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/60/151169.jpg',
    note: '',
  },
  {
    id: 17024,
    tvmazeId: '22160',
    title: 'Boomtown',
    network: 'Syndication',
    startYear: 1956,
    years: '1956',
    genres: ['Children', 'Family', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/80/202439.jpg',
    note: '',
  },
  {
    id: 17025,
    tvmazeId: '22145',
    title: 'Broken Arrow',
    network: 'ABC',
    startYear: 1956,
    years: '1956–1958',
    genres: ['Drama', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/80/202355.jpg',
    note: '',
  },
  {
    id: 17026,
    tvmazeId: '4267',
    title: 'Circus Boy',
    network: 'ABC',
    startYear: 1956,
    years: '1956–1957',
    genres: ['Adventure', 'Family', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/235/589370.jpg',
    note: '',
  },
  {
    id: 17027,
    tvmazeId: '58442',
    title: 'Colonel March of Scotland Yard',
    network: 'ITV1',
    startYear: 1956,
    years: '1956–1957',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/368/920236.jpg',
    note: '',
  },
  {
    id: 17028,
    tvmazeId: '75007',
    title: 'Conflict',
    network: 'ABC',
    startYear: 1956,
    years: '1956–1957',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17029,
    tvmazeId: '9472',
    title: 'Dick Powell\'s Zane Grey Theatre',
    network: 'CBS',
    startYear: 1956,
    years: '1956–1961',
    genres: ['Drama', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/82984.jpg',
    note: '',
  },
  {
    id: 17030,
    tvmazeId: '20445',
    title: 'Hancock\'s Half Hour',
    network: 'BBC One',
    startYear: 1956,
    years: '1956–1963',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/72/180766.jpg',
    note: '',
  },
  {
    id: 17031,
    tvmazeId: '59996',
    title: 'Hey, Jeannie!',
    network: 'CBS',
    startYear: 1956,
    years: '1956–1957',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/450/1127366.jpg',
    note: '',
  },
  {
    id: 17032,
    tvmazeId: '39504',
    title: 'Noah\'s Ark',
    network: 'NBC',
    startYear: 1956,
    years: '1956–1957',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/377/942570.jpg',
    note: '',
  },
  {
    id: 17033,
    tvmazeId: '21854',
    title: 'Playhouse 90',
    network: 'CBS',
    startYear: 1956,
    years: '1956–1960',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/78/196808.jpg',
    note: '',
  },
  {
    id: 17034,
    tvmazeId: '23955',
    title: 'Stanley',
    network: 'NBC',
    startYear: 1956,
    years: '1956–1957',
    genres: ['Comedy', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/90/226589.jpg',
    note: '',
  },
  {
    id: 17035,
    tvmazeId: '20537',
    title: 'State Trooper',
    network: 'NBC',
    startYear: 1956,
    years: '1956–1959',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/72/181507.jpg',
    note: '',
  },
  {
    id: 17036,
    tvmazeId: '56822',
    title: 'Tales of the 77th Bengal Lancers',
    network: 'NBC',
    startYear: 1956,
    years: '1956–1957',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/348/870926.jpg',
    note: '',
  },
  {
    id: 17037,
    tvmazeId: '75568',
    title: 'Telephone Time',
    network: 'ABC',
    startYear: 1956,
    years: '1956–1958',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/510/1275519.jpg',
    note: '',
  },
  {
    id: 17038,
    tvmazeId: '18670',
    title: 'The Adventures of Dr. Fu Manchu',
    network: 'Syndication',
    startYear: 1956,
    years: '1956',
    genres: ['Adventure', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/63/159763.jpg',
    note: '',
  },
  {
    id: 17039,
    tvmazeId: '36078',
    title: 'The Adventures of Hiram Holliday',
    network: 'NBC',
    startYear: 1956,
    years: '1956–1957',
    genres: ['Comedy', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/362/907471.jpg',
    note: '',
  },
  {
    id: 17040,
    tvmazeId: '16100',
    title: 'The Adventures of Jim Bowie',
    network: 'ABC',
    startYear: 1956,
    years: '1956–1958',
    genres: ['Action', 'Adventure', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/53/134722.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 710, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 398, "cliffhanger": 239, "ended": 15092}};
