window.pageShows = [
  {
    id: 10445,
    tvmazeId: '43130',
    title: 'Meet the Magoons',
    network: 'Channel 4',
    startYear: 2005,
    years: '2005',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 10446,
    tvmazeId: '16906',
    title: 'Mike Bassett: Manager',
    network: 'ITV1',
    startYear: 2005,
    years: '2005',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/56/142064.jpg',
    note: '',
  },
  {
    id: 10447,
    tvmazeId: '33020',
    title: 'Minoriteam',
    network: 'Adult Swim',
    startYear: 2005,
    years: '2005–2006',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/133/333214.jpg',
    note: '',
  },
  {
    id: 10448,
    tvmazeId: '1960',
    title: 'Moral Orel',
    network: 'Adult Swim',
    startYear: 2005,
    years: '2005–2008',
    genres: [],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/27902.jpg',
    note: '',
  },
  {
    id: 10449,
    tvmazeId: '62643',
    title: 'Muffin the Mule',
    network: 'CBeebies',
    startYear: 2005,
    years: '2005',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 10450,
    tvmazeId: '20434',
    title: 'My Gym Partner\'s a Monkey',
    network: 'Cartoon Network',
    startYear: 2005,
    years: '2005–2008',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/72/180780.jpg',
    note: '',
  },
  {
    id: 10451,
    tvmazeId: '15455',
    title: 'My Lovely Sam Soon',
    network: 'MBC',
    startYear: 2005,
    years: '2005',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/52/131218.jpg',
    note: '',
  },
  {
    id: 10452,
    tvmazeId: '678',
    title: 'My Name Is Earl',
    network: 'NBC',
    startYear: 2005,
    years: '2005–2009',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/5/14824.jpg',
    note: '',
  },
  {
    id: 10453,
    tvmazeId: '50149',
    title: 'Mysterious Island',
    network: 'Hallmark Channel',
    startYear: 2005,
    years: '2005',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/271/678987.jpg',
    note: '',
  },
  {
    id: 10454,
    tvmazeId: '2584',
    title: 'Nathan Barley',
    network: 'Channel 4',
    startYear: 2005,
    years: '2005',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/13/34456.jpg',
    note: '',
  },
  {
    id: 10455,
    tvmazeId: '22658',
    title: 'Naturally, Sadie',
    network: 'Family Channel',
    startYear: 2005,
    years: '2005–2007',
    genres: ['Drama', 'Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/83/209543.jpg',
    note: '',
  },
  {
    id: 10456,
    tvmazeId: '3648',
    title: 'New Captain Scarlet',
    network: 'ITV1',
    startYear: 2005,
    years: '2005',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/47287.jpg',
    note: '',
  },
  {
    id: 10457,
    tvmazeId: '13187',
    title: 'Night Stalker',
    network: 'ABC',
    startYear: 2005,
    years: '2005',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/293/733200.jpg',
    note: '',
  },
  {
    id: 10458,
    tvmazeId: '32957',
    title: 'Noah\'s Arc',
    network: 'Logo TV',
    startYear: 2005,
    years: '2005–2006',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/132/332408.jpg',
    note: '',
  },
  {
    id: 10459,
    tvmazeId: '6419',
    title: 'Nobuta wo Produce',
    network: 'NTV',
    startYear: 2005,
    years: '2005',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/24/61330.jpg',
    note: '',
  },
  {
    id: 10460,
    tvmazeId: '682',
    title: 'Numb3rs',
    network: 'CBS',
    startYear: 2005,
    years: '2005–2010',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/5/14852.jpg',
    note: '',
  },
  {
    id: 10461,
    tvmazeId: '1160',
    title: 'Out of Practice',
    network: 'CBS',
    startYear: 2005,
    years: '2005–2006',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17436.jpg',
    note: '',
  },
  {
    id: 10462,
    tvmazeId: '3086',
    title: 'Outrageous Fortune',
    network: 'Three',
    startYear: 2005,
    years: '2005–2010',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/17/42753.jpg',
    note: '',
  },
  {
    id: 10463,
    tvmazeId: '3287',
    title: 'Over There',
    network: 'FX',
    startYear: 2005,
    years: '2005–2006',
    genres: ['Drama', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/17/43910.jpg',
    note: '',
  },
  {
    id: 10464,
    tvmazeId: '27171',
    title: 'Pahappahooey Island',
    network: 'TBN',
    startYear: 2005,
    years: '2005–2006',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/107/268120.jpg',
    note: '',
  },
  {
    id: 10465,
    tvmazeId: '7818',
    title: 'Pastewka',
    network: 'Prime Video',
    startYear: 2005,
    years: '2005–2020',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/227/569645.jpg',
    note: '',
  },
  {
    id: 10466,
    tvmazeId: '27720',
    title: 'Perfect Hair Forever',
    network: 'Adult Swim',
    startYear: 2005,
    years: '2005–2014',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/109/273597.jpg',
    note: '',
  },
  {
    id: 10467,
    tvmazeId: '51479',
    title: 'Pet Alien',
    network: 'Cartoon Network',
    startYear: 2005,
    years: '2005',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/385/962791.jpg',
    note: '',
  },
  {
    id: 10468,
    tvmazeId: '68435',
    title: 'Planet Sketch',
    network: 'Télé Toon',
    startYear: 2005,
    years: '2005–2008',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  }
];
window.pageMetadata = {"page": 436, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
