window.pageShows = [
  {
    id: 17117,
    tvmazeId: '16191',
    title: 'Stories of the Century',
    network: 'Syndication',
    startYear: 1954,
    years: '1954–1955',
    genres: ['Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/54/135238.jpg',
    note: '',
  },
  {
    id: 17118,
    tvmazeId: '21859',
    title: 'Studio 57',
    network: 'Syndication',
    startYear: 1954,
    years: '1954–1957',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/78/196844.jpg',
    note: '',
  },
  {
    id: 17119,
    tvmazeId: '10604',
    title: 'The Adventures of Rin Tin Tin',
    network: 'ABC',
    startYear: 1954,
    years: '1954–1959',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/35/89272.jpg',
    note: '',
  },
  {
    id: 17120,
    tvmazeId: '59921',
    title: 'The Best of Broadway',
    network: 'CBS',
    startYear: 1954,
    years: '1954–1955',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17121,
    tvmazeId: '75056',
    title: 'The Elgin Hour',
    network: 'ABC',
    startYear: 1954,
    years: '1954–1955',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/506/1266783.jpg',
    note: '',
  },
  {
    id: 17122,
    tvmazeId: '62905',
    title: 'The Grove Family',
    network: 'BBC One',
    startYear: 1954,
    years: '1954–1957',
    genres: ['Drama', 'Family'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17123,
    tvmazeId: '48889',
    title: 'The Lineup',
    network: 'CBS',
    startYear: 1954,
    years: '1954–1960',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/478/1195390.jpg',
    note: '',
  },
  {
    id: 17124,
    tvmazeId: '62788',
    title: 'The Marriage',
    network: 'NBC',
    startYear: 1954,
    years: '1954',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17125,
    tvmazeId: '29760',
    title: 'The Mickey Rooney Show',
    network: 'NBC',
    startYear: 1954,
    years: '1954–1955',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/118/295862.jpg',
    note: '',
  },
  {
    id: 17126,
    tvmazeId: '42980',
    title: 'The Public Defender',
    network: 'CBS',
    startYear: 1954,
    years: '1954–1955',
    genres: ['Drama', 'Crime', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/204/512212.jpg',
    note: '',
  },
  {
    id: 17127,
    tvmazeId: '75647',
    title: 'The Vise',
    network: 'ABC',
    startYear: 1954,
    years: '1954–1960',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17128,
    tvmazeId: '71094',
    title: 'The Whistler',
    network: 'CBS',
    startYear: 1954,
    years: '1954–1955',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17129,
    tvmazeId: '22156',
    title: 'Action in the Afternoon',
    network: 'CBS',
    startYear: 1953,
    years: '1953',
    genres: ['Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17130,
    tvmazeId: '58443',
    title: 'Colonel Humphrey Flack',
    network: 'DuMont Television Network',
    startYear: 1953,
    years: '1953–1959',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17131,
    tvmazeId: '25234',
    title: 'Ethel and Albert',
    network: 'ABC',
    startYear: 1953,
    years: '1953–1956',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/97/244462.jpg',
    note: '',
  },
  {
    id: 17132,
    tvmazeId: '18432',
    title: 'General Electric Theater',
    network: 'CBS',
    startYear: 1953,
    years: '1953–1961',
    genres: ['Drama', 'Comedy', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/355/889201.jpg',
    note: '',
  },
  {
    id: 17133,
    tvmazeId: '59997',
    title: 'I\'m the Law',
    network: 'Syndication',
    startYear: 1953,
    years: '1953',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17134,
    tvmazeId: '12740',
    title: 'Make Room for Daddy',
    network: 'CBS',
    startYear: 1953,
    years: '1953–1964',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/43/109171.jpg',
    note: '',
  },
  {
    id: 17135,
    tvmazeId: '65961',
    title: 'Ponds Theater',
    network: 'ABC',
    startYear: 1953,
    years: '1953–1955',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17136,
    tvmazeId: '22601',
    title: 'Private Secretary',
    network: 'CBS',
    startYear: 1953,
    years: '1953–1957',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/83/208611.jpg',
    note: '',
  },
  {
    id: 17137,
    tvmazeId: '31779',
    title: 'Ramar of the Jungle',
    network: 'Syndication',
    startYear: 1953,
    years: '1953–1954',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/127/318429.jpg',
    note: '',
  },
  {
    id: 17138,
    tvmazeId: '24263',
    title: 'The Life of Riley',
    network: 'NBC',
    startYear: 1953,
    years: '1953–1958',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/92/230642.jpg',
    note: '',
  },
  {
    id: 17139,
    tvmazeId: '55226',
    title: 'The Loretta Young Show',
    network: 'NBC',
    startYear: 1953,
    years: '1953–1961',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/315/789605.jpg',
    note: '',
  },
  {
    id: 17140,
    tvmazeId: '38177',
    title: 'The Man Behind the Badge',
    network: 'CBS',
    startYear: 1953,
    years: '1953–1955',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/376/940825.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 714, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
