window.pageShows = [
  {
    id: 9481,
    tvmazeId: '77987',
    title: 'The Lake',
    network: 'TheWB.com',
    startYear: 2009,
    years: '2009',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/524/1311829.jpg',
    note: '',
  },
  {
    id: 9482,
    tvmazeId: '5267',
    title: 'The Last Templar',
    network: 'NBC',
    startYear: 2009,
    years: '2009',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/55022.jpg',
    note: '',
  },
  {
    id: 9483,
    tvmazeId: '270',
    title: 'The League',
    network: 'FXX',
    startYear: 2009,
    years: '2009–2015',
    genres: ['Comedy', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/1/4720.jpg',
    note: '',
  },
  {
    id: 9484,
    tvmazeId: '22314',
    title: 'The Legend of Dick and Dom',
    network: 'CBBC',
    startYear: 2009,
    years: '2009–2011',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/81/204199.jpg',
    note: '',
  },
  {
    id: 9485,
    tvmazeId: '7497',
    title: 'The Line',
    network: 'Crave',
    startYear: 2009,
    years: '2009',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/68962.jpg',
    note: '',
  },
  {
    id: 9486,
    tvmazeId: '1691',
    title: 'The Listener',
    network: 'CTV',
    startYear: 2009,
    years: '2009–2014',
    genres: ['Drama', 'Crime', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/9/23690.jpg',
    note: '',
  },
  {
    id: 9487,
    tvmazeId: '77',
    title: 'The Middle',
    network: 'ABC',
    startYear: 2009,
    years: '2009–2018',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/605/1514143.jpg',
    note: '',
  },
  {
    id: 9488,
    tvmazeId: '20981',
    title: 'The Nativity',
    network: 'BBC One',
    startYear: 2009,
    years: '2009',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/74/185145.jpg',
    note: '',
  },
  {
    id: 9489,
    tvmazeId: '6889',
    title: 'The No. 1 Ladies\' Detective Agency',
    network: 'BBC One',
    startYear: 2009,
    years: '2009',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/148/370681.jpg',
    note: '',
  },
  {
    id: 9490,
    tvmazeId: '49531',
    title: 'The Office: Blackmail',
    network: 'NBC',
    startYear: 2009,
    years: '2009',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 9491,
    tvmazeId: '49507',
    title: 'The Office: Subtle Sexuality',
    network: 'NBC.com',
    startYear: 2009,
    years: '2009',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/280/700888.jpg',
    note: '',
  },
  {
    id: 9492,
    tvmazeId: '18894',
    title: 'The Old Guys',
    network: 'BBC One',
    startYear: 2009,
    years: '2009–2010',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/65/163231.jpg',
    note: '',
  },
  {
    id: 9493,
    tvmazeId: '3891',
    title: 'The Phantom',
    network: 'Crave',
    startYear: 2009,
    years: '2009',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/48717.jpg',
    note: '',
  },
  {
    id: 9494,
    tvmazeId: '3999',
    title: 'The Philanthropist',
    network: 'NBC',
    startYear: 2009,
    years: '2009',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/49285.jpg',
    note: '',
  },
  {
    id: 9495,
    tvmazeId: '471',
    title: 'The Prisoner',
    network: 'AMC',
    startYear: 2009,
    years: '2009',
    genres: ['Drama', 'Science-Fiction', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/3/9294.jpg',
    note: '',
  },
  {
    id: 9496,
    tvmazeId: '30134',
    title: 'The Rising Son',
    network: 'Adult Swim',
    startYear: 2009,
    years: '2009',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/367/917877.jpg',
    note: '',
  },
  {
    id: 9497,
    tvmazeId: '24518',
    title: 'The Storm',
    network: 'NBC',
    startYear: 2009,
    years: '2009',
    genres: ['Drama', 'Science-Fiction', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/93/233774.jpg',
    note: '',
  },
  {
    id: 9498,
    tvmazeId: '26545',
    title: 'The Super Hero Squad Show',
    network: 'Cartoon Network',
    startYear: 2009,
    years: '2009–2013',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/104/261255.jpg',
    note: '',
  },
  {
    id: 9499,
    tvmazeId: '8356',
    title: 'The Take',
    network: 'Sky Showcase',
    startYear: 2009,
    years: '2009',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/74996.jpg',
    note: '',
  },
  {
    id: 9500,
    tvmazeId: '14285',
    title: 'The Troop',
    network: 'Nicktoons',
    startYear: 2009,
    years: '2009–2013',
    genres: ['Drama', 'Comedy', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/48/121462.jpg',
    note: '',
  },
  {
    id: 9501,
    tvmazeId: '3981',
    title: 'The Unusuals',
    network: 'ABC',
    startYear: 2009,
    years: '2009',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'ABC cancelled after one season; the 2nd Precinct detectives\' personal mysteries were unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/49200.jpg',
    note: '',
  },
  {
    id: 9502,
    tvmazeId: '63',
    title: 'The Vampire Diaries',
    network: 'The CW',
    startYear: 2009,
    years: '2009–2017',
    genres: ['Drama', 'Romance', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/271/677698.jpg',
    note: '',
  },
  {
    id: 9503,
    tvmazeId: '4501',
    title: 'Three Rivers',
    network: 'CBS',
    startYear: 2009,
    years: '2009–2010',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/52001.jpg',
    note: '',
  },
  {
    id: 9504,
    tvmazeId: '22281',
    title: 'Timmy Time',
    network: 'CBeebies',
    startYear: 2009,
    years: '2009–2012',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/81/203701.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 396, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
