window.pageShows = [
  {
    id: 14665,
    tvmazeId: '19638',
    title: 'Agatha Christie\'s Partners in Crime',
    network: 'ITV1',
    startYear: 1983,
    years: '1983–1984',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/69/173778.jpg',
    note: '',
  },
  {
    id: 14666,
    tvmazeId: '16831',
    title: 'Alfresco',
    network: 'ITV1',
    startYear: 1983,
    years: '1983–1984',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/56/140603.jpg',
    note: '',
  },
  {
    id: 14667,
    tvmazeId: '20752',
    title: 'All the Rivers Run',
    network: 'Seven Network',
    startYear: 1983,
    years: '1983–1990',
    genres: ['Drama', 'Adventure', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/183549.jpg',
    note: '',
  },
  {
    id: 14668,
    tvmazeId: '18514',
    title: 'Alvin and the Chipmunks',
    network: 'NBC',
    startYear: 1983,
    years: '1983–1990',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/63/157989.jpg',
    note: '',
  },
  {
    id: 14669,
    tvmazeId: '47998',
    title: 'Amanda\'s',
    network: 'ABC',
    startYear: 1983,
    years: '1983',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/256/640861.jpg',
    note: '',
  },
  {
    id: 14670,
    tvmazeId: '74472',
    title: 'At Ease',
    network: 'ABC',
    startYear: 1983,
    years: '1983',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/515/1288082.jpg',
    note: '',
  },
  {
    id: 14671,
    tvmazeId: '4791',
    title: 'Auf Wiedersehen, Pet',
    network: 'BBC One',
    startYear: 1983,
    years: '1983–2004',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/53254.jpg',
    note: '',
  },
  {
    id: 14672,
    tvmazeId: '8733',
    title: 'Automan',
    network: 'ABC',
    startYear: 1983,
    years: '1983–1984',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/77737.jpg',
    note: '',
  },
  {
    id: 14673,
    tvmazeId: '41318',
    title: 'Baby Makes Five',
    network: 'ABC',
    startYear: 1983,
    years: '1983',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/379/948744.jpg',
    note: '',
  },
  {
    id: 14674,
    tvmazeId: '5677',
    title: 'Bananaman',
    network: 'BBC One',
    startYear: 1983,
    years: '1983–1986',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/56896.jpg',
    note: '',
  },
  {
    id: 14675,
    tvmazeId: '57608',
    title: 'Bay City Blues',
    network: 'NBC',
    startYear: 1983,
    years: '1983–1984',
    genres: ['Drama', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/357/892865.jpg',
    note: '',
  },
  {
    id: 14676,
    tvmazeId: '34296',
    title: 'Benji, Zax and the Alien Prince',
    network: 'CBS',
    startYear: 1983,
    years: '1983',
    genres: ['Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/141/354242.jpg',
    note: '',
  },
  {
    id: 14677,
    tvmazeId: '1072',
    title: 'Blackadder',
    network: 'BBC One',
    startYear: 1983,
    years: '1983–1989',
    genres: ['Comedy', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17102.jpg',
    note: '',
  },
  {
    id: 14678,
    tvmazeId: '25218',
    title: 'Boone',
    network: 'NBC',
    startYear: 1983,
    years: '1983–1984',
    genres: ['Drama', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/155/389000.jpg',
    note: '',
  },
  {
    id: 14679,
    tvmazeId: '31366',
    title: 'Brass',
    network: 'Channel 4',
    startYear: 1983,
    years: '1983–1990',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/125/313072.jpg',
    note: '',
  },
  {
    id: 14680,
    tvmazeId: '19530',
    title: 'Buffalo Bill',
    network: 'NBC',
    startYear: 1983,
    years: '1983–1984',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/99/247897.jpg',
    note: '',
  },
  {
    id: 14681,
    tvmazeId: '22376',
    title: 'By the Sword Divided',
    network: 'BBC One',
    startYear: 1983,
    years: '1983–1985',
    genres: ['Drama', 'War', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/82/205328.jpg',
    note: '',
  },
  {
    id: 14682,
    tvmazeId: '58248',
    title: 'Captain Zep - Space Detective',
    network: 'BBC One',
    startYear: 1983,
    years: '1983–1984',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14683,
    tvmazeId: '61076',
    title: 'Carson\'s Law',
    network: 'Network 10',
    startYear: 1983,
    years: '1983',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14684,
    tvmazeId: '20694',
    title: 'Casablanca',
    network: 'NBC',
    startYear: 1983,
    years: '1983',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/182791.jpg',
    note: '',
  },
  {
    id: 14685,
    tvmazeId: '50663',
    title: 'Chiefs',
    network: 'CBS',
    startYear: 1983,
    years: '1983',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/275/687647.jpg',
    note: '',
  },
  {
    id: 14686,
    tvmazeId: '74475',
    title: 'Condo',
    network: 'ABC',
    startYear: 1983,
    years: '1983',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14687,
    tvmazeId: '79855',
    title: 'Cuffy',
    network: 'ITV1',
    startYear: 1983,
    years: '1983',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/537/1343647.jpg',
    note: '',
  },
  {
    id: 14688,
    tvmazeId: '23044',
    title: 'Cutter to Houston',
    network: 'CBS',
    startYear: 1983,
    years: '1983',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/360/901116.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 612, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
