window.pageShows = [
  {
    id: 6817,
    tvmazeId: '23146',
    title: 'Valea Mută',
    network: 'HBO',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/86/216256.jpg',
    note: '',
  },
  {
    id: 6818,
    tvmazeId: '7523',
    title: 'Van Helsing',
    network: 'Syfy',
    startYear: 2016,
    years: '2016–2021',
    genres: ['Drama', 'Action', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/302/755126.jpg',
    note: '',
  },
  {
    id: 6819,
    tvmazeId: '3605',
    title: 'Vice Principals',
    network: 'HBO',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/127/319704.jpg',
    note: '',
  },
  {
    id: 6820,
    tvmazeId: '8699',
    title: 'Victoria',
    network: 'PBS',
    startYear: 2016,
    years: '2016–2019',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/179/448340.jpg',
    note: '',
  },
  {
    id: 6821,
    tvmazeId: '3603',
    title: 'Vinyl',
    network: 'HBO',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Music'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'HBO cancelled after one season; Richie Finestra\'s rock music empire and cocaine-fuelled decline were just beginning.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/355/889340.jpg',
    note: '',
  },
  {
    id: 6822,
    tvmazeId: '15296',
    title: 'Voltron: Legendary Defender',
    network: 'Netflix',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Action', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: 'Netflix gave the series an eight-season planned conclusion, though some fans found the ending rushed.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/52/130137.jpg',
    note: '',
  },
  {
    id: 6823,
    tvmazeId: '14842',
    title: 'W',
    network: 'MBC',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Romance', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/68/170142.jpg',
    note: '',
  },
  {
    id: 6824,
    tvmazeId: '12560',
    title: 'Wanted',
    network: 'Seven Network',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/44/110213.jpg',
    note: '',
  },
  {
    id: 6825,
    tvmazeId: '3374',
    title: 'War & Peace',
    network: 'BBC One',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Romance', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/37/93943.jpg',
    note: '',
  },
  {
    id: 6826,
    tvmazeId: '7387',
    title: 'Wasted',
    network: 'E4',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/275/689829.jpg',
    note: '',
  },
  {
    id: 6827,
    tvmazeId: '18860',
    title: 'Weightlifting Fairy Kim Bok Joo',
    network: 'MBC',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Drama', 'Romance', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/85/212837.jpg',
    note: '',
  },
  {
    id: 6828,
    tvmazeId: '1371',
    title: 'Westworld',
    network: 'HBO',
    startYear: 2016,
    years: '2016–2022',
    genres: ['Drama', 'Science-Fiction', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: 'Season 4 was crafted as a planned series finale; the story was brought to a self-contained close.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/445/1113927.jpg',
    note: '',
  },
  {
    id: 6829,
    tvmazeId: '25670',
    title: 'Wham Bam Thank You Ma\'am',
    network: 'ABC Family',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/100/250211.jpg',
    note: '',
  },
  {
    id: 6830,
    tvmazeId: '44620',
    title: 'What the Fuck France',
    network: 'Canal+',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/216/541554.jpg',
    note: '',
  },
  {
    id: 6831,
    tvmazeId: '35194',
    title: 'When TV Was Awesome',
    network: 'ABC iview',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/147/369484.jpg',
    note: '',
  },
  {
    id: 6832,
    tvmazeId: '23641',
    title: 'Windscreen Watch',
    network: 'C31',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 6833,
    tvmazeId: '21117',
    title: 'Winston Steinburger & Sir Dudley Ding Dong',
    network: 'ABC Entertains',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/74/186353.jpg',
    note: '',
  },
  {
    id: 6834,
    tvmazeId: '8701',
    title: 'Witless',
    network: 'BBC Three',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/54/136095.jpg',
    note: '',
  },
  {
    id: 6835,
    tvmazeId: '12039',
    title: 'Wolf Creek',
    network: 'Stan',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Drama', 'Horror', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/498/1245285.jpg',
    note: '',
  },
  {
    id: 6836,
    tvmazeId: '21192',
    title: 'Wolfblood Secrets',
    network: 'CBBC',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Drama', 'Action', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/78/197040.jpg',
    note: '',
  },
  {
    id: 6837,
    tvmazeId: '11920',
    title: 'Word Party',
    network: 'Netflix',
    startYear: 2016,
    years: '2016–2021',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/195/488700.jpg',
    note: '',
  },
  {
    id: 6838,
    tvmazeId: '22651',
    title: 'World of Winx',
    network: 'Netflix',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/83/209286.jpg',
    note: '',
  },
  {
    id: 6839,
    tvmazeId: '3590',
    title: 'Wrecked',
    network: 'TBS',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Comedy', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/117/293992.jpg',
    note: '',
  },
  {
    id: 6840,
    tvmazeId: '6767',
    title: 'Wynonna Earp',
    network: 'Syfy',
    startYear: 2016,
    years: '2016–2024',
    genres: ['Drama', 'Western', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/206/515140.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 285, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
