window.pageShows = [
  {
    id: 16897,
    tvmazeId: '16186',
    title: 'Overland Trail',
    network: 'NBC',
    startYear: 1960,
    years: '1960',
    genres: ['Action', 'Adventure', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/54/135234.jpg',
    note: '',
  },
  {
    id: 16898,
    tvmazeId: '3668',
    title: 'Pathfinders in Space',
    network: 'ITV1',
    startYear: 1960,
    years: '1960',
    genres: ['Drama', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/47345.jpg',
    note: '',
  },
  {
    id: 16899,
    tvmazeId: '3666',
    title: 'Pathfinders to Mars',
    network: 'ITV1',
    startYear: 1960,
    years: '1960–1961',
    genres: ['Drama', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/47343.jpg',
    note: '',
  },
  {
    id: 16900,
    tvmazeId: '42874',
    title: 'Pete and Gladys',
    network: 'CBS',
    startYear: 1960,
    years: '1960–1962',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/380/951337.jpg',
    note: '',
  },
  {
    id: 16901,
    tvmazeId: '58971',
    title: 'Peter Loves Mary',
    network: 'NBC',
    startYear: 1960,
    years: '1960–1961',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 16902,
    tvmazeId: '29364',
    title: 'Police Surgeon',
    network: 'ITV1',
    startYear: 1960,
    years: '1960',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/117/292552.jpg',
    note: '',
  },
  {
    id: 16903,
    tvmazeId: '21977',
    title: 'Q.T. Hush',
    network: 'Syndication',
    startYear: 1960,
    years: '1960–1961',
    genres: ['Crime', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/79/199027.jpg',
    note: '',
  },
  {
    id: 16904,
    tvmazeId: '4382',
    title: 'Route 66',
    network: 'CBS',
    startYear: 1960,
    years: '1960–1964',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/51672.jpg',
    note: '',
  },
  {
    id: 16905,
    tvmazeId: '17437',
    title: 'Stagecoach West',
    network: 'ABC',
    startYear: 1960,
    years: '1960–1961',
    genres: ['Drama', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/58/147180.jpg',
    note: '',
  },
  {
    id: 16906,
    tvmazeId: '6274',
    title: 'SurfSide 6',
    network: 'ABC',
    startYear: 1960,
    years: '1960–1962',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/516/1291087.jpg',
    note: '',
  },
  {
    id: 16907,
    tvmazeId: '57486',
    title: 'Sykes and a...',
    network: 'BBC One',
    startYear: 1960,
    years: '1960–1965',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/356/890469.jpg',
    note: '',
  },
  {
    id: 16908,
    tvmazeId: '53940',
    title: 'Target Luna',
    network: 'ABC Weekend TV',
    startYear: 1960,
    years: '1960',
    genres: ['Drama', 'Family', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 16909,
    tvmazeId: '40982',
    title: 'Tate',
    network: 'NBC',
    startYear: 1960,
    years: '1960',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/183/459650.jpg',
    note: '',
  },
  {
    id: 16910,
    tvmazeId: '3853',
    title: 'The Andy Griffith Show',
    network: 'CBS',
    startYear: 1960,
    years: '1960–1968',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/494/1235133.jpg',
    note: '',
  },
  {
    id: 16911,
    tvmazeId: '18599',
    title: 'The Aquanauts',
    network: 'CBS',
    startYear: 1960,
    years: '1960–1961',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/469/1172548.jpg',
    note: '',
  },
  {
    id: 16912,
    tvmazeId: '39667',
    title: 'The Barbara Stanwyck Show',
    network: 'NBC',
    startYear: 1960,
    years: '1960–1961',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/174/435431.jpg',
    note: '',
  },
  {
    id: 16913,
    tvmazeId: '70326',
    title: 'The Brothers Brannagan',
    network: 'Syndication',
    startYear: 1960,
    years: '1960–1961',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/471/1178335.jpg',
    note: '',
  },
  {
    id: 16914,
    tvmazeId: '21978',
    title: 'The Bugs Bunny Show',
    network: 'ABC',
    startYear: 1960,
    years: '1960–1971',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/79/199028.jpg',
    note: '',
  },
  {
    id: 16915,
    tvmazeId: '60022',
    title: 'The Case of the Dangerous Robin',
    network: 'Syndication',
    startYear: 1960,
    years: '1960–1961',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/501/1254693.jpg',
    note: '',
  },
  {
    id: 16916,
    tvmazeId: '40336',
    title: 'The Cheaters',
    network: 'ITV1',
    startYear: 1960,
    years: '1960–1962',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/179/448729.jpg',
    note: '',
  },
  {
    id: 16917,
    tvmazeId: '56087',
    title: 'The Chevy Mystery Show',
    network: 'NBC',
    startYear: 1960,
    years: '1960',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/396/992368.jpg',
    note: '',
  },
  {
    id: 16918,
    tvmazeId: '21079',
    title: 'The Edgar Wallace Mysteries',
    network: 'ITV1',
    startYear: 1960,
    years: '1960–1963',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/74/185949.jpg',
    note: '',
  },
  {
    id: 16919,
    tvmazeId: '2143',
    title: 'The Flintstones',
    network: 'ABC',
    startYear: 1960,
    years: '1960–1966',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/29907.jpg',
    note: '',
  },
  {
    id: 16920,
    tvmazeId: '75165',
    title: 'The Islanders',
    network: 'ABC',
    startYear: 1960,
    years: '1960–1961',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/516/1291103.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 705, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
