window.pageShows = [
  {
    id: 3601,
    tvmazeId: '33989',
    title: 'Dead Lucky',
    network: 'SBS',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/163/407568.jpg',
    note: '',
  },
  {
    id: 3602,
    tvmazeId: '46990',
    title: 'Deadwax',
    network: 'Shudder',
    startYear: 2018,
    years: '2018',
    genres: ['Horror', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/383/958687.jpg',
    note: '',
  },
  {
    id: 3603,
    tvmazeId: '36953',
    title: 'Death and Nightingales',
    network: 'BBC Two',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/173/433058.jpg',
    note: '',
  },
  {
    id: 3604,
    tvmazeId: '24624',
    title: 'Deception',
    network: 'ABC',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'ABC cancelled after one season; magician Cameron Black\'s FBI partnership and the big mystery were unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/147/367898.jpg',
    note: '',
  },
  {
    id: 3605,
    tvmazeId: '34318',
    title: 'Deep State',
    network: 'FOX',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Drama', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/194/485335.jpg',
    note: '',
  },
  {
    id: 3606,
    tvmazeId: '37003',
    title: 'Defending the Guilty',
    network: 'BBC Two',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/169/423366.jpg',
    note: '',
  },
  {
    id: 3607,
    tvmazeId: '33320',
    title: 'Derry Girls',
    network: 'Channel 4',
    startYear: 2018,
    years: '2018–2022',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/402/1007479.jpg',
    note: '',
  },
  {
    id: 3608,
    tvmazeId: '40877',
    title: 'Die Trying',
    network: 'Prime Video',
    startYear: 2018,
    years: '2018',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/182/456914.jpg',
    note: '',
  },
  {
    id: 3609,
    tvmazeId: '30872',
    title: 'Dietland',
    network: 'AMC',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/154/387243.jpg',
    note: '',
  },
  {
    id: 3610,
    tvmazeId: '36068',
    title: 'Dirt',
    network: 'YouTube',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Drama', 'Romance', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/301/754917.jpg',
    note: '',
  },
  {
    id: 3611,
    tvmazeId: '34649',
    title: 'Dirty John',
    network: 'USA Network',
    startYear: 2018,
    years: '2018–2020',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/579/1448722.jpg',
    note: '',
  },
  {
    id: 3612,
    tvmazeId: '30715',
    title: 'Disenchantment',
    network: 'Netflix',
    startYear: 2018,
    years: '2018–2023',
    genres: ['Comedy', 'Adventure', 'Fantasy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Netflix cancelled after five parts; Bean\'s destiny and Dreamland\'s fate were left partially open in an ambiguous finale.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/156/391231.jpg',
    note: '',
  },
  {
    id: 3613,
    tvmazeId: '39427',
    title: 'Don\'t Watch This',
    network: 'Netflix',
    startYear: 2018,
    years: '2018',
    genres: ['Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/173/433380.jpg',
    note: '',
  },
  {
    id: 3614,
    tvmazeId: '38094',
    title: 'Donald Duck in Legend of the Three Caballeros',
    network: 'DisneyLife',
    startYear: 2018,
    years: '2018',
    genres: ['Comedy', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/403/1009698.jpg',
    note: '',
  },
  {
    id: 3615,
    tvmazeId: '36409',
    title: 'Doomsday',
    network: 'Prime Video',
    startYear: 2018,
    years: '2018',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/525/1312829.jpg',
    note: '',
  },
  {
    id: 3616,
    tvmazeId: '56869',
    title: 'Drag Tots',
    network: 'WOW Presents Plus',
    startYear: 2018,
    years: '2018–2021',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/476/1191425.jpg',
    note: '',
  },
  {
    id: 3617,
    tvmazeId: '40179',
    title: 'Driven',
    network: 'PassionFlix',
    startYear: 2018,
    years: '2018–2022',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/178/445717.jpg',
    note: '',
  },
  {
    id: 3618,
    tvmazeId: '39966',
    title: 'Dystopia',
    network: 'Prime Video',
    startYear: 2018,
    years: '2018',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/228/571161.jpg',
    note: '',
  },
  {
    id: 3619,
    tvmazeId: '58715',
    title: 'Enchantimals: Tales from Everwilde',
    network: 'ABC',
    startYear: 2018,
    years: '2018–2019',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/371/929169.jpg',
    note: '',
  },
  {
    id: 3620,
    tvmazeId: '30764',
    title: 'Enterprice',
    network: 'BBC Three',
    startYear: 2018,
    years: '2018–2020',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/176/440084.jpg',
    note: '',
  },
  {
    id: 3621,
    tvmazeId: '28857',
    title: 'Escape at Dannemora',
    network: 'Paramount+ with Showtime',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/173/433542.jpg',
    note: '',
  },
  {
    id: 3622,
    tvmazeId: '40810',
    title: 'Esluna: The First Monolith',
    network: 'YouTube',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/182/456063.jpg',
    note: '',
  },
  {
    id: 3623,
    tvmazeId: '48041',
    title: 'Esme & Roy',
    network: 'HBO Max',
    startYear: 2018,
    years: '2018–2021',
    genres: ['Adventure', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/259/649564.jpg',
    note: '',
  },
  {
    id: 3624,
    tvmazeId: '29895',
    title: 'Everything Sucks!',
    network: 'Netflix',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Netflix cancelled after one season; Kate and Luke\'s relationship and the Boring Oregon friend group were just developing.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/142/356594.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 151, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 785, "cliffhanger": 237, "ended": 13610}};
