window.pageShows = [
  {
    id: 16465,
    tvmazeId: '8812',
    title: 'No, That\'s Me Over Here!',
    network: 'ITV1',
    startYear: 1967,
    years: '1967–1970',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/78336.jpg',
    note: '',
  },
  {
    id: 16466,
    tvmazeId: '41339',
    title: 'Not in Front of the Children',
    network: 'BBC One',
    startYear: 1967,
    years: '1967–1969',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/187/468950.jpg',
    note: '',
  },
  {
    id: 16467,
    tvmazeId: '74723',
    title: 'Rango',
    network: 'ABC',
    startYear: 1967,
    years: '1967',
    genres: ['Comedy', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/504/1261535.jpg',
    note: '',
  },
  {
    id: 16468,
    tvmazeId: '16953',
    title: 'Rocket Robin Hood',
    network: 'Syndication',
    startYear: 1967,
    years: '1967',
    genres: ['Adventure', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/57/142514.jpg',
    note: '',
  },
  {
    id: 16469,
    tvmazeId: '11598',
    title: 'Sanctuary',
    network: 'ITV London',
    startYear: 1967,
    years: '1967–1968',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: '',
    note: '',
  },
  {
    id: 16470,
    tvmazeId: '26953',
    title: 'Shazzan',
    network: 'CBS',
    startYear: 1967,
    years: '1967–1968',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/106/266212.jpg',
    note: '',
  },
  {
    id: 16471,
    tvmazeId: '14152',
    title: 'Speed Racer',
    network: 'Syndication',
    startYear: 1967,
    years: '1967–1968',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/48/120810.jpg',
    note: '',
  },
  {
    id: 16472,
    tvmazeId: '4107',
    title: 'Spider-Man',
    network: 'Syndication',
    startYear: 1967,
    years: '1967–1970',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/49914.jpg',
    note: '',
  },
  {
    id: 16473,
    tvmazeId: '56080',
    title: 'The Danny Thomas Hour',
    network: 'NBC',
    startYear: 1967,
    years: '1967–1968',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/389/974070.jpg',
    note: '',
  },
  {
    id: 16474,
    tvmazeId: '7079',
    title: 'The Flash',
    network: 'CBS',
    startYear: 1967,
    years: '1967',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/73727.jpg',
    note: '',
  },
  {
    id: 16475,
    tvmazeId: '4966',
    title: 'The Flying Nun',
    network: 'ABC',
    startYear: 1967,
    years: '1967–1970',
    genres: ['Comedy', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/53899.jpg',
    note: '',
  },
  {
    id: 16476,
    tvmazeId: '13348',
    title: 'The Forsyte Saga',
    network: 'BBC Two',
    startYear: 1967,
    years: '1967',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/46/115541.jpg',
    note: '',
  },
  {
    id: 16477,
    tvmazeId: '62725',
    title: 'The Further Adventures of the Musketeers',
    network: 'BBC One',
    startYear: 1967,
    years: '1967',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/413/1034744.jpg',
    note: '',
  },
  {
    id: 16478,
    tvmazeId: '53385',
    title: 'The Galaxy Trio',
    network: 'NBC',
    startYear: 1967,
    years: '1967–1968',
    genres: ['Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/295/739596.jpg',
    note: '',
  },
  {
    id: 16479,
    tvmazeId: '8424',
    title: 'The Guns of Will Sonnett',
    network: 'ABC',
    startYear: 1967,
    years: '1967–1969',
    genres: ['Action', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/30/75314.jpg',
    note: '',
  },
  {
    id: 16480,
    tvmazeId: '3778',
    title: 'The Herculoids',
    network: 'CBS',
    startYear: 1967,
    years: '1967–1968',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/47925.jpg',
    note: '',
  },
  {
    id: 16481,
    tvmazeId: '16022',
    title: 'The High Chaparral',
    network: 'NBC',
    startYear: 1967,
    years: '1967–1971',
    genres: ['Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/53/134292.jpg',
    note: '',
  },
  {
    id: 16482,
    tvmazeId: '2144',
    title: 'The Invaders',
    network: 'ABC',
    startYear: 1967,
    years: '1967–1968',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/29908.jpg',
    note: '',
  },
  {
    id: 16483,
    tvmazeId: '55188',
    title: 'The Jerry Lewis Show',
    network: 'NBC',
    startYear: 1967,
    years: '1967–1969',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/315/787588.jpg',
    note: '',
  },
  {
    id: 16484,
    tvmazeId: '28616',
    title: 'The Lion, the Witch and the Wardrobe',
    network: 'ITV1',
    startYear: 1967,
    years: '1967',
    genres: ['Drama', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/113/284797.jpg',
    note: '',
  },
  {
    id: 16485,
    tvmazeId: '17778',
    title: 'The Mothers-In-Law',
    network: 'NBC',
    startYear: 1967,
    years: '1967–1969',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/59/149874.jpg',
    note: '',
  },
  {
    id: 16486,
    tvmazeId: '3848',
    title: 'The Outsider',
    network: 'NBC',
    startYear: 1967,
    years: '1967–1969',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/302/755430.jpg',
    note: '',
  },
  {
    id: 16487,
    tvmazeId: '470',
    title: 'The Prisoner',
    network: 'ITV1',
    startYear: 1967,
    years: '1967–1968',
    genres: ['Drama', 'Science-Fiction', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/3/9292.jpg',
    note: '',
  },
  {
    id: 16488,
    tvmazeId: '37102',
    title: 'The Reluctant Romeo',
    network: 'BBC One',
    startYear: 1967,
    years: '1967',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  }
];
window.pageMetadata = {"page": 687, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
