window.pageShows = [
  {
    id: 4921,
    tvmazeId: '33129',
    title: 'The Name of the Rose',
    network: 'Rai 1',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/186/466564.jpg',
    note: '',
  },
  {
    id: 4922,
    tvmazeId: '42349',
    title: 'The Ninth',
    network: 'CBC Gem',
    startYear: 2019,
    years: '2019',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/199/499360.jpg',
    note: '',
  },
  {
    id: 4923,
    tvmazeId: '36218',
    title: 'The Order',
    network: 'Netflix',
    startYear: 2019,
    years: '2019–2020',
    genres: ['Drama', 'Fantasy', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/261/654947.jpg',
    note: '',
  },
  {
    id: 4924,
    tvmazeId: '39333',
    title: 'The Other Two',
    network: 'HBO Max',
    startYear: 2019,
    years: '2019–2023',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/459/1149370.jpg',
    note: '',
  },
  {
    id: 4925,
    tvmazeId: '22766',
    title: 'The Passage',
    network: 'FOX',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Horror', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/174/437131.jpg',
    note: '',
  },
  {
    id: 4926,
    tvmazeId: '44306',
    title: 'The Perfect Plan',
    network: 'Facebook Watch',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Comedy', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/214/536563.jpg',
    note: '',
  },
  {
    id: 4927,
    tvmazeId: '34784',
    title: 'The Politician',
    network: 'Netflix',
    startYear: 2019,
    years: '2019–2020',
    genres: ['Drama', 'Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Netflix effectively shelved after two seasons; Payton Hobart\'s political ambitions were left mid-arc.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/257/643545.jpg',
    note: '',
  },
  {
    id: 4928,
    tvmazeId: '45350',
    title: 'The Prince of Tennis',
    network: 'Hunan TV',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/230/575403.jpg',
    note: '',
  },
  {
    id: 4929,
    tvmazeId: '36707',
    title: 'The Red Line',
    network: 'CBS',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/193/484382.jpg',
    note: '',
  },
  {
    id: 4930,
    tvmazeId: '37387',
    title: 'The Righteous Gemstones',
    network: 'HBO',
    startYear: 2019,
    years: '2019–2025',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/560/1401883.jpg',
    note: '',
  },
  {
    id: 4931,
    tvmazeId: '35136',
    title: 'The Rocketeer',
    network: 'DisneyNOW',
    startYear: 2019,
    years: '2019–2020',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/219/548111.jpg',
    note: '',
  },
  {
    id: 4932,
    tvmazeId: '8969',
    title: 'The Rook',
    network: 'STARZ',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Thriller', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/195/488859.jpg',
    note: '',
  },
  {
    id: 4933,
    tvmazeId: '43526',
    title: 'The Rubbish World of Dave Spud',
    network: 'ITVX',
    startYear: 2019,
    years: '2019–2024',
    genres: ['Adventure', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/301/753640.jpg',
    note: '',
  },
  {
    id: 4934,
    tvmazeId: '38533',
    title: 'The Society',
    network: 'Netflix',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Science-Fiction', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Netflix cancelled after one season, with the mystery of how the teens were transported and whether they could return left open.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/191/478974.jpg',
    note: '',
  },
  {
    id: 4935,
    tvmazeId: '36789',
    title: 'The Spanish Princess',
    network: 'STARZ',
    startYear: 2019,
    years: '2019–2020',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/272/681744.jpg',
    note: '',
  },
  {
    id: 4936,
    tvmazeId: '35968',
    title: 'The Spy',
    network: 'Netflix',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Thriller', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/209/523364.jpg',
    note: '',
  },
  {
    id: 4937,
    tvmazeId: '40421',
    title: 'The Stranded',
    network: 'Netflix',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Adventure', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/222/555975.jpg',
    note: '',
  },
  {
    id: 4938,
    tvmazeId: '44862',
    title: 'The Strange Chores',
    network: 'ABC iview',
    startYear: 2019,
    years: '2019–',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/416/1040681.jpg',
    note: '',
  },
  {
    id: 4939,
    tvmazeId: '41832',
    title: 'The Tale of Nokdu',
    network: 'KBS2',
    startYear: 2019,
    years: '2019',
    genres: ['Comedy', 'Romance', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/212/532340.jpg',
    note: '',
  },
  {
    id: 4940,
    tvmazeId: '44959',
    title: 'The Third checkifcancelled',
    network: 'Dekkoo',
    startYear: 2019,
    years: '2019–',
    genres: ['Drama', 'Comedy', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/221/553337.jpg',
    note: '',
  },
  {
    id: 4941,
    tvmazeId: '32492',
    title: 'The Trial of Christine Keeler',
    network: 'BBC One',
    startYear: 2019,
    years: '2019–2020',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/402/1005102.jpg',
    note: '',
  },
  {
    id: 4942,
    tvmazeId: '33153',
    title: 'The Twilight Zone',
    network: 'Paramount+',
    startYear: 2019,
    years: '2019–2020',
    genres: ['Drama', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/256/641058.jpg',
    note: '',
  },
  {
    id: 4943,
    tvmazeId: '30386',
    title: 'The Umbrella Academy',
    network: 'Netflix',
    startYear: 2019,
    years: '2019–2024',
    genres: ['Drama', 'Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/529/1324589.jpg',
    note: '',
  },
  {
    id: 4944,
    tvmazeId: '41534',
    title: 'The Unexplainers',
    network: 'BBC Two Wales',
    startYear: 2019,
    years: '2019',
    genres: ['Comedy', 'Adventure', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/189/474209.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 206, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
