window.pageShows = [
  {
    id: 12961,
    tvmazeId: '22271',
    title: 'The Powers of Matthew Star',
    network: 'NBC',
    startYear: 1982,
    years: '1982–1983',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/359/899235.jpg',
    note: '',
  },
  {
    id: 12962,
    tvmazeId: '65041',
    title: 'The Renegades',
    network: 'ABC',
    startYear: 1982,
    years: '1982–1983',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/429/1074496.jpg',
    note: '',
  },
  {
    id: 12963,
    tvmazeId: '65563',
    title: 'The Snowman',
    network: 'Channel 4',
    startYear: 1982,
    years: '1982–2012',
    genres: ['Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/433/1083855.jpg',
    note: '',
  },
  {
    id: 12964,
    tvmazeId: '36202',
    title: 'The Woman in White',
    network: 'BBC One',
    startYear: 1982,
    years: '1982',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/153/382680.jpg',
    note: '',
  },
  {
    id: 12965,
    tvmazeId: '1151',
    title: 'The Young Ones',
    network: 'BBC Two',
    startYear: 1982,
    years: '1982–1984',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/62/155416.jpg',
    note: '',
  },
  {
    id: 12966,
    tvmazeId: '48011',
    title: 'Third Time Lucky',
    network: 'ITV Yorkshire',
    startYear: 1982,
    years: '1982',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12967,
    tvmazeId: '7351',
    title: 'Today\'s Special',
    network: 'TVO',
    startYear: 1982,
    years: '1982–1987',
    genres: ['Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/67817.jpg',
    note: '',
  },
  {
    id: 12968,
    tvmazeId: '78996',
    title: 'Tom, Dick and Harriet',
    network: 'ITV1',
    startYear: 1982,
    years: '1982–1983',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12969,
    tvmazeId: '41036',
    title: 'Tucker\'s Witch',
    network: 'CBS',
    startYear: 1982,
    years: '1982–1983',
    genres: ['Drama', 'Comedy', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/184/461038.jpg',
    note: '',
  },
  {
    id: 12970,
    tvmazeId: '39069',
    title: 'Union Castle',
    network: 'ITV1',
    startYear: 1982,
    years: '1982',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12971,
    tvmazeId: '1507',
    title: 'Voyagers!',
    network: 'NBC',
    startYear: 1982,
    years: '1982–1983',
    genres: ['Adventure', 'Family', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/8/21239.jpg',
    note: '',
  },
  {
    id: 12972,
    tvmazeId: '71521',
    title: 'We\'ll Meet Again',
    network: 'ITV1',
    startYear: 1982,
    years: '1982',
    genres: ['Drama', 'Romance', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/478/1196920.jpg',
    note: '',
  },
  {
    id: 12973,
    tvmazeId: '3680',
    title: 'Whoops Apocalypse',
    network: 'ITV1',
    startYear: 1982,
    years: '1982',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/47399.jpg',
    note: '',
  },
  {
    id: 12974,
    tvmazeId: '17255',
    title: 'Wood & Walters',
    network: 'ITV1',
    startYear: 1982,
    years: '1982',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/58/145451.jpg',
    note: '',
  },
  {
    id: 12975,
    tvmazeId: '49750',
    title: 'World War III',
    network: 'NBC',
    startYear: 1982,
    years: '1982',
    genres: ['Drama', 'Thriller', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/268/671371.jpg',
    note: '',
  },
  {
    id: 12976,
    tvmazeId: '22614',
    title: 'Young Sherlock: The Mystery of the Manor House',
    network: 'ITV1',
    startYear: 1982,
    years: '1982',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/83/208842.jpg',
    note: '',
  },
  {
    id: 12977,
    tvmazeId: '9499',
    title: 'A Country Practice',
    network: 'Seven Network',
    startYear: 1981,
    years: '1981–1994',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/83117.jpg',
    note: '',
  },
  {
    id: 12978,
    tvmazeId: '7755',
    title: 'A Fine Romance',
    network: 'ITV1',
    startYear: 1981,
    years: '1981–1984',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/71397.jpg',
    note: '',
  },
  {
    id: 12979,
    tvmazeId: '11498',
    title: 'A Kick Up the Eighties',
    network: 'BBC Two',
    startYear: 1981,
    years: '1981–1984',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/38/96797.jpg',
    note: '',
  },
  {
    id: 12980,
    tvmazeId: '19443',
    title: 'A Town Like Alice',
    network: 'Seven Network',
    startYear: 1981,
    years: '1981',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/563/1409934.jpg',
    note: '',
  },
  {
    id: 12981,
    tvmazeId: '20269',
    title: 'Aloha Paradise',
    network: 'ABC',
    startYear: 1981,
    years: '1981',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/487/1219509.jpg',
    note: '',
  },
  {
    id: 12982,
    tvmazeId: '32118',
    title: 'American Dream',
    network: 'ABC',
    startYear: 1981,
    years: '1981',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/418/1045364.jpg',
    note: '',
  },
  {
    id: 12983,
    tvmazeId: '15685',
    title: 'And Here Comes Bucknuckle',
    network: 'ABC',
    startYear: 1981,
    years: '1981',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12984,
    tvmazeId: '53562',
    title: 'Astro and the Space Mutts',
    network: 'NBC',
    startYear: 1981,
    years: '1981',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/513/1284963.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 541, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 856, "cliffhanger": 286, "ended": 13542}};
