window.pageShows = [
  {
    id: 16177,
    tvmazeId: '71500',
    title: 'Simon in the Land of Chalk Drawings',
    network: 'ITV London',
    startYear: 1970,
    years: '1970',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/478/1196609.jpg',
    note: '',
  },
  {
    id: 16178,
    tvmazeId: '64747',
    title: 'Storefront Lawyers',
    network: 'CBS',
    startYear: 1970,
    years: '1970–1971',
    genres: ['Drama', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 16179,
    tvmazeId: '32830',
    title: 'Tales of Unease',
    network: 'London Weekend Television',
    startYear: 1970,
    years: '1970',
    genres: ['Drama', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/132/330313.jpg',
    note: '',
  },
  {
    id: 16180,
    tvmazeId: '57370',
    title: 'The Adventures of Don Quick',
    network: 'ITV1',
    startYear: 1970,
    years: '1970',
    genres: ['Comedy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/354/886656.jpg',
    note: '',
  },
  {
    id: 16181,
    tvmazeId: '17740',
    title: 'The Bold Ones: The Senator',
    network: 'NBC',
    startYear: 1970,
    years: '1970–1971',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/59/149339.jpg',
    note: '',
  },
  {
    id: 16182,
    tvmazeId: '7094',
    title: 'The Bugaloos',
    network: 'NBC',
    startYear: 1970,
    years: '1970–1971',
    genres: ['Comedy', 'Action', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/66305.jpg',
    note: '',
  },
  {
    id: 16183,
    tvmazeId: '1749',
    title: 'The Goodies',
    network: 'London Weekend Television',
    startYear: 1970,
    years: '1970–1982',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/9/24480.jpg',
    note: '',
  },
  {
    id: 16184,
    tvmazeId: '3845',
    title: 'The Immortal',
    network: 'ABC',
    startYear: 1970,
    years: '1970–1971',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/48301.jpg',
    note: '',
  },
  {
    id: 16185,
    tvmazeId: '64734',
    title: 'The Interns',
    network: 'CBS',
    startYear: 1970,
    years: '1970–1971',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/484/1212396.jpg',
    note: '',
  },
  {
    id: 16186,
    tvmazeId: '10884',
    title: 'The Lovers',
    network: 'ITV1',
    startYear: 1970,
    years: '1970–1971',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/36/91685.jpg',
    note: '',
  },
  {
    id: 16187,
    tvmazeId: '4050',
    title: 'The Mary Tyler Moore Show',
    network: 'CBS',
    startYear: 1970,
    years: '1970–1977',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/49640.jpg',
    note: '',
  },
  {
    id: 16188,
    tvmazeId: '79988',
    title: 'The Misfit',
    network: 'ITV1',
    startYear: 1970,
    years: '1970–1971',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 16189,
    tvmazeId: '37555',
    title: 'The Most Deadly Game',
    network: 'ABC',
    startYear: 1970,
    years: '1970–1971',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/160/400007.jpg',
    note: '',
  },
  {
    id: 16190,
    tvmazeId: '5735',
    title: 'The Odd Couple',
    network: 'ABC',
    startYear: 1970,
    years: '1970–1975',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/57193.jpg',
    note: '',
  },
  {
    id: 16191,
    tvmazeId: '1491',
    title: 'The Partridge Family',
    network: 'ABC',
    startYear: 1970,
    years: '1970–1974',
    genres: ['Comedy', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/628/1572454.jpg',
    note: '',
  },
  {
    id: 16192,
    tvmazeId: '79179',
    title: 'The Psychiatrist',
    network: 'NBC',
    startYear: 1970,
    years: '1970–1971',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 16193,
    tvmazeId: '67325',
    title: 'The Reluctant Dragon & Mr. Toad Show',
    network: 'ABC',
    startYear: 1970,
    years: '1970–1971',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/450/1126130.jpg',
    note: '',
  },
  {
    id: 16194,
    tvmazeId: '33363',
    title: 'The Roads to Freedom',
    network: 'BBC Two',
    startYear: 1970,
    years: '1970',
    genres: ['Drama', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 16195,
    tvmazeId: '35943',
    title: 'The Rovers',
    network: 'Network 10',
    startYear: 1970,
    years: '1970',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/152/380816.jpg',
    note: '',
  },
  {
    id: 16196,
    tvmazeId: '64748',
    title: 'The Silent Force',
    network: 'ABC',
    startYear: 1970,
    years: '1970–1971',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/427/1068511.jpg',
    note: '',
  },
  {
    id: 16197,
    tvmazeId: '13340',
    title: 'The Six Wives of Henry VIII',
    network: 'BBC Two',
    startYear: 1970,
    years: '1970',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/46/115520.jpg',
    note: '',
  },
  {
    id: 16198,
    tvmazeId: '36371',
    title: 'The Spoils of Poynton',
    network: 'BBC Two',
    startYear: 1970,
    years: '1970',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 16199,
    tvmazeId: '52433',
    title: 'The Tim Conway Show',
    network: 'CBS',
    startYear: 1970,
    years: '1970',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/288/722183.jpg',
    note: '',
  },
  {
    id: 16200,
    tvmazeId: '64746',
    title: 'The Young Rebels',
    network: 'ABC',
    startYear: 1970,
    years: '1970–1971',
    genres: ['Adventure', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/427/1068510.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 675, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 398, "cliffhanger": 239, "ended": 15092}};
