window.pageShows = [
  {
    id: 3073,
    tvmazeId: '62333',
    title: 'Жиза',
    network: 'Start',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/414/1035976.jpg',
    note: '',
  },
  {
    id: 3074,
    tvmazeId: '63452',
    title: 'Жизнь по вызову',
    network: 'КИОН',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/419/1047795.jpg',
    note: '',
  },
  {
    id: 3075,
    tvmazeId: '63131',
    title: 'Капельник',
    network: 'Premier',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/421/1053497.jpg',
    note: '',
  },
  {
    id: 3076,
    tvmazeId: '64208',
    title: 'Конец света',
    network: 'КиноПоиск',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/551/1377565.jpg',
    note: '',
  },
  {
    id: 3077,
    tvmazeId: '61519',
    title: 'Нереалити',
    network: 'КИОН',
    startYear: 2022,
    years: '2022–2025',
    genres: ['Drama', 'Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/565/1414403.jpg',
    note: '',
  },
  {
    id: 3078,
    tvmazeId: '58359',
    title: 'Сергий против нечисти',
    network: 'КИОН',
    startYear: 2022,
    years: '2022–',
    genres: ['Comedy', 'Fantasy', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/384/961795.jpg',
    note: '',
  },
  {
    id: 3079,
    tvmazeId: '64611',
    title: 'Сны',
    network: 'Premier',
    startYear: 2022,
    years: '2022',
    genres: ['Science-Fiction', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/426/1065430.jpg',
    note: '',
  },
  {
    id: 3080,
    tvmazeId: '53327',
    title: '1883',
    network: 'Paramount+',
    startYear: 2021,
    years: '2021–2022',
    genres: ['Drama', 'Adventure', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/486/1215657.jpg',
    note: '',
  },
  {
    id: 3081,
    tvmazeId: '52119',
    title: '3 Caminos',
    network: 'Prime Video',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Comedy', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/285/713472.jpg',
    note: '',
  },
  {
    id: 3082,
    tvmazeId: '39652',
    title: '4400',
    network: 'The CW',
    startYear: 2021,
    years: '2021–2022',
    genres: ['Drama', 'Science-Fiction', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/368/921392.jpg',
    note: '',
  },
  {
    id: 3083,
    tvmazeId: '51405',
    title: '50M²',
    network: 'Netflix',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/291/728063.jpg',
    note: '',
  },
  {
    id: 3084,
    tvmazeId: '54322',
    title: '5X Comedia',
    network: 'Prime Video',
    startYear: 2021,
    years: '2021–2024',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/306/765085.jpg',
    note: '',
  },
  {
    id: 3085,
    tvmazeId: '54156',
    title: '6 X confiné.e.s',
    network: 'Canal+',
    startYear: 2021,
    years: '2021',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/300/750266.jpg',
    note: '',
  },
  {
    id: 3086,
    tvmazeId: '55599',
    title: '7 LOVES checkifcancelled',
    network: 'Prime Video',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/321/804395.jpg',
    note: '',
  },
  {
    id: 3087,
    tvmazeId: '54312',
    title: '8 Zeugen',
    network: 'RTL+',
    startYear: 2021,
    years: '2021',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/301/753270.jpg',
    note: '',
  },
  {
    id: 3088,
    tvmazeId: '68015',
    title: 'A casa tutti bene',
    network: 'Sky Atlantic',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/464/1161845.jpg',
    note: '',
  },
  {
    id: 3089,
    tvmazeId: '59615',
    title: 'A Good Cop',
    network: 'NTD Television',
    startYear: 2021,
    years: '2021–2022',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/385/963673.jpg',
    note: '',
  },
  {
    id: 3090,
    tvmazeId: '55840',
    title: 'A Luv Tale',
    network: 'BET+',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/389/974019.jpg',
    note: '',
  },
  {
    id: 3091,
    tvmazeId: '56069',
    title: 'A Tale Dark & Grimm',
    network: 'Netflix',
    startYear: 2021,
    years: '2021',
    genres: ['Comedy', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/364/910217.jpg',
    note: '',
  },
  {
    id: 3092,
    tvmazeId: '54074',
    title: 'A Very British Scandal',
    network: 'BBC iPlayer',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/385/964670.jpg',
    note: '',
  },
  {
    id: 3093,
    tvmazeId: '55350',
    title: 'Abbott Elementary',
    network: 'ABC',
    startYear: 2021,
    years: '2021–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/586/1467109.jpg',
    note: '',
  },
  {
    id: 3094,
    tvmazeId: '53615',
    title: 'Abla Fahita: Drama Queen',
    network: 'Netflix',
    startYear: 2021,
    years: '2021',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/297/742560.jpg',
    note: '',
  },
  {
    id: 3095,
    tvmazeId: '62535',
    title: 'Action Royale',
    network: 'Snapchat',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/413/1032570.jpg',
    note: '',
  },
  {
    id: 3096,
    tvmazeId: '53330',
    title: 'Ada Twist, Scientist',
    network: 'Netflix',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/458/1145896.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 129, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
