window.pageShows = [
  {
    id: 11905,
    tvmazeId: '8805',
    title: 'Stay Lucky',
    network: 'ITV1',
    startYear: 1989,
    years: '1989–1993',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/78135.jpg',
    note: '',
  },
  {
    id: 11906,
    tvmazeId: '77957',
    title: 'Streetwise',
    network: 'ITV1',
    startYear: 1989,
    years: '1989–1992',
    genres: ['Drama', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/524/1311946.jpg',
    note: '',
  },
  {
    id: 11907,
    tvmazeId: '58326',
    title: 'Studio 5-B',
    network: 'ABC',
    startYear: 1989,
    years: '1989',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11908,
    tvmazeId: '32872',
    title: 'Summer\'s Lease',
    network: 'BBC Two',
    startYear: 1989,
    years: '1989',
    genres: ['Drama', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/132/331103.jpg',
    note: '',
  },
  {
    id: 11909,
    tvmazeId: '8439',
    title: 'Surgical Spirit',
    network: 'ITV1',
    startYear: 1989,
    years: '1989–1995',
    genres: ['Comedy', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/30/75356.jpg',
    note: '',
  },
  {
    id: 11910,
    tvmazeId: '51026',
    title: 'Take Me Home',
    network: 'BBC One',
    startYear: 1989,
    years: '1989',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/276/692413.jpg',
    note: '',
  },
  {
    id: 11911,
    tvmazeId: '453',
    title: 'Tales from the Crypt',
    network: 'HBO',
    startYear: 1989,
    years: '1989–1996',
    genres: ['Comedy', 'Fantasy', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/3/9142.jpg',
    note: '',
  },
  {
    id: 11912,
    tvmazeId: '51027',
    title: 'Tanamera – Lion of Singapore',
    network: 'Network 10',
    startYear: 1989,
    years: '1989',
    genres: ['Drama', 'Romance', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/276/692419.jpg',
    note: '',
  },
  {
    id: 11913,
    tvmazeId: '50653',
    title: 'Teen Angel',
    network: 'Disney Channel',
    startYear: 1989,
    years: '1989',
    genres: ['Drama', 'Family', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/384/962299.jpg',
    note: '',
  },
  {
    id: 11914,
    tvmazeId: '81028',
    title: 'Teen Angel Returns',
    network: 'Disney Channel',
    startYear: 1989,
    years: '1989',
    genres: ['Drama', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11915,
    tvmazeId: '28557',
    title: 'The Adventures of McGee and Me',
    network: 'ABC',
    startYear: 1989,
    years: '1989–1992',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/113/284186.jpg',
    note: '',
  },
  {
    id: 11916,
    tvmazeId: '65225',
    title: 'The All New Mickey Mouse Club',
    network: 'Disney Channel',
    startYear: 1989,
    years: '1989–1993',
    genres: ['Comedy', 'Children', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/556/1391215.jpg',
    note: '',
  },
  {
    id: 11917,
    tvmazeId: '40523',
    title: 'The California Raisin Show',
    network: 'CBS',
    startYear: 1989,
    years: '1989',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/181/453146.jpg',
    note: '',
  },
  {
    id: 11918,
    tvmazeId: '22200',
    title: 'The Dark Angel',
    network: 'BBC Two',
    startYear: 1989,
    years: '1989',
    genres: ['Drama', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/81/203178.jpg',
    note: '',
  },
  {
    id: 11919,
    tvmazeId: '86064',
    title: 'The Edge',
    network: 'HBO',
    startYear: 1989,
    years: '1989',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11920,
    tvmazeId: '50960',
    title: 'The Endless Game',
    network: 'ITV1',
    startYear: 1989,
    years: '1989',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/397/994013.jpg',
    note: '',
  },
  {
    id: 11921,
    tvmazeId: '42473',
    title: 'The Famous Teddy Z',
    network: 'CBS',
    startYear: 1989,
    years: '1989–1990',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11922,
    tvmazeId: '41316',
    title: 'The Ginger Tree',
    network: 'BBC One',
    startYear: 1989,
    years: '1989',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/187/468401.jpg',
    note: '',
  },
  {
    id: 11923,
    tvmazeId: '65235',
    title: 'The Groovy Fellers',
    network: 'Channel 4',
    startYear: 1989,
    years: '1989',
    genres: ['Comedy', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11924,
    tvmazeId: '9711',
    title: 'The Karate Kid',
    network: 'NBC',
    startYear: 1989,
    years: '1989',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/84294.jpg',
    note: '',
  },
  {
    id: 11925,
    tvmazeId: '78856',
    title: 'The Labours of Erica',
    network: 'ITV1',
    startYear: 1989,
    years: '1989–1990',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/530/1326693.jpg',
    note: '',
  },
  {
    id: 11926,
    tvmazeId: '26813',
    title: 'The Legend of Zelda',
    network: 'NBC',
    startYear: 1989,
    years: '1989',
    genres: ['Adventure', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/105/263896.jpg',
    note: '',
  },
  {
    id: 11927,
    tvmazeId: '51530',
    title: 'The Manageress',
    network: 'Channel 4',
    startYear: 1989,
    years: '1989–1990',
    genres: ['Drama', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/279/699986.jpg',
    note: '',
  },
  {
    id: 11928,
    tvmazeId: '6320',
    title: 'The New Lassie',
    network: 'Syndication',
    startYear: 1989,
    years: '1989–1992',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/24/60634.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 497, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 334, "cliffhanger": 235, "ended": 13701}};
