window.pageShows = [
  {
    id: 2233,
    tvmazeId: '64152',
    title: 'Master Giovanni N',
    network: 'YouTube',
    startYear: 2021,
    years: '2021–',
    genres: ['Comedy', 'Children', 'Music'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/450/1125272.jpg',
    note: '',
  },
  {
    id: 2234,
    tvmazeId: '43428',
    title: 'Masters of the Universe: Revelation',
    network: 'Netflix',
    startYear: 2021,
    years: '2021',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/365/914541.jpg',
    note: '',
  },
  {
    id: 2235,
    tvmazeId: '45840',
    title: 'Mayor of Kingstown',
    network: 'Paramount+',
    startYear: 2021,
    years: '2021–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/594/1486611.jpg',
    note: '',
  },
  {
    id: 2236,
    tvmazeId: '63792',
    title: 'MC Grammar: Wonder Raps',
    network: 'Now',
    startYear: 2021,
    years: '2021–2022',
    genres: ['Children', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/420/1050546.jpg',
    note: '',
  },
  {
    id: 2237,
    tvmazeId: '56182',
    title: 'Meet Spidey and His Amazing Friends',
    network: 'DisneyNOW',
    startYear: 2021,
    years: '2021–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/334/837063.jpg',
    note: '',
  },
  {
    id: 2238,
    tvmazeId: '55961',
    title: 'Mickey Mouse Funhouse',
    network: 'Disney Junior',
    startYear: 2021,
    years: '2021–2025',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/330/825650.jpg',
    note: '',
  },
  {
    id: 2239,
    tvmazeId: '70700',
    title: 'Mickey Mouse Specials',
    network: 'Disney+',
    startYear: 2021,
    years: '2021–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/473/1183492.jpg',
    note: '',
  },
  {
    id: 2240,
    tvmazeId: '55502',
    title: 'Middlemost Post',
    network: 'Nickelodeon',
    startYear: 2021,
    years: '2021–2022',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/336/841438.jpg',
    note: '',
  },
  {
    id: 2241,
    tvmazeId: '42840',
    title: 'Midnight Mass',
    network: 'Netflix',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Horror', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/354/885283.jpg',
    note: '',
  },
  {
    id: 2242,
    tvmazeId: '64728',
    title: 'Mikki vs the World checkifcancelled',
    network: 'ABC iview',
    startYear: 2021,
    years: '2021–',
    genres: ['Children'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/427/1068213.jpg',
    note: '',
  },
  {
    id: 2243,
    tvmazeId: '53254',
    title: 'Millennials checkifcancelled',
    network: 'ALLBLK',
    startYear: 2021,
    years: '2021–',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/297/744565.jpg',
    note: '',
  },
  {
    id: 2244,
    tvmazeId: '61285',
    title: 'Milo checkifcancelled',
    network: '5',
    startYear: 2021,
    years: '2021–',
    genres: ['Children'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/416/1041510.jpg',
    note: '',
  },
  {
    id: 2245,
    tvmazeId: '78174',
    title: 'Minnie\'s Bow-Toon\'s: Party Palace Pals',
    network: 'YouTube',
    startYear: 2021,
    years: '2021–2022',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/525/1314885.jpg',
    note: '',
  },
  {
    id: 2246,
    tvmazeId: '54203',
    title: 'Mira Mira',
    network: 'Facebook Watch',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/619/1548961.jpg',
    note: '',
  },
  {
    id: 2247,
    tvmazeId: '85402',
    title: 'Monster Lab',
    network: 'YouTube',
    startYear: 2021,
    years: '2021',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/574/1436405.jpg',
    note: '',
  },
  {
    id: 2248,
    tvmazeId: '41698',
    title: 'Monsters at Work',
    network: 'Disney Channel',
    startYear: 2021,
    years: '2021–',
    genres: ['Comedy', 'Fantasy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Disney+ cancelled after two seasons; Tylor Tuskmon\'s career arc and ongoing comedy arcs were unfinished.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/507/1268353.jpg',
    note: '',
  },
  {
    id: 2249,
    tvmazeId: '56931',
    title: 'Moonshine',
    network: 'CBC Gem',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/445/1113497.jpg',
    note: '',
  },
  {
    id: 2250,
    tvmazeId: '43729',
    title: 'Mr. Corman',
    network: 'Apple TV',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/339/849022.jpg',
    note: '',
  },
  {
    id: 2251,
    tvmazeId: '48194',
    title: 'Mr. Mayor',
    network: 'NBC',
    startYear: 2021,
    years: '2021–2022',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/402/1007454.jpg',
    note: '',
  },
  {
    id: 2252,
    tvmazeId: '65399',
    title: 'Murder Drones',
    network: 'YouTube',
    startYear: 2021,
    years: '2021–2024',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/432/1080092.jpg',
    note: '',
  },
  {
    id: 2253,
    tvmazeId: '60272',
    title: 'Mush Mush and the Mushables',
    network: 'Ketnet',
    startYear: 2021,
    years: '2021–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/394/985379.jpg',
    note: '',
  },
  {
    id: 2254,
    tvmazeId: '60854',
    title: 'My Little Pony: Make Your Mark',
    network: 'Netflix',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Adventure', 'Children', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/410/1026527.jpg',
    note: '',
  },
  {
    id: 2255,
    tvmazeId: '53629',
    title: 'NCIS: Hawaiʻi',
    network: 'CBS',
    startYear: 2021,
    years: '2021–2024',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/591/1479860.jpg',
    note: '',
  },
  {
    id: 2256,
    tvmazeId: '45188',
    title: 'New Gold Mountain',
    network: 'SBS',
    startYear: 2021,
    years: '2021',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/396/990091.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 94, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 856, "cliffhanger": 286, "ended": 13542}};
