window.pageShows = [
  {
    id: 12121,
    tvmazeId: '62422',
    title: 'Magic Adventures of Mumfie',
    network: 'ITV1',
    startYear: 1998,
    years: '1998',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12122,
    tvmazeId: '10314',
    title: 'Maisie Raine',
    network: 'BBC One',
    startYear: 1998,
    years: '1998–1999',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/34/87395.jpg',
    note: '',
  },
  {
    id: 12123,
    tvmazeId: '65972',
    title: 'Malibu, CA',
    network: 'Syndication',
    startYear: 1998,
    years: '1998–2000',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12124,
    tvmazeId: '50822',
    title: 'Mama Flora\'s Family',
    network: 'CBS',
    startYear: 1998,
    years: '1998',
    genres: ['Drama', 'Family', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/275/689568.jpg',
    note: '',
  },
  {
    id: 12125,
    tvmazeId: '2044',
    title: 'Martial Law',
    network: 'CBS',
    startYear: 1998,
    years: '1998–2000',
    genres: ['Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/28487.jpg',
    note: '',
  },
  {
    id: 12126,
    tvmazeId: '14138',
    title: 'Maximum Bob',
    network: 'ABC',
    startYear: 1998,
    years: '1998',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/48/120746.jpg',
    note: '',
  },
  {
    id: 12127,
    tvmazeId: '39454',
    title: 'Mercy Point',
    network: 'UPN',
    startYear: 1998,
    years: '1998–1999',
    genres: ['Drama', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/173/433731.jpg',
    note: '',
  },
  {
    id: 12128,
    tvmazeId: '35499',
    title: 'Merlin',
    network: 'NBC',
    startYear: 1998,
    years: '1998',
    genres: ['Drama', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: '1998 NBC miniseries starring Sam Neill; told a complete story of Merlin\'s life and concluded properly.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/149/374688.jpg',
    note: '',
  },
  {
    id: 12129,
    tvmazeId: '75390',
    title: 'Microscopic Milton',
    network: 'BBC One',
    startYear: 1998,
    years: '1998',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12130,
    tvmazeId: '36205',
    title: 'Microsoap',
    network: 'BBC One',
    startYear: 1998,
    years: '1998–2000',
    genres: ['Drama', 'Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/153/382746.jpg',
    note: '',
  },
  {
    id: 12131,
    tvmazeId: '328',
    title: 'Midsomer Murders',
    network: 'Acorn TV',
    startYear: 1998,
    years: '1998–',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/603/1508988.jpg',
    note: '',
  },
  {
    id: 12132,
    tvmazeId: '31907',
    title: 'Minty',
    network: 'ABC',
    startYear: 1998,
    years: '1998',
    genres: ['Drama', 'Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/165/413095.jpg',
    note: '',
  },
  {
    id: 12133,
    tvmazeId: '27628',
    title: 'Moby Dick',
    network: 'USA Network',
    startYear: 1998,
    years: '1998',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/108/272237.jpg',
    note: '',
  },
  {
    id: 12134,
    tvmazeId: '40865',
    title: 'Monkey Magic',
    network: 'UPN',
    startYear: 1998,
    years: '1998',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/378/946863.jpg',
    note: '',
  },
  {
    id: 12135,
    tvmazeId: '17975',
    title: 'MonsterVision',
    network: 'TNT',
    startYear: 1998,
    years: '1998',
    genres: ['Horror', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/60/152252.jpg',
    note: '',
  },
  {
    id: 12136,
    tvmazeId: '65970',
    title: 'More Tears',
    network: 'CBC',
    startYear: 1998,
    years: '1998',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12137,
    tvmazeId: '1658',
    title: 'Mortal Kombat: Conquest',
    network: 'Syndication',
    startYear: 1998,
    years: '1998–1999',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/302/755273.jpg',
    note: '',
  },
  {
    id: 12138,
    tvmazeId: '51165',
    title: 'Mortimer\'s Law',
    network: 'BBC One',
    startYear: 1998,
    years: '1998',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12139,
    tvmazeId: '51166',
    title: 'Mosley',
    network: 'Channel 4',
    startYear: 1998,
    years: '1998',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/277/694232.jpg',
    note: '',
  },
  {
    id: 12140,
    tvmazeId: '15709',
    title: 'Mowgli: The New Adventures of the Jungle Book',
    network: 'FOX',
    startYear: 1998,
    years: '1998',
    genres: ['Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/53/132928.jpg',
    note: '',
  },
  {
    id: 12141,
    tvmazeId: '26378',
    title: 'Mystic Knights of Tir Na Nog',
    network: 'FOX',
    startYear: 1998,
    years: '1998–1999',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/103/259410.jpg',
    note: '',
  },
  {
    id: 12142,
    tvmazeId: '18463',
    title: 'Mythic Warriors: Guardians of the Legend',
    network: 'CBS',
    startYear: 1998,
    years: '1998–2000',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/184323.jpg',
    note: '',
  },
  {
    id: 12143,
    tvmazeId: '16814',
    title: 'Ned\'s Newt',
    network: 'Cartoon Network',
    startYear: 1998,
    years: '1998–1999',
    genres: ['Comedy', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/56/140424.jpg',
    note: '',
  },
  {
    id: 12144,
    tvmazeId: '46647',
    title: 'Noddy',
    network: 'TVO',
    startYear: 1998,
    years: '1998–2000',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/245/613715.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 506, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
