window.pageShows = [
  {
    id: 11501,
    tvmazeId: '58289',
    title: 'Chambers',
    network: 'BBC One',
    startYear: 2000,
    years: '2000–2001',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: '',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/365/913688.jpg',
    note: '',
  },
  {
    id: 11502,
    tvmazeId: '58411',
    title: 'City of Angels',
    network: 'CBS',
    startYear: 2000,
    years: '2000',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11503,
    tvmazeId: '981',
    title: 'Cleopatra 2525',
    network: 'Syndication',
    startYear: 2000,
    years: '2000–2001',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16510.jpg',
    note: '',
  },
  {
    id: 11504,
    tvmazeId: '42151',
    title: 'Clifford the Big Red Dog',
    network: 'PBS',
    startYear: 2000,
    years: '2000–2003',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/196/491154.jpg',
    note: '',
  },
  {
    id: 11505,
    tvmazeId: '11129',
    title: 'Clocking Off',
    network: 'BBC One',
    startYear: 2000,
    years: '2000–2003',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/124/310574.jpg',
    note: '',
  },
  {
    id: 11506,
    tvmazeId: '42223',
    title: 'Close and True',
    network: 'ITV1',
    startYear: 2000,
    years: '2000',
    genres: ['Drama', 'Comedy', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/197/493788.jpg',
    note: '',
  },
  {
    id: 11507,
    tvmazeId: '1644',
    title: 'Code Name: Eternity',
    network: 'Syndication',
    startYear: 2000,
    years: '2000',
    genres: [],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/9/22882.jpg',
    note: '',
  },
  {
    id: 11508,
    tvmazeId: '59386',
    title: 'Corduroy',
    network: 'TVO',
    startYear: 2000,
    years: '2000',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/381/954621.jpg',
    note: '',
  },
  {
    id: 11509,
    tvmazeId: '1085',
    title: 'Coupling',
    network: 'BBC Three',
    startYear: 2000,
    years: '2000–2004',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17197.jpg',
    note: '',
  },
  {
    id: 11510,
    tvmazeId: '32127',
    title: 'Cover Me: Based on the True Life of an FBI Family',
    network: 'USA Network',
    startYear: 2000,
    years: '2000–2001',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/128/321046.jpg',
    note: '',
  },
  {
    id: 11511,
    tvmazeId: '109',
    title: 'CSI: Crime Scene Investigation',
    network: 'CBS',
    startYear: 2000,
    years: '2000–2015',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/501/1254955.jpg',
    note: '',
  },
  {
    id: 11512,
    tvmazeId: '551',
    title: 'Curb Your Enthusiasm',
    network: 'HBO',
    startYear: 2000,
    years: '2000–2024',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/500/1250735.jpg',
    note: '',
  },
  {
    id: 11513,
    tvmazeId: '17296',
    title: 'D.C.',
    network: 'The WB',
    startYear: 2000,
    years: '2000',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/355/887752.jpg',
    note: '',
  },
  {
    id: 11514,
    tvmazeId: '70818',
    title: 'D\'Myna Leagues',
    network: 'CTV',
    startYear: 2000,
    years: '2000–2004',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/474/1185446.jpg',
    note: '',
  },
  {
    id: 11515,
    tvmazeId: '25973',
    title: 'Daddio',
    network: 'NBC',
    startYear: 2000,
    years: '2000',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/101/254395.jpg',
    note: '',
  },
  {
    id: 11516,
    tvmazeId: '23824',
    title: 'DAG',
    network: 'NBC',
    startYear: 2000,
    years: '2000–2001',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/590/1476661.jpg',
    note: '',
  },
  {
    id: 11517,
    tvmazeId: '58594',
    title: 'Daring & Grace: Teen Detectives',
    network: 'CBC',
    startYear: 2000,
    years: '2000–2001',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/369/924920.jpg',
    note: '',
  },
  {
    id: 11518,
    tvmazeId: '554',
    title: 'Dark Angel',
    network: 'FOX',
    startYear: 2000,
    years: '2000–2002',
    genres: ['Action', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Major cliffhanger — the show ends mid-story with the protagonist in serious jeopardy and the central conflict completely unresolved. The story was never concluded.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/4/11610.jpg',
    note: '',
  },
  {
    id: 11519,
    tvmazeId: '37691',
    title: 'Dark Knight',
    network: '5',
    startYear: 2000,
    years: '2000–2002',
    genres: ['Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/160/401859.jpg',
    note: '',
  },
  {
    id: 11520,
    tvmazeId: '5600',
    title: 'Deadline',
    network: 'NBC',
    startYear: 2000,
    years: '2000–2001',
    genres: ['Drama', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/190/475319.jpg',
    note: '',
  },
  {
    id: 11521,
    tvmazeId: '91225',
    title: 'Deceit',
    network: 'BBC One',
    startYear: 2000,
    years: '2000',
    genres: ['Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11522,
    tvmazeId: '80088',
    title: 'Dirty Work',
    network: 'BBC One',
    startYear: 2000,
    years: '2000',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11523,
    tvmazeId: '3399',
    title: 'Doctors',
    network: 'BBC One',
    startYear: 2000,
    years: '2000–2024',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/105/264564.jpg',
    note: '',
  },
  {
    id: 11524,
    tvmazeId: '6489',
    title: 'Dora the Explorer',
    network: 'Nickelodeon',
    startYear: 2000,
    years: '2000–2019',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/448/1121183.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 480, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
