window.pageShows = [
  {
    id: 2521,
    tvmazeId: '64098',
    title: 'Ivy + Bean',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy', 'Children', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/422/1055151.jpg',
    note: '',
  },
  {
    id: 2522,
    tvmazeId: '71297',
    title: 'Jacqueline Wilson\'s Little Darlings',
    network: 'Now',
    startYear: 2022,
    years: '2022',
    genres: ['Children', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/519/1297925.jpg',
    note: '',
  },
  {
    id: 2523,
    tvmazeId: '53175',
    title: 'Jerusalem',
    network: 'HOT3',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/510/1277032.jpg',
    note: '',
  },
  {
    id: 2524,
    tvmazeId: '59005',
    title: 'Jim Henson\'s Fraggle Rock Back to the Rock',
    network: 'Apple TV',
    startYear: 2022,
    years: '2022–',
    genres: ['Children', 'Family'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Apple TV+ cancelled after one season with the Gorgs\' storyline and world-building unfinished.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/509/1274226.jpg',
    note: '',
  },
  {
    id: 2525,
    tvmazeId: '49925',
    title: 'Joe vs Carole',
    network: 'Peacock',
    startYear: 2022,
    years: '2022',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/397/994403.jpg',
    note: '',
  },
  {
    id: 2526,
    tvmazeId: '60048',
    title: 'Juanpis González - La serie',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/391/978457.jpg',
    note: '',
  },
  {
    id: 2527,
    tvmazeId: '65429',
    title: 'Julestorm',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/434/1086510.jpg',
    note: '',
  },
  {
    id: 2528,
    tvmazeId: '46702',
    title: 'Julia',
    network: 'HBO Max',
    startYear: 2022,
    years: '2022–2023',
    genres: ['Drama', 'Comedy', 'Food'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/484/1211032.jpg',
    note: '',
  },
  {
    id: 2529,
    tvmazeId: '49962',
    title: 'Jungle',
    network: 'Prime Video',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Music'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/424/1060211.jpg',
    note: '',
  },
  {
    id: 2530,
    tvmazeId: '64209',
    title: 'Junior\'s',
    network: 'YouTube',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/423/1057954.jpg',
    note: '',
  },
  {
    id: 2531,
    tvmazeId: '63246',
    title: 'Justice Served',
    network: 'Netflix',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/416/1042390.jpg',
    note: '',
  },
  {
    id: 2532,
    tvmazeId: '60169',
    title: 'Juvenile Justice',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Crime', 'Legal'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/393/983462.jpg',
    note: '',
  },
  {
    id: 2533,
    tvmazeId: '64081',
    title: 'Kabe-Koji-Nekoyashiki-kun Desires to be Recognized',
    network: 'ABC',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/421/1054977.jpg',
    note: '',
  },
  {
    id: 2534,
    tvmazeId: '64909',
    title: 'Kamen Rider: Black Sun',
    network: 'Prime Video',
    startYear: 2022,
    years: '2022',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/428/1071917.jpg',
    note: '',
  },
  {
    id: 2535,
    tvmazeId: '48420',
    title: 'Karen Pirie',
    network: 'ITVX',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/579/1447907.jpg',
    note: '',
  },
  {
    id: 2536,
    tvmazeId: '62528',
    title: 'Kaçış',
    network: 'Disney+',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/413/1032605.jpg',
    note: '',
  },
  {
    id: 2537,
    tvmazeId: '53462',
    title: 'Keep Breathing',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Adventure', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/414/1036538.jpg',
    note: '',
  },
  {
    id: 2538,
    tvmazeId: '59063',
    title: 'Kei×Yaku: Abunai Aibou',
    network: 'YTV',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/376/942291.jpg',
    note: '',
  },
  {
    id: 2539,
    tvmazeId: '64999',
    title: 'Khakee: The Bihar Chapter',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/429/1073361.jpg',
    note: '',
  },
  {
    id: 2540,
    tvmazeId: '62938',
    title: 'Kid Sister',
    network: 'TVNZ+',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/455/1137987.jpg',
    note: '',
  },
  {
    id: 2541,
    tvmazeId: '49440',
    title: 'Killing It',
    network: 'Peacock',
    startYear: 2022,
    years: '2022–',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Peacock cancelled after two seasons; Craig\'s ambitions and the family dynamics were left mid-arc.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/404/1012074.jpg',
    note: '',
  },
  {
    id: 2542,
    tvmazeId: '57990',
    title: 'Kindred',
    network: 'Hulu',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Fantasy', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/432/1081699.jpg',
    note: '',
  },
  {
    id: 2543,
    tvmazeId: '62038',
    title: 'King of Stonks',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Comedy', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/413/1034564.jpg',
    note: '',
  },
  {
    id: 2544,
    tvmazeId: '62152',
    title: 'Kingdom Business',
    network: 'BET+',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Music'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/502/1256073.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 106, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 295, "ended": 12349}};
