window.pageShows = [
  {
    id: 9433,
    tvmazeId: '23676',
    title: 'Sea Wolf',
    network: 'ZDF',
    startYear: 2009,
    years: '2009',
    genres: ['Drama', 'Adventure', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/465/1164672.jpg',
    note: '',
  },
  {
    id: 9434,
    tvmazeId: '7928',
    title: 'Secret Girlfriend',
    network: 'Comedy Central',
    startYear: 2009,
    years: '2009',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/326/816696.jpg',
    note: '',
  },
  {
    id: 9435,
    tvmazeId: '26585',
    title: 'SGU Stargate Universe Kino',
    network: 'Syfy.com',
    startYear: 2009,
    years: '2009–2011',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/104/261679.jpg',
    note: '',
  },
  {
    id: 9436,
    tvmazeId: '33674',
    title: 'Sherri',
    network: 'Lifetime',
    startYear: 2009,
    years: '2009',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/137/343181.jpg',
    note: '',
  },
  {
    id: 9437,
    tvmazeId: '5937',
    title: 'Sit Down, Shut Up',
    network: 'FOX',
    startYear: 2009,
    years: '2009',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/485/1214064.jpg',
    note: '',
  },
  {
    id: 9438,
    tvmazeId: '69789',
    title: 'Slasher School',
    network: 'G4',
    startYear: 2009,
    years: '2009',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/468/1170080.jpg',
    note: '',
  },
  {
    id: 9439,
    tvmazeId: '35359',
    title: 'Small Island',
    network: 'BBC One',
    startYear: 2009,
    years: '2009',
    genres: ['Drama', 'Romance', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/149/372505.jpg',
    note: '',
  },
  {
    id: 9440,
    tvmazeId: '75038',
    title: 'Snake \'n\' Bacon',
    network: 'Adult Swim',
    startYear: 2009,
    years: '2009',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/506/1266333.jpg',
    note: '',
  },
  {
    id: 9441,
    tvmazeId: '9933',
    title: 'Snake Tales',
    network: 'Nine Network',
    startYear: 2009,
    years: '2009',
    genres: ['Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/34/85341.jpg',
    note: '',
  },
  {
    id: 9442,
    tvmazeId: '2206',
    title: 'Sonny with a Chance',
    network: 'Disney Channel',
    startYear: 2009,
    years: '2009–2011',
    genres: ['Comedy', 'Family', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/316/792445.jpg',
    note: '',
  },
  {
    id: 9443,
    tvmazeId: '674',
    title: 'Southland',
    network: 'TNT',
    startYear: 2009,
    years: '2009–2013',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/5/14795.jpg',
    note: '',
  },
  {
    id: 9444,
    tvmazeId: '49564',
    title: 'Spartacus: Blood and Sand - The Motion Comic',
    network: 'STARZ',
    startYear: 2009,
    years: '2009–2010',
    genres: ['Drama', 'Action', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/384/961561.jpg',
    note: '',
  },
  {
    id: 9445,
    tvmazeId: '12439',
    title: 'Special Agent Oso',
    network: 'Disney Channel',
    startYear: 2009,
    years: '2009–2012',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/512/1281784.jpg',
    note: '',
  },
  {
    id: 9446,
    tvmazeId: '37500',
    title: 'Spider-Woman, Agent of S.W.O.R.D.',
    network: 'iTunes',
    startYear: 2009,
    years: '2009',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/159/399833.jpg',
    note: '',
  },
  {
    id: 9447,
    tvmazeId: '207',
    title: 'Stargate Universe',
    network: 'Syfy',
    startYear: 2009,
    years: '2009–2011',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Syfy cancelled after two seasons on a massive cliffhanger; the Destiny crew\'s mission in deep space was left unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/81/204195.jpg',
    note: '',
  },
  {
    id: 9448,
    tvmazeId: '3673',
    title: 'Starhyke',
    network: 'Music & Memories',
    startYear: 2009,
    years: '2009',
    genres: ['Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/47363.jpg',
    note: '',
  },
  {
    id: 9449,
    tvmazeId: '2589',
    title: 'Stewart Lee\'s Comedy Vehicle',
    network: 'BBC Two',
    startYear: 2009,
    years: '2009–2016',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/181/454802.jpg',
    note: '',
  },
  {
    id: 9450,
    tvmazeId: '18460',
    title: 'Stoked',
    network: 'Cartoon Network',
    startYear: 2009,
    years: '2009–2013',
    genres: ['Drama', 'Comedy', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/62/157382.jpg',
    note: '',
  },
  {
    id: 9451,
    tvmazeId: '9932',
    title: 'Stormworld',
    network: 'CTV Sci-Fi Channel',
    startYear: 2009,
    years: '2009',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/34/85334.jpg',
    note: '',
  },
  {
    id: 9452,
    tvmazeId: '7075',
    title: 'Superman: Red Son',
    network: 'iTunes',
    startYear: 2009,
    years: '2009',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/66205.jpg',
    note: '',
  },
  {
    id: 9453,
    tvmazeId: '4465',
    title: 'Surviving Suburbia',
    network: 'ABC',
    startYear: 2009,
    years: '2009',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/51887.jpg',
    note: '',
  },
  {
    id: 9454,
    tvmazeId: '2991',
    title: 'Taking the Flak',
    network: 'BBC Two',
    startYear: 2009,
    years: '2009',
    genres: ['Drama', 'Comedy', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/16/40837.jpg',
    note: '',
  },
  {
    id: 9455,
    tvmazeId: '7151',
    title: 'Tangle',
    network: 'Showcase',
    startYear: 2009,
    years: '2009–2012',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/66924.jpg',
    note: '',
  },
  {
    id: 9456,
    tvmazeId: '22399',
    title: 'Team Epic',
    network: 'Makeful',
    startYear: 2009,
    years: '2009',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/82/205798.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 394, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
