window.pageShows = [
  {
    id: 17041,
    tvmazeId: '28388',
    title: 'The Adventures of Sir Lancelot',
    network: 'ITV1',
    startYear: 1956,
    years: '1956–1957',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/112/282346.jpg',
    note: '',
  },
  {
    id: 17042,
    tvmazeId: '28387',
    title: 'The Buccaneers',
    network: 'ITV1',
    startYear: 1956,
    years: '1956–1957',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/112/282333.jpg',
    note: '',
  },
  {
    id: 17043,
    tvmazeId: '35891',
    title: 'The Count of Monte Cristo',
    network: 'ITV1',
    startYear: 1956,
    years: '1956',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/151/379997.jpg',
    note: '',
  },
  {
    id: 17044,
    tvmazeId: '19203',
    title: 'The Edge of Night',
    network: 'CBS',
    startYear: 1956,
    years: '1956–1984',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/356/892000.jpg',
    note: '',
  },
  {
    id: 17045,
    tvmazeId: '59169',
    title: 'The Errol Flynn Theatre',
    network: 'ITV1',
    startYear: 1956,
    years: '1956',
    genres: ['Drama', 'Comedy', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/378/946534.jpg',
    note: '',
  },
  {
    id: 17046,
    tvmazeId: '30232',
    title: 'The Gale Storm Show',
    network: 'CBS',
    startYear: 1956,
    years: '1956–1959',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17047,
    tvmazeId: '18013',
    title: 'The Gumby Show',
    network: 'NBC',
    startYear: 1956,
    years: '1956–1968',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/414/1036576.jpg',
    note: '',
  },
  {
    id: 17048,
    tvmazeId: '45826',
    title: 'The Hardy Boys',
    network: 'ABC',
    startYear: 1956,
    years: '1956–1957',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/236/590042.jpg',
    note: '',
  },
  {
    id: 17049,
    tvmazeId: '39495',
    title: 'The Joseph Cotten Show',
    network: 'CBS',
    startYear: 1956,
    years: '1956–1957',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/377/942564.jpg',
    note: '',
  },
  {
    id: 17050,
    tvmazeId: '7633',
    title: 'Torchy the Battery Boy',
    network: 'ITV1',
    startYear: 1956,
    years: '1956–1960',
    genres: ['Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/70664.jpg',
    note: '',
  },
  {
    id: 17051,
    tvmazeId: '55769',
    title: 'West Point',
    network: 'CBS',
    startYear: 1956,
    years: '1956–1957',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/325/814716.jpg',
    note: '',
  },
  {
    id: 17052,
    tvmazeId: '75164',
    title: 'Wire Service',
    network: 'ABC',
    startYear: 1956,
    years: '1956–1957',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/507/1268392.jpg',
    note: '',
  },
  {
    id: 17053,
    tvmazeId: '3738',
    title: 'Alfred Hitchcock Presents',
    network: 'CBS',
    startYear: 1955,
    years: '1955–1962',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/47746.jpg',
    note: '',
  },
  {
    id: 17054,
    tvmazeId: '75930',
    title: 'Appointment with Adventure',
    network: 'CBS',
    startYear: 1955,
    years: '1955–1956',
    genres: ['Drama', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17055,
    tvmazeId: '75961',
    title: 'Brave Eagle',
    network: 'CBS',
    startYear: 1955,
    years: '1955–1956',
    genres: ['Drama', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/512/1282121.jpg',
    note: '',
  },
  {
    id: 17056,
    tvmazeId: '56745',
    title: 'Captain Gallant of the Foreign Legion',
    network: 'NBC',
    startYear: 1955,
    years: '1955–1957',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/346/867406.jpg',
    note: '',
  },
  {
    id: 17057,
    tvmazeId: '7792',
    title: 'Captain Z-Ro',
    network: 'Syndication',
    startYear: 1955,
    years: '1955–1956',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/71660.jpg',
    note: '',
  },
  {
    id: 17058,
    tvmazeId: '58261',
    title: 'Casablanca',
    network: 'ABC',
    startYear: 1955,
    years: '1955–1956',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/396/990649.jpg',
    note: '',
  },
  {
    id: 17059,
    tvmazeId: '4040',
    title: 'Cheyenne',
    network: 'ABC',
    startYear: 1955,
    years: '1955–1962',
    genres: ['Action', 'Adventure', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/599/1499214.jpg',
    note: '',
  },
  {
    id: 17060,
    tvmazeId: '21868',
    title: 'Commando Cody: Sky Marshal of the Universe',
    network: 'NBC',
    startYear: 1955,
    years: '1955',
    genres: ['Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/78/197277.jpg',
    note: '',
  },
  {
    id: 17061,
    tvmazeId: '21885',
    title: 'Crossroads',
    network: 'ABC',
    startYear: 1955,
    years: '1955–1957',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/78/197263.jpg',
    note: '',
  },
  {
    id: 17062,
    tvmazeId: '40954',
    title: 'Crusader',
    network: 'CBS',
    startYear: 1955,
    years: '1955–1956',
    genres: ['Drama', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/183/458789.jpg',
    note: '',
  },
  {
    id: 17063,
    tvmazeId: '76150',
    title: 'Damon Runyon Theater',
    network: 'CBS',
    startYear: 1955,
    years: '1955–1956',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17064,
    tvmazeId: '9975',
    title: 'Dixon of Dock Green',
    network: 'BBC One',
    startYear: 1955,
    years: '1955–1976',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/34/85500.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 711, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 398, "cliffhanger": 239, "ended": 15092}};
