window.pageShows = [
  {
    id: 2785,
    tvmazeId: '82567',
    title: 'Single Black Female',
    network: 'Lifetime',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/560/1400964.jpg',
    note: '',
  },
  {
    id: 2786,
    tvmazeId: '52322',
    title: 'Single Drunk Female',
    network: 'Freeform.com',
    startYear: 2022,
    years: '2022–2023',
    genres: ['Drama', 'Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/456/1140582.jpg',
    note: '',
  },
  {
    id: 2787,
    tvmazeId: '75099',
    title: 'Single, Out',
    network: 'Here TV',
    startYear: 2022,
    years: '2022–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/559/1398646.jpg',
    note: '',
  },
  {
    id: 2788,
    tvmazeId: '45841',
    title: 'Sister Boniface Mysteries',
    network: 'BritBox',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/405/1013296.jpg',
    note: '',
  },
  {
    id: 2789,
    tvmazeId: '63915',
    title: 'Sketchy Queens',
    network: 'WOW Presents Plus',
    startYear: 2022,
    years: '2022–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/553/1384130.jpg',
    note: '',
  },
  {
    id: 2790,
    tvmazeId: '61031',
    title: 'Skint',
    network: 'BBC iPlayer',
    startYear: 2022,
    years: '2022–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 2791,
    tvmazeId: '61171',
    title: 'Skruk',
    network: 'Netflix',
    startYear: 2022,
    years: '2022–',
    genres: ['Comedy', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/410/1026671.jpg',
    note: '',
  },
  {
    id: 2792,
    tvmazeId: '57682',
    title: 'SkyMed',
    network: 'Paramount+',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Romance', 'Medical'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/622/1557107.jpg',
    note: '',
  },
  {
    id: 2793,
    tvmazeId: '45039',
    title: 'Slow Horses',
    network: 'Apple TV',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Thriller', 'Espionage'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/593/1484384.jpg',
    note: '',
  },
  {
    id: 2794,
    tvmazeId: '64284',
    title: 'Slumberkins',
    network: 'Apple TV',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy', 'Children'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/438/1096360.jpg',
    note: '',
  },
  {
    id: 2795,
    tvmazeId: '66927',
    title: 'Small & Mighty',
    network: 'Disney+',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/446/1116136.jpg',
    note: '',
  },
  {
    id: 2796,
    tvmazeId: '65535',
    title: 'Smiley',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/433/1082669.jpg',
    note: '',
  },
  {
    id: 2797,
    tvmazeId: '63488',
    title: 'Snap',
    network: 'ALLBLK',
    startYear: 2022,
    years: '2022–',
    genres: ['Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/435/1089468.jpg',
    note: '',
  },
  {
    id: 2798,
    tvmazeId: '60076',
    title: 'Sneakerhead',
    network: 'U',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/414/1036343.jpg',
    note: '',
  },
  {
    id: 2799,
    tvmazeId: '62029',
    title: 'So Help Me Todd',
    network: 'CBS',
    startYear: 2022,
    years: '2022–2024',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/504/1260388.jpg',
    note: '',
  },
  {
    id: 2800,
    tvmazeId: '77713',
    title: 'SolarBalls',
    network: 'YouTube',
    startYear: 2022,
    years: '2022–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/522/1307271.jpg',
    note: '',
  },
  {
    id: 2801,
    tvmazeId: '60172',
    title: 'Somebody',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/424/1061738.jpg',
    note: '',
  },
  {
    id: 2802,
    tvmazeId: '49313',
    title: 'Somebody Somewhere',
    network: 'HBO',
    startYear: 2022,
    years: '2022–2024',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/540/1351951.jpg',
    note: '',
  },
  {
    id: 2803,
    tvmazeId: '49914',
    title: 'Somewhere Boy',
    network: 'Channel 4',
    startYear: 2022,
    years: '2022',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/426/1067412.jpg',
    note: '',
  },
  {
    id: 2804,
    tvmazeId: '56930',
    title: 'Son of a Critch',
    network: 'CBC',
    startYear: 2022,
    years: '2022–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/501/1253400.jpg',
    note: '',
  },
  {
    id: 2805,
    tvmazeId: '53242',
    title: 'Sonic Prime',
    network: 'Netflix',
    startYear: 2022,
    years: '2022–2024',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/428/1071073.jpg',
    note: '',
  },
  {
    id: 2806,
    tvmazeId: '60557',
    title: 'Soundtrack #1',
    network: 'Disney+',
    startYear: 2022,
    years: '2022–2023',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/594/1487285.jpg',
    note: '',
  },
  {
    id: 2807,
    tvmazeId: '63657',
    title: 'Soundtrack to Our Teenage Zombie Apocalypse',
    network: 'ABC iview',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/419/1048833.jpg',
    note: '',
  },
  {
    id: 2808,
    tvmazeId: '65381',
    title: 'Spirit & Friends',
    network: 'YouTube',
    startYear: 2022,
    years: '2022–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  }
];
window.pageMetadata = {"page": 117, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
