window.pageShows = [
  {
    id: 12817,
    tvmazeId: '24019',
    title: 'Pride & Joy',
    network: 'NBC',
    startYear: 1995,
    years: '1995',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/90/227310.jpg',
    note: '',
  },
  {
    id: 12818,
    tvmazeId: '2355',
    title: 'Pride and Prejudice',
    network: 'BBC One',
    startYear: 1995,
    years: '1995',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/12/32116.jpg',
    note: '',
  },
  {
    id: 12819,
    tvmazeId: '19167',
    title: 'Princess Gwenevere and the Jewel Riders',
    network: 'Syndication',
    startYear: 1995,
    years: '1995–1996',
    genres: ['Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/523/1309767.jpg',
    note: '',
  },
  {
    id: 12820,
    tvmazeId: '51215',
    title: 'Resort to Murder',
    network: 'BBC One',
    startYear: 1995,
    years: '1995',
    genres: ['Crime', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/419/1048983.jpg',
    note: '',
  },
  {
    id: 12821,
    tvmazeId: '65668',
    title: 'Sherman Oaks',
    network: 'Paramount+ with Showtime',
    startYear: 1995,
    years: '1995–1997',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/434/1085172.jpg',
    note: '',
  },
  {
    id: 12822,
    tvmazeId: '24879',
    title: 'Simon',
    network: 'The WB',
    startYear: 1995,
    years: '1995–1996',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/95/239505.jpg',
    note: '',
  },
  {
    id: 12823,
    tvmazeId: '26897',
    title: 'Skeleton Warriors',
    network: 'CBS',
    startYear: 1995,
    years: '1995',
    genres: ['Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/106/265328.jpg',
    note: '',
  },
  {
    id: 12824,
    tvmazeId: '31063',
    title: 'Sky Trackers',
    network: 'Seven Network',
    startYear: 1995,
    years: '1995',
    genres: ['Drama', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/123/309582.jpg',
    note: '',
  },
  {
    id: 12825,
    tvmazeId: '31553',
    title: 'Skysurfer Strike Force',
    network: 'Syndication',
    startYear: 1995,
    years: '1995–1996',
    genres: ['Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/126/315366.jpg',
    note: '',
  },
  {
    id: 12826,
    tvmazeId: '583',
    title: 'Sliders',
    network: 'Syfy',
    startYear: 1995,
    years: '1995–2000',
    genres: ['Adventure', 'Fantasy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/4/11896.jpg',
    note: '',
  },
  {
    id: 12827,
    tvmazeId: '5818',
    title: 'Space: Above and Beyond',
    network: 'FOX',
    startYear: 1995,
    years: '1995–1996',
    genres: ['Drama', 'Science-Fiction', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/57873.jpg',
    note: '',
  },
  {
    id: 12828,
    tvmazeId: '5645',
    title: 'Spellbinder',
    network: 'Nine Network',
    startYear: 1995,
    years: '1995–1997',
    genres: ['Adventure', 'Fantasy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/56810.jpg',
    note: '',
  },
  {
    id: 12829,
    tvmazeId: '492',
    title: 'Star Trek: Voyager',
    network: 'UPN',
    startYear: 1995,
    years: '1995–2001',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/362/907309.jpg',
    note: '',
  },
  {
    id: 12830,
    tvmazeId: '4950',
    title: 'Strange Luck',
    network: 'FOX',
    startYear: 1995,
    years: '1995–1996',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Fox cancelled after one season; Chance Harper\'s extreme luck and its true origin were never explained.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/56126.jpg',
    note: '',
  },
  {
    id: 12831,
    tvmazeId: '9918',
    title: 'Street Fighter',
    network: 'USA Network',
    startYear: 1995,
    years: '1995–1997',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/34/85211.jpg',
    note: '',
  },
  {
    id: 12832,
    tvmazeId: '14558',
    title: 'Streets of Laredo',
    network: 'CBS',
    startYear: 1995,
    years: '1995',
    genres: ['Drama', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/49/123246.jpg',
    note: '',
  },
  {
    id: 12833,
    tvmazeId: '74559',
    title: 'Tenko and the Guardians of the Magic',
    network: 'Syndication',
    startYear: 1995,
    years: '1995',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/503/1258090.jpg',
    note: '',
  },
  {
    id: 12834,
    tvmazeId: '75848',
    title: 'The Adventures of Hyperman',
    network: 'CBS',
    startYear: 1995,
    years: '1995–1996',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/556/1391193.jpg',
    note: '',
  },
  {
    id: 12835,
    tvmazeId: '36108',
    title: 'The Baldy Man',
    network: 'ITV1',
    startYear: 1995,
    years: '1995–1997',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/152/382279.jpg',
    note: '',
  },
  {
    id: 12836,
    tvmazeId: '55933',
    title: 'The Bonnie Hunt Show',
    network: 'CBS',
    startYear: 1995,
    years: '1995–1996',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/329/824544.jpg',
    note: '',
  },
  {
    id: 12837,
    tvmazeId: '4275',
    title: 'The Buccaneers',
    network: 'BBC One',
    startYear: 1995,
    years: '1995',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/51117.jpg',
    note: '',
  },
  {
    id: 12838,
    tvmazeId: '17734',
    title: 'The Client',
    network: 'CBS',
    startYear: 1995,
    years: '1995–1996',
    genres: ['Drama', 'Thriller', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/59/149243.jpg',
    note: '',
  },
  {
    id: 12839,
    tvmazeId: '58524',
    title: 'The Crew',
    network: 'FOX',
    startYear: 1995,
    years: '1995–1996',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12840,
    tvmazeId: '1468',
    title: 'The Drew Carey Show',
    network: 'ABC',
    startYear: 1995,
    years: '1995–2004',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/8/21085.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 535, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
