window.pageShows = [
  {
    id: 4349,
    tvmazeId: '78308',
    title: 'Abracadavers',
    network: 'Amazon Freevee',
    startYear: 2019,
    years: '2019–2023',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/526/1317229.jpg',
    note: '',
  },
  {
    id: 4350,
    tvmazeId: '65727',
    title: 'After Ever After',
    network: 'Sky One',
    startYear: 2019,
    years: '2019–2022',
    genres: ['Comedy', 'Family', 'Fantasy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/488/1221199.jpg',
    note: '',
  },
  {
    id: 4351,
    tvmazeId: '36673',
    title: 'After Life',
    network: 'Netflix',
    startYear: 2019,
    years: '2019–2022',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/383/958692.jpg',
    note: '',
  },
  {
    id: 4352,
    tvmazeId: '45532',
    title: 'Agent',
    network: 'Netflix',
    startYear: 2019,
    years: '2019',
    genres: ['Drama'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/232/581719.jpg',
    note: '',
  },
  {
    id: 4353,
    tvmazeId: '48617',
    title: 'Agent Binky: Pets of the Universe',
    network: 'Prime Video',
    startYear: 2019,
    years: '2019–2024',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/380/951826.jpg',
    note: '',
  },
  {
    id: 4354,
    tvmazeId: '41591',
    title: 'Alien 40th Anniversary Short Films',
    network: 'YouTube',
    startYear: 2019,
    years: '2019',
    genres: ['Action', 'Horror', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/203/508861.jpg',
    note: '',
  },
  {
    id: 4355,
    tvmazeId: '39762',
    title: 'Alien News Desk',
    network: 'Syfy',
    startYear: 2019,
    years: '2019',
    genres: ['Comedy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/213/533300.jpg',
    note: '',
  },
  {
    id: 4356,
    tvmazeId: '70969',
    title: 'Alien: Isolation - The Digital Series',
    network: 'IGN',
    startYear: 2019,
    years: '2019',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/475/1188279.jpg',
    note: '',
  },
  {
    id: 4357,
    tvmazeId: '42181',
    title: 'All Rise',
    network: 'Oprah Winfrey Network',
    startYear: 2019,
    years: '2019–2023',
    genres: ['Drama', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/413/1034988.jpg',
    note: '',
  },
  {
    id: 4358,
    tvmazeId: '39229',
    title: 'Almost Family',
    network: 'FOX',
    startYear: 2019,
    years: '2019–2020',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/213/534025.jpg',
    note: '',
  },
  {
    id: 4359,
    tvmazeId: '40155',
    title: 'Almost Never',
    network: 'CBBC',
    startYear: 2019,
    years: '2019–2021',
    genres: ['Drama', 'Children', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/184/461952.jpg',
    note: '',
  },
  {
    id: 4360,
    tvmazeId: '38939',
    title: 'Alta Mar',
    network: 'Netflix',
    startYear: 2019,
    years: '2019–2020',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/227/567627.jpg',
    note: '',
  },
  {
    id: 4361,
    tvmazeId: '43313',
    title: 'Am I the Only One with Butterflies?',
    network: 'Vimeo',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/415/1038996.jpg',
    note: '',
  },
  {
    id: 4362,
    tvmazeId: '42528',
    title: 'Ambitions',
    network: 'Oprah Winfrey Network',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Legal'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/201/503873.jpg',
    note: '',
  },
  {
    id: 4363,
    tvmazeId: '31075',
    title: 'American Princess',
    network: 'Lifetime',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/221/554243.jpg',
    note: '',
  },
  {
    id: 4364,
    tvmazeId: '40328',
    title: 'American Soul',
    network: 'BET',
    startYear: 2019,
    years: '2019–2020',
    genres: ['Drama', 'Music', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/259/649254.jpg',
    note: '',
  },
  {
    id: 4365,
    tvmazeId: '35072',
    title: 'Amphibia',
    network: 'Disney Channel',
    startYear: 2019,
    years: '2019–2022',
    genres: ['Comedy', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: 'Disney Channel gave the series a proper finale, concluding Anne and the Plantar family\'s adventure fully.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/344/861126.jpg',
    note: '',
  },
  {
    id: 4366,
    tvmazeId: '46414',
    title: 'Andy\'s Wild Workouts',
    network: 'CBeebies',
    startYear: 2019,
    years: '2019',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/246/617053.jpg',
    note: '',
  },
  {
    id: 4367,
    tvmazeId: '36471',
    title: 'Another Life',
    network: 'Netflix',
    startYear: 2019,
    years: '2019–2021',
    genres: ['Drama', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Netflix cancelled after two seasons with the alien contact storyline and Niko\'s mission left completely open.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/361/903008.jpg',
    note: '',
  },
  {
    id: 4368,
    tvmazeId: '43494',
    title: 'Apache: La vida de Carlos Tevez',
    network: 'Netflix',
    startYear: 2019,
    years: '2019',
    genres: ['Drama', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/208/521989.jpg',
    note: '',
  },
  {
    id: 4369,
    tvmazeId: '43718',
    title: 'Archibald\'s Next Big Thing',
    network: 'Netflix',
    startYear: 2019,
    years: '2019–2020',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/210/525474.jpg',
    note: '',
  },
  {
    id: 4370,
    tvmazeId: '43830',
    title: 'Are You Afraid of the Dark?',
    network: 'Nickelodeon',
    startYear: 2019,
    years: '2019–2022',
    genres: ['Horror', 'Supernatural'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/494/1235412.jpg',
    note: '',
  },
  {
    id: 4371,
    tvmazeId: '46972',
    title: 'Astrid et Raphaëlle',
    network: 'France 2',
    startYear: 2019,
    years: '2019–',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/628/1572100.jpg',
    note: '',
  },
  {
    id: 4372,
    tvmazeId: '45144',
    title: 'Atiye',
    network: 'Netflix',
    startYear: 2019,
    years: '2019–2021',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/233/582811.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 182, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
