window.pageShows = [
  {
    id: 2161,
    tvmazeId: '53987',
    title: 'Harry Hill\'s Lonely Island',
    network: 'BBC Two',
    startYear: 2021,
    years: '2021–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/299/748164.jpg',
    note: '',
  },
  {
    id: 2162,
    tvmazeId: '43102',
    title: 'Hawkeye',
    network: 'Disney+',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/383/959105.jpg',
    note: '',
  },
  {
    id: 2163,
    tvmazeId: '45488',
    title: 'He-Man and the Masters of the Universe',
    network: 'Netflix',
    startYear: 2021,
    years: '2021–2022',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/357/894764.jpg',
    note: '',
  },
  {
    id: 2164,
    tvmazeId: '48015',
    title: 'Head of the Class',
    network: 'HBO Max',
    startYear: 2021,
    years: '2021',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/368/921517.jpg',
    note: '',
  },
  {
    id: 2165,
    tvmazeId: '55069',
    title: 'Heels',
    network: 'STARZ',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Drama', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/472/1181464.jpg',
    note: '',
  },
  {
    id: 2166,
    tvmazeId: '58190',
    title: 'Hello, Jack! The Kindness Show',
    network: 'Apple TV',
    startYear: 2021,
    years: '2021–2022',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/363/909927.jpg',
    note: '',
  },
  {
    id: 2167,
    tvmazeId: '72526',
    title: 'Here Comes Your Man checkifcancelled',
    network: 'Dekkoo',
    startYear: 2021,
    years: '2021–',
    genres: ['Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/485/1214085.jpg',
    note: '',
  },
  {
    id: 2168,
    tvmazeId: '58880',
    title: 'Hidden Assets checkifcancelled',
    network: 'RTÉ ONE',
    startYear: 2021,
    years: '2021–',
    genres: ['Drama', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/597/1493349.jpg',
    note: '',
  },
  {
    id: 2169,
    tvmazeId: '55001',
    title: 'Hit & Run',
    network: 'Netflix',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Action', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/311/778638.jpg',
    note: '',
  },
  {
    id: 2170,
    tvmazeId: '46413',
    title: 'Hollington Drive',
    network: 'ITV1',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/362/906953.jpg',
    note: '',
  },
  {
    id: 2171,
    tvmazeId: '52312',
    title: 'Home Economics',
    network: 'ABC',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/441/1104670.jpg',
    note: '',
  },
  {
    id: 2172,
    tvmazeId: '43084',
    title: 'Home Invasion',
    network: 'Viaplay',
    startYear: 2021,
    years: '2021',
    genres: ['Comedy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/320/801488.jpg',
    note: '',
  },
  {
    id: 2173,
    tvmazeId: '57165',
    title: 'Hope Street',
    network: 'BBC iPlayer',
    startYear: 2021,
    years: '2021–',
    genres: ['Drama', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/595/1489494.jpg',
    note: '',
  },
  {
    id: 2174,
    tvmazeId: '45497',
    title: 'HouseBroken',
    network: 'FOX',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/444/1111513.jpg',
    note: '',
  },
  {
    id: 2175,
    tvmazeId: '56814',
    title: 'How to Stay at Home',
    network: 'Disney+',
    startYear: 2021,
    years: '2021',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/348/870720.jpg',
    note: '',
  },
  {
    id: 2176,
    tvmazeId: '43175',
    title: 'I Know What You Did Last Summer',
    network: 'Prime Video',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/357/893898.jpg',
    note: '',
  },
  {
    id: 2177,
    tvmazeId: '56836',
    title: 'I ❤️ Arlo',
    network: 'Netflix',
    startYear: 2021,
    years: '2021',
    genres: ['Comedy', 'Adventure', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/348/871534.jpg',
    note: '',
  },
  {
    id: 2178,
    tvmazeId: '52330',
    title: 'iCarly',
    network: 'Paramount+',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Comedy', 'Children', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/463/1157974.jpg',
    note: '',
  },
  {
    id: 2179,
    tvmazeId: '56771',
    title: 'Iggy and Ace',
    network: 'SBS On Demand',
    startYear: 2021,
    years: '2021–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/356/892282.jpg',
    note: '',
  },
  {
    id: 2180,
    tvmazeId: '55576',
    title: 'INDEMNITY: The Rabbit Hole',
    network: 'YouTube',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/321/803557.jpg',
    note: '',
  },
  {
    id: 2181,
    tvmazeId: '41933',
    title: 'Inside Job',
    network: 'Netflix',
    startYear: 2021,
    years: '2021–2022',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Netflix cancelled after two seasons; Reagan Ridley\'s Cognito Inc. leadership and her father\'s redemption were cut short.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/360/901511.jpg',
    note: '',
  },
  {
    id: 2182,
    tvmazeId: '41049',
    title: 'Intergalactic',
    network: 'Now',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/385/962561.jpg',
    note: '',
  },
  {
    id: 2183,
    tvmazeId: '51032',
    title: 'Intruder',
    network: '5',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/304/760080.jpg',
    note: '',
  },
  {
    id: 2184,
    tvmazeId: '49964',
    title: 'Invasion',
    network: 'Apple TV',
    startYear: 2021,
    years: '2021–',
    genres: ['Drama', 'Science-Fiction', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Apple TV+ cancelled after three seasons; the alien invasion story and humanity\'s fate were left completely unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/589/1473271.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 91, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 785, "cliffhanger": 237, "ended": 13610}};
