window.pageShows = [
  {
    id: 9073,
    tvmazeId: '71626',
    title: 'Skatoony',
    network: 'Cartoon Network',
    startYear: 2010,
    years: '2010–2013',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/479/1198202.jpg',
    note: '',
  },
  {
    id: 9074,
    tvmazeId: '4605',
    title: 'Solsidan',
    network: 'TV4 Play',
    startYear: 2010,
    years: '2010–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/52410.jpg',
    note: '',
  },
  {
    id: 9075,
    tvmazeId: '3941',
    title: 'Sons of Tucson',
    network: 'FOX',
    startYear: 2010,
    years: '2010',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/397/994644.jpg',
    note: '',
  },
  {
    id: 9076,
    tvmazeId: '716',
    title: 'Spartacus',
    network: 'STARZ',
    startYear: 2010,
    years: '2010–2013',
    genres: ['Drama', 'Action', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/354/886339.jpg',
    note: '',
  },
  {
    id: 9077,
    tvmazeId: '62091',
    title: 'Spirit Warriors',
    network: 'CBBC',
    startYear: 2010,
    years: '2010',
    genres: ['Drama', 'Children', 'Fantasy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/419/1048363.jpg',
    note: '',
  },
  {
    id: 9078,
    tvmazeId: '9906',
    title: 'Spirited',
    network: 'Binge',
    startYear: 2010,
    years: '2010–2011',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/34/85170.jpg',
    note: '',
  },
  {
    id: 9079,
    tvmazeId: '28069',
    title: 'Spliced',
    network: 'Cartoon Network',
    startYear: 2010,
    years: '2010',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/111/277548.jpg',
    note: '',
  },
  {
    id: 9080,
    tvmazeId: '8300',
    title: 'Stanley Park',
    network: 'BBC Three',
    startYear: 2010,
    years: '2010',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/74770.jpg',
    note: '',
  },
  {
    id: 9081,
    tvmazeId: '12447',
    title: 'Strawberry Shortcake\'s Berry Bitty Adventures',
    network: 'Family Channel',
    startYear: 2010,
    years: '2010–2015',
    genres: ['Children'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/42/106282.jpg',
    note: '',
  },
  {
    id: 9082,
    tvmazeId: '804',
    title: 'Strike Back',
    network: 'Cinemax',
    startYear: 2010,
    years: '2010–2020',
    genres: ['Drama', 'Action', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/485/1213247.jpg',
    note: '',
  },
  {
    id: 9083,
    tvmazeId: '9228',
    title: 'Submissions Only',
    network: 'YouTube',
    startYear: 2010,
    years: '2010–2014',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/32/81315.jpg',
    note: '',
  },
  {
    id: 9084,
    tvmazeId: '34918',
    title: 'Summer in Transylvania',
    network: 'Nickelodeon',
    startYear: 2010,
    years: '2010–2011',
    genres: ['Drama', 'Comedy', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/146/365599.jpg',
    note: '',
  },
  {
    id: 9085,
    tvmazeId: '17318',
    title: 'Sungkyunkwan Scandal',
    network: 'KBS1',
    startYear: 2010,
    years: '2010',
    genres: ['Drama', 'Comedy', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/582/1456535.jpg',
    note: '',
  },
  {
    id: 9086,
    tvmazeId: '9052',
    title: 'Svetlana',
    network: 'AXS TV',
    startYear: 2010,
    years: '2010–2011',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/79976.jpg',
    note: '',
  },
  {
    id: 9087,
    tvmazeId: '1954',
    title: 'Sym-Bionic Titan',
    network: 'Cartoon Network',
    startYear: 2010,
    years: '2010–2011',
    genres: ['Action', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Cartoon Network cancelled after one season mid-story; Lance, Ilana and Octus\'s fight to protect Earth was unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/27895.jpg',
    note: '',
  },
  {
    id: 9088,
    tvmazeId: '16497',
    title: 'T.U.F.F. Puppy',
    network: 'Nicktoons',
    startYear: 2010,
    years: '2010–2015',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/55/137515.jpg',
    note: '',
  },
  {
    id: 9089,
    tvmazeId: '30161',
    title: 'Take Two with Phineas and Ferb',
    network: 'Disney Channel',
    startYear: 2010,
    years: '2010–2011',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/119/299633.jpg',
    note: '',
  },
  {
    id: 9090,
    tvmazeId: '12443',
    title: 'Team Umizoomi',
    network: 'Nick Jr.',
    startYear: 2010,
    years: '2010–2015',
    genres: ['Children', 'Fantasy', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/448/1122493.jpg',
    note: '',
  },
  {
    id: 9091,
    tvmazeId: '1061',
    title: 'Terriers',
    network: 'FX',
    startYear: 2010,
    years: '2010',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/167/419117.jpg',
    note: '',
  },
  {
    id: 9092,
    tvmazeId: '3888',
    title: 'Terry Pratchett\'s Going Postal',
    network: 'Sky Showcase',
    startYear: 2010,
    years: '2010',
    genres: ['Comedy', 'Fantasy', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/48698.jpg',
    note: '',
  },
  {
    id: 9093,
    tvmazeId: '37454',
    title: 'The Adventures of Chuck & Friends',
    network: 'Discovery Family',
    startYear: 2010,
    years: '2010–2012',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/159/399328.jpg',
    note: '',
  },
  {
    id: 9094,
    tvmazeId: '671',
    title: 'The Avengers: Earth\'s Mightiest Heroes!',
    network: 'Disney XD',
    startYear: 2010,
    years: '2010–2013',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Disney cancelled after two seasons for the Avengers Assemble reboot; unresolved Secret Invasion and Galactus storylines were dropped.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/399/998632.jpg',
    note: '',
  },
  {
    id: 9095,
    tvmazeId: '63592',
    title: 'The Bay',
    network: 'Popstar! TV',
    startYear: 2010,
    years: '2010–',
    genres: ['Drama', 'Family', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/419/1047605.jpg',
    note: '',
  },
  {
    id: 9096,
    tvmazeId: '762',
    title: 'The Big C',
    network: 'Paramount+ with Showtime',
    startYear: 2010,
    years: '2010–2013',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/15271.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 379, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
