window.pageShows = [
  {
    id: 577,
    tvmazeId: '85870',
    title: 'Moni',
    network: 'SBS On Demand',
    startYear: 2025,
    years: '2025',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/577/1444537.jpg',
    note: '',
  },
  {
    id: 578,
    tvmazeId: '86754',
    title: 'Monster: The Ed Gein Story',
    network: 'Netflix',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Crime', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/584/1461917.jpg',
    note: '',
  },
  {
    id: 579,
    tvmazeId: '72864',
    title: 'Motorheads',
    network: 'Prime Video',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/567/1418402.jpg',
    note: '',
  },
  {
    id: 580,
    tvmazeId: '87193',
    title: 'Mrs Playmen',
    network: 'Netflix',
    startYear: 2025,
    years: '2025',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/597/1494397.jpg',
    note: '',
  },
  {
    id: 581,
    tvmazeId: '82743',
    title: 'Murdaugh: Death in the Family',
    network: 'Hulu',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/592/1480197.jpg',
    note: '',
  },
  {
    id: 582,
    tvmazeId: '81585',
    title: 'Murder Before Evensong',
    network: 'Acorn TV',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/588/1471686.jpg',
    note: '',
  },
  {
    id: 583,
    tvmazeId: '85192',
    title: 'Murder Most Puzzling',
    network: '5',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/574/1436530.jpg',
    note: '',
  },
  {
    id: 584,
    tvmazeId: '73453',
    title: 'Murderbot',
    network: 'Apple TV',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy', 'Action', 'Science-Fiction'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/563/1408093.jpg',
    note: '',
  },
  {
    id: 585,
    tvmazeId: '83697',
    title: 'My Mafia Pilot Boyfriend',
    network: 'DramaWave',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/561/1404054.jpg',
    note: '',
  },
  {
    id: 586,
    tvmazeId: '81092',
    title: 'My Magic Prophecy',
    network: 'GMM25',
    startYear: 2025,
    years: '2025',
    genres: ['Crime', 'Romance', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/577/1443502.jpg',
    note: '',
  },
  {
    id: 587,
    tvmazeId: '82658',
    title: 'My Serial Killer Lover',
    network: 'Dramabox',
    startYear: 2025,
    years: '2025–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/556/1390952.jpg',
    note: '',
  },
  {
    id: 588,
    tvmazeId: '86865',
    title: 'Máscaras de Oxigênio Não Cairão Automaticamente',
    network: 'HBO',
    startYear: 2025,
    years: '2025',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/585/1464528.jpg',
    note: '',
  },
  {
    id: 589,
    tvmazeId: '87616',
    title: 'Nadie nos vio partir',
    network: 'Netflix',
    startYear: 2025,
    years: '2025',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/592/1481056.jpg',
    note: '',
  },
  {
    id: 590,
    tvmazeId: '82709',
    title: 'National Theatre Live',
    network: 'Sky Arts',
    startYear: 2025,
    years: '2025–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/615/1538067.jpg',
    note: '',
  },
  {
    id: 591,
    tvmazeId: '76760',
    title: 'NCIS: Tony & Ziva',
    network: 'Paramount+',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/593/1484371.jpg',
    note: '',
  },
  {
    id: 592,
    tvmazeId: '89484',
    title: 'Niebo. Rok w piekle',
    network: 'HBO',
    startYear: 2025,
    years: '2025–2026',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/606/1515528.jpg',
    note: '',
  },
  {
    id: 593,
    tvmazeId: '75195',
    title: 'Nine Bodies in a Mexican Morgue',
    network: 'MGM+',
    startYear: 2025,
    years: '2025',
    genres: ['Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/557/1394493.jpg',
    note: '',
  },
  {
    id: 594,
    tvmazeId: '81529',
    title: 'Nine Puzzles',
    network: 'Disney+',
    startYear: 2025,
    years: '2025',
    genres: ['Crime', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/564/1411412.jpg',
    note: '',
  },
  {
    id: 595,
    tvmazeId: '88274',
    title: 'No Strings Attached',
    network: 'Channel 4',
    startYear: 2025,
    years: '2025–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/597/1493665.jpg',
    note: '',
  },
  {
    id: 596,
    tvmazeId: '89496',
    title: 'No, Your Majesty',
    network: 'My Drama',
    startYear: 2025,
    years: '2025',
    genres: ['Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/606/1515881.jpg',
    note: '',
  },
  {
    id: 597,
    tvmazeId: '88888',
    title: 'Nordin',
    network: 'Prime Video',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/602/1507281.jpg',
    note: '',
  },
  {
    id: 598,
    tvmazeId: '75363',
    title: 'North of North',
    network: 'CBC Gem',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/550/1376534.jpg',
    note: '',
  },
  {
    id: 599,
    tvmazeId: '84648',
    title: 'Not a Box',
    network: 'Apple TV',
    startYear: 2025,
    years: '2025–',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/571/1427884.jpg',
    note: '',
  },
  {
    id: 600,
    tvmazeId: '82825',
    title: 'Novelette Is Trying',
    network: 'OUTtv',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/557/1393136.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 25, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
