window.pageShows = [
  {
    id: 2833,
    tvmazeId: '62651',
    title: 'Thalu',
    network: 'ABC Entertains',
    startYear: 2020,
    years: '2020',
    genres: ['Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/413/1034094.jpg',
    note: '',
  },
  {
    id: 2834,
    tvmazeId: '59748',
    title: 'The Accidental Wolf',
    network: 'MHz Choice',
    startYear: 2020,
    years: '2020–2022',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/463/1159218.jpg',
    note: '',
  },
  {
    id: 2835,
    tvmazeId: '56852',
    title: 'The Andy Cohen Diaries',
    network: 'The Roku Channel',
    startYear: 2020,
    years: '2020',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/387/969463.jpg',
    note: '',
  },
  {
    id: 2836,
    tvmazeId: '53809',
    title: 'The Anomalyst',
    network: 'Prime Video',
    startYear: 2020,
    years: '2020–2023',
    genres: ['Horror', 'Thriller', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/467/1168148.jpg',
    note: '',
  },
  {
    id: 2837,
    tvmazeId: '46340',
    title: 'The Astronauts',
    network: 'Nickelodeon',
    startYear: 2020,
    years: '2020–2021',
    genres: ['Adventure', 'Family', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/282/705468.jpg',
    note: '',
  },
  {
    id: 2838,
    tvmazeId: '41167',
    title: 'The Baby-Sitters Club',
    network: 'Netflix',
    startYear: 2020,
    years: '2020–2021',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/579/1448192.jpg',
    note: '',
  },
  {
    id: 2839,
    tvmazeId: '42152',
    title: 'The Baker and the Beauty',
    network: 'ABC',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/237/594220.jpg',
    note: '',
  },
  {
    id: 2840,
    tvmazeId: '43209',
    title: 'The Big Show Show',
    network: 'Netflix',
    startYear: 2020,
    years: '2020',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/249/624694.jpg',
    note: '',
  },
  {
    id: 2841,
    tvmazeId: '61932',
    title: 'The Browns',
    network: 'OUTtv',
    startYear: 2020,
    years: '2020–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/407/1019492.jpg',
    note: '',
  },
  {
    id: 2842,
    tvmazeId: '48730',
    title: 'The Comey Rule',
    network: 'Paramount+ with Showtime',
    startYear: 2020,
    years: '2020',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/269/674052.jpg',
    note: '',
  },
  {
    id: 2843,
    tvmazeId: '52021',
    title: 'The Dark: The Great Deceiver',
    network: 'Prime Video',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/284/711027.jpg',
    note: '',
  },
  {
    id: 2844,
    tvmazeId: '45342',
    title: 'The Dead Lands',
    network: 'Shudder',
    startYear: 2020,
    years: '2020',
    genres: ['Action', 'Adventure', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/230/575805.jpg',
    note: '',
  },
  {
    id: 2845,
    tvmazeId: '43091',
    title: 'The Deceived',
    network: '5',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/267/668086.jpg',
    note: '',
  },
  {
    id: 2846,
    tvmazeId: '76271',
    title: 'The Dog & Pony Show',
    network: 'Treehouse',
    startYear: 2020,
    years: '2020–2021',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/515/1288318.jpg',
    note: '',
  },
  {
    id: 2847,
    tvmazeId: '47800',
    title: 'The Dress Up Gang',
    network: 'TBS.com',
    startYear: 2020,
    years: '2020',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/255/638094.jpg',
    note: '',
  },
  {
    id: 2848,
    tvmazeId: '39665',
    title: 'The Duchess',
    network: 'Netflix',
    startYear: 2020,
    years: '2020',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/272/682085.jpg',
    note: '',
  },
  {
    id: 2849,
    tvmazeId: '38884',
    title: 'The End',
    network: 'Sky Atlantic',
    startYear: 2020,
    years: '2020',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/240/601510.jpg',
    note: '',
  },
  {
    id: 2850,
    tvmazeId: '36284',
    title: 'The English Game',
    network: 'Netflix',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/245/613618.jpg',
    note: '',
  },
  {
    id: 2851,
    tvmazeId: '71303',
    title: 'The Epic Adventures of Morph',
    network: 'Now',
    startYear: 2020,
    years: '2020–2021',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/477/1193055.jpg',
    note: '',
  },
  {
    id: 2852,
    tvmazeId: '66523',
    title: 'The Epic Tales of Captain Underpants in Space!',
    network: 'Netflix',
    startYear: 2020,
    years: '2020',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/442/1106722.jpg',
    note: '',
  },
  {
    id: 2853,
    tvmazeId: '42305',
    title: 'The Expanding Universe of Ashley Garcia',
    network: 'Netflix',
    startYear: 2020,
    years: '2020',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/240/600617.jpg',
    note: '',
  },
  {
    id: 2854,
    tvmazeId: '50014',
    title: 'The Expecting',
    network: 'Quibi',
    startYear: 2020,
    years: '2020',
    genres: ['Horror', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/270/676226.jpg',
    note: '',
  },
  {
    id: 2855,
    tvmazeId: '41082',
    title: 'The First Team',
    network: 'BBC iPlayer',
    startYear: 2020,
    years: '2020',
    genres: ['Comedy', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/259/647979.jpg',
    note: '',
  },
  {
    id: 2856,
    tvmazeId: '42843',
    title: 'The Flight Attendant',
    network: 'HBO Max',
    startYear: 2020,
    years: '2020–2022',
    genres: ['Comedy', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/445/1113526.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 119, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 334, "cliffhanger": 235, "ended": 13701}};
