window.pageShows = [
  {
    id: 1009,
    tvmazeId: '77674',
    title: 'Desde el Mañana',
    network: 'Disney+',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Science-Fiction', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/523/1308899.jpg',
    note: '',
  },
  {
    id: 1010,
    tvmazeId: '82657',
    title: 'Desired by My Unknown Husband',
    network: 'Dramabox',
    startYear: 2024,
    years: '2024',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/556/1390848.jpg',
    note: '',
  },
  {
    id: 1011,
    tvmazeId: '76509',
    title: 'Destination Heaven',
    network: 'Great American Pure Flix',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/529/1323209.jpg',
    note: '',
  },
  {
    id: 1012,
    tvmazeId: '67316',
    title: 'Dexter: Original Sin',
    network: 'Paramount+',
    startYear: 2024,
    years: '2024–2025',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/548/1372007.jpg',
    note: '',
  },
  {
    id: 1013,
    tvmazeId: '69170',
    title: 'Diarra from Detroit',
    network: 'Paramount+',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Comedy', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/507/1269977.jpg',
    note: '',
  },
  {
    id: 1014,
    tvmazeId: '75463',
    title: 'Dil Dosti Dilemma',
    network: 'Prime Video',
    startYear: 2024,
    years: '2024',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/516/1290380.jpg',
    note: '',
  },
  {
    id: 1015,
    tvmazeId: '64116',
    title: 'Dinner with the Parents',
    network: 'Amazon Freevee',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/507/1269091.jpg',
    note: '',
  },
  {
    id: 1016,
    tvmazeId: '79920',
    title: 'Dino Dex',
    network: 'Prime Video',
    startYear: 2024,
    years: '2024–',
    genres: ['Adventure', 'Children', 'Fantasy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/537/1344249.jpg',
    note: '',
  },
  {
    id: 1017,
    tvmazeId: '59248',
    title: 'Disclaimer',
    network: 'Apple TV',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/538/1347291.jpg',
    note: '',
  },
  {
    id: 1018,
    tvmazeId: '76373',
    title: 'Doctor Climax',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/522/1305184.jpg',
    note: '',
  },
  {
    id: 1019,
    tvmazeId: '75508',
    title: 'Doctor Odyssey',
    network: 'ABC',
    startYear: 2024,
    years: '2024–2025',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/533/1334692.jpg',
    note: '',
  },
  {
    id: 1020,
    tvmazeId: '73613',
    title: 'Doctor Slump',
    network: 'jTBC',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy', 'Romance', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/503/1259117.jpg',
    note: '',
  },
  {
    id: 1021,
    tvmazeId: '79040',
    title: 'Dodge\'s Pup School',
    network: 'BBC iPlayer',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/537/1344330.jpg',
    note: '',
  },
  {
    id: 1022,
    tvmazeId: '54407',
    title: 'Domino Day',
    network: 'BBC iPlayer',
    startYear: 2024,
    years: '2024–',
    genres: ['Thriller', 'Supernatural'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/502/1255964.jpg',
    note: '',
  },
  {
    id: 1023,
    tvmazeId: '80014',
    title: 'Don\'t Come Home',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Horror', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/541/1354204.jpg',
    note: '',
  },
  {
    id: 1024,
    tvmazeId: '79130',
    title: 'Don\'t Even',
    network: 'Crave',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/532/1331565.jpg',
    note: '',
  },
  {
    id: 1025,
    tvmazeId: '79488',
    title: 'Doppelgänger. Sobowtór',
    network: 'HBO Max',
    startYear: 2024,
    years: '2024',
    genres: ['Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/534/1337444.jpg',
    note: '',
  },
  {
    id: 1026,
    tvmazeId: '61798',
    title: 'Dora',
    network: 'Paramount+',
    startYear: 2024,
    years: '2024–2025',
    genres: ['Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/513/1284071.jpg',
    note: '',
  },
  {
    id: 1027,
    tvmazeId: '81124',
    title: 'Dostoevskij',
    network: 'Sky Atlantic',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/545/1364175.jpg',
    note: '',
  },
  {
    id: 1028,
    tvmazeId: '72766',
    title: 'Douglas is Cancelled',
    network: 'ITVX',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/525/1313017.jpg',
    note: '',
  },
  {
    id: 1029,
    tvmazeId: '76497',
    title: 'Drag Me to the Movies',
    network: 'WOW Presents Plus',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/519/1298540.jpg',
    note: '',
  },
  {
    id: 1030,
    tvmazeId: '77488',
    title: 'Dream Productions',
    network: 'Disney+',
    startYear: 2024,
    years: '2024',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/621/1553834.jpg',
    note: '',
  },
  {
    id: 1031,
    tvmazeId: '81471',
    title: 'Drill',
    network: 'VET Tv',
    startYear: 2024,
    years: '2024–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 1032,
    tvmazeId: '42846',
    title: 'Dune: Prophecy',
    network: 'HBO',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Science-Fiction'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/543/1358056.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 43, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
