window.pageShows = [
  {
    id: 15769,
    tvmazeId: '22604',
    title: 'Cilla\'s Comedy Six',
    network: 'ITV1',
    startYear: 1975,
    years: '1975',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/83/208624.jpg',
    note: '',
  },
  {
    id: 15770,
    tvmazeId: '75538',
    title: 'Dawson\'s Weekly',
    network: 'ITV1',
    startYear: 1975,
    years: '1975',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/509/1274632.jpg',
    note: '',
  },
  {
    id: 15771,
    tvmazeId: '50909',
    title: 'Days of Hope',
    network: 'BBC One',
    startYear: 1975,
    years: '1975',
    genres: ['Drama', 'Family', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/276/690639.jpg',
    note: '',
  },
  {
    id: 15772,
    tvmazeId: '56807',
    title: 'Doctor on the Go',
    network: 'ITV1',
    startYear: 1975,
    years: '1975–1977',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/348/870455.jpg',
    note: '',
  },
  {
    id: 15773,
    tvmazeId: '64762',
    title: 'Doctors\' Hospital',
    network: 'NBC',
    startYear: 1975,
    years: '1975–1976',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/478/1195383.jpg',
    note: '',
  },
  {
    id: 15774,
    tvmazeId: '13335',
    title: 'Edward VII',
    network: 'ITV1',
    startYear: 1975,
    years: '1975',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/46/115507.jpg',
    note: '',
  },
  {
    id: 15775,
    tvmazeId: '3572',
    title: 'Ellery Queen',
    network: 'NBC',
    startYear: 1975,
    years: '1975–1976',
    genres: ['Drama', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/46784.jpg',
    note: '',
  },
  {
    id: 15776,
    tvmazeId: '7279',
    title: 'Far Out Space Nuts',
    network: 'CBS',
    startYear: 1975,
    years: '1975',
    genres: ['Comedy', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/67605.jpg',
    note: '',
  },
  {
    id: 15777,
    tvmazeId: '577',
    title: 'Fawlty Towers',
    network: 'BBC Two',
    startYear: 1975,
    years: '1975–1979',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/4/11842.jpg',
    note: '',
  },
  {
    id: 15778,
    tvmazeId: '25026',
    title: 'Fay',
    network: 'NBC',
    startYear: 1975,
    years: '1975–1976',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/96/241269.jpg',
    note: '',
  },
  {
    id: 15779,
    tvmazeId: '74803',
    title: 'Fraidy Cat',
    network: 'ABC',
    startYear: 1975,
    years: '1975',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/505/1262535.jpg',
    note: '',
  },
  {
    id: 15780,
    tvmazeId: '23576',
    title: 'Get Some In!',
    network: 'ITV1',
    startYear: 1975,
    years: '1975–1978',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/88/221048.jpg',
    note: '',
  },
  {
    id: 15781,
    tvmazeId: '7599',
    title: 'Grady',
    network: 'NBC',
    startYear: 1975,
    years: '1975–1976',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/94/235310.jpg',
    note: '',
  },
  {
    id: 15782,
    tvmazeId: '64763',
    title: 'Hot l Baltimore',
    network: 'ABC',
    startYear: 1975,
    years: '1975',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/427/1069094.jpg',
    note: '',
  },
  {
    id: 15783,
    tvmazeId: '36344',
    title: 'How Green Was My Valley',
    network: 'BBC Two',
    startYear: 1975,
    years: '1975–1976',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/153/383754.jpg',
    note: '',
  },
  {
    id: 15784,
    tvmazeId: '48560',
    title: 'I Didn\'t Know You Cared',
    network: 'BBC One',
    startYear: 1975,
    years: '1975–1979',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/260/652141.jpg',
    note: '',
  },
  {
    id: 15785,
    tvmazeId: '8977',
    title: 'Ivor the Engine',
    network: 'BBC One',
    startYear: 1975,
    years: '1975',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/79750.jpg',
    note: '',
  },
  {
    id: 15786,
    tvmazeId: '21757',
    title: 'Joe Forrester',
    network: 'NBC',
    startYear: 1975,
    years: '1975–1976',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/78/195962.jpg',
    note: '',
  },
  {
    id: 15787,
    tvmazeId: '27518',
    title: 'Karen',
    network: 'ABC',
    startYear: 1975,
    years: '1975',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/108/271491.jpg',
    note: '',
  },
  {
    id: 15788,
    tvmazeId: '24409',
    title: 'Kate McShane',
    network: 'CBS',
    startYear: 1975,
    years: '1975',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/586/1467280.jpg',
    note: '',
  },
  {
    id: 15789,
    tvmazeId: '40016',
    title: 'Khan!',
    network: 'CBS',
    startYear: 1975,
    years: '1975',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/177/442687.jpg',
    note: '',
  },
  {
    id: 15790,
    tvmazeId: '8100',
    title: 'King of Kensington',
    network: 'CBC',
    startYear: 1975,
    years: '1975–1980',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/73880.jpg',
    note: '',
  },
  {
    id: 15791,
    tvmazeId: '79710',
    title: 'Looking for Clancy',
    network: 'BBC Two',
    startYear: 1975,
    years: '1975',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 15792,
    tvmazeId: '36115',
    title: 'Madame Bovary',
    network: 'BBC Two',
    startYear: 1975,
    years: '1975',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/152/382290.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 658, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
