window.pageShows = [
  {
    id: 12481,
    tvmazeId: '36638',
    title: 'In Cold Blood',
    network: 'CBS',
    startYear: 1996,
    years: '1996',
    genres: ['Drama', 'Crime', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/155/387743.jpg',
    note: '',
  },
  {
    id: 12482,
    tvmazeId: '33532',
    title: 'Ink',
    network: 'CBS',
    startYear: 1996,
    years: '1996–1997',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/136/341208.jpg',
    note: '',
  },
  {
    id: 12483,
    tvmazeId: '51138',
    title: 'Into the Fire',
    network: 'BBC One',
    startYear: 1996,
    years: '1996',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12484,
    tvmazeId: '65693',
    title: 'Jack & Jeremy\'s Real Lives',
    network: 'Channel 4',
    startYear: 1996,
    years: '1996',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/434/1086100.jpg',
    note: '',
  },
  {
    id: 12485,
    tvmazeId: '18175',
    title: 'Jonny Quest: The Real Adventures',
    network: 'Cartoon Network',
    startYear: 1996,
    years: '1996–1997',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/61/153912.jpg',
    note: '',
  },
  {
    id: 12486,
    tvmazeId: '8367',
    title: 'Jumanji',
    network: 'UPN',
    startYear: 1996,
    years: '1996–1998',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/44/111282.jpg',
    note: '',
  },
  {
    id: 12487,
    tvmazeId: '31785',
    title: 'Jungle Cubs',
    network: 'ABC',
    startYear: 1996,
    years: '1996–1998',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/127/318436.jpg',
    note: '',
  },
  {
    id: 12488,
    tvmazeId: '6333',
    title: 'Kablam!',
    network: 'Nickelodeon',
    startYear: 1996,
    years: '1996–1999',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/343/858925.jpg',
    note: '',
  },
  {
    id: 12489,
    tvmazeId: '23392',
    title: 'Karaoke',
    network: 'BBC Two',
    startYear: 1996,
    years: '1996',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/87/219665.jpg',
    note: '',
  },
  {
    id: 12490,
    tvmazeId: '4131',
    title: 'Kenan & Kel',
    network: 'Nickelodeon',
    startYear: 1996,
    years: '1996–2000',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/50011.jpg',
    note: '',
  },
  {
    id: 12491,
    tvmazeId: '3883',
    title: 'Kindred: The Embraced',
    network: 'FOX',
    startYear: 1996,
    years: '1996',
    genres: ['Drama', 'Fantasy', 'Horror'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/48682.jpg',
    note: '',
  },
  {
    id: 12492,
    tvmazeId: '65694',
    title: 'L.A. Firefighters',
    network: 'FOX',
    startYear: 1996,
    years: '1996',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12493,
    tvmazeId: '65707',
    title: 'Life with Roger',
    network: 'The WB',
    startYear: 1996,
    years: '1996–1997',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12494,
    tvmazeId: '65708',
    title: 'Life\'s Work',
    network: 'ABC',
    startYear: 1996,
    years: '1996–1997',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12495,
    tvmazeId: '27254',
    title: 'Local Heroes',
    network: 'FOX',
    startYear: 1996,
    years: '1996',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/365/912951.jpg',
    note: '',
  },
  {
    id: 12496,
    tvmazeId: '10936',
    title: 'London Bridge',
    network: 'ITV London',
    startYear: 1996,
    years: '1996–1999',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/36/91975.jpg',
    note: '',
  },
  {
    id: 12497,
    tvmazeId: '39597',
    title: 'Love and Marriage',
    network: 'FOX',
    startYear: 1996,
    years: '1996',
    genres: ['Drama'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/377/942913.jpg',
    note: '',
  },
  {
    id: 12498,
    tvmazeId: '65721',
    title: 'Lush Life',
    network: 'FOX',
    startYear: 1996,
    years: '1996',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/434/1087067.jpg',
    note: '',
  },
  {
    id: 12499,
    tvmazeId: '51151',
    title: 'Madson',
    network: 'BBC One',
    startYear: 1996,
    years: '1996',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12500,
    tvmazeId: '7702',
    title: 'Malcolm & Eddie',
    network: 'UPN',
    startYear: 1996,
    years: '1996–2000',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/70796.jpg',
    note: '',
  },
  {
    id: 12501,
    tvmazeId: '35940',
    title: 'Malibu Shores',
    network: 'NBC',
    startYear: 1996,
    years: '1996',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/152/380796.jpg',
    note: '',
  },
  {
    id: 12502,
    tvmazeId: '42952',
    title: 'Married for Life',
    network: 'ITV1',
    startYear: 1996,
    years: '1996',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/204/512031.jpg',
    note: '',
  },
  {
    id: 12503,
    tvmazeId: '65722',
    title: 'Matt Waters',
    network: 'CBS',
    startYear: 1996,
    years: '1996',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12504,
    tvmazeId: '37386',
    title: 'Medivac',
    network: 'Network 10',
    startYear: 1996,
    years: '1996–1998',
    genres: ['Drama', 'Action', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  }
];
window.pageMetadata = {"page": 521, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
