window.pageShows = [
  {
    id: 12337,
    tvmazeId: '65798',
    title: 'Incredible Story Studio',
    network: 'YTV',
    startYear: 1997,
    years: '1997–2002',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/435/1088315.jpg',
    note: '',
  },
  {
    id: 12338,
    tvmazeId: '51137',
    title: 'Insiders',
    network: 'BBC One',
    startYear: 1997,
    years: '1997',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12339,
    tvmazeId: '32352',
    title: 'Invasion',
    network: 'NBC',
    startYear: 1997,
    years: '1997',
    genres: ['Drama', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: '',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/129/323214.jpg',
    note: '',
  },
  {
    id: 12340,
    tvmazeId: '20938',
    title: 'Ivanhoe',
    network: 'BBC One',
    startYear: 1997,
    years: '1997',
    genres: ['Drama', 'Adventure', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/184874.jpg',
    note: '',
  },
  {
    id: 12341,
    tvmazeId: '22023',
    title: 'Jenny',
    network: 'NBC',
    startYear: 1997,
    years: '1997–1998',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/359/897621.jpg',
    note: '',
  },
  {
    id: 12342,
    tvmazeId: '3932',
    title: 'Johnny Bravo',
    network: 'Cartoon Network',
    startYear: 1997,
    years: '1997–2004',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/48986.jpg',
    note: '',
  },
  {
    id: 12343,
    tvmazeId: '1753',
    title: 'Jonathan Creek',
    network: 'BBC One',
    startYear: 1997,
    years: '1997–2016',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/9/24490.jpg',
    note: '',
  },
  {
    id: 12344,
    tvmazeId: '2039',
    title: 'Just Shoot Me!',
    network: 'NBC',
    startYear: 1997,
    years: '1997–2003',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/312/782287.jpg',
    note: '',
  },
  {
    id: 12345,
    tvmazeId: '7360',
    title: 'Justice League of America',
    network: 'TV Land',
    startYear: 1997,
    years: '1997',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/68114.jpg',
    note: '',
  },
  {
    id: 12346,
    tvmazeId: '32288',
    title: 'Keeping Mum',
    network: 'BBC One',
    startYear: 1997,
    years: '1997–1998',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/129/322654.jpg',
    note: '',
  },
  {
    id: 12347,
    tvmazeId: '4898',
    title: 'Kenny Starfighter',
    network: 'SVT1',
    startYear: 1997,
    years: '1997–2022',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/53564.jpg',
    note: '',
  },
  {
    id: 12348,
    tvmazeId: '115',
    title: 'King of the Hill',
    network: 'Hulu',
    startYear: 1997,
    years: '1997–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/592/1480199.jpg',
    note: '',
  },
  {
    id: 12349,
    tvmazeId: '18014',
    title: 'Kipper',
    network: 'ITV1',
    startYear: 1997,
    years: '1997–2000',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/61/152618.jpg',
    note: '',
  },
  {
    id: 12350,
    tvmazeId: '561',
    title: 'La Femme Nikita',
    network: 'USA Network',
    startYear: 1997,
    years: '1997–2001',
    genres: ['Drama', 'Action', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/481/1204994.jpg',
    note: '',
  },
  {
    id: 12351,
    tvmazeId: '56587',
    title: 'Lassie',
    network: 'YTV',
    startYear: 1997,
    years: '1997',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12352,
    tvmazeId: '32566',
    title: 'Lawless',
    network: 'FOX',
    startYear: 1997,
    years: '1997',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/130/326133.jpg',
    note: '',
  },
  {
    id: 12353,
    tvmazeId: '65812',
    title: 'Leaving L.A.',
    network: 'ABC',
    startYear: 1997,
    years: '1997',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/435/1088676.jpg',
    note: '',
  },
  {
    id: 12354,
    tvmazeId: '1656',
    title: 'Lexx',
    network: 'CTV Sci-Fi Channel',
    startYear: 1997,
    years: '1997–2002',
    genres: ['Drama', 'Horror', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/9/22933.jpg',
    note: '',
  },
  {
    id: 12355,
    tvmazeId: '52650',
    title: 'Li\'l Elvis and the Truckstoppers',
    network: 'ABC',
    startYear: 1997,
    years: '1997–1998',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/290/727212.jpg',
    note: '',
  },
  {
    id: 12356,
    tvmazeId: '65814',
    title: 'Life... and Stuff',
    network: 'CBS',
    startYear: 1997,
    years: '1997',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12357,
    tvmazeId: '62864',
    title: 'Loved by You',
    network: 'ITV1',
    startYear: 1997,
    years: '1997–1998',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12358,
    tvmazeId: '14697',
    title: 'McCallum',
    network: 'ITV1',
    startYear: 1997,
    years: '1997–1998',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/49/124438.jpg',
    note: '',
  },
  {
    id: 12359,
    tvmazeId: '8144',
    title: 'Meego',
    network: 'CBS',
    startYear: 1997,
    years: '1997',
    genres: ['Comedy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/73962.jpg',
    note: '',
  },
  {
    id: 12360,
    tvmazeId: '51152',
    title: 'Melissa',
    network: 'Channel 4',
    startYear: 1997,
    years: '1997',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/277/694214.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 515, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
