window.pageShows = [
  {
    id: 11521,
    tvmazeId: '42456',
    title: 'Packet of Three',
    network: 'Channel 4',
    startYear: 1991,
    years: '1991',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11522,
    tvmazeId: '8848',
    title: 'Palace Guard',
    network: 'CBS',
    startYear: 1991,
    years: '1991',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/78690.jpg',
    note: '',
  },
  {
    id: 11523,
    tvmazeId: '51191',
    title: 'Parnell and the Englishwoman',
    network: 'BBC Two',
    startYear: 1991,
    years: '1991',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/277/694995.jpg',
    note: '',
  },
  {
    id: 11524,
    tvmazeId: '51712',
    title: 'Performance',
    network: 'BBC Two',
    startYear: 1991,
    years: '1991–1998',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11525,
    tvmazeId: '48010',
    title: 'Plaza Patrol',
    network: 'ITV1',
    startYear: 1991,
    years: '1991',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11526,
    tvmazeId: '28524',
    title: 'Police Rescue',
    network: 'ABC',
    startYear: 1991,
    years: '1991–1996',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/113/284047.jpg',
    note: '',
  },
  {
    id: 11527,
    tvmazeId: '1282',
    title: 'Prime Suspect',
    network: 'ITV1',
    startYear: 1991,
    years: '1991–2006',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/18390.jpg',
    note: '',
  },
  {
    id: 11528,
    tvmazeId: '53355',
    title: 'Princesses',
    network: 'CBS',
    startYear: 1991,
    years: '1991',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/295/739311.jpg',
    note: '',
  },
  {
    id: 11529,
    tvmazeId: '40774',
    title: 'ProStars',
    network: 'NBC',
    startYear: 1991,
    years: '1991',
    genres: ['Children', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/182/455712.jpg',
    note: '',
  },
  {
    id: 11530,
    tvmazeId: '18042',
    title: 'Reasonable Doubts',
    network: 'NBC',
    startYear: 1991,
    years: '1991–1993',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/61/152988.jpg',
    note: '',
  },
  {
    id: 11531,
    tvmazeId: '51210',
    title: 'Red Fox',
    network: 'ITV1',
    startYear: 1991,
    years: '1991',
    genres: ['Drama', 'Action', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/278/695163.jpg',
    note: '',
  },
  {
    id: 11532,
    tvmazeId: '8091',
    title: 'Roc',
    network: 'FOX',
    startYear: 1991,
    years: '1991–1994',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/73503.jpg',
    note: '',
  },
  {
    id: 11533,
    tvmazeId: '421',
    title: 'Rugrats',
    network: 'Nickelodeon',
    startYear: 1991,
    years: '1991–2006',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/402/1007439.jpg',
    note: '',
  },
  {
    id: 11534,
    tvmazeId: '17993',
    title: 'Rupert',
    network: 'YTV',
    startYear: 1991,
    years: '1991–1997',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/61/152569.jpg',
    note: '',
  },
  {
    id: 11535,
    tvmazeId: '6304',
    title: 'Salute Your Shorts',
    network: 'Nickelodeon',
    startYear: 1991,
    years: '1991–1992',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/24/60451.jpg',
    note: '',
  },
  {
    id: 11536,
    tvmazeId: '65322',
    title: 'Scene of the Crime',
    network: 'CBS',
    startYear: 1991,
    years: '1991–2002',
    genres: ['Drama', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11537,
    tvmazeId: '10048',
    title: 'Second Thoughts',
    network: 'ITV1',
    startYear: 1991,
    years: '1991–1994',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/34/85848.jpg',
    note: '',
  },
  {
    id: 11538,
    tvmazeId: '26733',
    title: 'Selling Hitler',
    network: 'ITV1',
    startYear: 1991,
    years: '1991',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/105/263223.jpg',
    note: '',
  },
  {
    id: 11539,
    tvmazeId: '50850',
    title: 'Separate But Equal',
    network: 'ABC',
    startYear: 1991,
    years: '1991',
    genres: ['Drama', 'History', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/275/689929.jpg',
    note: '',
  },
  {
    id: 11540,
    tvmazeId: '77989',
    title: 'Sibs',
    network: 'ABC',
    startYear: 1991,
    years: '1991–1992',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/524/1311840.jpg',
    note: '',
  },
  {
    id: 11541,
    tvmazeId: '1893',
    title: 'Silk Stalkings',
    network: 'USA Network',
    startYear: 1991,
    years: '1991–1999',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/27613.jpg',
    note: '',
  },
  {
    id: 11542,
    tvmazeId: '8143',
    title: 'Sisters',
    network: 'NBC',
    startYear: 1991,
    years: '1991–1996',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/73939.jpg',
    note: '',
  },
  {
    id: 11543,
    tvmazeId: '31060',
    title: 'Sleepers',
    network: 'BBC Two',
    startYear: 1991,
    years: '1991',
    genres: ['Drama', 'Comedy', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/123/309574.jpg',
    note: '',
  },
  {
    id: 11544,
    tvmazeId: '65315',
    title: 'So You Think You\'ve Got Troubles',
    network: 'BBC One',
    startYear: 1991,
    years: '1991',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  }
];
window.pageMetadata = {"page": 481, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 785, "cliffhanger": 237, "ended": 13610}};
