window.pageShows = [
  {
    id: 2137,
    tvmazeId: '69251',
    title: 'The Sixth Commandment',
    network: 'BBC iPlayer',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/469/1172605.jpg',
    note: '',
  },
  {
    id: 2138,
    tvmazeId: '67029',
    title: 'The Sound Collector',
    network: 'itv QUiZ',
    startYear: 2023,
    years: '2023–',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/448/1120806.jpg',
    note: '',
  },
  {
    id: 2139,
    tvmazeId: '65181',
    title: 'The Spencer Sisters',
    network: 'CTV',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/443/1108027.jpg',
    note: '',
  },
  {
    id: 2140,
    tvmazeId: '61618',
    title: 'The Turkish Detective',
    network: 'Paramount+',
    startYear: 2023,
    years: '2023–2024',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/498/1246413.jpg',
    note: '',
  },
  {
    id: 2141,
    tvmazeId: '73933',
    title: 'The Twisted Timeline of Sammy & Raj',
    network: 'Nicktoons',
    startYear: 2023,
    years: '2023–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/500/1252430.jpg',
    note: '',
  },
  {
    id: 2142,
    tvmazeId: '71221',
    title: 'The Vanishing Triangle',
    network: 'Sundance Now',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/476/1192134.jpg',
    note: '',
  },
  {
    id: 2143,
    tvmazeId: '72908',
    title: 'The Village',
    network: 'Prime Video',
    startYear: 2023,
    years: '2023',
    genres: ['Horror', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/490/1227208.jpg',
    note: '',
  },
  {
    id: 2144,
    tvmazeId: '64501',
    title: 'The Walking Dead: Daryl Dixon',
    network: 'AMC',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Action', 'Horror'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/581/1453640.jpg',
    note: '',
  },
  {
    id: 2145,
    tvmazeId: '71075',
    title: 'The Walking Dead: Daryl Dixon: Cast Diaries',
    network: 'AMC+',
    startYear: 2023,
    years: '2023–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/476/1192117.jpg',
    note: '',
  },
  {
    id: 2146,
    tvmazeId: '60879',
    title: 'The Walking Dead: Dead City',
    network: 'AMC+',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Action', 'Horror'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/568/1420160.jpg',
    note: '',
  },
  {
    id: 2147,
    tvmazeId: '62854',
    title: 'The Watchful Eye',
    network: 'Freeform',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/443/1108163.jpg',
    note: '',
  },
  {
    id: 2148,
    tvmazeId: '62766',
    title: 'The Way Home',
    network: 'Hallmark Channel',
    startYear: 2023,
    years: '2023–2026',
    genres: ['Drama', 'Family', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/549/1373567.jpg',
    note: '',
  },
  {
    id: 2149,
    tvmazeId: '45906',
    title: 'The Winter King',
    network: 'MGM+',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'History'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/472/1181669.jpg',
    note: '',
  },
  {
    id: 2150,
    tvmazeId: '63576',
    title: 'The Woman in the Wall',
    network: 'BBC One',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/474/1186025.jpg',
    note: '',
  },
  {
    id: 2151,
    tvmazeId: '65500',
    title: 'The Worst of Evil',
    network: 'Disney+',
    startYear: 2023,
    years: '2023',
    genres: ['Action', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/514/1286759.jpg',
    note: '',
  },
  {
    id: 2152,
    tvmazeId: '46253',
    title: 'Then You Run',
    network: 'Now',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/467/1168889.jpg',
    note: '',
  },
  {
    id: 2153,
    tvmazeId: '61166',
    title: 'Three Little Birds',
    network: 'ITVX',
    startYear: 2023,
    years: '2023–2023',
    genres: ['Drama', 'History'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/482/1206506.jpg',
    note: '',
  },
  {
    id: 2154,
    tvmazeId: '65038',
    title: 'Three-Body',
    network: 'Tencent QQ',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Science-Fiction'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/575/1439042.jpg',
    note: '',
  },
  {
    id: 2155,
    tvmazeId: '62425',
    title: 'Tiny Beautiful Things',
    network: 'Hulu',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/455/1139376.jpg',
    note: '',
  },
  {
    id: 2156,
    tvmazeId: '51575',
    title: 'Tiny Toons Looniversity',
    network: 'HBO Max',
    startYear: 2023,
    years: '2023–',
    genres: [],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Max cancelled after one season with the characters\' first year at school unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/491/1229452.jpg',
    note: '',
  },
  {
    id: 2157,
    tvmazeId: '82822',
    title: 'Toad & Friends',
    network: 'Cartoonito',
    startYear: 2023,
    years: '2023–',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/557/1393081.jpg',
    note: '',
  },
  {
    id: 2158,
    tvmazeId: '66457',
    title: 'Todas las veces que nos enamoramos',
    network: 'Netflix',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/447/1117723.jpg',
    note: '',
  },
  {
    id: 2159,
    tvmazeId: '63538',
    title: 'Todo Dia a Mesma Noite',
    network: 'Netflix',
    startYear: 2023,
    years: '2023',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/442/1107293.jpg',
    note: '',
  },
  {
    id: 2160,
    tvmazeId: '69145',
    title: 'Together Forever',
    network: 'YouTube',
    startYear: 2023,
    years: '2023',
    genres: ['Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/465/1163192.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 90, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 295, "ended": 12349}};
