window.pageShows = [
  {
    id: 4321,
    tvmazeId: '42387',
    title: 'Transformers: War for Cybertron Trilogy',
    network: 'Netflix',
    startYear: 2020,
    years: '2020–2021',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/289/724883.jpg',
    note: '',
  },
  {
    id: 4322,
    tvmazeId: '43828',
    title: 'Transplant',
    network: 'CTV',
    startYear: 2020,
    years: '2020–2024',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/480/1200198.jpg',
    note: '',
  },
  {
    id: 4323,
    tvmazeId: '39629',
    title: 'Trash Truck',
    network: 'Netflix',
    startYear: 2020,
    years: '2020–2021',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/280/700141.jpg',
    note: '',
  },
  {
    id: 4324,
    tvmazeId: '46384',
    title: 'Tribal',
    network: 'APTN',
    startYear: 2020,
    years: '2020–',
    genres: ['Drama', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/242/607148.jpg',
    note: '',
  },
  {
    id: 4325,
    tvmazeId: '42445',
    title: 'Trickster',
    network: 'CBC',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Thriller', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/276/691304.jpg',
    note: '',
  },
  {
    id: 4326,
    tvmazeId: '46662',
    title: 'Trigonometry',
    network: 'BBC iPlayer',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/246/615529.jpg',
    note: '',
  },
  {
    id: 4327,
    tvmazeId: '51770',
    title: 'Trolls: TrollsTopia',
    network: 'Hulu',
    startYear: 2020,
    years: '2020–',
    genres: ['Adventure', 'Fantasy', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/599/1498404.jpg',
    note: '',
  },
  {
    id: 4328,
    tvmazeId: '51480',
    title: 'True Beauty',
    network: 'tvN',
    startYear: 2020,
    years: '2020–2021',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/282/706693.jpg',
    note: '',
  },
  {
    id: 4329,
    tvmazeId: '58006',
    title: 'True Story avec',
    network: 'Prime Video',
    startYear: 2020,
    years: '2020–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/362/905683.jpg',
    note: '',
  },
  {
    id: 4330,
    tvmazeId: '48048',
    title: 'True: Terrific Tales',
    network: 'Netflix',
    startYear: 2020,
    years: '2020',
    genres: ['Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/256/641731.jpg',
    note: '',
  },
  {
    id: 4331,
    tvmazeId: '51093',
    title: 'Trump Learns Things',
    network: 'WOW Presents Plus',
    startYear: 2020,
    years: '2020',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/277/693452.jpg',
    note: '',
  },
  {
    id: 4332,
    tvmazeId: '43275',
    title: 'Truth Seekers',
    network: 'Prime Video',
    startYear: 2020,
    years: '2020',
    genres: ['Drama', 'Comedy', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/356/890239.jpg',
    note: '',
  },
  {
    id: 4333,
    tvmazeId: '45928',
    title: 'Trying',
    network: 'Apple TV',
    startYear: 2020,
    years: '2020–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/628/1570848.jpg',
    note: '',
  },
  {
    id: 4334,
    tvmazeId: '38796',
    title: 'Twenties',
    network: 'BET',
    startYear: 2020,
    years: '2020–',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'BET cancelled after two seasons leaving Hattie\'s career and relationships unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/364/911628.jpg',
    note: '',
  },
  {
    id: 4335,
    tvmazeId: '42773',
    title: 'Two Weeks to Live',
    network: 'Now',
    startYear: 2020,
    years: '2020',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/268/670510.jpg',
    note: '',
  },
  {
    id: 4336,
    tvmazeId: '50023',
    title: 'Tyler Perry\'s Assisted Living',
    network: 'BET',
    startYear: 2020,
    years: '2020–',
    genres: ['Comedy', 'Family'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/566/1416627.jpg',
    note: '',
  },
  {
    id: 4337,
    tvmazeId: '47633',
    title: 'Tyler Perry\'s Bruh',
    network: 'BET+',
    startYear: 2020,
    years: '2020–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/420/1050641.jpg',
    note: '',
  },
  {
    id: 4338,
    tvmazeId: '46668',
    title: 'Tyler Perry\'s Ruthless',
    network: 'BET+',
    startYear: 2020,
    years: '2020–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/617/1544110.jpg',
    note: '',
  },
  {
    id: 4339,
    tvmazeId: '46300',
    title: 'Tyler Perry\'s Young Dylan',
    network: 'Nickelodeon',
    startYear: 2020,
    years: '2020–2025',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/480/1200232.jpg',
    note: '',
  },
  {
    id: 4340,
    tvmazeId: '42165',
    title: 'United We Fall',
    network: 'ABC',
    startYear: 2020,
    years: '2020',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/262/655194.jpg',
    note: '',
  },
  {
    id: 4341,
    tvmazeId: '41072',
    title: 'Unorthodox',
    network: 'Netflix',
    startYear: 2020,
    years: '2020',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/248/620726.jpg',
    note: '',
  },
  {
    id: 4342,
    tvmazeId: '48084',
    title: 'Unprecedented',
    network: 'BBC Four',
    startYear: 2020,
    years: '2020',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/259/647792.jpg',
    note: '',
  },
  {
    id: 4343,
    tvmazeId: '49444',
    title: 'Unsaid Stories',
    network: 'ITV1',
    startYear: 2020,
    years: '2020',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/267/668657.jpg',
    note: '',
  },
  {
    id: 4344,
    tvmazeId: '31732',
    title: 'Upload',
    network: 'Prime Video',
    startYear: 2020,
    years: '2020–2025',
    genres: ['Comedy', 'Science-Fiction', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/586/1466414.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 181, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
