window.pageShows = [
  {
    id: 8353,
    tvmazeId: '48385',
    title: 'My Phone Genie',
    network: 'CITV',
    startYear: 2012,
    years: '2012',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 8354,
    tvmazeId: '22424',
    title: 'My Story',
    network: 'CBeebies',
    startYear: 2012,
    years: '2012–2016',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/82/206091.jpg',
    note: '',
  },
  {
    id: 8355,
    tvmazeId: '13528',
    title: 'MyMusic',
    network: 'YouTube',
    startYear: 2012,
    years: '2012–2014',
    genres: ['Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/46/116750.jpg',
    note: '',
  },
  {
    id: 8356,
    tvmazeId: '5725',
    title: 'Napoleon Dynamite',
    network: 'FOX',
    startYear: 2012,
    years: '2012',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/57176.jpg',
    note: '',
  },
  {
    id: 8357,
    tvmazeId: '53',
    title: 'Nashville',
    network: 'CMT',
    startYear: 2012,
    years: '2012–2018',
    genres: ['Drama', 'Music', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/89/224913.jpg',
    note: '',
  },
  {
    id: 8358,
    tvmazeId: '7645',
    title: 'Neil\'s Puppet Dreams',
    network: 'YouTube',
    startYear: 2012,
    years: '2012–2013',
    genres: ['Comedy', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/70420.jpg',
    note: '',
  },
  {
    id: 8359,
    tvmazeId: '13526',
    title: 'Nick Nickleby',
    network: 'BBC One',
    startYear: 2012,
    years: '2012',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/46/116737.jpg',
    note: '',
  },
  {
    id: 8360,
    tvmazeId: '1948',
    title: 'Noel Fielding\'s Luxury Comedy',
    network: 'E4',
    startYear: 2012,
    years: '2012–2014',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/27833.jpg',
    note: '',
  },
  {
    id: 8361,
    tvmazeId: '4733',
    title: 'NYC 22',
    network: 'CBS',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/53027.jpg',
    note: '',
  },
  {
    id: 8362,
    tvmazeId: '43211',
    title: 'Oishi High School Battle',
    network: 'YouTube',
    startYear: 2012,
    years: '2012–2014',
    genres: ['Comedy', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/206/516829.jpg',
    note: '',
  },
  {
    id: 8363,
    tvmazeId: '2363',
    title: 'One Night',
    network: 'BBC One',
    startYear: 2012,
    years: '2012',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/12/32145.jpg',
    note: '',
  },
  {
    id: 8364,
    tvmazeId: '9038',
    title: 'Outland',
    network: 'ABC',
    startYear: 2012,
    years: '2012',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/79955.jpg',
    note: '',
  },
  {
    id: 8365,
    tvmazeId: '1161',
    title: 'Parade\'s End',
    network: 'BBC Two',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'War', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17437.jpg',
    note: '',
  },
  {
    id: 8366,
    tvmazeId: '9650',
    title: 'Parents',
    network: 'Sky Showcase',
    startYear: 2012,
    years: '2012',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/83922.jpg',
    note: '',
  },
  {
    id: 8367,
    tvmazeId: '1523',
    title: 'Partners',
    network: 'CBS',
    startYear: 2012,
    years: '2012–2013',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/8/21300.jpg',
    note: '',
  },
  {
    id: 8368,
    tvmazeId: '357',
    title: 'Perception',
    network: 'TNT',
    startYear: 2012,
    years: '2012–2015',
    genres: ['Drama', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/150/376028.jpg',
    note: '',
  },
  {
    id: 8369,
    tvmazeId: '10343',
    title: 'Peter Rabbit',
    network: 'Nick Jr.',
    startYear: 2012,
    years: '2012–2016',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/35/87689.jpg',
    note: '',
  },
  {
    id: 8370,
    tvmazeId: '47862',
    title: 'Plastic Man In...',
    network: 'Cartoon Network',
    startYear: 2012,
    years: '2012–2013',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/255/638938.jpg',
    note: '',
  },
  {
    id: 8371,
    tvmazeId: '4618',
    title: 'Playhouse Presents',
    network: 'Sky Arts',
    startYear: 2012,
    years: '2012–2014',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/52424.jpg',
    note: '',
  },
  {
    id: 8372,
    tvmazeId: '1082',
    title: 'Political Animals',
    network: 'USA Network',
    startYear: 2012,
    years: '2012',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17185.jpg',
    note: '',
  },
  {
    id: 8373,
    tvmazeId: '26766',
    title: 'Pond Life',
    network: 'BBC Doctor Who Webcast',
    startYear: 2012,
    years: '2012',
    genres: ['Comedy', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/105/263634.jpg',
    note: '',
  },
  {
    id: 8374,
    tvmazeId: '4623',
    title: 'Pramface',
    network: 'BBC Three',
    startYear: 2012,
    years: '2012–2014',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/52444.jpg',
    note: '',
  },
  {
    id: 8375,
    tvmazeId: '28592',
    title: 'Preamar',
    network: 'HBO',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/113/284491.jpg',
    note: '',
  },
  {
    id: 8376,
    tvmazeId: '35023',
    title: 'Pretty Dirty Secrets',
    network: 'ABC.com',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/146/366792.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 349, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
