window.pageShows = [
  {
    id: 15145,
    tvmazeId: '62907',
    title: 'TV Playhouse',
    network: 'ITV1',
    startYear: 1955,
    years: '1955–1956',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 15146,
    tvmazeId: '75607',
    title: 'TV Reader\'s Digest',
    network: 'ABC',
    startYear: 1955,
    years: '1955–1956',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/510/1275853.jpg',
    note: '',
  },
  {
    id: 15147,
    tvmazeId: '64160',
    title: 'Adventures of the Falcon',
    network: 'Syndication',
    startYear: 1954,
    years: '1954–1955',
    genres: ['Drama', 'Adventure', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/422/1056613.jpg',
    note: '',
  },
  {
    id: 15148,
    tvmazeId: '9475',
    title: 'Annie Oakley',
    network: 'Syndication',
    startYear: 1954,
    years: '1954–1957',
    genres: ['Drama', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/82989.jpg',
    note: '',
  },
  {
    id: 15149,
    tvmazeId: '42793',
    title: 'Captain Midnight',
    network: 'CBS',
    startYear: 1954,
    years: '1954–1956',
    genres: ['Drama', 'Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/203/508828.jpg',
    note: '',
  },
  {
    id: 15150,
    tvmazeId: '21855',
    title: 'Climax!',
    network: 'CBS',
    startYear: 1954,
    years: '1954–1958',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/78/196829.jpg',
    note: '',
  },
  {
    id: 15151,
    tvmazeId: '48004',
    title: 'Dear Dotty',
    network: 'BBC One',
    startYear: 1954,
    years: '1954',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 15152,
    tvmazeId: '58595',
    title: 'Dear Phoebe',
    network: 'NBC',
    startYear: 1954,
    years: '1954–1955',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/369/924918.jpg',
    note: '',
  },
  {
    id: 15153,
    tvmazeId: '42873',
    title: 'December Bride',
    network: 'CBS',
    startYear: 1954,
    years: '1954–1959',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/204/510122.jpg',
    note: '',
  },
  {
    id: 15154,
    tvmazeId: '67202',
    title: 'Duffy\'s Tavern',
    network: 'Syndication',
    startYear: 1954,
    years: '1954',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 15155,
    tvmazeId: '92032',
    title: 'Fabian of the Yard',
    network: 'BBC One',
    startYear: 1954,
    years: '1954–1956',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/629/1573986.jpg',
    note: '',
  },
  {
    id: 15156,
    tvmazeId: '4537',
    title: 'Father Knows Best',
    network: 'NBC',
    startYear: 1954,
    years: '1954–1960',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/52090.jpg',
    note: '',
  },
  {
    id: 15157,
    tvmazeId: '34934',
    title: 'Flash Gordon',
    network: 'Syndication',
    startYear: 1954,
    years: '1954–1955',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/146/365630.jpg',
    note: '',
  },
  {
    id: 15158,
    tvmazeId: '77360',
    title: 'Inner Sanctum',
    network: 'NBC',
    startYear: 1954,
    years: '1954',
    genres: ['Horror', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 15159,
    tvmazeId: '59881',
    title: 'It\'s a Great Life',
    network: 'NBC',
    startYear: 1954,
    years: '1954–1956',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/392/982376.jpg',
    note: '',
  },
  {
    id: 15160,
    tvmazeId: '4968',
    title: 'Lassie',
    network: 'CBS',
    startYear: 1954,
    years: '1954–1973',
    genres: ['Drama', 'Adventure', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/53983.jpg',
    note: '',
  },
  {
    id: 15161,
    tvmazeId: '18443',
    title: 'Medic',
    network: 'NBC',
    startYear: 1954,
    years: '1954–1956',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/62/157075.jpg',
    note: '',
  },
  {
    id: 15162,
    tvmazeId: '79081',
    title: 'Producers\' Showcase',
    network: 'NBC',
    startYear: 1954,
    years: '1954–1957',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 15163,
    tvmazeId: '26747',
    title: 'Rocky Jones, Space Ranger',
    network: 'Syndication',
    startYear: 1954,
    years: '1954',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/105/263370.jpg',
    note: '',
  },
  {
    id: 15164,
    tvmazeId: '22618',
    title: 'Sherlock Holmes',
    network: 'Syndication',
    startYear: 1954,
    years: '1954–1955',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/544/1362262.jpg',
    note: '',
  },
  {
    id: 15165,
    tvmazeId: '16191',
    title: 'Stories of the Century',
    network: 'Syndication',
    startYear: 1954,
    years: '1954–1955',
    genres: ['Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/54/135238.jpg',
    note: '',
  },
  {
    id: 15166,
    tvmazeId: '21859',
    title: 'Studio 57',
    network: 'Syndication',
    startYear: 1954,
    years: '1954–1957',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/78/196844.jpg',
    note: '',
  },
  {
    id: 15167,
    tvmazeId: '10604',
    title: 'The Adventures of Rin Tin Tin',
    network: 'ABC',
    startYear: 1954,
    years: '1954–1959',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/35/89272.jpg',
    note: '',
  },
  {
    id: 15168,
    tvmazeId: '59921',
    title: 'The Best of Broadway',
    network: 'CBS',
    startYear: 1954,
    years: '1954–1955',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  }
];
window.pageMetadata = {"page": 632, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 824, "cliffhanger": 237, "ended": 13574}};
