window.pageShows = [
  {
    id: 7489,
    tvmazeId: '46',
    title: 'Forever',
    network: 'ABC',
    startYear: 2014,
    years: '2014–2015',
    genres: ['Drama', 'Crime', 'Supernatural'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'ABC cancelled after one season; Henry Morgan\'s immortality origins and Adam\'s identity were unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/0/383.jpg',
    note: '',
  },
  {
    id: 7490,
    tvmazeId: '37971',
    title: 'Frankenstein, MD',
    network: 'YouTube',
    startYear: 2014,
    years: '2014',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/162/406763.jpg',
    note: '',
  },
  {
    id: 7491,
    tvmazeId: '10356',
    title: 'Franklin and Friends',
    network: 'Nick Jr.',
    startYear: 2014,
    years: '2014–2017',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/35/87698.jpg',
    note: '',
  },
  {
    id: 7492,
    tvmazeId: '3542',
    title: 'Friends with Better Lives',
    network: 'CBS',
    startYear: 2014,
    years: '2014',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/146/366918.jpg',
    note: '',
  },
  {
    id: 7493,
    tvmazeId: '105',
    title: 'From Dusk Till Dawn: The Series',
    network: 'El Rey Network',
    startYear: 2014,
    years: '2014–2016',
    genres: ['Action', 'Crime', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/70/176381.jpg',
    note: '',
  },
  {
    id: 7494,
    tvmazeId: '13576',
    title: 'From Here on OUT',
    network: 'Here TV',
    startYear: 2014,
    years: '2014',
    genres: ['Drama', 'Adult'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/46/117160.jpg',
    note: '',
  },
  {
    id: 7495,
    tvmazeId: '13032',
    title: 'From There to Here',
    network: 'BBC One',
    startYear: 2014,
    years: '2014',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/44/111880.jpg',
    note: '',
  },
  {
    id: 7496,
    tvmazeId: '3117',
    title: 'Gaming Show (In My Parents\' Garage)',
    network: 'Disney XD',
    startYear: 2014,
    years: '2014–2016',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/333/834050.jpg',
    note: '',
  },
  {
    id: 7497,
    tvmazeId: '1239',
    title: 'Gang Related',
    network: 'FOX',
    startYear: 2014,
    years: '2014',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/17804.jpg',
    note: '',
  },
  {
    id: 7498,
    tvmazeId: '1383',
    title: 'Garfunkel and Oates',
    network: 'IFC',
    startYear: 2014,
    years: '2014',
    genres: ['Comedy', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/19545.jpg',
    note: '',
  },
  {
    id: 7499,
    tvmazeId: '12229',
    title: 'Gays: The Series',
    network: 'Vimeo',
    startYear: 2014,
    years: '2014–2015',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/41/102975.jpg',
    note: '',
  },
  {
    id: 7500,
    tvmazeId: '9890',
    title: 'Get Ace',
    network: 'Network 10',
    startYear: 2014,
    years: '2014',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/34/85077.jpg',
    note: '',
  },
  {
    id: 7501,
    tvmazeId: '252',
    title: 'Girl Meets World',
    network: 'Disney Channel',
    startYear: 2014,
    years: '2014–2017',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/316/792450.jpg',
    note: '',
  },
  {
    id: 7502,
    tvmazeId: '637',
    title: 'Girlfriends\' Guide to Divorce',
    network: 'Bravo',
    startYear: 2014,
    years: '2014–2018',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/162/405182.jpg',
    note: '',
  },
  {
    id: 7503,
    tvmazeId: '3447',
    title: 'Give Out Girls',
    network: 'Comedy Central',
    startYear: 2014,
    years: '2014',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/45365.jpg',
    note: '',
  },
  {
    id: 7504,
    tvmazeId: '258',
    title: 'Glue',
    network: 'E4',
    startYear: 2014,
    years: '2014',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/118/295401.jpg',
    note: '',
  },
  {
    id: 7505,
    tvmazeId: '4679',
    title: 'God\'s Gift: 14 Days',
    network: 'SBS',
    startYear: 2014,
    years: '2014',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/124/312498.jpg',
    note: '',
  },
  {
    id: 7506,
    tvmazeId: '2228',
    title: 'Gomorra: La Serie',
    network: 'Sky Atlantic',
    startYear: 2014,
    years: '2014–2021',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/290/726024.jpg',
    note: '',
  },
  {
    id: 7507,
    tvmazeId: '4638',
    title: 'Gortimer Gibbon\'s Life on Normal Street',
    network: 'Prime Video',
    startYear: 2014,
    years: '2014–2016',
    genres: ['Drama', 'Mystery', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/167/419276.jpg',
    note: '',
  },
  {
    id: 7508,
    tvmazeId: '11',
    title: 'Gotham',
    network: 'FOX',
    startYear: 2014,
    years: '2014–2019',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/189/474715.jpg',
    note: '',
  },
  {
    id: 7509,
    tvmazeId: '61788',
    title: 'Grace',
    network: 'HBO',
    startYear: 2014,
    years: '2014',
    genres: ['Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/406/1016382.jpg',
    note: '',
  },
  {
    id: 7510,
    tvmazeId: '110',
    title: 'Gracepoint',
    network: 'FOX',
    startYear: 2014,
    years: '2014',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/0/862.jpg',
    note: '',
  },
  {
    id: 7511,
    tvmazeId: '1548',
    title: 'Grantchester',
    network: 'PBS Passport',
    startYear: 2014,
    years: '2014–2026',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/572/1431930.jpg',
    note: '',
  },
  {
    id: 7512,
    tvmazeId: '47900',
    title: 'Green Arrow',
    network: 'Cartoon Network',
    startYear: 2014,
    years: '2014',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/255/639368.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 313, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
