window.pageShows = [
  {
    id: 7177,
    tvmazeId: '19073',
    title: 'Robotomy',
    network: 'Cartoon Network',
    startYear: 2010,
    years: '2010–2011',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/66/165637.jpg',
    note: '',
  },
  {
    id: 7178,
    tvmazeId: '4755',
    title: 'Rock & Chips',
    network: 'BBC One',
    startYear: 2010,
    years: '2010–2011',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/53099.jpg',
    note: '',
  },
  {
    id: 7179,
    tvmazeId: '13432',
    title: 'Roger and Val Have Just Got In',
    network: 'BBC Two',
    startYear: 2010,
    years: '2010–2012',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/46/116166.jpg',
    note: '',
  },
  {
    id: 7180,
    tvmazeId: '4309',
    title: 'Romantically Challenged',
    network: 'ABC',
    startYear: 2010,
    years: '2010',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/51230.jpg',
    note: '',
  },
  {
    id: 7181,
    tvmazeId: '387',
    title: 'Rookie Blue',
    network: 'Global',
    startYear: 2010,
    years: '2010–2015',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/2/5609.jpg',
    note: '',
  },
  {
    id: 7182,
    tvmazeId: '968',
    title: 'Rubicon',
    network: 'AMC',
    startYear: 2010,
    years: '2010',
    genres: ['Drama', 'Thriller', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16431.jpg',
    note: '',
  },
  {
    id: 7183,
    tvmazeId: '42605',
    title: 'Ruby Skye P.I.',
    network: 'YouTube',
    startYear: 2010,
    years: '2010–2012',
    genres: ['Comedy', 'Children', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/203/508024.jpg',
    note: '',
  },
  {
    id: 7184,
    tvmazeId: '2007',
    title: 'Running Wilde',
    network: 'FOX',
    startYear: 2010,
    years: '2010–2011',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/28119.jpg',
    note: '',
  },
  {
    id: 7185,
    tvmazeId: '73608',
    title: 'Sally Bollywood: Super Detective',
    network: 'Seven Network',
    startYear: 2010,
    years: '2010–2014',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/495/1238936.jpg',
    note: '',
  },
  {
    id: 7186,
    tvmazeId: '71595',
    title: 'SciGirls',
    network: 'PBS Kids',
    startYear: 2010,
    years: '2010–2023',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/479/1197814.jpg',
    note: '',
  },
  {
    id: 7187,
    tvmazeId: '2711',
    title: 'Scooby-Doo! Mystery Incorporated',
    network: 'Cartoon Network',
    startYear: 2010,
    years: '2010–2013',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/14/36568.jpg',
    note: '',
  },
  {
    id: 7188,
    tvmazeId: '1688',
    title: 'Scoundrels',
    network: 'ABC',
    startYear: 2010,
    years: '2010',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/9/23627.jpg',
    note: '',
  },
  {
    id: 7189,
    tvmazeId: '27079',
    title: 'Seven Deadly Sins',
    network: 'Lifetime',
    startYear: 2010,
    years: '2010',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/296/740289.jpg',
    note: '',
  },
  {
    id: 7190,
    tvmazeId: '50776',
    title: 'Shadow Island Mysteries',
    network: 'Crave',
    startYear: 2010,
    years: '2010',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/275/689290.jpg',
    note: '',
  },
  {
    id: 7191,
    tvmazeId: '2194',
    title: 'Shake It Up',
    network: 'Disney Channel',
    startYear: 2010,
    years: '2010–2013',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/12/30372.jpg',
    note: '',
  },
  {
    id: 7192,
    tvmazeId: '20849',
    title: 'Sharktopus',
    network: 'Syfy',
    startYear: 2010,
    years: '2010–2015',
    genres: ['Comedy', 'Horror', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/184406.jpg',
    note: '',
  },
  {
    id: 7193,
    tvmazeId: '7172',
    title: 'Shattered',
    network: 'Showcase',
    startYear: 2010,
    years: '2010–2011',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/66992.jpg',
    note: '',
  },
  {
    id: 7194,
    tvmazeId: '335',
    title: 'Sherlock',
    network: 'BBC One',
    startYear: 2010,
    years: '2010–2017',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/171/428042.jpg',
    note: '',
  },
  {
    id: 7195,
    tvmazeId: '14050',
    title: 'Sidekick',
    network: 'Nickelodeon',
    startYear: 2010,
    years: '2010–2018',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/48/120284.jpg',
    note: '',
  },
  {
    id: 7196,
    tvmazeId: '6944',
    title: 'Single Father',
    network: 'BBC One',
    startYear: 2010,
    years: '2010',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/65375.jpg',
    note: '',
  },
  {
    id: 7197,
    tvmazeId: '71626',
    title: 'Skatoony',
    network: 'Cartoon Network',
    startYear: 2010,
    years: '2010–2013',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/479/1198202.jpg',
    note: '',
  },
  {
    id: 7198,
    tvmazeId: '3941',
    title: 'Sons of Tucson',
    network: 'FOX',
    startYear: 2010,
    years: '2010',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/397/994644.jpg',
    note: '',
  },
  {
    id: 7199,
    tvmazeId: '716',
    title: 'Spartacus',
    network: 'STARZ',
    startYear: 2010,
    years: '2010–2013',
    genres: ['Drama', 'Action', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/354/886339.jpg',
    note: '',
  },
  {
    id: 7200,
    tvmazeId: '62091',
    title: 'Spirit Warriors',
    network: 'CBBC',
    startYear: 2010,
    years: '2010',
    genres: ['Drama', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/419/1048363.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 300, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 856, "cliffhanger": 286, "ended": 13542}};
