window.pageShows = [
  {
    id: 5737,
    tvmazeId: '2153',
    title: 'Famous in Love',
    network: 'Freeform.com',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/402/1007090.jpg',
    note: '',
  },
  {
    id: 5738,
    tvmazeId: '43835',
    title: 'FANtasies',
    network: 'fullscreen',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 5739,
    tvmazeId: '23910',
    title: 'Father is Strange',
    network: 'KBS2',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy', 'Family', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/99/249705.jpg',
    note: '',
  },
  {
    id: 5740,
    tvmazeId: '26411',
    title: 'Fazilet Hanım ve Kızları',
    network: 'Star TV',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/104/260069.jpg',
    note: '',
  },
  {
    id: 5741,
    tvmazeId: '28481',
    title: 'Fearless',
    network: 'ITV1',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/114/287223.jpg',
    note: '',
  },
  {
    id: 5742,
    tvmazeId: '16788',
    title: 'Feud',
    network: 'FX',
    startYear: 2017,
    years: '2017–2024',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/500/1251458.jpg',
    note: '',
  },
  {
    id: 5743,
    tvmazeId: '26106',
    title: 'Fi',
    network: 'Puhu TV',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Drama', 'Romance', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/113/284506.jpg',
    note: '',
  },
  {
    id: 5744,
    tvmazeId: '46145',
    title: 'Fifty: The Series',
    network: 'EbonyLife TV',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/591/1479741.jpg',
    note: '',
  },
  {
    id: 5745,
    tvmazeId: '32094',
    title: 'Final Life',
    network: 'Prime Video',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/575/1438867.jpg',
    note: '',
  },
  {
    id: 5746,
    tvmazeId: '29128',
    title: 'five by five',
    network: 'BBC Three',
    startYear: 2017,
    years: '2017',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/116/290580.jpg',
    note: '',
  },
  {
    id: 5747,
    tvmazeId: '26438',
    title: 'Fixer Upper Mystery',
    network: 'Hallmark Mystery',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Drama', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/149/372794.jpg',
    note: '',
  },
  {
    id: 5748,
    tvmazeId: '32524',
    title: 'Flunky\'s Upset',
    network: 'YouTube',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/137/344363.jpg',
    note: '',
  },
  {
    id: 5749,
    tvmazeId: '44099',
    title: 'Fox Tossing',
    network: 'fullscreen',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy', 'History', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/213/532913.jpg',
    note: '',
  },
  {
    id: 5750,
    tvmazeId: '26794',
    title: 'Frankie Drake Mysteries',
    network: 'CBC',
    startYear: 2017,
    years: '2017–2021',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/213/533512.jpg',
    note: '',
  },
  {
    id: 5751,
    tvmazeId: '73323',
    title: 'Frankie Drake Mysteries: A Cold Case',
    network: 'CBC',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 5752,
    tvmazeId: '25764',
    title: 'Free Rein',
    network: 'Netflix',
    startYear: 2017,
    years: '2017–2019',
    genres: ['Drama', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/204/510513.jpg',
    note: '',
  },
  {
    id: 5753,
    tvmazeId: '20003',
    title: 'Freedom Fighters: The Ray',
    network: 'CW Seed',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Action', 'Crime', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/167/418247.jpg',
    note: '',
  },
  {
    id: 5754,
    tvmazeId: '33489',
    title: 'Friday on My Mind',
    network: 'ABC',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/136/341862.jpg',
    note: '',
  },
  {
    id: 5755,
    tvmazeId: '20345',
    title: 'Friends from College',
    network: 'Netflix',
    startYear: 2017,
    years: '2017–2019',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/542/1355491.jpg',
    note: '',
  },
  {
    id: 5756,
    tvmazeId: '56857',
    title: 'From Beyond',
    network: 'Prime Video',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Horror', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/348/872449.jpg',
    note: '',
  },
  {
    id: 5757,
    tvmazeId: '74413',
    title: 'Fruit Ninja: Frenzy Force',
    network: 'YouTube Premium',
    startYear: 2017,
    years: '2017',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/502/1255934.jpg',
    note: '',
  },
  {
    id: 5758,
    tvmazeId: '28986',
    title: 'Fubar Age of Computer',
    network: 'Viceland',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/136/340951.jpg',
    note: '',
  },
  {
    id: 5759,
    tvmazeId: '3022',
    title: 'Future Man',
    network: 'Hulu',
    startYear: 2017,
    years: '2017–2020',
    genres: ['Comedy', 'Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/592/1480203.jpg',
    note: '',
  },
  {
    id: 5760,
    tvmazeId: '64042',
    title: 'Gaki Rock: Asakusa roku-ku ninjo monogatari',
    network: 'Prime Video',
    startYear: 2017,
    years: '2017',
    genres: [],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/422/1055131.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 240, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 398, "cliffhanger": 239, "ended": 15092}};
