window.pageShows = [
  {
    id: 9241,
    tvmazeId: '50025',
    title: 'That Was Then',
    network: 'ABC',
    startYear: 2002,
    years: '2002',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/270/676685.jpg',
    note: '',
  },
  {
    id: 9242,
    tvmazeId: '7457',
    title: 'The Adventures of Jimmy Neutron: Boy Genius',
    network: 'Nickelodeon',
    startYear: 2002,
    years: '2002–2006',
    genres: ['Comedy', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/494/1235083.jpg',
    note: '',
  },
  {
    id: 9243,
    tvmazeId: '8844',
    title: 'The American Embassy',
    network: 'FOX',
    startYear: 2002,
    years: '2002',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/418/1045488.jpg',
    note: '',
  },
  {
    id: 9244,
    tvmazeId: '21148',
    title: 'The Basil Brush Show',
    network: 'CBBC',
    startYear: 2002,
    years: '2002–2007',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/74/186569.jpg',
    note: '',
  },
  {
    id: 9245,
    tvmazeId: '43547',
    title: 'The Best Sex Ever',
    network: 'Cinemax',
    startYear: 2002,
    years: '2002–2003',
    genres: ['Drama', 'Fantasy', 'Adult'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/209/522996.jpg',
    note: '',
  },
  {
    id: 9246,
    tvmazeId: '85674',
    title: 'The Big Impression',
    network: 'BBC One',
    startYear: 2002,
    years: '2002–2004',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/576/1441523.jpg',
    note: '',
  },
  {
    id: 9247,
    tvmazeId: '7786',
    title: 'The Book Group',
    network: 'Channel 4',
    startYear: 2002,
    years: '2002–2003',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/71639.jpg',
    note: '',
  },
  {
    id: 9248,
    tvmazeId: '57247',
    title: 'The Book of Pooh',
    network: 'Disney Channel',
    startYear: 2002,
    years: '2002',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/352/882217.jpg',
    note: '',
  },
  {
    id: 9249,
    tvmazeId: '58490',
    title: 'The Court',
    network: 'ABC',
    startYear: 2002,
    years: '2002',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 9250,
    tvmazeId: '8911',
    title: 'The Cramp Twins',
    network: 'Cartoon Network',
    startYear: 2002,
    years: '2002–2005',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/79091.jpg',
    note: '',
  },
  {
    id: 9251,
    tvmazeId: '940',
    title: 'The Dead Zone',
    network: 'USA Network',
    startYear: 2002,
    years: '2002–2007',
    genres: ['Drama', 'Fantasy', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16191.jpg',
    note: '',
  },
  {
    id: 9252,
    tvmazeId: '8822',
    title: 'The Eleventh Hour',
    network: 'CTV',
    startYear: 2002,
    years: '2002–2005',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/38/96065.jpg',
    note: '',
  },
  {
    id: 9253,
    tvmazeId: '66034',
    title: 'The Estate Agents',
    network: 'Channel 4',
    startYear: 2002,
    years: '2002',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/437/1093146.jpg',
    note: '',
  },
  {
    id: 9254,
    tvmazeId: '1289',
    title: 'The Forsyte Saga',
    network: 'ITV1',
    startYear: 2002,
    years: '2002–2003',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/18425.jpg',
    note: '',
  },
  {
    id: 9255,
    tvmazeId: '20951',
    title: 'The House That Jack Built',
    network: 'BBC One',
    startYear: 2002,
    years: '2002',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/184916.jpg',
    note: '',
  },
  {
    id: 9256,
    tvmazeId: '18450',
    title: 'The Jury',
    network: 'ITV1',
    startYear: 2002,
    years: '2002',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/62/157206.jpg',
    note: '',
  },
  {
    id: 9257,
    tvmazeId: '41678',
    title: 'The Little Polar Bear',
    network: 'KiKa',
    startYear: 2002,
    years: '2002–1995',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/190/477421.jpg',
    note: '',
  },
  {
    id: 9258,
    tvmazeId: '66380',
    title: 'The Random Years',
    network: 'UPN',
    startYear: 2002,
    years: '2002',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 9259,
    tvmazeId: '66379',
    title: 'The Rerun Show',
    network: 'NBC',
    startYear: 2002,
    years: '2002',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/441/1103980.jpg',
    note: '',
  },
  {
    id: 9260,
    tvmazeId: '66413',
    title: 'The Shapies',
    network: 'Nine Network',
    startYear: 2002,
    years: '2002',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/441/1104448.jpg',
    note: '',
  },
  {
    id: 9261,
    tvmazeId: '663',
    title: 'The Shield',
    network: 'FX',
    startYear: 2002,
    years: '2002–2008',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/55/138892.jpg',
    note: '',
  },
  {
    id: 9262,
    tvmazeId: '9541',
    title: 'The Story of Tracy Beaker',
    network: 'BBC One',
    startYear: 2002,
    years: '2002–2005',
    genres: ['Drama', 'Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/398/995494.jpg',
    note: '',
  },
  {
    id: 9263,
    tvmazeId: '14542',
    title: 'The Strip',
    network: 'Three',
    startYear: 2002,
    years: '2002–2003',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/49/123053.jpg',
    note: '',
  },
  {
    id: 9264,
    tvmazeId: '3880',
    title: 'The Twilight Zone',
    network: 'UPN',
    startYear: 2002,
    years: '2002–2003',
    genres: ['Fantasy', 'Horror', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/48680.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 386, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 824, "cliffhanger": 237, "ended": 13574}};
