window.pageShows = [
  {
    id: 7805,
    tvmazeId: '193',
    title: 'Dads',
    network: 'FOX',
    startYear: 2013,
    years: '2013–2014',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/1/2831.jpg',
    note: '',
  },
  {
    id: 7806,
    tvmazeId: '701',
    title: 'Dancing on the Edge',
    network: 'BBC Two',
    startYear: 2013,
    years: '2013',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/15002.jpg',
    note: '',
  },
  {
    id: 7807,
    tvmazeId: '5345',
    title: 'Dani\'s Castle',
    network: 'CBBC',
    startYear: 2013,
    years: '2013–2015',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/55377.jpg',
    note: '',
  },
  {
    id: 7808,
    tvmazeId: '3562',
    title: 'Darknet',
    network: 'Super Channel Fuse',
    startYear: 2013,
    years: '2013–2014',
    genres: ['Fantasy', 'Horror', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/46714.jpg',
    note: '',
  },
  {
    id: 7809,
    tvmazeId: '1705',
    title: 'Dates',
    network: 'Channel 4',
    startYear: 2013,
    years: '2013',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/9/23903.jpg',
    note: '',
  },
  {
    id: 7810,
    tvmazeId: '47882',
    title: 'DC Nation\'s Farm League',
    network: 'Cartoon Network',
    startYear: 2013,
    years: '2013',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/255/639087.jpg',
    note: '',
  },
  {
    id: 7811,
    tvmazeId: '47899',
    title: 'Deadman',
    network: 'Cartoon Network',
    startYear: 2013,
    years: '2013',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/255/639356.jpg',
    note: '',
  },
  {
    id: 7812,
    tvmazeId: '1092',
    title: 'Death Comes to Pemberley',
    network: 'BBC One',
    startYear: 2013,
    years: '2013',
    genres: ['Drama', 'Romance', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17213.jpg',
    note: '',
  },
  {
    id: 7813,
    tvmazeId: '967',
    title: 'Deception',
    network: 'NBC',
    startYear: 2013,
    years: '2013',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'NBC cancelled after one season; the murder conspiracy surrounding the Beaumont family and the Lyritrol drug cover-up were left unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16423.jpg',
    note: '',
  },
  {
    id: 7814,
    tvmazeId: '29363',
    title: 'Deception',
    network: 'Virgin Media One',
    startYear: 2013,
    years: '2013',
    genres: ['Drama'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: '',
    note: '',
  },
  {
    id: 7815,
    tvmazeId: '94',
    title: 'Defiance',
    network: 'Syfy',
    startYear: 2013,
    years: '2013–2015',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Syfy cancelled after three seasons; the alien-human co-existence in future St. Louis was left mid-arc.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/0/700.jpg',
    note: '',
  },
  {
    id: 7816,
    tvmazeId: '10002',
    title: 'Delete',
    network: 'REELZ',
    startYear: 2013,
    years: '2013',
    genres: ['Drama', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/34/85655.jpg',
    note: '',
  },
  {
    id: 7817,
    tvmazeId: '201',
    title: 'Devious Maids',
    network: 'Lifetime',
    startYear: 2013,
    years: '2013–2016',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Lifetime cancelled after four seasons on a cliffhanger; the Marisol storyline and ongoing crimes were unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/40/100562.jpg',
    note: '',
  },
  {
    id: 7818,
    tvmazeId: '15451',
    title: 'Disney Mickey Mouse',
    network: 'Disney Channel',
    startYear: 2013,
    years: '2013–2019',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/52/131045.jpg',
    note: '',
  },
  {
    id: 7819,
    tvmazeId: '1009',
    title: 'Do No Harm',
    network: 'NBC',
    startYear: 2013,
    years: '2013',
    genres: ['Drama', 'Horror', 'Medical'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'NBC cancelled after two episodes mid-story.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16604.jpg',
    note: '',
  },
  {
    id: 7820,
    tvmazeId: '32715',
    title: 'DokiDoki! PreCure',
    network: 'ABC',
    startYear: 2013,
    years: '2013–2014',
    genres: ['Adventure', 'Anime', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/131/328860.jpg',
    note: '',
  },
  {
    id: 7821,
    tvmazeId: '47898',
    title: 'Doom Patrol',
    network: 'Cartoon Network',
    startYear: 2013,
    years: '2013',
    genres: ['Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/255/639342.jpg',
    note: '',
  },
  {
    id: 7822,
    tvmazeId: '31038',
    title: 'Dr. Wareheim',
    network: 'YouTube',
    startYear: 2013,
    years: '2013',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/123/309176.jpg',
    note: '',
  },
  {
    id: 7823,
    tvmazeId: '1382',
    title: 'Dracula',
    network: 'NBC',
    startYear: 2013,
    years: '2013–2014',
    genres: ['Drama', 'Horror'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/19413.jpg',
    note: '',
  },
  {
    id: 7824,
    tvmazeId: '4336',
    title: 'Drifters',
    network: 'E4',
    startYear: 2013,
    years: '2013–2016',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/51430.jpg',
    note: '',
  },
  {
    id: 7825,
    tvmazeId: '12492',
    title: 'Dude, That\'s My Ghost!',
    network: 'Disney XD',
    startYear: 2013,
    years: '2013',
    genres: ['Comedy', 'Children', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/42/106663.jpg',
    note: '',
  },
  {
    id: 7826,
    tvmazeId: '4338',
    title: 'East Los High',
    network: 'Hulu',
    startYear: 2013,
    years: '2013–2017',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/610/1525271.jpg',
    note: '',
  },
  {
    id: 7827,
    tvmazeId: '10868',
    title: 'EastSiders',
    network: 'Vimeo',
    startYear: 2013,
    years: '2013–2019',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/36/91513.jpg',
    note: '',
  },
  {
    id: 7828,
    tvmazeId: '65227',
    title: 'Easy Abby',
    network: 'Revry',
    startYear: 2013,
    years: '2013',
    genres: ['Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/430/1077179.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 326, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
