window.pageShows = [
  {
    id: 15937,
    tvmazeId: '18342',
    title: 'Speed Buggy',
    network: 'CBS',
    startYear: 1973,
    years: '1973',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/62/155963.jpg',
    note: '',
  },
  {
    id: 15938,
    tvmazeId: '10926',
    title: 'Spring and Autumn',
    network: 'ITV1',
    startYear: 1973,
    years: '1973–1976',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/36/91920.jpg',
    note: '',
  },
  {
    id: 15939,
    tvmazeId: '3513',
    title: 'Star Trek: The Animated Series',
    network: 'NBC',
    startYear: 1973,
    years: '1973–1974',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/496/1242393.jpg',
    note: '',
  },
  {
    id: 15940,
    tvmazeId: '20279',
    title: 'Super Friends',
    network: 'ABC',
    startYear: 1973,
    years: '1973',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/252/631018.jpg',
    note: '',
  },
  {
    id: 15941,
    tvmazeId: '79500',
    title: 'Tenafly',
    network: 'NBC',
    startYear: 1973,
    years: '1973–1974',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/535/1337675.jpg',
    note: '',
  },
  {
    id: 15942,
    tvmazeId: '9699',
    title: 'The Addams Family',
    network: 'NBC',
    startYear: 1973,
    years: '1973',
    genres: ['Comedy', 'Family', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/84269.jpg',
    note: '',
  },
  {
    id: 15943,
    tvmazeId: '24368',
    title: 'The Brontës of Haworth',
    network: 'ITV1',
    startYear: 1973,
    years: '1973',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/92/231965.jpg',
    note: '',
  },
  {
    id: 15944,
    tvmazeId: '72212',
    title: 'The Chuck Jones Show',
    network: 'Cartoon Network',
    startYear: 1973,
    years: '1973–1976',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/483/1208808.jpg',
    note: '',
  },
  {
    id: 15945,
    tvmazeId: '34198',
    title: 'The Collaborators',
    network: 'CBC',
    startYear: 1973,
    years: '1973–1974',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/616/1541791.jpg',
    note: '',
  },
  {
    id: 15946,
    tvmazeId: '57554',
    title: 'The Donati Conspiracy',
    network: 'BBC Two',
    startYear: 1973,
    years: '1973',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/356/891611.jpg',
    note: '',
  },
  {
    id: 15947,
    tvmazeId: '10238',
    title: 'The Evil Touch',
    network: 'Nine Network',
    startYear: 1973,
    years: '1973–1974',
    genres: ['Horror', 'Thriller', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/481/1202583.jpg',
    note: '',
  },
  {
    id: 15948,
    tvmazeId: '24659',
    title: 'The Girl with Something Extra',
    network: 'NBC',
    startYear: 1973,
    years: '1973–1974',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/555/1388698.jpg',
    note: '',
  },
  {
    id: 15949,
    tvmazeId: '24975',
    title: 'The Jensen Code',
    network: 'ITV1',
    startYear: 1973,
    years: '1973',
    genres: ['Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/96/240623.jpg',
    note: '',
  },
  {
    id: 15950,
    tvmazeId: '9276',
    title: 'The Magician',
    network: 'NBC',
    startYear: 1973,
    years: '1973–1974',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/346/865537.jpg',
    note: '',
  },
  {
    id: 15951,
    tvmazeId: '10813',
    title: 'The New Perry Mason',
    network: 'CBS',
    startYear: 1973,
    years: '1973–1974',
    genres: ['Drama', 'Crime', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/626/1565557.jpg',
    note: '',
  },
  {
    id: 15952,
    tvmazeId: '49445',
    title: 'The Paul Hogan Show',
    network: 'Nine Network',
    startYear: 1973,
    years: '1973–1975',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/266/666857.jpg',
    note: '',
  },
  {
    id: 15953,
    tvmazeId: '1500',
    title: 'The Six Million Dollar Man',
    network: 'ABC',
    startYear: 1973,
    years: '1973–1978',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/8/21225.jpg',
    note: '',
  },
  {
    id: 15954,
    tvmazeId: '1752',
    title: 'The Starlost',
    network: 'CTV',
    startYear: 1973,
    years: '1973–1974',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/9/24486.jpg',
    note: '',
  },
  {
    id: 15955,
    tvmazeId: '44331',
    title: 'The Swiss Family Robinson',
    network: 'CTV',
    startYear: 1973,
    years: '1973–1974',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/214/536976.jpg',
    note: '',
  },
  {
    id: 15956,
    tvmazeId: '3676',
    title: 'The Tomorrow People',
    network: 'ITV1',
    startYear: 1973,
    years: '1973–1979',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: 'Original UK children\'s sci-fi series ran eight series (1973-1979) and concluded its run.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/47381.jpg',
    note: '',
  },
  {
    id: 15957,
    tvmazeId: '8205',
    title: 'The Wombles',
    network: 'BBC One',
    startYear: 1973,
    years: '1973–1975',
    genres: ['Children', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/394/986807.jpg',
    note: '',
  },
  {
    id: 15958,
    tvmazeId: '4344',
    title: 'The Young and the Restless',
    network: 'CBS',
    startYear: 1973,
    years: '1973–',
    genres: ['Drama', 'Family', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/593/1482522.jpg',
    note: '',
  },
  {
    id: 15959,
    tvmazeId: '74748',
    title: 'Thicker Than Water',
    network: 'ABC',
    startYear: 1973,
    years: '1973',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 15960,
    tvmazeId: '13452',
    title: 'Thriller',
    network: 'ITV1',
    startYear: 1973,
    years: '1973–1976',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/46/116379.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 665, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 295, "ended": 12349}};
