window.pageShows = [
  {
    id: 1465,
    tvmazeId: '63261',
    title: 'Those About to Die',
    network: 'Peacock',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Action', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/527/1319291.jpg',
    note: '',
  },
  {
    id: 1466,
    tvmazeId: '75317',
    title: 'Thou Shalt Not Steal',
    network: 'Stan',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/539/1347810.jpg',
    note: '',
  },
  {
    id: 1467,
    tvmazeId: '67291',
    title: 'Three Women',
    network: 'Stan',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Adult'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/499/1248861.jpg',
    note: '',
  },
  {
    id: 1468,
    tvmazeId: '37926',
    title: 'Time Bandits',
    network: 'Apple TV',
    startYear: 2024,
    years: '2024',
    genres: ['Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/526/1317065.jpg',
    note: '',
  },
  {
    id: 1469,
    tvmazeId: '79568',
    title: 'Tiny Toot checkifcancelled',
    network: 'rtéjr',
    startYear: 2024,
    years: '2024–',
    genres: ['Adventure', 'Children', 'Fantasy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/535/1339049.jpg',
    note: '',
  },
  {
    id: 1470,
    tvmazeId: '74979',
    title: 'Tires',
    network: 'Netflix',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/520/1300772.jpg',
    note: '',
  },
  {
    id: 1471,
    tvmazeId: '78234',
    title: 'Toda Família Tem',
    network: 'Prime Video',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/526/1316239.jpg',
    note: '',
  },
  {
    id: 1472,
    tvmazeId: '77773',
    title: 'Tokyo Swindlers',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/526/1316583.jpg',
    note: '',
  },
  {
    id: 1473,
    tvmazeId: '53166',
    title: 'Tomb Raider: The Legend of Lara Croft',
    network: 'Netflix',
    startYear: 2024,
    years: '2024–2025',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/538/1347261.jpg',
    note: '',
  },
  {
    id: 1474,
    tvmazeId: '74568',
    title: 'Too Good to Be True',
    network: '5',
    startYear: 2024,
    years: '2024–',
    genres: ['Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/503/1259454.jpg',
    note: '',
  },
  {
    id: 1475,
    tvmazeId: '63192',
    title: 'Tracker',
    network: 'CBS',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/591/1479867.jpg',
    note: '',
  },
  {
    id: 1476,
    tvmazeId: '75945',
    title: 'Tree on a Hill',
    network: 'BBC iPlayer',
    startYear: 2024,
    years: '2024–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/512/1281833.jpg',
    note: '',
  },
  {
    id: 1477,
    tvmazeId: '78293',
    title: 'Tribhuvan Mishra CA Topper',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/526/1317052.jpg',
    note: '',
  },
  {
    id: 1478,
    tvmazeId: '91777',
    title: 'True Heiress vs. Fake Queen Bee',
    network: 'Reelshort',
    startYear: 2024,
    years: '2024',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/624/1561132.jpg',
    note: '',
  },
  {
    id: 1479,
    tvmazeId: '90584',
    title: 'True Justice',
    network: 'Hallmark Mystery',
    startYear: 2024,
    years: '2024–',
    genres: ['Crime', 'Mystery', 'Legal'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/616/1540663.jpg',
    note: '',
  },
  {
    id: 1480,
    tvmazeId: '62176',
    title: 'Truelove',
    network: 'Channel 4',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/498/1245054.jpg',
    note: '',
  },
  {
    id: 1481,
    tvmazeId: '79650',
    title: 'Turmschatten',
    network: 'Paramount+',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/536/1340382.jpg',
    note: '',
  },
  {
    id: 1482,
    tvmazeId: '55830',
    title: 'Twilight of the Gods',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Action', 'Adventure', 'Anime', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/532/1332453.jpg',
    note: '',
  },
  {
    id: 1483,
    tvmazeId: '74706',
    title: 'Tyler Perry\'s Beauty in Black',
    network: 'Netflix',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/539/1348219.jpg',
    note: '',
  },
  {
    id: 1484,
    tvmazeId: '74958',
    title: 'Un amore',
    network: 'Sky Atlantic',
    startYear: 2024,
    years: '2024',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/505/1264990.jpg',
    note: '',
  },
  {
    id: 1485,
    tvmazeId: '74808',
    title: 'Uncle Samsik',
    network: 'Disney+',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/519/1298354.jpg',
    note: '',
  },
  {
    id: 1486,
    tvmazeId: '64641',
    title: 'Under the Bridge',
    network: 'Hulu',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/592/1480211.jpg',
    note: '',
  },
  {
    id: 1487,
    tvmazeId: '77572',
    title: 'Une Amie Dévouée',
    network: 'HBO Max',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/535/1339986.jpg',
    note: '',
  },
  {
    id: 1488,
    tvmazeId: '65072',
    title: 'Universal Basic Guys',
    network: 'FOX',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/589/1474469.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 62, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
