window.pageShows = [
  {
    id: 9385,
    tvmazeId: '2991',
    title: 'Taking the Flak',
    network: 'BBC Two',
    startYear: 2009,
    years: '2009',
    genres: ['Drama', 'Comedy', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/16/40837.jpg',
    note: '',
  },
  {
    id: 9386,
    tvmazeId: '7151',
    title: 'Tangle',
    network: 'Showcase',
    startYear: 2009,
    years: '2009–2012',
    genres: ['Drama'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/66924.jpg',
    note: '',
  },
  {
    id: 9387,
    tvmazeId: '22399',
    title: 'Team Epic',
    network: 'Makeful',
    startYear: 2009,
    years: '2009',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/82/205798.jpg',
    note: '',
  },
  {
    id: 9388,
    tvmazeId: '7047',
    title: 'Terminator Salvation: The Machinima Series',
    network: 'Machinima',
    startYear: 2009,
    years: '2009',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/402/1006827.jpg',
    note: '',
  },
  {
    id: 9389,
    tvmazeId: '17838',
    title: 'The Amazing Spiez!',
    network: 'TF1',
    startYear: 2009,
    years: '2009–2010',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/60/150398.jpg',
    note: '',
  },
  {
    id: 9390,
    tvmazeId: '12060',
    title: 'The Annoying Orange',
    network: 'YouTube',
    startYear: 2009,
    years: '2009–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/467/1168089.jpg',
    note: '',
  },
  {
    id: 9391,
    tvmazeId: '15072',
    title: 'The Assistants',
    network: 'TeenNick',
    startYear: 2009,
    years: '2009',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/504/1261971.jpg',
    note: '',
  },
  {
    id: 9392,
    tvmazeId: '71959',
    title: 'The Bannen Way',
    network: 'Crackle',
    startYear: 2009,
    years: '2009–2012',
    genres: ['Comedy', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/481/1203425.jpg',
    note: '',
  },
  {
    id: 9393,
    tvmazeId: '3980',
    title: 'The Beast',
    network: 'A&E',
    startYear: 2009,
    years: '2009',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/49195.jpg',
    note: '',
  },
  {
    id: 9394,
    tvmazeId: '25663',
    title: 'The Beautiful Life: TBL',
    network: 'The CW',
    startYear: 2009,
    years: '2009',
    genres: ['Drama'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/100/250090.jpg',
    note: '',
  },
  {
    id: 9395,
    tvmazeId: '774',
    title: 'The Cleveland Show',
    network: 'FOX',
    startYear: 2009,
    years: '2009–2013',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/58/146119.jpg',
    note: '',
  },
  {
    id: 9396,
    tvmazeId: '31160',
    title: 'The CollegeHumor Show',
    network: 'MTV',
    startYear: 2009,
    years: '2009',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/124/310823.jpg',
    note: '',
  },
  {
    id: 9397,
    tvmazeId: '7147',
    title: 'The Cult',
    network: 'TVNZ 2',
    startYear: 2009,
    years: '2009',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/66915.jpg',
    note: '',
  },
  {
    id: 9398,
    tvmazeId: '9491',
    title: 'The Cut',
    network: 'ABC',
    startYear: 2009,
    years: '2009',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 9399,
    tvmazeId: '16496',
    title: 'The Cut',
    network: 'BBC Two',
    startYear: 2009,
    years: '2009–2010',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/54/137496.jpg',
    note: '',
  },
  {
    id: 9400,
    tvmazeId: '20580',
    title: 'The Dating Guy',
    network: 'Cartoon Network',
    startYear: 2009,
    years: '2009–2010',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/72/181958.jpg',
    note: '',
  },
  {
    id: 9401,
    tvmazeId: '3678',
    title: 'The Day of the Triffids',
    network: 'BBC One',
    startYear: 2009,
    years: '2009',
    genres: ['Drama', 'Fantasy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/47393.jpg',
    note: '',
  },
  {
    id: 9402,
    tvmazeId: '10468',
    title: 'The Diary of Anne Frank',
    network: 'BBC One',
    startYear: 2009,
    years: '2009',
    genres: ['Drama', 'War', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/35/88582.jpg',
    note: '',
  },
  {
    id: 9403,
    tvmazeId: '36773',
    title: 'The Diplomat',
    network: 'ION',
    startYear: 2009,
    years: '2009',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/155/389916.jpg',
    note: '',
  },
  {
    id: 9404,
    tvmazeId: '3839',
    title: 'The Forgotten',
    network: 'ABC',
    startYear: 2009,
    years: '2009–2010',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/48272.jpg',
    note: '',
  },
  {
    id: 9405,
    tvmazeId: '39012',
    title: 'The Foundation',
    network: 'Showcase',
    startYear: 2009,
    years: '2009',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/170/426349.jpg',
    note: '',
  },
  {
    id: 9406,
    tvmazeId: '18007',
    title: 'The Fresh Beat Band',
    network: 'Nick Jr.',
    startYear: 2009,
    years: '2009–2013',
    genres: ['Children', 'Music'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/61/152601.jpg',
    note: '',
  },
  {
    id: 9407,
    tvmazeId: '16574',
    title: 'The Garfield Show',
    network: 'Cartoon Network',
    startYear: 2009,
    years: '2009–2012',
    genres: ['Comedy', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/55/138081.jpg',
    note: '',
  },
  {
    id: 9408,
    tvmazeId: '101',
    title: 'The Good Wife',
    network: 'CBS',
    startYear: 2009,
    years: '2009–2016',
    genres: ['Drama', 'Crime', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/59/148162.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 392, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 295, "ended": 12349}};
