window.pageShows = [
  {
    id: 3053,
    tvmazeId: '59615',
    title: 'A Good Cop',
    network: 'NTD Television',
    startYear: 2021,
    years: '2021–2022',
    genres: ['Drama', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/385/963673.jpg',
    note: '',
  },
  {
    id: 3054,
    tvmazeId: '55840',
    title: 'A Luv Tale',
    network: 'BET+',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/389/974019.jpg',
    note: '',
  },
  {
    id: 3055,
    tvmazeId: '56069',
    title: 'A Tale Dark & Grimm',
    network: 'Netflix',
    startYear: 2021,
    years: '2021',
    genres: ['Comedy', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/364/910217.jpg',
    note: '',
  },
  {
    id: 3056,
    tvmazeId: '54074',
    title: 'A Very British Scandal',
    network: 'BBC iPlayer',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/385/964670.jpg',
    note: '',
  },
  {
    id: 3057,
    tvmazeId: '55350',
    title: 'Abbott Elementary',
    network: 'ABC',
    startYear: 2021,
    years: '2021–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/586/1467109.jpg',
    note: '',
  },
  {
    id: 3058,
    tvmazeId: '53615',
    title: 'Abla Fahita: Drama Queen',
    network: 'Netflix',
    startYear: 2021,
    years: '2021',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/297/742560.jpg',
    note: '',
  },
  {
    id: 3059,
    tvmazeId: '62535',
    title: 'Action Royale',
    network: 'Snapchat',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Action'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/413/1032570.jpg',
    note: '',
  },
  {
    id: 3060,
    tvmazeId: '53330',
    title: 'Ada Twist, Scientist',
    network: 'Netflix',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Comedy', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/458/1145896.jpg',
    note: '',
  },
  {
    id: 3061,
    tvmazeId: '56865',
    title: 'Adulting',
    network: 'Viddsee',
    startYear: 2021,
    years: '2021',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 3062,
    tvmazeId: '57801',
    title: 'Adventure Beast',
    network: 'Netflix',
    startYear: 2021,
    years: '2021',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/368/921376.jpg',
    note: '',
  },
  {
    id: 3063,
    tvmazeId: '49489',
    title: 'Aftertaste',
    network: 'ABC iview',
    startYear: 2021,
    years: '2021–2022',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/294/737054.jpg',
    note: '',
  },
  {
    id: 3064,
    tvmazeId: '83249',
    title: 'Akedo: Ultimate Arcade Warriors',
    network: 'YouTube',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Action', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/559/1399617.jpg',
    note: '',
  },
  {
    id: 3065,
    tvmazeId: '69266',
    title: 'Akkad Bakkad Rafu Chakkar',
    network: 'Prime Video',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/464/1162345.jpg',
    note: '',
  },
  {
    id: 3066,
    tvmazeId: '50906',
    title: 'All My Friends Are Racist',
    network: 'ABC',
    startYear: 2021,
    years: '2021',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/407/1017758.jpg',
    note: '',
  },
  {
    id: 3067,
    tvmazeId: '57465',
    title: 'All the Queen\'s Men',
    network: 'Paramount+',
    startYear: 2021,
    years: '2021–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/576/1441770.jpg',
    note: '',
  },
  {
    id: 3068,
    tvmazeId: '71651',
    title: 'Alma\'s Way',
    network: 'PBS Kids',
    startYear: 2021,
    years: '2021–',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/479/1198376.jpg',
    note: '',
  },
  {
    id: 3069,
    tvmazeId: '58752',
    title: 'Alparslan: Büyük Selçuklu',
    network: 'TRT1',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Action', 'War', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/429/1072783.jpg',
    note: '',
  },
  {
    id: 3070,
    tvmazeId: '53513',
    title: 'Alpha Betas',
    network: 'YouTube',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Comedy', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/296/740926.jpg',
    note: '',
  },
  {
    id: 3071,
    tvmazeId: '56710',
    title: 'AlRawabi School for Girls',
    network: 'Netflix',
    startYear: 2021,
    years: '2021–2024',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/512/1281564.jpg',
    note: '',
  },
  {
    id: 3072,
    tvmazeId: '68646',
    title: 'Amarres',
    network: 'HBO Max',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/460/1150676.jpg',
    note: '',
  },
  {
    id: 3073,
    tvmazeId: '49265',
    title: 'Amazing Grace',
    network: 'Nine Network',
    startYear: 2021,
    years: '2021',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/298/746556.jpg',
    note: '',
  },
  {
    id: 3074,
    tvmazeId: '59685',
    title: 'Ambient Swim',
    network: 'HBO Max',
    startYear: 2021,
    years: '2021–2023',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/385/964758.jpg',
    note: '',
  },
  {
    id: 3075,
    tvmazeId: '78514',
    title: 'Amelia Parker',
    network: 'Super Channel Heart & Home',
    startYear: 2021,
    years: '2021',
    genres: ['Comedy', 'Family'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/528/1320441.jpg',
    note: '',
  },
  {
    id: 3076,
    tvmazeId: '53264',
    title: 'American Auto',
    network: 'NBC',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/442/1107201.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 128, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
