window.pageShows = [
  {
    id: 17305,
    tvmazeId: '21883',
    title: 'Studio One',
    network: 'CBS',
    startYear: 1948,
    years: '1948–1958',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/78/197261.jpg',
    note: '',
  },
  {
    id: 17306,
    tvmazeId: '66697',
    title: 'The Ford Television Theatre',
    network: 'CBS',
    startYear: 1948,
    years: '1948–1951',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 17307,
    tvmazeId: '32008',
    title: 'The Philco Television Playhouse',
    network: 'NBC',
    startYear: 1948,
    years: '1948–1955',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/128/320010.jpg',
    note: '',
  },
  {
    id: 17308,
    tvmazeId: '14394',
    title: 'Kraft Television Theatre',
    network: 'NBC',
    startYear: 1947,
    years: '1947–1958',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/48/122359.jpg',
    note: '',
  },
  {
    id: 17309,
    tvmazeId: '17921',
    title: 'Lights Out',
    network: 'NBC',
    startYear: 1946,
    years: '1946–1972',
    genres: ['Horror', 'Science-Fiction', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/60/151287.jpg',
    note: '',
  },
  {
    id: 17310,
    tvmazeId: '12459',
    title: 'The Heckle and Jeckle Show',
    network: 'CBS',
    startYear: 1946,
    years: '1946–1966',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/42/106368.jpg',
    note: '',
  },
  {
    id: 17311,
    tvmazeId: '17798',
    title: 'Paramount - Famous Studios Cartoons 1943 - 1967',
    network: 'Cartoon Network',
    startYear: 1943,
    years: '1943–1967',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/60/150243.jpg',
    note: '',
  },
  {
    id: 17312,
    tvmazeId: '22479',
    title: 'Dr. Seuss',
    network: 'CBS',
    startYear: 1942,
    years: '1942–1995',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/82/207102.jpg',
    note: '',
  },
  {
    id: 17313,
    tvmazeId: '6496',
    title: 'Popeye',
    network: 'Cartoon Network',
    startYear: 1933,
    years: '1933–1961',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/24/61882.jpg',
    note: '',
  },
  {
    id: 17314,
    tvmazeId: '34953',
    title: 'Betty Boop',
    network: 'Syndication',
    startYear: 1930,
    years: '1930–1939',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/146/365880.jpg',
    note: '',
  },
  {
    id: 17315,
    tvmazeId: '4533',
    title: 'Looney Tunes',
    network: 'ABC',
    startYear: 1929,
    years: '1929–2014',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/629/1573702.jpg',
    note: '',
  },
  {
    id: 17316,
    tvmazeId: '27058',
    title: 'The Little Rascals',
    network: 'Syndication',
    startYear: 1922,
    years: '1922–1944',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/106/267298.jpg',
    note: '',
  },
];
];
];
window.pageMetadata = {"page": 722, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
