window.pageShows = [
  {
    id: 4777,
    tvmazeId: '23699',
    title: 'Marvel Funko Shorts',
    network: 'YouTube',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/89/222590.jpg',
    note: '',
  },
  {
    id: 4778,
    tvmazeId: '23312',
    title: 'Marvel Video Comics',
    network: 'Disney XD',
    startYear: 2016,
    years: '2016',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/263/659509.jpg',
    note: '',
  },
  {
    id: 4779,
    tvmazeId: '16281',
    title: 'Marvel\'s Agents of S.H.I.E.L.D.: Academy',
    network: 'ABC.com',
    startYear: 2016,
    years: '2016',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/54/135729.jpg',
    note: '',
  },
  {
    id: 4780,
    tvmazeId: '23460',
    title: 'Marvel\'s Agents of S.H.I.E.L.D.: Slingshot',
    network: 'ABC.com',
    startYear: 2016,
    years: '2016',
    genres: ['Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/89/222865.jpg',
    note: '',
  },
  {
    id: 4781,
    tvmazeId: '2174',
    title: 'Marvel\'s Luke Cage',
    network: 'Netflix',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Action', 'Crime', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/155/389198.jpg',
    note: '',
  },
  {
    id: 4782,
    tvmazeId: '19625',
    title: 'Mary + Jane',
    network: 'MTV',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/72/181353.jpg',
    note: '',
  },
  {
    id: 4783,
    tvmazeId: '12402',
    title: 'MECH-X4',
    network: 'Disney XD',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Comedy', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/152/382402.jpg',
    note: '',
  },
  {
    id: 4784,
    tvmazeId: '18999',
    title: 'Medici',
    network: 'Rai 1',
    startYear: 2016,
    years: '2016–2019',
    genres: ['Drama', 'Mystery', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/231/578528.jpg',
    note: '',
  },
  {
    id: 4785,
    tvmazeId: '21401',
    title: 'MegaBots',
    network: 'YouTube',
    startYear: 2016,
    years: '2016–2017',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 4786,
    tvmazeId: '2758',
    title: 'Mercy Street',
    network: 'PBS',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Drama', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/50132.jpg',
    note: '',
  },
  {
    id: 4787,
    tvmazeId: '22135',
    title: 'Midnight Sun',
    network: 'SVT1',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/143/359824.jpg',
    note: '',
  },
  {
    id: 4788,
    tvmazeId: '54586',
    title: 'Midtown',
    network: 'Prime Video',
    startYear: 2016,
    years: '2016',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/305/764511.jpg',
    note: '',
  },
  {
    id: 4789,
    tvmazeId: '17321',
    title: 'Million Dollar Extreme Presents: World Peace',
    network: 'Adult Swim',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/112/280096.jpg',
    note: '',
  },
  {
    id: 4790,
    tvmazeId: '20921',
    title: 'Milo Murphy\'s Law',
    network: 'Disney Channel',
    startYear: 2016,
    years: '2016–2019',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/184748.jpg',
    note: '',
  },
  {
    id: 4791,
    tvmazeId: '15657',
    title: 'Minnie\'s Fashion Challenge',
    network: 'Disney Channel',
    startYear: 2016,
    years: '2016',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 4792,
    tvmazeId: '25992',
    title: 'Miss 2059',
    network: 'go90',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Comedy', 'Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/402/1007099.jpg',
    note: '',
  },
  {
    id: 4793,
    tvmazeId: '20911',
    title: 'Morgana Robinson\'s The Agency',
    network: 'BBC Two',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/78/196114.jpg',
    note: '',
  },
  {
    id: 4794,
    tvmazeId: '32680',
    title: 'Motherland',
    network: 'BBC One',
    startYear: 2016,
    years: '2016–2022',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/396/990773.jpg',
    note: '',
  },
  {
    id: 4795,
    tvmazeId: '28918',
    title: 'Mr. Student Body President',
    network: 'go90',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/402/1007111.jpg',
    note: '',
  },
  {
    id: 4796,
    tvmazeId: '8698',
    title: 'Mum',
    network: 'BBC Two',
    startYear: 2016,
    years: '2016–2019',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/126/315950.jpg',
    note: '',
  },
  {
    id: 4797,
    tvmazeId: '52128',
    title: 'Music & Murder',
    network: 'Prime Video',
    startYear: 2016,
    years: '2016–',
    genres: ['Drama', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/285/713701.jpg',
    note: '',
  },
  {
    id: 4798,
    tvmazeId: '52899',
    title: 'My 90-Year-Old Roommate',
    network: 'CBC Comedy',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/292/731427.jpg',
    note: '',
  },
  {
    id: 4799,
    tvmazeId: '6913',
    title: 'My Mother and Other Strangers',
    network: 'RTÉ ONE',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'War', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/85/213362.jpg',
    note: '',
  },
  {
    id: 4800,
    tvmazeId: '29039',
    title: 'Mystery Files',
    network: 'TVO',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Children', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/115/289352.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 200, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 670, "cliffhanger": 0, "ended": 13760}};
