window.pageShows = [
  {
    id: 10633,
    tvmazeId: '15544',
    title: 'Στο Παρά 5',
    network: 'MEGA Channel',
    startYear: 2005,
    years: '2005–2007',
    genres: ['Drama', 'Comedy', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/52/131848.jpg',
    note: '',
  },
  {
    id: 10634,
    tvmazeId: '20415',
    title: '10.5',
    network: 'NBC',
    startYear: 2004,
    years: '2004',
    genres: ['Drama', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/72/180526.jpg',
    note: '',
  },
  {
    id: 10635,
    tvmazeId: '33379',
    title: '11 Somerset',
    network: 'CTV 2',
    startYear: 2004,
    years: '2004',
    genres: ['Adventure', 'Mystery', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/135/338132.jpg',
    note: '',
  },
  {
    id: 10636,
    tvmazeId: '20995',
    title: '15/Love',
    network: 'YTV',
    startYear: 2004,
    years: '2004–2006',
    genres: ['Drama', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/74/185267.jpg',
    note: '',
  },
  {
    id: 10637,
    tvmazeId: '8882',
    title: '55 Degrees North',
    network: 'BBC One',
    startYear: 2004,
    years: '2004–2005',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/78516.jpg',
    note: '',
  },
  {
    id: 10638,
    tvmazeId: '1759',
    title: '5ive Days to Midnight',
    network: 'Syfy',
    startYear: 2004,
    years: '2004',
    genres: ['Drama', 'Science-Fiction', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/9/24594.jpg',
    note: '',
  },
  {
    id: 10639,
    tvmazeId: '17994',
    title: '6Teen',
    network: 'Cartoon Network',
    startYear: 2004,
    years: '2004–2010',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/61/152570.jpg',
    note: '',
  },
  {
    id: 10640,
    tvmazeId: '36291',
    title: 'A Thing Called Love',
    network: 'BBC One',
    startYear: 2004,
    years: '2004',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/153/383323.jpg',
    note: '',
  },
  {
    id: 10641,
    tvmazeId: '8584',
    title: 'Achar!',
    network: 'Channel 5',
    startYear: 2004,
    years: '2004–2005',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/30/76366.jpg',
    note: '',
  },
  {
    id: 10642,
    tvmazeId: '882',
    title: 'Agatha Christie\'s Marple',
    network: 'ITV1',
    startYear: 2004,
    years: '2004–2013',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/15975.jpg',
    note: '',
  },
  {
    id: 10643,
    tvmazeId: '45633',
    title: 'Amnesia',
    network: 'ITV1',
    startYear: 2004,
    years: '2004',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/233/584590.jpg',
    note: '',
  },
  {
    id: 10644,
    tvmazeId: '84711',
    title: 'An American Girl',
    network: 'The WB',
    startYear: 2004,
    years: '2004–2006',
    genres: ['Children', 'Family', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/569/1422652.jpg',
    note: '',
  },
  {
    id: 10645,
    tvmazeId: '18462',
    title: 'Atomic Betty',
    network: 'Cartoon Network',
    startYear: 2004,
    years: '2004–2008',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/62/157386.jpg',
    note: '',
  },
  {
    id: 10646,
    tvmazeId: '40022',
    title: 'Ban This Filth',
    network: 'Channel 4',
    startYear: 2004,
    years: '2004',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 10647,
    tvmazeId: '20724',
    title: 'Black Tie Nights',
    network: 'Cinemax',
    startYear: 2004,
    years: '2004',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/183202.jpg',
    note: '',
  },
  {
    id: 10648,
    tvmazeId: '6925',
    title: 'Blackpool',
    network: 'BBC One',
    startYear: 2004,
    years: '2004',
    genres: ['Drama', 'Comedy', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/65165.jpg',
    note: '',
  },
  {
    id: 10649,
    tvmazeId: '36497',
    title: 'Blue\'s Room',
    network: 'Nick Jr.',
    startYear: 2004,
    years: '2004–2007',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/154/385765.jpg',
    note: '',
  },
  {
    id: 10650,
    tvmazeId: '10989',
    title: 'Bodies',
    network: 'BBC Three',
    startYear: 2004,
    years: '2004–2005',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/36/92340.jpg',
    note: '',
  },
  {
    id: 10651,
    tvmazeId: '598',
    title: 'Boston Legal',
    network: 'ABC',
    startYear: 2004,
    years: '2004–2008',
    genres: ['Drama', 'Comedy', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/4/12026.jpg',
    note: '',
  },
  {
    id: 10652,
    tvmazeId: '18002',
    title: 'Brandy & Mr. Whiskers',
    network: 'Disney Channel',
    startYear: 2004,
    years: '2004–2006',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/61/152592.jpg',
    note: '',
  },
  {
    id: 10653,
    tvmazeId: '19845',
    title: 'Bro\'Town',
    network: 'Three',
    startYear: 2004,
    years: '2004–2009',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/87/219574.jpg',
    note: '',
  },
  {
    id: 10654,
    tvmazeId: '28696',
    title: 'Broken Saints',
    network: 'BrokenSaints.com',
    startYear: 2004,
    years: '2004',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/114/285961.jpg',
    note: '',
  },
  {
    id: 10655,
    tvmazeId: '33008',
    title: 'Carrie and Barry',
    network: 'BBC One',
    startYear: 2004,
    years: '2004–2005',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/133/333190.jpg',
    note: '',
  },
  {
    id: 10656,
    tvmazeId: '33054',
    title: 'Category 6: Day of Destruction',
    network: 'CBS',
    startYear: 2004,
    years: '2004',
    genres: ['Drama', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/399/998234.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 444, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
