window.pageShows = [
  {
    id: 193,
    tvmazeId: '86528',
    title: 'Cartoonified! With Phineas and Ferb',
    network: 'Disney Channel',
    startYear: 2025,
    years: '2025–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/583/1457571.jpg',
    note: '',
  },
  {
    id: 194,
    tvmazeId: '74865',
    title: 'Chad Powers',
    network: 'Hulu',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy', 'Sports'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/586/1467302.jpg',
    note: '',
  },
  {
    id: 195,
    tvmazeId: '61439',
    title: 'Chief of War',
    network: 'Apple TV',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/581/1454407.jpg',
    note: '',
  },
  {
    id: 196,
    tvmazeId: '45860',
    title: 'Clean Slate',
    network: 'Prime Video',
    startYear: 2025,
    years: '2025',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/552/1381557.jpg',
    note: '',
  },
  {
    id: 197,
    tvmazeId: '68761',
    title: 'Code of Silence',
    network: 'ITVX',
    startYear: 2025,
    years: '2025–',
    genres: ['Crime', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/569/1422836.jpg',
    note: '',
  },
  {
    id: 198,
    tvmazeId: '78091',
    title: 'Coldwater',
    network: 'ITVX',
    startYear: 2025,
    years: '2025–',
    genres: ['Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/587/1469225.jpg',
    note: '',
  },
  {
    id: 199,
    tvmazeId: '69327',
    title: 'Common Side Effects',
    network: 'Adult Swim',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Comedy', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/553/1384654.jpg',
    note: '',
  },
  {
    id: 200,
    tvmazeId: '81530',
    title: 'Conspirators',
    network: 'ALLBLK',
    startYear: 2025,
    years: '2025–',
    genres: ['Thriller', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/548/1371690.jpg',
    note: '',
  },
  {
    id: 201,
    tvmazeId: '86070',
    title: 'Cooper & Fry',
    network: '5',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/598/1495799.jpg',
    note: '',
  },
  {
    id: 202,
    tvmazeId: '77625',
    title: 'Countdown',
    network: 'Prime Video',
    startYear: 2025,
    years: '2025',
    genres: ['Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/571/1427583.jpg',
    note: '',
  },
  {
    id: 203,
    tvmazeId: '74214',
    title: 'Crongton',
    network: 'BBC iPlayer',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Comedy', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/560/1402286.jpg',
    note: '',
  },
  {
    id: 204,
    tvmazeId: '86764',
    title: 'Crossroad Springs',
    network: 'Great American Pure Flix',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Family', 'Western'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/584/1462036.jpg',
    note: '',
  },
  {
    id: 205,
    tvmazeId: '76748',
    title: 'Crutch',
    network: 'Paramount+',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/594/1487342.jpg',
    note: '',
  },
  {
    id: 206,
    tvmazeId: '82098',
    title: 'Culpables: London',
    network: 'Prime Video',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/629/1573442.jpg',
    note: '',
  },
  {
    id: 207,
    tvmazeId: '63234',
    title: 'Daredevil: Born Again',
    network: 'Disney+',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Action', 'Science-Fiction'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/616/1540605.jpg',
    note: '',
  },
  {
    id: 208,
    tvmazeId: '85682',
    title: 'Dead Ahead',
    network: 'TVNZ+',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Comedy', 'Supernatural'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/576/1441512.jpg',
    note: '',
  },
  {
    id: 209,
    tvmazeId: '74416',
    title: 'Death by Lightning',
    network: 'Netflix',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/596/1491705.jpg',
    note: '',
  },
  {
    id: 210,
    tvmazeId: '84670',
    title: 'Death Valley',
    network: 'BBC iPlayer',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/625/1563749.jpg',
    note: '',
  },
  {
    id: 211,
    tvmazeId: '68689',
    title: 'Deli Boys',
    network: 'Hulu',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/626/1567474.jpg',
    note: '',
  },
  {
    id: 212,
    tvmazeId: '85841',
    title: 'Demascus',
    network: 'Tubi',
    startYear: 2025,
    years: '2025',
    genres: ['Comedy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/583/1458408.jpg',
    note: '',
  },
  {
    id: 213,
    tvmazeId: '68408',
    title: 'Dept. Q',
    network: 'Netflix',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/571/1427771.jpg',
    note: '',
  },
  {
    id: 214,
    tvmazeId: '74669',
    title: 'Devil in Disguise: John Wayne Gacy',
    network: 'Peacock',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Crime', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/592/1482499.jpg',
    note: '',
  },
  {
    id: 215,
    tvmazeId: '71529',
    title: 'Devil May Cry',
    network: 'Netflix',
    startYear: 2025,
    years: '2025–',
    genres: ['Action', 'Fantasy', 'Horror'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/555/1389167.jpg',
    note: '',
  },
  {
    id: 216,
    tvmazeId: '86591',
    title: 'Dexter Procter: The 10-Year-Old Doctor',
    network: 'BBC iPlayer',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy', 'Children', 'Medical'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/600/1500053.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 9, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 334, "cliffhanger": 235, "ended": 13701}};
