window.pageShows = [
  {
    id: 8569,
    tvmazeId: '8339',
    title: 'Warehouse 13: Grand Designs',
    network: 'Syfy.com',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Comedy', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/30/75028.jpg',
    note: '',
  },
  {
    id: 8570,
    tvmazeId: '35890',
    title: 'Watch with Mother',
    network: 'YouTube',
    startYear: 2012,
    years: '2012',
    genres: ['Comedy', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/151/379996.jpg',
    note: '',
  },
  {
    id: 8571,
    tvmazeId: '4494',
    title: 'Wedding Band',
    network: 'TBS',
    startYear: 2012,
    years: '2012–2013',
    genres: ['Drama', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/56/141209.jpg',
    note: '',
  },
  {
    id: 8572,
    tvmazeId: '8570',
    title: 'Where the Bears Are',
    network: 'YouTube',
    startYear: 2012,
    years: '2012–2018',
    genres: ['Comedy', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/30/76280.jpg',
    note: '',
  },
  {
    id: 8573,
    tvmazeId: '14676',
    title: 'White Heat',
    network: 'BBC Two',
    startYear: 2012,
    years: '2012',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/49/124235.jpg',
    note: '',
  },
  {
    id: 8574,
    tvmazeId: '1353',
    title: 'Wild Grinders',
    network: 'Nicktoons',
    startYear: 2012,
    years: '2012–2015',
    genres: ['Comedy', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/18661.jpg',
    note: '',
  },
  {
    id: 8575,
    tvmazeId: '30499',
    title: 'Wisp',
    network: 'Prime Video',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/120/301717.jpg',
    note: '',
  },
  {
    id: 8576,
    tvmazeId: '369',
    title: 'Wizards vs Aliens',
    network: 'CBBC',
    startYear: 2012,
    years: '2012–2014',
    genres: ['Fantasy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/2/5507.jpg',
    note: '',
  },
  {
    id: 8577,
    tvmazeId: '1300',
    title: 'Wolfblood',
    network: 'CBBC',
    startYear: 2012,
    years: '2012–2017',
    genres: ['Drama', 'Action', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/18459.jpg',
    note: '',
  },
  {
    id: 8578,
    tvmazeId: '8440',
    title: 'Wolfpack of Reseda',
    network: 'FOX',
    startYear: 2012,
    years: '2012',
    genres: ['Comedy', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/30/75357.jpg',
    note: '',
  },
  {
    id: 8579,
    tvmazeId: '9896',
    title: 'Woodley',
    network: 'ABC',
    startYear: 2012,
    years: '2012',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/34/85148.jpg',
    note: '',
  },
  {
    id: 8580,
    tvmazeId: '22230',
    title: 'Woolly and Tig',
    network: 'CBeebies',
    startYear: 2012,
    years: '2012–2013',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/81/203392.jpg',
    note: '',
  },
  {
    id: 8581,
    tvmazeId: '4893',
    title: 'Work It',
    network: 'ABC',
    startYear: 2012,
    years: '2012',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/53533.jpg',
    note: '',
  },
  {
    id: 8582,
    tvmazeId: '6956',
    title: 'WorkinGirls',
    network: 'Canal+',
    startYear: 2012,
    years: '2012–2016',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/65428.jpg',
    note: '',
  },
  {
    id: 8583,
    tvmazeId: '1041',
    title: 'World Without End',
    network: 'Showcase',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Romance', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16908.jpg',
    note: '',
  },
  {
    id: 8584,
    tvmazeId: '4398',
    title: '¡Rob!',
    network: 'CBS',
    startYear: 2012,
    years: '2012',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/51697.jpg',
    note: '',
  },
  {
    id: 8585,
    tvmazeId: '5189',
    title: 'Восьмидесятые',
    network: 'СТС',
    startYear: 2012,
    years: '2012–2016',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/257/644160.jpg',
    note: '',
  },
  {
    id: 8586,
    tvmazeId: '3353',
    title: 'Кухня',
    network: 'СТС',
    startYear: 2012,
    years: '2012–2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/17/44266.jpg',
    note: '',
  },
  {
    id: 8587,
    tvmazeId: '5176',
    title: 'Пока цветёт папоротник',
    network: 'СТС',
    startYear: 2012,
    years: '2012–2019',
    genres: ['Comedy', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/54640.jpg',
    note: '',
  },
  {
    id: 8588,
    tvmazeId: '124',
    title: '2 Broke Girls',
    network: 'CBS',
    startYear: 2011,
    years: '2011–2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/63/158548.jpg',
    note: '',
  },
  {
    id: 8589,
    tvmazeId: '8903',
    title: '32 Brinkburn Street',
    network: 'BBC One',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/78992.jpg',
    note: '',
  },
  {
    id: 8590,
    tvmazeId: '4649',
    title: '49 Days',
    network: 'SBS',
    startYear: 2011,
    years: '2011',
    genres: ['Drama', 'Fantasy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/52625.jpg',
    note: '',
  },
  {
    id: 8591,
    tvmazeId: '65007',
    title: 'A Fairly Odd Movie',
    network: 'Nickelodeon',
    startYear: 2011,
    years: '2011–2014',
    genres: ['Comedy', 'Children', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/429/1074057.jpg',
    note: '',
  },
  {
    id: 8592,
    tvmazeId: '422',
    title: 'A Gifted Man',
    network: 'CBS',
    startYear: 2011,
    years: '2011–2012',
    genres: ['Drama', 'Fantasy', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/2/7317.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 358, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
