window.pageShows = [
  {
    id: 9505,
    tvmazeId: '7422',
    title: 'City of Vice',
    network: 'Channel 4',
    startYear: 2008,
    years: '2008',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/68323.jpg',
    note: '',
  },
  {
    id: 9506,
    tvmazeId: '58435',
    title: 'Click & Clack\'s As the Wrench Turns',
    network: 'PBS',
    startYear: 2008,
    years: '2008',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/367/919843.jpg',
    note: '',
  },
  {
    id: 9507,
    tvmazeId: '1126',
    title: 'Clone',
    network: 'BBC Three',
    startYear: 2008,
    years: '2008',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17273.jpg',
    note: '',
  },
  {
    id: 9508,
    tvmazeId: '8422',
    title: 'Comanche Moon',
    network: 'CBS',
    startYear: 2008,
    years: '2008',
    genres: ['Drama', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/30/75318.jpg',
    note: '',
  },
  {
    id: 9509,
    tvmazeId: '26816',
    title: 'Coming of Age',
    network: 'BBC Three',
    startYear: 2008,
    years: '2008–2011',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/232/580231.jpg',
    note: '',
  },
  {
    id: 9510,
    tvmazeId: '1463',
    title: 'Crash',
    network: 'STARZ',
    startYear: 2008,
    years: '2008–2009',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/8/21072.jpg',
    note: '',
  },
  {
    id: 9511,
    tvmazeId: '3552',
    title: 'Criminal Justice',
    network: 'BBC One',
    startYear: 2008,
    years: '2008–2009',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/46688.jpg',
    note: '',
  },
  {
    id: 9512,
    tvmazeId: '7437',
    title: 'Crooked House',
    network: 'BBC Four',
    startYear: 2008,
    years: '2008',
    genres: ['Drama', 'Horror', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/68416.jpg',
    note: '',
  },
  {
    id: 9513,
    tvmazeId: '1465',
    title: 'Crusoe',
    network: 'NBC',
    startYear: 2008,
    years: '2008–2009',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/8/21082.jpg',
    note: '',
  },
  {
    id: 9514,
    tvmazeId: '15415',
    title: 'Dani\'s House',
    network: 'CBBC',
    startYear: 2008,
    years: '2008–2012',
    genres: ['Drama', 'Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/52/130916.jpg',
    note: '',
  },
  {
    id: 9515,
    tvmazeId: '476',
    title: 'Dead Set',
    network: 'E4',
    startYear: 2008,
    years: '2008',
    genres: ['Comedy', 'Fantasy', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/501/1253505.jpg',
    note: '',
  },
  {
    id: 9516,
    tvmazeId: '72889',
    title: 'Dex Hamilton: Alien Entomologist',
    network: 'CBC',
    startYear: 2008,
    years: '2008–2009',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/488/1221117.jpg',
    note: '',
  },
  {
    id: 9517,
    tvmazeId: '3998',
    title: 'Do Not Disturb',
    network: 'FOX',
    startYear: 2008,
    years: '2008',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/49278.jpg',
    note: '',
  },
  {
    id: 9518,
    tvmazeId: '63654',
    title: 'Dork Hunters from Outer Space',
    network: 'ITV1',
    startYear: 2008,
    years: '2008',
    genres: ['Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/419/1048808.jpg',
    note: '',
  },
  {
    id: 9519,
    tvmazeId: '37934',
    title: 'Dorm Life',
    network: 'Hulu',
    startYear: 2008,
    years: '2008–2009',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/162/406426.jpg',
    note: '',
  },
  {
    id: 9520,
    tvmazeId: '12981',
    title: 'Double Trouble',
    network: 'Nine Network',
    startYear: 2008,
    years: '2008',
    genres: ['Drama', 'Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/44/111488.jpg',
    note: '',
  },
  {
    id: 9521,
    tvmazeId: '1022',
    title: 'Dr. Horrible\'s Sing-Along Blog',
    network: 'Hulu',
    startYear: 2008,
    years: '2008',
    genres: ['Comedy', 'Music', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16681.jpg',
    note: '',
  },
  {
    id: 9522,
    tvmazeId: '7158',
    title: 'East of Everything',
    network: 'ABC',
    startYear: 2008,
    years: '2008–2009',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/66957.jpg',
    note: '',
  },
  {
    id: 9523,
    tvmazeId: '4541',
    title: 'Easy Money',
    network: 'The CW',
    startYear: 2008,
    years: '2008–2009',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/52108.jpg',
    note: '',
  },
  {
    id: 9524,
    tvmazeId: '4224',
    title: 'Echo Beach',
    network: 'ITV1',
    startYear: 2008,
    years: '2008',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/50688.jpg',
    note: '',
  },
  {
    id: 9525,
    tvmazeId: '1982',
    title: 'Eleventh Hour',
    network: 'CBS',
    startYear: 2008,
    years: '2008–2009',
    genres: ['Drama', 'Science-Fiction', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/27965.jpg',
    note: '',
  },
  {
    id: 9526,
    tvmazeId: '941',
    title: 'Eli Stone',
    network: 'ABC',
    startYear: 2008,
    years: '2008–2009',
    genres: ['Drama', 'Fantasy', 'Legal'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'ABC cancelled after two seasons; Eli\'s prophetic visions and his pending surgery were unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16196.jpg',
    note: '',
  },
  {
    id: 9527,
    tvmazeId: '18582',
    title: 'Eliot Kid',
    network: 'Cartoon Network',
    startYear: 2008,
    years: '2008',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/63/158238.jpg',
    note: '',
  },
  {
    id: 9528,
    tvmazeId: '29512',
    title: 'Empty',
    network: 'BBC One',
    startYear: 2008,
    years: '2008',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/117/293594.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 397, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 398, "cliffhanger": 239, "ended": 15092}};
