window.pageShows = [
  {
    id: 14161,
    tvmazeId: '4668',
    title: 'Hooperman',
    network: 'ABC',
    startYear: 1987,
    years: '1987–1989',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/52768.jpg',
    note: '',
  },
  {
    id: 14162,
    tvmazeId: '24649',
    title: 'Houston Knights',
    network: 'CBS',
    startYear: 1987,
    years: '1987–1988',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/94/235545.jpg',
    note: '',
  },
  {
    id: 14163,
    tvmazeId: '65175',
    title: 'I Married Dora',
    network: 'ABC',
    startYear: 1987,
    years: '1987',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/569/1422974.jpg',
    note: '',
  },
  {
    id: 14164,
    tvmazeId: '28610',
    title: 'I\'ll Take Manhattan',
    network: 'CBS',
    startYear: 1987,
    years: '1987',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/113/284673.jpg',
    note: '',
  },
  {
    id: 14165,
    tvmazeId: '3276',
    title: 'Inspector Morse',
    network: 'ITV1',
    startYear: 1987,
    years: '1987–2000',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/17/43885.jpg',
    note: '',
  },
  {
    id: 14166,
    tvmazeId: '51416',
    title: 'Intimate Contact',
    network: 'ITV1',
    startYear: 1987,
    years: '1987',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14167,
    tvmazeId: '39102',
    title: 'J.J. Starbuck',
    network: 'NBC',
    startYear: 1987,
    years: '1987–1988',
    genres: ['Drama', 'Adventure', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/171/428586.jpg',
    note: '',
  },
  {
    id: 14168,
    tvmazeId: '8171',
    title: 'Jake and the Fatman',
    network: 'CBS',
    startYear: 1987,
    years: '1987–1992',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/74119.jpg',
    note: '',
  },
  {
    id: 14169,
    tvmazeId: '43148',
    title: 'Karen\'s Song',
    network: 'FOX',
    startYear: 1987,
    years: '1987',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/478/1195674.jpg',
    note: '',
  },
  {
    id: 14170,
    tvmazeId: '33242',
    title: 'Knights of God',
    network: 'ITV1',
    startYear: 1987,
    years: '1987',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/134/335789.jpg',
    note: '',
  },
  {
    id: 14171,
    tvmazeId: '28992',
    title: 'L\'isola Del Tesoro',
    network: 'Rai 2',
    startYear: 1987,
    years: '1987',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/115/289011.jpg',
    note: '',
  },
  {
    id: 14172,
    tvmazeId: '79814',
    title: 'Late Expectations',
    network: 'BBC One',
    startYear: 1987,
    years: '1987',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14173,
    tvmazeId: '51624',
    title: 'Leg Work',
    network: 'CBS',
    startYear: 1987,
    years: '1987',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/385/962831.jpg',
    note: '',
  },
  {
    id: 14174,
    tvmazeId: '21014',
    title: 'Life Without George',
    network: 'BBC One',
    startYear: 1987,
    years: '1987–1989',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/74/185493.jpg',
    note: '',
  },
  {
    id: 14175,
    tvmazeId: '62338',
    title: 'Little Wizards',
    network: 'ABC',
    startYear: 1987,
    years: '1987',
    genres: ['Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/410/1027291.jpg',
    note: '',
  },
  {
    id: 14176,
    tvmazeId: '58391',
    title: 'Mama\'s Boy',
    network: 'NBC',
    startYear: 1987,
    years: '1987–1988',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 14177,
    tvmazeId: '65193',
    title: 'Marblehead Manor',
    network: 'Syndication',
    startYear: 1987,
    years: '1987–1988',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/569/1423032.jpg',
    note: '',
  },
  {
    id: 14178,
    tvmazeId: '59966',
    title: 'Mariah',
    network: 'ABC',
    startYear: 1987,
    years: '1987',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/389/973566.jpg',
    note: '',
  },
  {
    id: 14179,
    tvmazeId: '499',
    title: 'Married... with Children',
    network: 'FOX',
    startYear: 1987,
    years: '1987–1997',
    genres: ['Comedy', 'Family', 'Adult'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/4/10311.jpg',
    note: '',
  },
  {
    id: 14180,
    tvmazeId: '55969',
    title: 'Mathnet',
    network: 'PBS',
    startYear: 1987,
    years: '1987–1992',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/396/990619.jpg',
    note: '',
  },
  {
    id: 14181,
    tvmazeId: '6606',
    title: 'Max Headroom',
    network: 'ABC',
    startYear: 1987,
    years: '1987–1988',
    genres: ['Drama', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/25/62536.jpg',
    note: '',
  },
  {
    id: 14182,
    tvmazeId: '48583',
    title: 'Maxie\'s World',
    network: 'Syndication',
    startYear: 1987,
    years: '1987',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/260/652318.jpg',
    note: '',
  },
  {
    id: 14183,
    tvmazeId: '19233',
    title: 'Mighty Mouse the New Adventures',
    network: 'CBS',
    startYear: 1987,
    years: '1987–1988',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/67/168292.jpg',
    note: '',
  },
  {
    id: 14184,
    tvmazeId: '56192',
    title: 'Mr. President',
    network: 'FOX',
    startYear: 1987,
    years: '1987–1988',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/335/837774.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 591, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
