window.pageShows = [
  {
    id: 9385,
    tvmazeId: '30779',
    title: 'Linda Green',
    network: 'BBC One',
    startYear: 2001,
    years: '2001–2002',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/122/305775.jpg',
    note: '',
  },
  {
    id: 9386,
    tvmazeId: '49078',
    title: 'Liocracy',
    network: 'CTV Comedy Channel',
    startYear: 2001,
    years: '2001–2003',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 9387,
    tvmazeId: '6019',
    title: 'Lizzie McGuire',
    network: 'Disney Channel',
    startYear: 2001,
    years: '2001–2004',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/58873.jpg',
    note: '',
  },
  {
    id: 9388,
    tvmazeId: '17995',
    title: 'Lloyd in Space',
    network: 'ABC',
    startYear: 2001,
    years: '2001–2004',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/61/152575.jpg',
    note: '',
  },
  {
    id: 9389,
    tvmazeId: '66258',
    title: 'Los Dos Bros',
    network: 'E4',
    startYear: 2001,
    years: '2001',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 9390,
    tvmazeId: '66259',
    title: 'Los Luchadores',
    network: 'FOX',
    startYear: 2001,
    years: '2001',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/440/1100455.jpg',
    note: '',
  },
  {
    id: 9391,
    tvmazeId: '35459',
    title: 'Love in a Cold Climate',
    network: 'BBC One',
    startYear: 2001,
    years: '2001',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/397/993727.jpg',
    note: '',
  },
  {
    id: 9392,
    tvmazeId: '42407',
    title: 'Love is a Four Letter Word',
    network: 'ABC',
    startYear: 2001,
    years: '2001',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/200/501517.jpg',
    note: '',
  },
  {
    id: 9393,
    tvmazeId: '88015',
    title: 'Madam & Eve',
    network: 'e.tv',
    startYear: 2001,
    years: '2001',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/596/1490913.jpg',
    note: '',
  },
  {
    id: 9394,
    tvmazeId: '18516',
    title: 'Mary-Kate and Ashley in Action!',
    network: 'ABC',
    startYear: 2001,
    years: '2001–2002',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/63/157937.jpg',
    note: '',
  },
  {
    id: 9395,
    tvmazeId: '28100',
    title: 'Maybe It\'s Me',
    network: 'The WB',
    startYear: 2001,
    years: '2001–2002',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/111/277977.jpg',
    note: '',
  },
  {
    id: 9396,
    tvmazeId: '20949',
    title: 'McCready and Daughter',
    network: 'BBC One',
    startYear: 2001,
    years: '2001',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/184908.jpg',
    note: '',
  },
  {
    id: 9397,
    tvmazeId: '1374',
    title: 'McLeod\'s Daughters',
    network: 'Nine Network',
    startYear: 2001,
    years: '2001–2009',
    genres: ['Drama', 'Family', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/19089.jpg',
    note: '',
  },
  {
    id: 9398,
    tvmazeId: '39522',
    title: 'Men, Women & Dogs',
    network: 'The WB',
    startYear: 2001,
    years: '2001',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/173/434197.jpg',
    note: '',
  },
  {
    id: 9399,
    tvmazeId: '15924',
    title: 'Mercy Peak',
    network: 'TVNZ 1',
    startYear: 2001,
    years: '2001–2004',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 9400,
    tvmazeId: '32310',
    title: 'Merseybeat',
    network: 'BBC One',
    startYear: 2001,
    years: '2001–2004',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/129/322803.jpg',
    note: '',
  },
  {
    id: 9401,
    tvmazeId: '3889',
    title: 'Messiah',
    network: 'BBC One',
    startYear: 2001,
    years: '2001–2008',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/48709.jpg',
    note: '',
  },
  {
    id: 9402,
    tvmazeId: '35222',
    title: 'Metrosexuality',
    network: 'Channel 4',
    startYear: 2001,
    years: '2001',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/148/370209.jpg',
    note: '',
  },
  {
    id: 9403,
    tvmazeId: '63432',
    title: 'Micawber',
    network: 'ITV1',
    startYear: 2001,
    years: '2001–2002',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/418/1045678.jpg',
    note: '',
  },
  {
    id: 9404,
    tvmazeId: '44760',
    title: 'Monkey King: The Lost Empire',
    network: 'NBC',
    startYear: 2001,
    years: '2001',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/217/544808.jpg',
    note: '',
  },
  {
    id: 9405,
    tvmazeId: '66257',
    title: 'Mr Charity',
    network: 'BBC Two',
    startYear: 2001,
    years: '2001',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 9406,
    tvmazeId: '13997',
    title: 'Murder in Mind',
    network: 'BBC One',
    startYear: 2001,
    years: '2001–2003',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/47/119866.jpg',
    note: '',
  },
  {
    id: 9407,
    tvmazeId: '18440',
    title: 'Murphy\'s Law',
    network: 'BBC One',
    startYear: 2001,
    years: '2001–2007',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/62/157432.jpg',
    note: '',
  },
  {
    id: 9408,
    tvmazeId: '500',
    title: 'Mutant X',
    network: 'Syndication',
    startYear: 2001,
    years: '2001–2004',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/4/10319.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 392, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 670, "cliffhanger": 0, "ended": 13760}};
