window.pageShows = [
  {
    id: 10925,
    tvmazeId: '6020',
    title: 'Rosemary & Thyme',
    network: 'ITV1',
    startYear: 2003,
    years: '2003–2007',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/58877.jpg',
    note: '',
  },
  {
    id: 10926,
    tvmazeId: '2006',
    title: 'Run of the House',
    network: 'The WB',
    startYear: 2003,
    years: '2003–2004',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/28114.jpg',
    note: '',
  },
  {
    id: 10927,
    tvmazeId: '18510',
    title: 'Sabrina\'s Secret Life',
    network: 'Syndication',
    startYear: 2003,
    years: '2003–2004',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/370/926927.jpg',
    note: '',
  },
  {
    id: 10928,
    tvmazeId: '14760',
    title: 'Sergeant Stripes',
    network: 'CBeebies',
    startYear: 2003,
    years: '2003–2004',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/49/124846.jpg',
    note: '',
  },
  {
    id: 10929,
    tvmazeId: '14758',
    title: 'Serious and Organised',
    network: 'ITV1',
    startYear: 2003,
    years: '2003',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/49/124840.jpg',
    note: '',
  },
  {
    id: 10930,
    tvmazeId: '19019',
    title: 'Servants',
    network: 'BBC One',
    startYear: 2003,
    years: '2003',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/534/1335133.jpg',
    note: '',
  },
  {
    id: 10931,
    tvmazeId: '27821',
    title: 'Silverwing',
    network: 'Cartoon Network',
    startYear: 2003,
    years: '2003',
    genres: ['Adventure', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/110/275462.jpg',
    note: '',
  },
  {
    id: 10932,
    tvmazeId: '15101',
    title: 'Skin',
    network: 'FOX',
    startYear: 2003,
    years: '2003',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/353/882923.jpg',
    note: '',
  },
  {
    id: 10933,
    tvmazeId: '1283',
    title: 'Slings & Arrows',
    network: 'Crave',
    startYear: 2003,
    years: '2003–2006',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/18392.jpg',
    note: '',
  },
  {
    id: 10934,
    tvmazeId: '19874',
    title: 'Snobs',
    network: 'Nine Network',
    startYear: 2003,
    years: '2003',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/70/175619.jpg',
    note: '',
  },
  {
    id: 10935,
    tvmazeId: '74096',
    title: 'Softies',
    network: '5',
    startYear: 2003,
    years: '2003–2004',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 10936,
    tvmazeId: '7646',
    title: 'Sonic X',
    network: 'FOX',
    startYear: 2003,
    years: '2003–2006',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/70421.jpg',
    note: '',
  },
  {
    id: 10937,
    tvmazeId: '4458',
    title: 'Spider-Man',
    network: 'MTV',
    startYear: 2003,
    years: '2003',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/51873.jpg',
    note: '',
  },
  {
    id: 10938,
    tvmazeId: '17920',
    title: 'Spine Chillers',
    network: 'BBC Three',
    startYear: 2003,
    years: '2003',
    genres: ['Drama', 'Comedy', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/60/151260.jpg',
    note: '',
  },
  {
    id: 10939,
    tvmazeId: '1259',
    title: 'Star Wars: Clone Wars',
    network: 'Cartoon Network',
    startYear: 2003,
    years: '2003–2005',
    genres: ['Action', 'Family', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/393/983792.jpg',
    note: '',
  },
  {
    id: 10940,
    tvmazeId: '5788',
    title: 'State of Play',
    network: 'BBC One',
    startYear: 2003,
    years: '2003',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/57819.jpg',
    note: '',
  },
  {
    id: 10941,
    tvmazeId: '33101',
    title: 'Strange',
    network: 'BBC One',
    startYear: 2003,
    years: '2003',
    genres: ['Drama', 'Action', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/133/334132.jpg',
    note: '',
  },
  {
    id: 10942,
    tvmazeId: '1890',
    title: 'Stripperella',
    network: 'Paramount Network',
    startYear: 2003,
    years: '2003–2004',
    genres: ['Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/27609.jpg',
    note: '',
  },
  {
    id: 10943,
    tvmazeId: '68246',
    title: 'Stuart Little',
    network: 'HBO Family',
    startYear: 2003,
    years: '2003',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/458/1145465.jpg',
    note: '',
  },
  {
    id: 10944,
    tvmazeId: '11175',
    title: 'Swiss Toni',
    network: 'BBC Three',
    startYear: 2003,
    years: '2003–2004',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/37/93863.jpg',
    note: '',
  },
  {
    id: 10945,
    tvmazeId: '4469',
    title: 'Tarzan',
    network: 'The WB',
    startYear: 2003,
    years: '2003',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/51895.jpg',
    note: '',
  },
  {
    id: 10946,
    tvmazeId: '765',
    title: 'Teen Titans',
    network: 'Cartoon Network',
    startYear: 2003,
    years: '2003–2006',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/15290.jpg',
    note: '',
  },
  {
    id: 10947,
    tvmazeId: '736',
    title: 'Teenage Mutant Ninja Turtles',
    network: 'The CW',
    startYear: 2003,
    years: '2003–2009',
    genres: ['Comedy', 'Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/15145.jpg',
    note: '',
  },
  {
    id: 10948,
    tvmazeId: '1408',
    title: 'That\'s So Raven',
    network: 'Disney Channel',
    startYear: 2003,
    years: '2003–2007',
    genres: ['Comedy', 'Children', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/8/20019.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 456, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
