window.pageShows = [
  {
    id: 1057,
    tvmazeId: '76102',
    title: 'Faithless',
    network: 'Virgin Media Player',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/514/1285017.jpg',
    note: '',
  },
  {
    id: 1058,
    tvmazeId: '71232',
    title: 'Fake',
    network: 'Paramount+',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Romance', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/522/1306878.jpg',
    note: '',
  },
  {
    id: 1059,
    tvmazeId: '73556',
    title: 'Fallen',
    network: 'Globoplay',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Romance', 'Supernatural'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/531/1328102.jpg',
    note: '',
  },
  {
    id: 1060,
    tvmazeId: '49041',
    title: 'Fallout',
    network: 'Prime Video',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Action', 'Science-Fiction'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/599/1499142.jpg',
    note: '',
  },
  {
    id: 1061,
    tvmazeId: '45185',
    title: 'Fam Time',
    network: '7plus',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/527/1318415.jpg',
    note: '',
  },
  {
    id: 1062,
    tvmazeId: '79364',
    title: 'Family By Choice',
    network: 'jTBC',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/533/1334809.jpg',
    note: '',
  },
  {
    id: 1063,
    tvmazeId: '80348',
    title: 'Family Guy Hulu Exclusives',
    network: 'Hulu',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/599/1497907.jpg',
    note: '',
  },
  {
    id: 1064,
    tvmazeId: '76553',
    title: 'Fantasmas',
    network: 'HBO',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/522/1306906.jpg',
    note: '',
  },
  {
    id: 1065,
    tvmazeId: '76563',
    title: 'Felices Los 6',
    network: 'HBO Max',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/522/1306818.jpg',
    note: '',
  },
  {
    id: 1066,
    tvmazeId: '69674',
    title: 'Fiasco',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/513/1283157.jpg',
    note: '',
  },
  {
    id: 1067,
    tvmazeId: '74506',
    title: 'Fight Night: The Million Dollar Heist',
    network: 'Peacock',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/528/1322334.jpg',
    note: '',
  },
  {
    id: 1068,
    tvmazeId: '68641',
    title: 'Finders Keepers',
    network: '5',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/500/1250125.jpg',
    note: '',
  },
  {
    id: 1069,
    tvmazeId: '75942',
    title: 'Fizzy and Suds',
    network: 'ABC iview',
    startYear: 2024,
    years: '2024–',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/512/1281850.jpg',
    note: '',
  },
  {
    id: 1070,
    tvmazeId: '75339',
    title: 'Fleur Bleue',
    network: 'Canal+',
    startYear: 2024,
    years: '2024–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/546/1367288.jpg',
    note: '',
  },
  {
    id: 1071,
    tvmazeId: '73181',
    title: 'Flex x Cop',
    network: 'SBS',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Romance', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/500/1252007.jpg',
    note: '',
  },
  {
    id: 1072,
    tvmazeId: '73900',
    title: 'Forst',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/499/1248512.jpg',
    note: '',
  },
  {
    id: 1073,
    tvmazeId: '72415',
    title: 'Four Years Later',
    network: 'SBS On Demand',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/539/1348397.jpg',
    note: '',
  },
  {
    id: 1074,
    tvmazeId: '74480',
    title: 'Franklin',
    network: 'Apple TV',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/510/1277075.jpg',
    note: '',
  },
  {
    id: 1075,
    tvmazeId: '75612',
    title: 'Friends Like Her',
    network: 'ThreeNow',
    startYear: 2024,
    years: '2024',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/514/1285548.jpg',
    note: '',
  },
  {
    id: 1076,
    tvmazeId: '74535',
    title: 'Furies',
    network: 'Netflix',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/505/1262722.jpg',
    note: '',
  },
  {
    id: 1077,
    tvmazeId: '68485',
    title: 'G\'wed',
    network: 'ITVX',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/628/1570317.jpg',
    note: '',
  },
  {
    id: 1078,
    tvmazeId: '77001',
    title: 'Gangnam B-Side',
    network: 'Disney+',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/537/1344887.jpg',
    note: '',
  },
  {
    id: 1079,
    tvmazeId: '71729',
    title: 'Gangnam Project',
    network: 'BBC iPlayer',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Comedy', 'Music'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/505/1263174.jpg',
    note: '',
  },
  {
    id: 1080,
    tvmazeId: '76501',
    title: 'Geek Girl',
    network: 'Netflix',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/521/1303825.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 45, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
