window.pageShows = [
  {
    id: 529,
    tvmazeId: '81766',
    title: 'Long Story Short',
    network: 'Netflix',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/577/1444561.jpg',
    note: '',
  },
  {
    id: 530,
    tvmazeId: '75310',
    title: 'Los gringo hunters',
    network: 'Netflix',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/577/1444179.jpg',
    note: '',
  },
  {
    id: 531,
    tvmazeId: '87092',
    title: 'Los Mufas: suerte para la desgracia',
    network: 'Disney+',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/587/1468666.jpg',
    note: '',
  },
  {
    id: 532,
    tvmazeId: '84785',
    title: 'Losmen Bu Broto: The Series',
    network: 'Netflix',
    startYear: 2025,
    years: '2025',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/570/1427457.jpg',
    note: '',
  },
  {
    id: 533,
    tvmazeId: '86864',
    title: 'Lover Merman',
    network: 'Channel 7',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Fantasy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/585/1464527.jpg',
    note: '',
  },
  {
    id: 534,
    tvmazeId: '81602',
    title: 'Low Life',
    network: 'Disney+',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/577/1443500.jpg',
    note: '',
  },
  {
    id: 535,
    tvmazeId: '80191',
    title: 'Lynley',
    network: 'BritBox',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/584/1460977.jpg',
    note: '',
  },
  {
    id: 536,
    tvmazeId: '61499',
    title: 'M. Il figlio del secolo',
    network: 'Sky Atlantic',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/545/1363519.jpg',
    note: '',
  },
  {
    id: 537,
    tvmazeId: '84395',
    title: 'Mad Unicorn',
    network: 'Netflix',
    startYear: 2025,
    years: '2025',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/570/1425898.jpg',
    note: '',
  },
  {
    id: 538,
    tvmazeId: '81597',
    title: 'Made in Korea',
    network: 'Disney+',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/607/1517771.jpg',
    note: '',
  },
  {
    id: 539,
    tvmazeId: '82659',
    title: 'Mafia Lover',
    network: 'Dramabox',
    startYear: 2025,
    years: '2025',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/556/1390946.jpg',
    note: '',
  },
  {
    id: 540,
    tvmazeId: '82716',
    title: 'Maigret',
    network: 'PBS',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/580/1452189.jpg',
    note: '',
  },
  {
    id: 541,
    tvmazeId: '84429',
    title: 'Malditos',
    network: 'HBO Max',
    startYear: 2025,
    years: '2025–',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/566/1416720.jpg',
    note: '',
  },
  {
    id: 542,
    tvmazeId: '74232',
    title: 'Malice',
    network: 'Prime Video',
    startYear: 2025,
    years: '2025–',
    genres: ['Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/598/1495715.jpg',
    note: '',
  },
  {
    id: 543,
    tvmazeId: '82740',
    title: 'Man vs Baby',
    network: 'Netflix',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/603/1507832.jpg',
    note: '',
  },
  {
    id: 544,
    tvmazeId: '75081',
    title: 'Mandala Murders',
    network: 'Netflix',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/579/1449254.jpg',
    note: '',
  },
  {
    id: 545,
    tvmazeId: '82715',
    title: 'Manual para señoritas',
    network: 'Netflix',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/561/1403285.jpg',
    note: '',
  },
  {
    id: 546,
    tvmazeId: '83829',
    title: 'Maria e o Cangaço',
    network: 'Disney+',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Crime', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/562/1405972.jpg',
    note: '',
  },
  {
    id: 547,
    tvmazeId: '85343',
    title: 'Marked',
    network: 'Netflix',
    startYear: 2025,
    years: '2025–',
    genres: ['Crime', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/580/1451143.jpg',
    note: '',
  },
  {
    id: 548,
    tvmazeId: '85668',
    title: 'Marry My Husband Japan',
    network: 'Prime Video',
    startYear: 2025,
    years: '2025',
    genres: ['Drama', 'Fantasy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/619/1549497.jpg',
    note: '',
  },
  {
    id: 549,
    tvmazeId: '80180',
    title: 'Marvel Iron Man and his Awesome Friends',
    network: 'Disney+',
    startYear: 2025,
    years: '2025–',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/599/1499012.jpg',
    note: '',
  },
  {
    id: 550,
    tvmazeId: '58949',
    title: 'Marvel Zombies',
    network: 'Disney+',
    startYear: 2025,
    years: '2025–',
    genres: ['Horror', 'Science-Fiction'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/586/1466484.jpg',
    note: '',
  },
  {
    id: 551,
    tvmazeId: '86377',
    title: 'Marvel\'s Spidey and Iron Man: Avengers Team-Up!',
    network: 'Disney Junior',
    startYear: 2025,
    years: '2025–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/590/1476824.jpg',
    note: '',
  },
  {
    id: 552,
    tvmazeId: '84685',
    title: 'Maschi veri',
    network: 'Netflix',
    startYear: 2025,
    years: '2025–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/568/1422146.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 23, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
