window.pageShows = [
  {
    id: 3097,
    tvmazeId: '56865',
    title: 'Adulting',
    network: 'Viddsee',
    startYear: 2021,
    years: '2021',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 3098,
    tvmazeId: '57801',
    title: 'Adventure Beast',
    network: 'Netflix',
    startYear: 2021,
    years: '2021',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/368/921376.jpg',
    note: '',
  },
  {
    id: 3099,
    tvmazeId: '49489',
    title: 'Aftertaste',
    network: 'ABC iview',
    startYear: 2021,
    years: '2021–2022',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/294/737054.jpg',
    note: '',
  },
  {
    id: 3100,
    tvmazeId: '83249',
    title: 'Akedo: Ultimate Arcade Warriors',
    network: 'YouTube',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Action', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/559/1399617.jpg',
    note: '',
  },
  {
    id: 3101,
    tvmazeId: '69266',
    title: 'Akkad Bakkad Rafu Chakkar',
    network: 'Prime Video',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/464/1162345.jpg',
    note: '',
  },
  {
    id: 3102,
    tvmazeId: '50906',
    title: 'All My Friends Are Racist',
    network: 'ABC',
    startYear: 2021,
    years: '2021',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/407/1017758.jpg',
    note: '',
  },
  {
    id: 3103,
    tvmazeId: '57465',
    title: 'All the Queen\'s Men',
    network: 'Paramount+',
    startYear: 2021,
    years: '2021–',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/576/1441770.jpg',
    note: '',
  },
  {
    id: 3104,
    tvmazeId: '71651',
    title: 'Alma\'s Way',
    network: 'PBS Kids',
    startYear: 2021,
    years: '2021–',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/479/1198376.jpg',
    note: '',
  },
  {
    id: 3105,
    tvmazeId: '58752',
    title: 'Alparslan: Büyük Selçuklu',
    network: 'TRT1',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Action', 'War', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/429/1072783.jpg',
    note: '',
  },
  {
    id: 3106,
    tvmazeId: '53513',
    title: 'Alpha Betas',
    network: 'YouTube',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Comedy', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/296/740926.jpg',
    note: '',
  },
  {
    id: 3107,
    tvmazeId: '56710',
    title: 'AlRawabi School for Girls',
    network: 'Netflix',
    startYear: 2021,
    years: '2021–2024',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/512/1281564.jpg',
    note: '',
  },
  {
    id: 3108,
    tvmazeId: '68646',
    title: 'Amarres',
    network: 'HBO Max',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/460/1150676.jpg',
    note: '',
  },
  {
    id: 3109,
    tvmazeId: '49265',
    title: 'Amazing Grace',
    network: 'Nine Network',
    startYear: 2021,
    years: '2021',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/298/746556.jpg',
    note: '',
  },
  {
    id: 3110,
    tvmazeId: '59685',
    title: 'Ambient Swim',
    network: 'HBO Max',
    startYear: 2021,
    years: '2021–2023',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/385/964758.jpg',
    note: '',
  },
  {
    id: 3111,
    tvmazeId: '78514',
    title: 'Amelia Parker',
    network: 'Super Channel Heart & Home',
    startYear: 2021,
    years: '2021',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/528/1320441.jpg',
    note: '',
  },
  {
    id: 3112,
    tvmazeId: '53264',
    title: 'American Auto',
    network: 'NBC',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/442/1107201.jpg',
    note: '',
  },
  {
    id: 3113,
    tvmazeId: '48000',
    title: 'American Horror Stories',
    network: 'Hulu',
    startYear: 2021,
    years: '2021–2024',
    genres: ['Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/592/1480231.jpg',
    note: '',
  },
  {
    id: 3114,
    tvmazeId: '43217',
    title: 'American Rust',
    network: 'Prime Video',
    startYear: 2021,
    years: '2021–2024',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/512/1281767.jpg',
    note: '',
  },
  {
    id: 3115,
    tvmazeId: '52904',
    title: 'And Just Like That...',
    network: 'HBO Max',
    startYear: 2021,
    years: '2021–2025',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/581/1453808.jpg',
    note: '',
  },
  {
    id: 3116,
    tvmazeId: '51063',
    title: 'Angela Black',
    network: 'ITV1',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/364/910347.jpg',
    note: '',
  },
  {
    id: 3117,
    tvmazeId: '55641',
    title: 'Angels of Death',
    network: 'Warhammer+',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/353/883760.jpg',
    note: '',
  },
  {
    id: 3118,
    tvmazeId: '54628',
    title: 'Anna',
    network: 'Sky Atlantic',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/310/775401.jpg',
    note: '',
  },
  {
    id: 3119,
    tvmazeId: '53485',
    title: 'Anne Boleyn',
    network: '5',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Thriller', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/324/811513.jpg',
    note: '',
  },
  {
    id: 3120,
    tvmazeId: '52732',
    title: 'Annika',
    network: 'U&alibi',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/419/1049050.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 130, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
