window.pageShows = [
  {
    id: 7729,
    tvmazeId: '16805',
    title: 'The Lost Honour of Christopher Jefferies',
    network: 'ITV1',
    startYear: 2014,
    years: '2014',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/56/140364.jpg',
    note: '',
  },
  {
    id: 7730,
    tvmazeId: '50',
    title: 'The Lottery',
    network: 'Lifetime',
    startYear: 2014,
    years: '2014',
    genres: ['Drama', 'Science-Fiction', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/146/366444.jpg',
    note: '',
  },
  {
    id: 7731,
    tvmazeId: '37984',
    title: 'The March Family Letters',
    network: 'YouTube',
    startYear: 2014,
    years: '2014–2015',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/162/406802.jpg',
    note: '',
  },
  {
    id: 7732,
    tvmazeId: '43801',
    title: 'The Martin Garrix Show',
    network: 'YouTube',
    startYear: 2014,
    years: '2014–',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/210/527227.jpg',
    note: '',
  },
  {
    id: 7733,
    tvmazeId: '136',
    title: 'The McCarthys',
    network: 'CBS',
    startYear: 2014,
    years: '2014–2015',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/0/1900.jpg',
    note: '',
  },
  {
    id: 7734,
    tvmazeId: '316',
    title: 'The Missing',
    network: 'BBC One',
    startYear: 2014,
    years: '2014–2016',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/2/5109.jpg',
    note: '',
  },
  {
    id: 7735,
    tvmazeId: '27926',
    title: 'The Moe Show',
    network: 'Three',
    startYear: 2014,
    years: '2014–2017',
    genres: ['Children', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/110/276285.jpg',
    note: '',
  },
  {
    id: 7736,
    tvmazeId: '377',
    title: 'The Musketeers',
    network: 'BBC One',
    startYear: 2014,
    years: '2014–2016',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/2/5545.jpg',
    note: '',
  },
  {
    id: 7737,
    tvmazeId: '78',
    title: 'The Mysteries of Laura',
    network: 'NBC',
    startYear: 2014,
    years: '2014–2016',
    genres: ['Comedy', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/0/568.jpg',
    note: '',
  },
  {
    id: 7738,
    tvmazeId: '31883',
    title: 'The New Adventures of Lassie',
    network: 'ZDF',
    startYear: 2014,
    years: '2014–2019',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/127/319067.jpg',
    note: '',
  },
  {
    id: 7739,
    tvmazeId: '294',
    title: 'The Night Shift',
    network: 'NBC',
    startYear: 2014,
    years: '2014–2017',
    genres: ['Drama', 'Action', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/126/315025.jpg',
    note: '',
  },
  {
    id: 7740,
    tvmazeId: '19744',
    title: 'The Other Wife',
    network: '5',
    startYear: 2014,
    years: '2014',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/69/174428.jpg',
    note: '',
  },
  {
    id: 7741,
    tvmazeId: '425',
    title: 'The Passing Bells',
    network: 'BBC One',
    startYear: 2014,
    years: '2014',
    genres: ['Drama', 'War', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/2/7487.jpg',
    note: '',
  },
  {
    id: 7742,
    tvmazeId: '3432',
    title: 'The Pinkertons',
    network: 'Syndication',
    startYear: 2014,
    years: '2014–2015',
    genres: ['Crime', 'Western', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/38/95843.jpg',
    note: '',
  },
  {
    id: 7743,
    tvmazeId: '4671',
    title: 'The Rebels',
    network: 'Prime Video',
    startYear: 2014,
    years: '2014',
    genres: ['Comedy', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/227/569569.jpg',
    note: '',
  },
  {
    id: 7744,
    tvmazeId: '371',
    title: 'The Red Road',
    network: 'SundanceTV',
    startYear: 2014,
    years: '2014–2015',
    genres: ['Drama', 'Crime', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/2/5516.jpg',
    note: '',
  },
  {
    id: 7745,
    tvmazeId: '650',
    title: 'The Red Tent',
    network: 'Lifetime',
    startYear: 2014,
    years: '2014',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/307/769078.jpg',
    note: '',
  },
  {
    id: 7746,
    tvmazeId: '14998',
    title: 'The Secrets',
    network: 'BBC One',
    startYear: 2014,
    years: '2014',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/51/127656.jpg',
    note: '',
  },
  {
    id: 7747,
    tvmazeId: '27831',
    title: 'The Skinner Boys',
    network: '9Go!',
    startYear: 2014,
    years: '2014–2017',
    genres: ['Action', 'Adventure', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/178/445143.jpg',
    note: '',
  },
  {
    id: 7748,
    tvmazeId: '5747',
    title: 'The Smoke',
    network: 'Sky Showcase',
    startYear: 2014,
    years: '2014',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/57315.jpg',
    note: '',
  },
  {
    id: 7749,
    tvmazeId: '1377',
    title: 'The Spoils of Babylon',
    network: 'IFC',
    startYear: 2014,
    years: '2014',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/19133.jpg',
    note: '',
  },
  {
    id: 7750,
    tvmazeId: '20',
    title: 'The Strain',
    network: 'FX',
    startYear: 2014,
    years: '2014–2017',
    genres: ['Drama', 'Horror', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/444/1111710.jpg',
    note: '',
  },
  {
    id: 7751,
    tvmazeId: '4296',
    title: 'The Tom and Jerry Show',
    network: 'Cartoon Network',
    startYear: 2014,
    years: '2014–2021',
    genres: ['Comedy', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/51195.jpg',
    note: '',
  },
  {
    id: 7752,
    tvmazeId: '3706',
    title: 'The Walshes',
    network: 'RTÉ ONE',
    startYear: 2014,
    years: '2014',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/47493.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 323, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
