window.pageShows = [
  {
    id: 1781,
    tvmazeId: '70494',
    title: 'Infamia',
    network: 'Netflix',
    startYear: 2023,
    years: '2023',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/475/1188998.jpg',
    note: '',
  },
  {
    id: 1782,
    tvmazeId: '72200',
    title: 'Informacja zwrotna',
    network: 'Netflix',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/486/1217170.jpg',
    note: '',
  },
  {
    id: 1783,
    tvmazeId: '70118',
    title: 'Irrésistible',
    network: 'Disney+',
    startYear: 2023,
    years: '2023–',
    genres: ['Comedy', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/470/1175916.jpg',
    note: '',
  },
  {
    id: 1784,
    tvmazeId: '72538',
    title: 'Isadora Moon',
    network: 'Now',
    startYear: 2023,
    years: '2023–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/532/1332340.jpg',
    note: '',
  },
  {
    id: 1785,
    tvmazeId: '67003',
    title: 'Jamie Johnson FC',
    network: 'BBC iPlayer',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Children', 'Sports'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/580/1450240.jpg',
    note: '',
  },
  {
    id: 1786,
    tvmazeId: '66598',
    title: 'Jane',
    network: 'Apple TV',
    startYear: 2023,
    years: '2023–2025',
    genres: ['Adventure', 'Children', 'Nature'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/512/1280324.jpg',
    note: '',
  },
  {
    id: 1787,
    tvmazeId: '70249',
    title: 'Jee Karda',
    network: 'Prime Video',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/470/1177324.jpg',
    note: '',
  },
  {
    id: 1788,
    tvmazeId: '71363',
    title: 'Jessica\'s Big Little World',
    network: 'Cartoon Network',
    startYear: 2023,
    years: '2023–2024',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/477/1194189.jpg',
    note: '',
  },
  {
    id: 1789,
    tvmazeId: '67945',
    title: 'Jubilee',
    network: 'Prime Video',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/455/1139198.jpg',
    note: '',
  },
  {
    id: 1790,
    tvmazeId: '66312',
    title: 'Judge Me Not',
    network: 'ALLBLK',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Legal'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/462/1155089.jpg',
    note: '',
  },
  {
    id: 1791,
    tvmazeId: '62012',
    title: 'Juice',
    network: 'BBC iPlayer',
    startYear: 2023,
    years: '2023–2025',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/590/1476762.jpg',
    note: '',
  },
  {
    id: 1792,
    tvmazeId: '69262',
    title: 'Jun and Jun',
    network: 'Heavenly',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/464/1162299.jpg',
    note: '',
  },
  {
    id: 1793,
    tvmazeId: '67367',
    title: 'Jury Duty',
    network: 'Prime Video',
    startYear: 2023,
    years: '2023',
    genres: ['Comedy', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/619/1547538.jpg',
    note: '',
  },
  {
    id: 1794,
    tvmazeId: '67491',
    title: 'Jusqu\'ici tout va bien',
    network: 'Netflix',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/455/1139638.jpg',
    note: '',
  },
  {
    id: 1795,
    tvmazeId: '59974',
    title: 'Justified: City Primeval',
    network: 'FX',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/468/1171537.jpg',
    note: '',
  },
  {
    id: 1796,
    tvmazeId: '71748',
    title: 'Kaala Paani',
    network: 'Netflix',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/481/1204191.jpg',
    note: '',
  },
  {
    id: 1797,
    tvmazeId: '57680',
    title: 'Kaleidoscope',
    network: 'Netflix',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/438/1097241.jpg',
    note: '',
  },
  {
    id: 1798,
    tvmazeId: '66667',
    title: 'Kiff',
    network: 'DisneyNOW',
    startYear: 2023,
    years: '2023–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/596/1492487.jpg',
    note: '',
  },
  {
    id: 1799,
    tvmazeId: '70033',
    title: 'Killer Coaster',
    network: 'Prime Video',
    startYear: 2023,
    years: '2023',
    genres: ['Comedy', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/469/1174384.jpg',
    note: '',
  },
  {
    id: 1800,
    tvmazeId: '63983',
    title: 'Kimi ni Todoke',
    network: 'Netflix',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/454/1136184.jpg',
    note: '',
  },
  {
    id: 1801,
    tvmazeId: '68297',
    title: 'Kitti Katz',
    network: 'Netflix',
    startYear: 2023,
    years: '2023–',
    genres: ['Action', 'Adventure', 'Children'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/461/1154272.jpg',
    note: '',
  },
  {
    id: 1802,
    tvmazeId: '67434',
    title: 'Kiya & the Kimoja Heroes',
    network: 'Disney+',
    startYear: 2023,
    years: '2023–2024',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/459/1148718.jpg',
    note: '',
  },
  {
    id: 1803,
    tvmazeId: '55955',
    title: 'Kizazi Moto: Generation Fire',
    network: 'Disney+',
    startYear: 2023,
    years: '2023',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/462/1157414.jpg',
    note: '',
  },
  {
    id: 1804,
    tvmazeId: '68125',
    title: 'Klub Kecanduan Mantan',
    network: 'Netflix',
    startYear: 2023,
    years: '2023',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/457/1142696.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 75, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
