window.pageShows = [
  {
    id: 15005,
    tvmazeId: '8747',
    title: 'Solo',
    network: 'BBC One',
    startYear: 1981,
    years: '1981–1982',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/77798.jpg',
    note: '',
  },
  {
    id: 15006,
    tvmazeId: '51016',
    title: 'Sons and Lovers',
    network: 'BBC One',
    startYear: 1981,
    years: '1981',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/276/692326.jpg',
    note: '',
  },
  {
    id: 15007,
    tvmazeId: '7040',
    title: 'Sorry!',
    network: 'BBC One',
    startYear: 1981,
    years: '1981–1988',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/66004.jpg',
    note: '',
  },
  {
    id: 15008,
    tvmazeId: '55916',
    title: 'Sorry, I\'m a Stranger Here Myself',
    network: 'ITV1',
    startYear: 1981,
    years: '1981–1982',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/329/823236.jpg',
    note: '',
  },
  {
    id: 15009,
    tvmazeId: '53559',
    title: 'Space Ghost',
    network: 'NBC',
    startYear: 1981,
    years: '1981',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 15010,
    tvmazeId: '53563',
    title: 'Space Stars Finale',
    network: 'NBC',
    startYear: 1981,
    years: '1981',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/296/741545.jpg',
    note: '',
  },
  {
    id: 15011,
    tvmazeId: '32686',
    title: 'Spider-Man',
    network: 'Syndication',
    startYear: 1981,
    years: '1981–1982',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/131/328110.jpg',
    note: '',
  },
  {
    id: 15012,
    tvmazeId: '4052',
    title: 'Spider-Man and His Amazing Friends',
    network: 'NBC',
    startYear: 1981,
    years: '1981–1983',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/49654.jpg',
    note: '',
  },
  {
    id: 15013,
    tvmazeId: '49368',
    title: 'Stig of the Dump',
    network: 'ITV1',
    startYear: 1981,
    years: '1981',
    genres: ['Drama', 'Adventure', 'Family'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/266/665525.jpg',
    note: '',
  },
  {
    id: 15014,
    tvmazeId: '18366',
    title: 'Strike Force',
    network: 'ABC',
    startYear: 1981,
    years: '1981–1982',
    genres: ['Action', 'Adventure', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/62/156100.jpg',
    note: '',
  },
  {
    id: 15015,
    tvmazeId: '87464',
    title: 'Sunday Night Thriller',
    network: 'ITV1',
    startYear: 1981,
    years: '1981',
    genres: ['Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 15016,
    tvmazeId: '29297',
    title: 'Take a Letter Mr. Jones...',
    network: 'ITV1',
    startYear: 1981,
    years: '1981',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/116/292189.jpg',
    note: '',
  },
  {
    id: 15017,
    tvmazeId: '53561',
    title: 'Teen Force',
    network: 'NBC',
    startYear: 1981,
    years: '1981',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 15018,
    tvmazeId: '8311',
    title: 'Tenko',
    network: 'BBC One',
    startYear: 1981,
    years: '1981–1984',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/74809.jpg',
    note: '',
  },
  {
    id: 15019,
    tvmazeId: '78914',
    title: 'That Beryl Marston...!',
    network: 'ITV1',
    startYear: 1981,
    years: '1981',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 15020,
    tvmazeId: '11043',
    title: 'That\'s My Boy',
    network: 'ITV1',
    startYear: 1981,
    years: '1981–1986',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/37/92814.jpg',
    note: '',
  },
  {
    id: 15021,
    tvmazeId: '27078',
    title: 'The Borgias',
    network: 'BBC Two',
    startYear: 1981,
    years: '1981',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: '',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/107/267517.jpg',
    note: '',
  },
  {
    id: 15022,
    tvmazeId: '41947',
    title: 'The Brady Brides',
    network: 'NBC',
    startYear: 1981,
    years: '1981',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/193/483474.jpg',
    note: '',
  },
  {
    id: 15023,
    tvmazeId: '53568',
    title: 'The Bungle Brothers',
    network: 'CBS',
    startYear: 1981,
    years: '1981',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 15024,
    tvmazeId: '29270',
    title: 'The Chinese Detective',
    network: 'BBC One',
    startYear: 1981,
    years: '1981–1982',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/277/693693.jpg',
    note: '',
  },
  {
    id: 15025,
    tvmazeId: '11094',
    title: 'The Comic Strip Presents...',
    network: 'U&GOLD',
    startYear: 1981,
    years: '1981–2016',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/230/577096.jpg',
    note: '',
  },
  {
    id: 15026,
    tvmazeId: '6907',
    title: 'The Day of the Triffids',
    network: 'BBC One',
    startYear: 1981,
    years: '1981',
    genres: ['Drama', 'Fantasy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/65113.jpg',
    note: '',
  },
  {
    id: 15027,
    tvmazeId: '2031',
    title: 'The Fall Guy',
    network: 'ABC',
    startYear: 1981,
    years: '1981–1986',
    genres: ['Action', 'Adventure', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/28370.jpg',
    note: '',
  },
  {
    id: 15028,
    tvmazeId: '24972',
    title: 'The Flame Trees of Thika',
    network: 'BBC One',
    startYear: 1981,
    years: '1981',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/96/240601.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 626, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
