window.pageShows = [
  {
    id: 7489,
    tvmazeId: '90498',
    title: 'Kol\'s World',
    network: 'The Pet Network',
    startYear: 2014,
    years: '2014',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 7490,
    tvmazeId: '44676',
    title: 'L.A. Rangers',
    network: 'CW Seed',
    startYear: 2014,
    years: '2014',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/217/543178.jpg',
    note: '',
  },
  {
    id: 7491,
    tvmazeId: '48729',
    title: 'Lah-Lah\'s Adventures',
    network: '7two',
    startYear: 2014,
    years: '2014–2015',
    genres: ['Children', 'Music'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/261/654672.jpg',
    note: '',
  },
  {
    id: 7492,
    tvmazeId: '10986',
    title: 'LARPs: The Series',
    network: 'YouTube',
    startYear: 2014,
    years: '2014–2015',
    genres: ['Drama', 'Comedy', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/36/92339.jpg',
    note: '',
  },
  {
    id: 7493,
    tvmazeId: '54',
    title: 'Legends',
    network: 'TNT',
    startYear: 2014,
    years: '2014–2015',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/36/92018.jpg',
    note: '',
  },
  {
    id: 7494,
    tvmazeId: '12063',
    title: 'Lily\'s Driftwood Bay',
    network: 'Nick Jr.',
    startYear: 2014,
    years: '2014–',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/40/101117.jpg',
    note: '',
  },
  {
    id: 7495,
    tvmazeId: '9879',
    title: 'Little Lunch',
    network: 'ABC Entertains',
    startYear: 2014,
    years: '2014',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/34/85018.jpg',
    note: '',
  },
  {
    id: 7496,
    tvmazeId: '9243',
    title: 'Long Live the Royals',
    network: 'Cartoon Network',
    startYear: 2014,
    years: '2014–2015',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/32/81379.jpg',
    note: '',
  },
  {
    id: 7497,
    tvmazeId: '140',
    title: 'Looking',
    network: 'HBO',
    startYear: 2014,
    years: '2014–2015',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/0/1961.jpg',
    note: '',
  },
  {
    id: 7498,
    tvmazeId: '18573',
    title: 'Lords of War',
    network: 'YouTube',
    startYear: 2014,
    years: '2014',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 7499,
    tvmazeId: '2164',
    title: 'Love Child',
    network: 'Nine Network',
    startYear: 2014,
    years: '2014–2017',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/12/30248.jpg',
    note: '',
  },
  {
    id: 7500,
    tvmazeId: '267',
    title: 'Lovesick',
    network: 'Netflix',
    startYear: 2014,
    years: '2014–2018',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/143/359769.jpg',
    note: '',
  },
  {
    id: 7501,
    tvmazeId: '43913',
    title: 'Ma Pire Angoisse',
    network: 'Canal+',
    startYear: 2014,
    years: '2014–2017',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/491/1229976.jpg',
    note: '',
  },
  {
    id: 7502,
    tvmazeId: '32302',
    title: 'Mabel\'s Guide to Life',
    network: 'Disney XD',
    startYear: 2014,
    years: '2014',
    genres: ['Comedy', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/129/322744.jpg',
    note: '',
  },
  {
    id: 7503,
    tvmazeId: '48',
    title: 'Madam Secretary',
    network: 'CBS',
    startYear: 2014,
    years: '2014–2019',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/214/536175.jpg',
    note: '',
  },
  {
    id: 7504,
    tvmazeId: '4294',
    title: 'Mammon',
    network: 'NRK1',
    startYear: 2014,
    years: '2014–2016',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/51180.jpg',
    note: '',
  },
  {
    id: 7505,
    tvmazeId: '688',
    title: 'Manhattan',
    network: 'NewsNation',
    startYear: 2014,
    years: '2014–2015',
    genres: ['Drama'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/46/116919.jpg',
    note: '',
  },
  {
    id: 7506,
    tvmazeId: '96',
    title: 'Manhattan Love Story',
    network: 'ABC',
    startYear: 2014,
    years: '2014',
    genres: ['Comedy', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/0/729.jpg',
    note: '',
  },
  {
    id: 7507,
    tvmazeId: '24148',
    title: 'Mapp and Lucia',
    network: 'BBC One',
    startYear: 2014,
    years: '2014',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/91/228935.jpg',
    note: '',
  },
  {
    id: 7508,
    tvmazeId: '700',
    title: 'Marco Polo',
    network: 'Netflix',
    startYear: 2014,
    years: '2014–2016',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Netflix cancelled after two seasons; Marco\'s place in Kublai Khan\'s court and the battle for empire were left open.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/61/153841.jpg',
    note: '',
  },
  {
    id: 7509,
    tvmazeId: '16007',
    title: 'Marriage, Not Dating',
    network: 'tvN',
    startYear: 2014,
    years: '2014',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/53/134182.jpg',
    note: '',
  },
  {
    id: 7510,
    tvmazeId: '310',
    title: 'Married',
    network: 'FX',
    startYear: 2014,
    years: '2014–2015',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/170/427163.jpg',
    note: '',
  },
  {
    id: 7511,
    tvmazeId: '129',
    title: 'Marry Me',
    network: 'NBC',
    startYear: 2014,
    years: '2014–2015',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/0/1836.jpg',
    note: '',
  },
  {
    id: 7512,
    tvmazeId: '308',
    title: 'Matador',
    network: 'El Rey Network',
    startYear: 2014,
    years: '2014',
    genres: ['Drama', 'Action'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/2/5061.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 313, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 295, "ended": 12349}};
