window.pageShows = [
  {
    id: 6389,
    tvmazeId: '17240',
    title: 'Hoot Hoot Go!',
    network: 'ABC Kids',
    startYear: 2016,
    years: '2016',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/58/145281.jpg',
    note: '',
  },
  {
    id: 6390,
    tvmazeId: '19616',
    title: 'Hooten & The Lady',
    network: 'Sky Showcase',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/74/185933.jpg',
    note: '',
  },
  {
    id: 6391,
    tvmazeId: '12523',
    title: 'Horace and Pete',
    network: 'LouisCK.net',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/43/109455.jpg',
    note: '',
  },
  {
    id: 6392,
    tvmazeId: '3601',
    title: 'Houdini & Doyle',
    network: 'ITV Encore',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/57/142605.jpg',
    note: '',
  },
  {
    id: 6393,
    tvmazeId: '73824',
    title: 'How to Be a Vampire',
    network: 'CW Seed',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/498/1247088.jpg',
    note: '',
  },
  {
    id: 6394,
    tvmazeId: '18647',
    title: 'HumanTown',
    network: 'CBC',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/395/988976.jpg',
    note: '',
  },
  {
    id: 6395,
    tvmazeId: '2178',
    title: 'Hunters',
    network: 'Syfy',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Science-Fiction', 'Thriller'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/47/118790.jpg',
    note: '',
  },
  {
    id: 6396,
    tvmazeId: '14841',
    title: 'Hwarang',
    network: 'KBS2',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Drama', 'Romance', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/532/1330910.jpg',
    note: '',
  },
  {
    id: 6397,
    tvmazeId: '20055',
    title: 'Hyde & Seek',
    network: 'Nine Network',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/85/213439.jpg',
    note: '',
  },
  {
    id: 6398,
    tvmazeId: '13324',
    title: 'I Love Dick',
    network: 'Prime Video',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/112/280892.jpg',
    note: '',
  },
  {
    id: 6399,
    tvmazeId: '18192',
    title: 'I Pranked My Parents!',
    network: 'WildBrainTV',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy', 'Children', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/61/153994.jpg',
    note: '',
  },
  {
    id: 6400,
    tvmazeId: '28758',
    title: 'I Ship It',
    network: 'CW Seed',
    startYear: 2016,
    years: '2016–2019',
    genres: ['Comedy', 'Music', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/184/462483.jpg',
    note: '',
  },
  {
    id: 6401,
    tvmazeId: '8695',
    title: 'I Want My Wife Back',
    network: 'BBC One',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/54/136016.jpg',
    note: '',
  },
  {
    id: 6402,
    tvmazeId: '19669',
    title: 'Ice',
    network: 'Audience Network',
    startYear: 2016,
    years: '2016–2018',
    genres: ['Drama', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/218/547095.jpg',
    note: '',
  },
  {
    id: 6403,
    tvmazeId: '5775',
    title: 'Idiotsitter',
    network: 'Comedy Central',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/52/131213.jpg',
    note: '',
  },
  {
    id: 6404,
    tvmazeId: '11550',
    title: 'Imaginary Friend',
    network: 'NBC',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 6405,
    tvmazeId: '22879',
    title: 'In Plain Sight',
    network: 'ITV1',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/88/220534.jpg',
    note: '',
  },
  {
    id: 6406,
    tvmazeId: '8798',
    title: 'Incorporated',
    network: 'Syfy',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Drama', 'Science-Fiction', 'Thriller'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/93/234846.jpg',
    note: '',
  },
  {
    id: 6407,
    tvmazeId: '18998',
    title: 'Inhuman Condition',
    network: 'YouTube',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Supernatural'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/184309.jpg',
    note: '',
  },
  {
    id: 6408,
    tvmazeId: '5967',
    title: 'Insecure',
    network: 'HBO',
    startYear: 2016,
    years: '2016–2021',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/485/1213250.jpg',
    note: '',
  },
  {
    id: 6409,
    tvmazeId: '15162',
    title: 'Interns of F.I.E.L.D.',
    network: 'YouTube',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 6410,
    tvmazeId: '20723',
    title: 'Invade All of the Humans!',
    network: 'Disney XD',
    startYear: 2016,
    years: '2016',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/183399.jpg',
    note: '',
  },
  {
    id: 6411,
    tvmazeId: '24199',
    title: 'Invisible',
    network: 'Jauntvr',
    startYear: 2016,
    years: '2016',
    genres: ['Drama', 'Science-Fiction', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/92/230003.jpg',
    note: '',
  },
  {
    id: 6412,
    tvmazeId: '20568',
    title: 'Içerde',
    network: 'Show TV',
    startYear: 2016,
    years: '2016–2017',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/72/181792.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 267, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
