window.pageShows = [
  {
    id: 1537,
    tvmazeId: '55423',
    title: 'Accused',
    network: 'FOX',
    startYear: 2023,
    years: '2023–2024',
    genres: ['Drama', 'Crime', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/537/1343369.jpg',
    note: '',
  },
  {
    id: 1538,
    tvmazeId: '65281',
    title: 'Act Your Age',
    network: 'Bounce',
    startYear: 2023,
    years: '2023',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/449/1123543.jpg',
    note: '',
  },
  {
    id: 1539,
    tvmazeId: '69676',
    title: 'Adhura',
    network: 'Prime Video',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Horror', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/487/1218481.jpg',
    note: '',
  },
  {
    id: 1540,
    tvmazeId: '56904',
    title: 'Adventure Time: Fionna and Cake',
    network: 'HBO Max',
    startYear: 2023,
    years: '2023–',
    genres: ['Action', 'Fantasy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: 'Completed its self-contained 10-episode story; all major arcs including Simon Petrikov\'s journey were fully resolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/604/1510959.jpg',
    note: '',
  },
  {
    id: 1541,
    tvmazeId: '68658',
    title: 'African Folktales Reimagined',
    network: 'Netflix',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/460/1152470.jpg',
    note: '',
  },
  {
    id: 1542,
    tvmazeId: '66140',
    title: 'After the Party',
    network: 'TVNZ 1',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/483/1209337.jpg',
    note: '',
  },
  {
    id: 1543,
    tvmazeId: '87052',
    title: 'Agent 203',
    network: 'ITVX',
    startYear: 2023,
    years: '2023',
    genres: ['Comedy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/587/1468223.jpg',
    note: '',
  },
  {
    id: 1544,
    tvmazeId: '43406',
    title: 'Agent Elvis',
    network: 'Netflix',
    startYear: 2023,
    years: '2023',
    genres: ['Comedy', 'Action', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/445/1114440.jpg',
    note: '',
  },
  {
    id: 1545,
    tvmazeId: '52343',
    title: 'Ahsoka',
    network: 'Disney+',
    startYear: 2023,
    years: '2023–',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/473/1184972.jpg',
    note: '',
  },
  {
    id: 1546,
    tvmazeId: '68382',
    title: 'Aktris',
    network: 'Disney+',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/458/1147044.jpg',
    note: '',
  },
  {
    id: 1547,
    tvmazeId: '62113',
    title: 'Alert: Missing Persons Unit',
    network: 'FOX',
    startYear: 2023,
    years: '2023–2025',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/558/1396027.jpg',
    note: '',
  },
  {
    id: 1548,
    tvmazeId: '41347',
    title: 'All the Light We Cannot See',
    network: 'Netflix',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Romance', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/485/1213361.jpg',
    note: '',
  },
  {
    id: 1549,
    tvmazeId: '67099',
    title: 'All the Liquors',
    network: 'Heavenly',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/564/1411836.jpg',
    note: '',
  },
  {
    id: 1550,
    tvmazeId: '71859',
    title: 'Alphonse',
    network: 'Prime Video',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/493/1234936.jpg',
    note: '',
  },
  {
    id: 1551,
    tvmazeId: '69996',
    title: 'Além do Guarda-Roupa',
    network: 'HBO Max',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Fantasy', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/469/1173766.jpg',
    note: '',
  },
  {
    id: 1552,
    tvmazeId: '72697',
    title: 'Amar é Para os Fortes',
    network: 'Prime Video',
    startYear: 2023,
    years: '2023',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/486/1216959.jpg',
    note: '',
  },
  {
    id: 1553,
    tvmazeId: '58168',
    title: 'American Born Chinese',
    network: 'Disney+',
    startYear: 2023,
    years: '2023',
    genres: ['Comedy', 'Action', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/458/1146100.jpg',
    note: '',
  },
  {
    id: 1554,
    tvmazeId: '72414',
    title: 'Analog Squad',
    network: 'Netflix',
    startYear: 2023,
    years: '2023',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/491/1228034.jpg',
    note: '',
  },
  {
    id: 1555,
    tvmazeId: '72157',
    title: 'Anderson Spider Silva',
    network: 'Paramount+',
    startYear: 2023,
    years: '2023',
    genres: ['Drama', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/483/1207777.jpg',
    note: '',
  },
  {
    id: 1556,
    tvmazeId: '66299',
    title: 'Angel',
    network: 'BET+',
    startYear: 2023,
    years: '2023',
    genres: ['Drama'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: '',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/441/1104678.jpg',
    note: '',
  },
  {
    id: 1557,
    tvmazeId: '67295',
    title: 'Angel Flight',
    network: 'Prime Video',
    startYear: 2023,
    years: '2023',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/452/1131768.jpg',
    note: '',
  },
  {
    id: 1558,
    tvmazeId: '63266',
    title: 'Animal Control',
    network: 'FOX',
    startYear: 2023,
    years: '2023–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/605/1513832.jpg',
    note: '',
  },
  {
    id: 1559,
    tvmazeId: '59249',
    title: 'Anne Rice\'s Mayfair Witches',
    network: 'AMC+',
    startYear: 2023,
    years: '2023–',
    genres: ['Drama', 'Fantasy', 'Supernatural'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/548/1371382.jpg',
    note: '',
  },
  {
    id: 1560,
    tvmazeId: '68472',
    title: 'Appetite',
    network: 'SBS On Demand',
    startYear: 2023,
    years: '2023',
    genres: ['Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/459/1148533.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 65, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
