window.pageShows = [
  {
    id: 8257,
    tvmazeId: '47876',
    title: 'Batman of Shanghai',
    network: 'Cartoon Network',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/255/639009.jpg',
    note: '',
  },
  {
    id: 8258,
    tvmazeId: '7403',
    title: 'Battlefield Friends',
    network: 'YouTube',
    startYear: 2012,
    years: '2012–2016',
    genres: ['Comedy', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/68210.jpg',
    note: '',
  },
  {
    id: 8259,
    tvmazeId: '7214',
    title: 'Battleground',
    network: 'Hulu',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/67161.jpg',
    note: '',
  },
  {
    id: 8260,
    tvmazeId: '870',
    title: 'Battlestar Galactica: Blood & Chrome',
    network: 'Syfy',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/15949.jpg',
    note: '',
  },
  {
    id: 8261,
    tvmazeId: '155',
    title: 'Beauty & the Beast',
    network: 'The CW',
    startYear: 2012,
    years: '2012–2016',
    genres: ['Action', 'Romance', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: 'CW ran for four seasons and concluded Cat and Vincent\'s romance with a proper finale.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/0/2128.jpg',
    note: '',
  },
  {
    id: 8262,
    tvmazeId: '1264',
    title: 'Ben 10: Omniverse',
    network: 'Cartoon Network',
    startYear: 2012,
    years: '2012–2014',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/18280.jpg',
    note: '',
  },
  {
    id: 8263,
    tvmazeId: '2210',
    title: 'Ben and Kate',
    network: 'FOX',
    startYear: 2012,
    years: '2012–2013',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/12/30570.jpg',
    note: '',
  },
  {
    id: 8264,
    tvmazeId: '4569',
    title: 'Bent',
    network: 'NBC',
    startYear: 2012,
    years: '2012',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/52211.jpg',
    note: '',
  },
  {
    id: 8265,
    tvmazeId: '5332',
    title: 'Best Friends Forever',
    network: 'NBC',
    startYear: 2012,
    years: '2012',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/55312.jpg',
    note: '',
  },
  {
    id: 8266,
    tvmazeId: '72890',
    title: 'Big Block SingSong',
    network: 'CBC',
    startYear: 2012,
    years: '2012–2017',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/488/1221119.jpg',
    note: '',
  },
  {
    id: 8267,
    tvmazeId: '7280',
    title: 'Bikie Wars: Brothers in Arms',
    network: 'Network 10',
    startYear: 2012,
    years: '2012',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/67607.jpg',
    note: '',
  },
  {
    id: 8268,
    tvmazeId: '1071',
    title: 'Birdsong',
    network: 'BBC One',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Romance', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17100.jpg',
    note: '',
  },
  {
    id: 8269,
    tvmazeId: '273',
    title: 'Black Dynamite',
    network: 'Adult Swim',
    startYear: 2012,
    years: '2012–2015',
    genres: ['Comedy', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/1/4742.jpg',
    note: '',
  },
  {
    id: 8270,
    tvmazeId: '5739',
    title: 'Blackout',
    network: 'BBC One',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Action', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/57293.jpg',
    note: '',
  },
  {
    id: 8271,
    tvmazeId: '41023',
    title: 'Blood Cell',
    network: 'The WB',
    startYear: 2012,
    years: '2012',
    genres: ['Horror', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/184/460895.jpg',
    note: '',
  },
  {
    id: 8272,
    tvmazeId: '3356',
    title: 'Blue',
    network: 'Hulu',
    startYear: 2012,
    years: '2012–2014',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/17/44273.jpg',
    note: '',
  },
  {
    id: 8273,
    tvmazeId: '1073',
    title: 'Bomb Girls',
    network: 'Global',
    startYear: 2012,
    years: '2012–2013',
    genres: ['Drama', 'Romance', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/17549.jpg',
    note: '',
  },
  {
    id: 8274,
    tvmazeId: '28748',
    title: 'Bondi Hipsters',
    network: 'YouTube',
    startYear: 2012,
    years: '2012–2014',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/114/286720.jpg',
    note: '',
  },
  {
    id: 8275,
    tvmazeId: '5236',
    title: 'Bravest Warriors',
    network: 'VRV Select',
    startYear: 2012,
    years: '2012–2018',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/54781.jpg',
    note: '',
  },
  {
    id: 8276,
    tvmazeId: '277',
    title: 'Brickleberry',
    network: 'Comedy Central',
    startYear: 2012,
    years: '2012–2015',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/1/4787.jpg',
    note: '',
  },
  {
    id: 8277,
    tvmazeId: '2852',
    title: 'Bridal Mask',
    network: 'KBS2',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Action', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/15/38709.jpg',
    note: '',
  },
  {
    id: 8278,
    tvmazeId: '3560',
    title: 'Bullet in the Face',
    network: 'IFC',
    startYear: 2012,
    years: '2012',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/46702.jpg',
    note: '',
  },
  {
    id: 8279,
    tvmazeId: '871',
    title: 'Bunheads',
    network: 'Freeform',
    startYear: 2012,
    years: '2012–2013',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/15953.jpg',
    note: '',
  },
  {
    id: 8280,
    tvmazeId: '394',
    title: 'Call the Midwife',
    network: 'BBC One',
    startYear: 2012,
    years: '2012–',
    genres: ['Drama', 'Medical', 'History'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/608/1520011.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 345, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
