window.pageShows = [
  {
    id: 2689,
    tvmazeId: '69516',
    title: 'Petronix Defenders',
    network: 'Tiny Pop',
    startYear: 2022,
    years: '2022–2023',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/466/1166038.jpg',
    note: '',
  },
  {
    id: 2690,
    tvmazeId: '65365',
    title: 'Pewnego razu na krajowej jedynce',
    network: 'Netflix',
    startYear: 2022,
    years: '2022–',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/432/1081663.jpg',
    note: '',
  },
  {
    id: 2691,
    tvmazeId: '63603',
    title: 'Pfffirates',
    network: 'BBC iPlayer',
    startYear: 2022,
    years: '2022',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/419/1048174.jpg',
    note: '',
  },
  {
    id: 2692,
    tvmazeId: '64285',
    title: 'Phantom Pups',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy', 'Children', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/424/1060273.jpg',
    note: '',
  },
  {
    id: 2693,
    tvmazeId: '40864',
    title: 'Pieces of Her',
    network: 'Netflix',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/397/994412.jpg',
    note: '',
  },
  {
    id: 2694,
    tvmazeId: '60728',
    title: 'Pillow Talk',
    network: 'Crave',
    startYear: 2022,
    years: '2022–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/397/994597.jpg',
    note: '',
  },
  {
    id: 2695,
    tvmazeId: '61090',
    title: 'Pinecone & Pony',
    network: 'Apple TV',
    startYear: 2022,
    years: '2022–2023',
    genres: ['Adventure', 'Children'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/445/1113323.jpg',
    note: '',
  },
  {
    id: 2696,
    tvmazeId: '52918',
    title: 'Pistol',
    network: 'Hulu',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Music', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/407/1019117.jpg',
    note: '',
  },
  {
    id: 2697,
    tvmazeId: '57796',
    title: 'Pitch Perfect: Bumper in Berlin',
    network: 'Peacock',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy', 'Music'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/430/1075508.jpg',
    note: '',
  },
  {
    id: 2698,
    tvmazeId: '47411',
    title: 'Pivoting',
    network: 'FOX',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/402/1006401.jpg',
    note: '',
  },
  {
    id: 2699,
    tvmazeId: '57178',
    title: 'Players',
    network: 'Paramount+',
    startYear: 2022,
    years: '2022',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/408/1020518.jpg',
    note: '',
  },
  {
    id: 2700,
    tvmazeId: '65228',
    title: 'Pop Paper City',
    network: '5',
    startYear: 2022,
    years: '2022–2023',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/430/1077183.jpg',
    note: '',
  },
  {
    id: 2701,
    tvmazeId: '54014',
    title: 'Porno y Helado',
    network: 'Prime Video',
    startYear: 2022,
    years: '2022–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/407/1018908.jpg',
    note: '',
  },
  {
    id: 2702,
    tvmazeId: '46213',
    title: 'Power Book IV: Force',
    network: 'STARZ',
    startYear: 2022,
    years: '2022–2026',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/474/1187423.jpg',
    note: '',
  },
  {
    id: 2703,
    tvmazeId: '50637',
    title: 'Pretty Little Liars',
    network: 'HBO Max',
    startYear: 2022,
    years: '2022–2024',
    genres: ['Drama', 'Horror', 'Thriller'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/521/1303358.jpg',
    note: '',
  },
  {
    id: 2704,
    tvmazeId: '60428',
    title: 'Pretzel and the Puppies',
    network: 'Apple TV',
    startYear: 2022,
    years: '2022–2023',
    genres: ['Children'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/447/1118520.jpg',
    note: '',
  },
  {
    id: 2705,
    tvmazeId: '89199',
    title: 'Primate',
    network: 'Prime Video',
    startYear: 2022,
    years: '2022–2024',
    genres: ['Drama', 'Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/604/1511795.jpg',
    note: '',
  },
  {
    id: 2706,
    tvmazeId: '63635',
    title: 'Prisma',
    network: 'Prime Video',
    startYear: 2022,
    years: '2022–2024',
    genres: ['Drama', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/522/1306376.jpg',
    note: '',
  },
  {
    id: 2707,
    tvmazeId: '54382',
    title: 'Promised Land',
    network: 'Hulu',
    startYear: 2022,
    years: '2022',
    genres: ['Drama', 'Family'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'ABC cancelled after one season; the Sandoval winery family power struggle was just developing.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/446/1115994.jpg',
    note: '',
  },
  {
    id: 2708,
    tvmazeId: '83614',
    title: 'Puffins Impossible',
    network: 'Apple TV',
    startYear: 2022,
    years: '2022',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/561/1403057.jpg',
    note: '',
  },
  {
    id: 2709,
    tvmazeId: '63573',
    title: 'Pulse',
    network: 'Showmax',
    startYear: 2022,
    years: '2022–',
    genres: ['Horror', 'Science-Fiction', 'Thriller'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/418/1047387.jpg',
    note: '',
  },
  {
    id: 2710,
    tvmazeId: '74671',
    title: 'Putham Pudhu Kaalai Vidiyaadhaa',
    network: 'Prime Video',
    startYear: 2022,
    years: '2022',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/504/1260650.jpg',
    note: '',
  },
  {
    id: 2711,
    tvmazeId: '61660',
    title: 'Pálpito',
    network: 'Netflix',
    startYear: 2022,
    years: '2022–2023',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/405/1013941.jpg',
    note: '',
  },
  {
    id: 2712,
    tvmazeId: '59958',
    title: 'Quantum Leap',
    network: 'NBC',
    startYear: 2022,
    years: '2022–2024',
    genres: ['Drama', 'Science-Fiction', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/479/1198798.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 113, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 239, "ended": 12349}};
