window.pageShows = [
  {
    id: 6097,
    tvmazeId: '32596',
    title: 'Sunshine',
    network: 'SBS',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Crime', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/146/366265.jpg',
    note: '',
  },
  {
    id: 6098,
    tvmazeId: '21821',
    title: 'Super Monsters',
    network: 'Netflix',
    startYear: 2017,
    years: '2017–2021',
    genres: ['Adventure', 'Children', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/131/328023.jpg',
    note: '',
  },
  {
    id: 6099,
    tvmazeId: '37994',
    title: 'Superhigh',
    network: 'Blackpills',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/162/406815.jpg',
    note: '',
  },
  {
    id: 6100,
    tvmazeId: '12114',
    title: 'Superior Donuts',
    network: 'CBS',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Comedy', 'Food'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/147/369387.jpg',
    note: '',
  },
  {
    id: 6101,
    tvmazeId: '25721',
    title: 'Superstition',
    network: 'Syfy',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Drama', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/131/327760.jpg',
    note: '',
  },
  {
    id: 6102,
    tvmazeId: '39182',
    title: 'Surrogate',
    network: 'Blackpills',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/172/430313.jpg',
    note: '',
  },
  {
    id: 6103,
    tvmazeId: '26157',
    title: 'Suspicious Partner',
    network: 'SBS',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy', 'Romance', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/111/278231.jpg',
    note: '',
  },
  {
    id: 6104,
    tvmazeId: '3593',
    title: 'Taboo',
    network: 'BBC One',
    startYear: 2017,
    years: '2017–',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/137/343264.jpg',
    note: '',
  },
  {
    id: 6105,
    tvmazeId: '3822',
    title: 'Taken',
    network: 'NBC',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Action', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/137/343530.jpg',
    note: '',
  },
  {
    id: 6106,
    tvmazeId: '16314',
    title: 'Tales',
    network: 'BET',
    startYear: 2017,
    years: '2017–',
    genres: ['Drama', 'Crime', 'Music'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/425/1063395.jpg',
    note: '',
  },
  {
    id: 6107,
    tvmazeId: '58313',
    title: 'Tali\'s Wedding Diary',
    network: 'Showmax',
    startYear: 2017,
    years: '2017',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 6108,
    tvmazeId: '19682',
    title: 'Tarantula',
    network: 'TBS.com',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/404/1012385.jpg',
    note: '',
  },
  {
    id: 6109,
    tvmazeId: '19771',
    title: 'Ten Days in the Valley',
    network: 'ABC',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Drama', 'Thriller', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'ABC cancelled after one season; Jane\'s kidnapped daughter and the conspiracy were left unresolved.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/123/308563.jpg',
    note: '',
  },
  {
    id: 6110,
    tvmazeId: '34049',
    title: 'Tender Touches',
    network: 'Adult Swim',
    startYear: 2017,
    years: '2017–',
    genres: ['Drama', 'Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/174/435907.jpg',
    note: '',
  },
  {
    id: 6111,
    tvmazeId: '8793',
    title: 'The Arrangement',
    network: 'E!',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/486/1215678.jpg',
    note: '',
  },
  {
    id: 6112,
    tvmazeId: '49983',
    title: 'The Babysitter',
    network: 'Netflix',
    startYear: 2017,
    years: '2017–2020',
    genres: ['Comedy', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/579/1448673.jpg',
    note: '',
  },
  {
    id: 6113,
    tvmazeId: '39560',
    title: 'The Back Pages',
    network: 'YouTube',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy', 'Fantasy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/173/434406.jpg',
    note: '',
  },
  {
    id: 6114,
    tvmazeId: '54839',
    title: 'The Bagel and Becky Show',
    network: 'Cartoon Network',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/309/774520.jpg',
    note: '',
  },
  {
    id: 6115,
    tvmazeId: '17162',
    title: 'The Blacklist: Redemption',
    network: 'NBC',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/99/248555.jpg',
    note: '',
  },
  {
    id: 6116,
    tvmazeId: '15324',
    title: 'The Bold Type',
    network: 'Freeform',
    startYear: 2017,
    years: '2017–2021',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/342/857240.jpg',
    note: '',
  },
  {
    id: 6117,
    tvmazeId: '31114',
    title: 'The Boonies',
    network: 'go90',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/124/310118.jpg',
    note: '',
  },
  {
    id: 6118,
    tvmazeId: '24623',
    title: 'The Brave',
    network: 'NBC',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Drama', 'Action', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/123/307553.jpg',
    note: '',
  },
  {
    id: 6119,
    tvmazeId: '13140',
    title: 'The Breaks',
    network: 'BET',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/99/248198.jpg',
    note: '',
  },
  {
    id: 6120,
    tvmazeId: '34420',
    title: 'The Canadians',
    network: 'Prime Video',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/142/356654.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 255, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
