window.pageShows = [
  {
    id: 8209,
    tvmazeId: '4648',
    title: 'Hotel Babylon',
    network: 'BBC One',
    startYear: 2006,
    years: '2006–2009',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/52605.jpg',
    note: '',
  },
  {
    id: 8210,
    tvmazeId: '46444',
    title: 'Hotel Erotica Cabo',
    network: 'Cinemax',
    startYear: 2006,
    years: '2006',
    genres: ['Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 8211,
    tvmazeId: '6903',
    title: 'Hyperdrive',
    network: 'BBC Two',
    startYear: 2006,
    years: '2006–2007',
    genres: ['Comedy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/65096.jpg',
    note: '',
  },
  {
    id: 8212,
    tvmazeId: '33105',
    title: 'I\'m with Stupid',
    network: 'BBC Three',
    startYear: 2006,
    years: '2006',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/133/334138.jpg',
    note: '',
  },
  {
    id: 8213,
    tvmazeId: '4753',
    title: 'In Justice',
    network: 'ABC',
    startYear: 2006,
    years: '2006',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/53091.jpg',
    note: '',
  },
  {
    id: 8214,
    tvmazeId: '4557',
    title: 'Intelligence',
    network: 'CBC',
    startYear: 2006,
    years: '2006–2007',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/52139.jpg',
    note: '',
  },
  {
    id: 8215,
    tvmazeId: '15543',
    title: 'It\'s a Big Big World',
    network: 'PBS',
    startYear: 2006,
    years: '2006–2007',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/52/131829.jpg',
    note: '',
  },
  {
    id: 8216,
    tvmazeId: '10888',
    title: 'Jam and Jerusalem',
    network: 'BBC One',
    startYear: 2006,
    years: '2006–2009',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/36/91702.jpg',
    note: '',
  },
  {
    id: 8217,
    tvmazeId: '10492',
    title: 'Jane and the Dragon',
    network: 'YTV',
    startYear: 2006,
    years: '2006',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/35/88660.jpg',
    note: '',
  },
  {
    id: 8218,
    tvmazeId: '2359',
    title: 'Jane Eyre',
    network: 'BBC One',
    startYear: 2006,
    years: '2006',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/12/32138.jpg',
    note: '',
  },
  {
    id: 8219,
    tvmazeId: '20954',
    title: 'Jane Hall',
    network: 'ITV1',
    startYear: 2006,
    years: '2006',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/73/184920.jpg',
    note: '',
  },
  {
    id: 8220,
    tvmazeId: '795',
    title: 'Jericho',
    network: 'CBS',
    startYear: 2006,
    years: '2006–2008',
    genres: ['Drama', 'Action', 'Science-Fiction'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'CBS cancelled twice; the civil war and Hawkins\'s mission to expose the conspiracy were left unresolved on screen (a comics continuation existed but the TV story was never concluded).',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/495/1239461.jpg',
    note: '',
  },
  {
    id: 8221,
    tvmazeId: '31788',
    title: 'Johnny and the Bomb',
    network: 'BBC One',
    startYear: 2006,
    years: '2006',
    genres: ['Drama', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/127/318466.jpg',
    note: '',
  },
  {
    id: 8222,
    tvmazeId: '68827',
    title: 'Jozi-H',
    network: 'CBC',
    startYear: 2006,
    years: '2006–2007',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/462/1155044.jpg',
    note: '',
  },
  {
    id: 8223,
    tvmazeId: '40538',
    title: 'Just for Kicks',
    network: 'Nickelodeon',
    startYear: 2006,
    years: '2006',
    genres: ['Drama', 'Comedy', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/181/453170.jpg',
    note: '',
  },
  {
    id: 8224,
    tvmazeId: '4705',
    title: 'Justice',
    network: 'FOX',
    startYear: 2006,
    years: '2006',
    genres: ['Drama', 'Crime', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/52948.jpg',
    note: '',
  },
  {
    id: 8225,
    tvmazeId: '16265',
    title: 'Kappa Mikey',
    network: 'Nicktoons',
    startYear: 2006,
    years: '2006–2008',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/54/135683.jpg',
    note: '',
  },
  {
    id: 8226,
    tvmazeId: '1278',
    title: 'Kidnapped',
    network: 'NBC',
    startYear: 2006,
    years: '2006–2007',
    genres: ['Crime', 'Thriller'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'NBC cancelled after one season mid-story; the Leopold Cain kidnapping was resolved hastily due to the cancellation.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/18372.jpg',
    note: '',
  },
  {
    id: 8227,
    tvmazeId: '40355',
    title: 'Kim Possible and the New Incredible Super Piglet',
    network: 'Disney Channel',
    startYear: 2006,
    years: '2006',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 8228,
    tvmazeId: '22476',
    title: 'Korgoth of Barbaria',
    network: 'AdultSwim.com',
    startYear: 2006,
    years: '2006',
    genres: ['Comedy', 'Action'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/82/207079.jpg',
    note: '',
  },
  {
    id: 8229,
    tvmazeId: '800',
    title: 'Kyle XY',
    network: 'Freeform',
    startYear: 2006,
    years: '2006–2009',
    genres: ['Drama', 'Science-Fiction', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/15591.jpg',
    note: '',
  },
  {
    id: 8230,
    tvmazeId: '4025',
    title: 'Lead Balloon',
    network: 'BBC Two',
    startYear: 2006,
    years: '2006–2011',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/19/49567.jpg',
    note: '',
  },
  {
    id: 8231,
    tvmazeId: '15771',
    title: 'Legend of the Dragon',
    network: 'CBBC',
    startYear: 2006,
    years: '2006–2008',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/53/132942.jpg',
    note: '',
  },
  {
    id: 8232,
    tvmazeId: '3615',
    title: 'Legion of Super Heroes',
    network: 'The CW',
    startYear: 2006,
    years: '2006–2008',
    genres: ['Children', 'Fantasy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/46938.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 343, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 824, "cliffhanger": 237, "ended": 13574}};
