window.pageShows = [
  {
    id: 8957,
    tvmazeId: '45813',
    title: 'Hounded',
    network: 'CBBC',
    startYear: 2010,
    years: '2010',
    genres: ['Drama', 'Comedy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/235/589586.jpg',
    note: '',
  },
  {
    id: 8958,
    tvmazeId: '1210',
    title: 'How to Make It in America',
    network: 'HBO',
    startYear: 2010,
    years: '2010–2011',
    genres: ['Drama', 'Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/421/1052878.jpg',
    note: '',
  },
  {
    id: 8959,
    tvmazeId: '7609',
    title: 'Huge',
    network: 'Freeform',
    startYear: 2010,
    years: '2010',
    genres: ['Drama'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/70124.jpg',
    note: '',
  },
  {
    id: 8960,
    tvmazeId: '163',
    title: 'Human Target',
    network: 'FOX',
    startYear: 2010,
    years: '2010–2011',
    genres: ['Action', 'Adventure', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/42/106702.jpg',
    note: '',
  },
  {
    id: 8961,
    tvmazeId: '7161',
    title: 'I Rock',
    network: 'ABC Family',
    startYear: 2010,
    years: '2010',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/66960.jpg',
    note: '',
  },
  {
    id: 8962,
    tvmazeId: '7276',
    title: 'Identity',
    network: 'ITV1',
    startYear: 2010,
    years: '2010',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/67599.jpg',
    note: '',
  },
  {
    id: 8963,
    tvmazeId: '31141',
    title: 'In Between Men',
    network: 'YouTube',
    startYear: 2010,
    years: '2010–2013',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 8964,
    tvmazeId: '8465',
    title: 'Iron Man: Extremis',
    network: 'iTunes',
    startYear: 2010,
    years: '2010',
    genres: ['Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/30/75420.jpg',
    note: '',
  },
  {
    id: 8965,
    tvmazeId: '3662',
    title: 'Jack Taylor',
    network: 'Virgin Media One',
    startYear: 2010,
    years: '2010–2016',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/18/47329.jpg',
    note: '',
  },
  {
    id: 8966,
    tvmazeId: '30275',
    title: 'Jazmin\'s Touch',
    network: 'Playboy TV',
    startYear: 2010,
    years: '2010',
    genres: ['Fantasy', 'Adult'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/204/510758.jpg',
    note: '',
  },
  {
    id: 8967,
    tvmazeId: '12070',
    title: 'Jim Henson\'s Pajanimals',
    network: 'Universal Kids',
    startYear: 2010,
    years: '2010–2013',
    genres: ['Children', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/40/101238.jpg',
    note: '',
  },
  {
    id: 8968,
    tvmazeId: '54193',
    title: 'Jonah Hex: Motion Comics',
    network: 'The WB',
    startYear: 2010,
    years: '2010',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/300/750886.jpg',
    note: '',
  },
  {
    id: 8969,
    tvmazeId: '12221',
    title: 'JourneyQuest',
    network: 'YouTube',
    startYear: 2010,
    years: '2010–2018',
    genres: ['Comedy', 'Adventure', 'Fantasy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/41/102926.jpg',
    note: '',
  },
  {
    id: 8970,
    tvmazeId: '11165',
    title: 'Just William',
    network: 'BBC One',
    startYear: 2010,
    years: '2010',
    genres: ['Drama', 'Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/37/93677.jpg',
    note: '',
  },
  {
    id: 8971,
    tvmazeId: '106',
    title: 'Justified',
    network: 'FX',
    startYear: 2010,
    years: '2010–2015',
    genres: ['Drama', 'Crime', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/0/808.jpg',
    note: '',
  },
  {
    id: 8972,
    tvmazeId: '18765',
    title: 'Kick Buttowski: Suburban Daredevil',
    network: 'Disney XD',
    startYear: 2010,
    years: '2010–2012',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/64/161975.jpg',
    note: '',
  },
  {
    id: 8973,
    tvmazeId: '14635',
    title: 'King of Baking, Kim Tak Goo',
    network: 'KBS2',
    startYear: 2010,
    years: '2010',
    genres: ['Food', 'Family', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/156/391456.jpg',
    note: '',
  },
  {
    id: 8974,
    tvmazeId: '7190',
    title: 'Klass: Elu pärast',
    network: 'ETV',
    startYear: 2010,
    years: '2010',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/67102.jpg',
    note: '',
  },
  {
    id: 8975,
    tvmazeId: '4766',
    title: 'La La Land',
    network: 'Paramount+ with Showtime',
    startYear: 2010,
    years: '2010',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/53107.jpg',
    note: '',
  },
  {
    id: 8976,
    tvmazeId: '867',
    title: 'Law & Order: LA',
    network: 'NBC',
    startYear: 2010,
    years: '2010–2011',
    genres: ['Drama', 'Crime', 'Legal'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/262/657208.jpg',
    note: '',
  },
  {
    id: 8977,
    tvmazeId: '993',
    title: 'Life Unexpected',
    network: 'The CW',
    startYear: 2010,
    years: '2010–2011',
    genres: ['Drama', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/502/1256337.jpg',
    note: '',
  },
  {
    id: 8978,
    tvmazeId: '1114',
    title: 'Lip Service',
    network: 'BBC Three',
    startYear: 2010,
    years: '2010–2012',
    genres: ['Drama', 'Romance'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/17247.jpg',
    note: '',
  },
  {
    id: 8979,
    tvmazeId: '31933',
    title: 'Little Crackers',
    network: 'Sky Showcase',
    startYear: 2010,
    years: '2010–2012',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/127/319472.jpg',
    note: '',
  },
  {
    id: 8980,
    tvmazeId: '7526',
    title: 'Living in Your Car',
    network: 'HBO',
    startYear: 2010,
    years: '2010–2011',
    genres: ['Drama', 'Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/122/306083.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 374, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
