window.pageShows = [
  {
    id: 5809,
    tvmazeId: '33446',
    title: 'How to Buy a Baby',
    network: 'CBC Gem',
    startYear: 2017,
    years: '2017–2019',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/202/506942.jpg',
    note: '',
  },
  {
    id: 5810,
    tvmazeId: '25396',
    title: 'Howards End',
    network: 'BBC One',
    startYear: 2017,
    years: '2017',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/138/347200.jpg',
    note: '',
  },
  {
    id: 5811,
    tvmazeId: '25383',
    title: 'Hunter Street',
    network: 'TeenNick',
    startYear: 2017,
    years: '2017–2021',
    genres: ['Children', 'Family', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/208/520012.jpg',
    note: '',
  },
  {
    id: 5812,
    tvmazeId: '28749',
    title: 'Hyperlinked',
    network: 'YouTube Premium',
    startYear: 2017,
    years: '2017',
    genres: ['Children', 'Family', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/116/290272.jpg',
    note: '',
  },
  {
    id: 5813,
    tvmazeId: '30190',
    title: 'I Am Frankie',
    network: 'Nickelodeon',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/125/313077.jpg',
    note: '',
  },
  {
    id: 5814,
    tvmazeId: '2780',
    title: 'I\'m Dying Up Here',
    network: 'Paramount+ with Showtime',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Drama', 'Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/331/828831.jpg',
    note: '',
  },
  {
    id: 5815,
    tvmazeId: '35292',
    title: 'I\'m Fine',
    network: 'Dekkoo',
    startYear: 2017,
    years: '2017–2019',
    genres: ['Drama', 'Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/149/373677.jpg',
    note: '',
  },
  {
    id: 5816,
    tvmazeId: '25342',
    title: 'I\'m Sorry',
    network: 'truTV',
    startYear: 2017,
    years: '2017–2019',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/118/296874.jpg',
    note: '',
  },
  {
    id: 5817,
    tvmazeId: '30466',
    title: 'Ill Behaviour',
    network: 'BBC iPlayer',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Comedy', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/126/315743.jpg',
    note: '',
  },
  {
    id: 5818,
    tvmazeId: '17129',
    title: 'Imaginary Mary',
    network: 'ABC',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy', 'Family', 'Fantasy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/104/261611.jpg',
    note: '',
  },
  {
    id: 5819,
    tvmazeId: '4144',
    title: 'Imposters',
    network: 'Bravo',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/153/382966.jpg',
    note: '',
  },
  {
    id: 5820,
    tvmazeId: '11861',
    title: 'In the Dark',
    network: 'BBC One',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/132/331680.jpg',
    note: '',
  },
  {
    id: 5821,
    tvmazeId: '31700',
    title: 'In the Vault',
    network: 'go90',
    startYear: 2017,
    years: '2017–2022',
    genres: ['Drama', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/143/358363.jpg',
    note: '',
  },
  {
    id: 5822,
    tvmazeId: '25084',
    title: 'Ingobernable',
    network: 'Netflix',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/167/419596.jpg',
    note: '',
  },
  {
    id: 5823,
    tvmazeId: '46020',
    title: 'InMates',
    network: 'TVFPlay',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/238/596446.jpg',
    note: '',
  },
  {
    id: 5824,
    tvmazeId: '30403',
    title: 'Inside Edge',
    network: 'Prime Video',
    startYear: 2017,
    years: '2017–2021',
    genres: ['Drama', 'Sports'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/380/952378.jpg',
    note: '',
  },
  {
    id: 5825,
    tvmazeId: '55964',
    title: 'It\'s Fine',
    network: 'Prime Video',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/330/825888.jpg',
    note: '',
  },
  {
    id: 5826,
    tvmazeId: '16065',
    title: 'Jamestown',
    network: 'Sky Showcase',
    startYear: 2017,
    years: '2017–2019',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/152/381138.jpg',
    note: '',
  },
  {
    id: 5827,
    tvmazeId: '23572',
    title: 'Jeff & Some Aliens',
    network: 'Comedy Central',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/90/225863.jpg',
    note: '',
  },
  {
    id: 5828,
    tvmazeId: '21735',
    title: 'jerks.',
    network: 'Joyn',
    startYear: 2017,
    years: '2017–2023',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/395/987553.jpg',
    note: '',
  },
  {
    id: 5829,
    tvmazeId: '41988',
    title: 'Johnny Christ',
    network: 'Blackpills',
    startYear: 2017,
    years: '2017',
    genres: ['Drama'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/193/484739.jpg',
    note: '',
  },
  {
    id: 5830,
    tvmazeId: '33453',
    title: 'Judge Rinder\'s Crown Court',
    network: 'ITV1',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Crime'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/138/345139.jpg',
    note: '',
  },
  {
    id: 5831,
    tvmazeId: '25763',
    title: 'Julie\'s Greenroom',
    network: 'Netflix',
    startYear: 2017,
    years: '2017',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/100/251674.jpg',
    note: '',
  },
  {
    id: 5832,
    tvmazeId: '28873',
    title: 'Junior',
    network: 'Blackpills',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/115/287706.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 243, "totalPages": 719, "perPage": 24, "stats": {"total": 17244, "cancelled": 2246, "cliffhanger": 295, "ended": 12349}};
