window.pageShows = [
  {
    id: 11281,
    tvmazeId: '11002',
    title: 'Bucky O\'Hare and the Toad Wars',
    network: 'Syndication',
    startYear: 1992,
    years: '1992',
    genres: ['Family', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/36/92414.jpg',
    note: '',
  },
  {
    id: 11282,
    tvmazeId: '31800',
    title: 'By Way of the Stars',
    network: 'CBC',
    startYear: 1992,
    years: '1992–1993',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/127/318669.jpg',
    note: '',
  },
  {
    id: 11283,
    tvmazeId: '4680',
    title: 'California Dreams',
    network: 'NBC',
    startYear: 1992,
    years: '1992–1996',
    genres: ['Comedy', 'Family', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/52815.jpg',
    note: '',
  },
  {
    id: 11284,
    tvmazeId: '13616',
    title: 'Camp Wilder',
    network: 'ABC',
    startYear: 1992,
    years: '1992–1993',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/47/117504.jpg',
    note: '',
  },
  {
    id: 11285,
    tvmazeId: '30648',
    title: 'Capitol Critters',
    network: 'ABC',
    startYear: 1992,
    years: '1992',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/121/304037.jpg',
    note: '',
  },
  {
    id: 11286,
    tvmazeId: '10928',
    title: 'Civvies',
    network: 'BBC One',
    startYear: 1992,
    years: '1992',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/36/91923.jpg',
    note: '',
  },
  {
    id: 11287,
    tvmazeId: '8974',
    title: 'Conan the Adventurer',
    network: 'FOX',
    startYear: 1992,
    years: '1992–1993',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/79700.jpg',
    note: '',
  },
  {
    id: 11288,
    tvmazeId: '26818',
    title: 'Covington Cross',
    network: 'ABC',
    startYear: 1992,
    years: '1992',
    genres: ['Drama', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/364/912384.jpg',
    note: '',
  },
  {
    id: 11289,
    tvmazeId: '51060',
    title: 'Crime Story',
    network: 'ITV1',
    startYear: 1992,
    years: '1992–1995',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11290,
    tvmazeId: '58537',
    title: 'Crossroads',
    network: 'ABC',
    startYear: 1992,
    years: '1992–1993',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/526/1315769.jpg',
    note: '',
  },
  {
    id: 11291,
    tvmazeId: '50799',
    title: 'Cruel Doubt',
    network: 'NBC',
    startYear: 1992,
    years: '1992',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/275/689377.jpg',
    note: '',
  },
  {
    id: 11292,
    tvmazeId: '36871',
    title: 'Dangerous Curves',
    network: 'CBS',
    startYear: 1992,
    years: '1992–1993',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/156/391562.jpg',
    note: '',
  },
  {
    id: 11293,
    tvmazeId: '50806',
    title: 'Deadly Matrimony',
    network: 'NBC',
    startYear: 1992,
    years: '1992',
    genres: ['Drama', 'Crime', 'Legal'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/276/690084.jpg',
    note: '',
  },
  {
    id: 11294,
    tvmazeId: '58610',
    title: 'Delta',
    network: 'ABC',
    startYear: 1992,
    years: '1992–1993',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11295,
    tvmazeId: '3307',
    title: 'Diagnosis: Murder',
    network: 'CBS',
    startYear: 1992,
    years: '1992–2002',
    genres: ['Drama', 'Crime', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/17/44006.jpg',
    note: '',
  },
  {
    id: 11296,
    tvmazeId: '58631',
    title: 'Dog City',
    network: 'FOX',
    startYear: 1992,
    years: '1992–1994',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/370/925522.jpg',
    note: '',
  },
  {
    id: 11297,
    tvmazeId: '91995',
    title: 'Don\'t Tell Father',
    network: 'BBC One',
    startYear: 1992,
    years: '1992',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/625/1563902.jpg',
    note: '',
  },
  {
    id: 11298,
    tvmazeId: '47188',
    title: 'Down the Shore',
    network: 'FOX',
    startYear: 1992,
    years: '1992–1993',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/251/628968.jpg',
    note: '',
  },
  {
    id: 11299,
    tvmazeId: '84593',
    title: 'Downtown Lagos',
    network: 'BBC Two',
    startYear: 1992,
    years: '1992',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 11300,
    tvmazeId: '46897',
    title: 'Drug Wars: The Cocaine Cartel',
    network: 'NBC',
    startYear: 1992,
    years: '1992',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/248/620442.jpg',
    note: '',
  },
  {
    id: 11301,
    tvmazeId: '12825',
    title: 'Eek! the Cat',
    network: 'FOX',
    startYear: 1992,
    years: '1992–1997',
    genres: ['Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/43/109757.jpg',
    note: '',
  },
  {
    id: 11302,
    tvmazeId: '6500',
    title: 'Eldorado',
    network: 'BBC One',
    startYear: 1992,
    years: '1992–1993',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/24/61916.jpg',
    note: '',
  },
  {
    id: 11303,
    tvmazeId: '19786',
    title: 'Fievel\'s American Tails',
    network: 'CBS',
    startYear: 1992,
    years: '1992',
    genres: ['Children', 'Family', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/69/174622.jpg',
    note: '',
  },
  {
    id: 11304,
    tvmazeId: '51103',
    title: 'Firm Friends',
    network: 'ITV1',
    startYear: 1992,
    years: '1992–1994',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/277/693914.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 471, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 334, "cliffhanger": 235, "ended": 13701}};
