window.pageShows = [
  {
    id: 1129,
    tvmazeId: '74881',
    title: 'Invincible Fight Girl',
    network: 'Adult Swim',
    startYear: 2024,
    years: '2024–',
    genres: ['Action'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/541/1354799.jpg',
    note: '',
  },
  {
    id: 1130,
    tvmazeId: '81435',
    title: 'Invisible',
    network: 'Disney+',
    startYear: 2024,
    years: '2024',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/547/1369126.jpg',
    note: '',
  },
  {
    id: 1131,
    tvmazeId: '80937',
    title: 'Iris',
    network: 'Canal+',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/544/1361048.jpg',
    note: '',
  },
  {
    id: 1132,
    tvmazeId: '80035',
    title: 'It\'s Florida, Man',
    network: 'HBO',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/600/1501487.jpg',
    note: '',
  },
  {
    id: 1133,
    tvmazeId: '74388',
    title: 'Jack and Joker',
    network: 'Channel 3',
    startYear: 2024,
    years: '2024–2025',
    genres: ['Action', 'Crime', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/529/1323840.jpg',
    note: '',
  },
  {
    id: 1134,
    tvmazeId: '79393',
    title: 'Jazz Ramsey: A K-9 Mystery checkifcancelled',
    network: 'Hallmark Mystery',
    startYear: 2024,
    years: '2024–',
    genres: ['Crime', 'Romance', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/534/1335299.jpg',
    note: '',
  },
  {
    id: 1135,
    tvmazeId: '74882',
    title: 'Jentry Chau vs. the Underworld',
    network: 'Netflix',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy', 'Action', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/546/1366269.jpg',
    note: '',
  },
  {
    id: 1136,
    tvmazeId: '65087',
    title: 'Joan',
    network: 'ITVX',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/537/1343526.jpg',
    note: '',
  },
  {
    id: 1137,
    tvmazeId: '63909',
    title: 'Joko Anwar\'s Nightmares and Daydreams',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Science-Fiction', 'Thriller', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/523/1308910.jpg',
    note: '',
  },
  {
    id: 1138,
    tvmazeId: '74883',
    title: 'Jurassic World: Chaos Theory',
    network: 'Netflix',
    startYear: 2024,
    years: '2024–2025',
    genres: ['Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/599/1498332.jpg',
    note: '',
  },
  {
    id: 1139,
    tvmazeId: '37114',
    title: 'Kaos',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Comedy', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/533/1332932.jpg',
    note: '',
  },
  {
    id: 1140,
    tvmazeId: '83943',
    title: 'Kayangan',
    network: 'Prime Video',
    startYear: 2024,
    years: '2024',
    genres: ['Action', 'Fantasy', 'Horror'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/563/1407699.jpg',
    note: '',
  },
  {
    id: 1141,
    tvmazeId: '74509',
    title: 'Kidnapped: The Chloe Ayling Story',
    network: 'BBC iPlayer',
    startYear: 2024,
    years: '2024',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/531/1329917.jpg',
    note: '',
  },
  {
    id: 1142,
    tvmazeId: '80194',
    title: 'Kiedy ślub?',
    network: 'Canal+',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/539/1349119.jpg',
    note: '',
  },
  {
    id: 1143,
    tvmazeId: '73424',
    title: 'Killer Soup',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/499/1248619.jpg',
    note: '',
  },
  {
    id: 1144,
    tvmazeId: '76134',
    title: 'Kimler Geldi Kimler Geçti',
    network: 'Netflix',
    startYear: 2024,
    years: '2024–',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/566/1415030.jpg',
    note: '',
  },
  {
    id: 1145,
    tvmazeId: '78887',
    title: 'Kindergarten: The Musical',
    network: 'Disney Junior',
    startYear: 2024,
    years: '2024–',
    genres: ['Children', 'Music'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/533/1334490.jpg',
    note: '',
  },
  {
    id: 1146,
    tvmazeId: '61066',
    title: 'Kite Man: Hell Yeah!',
    network: 'HBO Max',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy', 'Action', 'Adult'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: 'Max cancelled after one season; Kite Man and Golden Glider\'s Noonan\'s Bar storyline was unfinished.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/526/1315189.jpg',
    note: '',
  },
  {
    id: 1147,
    tvmazeId: '73184',
    title: 'Knight Flower',
    network: 'MBC',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/498/1246934.jpg',
    note: '',
  },
  {
    id: 1148,
    tvmazeId: '60808',
    title: 'Knuckles',
    network: 'Paramount+',
    startYear: 2024,
    years: '2024',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/510/1277082.jpg',
    note: '',
  },
  {
    id: 1149,
    tvmazeId: '73902',
    title: 'Komedi Kacau',
    network: 'Netflix',
    startYear: 2024,
    years: '2024–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/504/1261201.jpg',
    note: '',
  },
  {
    id: 1150,
    tvmazeId: '81370',
    title: 'Konflikti',
    network: 'MTV3',
    startYear: 2024,
    years: '2024–2025',
    genres: ['Drama', 'Action', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/547/1367820.jpg',
    note: '',
  },
  {
    id: 1151,
    tvmazeId: '74702',
    title: 'Kuvvetli Bir Alkış',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/506/1266389.jpg',
    note: '',
  },
  {
    id: 1152,
    tvmazeId: '73599',
    title: 'Kübra',
    network: 'Netflix',
    startYear: 2024,
    years: '2024',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/500/1250782.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 48, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
