window.pageShows = [
  {
    id: 3841,
    tvmazeId: '20596',
    title: 'Splitting Up Together',
    network: 'ABC',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/169/424614.jpg',
    note: '',
  },
  {
    id: 3842,
    tvmazeId: '25911',
    title: 'Spy Kids: Mission Critical',
    network: 'Netflix',
    startYear: 2018,
    years: '2018',
    genres: ['Action', 'Children', 'Espionage'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/203/509997.jpg',
    note: '',
  },
  {
    id: 3843,
    tvmazeId: '32780',
    title: 'Squinters',
    network: 'ABC iview',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/207/519716.jpg',
    note: '',
  },
  {
    id: 3844,
    tvmazeId: '35182',
    title: 'Star Falls',
    network: 'Nick App',
    startYear: 2018,
    years: '2018',
    genres: ['Comedy', 'Children', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/375/937813.jpg',
    note: '',
  },
  {
    id: 3845,
    tvmazeId: '39744',
    title: 'Star Trek: Short Treks',
    network: 'Paramount+',
    startYear: 2018,
    years: '2018–2020',
    genres: ['Drama', 'Action', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/566/1416407.jpg',
    note: '',
  },
  {
    id: 3846,
    tvmazeId: '39912',
    title: 'Star Wars Galaxy of Adventures',
    network: 'YouTube',
    startYear: 2018,
    years: '2018–2020',
    genres: ['Adventure', 'Children', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/176/440054.jpg',
    note: '',
  },
  {
    id: 3847,
    tvmazeId: '55009',
    title: 'Star Wars: Galaxy of Adventures Fun Facts',
    network: 'Disney XD',
    startYear: 2018,
    years: '2018–2020',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/311/778350.jpg',
    note: '',
  },
  {
    id: 3848,
    tvmazeId: '36483',
    title: 'Star Wars: Resistance',
    network: 'Disney Channel',
    startYear: 2018,
    years: '2018–2020',
    genres: ['Action', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/212/531887.jpg',
    note: '',
  },
  {
    id: 3849,
    tvmazeId: '30634',
    title: 'Stargate: Origins',
    network: 'Stargate Command',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/146/365955.jpg',
    note: '',
  },
  {
    id: 3850,
    tvmazeId: '36922',
    title: 'Starhunter: Redux',
    network: 'El Rey Network',
    startYear: 2018,
    years: '2018–2019',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/176/441049.jpg',
    note: '',
  },
  {
    id: 3851,
    tvmazeId: '37204',
    title: 'Stath Lets Flats',
    network: 'Channel 4',
    startYear: 2018,
    years: '2018–2021',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/321/803697.jpg',
    note: '',
  },
  {
    id: 3852,
    tvmazeId: '34577',
    title: 'Station 19',
    network: 'ABC',
    startYear: 2018,
    years: '2018–2024',
    genres: ['Drama', 'Action', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/507/1267852.jpg',
    note: '',
  },
  {
    id: 3853,
    tvmazeId: '34018',
    title: 'Step Up',
    network: 'STARZ',
    startYear: 2018,
    years: '2018–2022',
    genres: ['Drama', 'Music', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/422/1056824.jpg',
    note: '',
  },
  {
    id: 3854,
    tvmazeId: '30907',
    title: 'Strange Angel',
    network: 'Paramount+',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Drama', 'Science-Fiction', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/244/611810.jpg',
    note: '',
  },
  {
    id: 3855,
    tvmazeId: '32993',
    title: 'Strangers',
    network: 'ITV1',
    startYear: 2018,
    years: '2018',
    genres: ['Drama', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/168/422201.jpg',
    note: '',
  },
  {
    id: 3856,
    tvmazeId: '34266',
    title: 'Street Smart',
    network: 'Network 10',
    startYear: 2018,
    years: '2018',
    genres: ['Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/162/405329.jpg',
    note: '',
  },
  {
    id: 3857,
    tvmazeId: '40262',
    title: 'Strowlers',
    network: 'The Fantasy Network',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/403/1008401.jpg',
    note: '',
  },
  {
    id: 3858,
    tvmazeId: '34911',
    title: 'Subject: Dad',
    network: 'Three',
    startYear: 2018,
    years: '2018',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/454/1135958.jpg',
    note: '',
  },
  {
    id: 3859,
    tvmazeId: '58369',
    title: 'Subway Surfers: The Animated Series',
    network: 'YouTube',
    startYear: 2018,
    years: '2018–2019',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/367/917916.jpg',
    note: '',
  },
  {
    id: 3860,
    tvmazeId: '23470',
    title: 'Succession',
    network: 'HBO',
    startYear: 2018,
    years: '2018–2023',
    genres: ['Drama', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/453/1134275.jpg',
    note: '',
  },
  {
    id: 3861,
    tvmazeId: '26643',
    title: 'Summer Camp Island',
    network: 'Cartoon Network',
    startYear: 2018,
    years: '2018–2022',
    genres: ['Comedy', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/290/727019.jpg',
    note: '',
  },
  {
    id: 3862,
    tvmazeId: '71785',
    title: 'Super Dinosaur',
    network: 'Télé Toon',
    startYear: 2018,
    years: '2018–2019',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/480/1200458.jpg',
    note: '',
  },
  {
    id: 3863,
    tvmazeId: '39129',
    title: 'Superwog',
    network: 'ABC',
    startYear: 2018,
    years: '2018–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/171/429133.jpg',
    note: '',
  },
  {
    id: 3864,
    tvmazeId: '30890',
    title: 'Sweetbitter',
    network: 'STARZ',
    startYear: 2018,
    years: '2018–2019',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/198/496076.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 161, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 670, "cliffhanger": 0, "ended": 13760}};
