window.pageShows = [
  {
    id: 8233,
    tvmazeId: '11078',
    title: 'Legit',
    network: 'BBC One',
    startYear: 2006,
    years: '2006',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/37/93055.jpg',
    note: '',
  },
  {
    id: 8234,
    tvmazeId: '3249',
    title: 'Lewis',
    network: 'ITV1',
    startYear: 2006,
    years: '2006–2015',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/46/115217.jpg',
    note: '',
  },
  {
    id: 8235,
    tvmazeId: '850',
    title: 'Life on Mars',
    network: 'BBC One',
    startYear: 2006,
    years: '2006–2007',
    genres: ['Drama', 'Crime', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: 'BBC One gave the show a planned two-series run; the finale resolved Sam Tyler\'s mystery about whether 1973 was real.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/15855.jpg',
    note: '',
  },
  {
    id: 8236,
    tvmazeId: '73314',
    title: 'Little Lodgers',
    network: '5',
    startYear: 2006,
    years: '2006–2013',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/498/1246100.jpg',
    note: '',
  },
  {
    id: 8237,
    tvmazeId: '18040',
    title: 'Little Miss Jocelyn',
    network: 'BBC Two',
    startYear: 2006,
    years: '2006–2008',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/61/152934.jpg',
    note: '',
  },
  {
    id: 8238,
    tvmazeId: '12162',
    title: 'Live! Girls! Present Dogtown',
    network: 'BBC Three',
    startYear: 2006,
    years: '2006',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/40/102213.jpg',
    note: '',
  },
  {
    id: 8239,
    tvmazeId: '53734',
    title: 'Losing Gemma',
    network: 'ITV1',
    startYear: 2006,
    years: '2006',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/297/744207.jpg',
    note: '',
  },
  {
    id: 8240,
    tvmazeId: '4236',
    title: 'Love Monkey',
    network: 'CBS',
    startYear: 2006,
    years: '2006',
    genres: ['Drama', 'Comedy', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/20/50813.jpg',
    note: '',
  },
  {
    id: 8241,
    tvmazeId: '7064',
    title: 'Lovespring International',
    network: 'Lifetime',
    startYear: 2006,
    years: '2006',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/66067.jpg',
    note: '',
  },
  {
    id: 8242,
    tvmazeId: '35357',
    title: 'Low Winter Sun',
    network: 'Channel 4',
    startYear: 2006,
    years: '2006',
    genres: ['Action', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/149/372503.jpg',
    note: '',
  },
  {
    id: 8243,
    tvmazeId: '2208',
    title: 'Lucky Louie',
    network: 'HBO',
    startYear: 2006,
    years: '2006–2008',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/12/30566.jpg',
    note: '',
  },
  {
    id: 8244,
    tvmazeId: '69429',
    title: 'Lunar Jim',
    network: 'CBC',
    startYear: 2006,
    years: '2006–2012',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/465/1164994.jpg',
    note: '',
  },
  {
    id: 8245,
    tvmazeId: '7419',
    title: 'Maddigan\'s Quest',
    network: 'CBBC',
    startYear: 2006,
    years: '2006',
    genres: ['Drama', 'Family', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/68278.jpg',
    note: '',
  },
  {
    id: 8246,
    tvmazeId: '38273',
    title: 'Mater\'s Tall Tales',
    network: 'Disney Channel',
    startYear: 2006,
    years: '2006–2017',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/164/411651.jpg',
    note: '',
  },
  {
    id: 8247,
    tvmazeId: '12823',
    title: 'Mayo',
    network: 'BBC One',
    startYear: 2006,
    years: '2006',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/53/133766.jpg',
    note: '',
  },
  {
    id: 8248,
    tvmazeId: '78188',
    title: 'Me Too!',
    network: 'CBeebies',
    startYear: 2006,
    years: '2006–2008',
    genres: ['Drama', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 8249,
    tvmazeId: '73747',
    title: 'Me, Eloise',
    network: 'Starz Kids & Family',
    startYear: 2006,
    years: '2006',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/498/1245230.jpg',
    note: '',
  },
  {
    id: 8250,
    tvmazeId: '996',
    title: 'Men in Trees',
    network: 'ABC',
    startYear: 2006,
    years: '2006–2008',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/12/31440.jpg',
    note: '',
  },
  {
    id: 8251,
    tvmazeId: '18562',
    title: 'Merlin\'s Apprentice',
    network: 'Channel 4',
    startYear: 2006,
    years: '2006',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/63/158047.jpg',
    note: '',
  },
  {
    id: 8252,
    tvmazeId: '928',
    title: 'Metalocalypse',
    network: 'Adult Swim',
    startYear: 2006,
    years: '2006–2012',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/16168.jpg',
    note: '',
  },
  {
    id: 8253,
    tvmazeId: '710',
    title: 'Mickey Mouse Clubhouse',
    network: 'Disney Channel',
    startYear: 2006,
    years: '2006–2016',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/6/15020.jpg',
    note: '',
  },
  {
    id: 8254,
    tvmazeId: '4632',
    title: 'Modern Men',
    network: 'The WB',
    startYear: 2006,
    years: '2006',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/21/52527.jpg',
    note: '',
  },
  {
    id: 8255,
    tvmazeId: '11072',
    title: 'Modern Toss',
    network: 'Channel 4',
    startYear: 2006,
    years: '2006–2008',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/37/93018.jpg',
    note: '',
  },
  {
    id: 8256,
    tvmazeId: '33185',
    title: 'Monarch Cove',
    network: 'Lifetime',
    startYear: 2006,
    years: '2006',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/139/349436.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 344, "totalPages": 638, "perPage": 24, "stats": {"total": 15292, "cancelled": 334, "cliffhanger": 235, "ended": 13701}};
