window.pageShows = [
  {
    id: 12913,
    tvmazeId: '14860',
    title: 'Bump in the Night',
    network: 'ABC',
    startYear: 1994,
    years: '1994–1995',
    genres: ['Comedy', 'Adventure', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/50/125987.jpg',
    note: '',
  },
  {
    id: 12914,
    tvmazeId: '6992',
    title: 'Burke\'s Law',
    network: 'CBS',
    startYear: 1994,
    years: '1994–1995',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/34/86750.jpg',
    note: '',
  },
  {
    id: 12915,
    tvmazeId: '18343',
    title: 'Cadfael',
    network: 'ITV1',
    startYear: 1994,
    years: '1994–1998',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/62/155966.jpg',
    note: '',
  },
  {
    id: 12916,
    tvmazeId: '8429',
    title: 'Cardiac Arrest',
    network: 'BBC One',
    startYear: 1994,
    years: '1994–1996',
    genres: ['Drama', 'Comedy', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/30/75327.jpg',
    note: '',
  },
  {
    id: 12917,
    tvmazeId: '33669',
    title: 'Catherine Cookson\'s The Cinder Path',
    network: 'ITV1',
    startYear: 1994,
    years: '1994',
    genres: ['Drama', 'Romance', 'War'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/137/343166.jpg',
    note: '',
  },
  {
    id: 12918,
    tvmazeId: '19795',
    title: 'Catherine Cookson\'s The Dwelling Place',
    network: 'ITV1',
    startYear: 1994,
    years: '1994',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/203/507728.jpg',
    note: '',
  },
  {
    id: 12919,
    tvmazeId: '11403',
    title: 'Chandler & Co.',
    network: 'BBC One',
    startYear: 1994,
    years: '1994–1995',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/38/96119.jpg',
    note: '',
  },
  {
    id: 12920,
    tvmazeId: '5371',
    title: 'Chicago Hope',
    network: 'CBS',
    startYear: 1994,
    years: '1994–2000',
    genres: ['Drama', 'Medical'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/22/55458.jpg',
    note: '',
  },
  {
    id: 12921,
    tvmazeId: '46502',
    title: 'Chris Cross',
    network: 'ITV1',
    startYear: 1994,
    years: '1994–1995',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12922,
    tvmazeId: '27186',
    title: 'Christy',
    network: 'CBS',
    startYear: 1994,
    years: '1994–1995',
    genres: ['Drama', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/107/268183.jpg',
    note: '',
  },
  {
    id: 12923,
    tvmazeId: '10887',
    title: 'Class Act',
    network: 'ITV1',
    startYear: 1994,
    years: '1994–1995',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/36/91700.jpg',
    note: '',
  },
  {
    id: 12924,
    tvmazeId: '8862',
    title: 'Common as Muck',
    network: 'BBC One',
    startYear: 1994,
    years: '1994–1997',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/78454.jpg',
    note: '',
  },
  {
    id: 12925,
    tvmazeId: '7748',
    title: 'Creepy Crawlers',
    network: 'Syndication',
    startYear: 1994,
    years: '1994–1996',
    genres: ['Comedy', 'Action', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/28/71650.jpg',
    note: '',
  },
  {
    id: 12926,
    tvmazeId: '14684',
    title: 'Crocodile Shoes',
    network: 'BBC One',
    startYear: 1994,
    years: '1994–1996',
    genres: ['Drama', 'Music'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/49/124337.jpg',
    note: '',
  },
  {
    id: 12927,
    tvmazeId: '41672',
    title: 'Cyberkidz',
    network: 'Syndication',
    startYear: 1994,
    years: '1994',
    genres: ['Action', 'Fantasy', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/190/477402.jpg',
    note: '',
  },
  {
    id: 12928,
    tvmazeId: '45364',
    title: 'Daddy\'s Girls',
    network: 'CBS',
    startYear: 1994,
    years: '1994',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/598/1496065.jpg',
    note: '',
  },
  {
    id: 12929,
    tvmazeId: '36288',
    title: 'Dandelion Dead',
    network: 'ITV1',
    startYear: 1994,
    years: '1994',
    genres: ['Drama', 'Crime', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/153/383250.jpg',
    note: '',
  },
  {
    id: 12930,
    tvmazeId: '30033',
    title: 'Dead at 21',
    network: 'MTV',
    startYear: 1994,
    years: '1994',
    genres: ['Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/119/297770.jpg',
    note: '',
  },
  {
    id: 12931,
    tvmazeId: '45210',
    title: 'Dino Babies',
    network: 'BBC One',
    startYear: 1994,
    years: '1994–1996',
    genres: ['Comedy', 'Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/227/569247.jpg',
    note: '',
  },
  {
    id: 12932,
    tvmazeId: '58683',
    title: 'Downwardly Mobile',
    network: 'ITV1',
    startYear: 1994,
    years: '1994',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  },
  {
    id: 12933,
    tvmazeId: '414',
    title: 'Duckman: Private Dick/Family Man',
    network: 'USA Network',
    startYear: 1994,
    years: '1994–1997',
    genres: ['Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/2/6606.jpg',
    note: '',
  },
  {
    id: 12934,
    tvmazeId: '1981',
    title: 'Due South',
    network: 'CTV',
    startYear: 1994,
    years: '1994–1999',
    genres: ['Drama', 'Action', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/11/27960.jpg',
    note: '',
  },
  {
    id: 12935,
    tvmazeId: '7136',
    title: 'Earth 2',
    network: 'NBC',
    startYear: 1994,
    years: '1994–1995',
    genres: ['Drama', 'Adventure', 'Science-Fiction'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/26/66803.jpg',
    note: '',
  },
  {
    id: 12936,
    tvmazeId: '8175',
    title: 'Ellen',
    network: 'ABC',
    startYear: 1994,
    years: '1994–1998',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/29/74124.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 539, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
