window.pageShows = [
  {
    id: 5765,
    tvmazeId: '26637',
    title: 'Get Krack!n',
    network: 'ABC',
    startYear: 2017,
    years: '2017–2019',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/122/307339.jpg',
    note: '',
  },
  {
    id: 5766,
    tvmazeId: '17643',
    title: 'Get Shorty',
    network: 'MGM+',
    startYear: 2017,
    years: '2017–2019',
    genres: ['Drama', 'Comedy', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/214/535567.jpg',
    note: '',
  },
  {
    id: 5767,
    tvmazeId: '27855',
    title: 'Ghost Wars',
    network: 'Syfy',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Drama', 'Mystery', 'Supernatural'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/153/382579.jpg',
    note: '',
  },
  {
    id: 5768,
    tvmazeId: '20652',
    title: 'Ghosted',
    network: 'FOX',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Comedy', 'Mystery', 'Supernatural'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/121/302697.jpg',
    note: '',
  },
  {
    id: 5769,
    tvmazeId: '35440',
    title: 'Giants',
    network: 'YouTube',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/149/374167.jpg',
    note: '',
  },
  {
    id: 5770,
    tvmazeId: '30407',
    title: 'Ginger Snaps',
    network: 'ABC.com',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/120/300553.jpg',
    note: '',
  },
  {
    id: 5771,
    tvmazeId: '18100',
    title: 'Girlboss',
    network: 'Netflix',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/105/263664.jpg',
    note: '',
  },
  {
    id: 5772,
    tvmazeId: '17869',
    title: 'GLOW',
    network: 'Netflix',
    startYear: 2017,
    years: '2017–2019',
    genres: ['Drama', 'Comedy', 'Sports'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Netflix cancelled season four due to COVID-19; the wrestling women\'s Las Vegas evolution was left mid-arc.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/202/505923.jpg',
    note: '',
  },
  {
    id: 5773,
    tvmazeId: '32213',
    title: 'Go Back Couple',
    network: 'KBS2',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Family', 'Fantasy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/129/323339.jpg',
    note: '',
  },
  {
    id: 5774,
    tvmazeId: '54232',
    title: 'GO! Cartoons',
    network: 'VRV Select',
    startYear: 2017,
    years: '2017–2018',
    genres: [],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/300/751533.jpg',
    note: '',
  },
  {
    id: 5775,
    tvmazeId: '13634',
    title: 'Godless',
    network: 'Netflix',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Western'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/131/329494.jpg',
    note: '',
  },
  {
    id: 5776,
    tvmazeId: '25719',
    title: 'Gone',
    network: 'Universal Channel',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/172/430185.jpg',
    note: '',
  },
  {
    id: 5777,
    tvmazeId: '29646',
    title: 'Good Game',
    network: 'YouTube Premium',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy', 'Sports'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/400/1001182.jpg',
    note: '',
  },
  {
    id: 5778,
    tvmazeId: '17211',
    title: 'Great News',
    network: 'NBC',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/147/368720.jpg',
    note: '',
  },
  {
    id: 5779,
    tvmazeId: '17866',
    title: 'Greenhouse Academy',
    network: 'Netflix',
    startYear: 2017,
    years: '2017–2020',
    genres: ['Drama', 'Family', 'Mystery'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/148/372374.jpg',
    note: '',
  },
  {
    id: 5780,
    tvmazeId: '31434',
    title: 'Grown Folks',
    network: 'Bounce',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/247/618854.jpg',
    note: '',
  },
  {
    id: 5781,
    tvmazeId: '34287',
    title: 'Gudrun: The Viking Princess',
    network: 'BBC iPlayer',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Children', 'History'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/236/591653.jpg',
    note: '',
  },
  {
    id: 5782,
    tvmazeId: '16079',
    title: 'Guerrilla',
    network: 'Sky Go',
    startYear: 2017,
    years: '2017',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/104/261842.jpg',
    note: '',
  },
  {
    id: 5783,
    tvmazeId: '31397',
    title: 'Guilty Party',
    network: 'YouTube',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Drama'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/125/313363.jpg',
    note: '',
  },
  {
    id: 5784,
    tvmazeId: '25488',
    title: 'Gunpowder',
    network: 'BBC One',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'History'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/542/1355283.jpg',
    note: '',
  },
  {
    id: 5785,
    tvmazeId: '24873',
    title: 'Guyane',
    network: 'Canal+',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Drama', 'Adventure'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/97/244339.jpg',
    note: '',
  },
  {
    id: 5786,
    tvmazeId: '11266',
    title: 'Gypsy',
    network: 'Netflix',
    startYear: 2017,
    years: '2017',
    genres: ['Drama', 'Romance', 'Thriller'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/112/280512.jpg',
    note: '',
  },
  {
    id: 5787,
    tvmazeId: '28648',
    title: 'H8ters',
    network: 'fullscreen',
    startYear: 2017,
    years: '2017',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/114/285297.jpg',
    note: '',
  },
  {
    id: 5788,
    tvmazeId: '75013',
    title: 'Hacking High School',
    network: 'go90',
    startYear: 2017,
    years: '2017–2018',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    note: '',
  }
];
window.pageMetadata = {"page": 241, "totalPages": 719, "perPage": 24, "stats": {"total": 17240, "cancelled": 2244, "cliffhanger": 295, "ended": 12349}};
