window.pageShows = [
  {
    id: 3265,
    tvmazeId: '43917',
    title: 'Fate: The Winx Saga',
    network: 'Netflix',
    startYear: 2021,
    years: '2021–2022',
    genres: ['Drama', 'Action', 'Fantasy'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: true,
    cliffhangerNote: 'Netflix cancelled after two seasons; Bloom\'s dragon flame powers and the Blood Witches threat were mid-arc.',
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/419/1049814.jpg',
    note: '',
  },
  {
    id: 3266,
    tvmazeId: '49398',
    title: 'Fatma',
    network: 'Netflix',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/302/755246.jpg',
    note: '',
  },
  {
    id: 3267,
    tvmazeId: '53659',
    title: 'FBI: International',
    network: 'CBS',
    startYear: 2021,
    years: '2021–2025',
    genres: ['Drama', 'Crime'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/538/1345376.jpg',
    note: '',
  },
  {
    id: 3268,
    tvmazeId: '55417',
    title: 'Fear Street',
    network: 'Netflix',
    startYear: 2021,
    years: '2021–',
    genres: ['Horror', 'Mystery', 'Supernatural'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/566/1416180.jpg',
    note: '',
  },
  {
    id: 3269,
    tvmazeId: '55854',
    title: 'Feels Like Ishq',
    network: 'Netflix',
    startYear: 2021,
    years: '2021',
    genres: ['Comedy', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/339/849345.jpg',
    note: '',
  },
  {
    id: 3270,
    tvmazeId: '44457',
    title: 'Finding Alice',
    network: 'ITVX',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/462/1155364.jpg',
    note: '',
  },
  {
    id: 3271,
    tvmazeId: '58786',
    title: 'Firebite',
    network: 'AMC+',
    startYear: 2021,
    years: '2021–2022',
    genres: ['Fantasy', 'Supernatural'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/388/972428.jpg',
    note: '',
  },
  {
    id: 3272,
    tvmazeId: '41101',
    title: 'Firefly Lane',
    network: 'Netflix',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Drama', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/458/1147479.jpg',
    note: '',
  },
  {
    id: 3273,
    tvmazeId: '53835',
    title: 'Fires',
    network: 'ABC',
    startYear: 2021,
    years: '2021',
    genres: ['Drama'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/358/897038.jpg',
    note: '',
  },
  {
    id: 3274,
    tvmazeId: '47584',
    title: 'Fisk',
    network: 'ABC iview',
    startYear: 2021,
    years: '2021–',
    genres: ['Comedy'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/300/750346.jpg',
    note: '',
  },
  {
    id: 3275,
    tvmazeId: '51213',
    title: 'Flatbush Misdemeanors',
    network: 'Paramount+ with Showtime',
    startYear: 2021,
    years: '2021–2022',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/416/1040089.jpg',
    note: '',
  },
  {
    id: 3276,
    tvmazeId: '63215',
    title: 'Float',
    network: 'BBC iPlayer',
    startYear: 2021,
    years: '2021–',
    genres: ['Drama', 'Romance'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/416/1041886.jpg',
    note: '',
  },
  {
    id: 3277,
    tvmazeId: '44523',
    title: 'Folk med Ångest',
    network: 'Netflix',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Comedy', 'Mystery'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/382/956687.jpg',
    note: '',
  },
  {
    id: 3278,
    tvmazeId: '35951',
    title: 'Foundation',
    network: 'Apple TV',
    startYear: 2021,
    years: '2021–',
    genres: ['Drama', 'Science-Fiction', 'Mystery'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/573/1433544.jpg',
    note: '',
  },
  {
    id: 3279,
    tvmazeId: '46468',
    title: 'Frank of Ireland',
    network: 'Channel 4',
    startYear: 2021,
    years: '2021',
    genres: ['Comedy'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/301/752515.jpg',
    note: '',
  },
  {
    id: 3280,
    tvmazeId: '50214',
    title: 'Furia',
    network: 'Prime Video',
    startYear: 2021,
    years: '2021–2024',
    genres: ['Drama', 'Crime', 'Thriller'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/383/958182.jpg',
    note: '',
  },
  {
    id: 3281,
    tvmazeId: '61395',
    title: 'G.O.A.T.',
    network: 'Disney XD',
    startYear: 2021,
    years: '2021–',
    genres: [],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/402/1006769.jpg',
    note: '',
  },
  {
    id: 3282,
    tvmazeId: '51222',
    title: 'Gabby\'s Dollhouse',
    network: 'Netflix',
    startYear: 2021,
    years: '2021–',
    genres: ['Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/468/1172282.jpg',
    note: '',
  },
  {
    id: 3283,
    tvmazeId: '85130',
    title: 'Gary\'s Magic Fort',
    network: 'CBC Gem',
    startYear: 2021,
    years: '2021–2023',
    genres: ['Children'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/571/1428833.jpg',
    note: '',
  },
  {
    id: 3284,
    tvmazeId: '45617',
    title: 'Genera+ion',
    network: 'HBO Max',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Comedy', 'Family'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/322/805263.jpg',
    note: '',
  },
  {
    id: 3285,
    tvmazeId: '55787',
    title: 'Generazione 56k',
    network: 'Netflix',
    startYear: 2021,
    years: '2021',
    genres: ['Drama', 'Comedy', 'Romance'],
    status: 'ended',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
        imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/326/816621.jpg',
    note: '',
  },
  {
    id: 3286,
    tvmazeId: '57462',
    title: 'Get Rolling with Otis',
    network: 'Apple TV',
    startYear: 2021,
    years: '2021–',
    genres: ['Children'],
    status: 'cancelled',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/355/889422.jpg',
    note: '',
  },
  {
    id: 3287,
    tvmazeId: '58277',
    title: 'GhostForce',
    network: 'Disney XD',
    startYear: 2021,
    years: '2021–',
    genres: ['Comedy', 'Action', 'Children'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/368/920535.jpg',
    note: '',
  },
  {
    id: 3288,
    tvmazeId: '46573',
    title: 'Ghosts',
    network: 'CBS',
    startYear: 2021,
    years: '2021–',
    genres: ['Comedy', 'Supernatural'],
    status: 'running',
    cancelledAfterSeason: null,
    totalSeasons: null,
    cliffhanger: false,
    cliffhangerNote: null,
    imageUrl: 'https://static.tvmaze.com/uploads/images/medium_portrait/590/1475093.jpg',
    note: '',
  }
];
window.pageMetadata = {"page": 137, "totalPages": 722, "perPage": 24, "stats": {"total": 17316, "cancelled": 491, "cliffhanger": 239, "ended": 15081}};
